- core/src/main/java/org/apache/accumulo/core/cli/ClientOpts.java
- core/src/main/java/org/apache/accumulo/core/client/impl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/client/mock/MockConfiguration.java
- core/src/main/java/org/apache/accumulo/core/conf/AccumuloConfiguration.java
- core/src/main/java/org/apache/accumulo/core/conf/ConfigurationCopy.java
- core/src/main/java/org/apache/accumulo/core/conf/DefaultConfiguration.java
- core/src/main/java/org/apache/accumulo/core/conf/SiteConfiguration.java
- core/src/test/java/org/apache/accumulo/core/client/impl/ClientContextTest.java
- core/src/test/java/org/apache/accumulo/core/conf/DefaultConfigurationTest.java
- core/src/test/java/org/apache/accumulo/core/conf/ObservableConfigurationTest.java
- core/src/test/java/org/apache/accumulo/core/conf/SiteConfigurationTest.java
- server/base/src/main/java/org/apache/accumulo/server/conf/NamespaceConfiguration.java
- server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java
- server/base/src/main/java/org/apache/accumulo/server/conf/ZooCachePropertyAccessor.java
- server/base/src/main/java/org/apache/accumulo/server/conf/ZooConfiguration.java
- server/base/src/main/java/org/apache/accumulo/server/fs/PreferredVolumeChooser.java
- server/base/src/test/java/org/apache/accumulo/server/conf/NamespaceConfigurationTest.java
- server/base/src/test/java/org/apache/accumulo/server/conf/TableConfigurationTest.java
- server/base/src/test/java/org/apache/accumulo/server/conf/ZooCachePropertyAccessorTest.java
- server/base/src/test/java/org/apache/accumulo/server/util/FileUtilTest.java
- test/src/test/java/org/apache/accumulo/test/util/CertUtils.java
* Replace internal PropertyFilter with Guava's Predicate.
* Preserve MockConfiguration public API by deprecating PropertyFilter
> ACCUMULO-3714 Replace PropertyFilter

- server/tserver/src/main/java/org/apache/accumulo/tserver/compaction/EverythingCompactionStrategy.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- test/src/main/java/org/apache/accumulo/test/HardListIterator.java
- test/src/test/java/org/apache/accumulo/test/TableOperationsIT.java
Putting this out for review to see if I am on the right track; I don't expect it to be perfect on the first shot.  I'd like to redo this for 1.6.3 if it looks good.  Open to suggestions on design and on testing compacting empty tablets.
Removed/modified lines in Tablet that stop construction of the SKVI stack when a tablet has no data.
Includes an iterator that generates data, for testing purposes. Includes one integration test. Not sure about MiniAccumulo.
> ACCUMULO-3645 Run iterators at major compaction on empty tablets

- .gitignore
- minicluster/pom.xml
- minicluster/src/main/java/org/apache/accumulo/minicluster/MiniAccumuloConfig.java
- minicluster/src/main/java/org/apache/accumulo/minicluster/MiniAccumuloRunner.java
- minicluster/src/main/java/org/apache/accumulo/minicluster/impl/MiniAccumuloClusterImpl.java
- minicluster/src/main/java/org/apache/accumulo/minicluster/impl/MiniAccumuloConfigImpl.java
- minicluster/src/test/java/org/apache/accumulo/minicluster/MiniAccumuloClusterExistingZooKeepersTest.java
- pom.xml
This creates a new MAC config option `existingZooKeepers` that can be optionally set to a ZK connection string (e.g., "localhost:2181"). If this is set, the MAC will not spin up a ZK process nor create a ZK config directory. Since the same ZK instance can now be used repeatedly, any existing Accumulo instances with the same instance name are removed.
> ACCUMULO-3000: Added config option and impl to use existing ZooKeeper

- docs/src/main/asciidoc/chapters/administration.txt
- shell/src/main/java/org/apache/accumulo/shell/commands/ActiveScanIterator.java
This adds an example of how to configure another SpanReceiver for tracing by the Accumulo server and by the client. Also documents the format of the trace table and some utilities.
> ACCUMULO-3971 Better doc for tracing

- server/base/src/main/java/org/apache/accumulo/server/util/FileSystemMonitor.java
- server/base/src/test/java/org/apache/accumulo/server/util/FileSystemMonitorTest.java
By too aggressively monitoring filesystem mounts, we can actually
make accumulo unstable. Try to restrict what we monitor.
> ACCUMULO-4080 Only check /dev/ entries and FSes in [ext3, ext4, xfs].

- docs/src/main/latex/accumulo_user_manual/accumulo_user_manual.tex
This is a best effort to pass scrutiny. Personally, I find this confusing... references to software guarantees which don't apply to docs, confusing reference to "using this file", etc. Additional clarification was requested in LEGAL-235, but this is an attempt to make progress in the interim.
> ACCUMULO-4144 Add copyright/license info to manual

- core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java
- core/src/main/java/org/apache/accumulo/core/util/shell/commands/DeleteRowsCommand.java
- core/src/main/java/org/apache/accumulo/core/util/shell/commands/MergeCommand.java
- core/src/main/java/org/apache/accumulo/core/util/shell/commands/OptUtil.java
- core/src/main/java/org/apache/accumulo/core/util/shell/commands/ScanCommand.java
- core/src/test/java/org/apache/accumulo/core/util/shell/commands/CompactCommandTest.java
- core/src/test/java/org/apache/accumulo/core/util/shell/commands/DeleteManyCommandTest.java
- core/src/test/java/org/apache/accumulo/core/util/shell/commands/DeleteRowsCommandTest.java
- core/src/test/java/org/apache/accumulo/core/util/shell/commands/FlushCommandTest.java
- core/src/test/java/org/apache/accumulo/core/util/shell/commands/MergeCommandTest.java
- core/src/test/java/org/apache/accumulo/core/util/shell/commands/ScanCommandTest.java
It was wrong for FlushCommand and CompactCommand.  In the process of
refactoring, the following was accomplished:
- Change the description in the OptUtil.startRowOpt to be (NOT) inclusive.
- Use OptUtil.startRowOpt in CompactCommand, MergeCommand and FlushCommand.
- Refactor the DeleteRowCommand to use the OptUtil.startRowOpt method.
- Refactor ScanCommand to override the description to say it is inclusive.
Also updated the javadoc from a potential cut and paste on TableOperations.
A little mixed on the usefulness of the Unit Tests for these.  They may be
brittle, but perhaps they would alert if someone changed the way one command
worked without looking at the others.
> ACCUMULO-4138 Fix the description of -b options

- core/src/main/java/org/apache/accumulo/core/client/security/tokens/KerberosToken.java
`KerberosToken(String, File, boolean)` is deprecated in favor of `KerberosToken(String, File)`.
The boolean flag would log in the requested user with Hadoop's `UserGroupInformation` class. This
changed global state about who the active user was. In a multi-user environment, this potentially
made little sense as other users could overwrite eachother.
This patch includes a convenience constructor that doesn't have any side effects, but has the same
semantics as logging in a user with a keytab.
> ACCUMULO-4348 Deprecate KerberosToken constructor with side effects

- test/src/test/java/org/apache/accumulo/harness/SharedMiniClusterIT.java
- test/src/test/java/org/apache/accumulo/test/ArbitraryTablePropertiesIT.java
- test/src/test/java/org/apache/accumulo/test/CreateTableWithNewTableConfigIT.java
- test/src/test/java/org/apache/accumulo/test/ShellServerIT.java
- test/src/test/java/org/apache/accumulo/test/SplitCancelsMajCIT.java
- test/src/test/java/org/apache/accumulo/test/functional/CleanUpIT.java
- test/src/test/java/org/apache/accumulo/test/functional/DeletedTablesDontFlushIT.java
- test/src/test/java/org/apache/accumulo/test/functional/SimpleMacIT.java
- test/src/test/java/org/apache/accumulo/test/functional/TabletStateChangeIteratorIT.java
- test/src/test/java/org/apache/accumulo/test/proxy/SimpleProxyBase.java
- test/src/test/java/org/apache/accumulo/test/proxy/TBinaryProxyIT.java
- test/src/test/java/org/apache/accumulo/test/proxy/TCompactProxyIT.java
- test/src/test/java/org/apache/accumulo/test/proxy/TJsonProtocolProxyIT.java
- test/src/test/java/org/apache/accumulo/test/proxy/TTupleProxyIT.java
- test/src/test/java/org/apache/accumulo/test/replication/StatusCombinerMacIT.java
Refactored SharedMiniClusterIT a little bit to work around the
static initialization of the MAC which previously would not have
allowed tests to control how MAC is configured. This has the downside
of forcing new tests to remember to define BeforeClass and AfterClass
annotated methods which call the corresponding methods on SharedMiniClusterIT.
> ACCUMULO-4361 Configure ShellServerIT to run with one tserver

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/tablet/DatafileManagerTest.java
Created the new property table.compaction.minor.merge.file.size.max with default value of 50M. Looking for feedback whether 50M is an appropriate default value.
Modified Tablet and DatafileManager to prevent minor compaction merge files from being larger than the max set in the new property.
Created DatafileManagerTest to test 3 different scenarios in reserveMergingMinorCompactionFile.
> ACCUMULO-1055: Configurable maximum size in which to perform merging minor compactions

- core/src/main/java/org/apache/accumulo/core/file/blockfile/impl/CachableBlockFile.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/BCFile.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/BoundedRangeFileInputStream.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/MultiThreadedRFileTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/RFileTest.java
- core/src/test/resources/log4j.properties
Added synchronization around the available() call in the BoundedRangeFileInputStream to allow RFile.Reader deepcopies to be usable in separate threads.
> ACCUMULO-4391 Source deepcopies cannot be used safely in separate threads in tserver

- _includes/nav.html
- _layouts/post.html
- index.md
It's causing page not found error in production.
> Remove slash from links to news archive

- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
- shell/src/main/java/org/apache/accumulo/shell/Shell.java
- shell/src/main/java/org/apache/accumulo/shell/ShellOptionsJC.java
Fixes in a couple places for ACCUMULO-4505. Shell was getting the site instance config (which read accumulo-site) when everything it needed was already in ClientConfig. ShellOptionsJC was ignoring zookeeper properties passed in by the user.  The Initialize class is not executed when the Shell is run but a static initialization of Zookeeper was forcing a read of accumulo-site when the class was loaded by getExecutables in Main.
> ACCUMULO-4505: Fix for Shell erroneously reading accumulo-site.xml

- core/src/test/java/org/apache/accumulo/core/data/RangeTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/BlockIndexTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/CreateCompatTestFile.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/KeyShortenerTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/MultiThreadedRFileTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/RFileMetricsTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/RFileTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/RelativeKeyTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/AggregatingIteratorTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/FirstEntryInRowTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/IteratorUtilTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/system/ColumnFamilySkippingIteratorTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/system/ColumnFilterTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/system/DeletingIteratorTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/system/MultiIteratorTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/system/SourceSwitchingIteratorTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/BigDecimalCombinerTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/ColumnSliceFilterTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/CombinerTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/IndexedDocIteratorTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/RegExFilterTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/RowDeletingIteratorTest.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/CheckTabletMetadataTest.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/InMemoryMapTest.java
- test/src/main/java/org/apache/accumulo/test/NativeMapPerformanceTest.java
- test/src/main/java/org/apache/accumulo/test/functional/NativeMapIT.java
While trying to learn the internals of Accumulo, I found a lot of the method names in Test to be confusing. I think Tests are an under utilized learning tool for newcomers. Many method names in Test were clearly chosen for brevity rather than clarity which I think is a bad habit that doesn't help new Accumulo developers.
This PR is for 2.0 (branch with the most changes). I have similar changes for 1.7 and 1.8 branches. Tests should be the same functionally but I wanted other devs to see the changes and get their opinions.
> ACCUMULO-4525: Replace meaningless method names

- assemble/bin/accumulo
- docs/src/main/asciidoc/chapters/kerberos.txt
* Added documentation for configuring Kerberos using 2.0.0 scripts
* Removed kerberos config file references from accumulo command as
these can be added by user to JAVA_OPTS in accumulo-env.sh
> ACCUMULO-4594 Fix Kerberos documentation

- TESTING.md
- assemble/bin/accumulo
- assemble/bin/accumulo-cluster
- assemble/bin/accumulo-service
- assemble/bin/accumulo-util
- minicluster/src/main/java/org/apache/accumulo/cluster/standalone/StandaloneAccumuloCluster.java
- minicluster/src/main/java/org/apache/accumulo/cluster/standalone/StandaloneClusterControl.java
- minicluster/src/test/java/org/apache/accumulo/cluster/standalone/StandaloneClusterControlTest.java
- test/src/main/java/org/apache/accumulo/harness/AccumuloClusterHarness.java
- test/src/main/java/org/apache/accumulo/harness/conf/StandaloneAccumuloClusterConfiguration.java
* Limited use of bash env variables in standalone cluster testing
* Fixed standalone cluster testing sow that it work with Accumulo 2.0
script changes
* Users now only need to configure Accumulo conf directory on client
> ACCUMULO-4596 Improvements to standalone cluster testing

- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeManager.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeManagerImpl.java
- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
Simple fix for ACCUMULO-2806.  I had overcomplicated the issue by attempting to set the permissions independently for each directory under /accumulo but I think just securing permissions at the top will work fine. 
My question for the community, will this change break/complicate 3rd party tools?
> ACCUMULO-2806: changed permissions of /accumulo to 700

- core/src/main/java/org/apache/accumulo/core/iterators/FirstEntryInRowIterator.java
- core/src/main/java/org/apache/accumulo/core/iterators/TypedValueCombiner.java
- core/src/test/java/org/apache/accumulo/core/iterators/FirstEntryInRowIteratorTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/CombinerTest.java
Updated iterators mentioned in [ACCUMULO-3521](https://issues.apache.org/jira/browse/ACCUMULO-3521), added tests to cover untested methods and deprecated OrIterator.  Couldn't find IteratorUtil.getMaxPriority and .findIterator methods.  StatsCombiner is in examples.
> ACCUMULO-3521: minor improvements to iterators

- core/pom.xml
- fate/pom.xml
- iterator-test-harness/pom.xml
- maven-plugin/pom.xml
- minicluster/pom.xml
- pom.xml
- proxy/pom.xml
- server/base/pom.xml
- server/gc/pom.xml
- server/master/pom.xml
- server/monitor/pom.xml
- server/tracer/pom.xml
- server/tserver/pom.xml
- shell/pom.xml
- start/pom.xml
- test/pom.xml
* Build will fail if module has missing or unused dependency
* Plugin is conifigured to ignore certain depedencies in main pom.xml
* Fixed all missing or unused dependencies in build
> ACCUMULO-4618 Enforce dependency analysis during build

- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeChooserEnvironment.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeManager.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeManagerImpl.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeUtil.java
- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
- server/base/src/main/java/org/apache/accumulo/server/util/FileUtil.java
- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
- server/base/src/main/java/org/apache/accumulo/server/util/RandomizeVolumes.java
- server/base/src/test/java/org/apache/accumulo/server/fs/VolumeManagerImplTest.java
- server/master/src/main/java/org/apache/accumulo/master/Master.java
- server/master/src/main/java/org/apache/accumulo/master/TabletGroupWatcher.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/ChooseDir.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/PopulateMetadataTable.java
- server/master/src/test/java/org/apache/accumulo/master/tableOps/ImportTableTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/TabletServerSyncCheckTest.java
Adds some improvements to the VolumeChooserEnvironment, and creates a "logger" scope so that VolumeChooser implementations can be configured to choose volumes for WALs. (Expect an implementation of such a VolumeChooser in an upcoming PR. I've separated it to make it easier to review.)
This PR depends on #250  (also included in this PR).
> ACCUMULO-4084 ACCUMULO-4085 volumechooserenv

- core/src/main/java/org/apache/accumulo/core/client/mock/MockScannerBase.java
- core/src/main/java/org/apache/accumulo/core/iterators/Filter.java
- core/src/main/java/org/apache/accumulo/core/iterators/FirstEntryInRowIterator.java
- core/src/main/java/org/apache/accumulo/core/iterators/IteratorUtil.java
- core/src/main/java/org/apache/accumulo/core/iterators/ServerFilter.java
- core/src/main/java/org/apache/accumulo/core/iterators/ServerSkippingIterator.java
- core/src/main/java/org/apache/accumulo/core/iterators/ServerWrappingIterator.java
- core/src/main/java/org/apache/accumulo/core/iterators/SynchronizedServerFilter.java
- core/src/main/java/org/apache/accumulo/core/iterators/system/ColumnFamilySkippingIterator.java
- core/src/main/java/org/apache/accumulo/core/iterators/system/ColumnQualifierFilter.java
- core/src/main/java/org/apache/accumulo/core/iterators/system/DeletingIterator.java
- core/src/main/java/org/apache/accumulo/core/iterators/system/SynchronizedIterator.java
- core/src/main/java/org/apache/accumulo/core/iterators/system/VisibilityFilter.java
- core/src/main/java/org/apache/accumulo/core/iterators/user/VersioningIterator.java
- core/src/main/java/org/apache/accumulo/core/iterators/user/VisibilityFilter.java
- core/src/test/java/org/apache/accumulo/core/iterators/system/ColumnFilterTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/system/VisibilityFilterTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/FilterTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/TransformingIteratorTest.java
- server/base/src/main/java/org/apache/accumulo/server/problems/ProblemReportingIterator.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/InMemoryMap.java
- test/src/main/java/org/apache/accumulo/test/performance/scan/CollectTabletStats.java
Applied the changes from the patch submitted by Adam Fuchs on [ACCUMULO-3079](https://issues.apache.org/jira/browse/ACCUMULO-3079) to master. This PR is to bring these changes back into discussion.  Created JMH benchmark tests [here](https://github.com/milleruntime/jmh-test/blob/master/src/main/java/org/sample/MyBenchmark.java).  I tried to isolate the tests to only the system iterators acting on data in memory.  
I have attached the results from the benchmark tests. 
[jmh-accumulo-benchmark-results.txt](https://github.com/apache/accumulo/files/906333/jmh-accumulo-benchmark-results.txt)
The JMH tests can be built and run from [here](https://github.com/milleruntime/jmh-test). After cloning the repo, simply run:
`mvn clean install`
`java -jar target/benchmarks.jar -i 100 -f 1`
> Discuss ACCUMULO-3079: collapsing the iterator stack to improve performance

- core/src/main/java/org/apache/accumulo/core/client/impl/OfflineIterator.java
- core/src/main/java/org/apache/accumulo/core/client/mock/MockScannerBase.java
- core/src/main/java/org/apache/accumulo/core/iterators/Filter.java
- core/src/main/java/org/apache/accumulo/core/iterators/FirstEntryInRowIterator.java
- core/src/main/java/org/apache/accumulo/core/iterators/system/ColumnFamilySkippingIterator.java
- core/src/main/java/org/apache/accumulo/core/iterators/system/ColumnQualifierFilter.java
- core/src/main/java/org/apache/accumulo/core/iterators/system/DeletingIterator.java
- core/src/main/java/org/apache/accumulo/core/iterators/system/VisibilityFilter.java
- core/src/main/java/org/apache/accumulo/core/iterators/user/VersioningIterator.java
- core/src/main/java/org/apache/accumulo/core/iterators/user/VisibilityFilter.java
- core/src/test/java/org/apache/accumulo/core/iterators/system/ColumnFilterTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/system/VisibilityFilterTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/FilterTest.java
- server/base/src/main/java/org/apache/accumulo/server/problems/ProblemReportingIterator.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/InMemoryMap.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java
- test/src/main/java/org/apache/accumulo/test/performance/scan/CollectTabletStats.java
Back ported some of the improvements from ACCUMULO-3079 and PR #244 to 1.7 (and will also merge with 1.8).  These improvements just include internal changes and leave out the new optimized server iterators introduced in 2.0.  
This PR is mainly a sanity check since there are a decent number of changes but I would also still accept any new feedback.
> ACCUMULO-4636 system iterator improvements for 1.7

- INSTALL.md
As a background for this PR, the text in INSTALL.md now exists on in Accumulo documentation on project website at.
https://accumulo.apache.org/docs/unreleased/getting-started/quick-install
These changes are due to that mirroring. We now have quick & in-depth installation instructions.  In-depth is install instructions from user manual.
https://accumulo.apache.org/docs/unreleased/administration/in-depth-install
I also tried to address some confusion in INSTALL.md brought up by @vivekvaidya
> ACCUMULO-4646 Updates to INSTALL.md

- core/src/main/java/org/apache/accumulo/core/conf/ConfigurationTypeHelper.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/base/src/main/java/org/apache/accumulo/server/fs/PerTableVolumeChooser.java
- server/base/src/main/java/org/apache/accumulo/server/fs/PreferredVolumeChooser.java
- server/base/src/main/java/org/apache/accumulo/server/fs/RandomVolumeChooser.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeChooser.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeChooserEnvironment.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeManagerImpl.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeUtil.java
- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
- server/base/src/main/java/org/apache/accumulo/server/util/RandomizeVolumes.java
- server/base/src/test/java/org/apache/accumulo/server/fs/PerTableVolumeChooserTest.java
- server/base/src/test/java/org/apache/accumulo/server/fs/PreferredVolumeChooserTest.java
- server/base/src/test/java/org/apache/accumulo/server/fs/VolumeManagerImplTest.java
- server/master/src/main/java/org/apache/accumulo/master/Master.java
- server/master/src/main/java/org/apache/accumulo/master/TabletGroupWatcher.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/ChooseDir.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/PopulateMetadataTable.java
- server/master/src/test/java/org/apache/accumulo/master/tableOps/ImportTableTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/tablet/RootFilesTest.java
- test/src/main/java/org/apache/accumulo/test/ShellConfigIT.java
- test/src/main/java/org/apache/accumulo/test/VolumeChooserFailureIT.java
- test/src/main/java/org/apache/accumulo/test/VolumeChooserIT.java
Implement a better fallback mechanism when the user's selected
VolumeChooser implementation cannot be loaded or is not specified.
Handles all such cases, including non-table scopes (logger), and
per-table scopes.
****
Note: this isn't quite ready for merging, but since I'm trying to proxy code written by somebody else, I think it'd be helpful to have it inspected/reviewed by more eyes. I tried to run the tests, but they hung (in Eclipse, at least). Keep in mind that this has been rebase'd from an older version of Accumulo, and probably needs a bit more work.
The goal of this is described in [ACCUMULO-4086][1] and its parent task, but all I have is the implementation, and it's not entirely clear what the best design is, in order to make sure this particular implementation matches that …
> ACCUMULO-4086 Improve volume chooser fallback

- core/src/main/java/org/apache/accumulo/core/file/rfile/VisMetricsGatherer.java
- fate/src/main/java/org/apache/accumulo/fate/ZooStore.java
- fate/src/main/java/org/apache/accumulo/fate/util/UtilWaitThread.java
- minicluster/src/main/java/org/apache/accumulo/minicluster/MiniAccumuloRunner.java
- proxy/src/main/java/org/apache/accumulo/proxy/Proxy.java
Created code to remove Guava dependencies which are still beta in release 23:
com.google.common.util.concurrent.Uninterruptibles
com.google.common.io.Files
com.google.common.hash.HashCode;
com.google.common.hash.HashFunction;
com.google.common.hash.Hashing;
> ACCUMULO-4702 Removed Beta Guava dependencies

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactionRunner.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
ACCUMULO-2968: Axe TabletServer.majorCompactorDisabled
Removed references to majorCompatorDisabled variable defined in
accumulo/tserver/TabletServer.java.  This private variable was
defined as 'false' and never modified in source and additionally
no means were provided to alter the value in the code.
Several locations within TabletServer.java where updated. This
included a couple of 'if' statement that would never be executed as well
as some return statement where a constant value of true was
unnecessarily included.
There was one reference each within CompationRunner.java and Tablet.java
which were removed also.
The change of most note is probably the while loop within the run method
of TableServer. Previously the while check read:
while(!majorCompatorDisabled)....
whereas now it reads: …
> ACCUMULO-2968: Axe TabletServer.majorCompactorDisabled

- core/src/main/java/org/apache/accumulo/core/util/Pair.java
- core/src/test/java/org/apache/accumulo/core/util/PairTest.java
ACCUMULO-4722 Use Objects.equals() in Pair equals method
Removed private equals method in Pairs class and instead made use of the
java.util.Objects.equals method. Updated the test class to verify
several variations of the equals method.
> ACCUMULO-4722 Use Objects.equals in Pairs class"

- shell/src/test/java/org/apache/accumulo/shell/PasswordConverterTest.java
Remove use of deprecated JCommander constructors, which are new warnings
after the previous ACCUMULO-4703 commits updating the JCommander
version.
> ACCUMULO-4703 Fix warnings for newer JCommander

- test/src/main/java/org/apache/accumulo/test/performance/thrift/NullTserver.java
Remove unused import from previous merge commit for ACCUMULO-4702. Also,
organized imports according to project conventions (formatting and
import order are normally skipped for this file, since it unfortunately
matches the package naming conventions for generated thrift code).
> ACCUMULO-4702 Fix unused import from previous merge

- iterator-test-harness/src/main/java/org/apache/accumulo/iteratortest/IteratorTestOutput.java
- pom.xml
- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
Upgrade to newest formatter, so javadocs are properly formatted.
> ACCUMULO-4703 Use formatter-maven-plugin 2.1.0.RC1

- core/src/main/java/org/apache/accumulo/core/data/Value.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/VersioningIteratorTest.java
(Note: This PR builds on #312; diffs of NullTServer may show up here, but are part of that PR, not this one.)
Add a method to compare Value objects with byte arrays, and stop
supporting the ability to compare Value objects with byte arrays using
the existing equals(Object) method, which is unsafe and should only be
used to compare with other Value instances.
> ACCUMULO-4726 Add Value.contentEquals(byte[]) method

- server/base/src/main/java/org/apache/accumulo/server/metrics/Metrics2ThriftMetrics.java
- server/base/src/main/java/org/apache/accumulo/server/metrics/MetricsSystemHelper.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/master/src/main/java/org/apache/accumulo/master/Master.java
- server/master/src/main/java/org/apache/accumulo/master/metrics/Metrics2ReplicationMetrics.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- server/tracer/src/main/java/org/apache/accumulo/tracer/TraceServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/Metrics2TabletServerMetrics.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/Metrics2TabletServerMinCMetrics.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/Metrics2TabletServerScanMetrics.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/Metrics2TabletServerUpdateMetrics.java
Create process name from system property -Dapp and instance from -Daccumulo.service.instance if applicable
By adding the ProcessName tag to the MetricsRegistry, this tag will be added to all created metrics,
allowing metrics consumers to deconflict metrics from different service instances
> ACCUMULO-4693: Add instance-specific ProcessName to Hadoop2 metrics

- core/src/main/java/org/apache/accumulo/core/client/admin/NewTableConfiguration.java
- core/src/main/java/org/apache/accumulo/core/client/impl/TableOperationsHelper.java
- core/src/main/java/org/apache/accumulo/core/client/impl/TableOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/util/LocalityGroupUtil.java
- test/src/main/java/org/apache/accumulo/test/NewConfigurationTestIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ReadWriteIT.java
- test/src/main/resources/log4j.properties
ACCUMULO-4732 No APIs to configure iterators or locality groups for new tables
Added several methods to the NewTableConfiguration class to allow for the configuration of locality groups
and the attachment of iterators prior table creation.
Modified/created 5 files:
NewTableConfiguration.java now has a setLocalityGroups, and two variations of an attachIterator method as
well as an additional helper method for checking iterator conflicts.
There is a new class, NewConfigurationTestIT.java to verify the updates made to the API.
An ensureNonOverlappingGroups functionality was extracted from TableOperationsImpl.java and added to
LocalityGroupUtil.java instead to allow for use by both NewTableConfiguration and TableOperationsImpl.
ReadWriteIT.java has an additional locality group test as well.
> ACCUMULO-4732 No APIs to configure iterators or locality groups for new tables

- docs/src/main/asciidoc/chapters/table_configuration.txt
ACCUMULO-4328 importtable and exporttable deserve descriptions in the user manual
Updated 1.8 and 2.0 user manual documentation to include the import/export example within the
documentation directly rather than requiring a user to click away from the manual pages to a
different project (i.e., the accumulo-examples project) for that information.
> ACCUMULO-4528 Add import/export table info to docs

- core/src/test/resources/crypto-on-accumulo-site.xml
ACCUMULO-3361 CryptoTest creates files in /tmp/tmp
Updated the crypto-on-accumulo-site.xml resource file to use target/dfs rather than /tmp for
location of instance.dfs.dir in cryptoTest. As a result the test.secret.key is now written
underneath the target directory rather than /tmp.
> ACCUMULO-3361 CryptoTest creates files in /tmp/tmp

- core/src/main/java/org/apache/accumulo/core/client/impl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/client/mock/MockConfiguration.java
- core/src/main/java/org/apache/accumulo/core/conf/AccumuloConfiguration.java
- core/src/main/java/org/apache/accumulo/core/conf/ConfigurationCopy.java
- core/src/main/java/org/apache/accumulo/core/conf/DefaultConfiguration.java
- core/src/main/java/org/apache/accumulo/core/conf/SiteConfiguration.java
- core/src/main/java/org/apache/accumulo/core/security/crypto/CryptoModuleFactory.java
- core/src/test/java/org/apache/accumulo/core/conf/AccumuloConfigurationTest.java
- fate/src/main/java/org/apache/accumulo/fate/zookeeper/ZooCache.java
- server/base/src/main/java/org/apache/accumulo/server/conf/NamespaceConfiguration.java
- server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java
- server/base/src/main/java/org/apache/accumulo/server/conf/ZooConfiguration.java
- server/base/src/main/java/org/apache/accumulo/server/conf/ZooConfigurationFactory.java
- server/base/src/test/java/org/apache/accumulo/server/conf/ZooConfigurationFactoryTest.java
- server/base/src/test/java/org/apache/accumulo/server/master/balancer/BaseHostRegexTableLoadBalancerTest.java
- server/base/src/test/java/org/apache/accumulo/server/master/balancer/HostRegexTableLoadBalancerTest.java
- server/base/src/test/java/org/apache/accumulo/server/rpc/TCredentialsUpdatingInvocationHandlerTest.java
- server/master/src/main/java/org/apache/accumulo/master/Master.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- shell/src/main/java/org/apache/accumulo/shell/Shell.java
- start/src/main/java/org/apache/accumulo/start/classloader/vfs/ContextManager.java
This change will improve the performance of creating iterators.
Also removed custom method to get VFS config.  Now that getting
config by prefixes is fast, it can used for VFS.
> ACCUMULO-4779 Improved performance get by prefix in config

- shell/src/main/java/org/apache/accumulo/shell/commands/CreateTableCommand.java
- test/src/main/java/org/apache/accumulo/test/ShellServerIT.java
ACCUMULO-4772 Update Accumulo shell to utilize new NewTableConfiguration methods
Added capability to pre-configure iterators and locality groups when creating
new tables via the Accumulo shell. Updated CreateTableCommand.java to accept locality group
and iterator data. Updated ShellServerIT.java to test the new capabilities.
> ACCUMULO-4772 Update shell to use NewTableConfiguration methods

- server/tserver/src/main/java/org/apache/accumulo/tserver/FileManager.java
Before this change the lock on the file manager was obtained F+1 times, where
F is the number of files.  When there are lots of threads this is a lot of
contention.  In this change, the lock is only obtained once.
Also in this change the file managers semaphore was switched to non-fair.  The
fair semaphore is expensive and can cause contention.
> ACCUMULO-4805 Obtain filemanager lock once when opening files

- core/src/main/java/org/apache/accumulo/core/conf/ConfigSanityCheck.java
- core/src/test/java/org/apache/accumulo/core/conf/ConfigSanityCheckTest.java
Added a check to the configuration sanity checker to ensure that, if a crypto module other than NullCryptoModule was selected, a
SecretKeyEncryptionStrategy other than NullSecretKeyEncryptionStrategy must also be selected (and vice versa).
> ACCUMULO-4792 Improve crypto configuration checks

- core/src/main/java/org/apache/accumulo/core/client/impl/ThriftTransportKey.java
- core/src/main/java/org/apache/accumulo/core/client/impl/ThriftTransportPool.java
The Jira issue mentions two problems inefficiency and a global lock. This PR focuses on the inefficiency issue and makes the reserve and return operations O(1) instead of O(N).  The global lock is stil there, but now operations done while the lock are held are much faster.  I plan to open up a follow on issue to address the lock.
> ACCUMULO-4788

- server/monitor/pom.xml
- server/monitor/src/test/java/org/apache/accumulo/monitor/WebViewsIT.java
- server/monitor/src/test/java/org/apache/accumulo/monitor/util/MonitorTests.java
- test/pom.xml
* Jersey 1.x jars were excluded in test module causing ITs to fail
* Moved WebViewsIT to monitor which requires Jersey 2.x
* Removed 1.x exclusions from test module
> ACCUMULO-4824 Fix Jersey dependency conflict causing ITs to fail

- core/src/main/java/org/apache/accumulo/core/client/impl/TableOperationsImpl.java
- test/src/main/java/org/apache/accumulo/test/randomwalk/concurrent/AddSplits.java
Also revert commit bcd2dc51 which was hiding this error
> Add TableOfflineException to TableOps.addSplits

- server/base/src/main/java/org/apache/accumulo/server/master/balancer/ChaoticLoadBalancer.java
- test/src/test/java/org/apache/accumulo/test/functional/ChaoticBalancerIT.java
First fixed the NPE by removing the overloaded init methods.  Then fixed the test (I think) by changing the configuration back to what it was originally intended, a balancer for all tables not just one.
> Fix ChaoticBalancerIT

- core/src/main/java/org/apache/accumulo/core/client/IteratorSetting.java
- core/src/main/java/org/apache/accumulo/core/iterators/IteratorUtil.java
- core/src/test/java/org/apache/accumulo/core/client/IteratorSettingTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/IteratorUtilTest.java
ACCUMULO-3389 Iterator Names can't contain dots
Updated code to check iterator names for the presence of dots. If name is found to contain a  dot then an IllegalArgumentException is thrown. Wrote unit/IT tests also.
> ACCUMULO-3389 Iterator Names can't contain dots

- core/src/main/java/org/apache/accumulo/core/client/IteratorSetting.java
- core/src/main/java/org/apache/accumulo/core/client/impl/TabletServerBatchDeleter.java
This was discovered by the failure in TabletStateChangeIteratorIT
* Also improved error message in IteratorSetting to include bad name
> ACCUMULO-3389 Fix name in tsBatchDeleter

- server/base/src/main/java/org/apache/accumulo/server/security/handler/ZKAuthorizor.java
[On the mailing list](https://lists.apache.org/thread.html/31ff119654efe1d2c7c95c544a1634f6cb3c0721108f169986de02dc@%3Cuser.accumulo.apache.org%3E) a performance problem with authorizations was identified.  For the case when a user has a large number of authorizations scans can be really slow. For example if a user has 100,000 auths and does a scan with 90,000 auths, its very slow.  This is caused by a subset check on the server side that uses two lists.  This PR changes the subset check to use an existing hashset.
The following is a performance test that was written to explore this problem.  This code creates a user with 100,000 auths and then times scans with 0, 10, 100, 1000, 10000, and 100000 auths.
```java
public void testManyAuths(Connector conn) throws Exception { …
```
> Fixed inefficient auths check

- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/LogSorter.java
The Math.max() will solve the issue I hope.
I'm not sure what happens if `Property.TSERV_WAL_BLOCKSIZE` is not 0 and smaller than `Property.TSERV_WALOG_MAX_SIZE`. The problem is that `TabletServerLogger` still uses `Property.TSERV_WALOG_MAX_SIZE` [to check data size](https://github.com/apache/accumulo/blob/master/server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java#L456) stored in one file. While file size  [is set to](https://github.com/apache/accumulo/blob/master/server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java#L452) `Property.TSERV_WAL_BLOCKSIZE`.
> ACCUMULO-3807 Avoid Copy/Sort column on WAL recovery exceeds 100%

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
When Accumulo's RPC is configured for SSL/TLS, the client connections
will choose TLSv1.2 by default (instead of TLSv1 or TLSv1.1).
> Make TLSv1.2 the default

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
ACCUMULO-4697 tablet server could kick off too many idle compactions
Tablet.initiateMajorCompaction() always returns false, but we check the return value when accounting for the number of idle major compactions started in TabletServer.MajorCompactor.run() and continue to kick off idle compactions on every tablet.
DefaultCompactionStrategy doesn't do anything special for idle compactions, so this will only be an issue with a custom CompactionStrategy.
My guess would be the best thing to do would be to get rid of idle compactions and get rid of the return value on initiateMajorCompaction().
This update follows the reporters suggestion and removes the idle compaction code and refactors the  initiateMajorCompaction() method to return void.
This ticket references Jira ticket …
> ACCUMULO-4697 tablet server could kick off too many idle compactions

- test/src/main/java/org/apache/accumulo/test/randomwalk/concurrent/OfflineTable.java
Saw this error during randomwalk:
<pre>12:44:53,443 [randomwalk.Framework] ERROR: Error during random walk
java.lang.Exception: Error running node Concurrent.xml
at org.apache.accumulo.test.randomwalk.Module.visit(Module.java:352)
at org.apache.accumulo.test.randomwalk.Framework.run(Framework.java:59)
at org.apache.accumulo.test.randomwalk.Framework.main(Framework.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.accumulo.start.Main$2.run(Main.java:170)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error …
> Handle RW unexpected table state

- core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java
Very useful API method that shouldn't be deprecated.
> Remove deprecated from flush API

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/CloseableIterator.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogReader.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/logger/LogEvents.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/logger/LogFileKey.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/logger/LogReader.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/replication/AccumuloReplicaSystem.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/log/LogEventsTest.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/log/LogFileKeyTest.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/log/RecoveryLogsReaderTest.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/log/SortedLogRecoveryTest.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/logger/LogFileTest.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/replication/AccumuloReplicaSystemTest.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/replication/BatchWriterReplicationReplayerTest.java
- test/src/main/java/org/apache/accumulo/test/replication/UnusedWalDoesntCloseReplicationStatusIT.java
* Fix bug where tablet is unloaded, reloaded on tserver, and then tserver dies
* Fix bug with out of order logs.  Recovery code assumed logs were passed in
time order.  However, since 1.8.0 they have been passed in random order. Rewrote
recovery code to handle out of order logs.  The fix was to read all logs in
a sorted merged way.
> fixes #449 fix two bugs with WAL recovery

- core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java
Ran into an issue with the crypto work i've been doing... the RFileScanner was only passing the default configuration to the BCFile constructor so the configured properties weren't visible.  This PR changes RFileScanner to set the table configured properties once and reuse throughout the iteration.
> Make RFileScanner use table props throughout

- core/src/main/java/org/apache/accumulo/core/metadata/schema/MetadataScanner.java
- core/src/main/java/org/apache/accumulo/core/summary/Gatherer.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/LoadFiles.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/PrepBulkImport.java
This bug was introduced in 9feb5e1. In addition to fixing the bug,
specifying the table was made mandatory for the metadata scanner
builder.
The bug was found by MetadataMaxFilesIT
> Fix bug with GC not scanning root table for file refs

- core/src/main/java/org/apache/accumulo/core/util/MonitorUtil.java
- core/src/test/java/org/apache/accumulo/core/util/MonitorUtilTest.java
In the rare case where this method is called before a monitor ever ran, it will propagate a NoNodeException. It should just return null.
> Catch NoNodeException in MonitorUtil and return null instead #504

- core/src/main/java/org/apache/accumulo/core/client/impl/Bulk.java
- proxy/src/main/java/org/apache/accumulo/proxy/ProxyServer.java
- server/base/src/main/java/org/apache/accumulo/server/client/BulkImporter.java
- server/base/src/main/java/org/apache/accumulo/server/client/ClientServiceHandler.java
- server/base/src/main/java/org/apache/accumulo/server/security/AuditedSecurityOperation.java
- server/base/src/main/java/org/apache/accumulo/server/security/SecurityOperation.java
- server/base/src/test/java/org/apache/accumulo/server/client/BulkImporterTest.java
- server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java
- test/src/main/java/org/apache/accumulo/test/AuditMessageIT.java
- test/src/main/java/org/apache/accumulo/test/BulkImportSequentialRowsIT.java
- test/src/main/java/org/apache/accumulo/test/NamespacesIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkFileIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkSplitOptimizationIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
- test/src/main/java/org/apache/accumulo/test/functional/FunctionalTestUtils.java
- test/src/main/java/org/apache/accumulo/test/mapred/TokenFileIT.java
- test/src/main/java/org/apache/accumulo/test/mapreduce/TokenFileIT.java
* Fix a bunch of warnings
* Ensure new Bulk Import requests are audited
* Remove unneeded deprecation of internal impl code for old bulk import
* Remove unnecessary Serializable for new Bulk code mapping information
* Use new bulk import in some tests when not specifically testing an old bulk import behavior
* Remove some unused variables from tests (left commented out for
reference to ongoing improvements to client configuration code)
> Fix Auditing for new Bulk Import / remove warnings

- pom.xml
This PR upgrades the Curator Framework from version 2.11.0 to 2.12.0.
I ran mvn verify and it fails but it did before I made this change, and there were no new failures. Perhaps that is best handled in another issue (did not see it in the current 29 that exist). 
This is my first pull for this project and I'd just like to also say hello!
> Upgrade the Curator Framework from version 2.11.0 to 2.12.0

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
I noticed this race condition while looking in to #535.  This seems like a very low probability event because multiple conditions would need to be met in a small time window for data loss to occur as a result of this race.
* Only tablet A references WAL_X in its otherLogs set
* Thread T1 one clears otherLogs for tablet A 
* Thread T2 calls markUnusedWALs() removing WAL_X from zookeeper
* Tablet server dies (tablet data that was in WAL_X is not in metadata table or recovery data)
* Thread T1 would have updated the metadata table with a new file if tserver had not died
This change acquires a lock so that the call to markUnusedWALs() will block until the file is added to metadata table.  This lock prevents zookeeper updates from happening before metadata table updates.
This bug only affects …
> Fix WAL race condition between zookeeper and metadata table

- server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/log/SortedLogRecoveryTest.java
There were two changes in this patch. First, removed a sanity check from the code
that resulted in false positives.  Second, changed recovery code to use last
compaction finish event for recovery seq #.
> fixes #538 fix WAL recovery code

- core/src/main/java/org/apache/accumulo/core/util/Duration.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/servlets/BulkImportServlet.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/util/celltypes/DurationType.java
The formatting for monitor display accepts milliseconds. This
fix corrects issue where seconds (duration / 1000) were used,
causing the duration displayed by the monitor to format and display
incorrectly.
> Correct display of BulkImport duration in monitor

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/master/src/main/java/org/apache/accumulo/master/Master.java
Master.gatherTableInformation() had the following problems :
* If Property.MASTER_STATUS_THREAD_POOL_SIZE set > 1, then multiple threads
would put into a TreeMap
* Create a thread pool and never called shutdown now
* Returns a reference to a treemap that threads in thread pool may still
be adding to.
This patch also attempts to address the issues brought up in #402 by switching
to a cached thread pool.  This will allow the thread pool to expand so that
unresponsive tservers do not prevent gathering status from responsive tservers.
> Fix multiple concurrency bugs in Master.gatherTableInformation()

- core/src/main/java/org/apache/accumulo/core/iterators/system/VisibilityFilter.java
User was unable to debug bad visibility because error didn't have any key information.
> Improve info given in visibility exceptions

- server/base/src/main/java/org/apache/accumulo/server/fs/PerTableVolumeChooser.java
- server/base/src/main/java/org/apache/accumulo/server/fs/PreferredVolumeChooser.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeChooserEnvironment.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeUtil.java
- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
- server/base/src/main/java/org/apache/accumulo/server/util/RandomizeVolumes.java
- server/base/src/test/java/org/apache/accumulo/server/fs/PerTableVolumeChooserTest.java
- server/base/src/test/java/org/apache/accumulo/server/fs/PreferredVolumeChooserTest.java
- server/master/src/main/java/org/apache/accumulo/master/Master.java
- server/master/src/main/java/org/apache/accumulo/master/TabletGroupWatcher.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/ChooseDir.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/PopulateMetadataTable.java
- server/master/src/test/java/org/apache/accumulo/master/tableOps/ImportTableTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/WalRemovalOrderTest.java
* Removed ServerContext.getInstance() from VolumeChoosers
* Passed ServerContext by modifying VolumeChooserEnvironment
>  #582 - Pass ServerContext to VolumeChoosers

- core/src/main/java/org/apache/accumulo/core/client/impl/OfflineIterator.java
- core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java
- core/src/main/java/org/apache/accumulo/core/conf/AccumuloConfiguration.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/constraints/NoDeleteConstraint.java
- core/src/main/java/org/apache/accumulo/core/data/Mutation.java
- core/src/main/java/org/apache/accumulo/core/iterators/IteratorUtil.java
- core/src/main/java/org/apache/accumulo/core/iterators/system/DeletingIterator.java
- core/src/test/java/org/apache/accumulo/core/constraints/NoDeleteConstraintTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/system/DeletingIteratorTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Compactor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java
- test/src/main/java/org/apache/accumulo/test/functional/DeleteFailIT.java
- test/src/main/java/org/apache/accumulo/test/performance/scan/CollectTabletStats.java
This experimental option allows for tables that do not use
deletes to have fast seeks within the timestamp range.
> ACCUMULO-4629 Add table option to fail when deletes seen.

- core/src/main/java/org/apache/accumulo/core/file/FileOperations.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/BCFile.java
- server/base/src/main/java/org/apache/accumulo/server/security/AuditedSecurityOperation.java
- test/src/main/java/org/apache/accumulo/test/UnusedWALIT.java
* Remove unnecessary warnings suppression in FileOperations (also add
missing overrides annotations here)
* Remove potential resource leak in BCFile due to reusing a variable for
a potentially new resource allocation without closing the previous one
assigned to that variable; this wasn't really a problem because of the
way we were passing the input stream into the decryptor to get a new
input stream, but it could happen if that code were to change slightly
* Remove unused instanceId from AuditedSecurityOperation
* Remove unused zk variable from UnusedWALIT (also make the timeout
scalable, like other ITs, in case of testing on a resource-limited
machine)
> Remove warnings

- assemble/conf/accumulo-env.sh
- assemble/pom.xml
- assemble/src/main/assemblies/component.xml
- core/src/main/java/org/apache/accumulo/core/client/summary/SummarizerConfiguration.java
- core/src/main/java/org/apache/accumulo/core/sample/impl/DataoutputHasher.java
- core/src/main/java/org/apache/accumulo/core/summary/Gatherer.java
- core/src/main/spotbugs/exclude-filter.xml
- pom.xml
- server/gc/src/main/java/org/apache/accumulo/gc/replication/CloseWriteAheadLogReferences.java
- server/master/src/main/java/org/apache/accumulo/master/replication/RemoveCompleteReplicationRecords.java
- server/monitor/pom.xml
- server/monitor/src/main/java/org/apache/accumulo/monitor/EmbeddedWebServer.java
- test/src/main/java/org/apache/accumulo/test/functional/ScannerIT.java
* Limited the number of dependencies from Hadoop
* Upgraded several dependencies including ZooKeeper,
Jetty, Guava, Gson, Jersey, Bouncy Castle, ClassMate,
FreeMarker, Caffeine, commons-cli, commons-codec,
commons-configuration, commons-io, commons-lang,
commons-logging, javax.ws-rs-api, HK2
> Updated Accumulo dependencies and classpath

- core/src/main/java/org/apache/accumulo/core/client/Instance.java
Restoring these for following reasons :
* Any project that implemented Instance still had to implement deprecated
methods.
* Multiple projects currently have code that call these methods.
* All of Instance is now deprecated.
* Use of Java 8 default methods makes restoration trivial with single line
implementations that have negligible maintenance burden.
> Restore deprecated instance methods removed in 0ba6c49

- pom.xml
The command `mvn install -PskipQA` allows quick install for
testing.  However the accumulo maven plugin built by this
command was not working.  This change fixes that.
> Fix plugin build with skipQA profile

- test/system/continuous/start-ingest.sh
I was trying to run continuous ingest test, but run into an error:
In start-ingest.sh, DEBUG_OPT is set to use -debug, but that is to turn logs on-off.
When calling pssh command, we use it to set where to log. It will not run, and in the .out log it will just write the usage:
```
Usage: org.apache.accumulo.test.continuous.ContinuousIngest [options]
Options:
[..]
--debug
turn on TRACE-level log messages
Default: false
--debugLog
file to write debugging output
```
> Correct how Continuous Ingest specifies the debug log file

- core/src/main/java/org/apache/accumulo/core/security/crypto/impl/AESCryptoService.java
- core/src/main/java/org/apache/accumulo/core/security/crypto/streams/DiscardCloseOutputStream.java
- core/src/main/java/org/apache/accumulo/core/security/crypto/streams/NoFlushOutputStream.java
* Remove use of DiscardCloseOutputStream from WAL encryption
* Override inefficient write method in DiscardCloseOutputStream and NoFlushOutputStream
* Changed NoFlushOutputStream to extend FilterOutputStream, which doesn't have synchronized methods like DataOutputStream does
> Fix performance of crypto

- test/src/main/java/org/apache/accumulo/test/mapred/AccumuloFileOutputFormatIT.java
- test/src/main/java/org/apache/accumulo/test/mapreduce/AccumuloFileOutputFormatIT.java
Before this change the {mapred,mapreduce}.AccumuloFileOutputFormatITs would work against a minicluster backed by
Hadoop's LocalFileSystem, but fail if one followed the instructions for testing against a stand alone cluster.
The failure is because in the cluster case the FileSystem we get is for the HDFS instance underlying the
Accumulo cluster, which can't find the folder JUnit created for our test.
> AccumuloFileOutputFormatITs need to look on local filesystem for results written into JUnit provided temp dir.

- core/pom.xml
- examples/simple/pom.xml
- maven-plugin/pom.xml
- maven-plugin/src/it/plugin-test/pom.xml
- maven-plugin/src/main/java/org/apache/accumulo/maven/plugin/StartMojo.java
- maven-plugin/src/main/java/org/apache/accumulo/maven/plugin/StopMojo.java
- pom.xml
- test/pom.xml
* was present for Hadoop 1, which we don't support anymore
* was present for ThreadSafe note on our maven-plugin mojo, but that annotation is gone in current releases
Tested via running ITs locally and against standalone hadoop clusters
> Remove httpclient dependency.

- shell/src/main/java/org/apache/accumulo/shell/commands/DeleteTableCommand.java
- shell/src/main/java/org/apache/accumulo/shell/commands/DropTableCommand.java
- Explicitly state that deletetable and droptable are the same
Screenshot from running in uno.
> Fixes #561 - Be explicit about aliases in shell

- .travis.yml
* Remove IRC notifications (nobody lurks in IRC anymore, so this isn't useful)
* Unset _JAVA_OPTIONS to restore default Java options, so plugins don't
run out of memory and cause the container to get killed
* Remove forking for unit tests; the container doesn't have a lot of CPU
to fork anyway, and removing this helps with excessive memory utilization
> Update travis-ci settings

- core/src/main/java/org/apache/accumulo/core/cli/ConfigOpts.java
We are getting the properties path after calling getSiteconfiguration but it was never set so a null is getting passed to JCommander.
> Set props path in ConfigOpts. Fixes #676

- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/navbar.ftl
I am not sure what to call this link but it shouldn't be API.  This is for the top far right link in the navigation bar.  It is a drop down of two links, one to generate the XML and one for JSON.
> Rename link on Monitor to Rest

- client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapred/AbstractInputFormat.java
- client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapreduce/AbstractInputFormat.java
- client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapreduce/lib/impl/ConfiguratorBase.java
- core/src/main/java/org/apache/accumulo/core/client/impl/AccumuloClientImpl.java
- core/src/main/java/org/apache/accumulo/core/client/impl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/client/summary/Summary.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/util/format/BinaryFormatter.java
- core/src/main/java/org/apache/accumulo/core/util/format/DateStringFormatter.java
- minicluster/src/main/java/org/apache/accumulo/cluster/AccumuloCluster.java
- minicluster/src/main/java/org/apache/accumulo/minicluster/MiniAccumuloCluster.java
- minicluster/src/test/java/org/apache/accumulo/minicluster/MiniAccumuloClusterExistingZooKeepersTest.java
- minicluster/src/test/java/org/apache/accumulo/minicluster/MiniAccumuloClusterStartStopTest.java
- minicluster/src/test/java/org/apache/accumulo/minicluster/MiniAccumuloClusterTest.java
* Add missing since information for deprecations, including properties
* Fix various javadoc syntax
* Remove deprecated import statements and suppress deprecations in
tests, to limit spam from compiler warnings
> Cleanup deprecation stuffs

- pom.xml
ACCUMULO-4818 is about upgrading to checkstyle 8+. Since the current version is upgraded to 8.12 in the meantime this change might be insignificant.
> ACCUMULO-4818 Upgrade to checkstyle 8.13

- core/src/main/java/org/apache/accumulo/core/summary/SummarySerializer.java
- test/src/main/java/org/apache/accumulo/test/functional/SummaryIT.java
For a table with multiple locality groups and a locality group with no data,
feching summaries would fail.  Found this while working on apache/fluo#1054
> Fix summarizer bug with empty loc group

- core/src/main/java/org/apache/accumulo/core/client/mapreduce/lib/impl/InputConfigurator.java
…thin AbstractInputFormat.initialize()
> Fix #705 TableName from baseSplit is ignored, when getting inputTableConfig within AbstractInputFormat.initialize()

- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/default.ftl
Included Flot's resize plugin to properly handle window resize.
> Fix #713 Monitor 2.0 overview plots overlap when resizing browser window

- core/src/main/java/org/apache/accumulo/core/client/mapreduce/lib/impl/InputConfigurator.java
- server/base/src/main/java/org/apache/accumulo/server/tables/TableManager.java
- server/master/src/main/java/org/apache/accumulo/master/TabletGroupWatcher.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/CleanUp.java
The tableOps.CleanUp.isReady() operation was not waiting on tablets that were
assigned to dead tablet servers.  The master will attempt to write logs and
delete the location for these tablets.  Therefore its best to wait for the
Master to make its metadata update before proceeding to clean up a deleted
table.
> fixes #587 Wait for tablets assigned to dead servers before deleting table

- pom.xml
Roll back to commons-vfs2 version 2.1 due to bugs with 2.2.  See dev mailing list thread: "commons-vfs2.jar 2.2 buggy"
> Revert commons-vfs2 version

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/bulkImport.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/functions.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/gc.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/listType.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/master.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/navbar.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/overview.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/problems.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/replication.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/scans.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/server.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/show.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/summary.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/table.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/tservers.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/vis.ftl
Forcing ajax queries to be synchronous isn't advisable for the reasons described in the links below.  I've improved the code to work asynchronously.
I'm also working on some other improvements but I wanted to submit them as smaller PR's to make them easier to review.
[jQuery.ajax(): Setting async to false is strongly discouraged as it can cause the browser to become unresponsive.](http://api.jquery.com/jquery.ajax/)
[MDN: Synchronous requests on the main thread have been deprecated due to the negative effects to the user experience.](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests#Synchronous_request)
The functions that use .getJSON() in functions.js now return the jqXHR (jQuery XML HTTP Request) object.
This object implements the …
> Monitor 2.0: Eliminate use of async:false for ajax requests

- core/src/main/java/org/apache/accumulo/core/conf/AccumuloConfiguration.java
- core/src/main/java/org/apache/accumulo/core/conf/DefaultConfiguration.java
- core/src/main/java/org/apache/accumulo/core/conf/SiteConfiguration.java
- core/src/main/java/org/apache/accumulo/fate/zookeeper/ZooCache.java
- core/src/test/java/org/apache/accumulo/core/conf/AccumuloConfigurationTest.java
- server/base/src/main/java/org/apache/accumulo/server/ServerUtil.java
- server/base/src/main/java/org/apache/accumulo/server/conf/ZooConfiguration.java
- server/base/src/main/java/org/apache/accumulo/server/conf/ZooConfigurationFactory.java
- server/base/src/test/java/org/apache/accumulo/server/conf/ZooConfigurationFactoryTest.java
* Updated AccumuloConfig.isPropertySet() method optionally cache and
watch for changes in the property
> Avoid ZK watch when checking if property is set

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactionRunner.java
While working on an experimental compaction strategy for Fluo for apache/fluo#1054 I ran into a situation where Accumulo was calling my compaction strategy hundreds of thousands of times per second.  I tracked down the problem and fixed it in this PR.
> Only requeue compaction when there was activity

- core/src/main/java/org/apache/accumulo/core/client/impl/ConnectorImpl.java
- core/src/main/java/org/apache/accumulo/core/client/impl/TableOperationsImpl.java
- core/src/test/java/org/apache/accumulo/core/security/crypto/CryptoTest.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapred/AccumuloInputFormat.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/AccumuloInputFormat.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/AccumuloRowInputFormat.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapred/AccumuloRowInputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/AccumuloRowInputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/NewAccumuloInputFormatIT.java
- test/src/main/java/org/apache/accumulo/test/UserCompactionStrategyIT.java
* Fix compiler warnings
* Add missing Deprecated annotation in class method which overrides
deprecated interface method
* Add trivial notNull checks in test try-with-resources methods which
didn't otherwise reference the resource inside the try block
* Add fail() methods to fail after a test method is called which is
expected to throw an exception, in order to ensure the exception is
thrown in the correct line, and to add a reference to the assigned
variable
* Add generic parameters and final keyword to CLASS constants in new
hadoop-mapreduce module
* Remove import statement for deprecated class
* Rename packages for ITs in new hadoop-mapreduce module to avoid jar
sealing conflicts between the module's main jar and the IT classes
* Fix trivial typos in a comment seen in …
> Fix warnings and jar sealing issues with ITs

- assemble/pom.xml
- assemble/src/main/assemblies/component.xml
We need newer than Hadoop 2.y releases provide now, so bring our own along.
Closes #757 
Tested by using Apache Fluo Unos to stand up a cluster on top of Apache Hadoop 2.8.4. Setup failed right off the bat before change. After change was able to stand up a cluster, go through YCSB Workload A load and run, and use shell to flush, compact, scan, etc.
> Include commons-configuration in our convenience binaries for Hadoop 2.

- server/native/src/main/c++/nativeMap/NativeMap.h
This fixes a bug that was found when building the native maps against
Fedora 29.  The cause of the bug was that an empty C++ map seemed to
allocate a small amount of memory, which was a new behavior.  This new
behavior violated an assumption made by the custom alloctor used by the
native map code.  The code was restructured to avoid this issue.
> fixes #767 correct allocation issue in native maps

- core/src/main/java/org/apache/accumulo/core/client/BatchWriterConfig.java
- core/src/main/java/org/apache/accumulo/core/conf/ClientProperty.java
- core/src/test/java/org/apache/accumulo/core/client/BatchWriterConfigTest.java
Replace hard coded defaults and key names in BatchWriterConfig with values in ClientProperty.
Also improved BATCH_WRITER_DURABILITY javadoc.
> Remove hard coded values from BatchWriterConfig

- start/src/test/shell/makeHelloWorldJars.sh
- start/src/test/shell/makeTestJars.sh
PATCH:  Asserting whether JAVA_HOME is set or not when running "mvn package". When the JAVA_HOME is not set, we are seeing an error that says "bin/javac" not found, "bin/java" not found.
Adding the Assertion that checks for JAVA_HOME is set or not and Errors out with a more intuitive Error Message
> Verifying whether JAVA_HOME is set or not

- core/src/main/java/org/apache/accumulo/core/client/BatchWriterConfig.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/AccumuloClientImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/conf/ClientProperty.java
- core/src/main/java/org/apache/accumulo/core/conf/PropertyType.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/ClientConfConverterTest.java
- core/src/test/java/org/apache/accumulo/core/conf/ClientPropertyTest.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/lib/OutputConfigurator.java
* Change ClientProperty to use millis for batch writer properties
One solution to fix #778.  I also thought of adding different property types to ClientProperty, similar to the way Property uses PropertyType.TIMEDURATION but that required a lot more work. Perhaps that could be a future improvement.
> Create types in ClientProperty. Closes #778

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/css/screen.css
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/functions.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/overview.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/navbar.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/overview.ftl
Fixed avatar jumping left/right between small/medium layouts.
When resizing the browser window between medium and small bootstrap layouts, the accumulo avatar (or "brand image" in bootstrap terms) was shifting position on the navbar.
According to the [Bootstrap Navbar example](https://getbootstrap.com/docs/3.3/components/#navbar-brand-image), the image element should be inside the navbar-brand element.
Fixed overview plots timeformat option not working because of a typo.
Code was using "timeFormat" instead of "timeformat".
It was supposed to display like '00:00<br>EDT' but it was defaulting to '00:00'
I fixed the bug but I think I liked it better without the time zone.  It looks really repetitive to show the time zone with every tick on ten charts.  To me, it seems obvious that it's local …
> Monitor 2.0: Minor bug fixes, chart updates

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/css/screen.css
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/overview.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/bulkImport.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/default.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/listType.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/master.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/navbar.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/overview.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/problems.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/replication.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/scans.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/server.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/show.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/summary.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/table.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/tservers.ftl
Fixed a .container div nested in a .container-fluid. Bootstrap [container classes are not nestable](https://getbootstrap.com/docs/3.3/css/#overview-container).
Changed main div from absolute positioning to relative.  This was causing plot tooltips to display offset from the actual location of the data point. (Tooltips to be added as a separate pull request)
Replaced divs using .center-block class with Bootstrap's .row and .col-* to improve layout responsiveness.
Also moved h3 titles inside .row and .col-* divs.
Cleaned up unused and redundant CSS rules.
Side-by-side plots on the overview page still look fine at the small layout. Changed .col-md-6 to .col-sm-6
Removed time zone from plots' X axis tick labels. Planning to add other means of displaying and selecting time zone.  Plot option …
> Monitor 2.0: HTML, CSS, and plot updates

- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapred/AccumuloInputFormat.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapred/AccumuloRowInputFormat.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/AccumuloInputFormat.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/InputFormatBuilder.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapred/AbstractInputFormat.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/AbstractInputFormat.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/InputFormatBuilderImpl.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/InputTableConfig.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/lib/InputConfigurator.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapred/MultiTableInputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/MultiTableInputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/mapred/AccumuloInputFormatTest.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/mapred/MultiTableInputFormatTest.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/mapreduce/AccumuloInputFormatTest.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/mapreduce/MultiTableInputFormatTest.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoopImpl/mapreduce/InputTableConfigTest.java
* Modified new MapReduce builder and implemention to allow multiple
tables through the same fluent API as AccumuloInputFormat
* Removed redundant getInputTableConfig methods, replacing with InputConfigurator
> Multi table input for new MR. Closes #749

- server/tserver/src/main/java/org/apache/accumulo/tserver/InMemoryMap.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CommitSession.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/TabletMemory.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/InMemoryMapTest.java
- test/src/main/java/org/apache/accumulo/test/InMemoryMapIT.java
* The number of total keys across mutations was counted twice so just
pass the count down to the InMemoryMap
> Remove extra loop in InMemoryMap

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletMutations.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/log/DfsLoggerTest.java
* Actually log MUTATION for single mutation
* Make TabletMutations constructor take CommitSession
* Simplify calls to defineTablet
* Remove unused datafile path param
* Add checks for debug
Only synchronize on write method
> More cleanup for WAL

- assemble/conf/accumulo-env.sh
* If CLASSPATH variable was empty, a colon would be added
to front of CLASSPATH causing user's current directory
to be added to directory.
* This could unexpected files like accumulo.properties to be
added to the classpath
> Fix CLASSPATH bug causing current dir to be added

- core/src/main/java/org/apache/accumulo/core/client/admin/NewTableConfiguration.java
- core/src/main/java/org/apache/accumulo/core/client/impl/InstanceOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/client/impl/NamespaceOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/client/impl/TableOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/util/LocalityGroupUtil.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/InMemoryMap.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Compactor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/MinorCompactor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/TabletMemory.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/InMemoryMapTest.java
- test/src/main/java/org/apache/accumulo/test/InMemoryMapIT.java
- test/src/main/java/org/apache/accumulo/test/InMemoryMapMemoryUsageTest.java
- test/src/main/java/org/apache/accumulo/test/functional/BadLocalityGroupMincIT.java
- test/src/main/java/org/apache/accumulo/test/functional/RowDeleteIT.java
Two changes were made for bad locality group config.  First, when setting
properties a warning  is issued if the change results in bad LG config.
Second, minor compactions will log a warning and proceed with no LG config
if the config is bad.
> fixes #819 Handle bad locality group config.

- server/base/src/main/java/org/apache/accumulo/server/log/WalStateManager.java
When a tablet server dies the master gets its WALs from ZK.  In ZK there
is a list of WALs per tserver. Each WAL in ZK has state that is either
OPEN, CLOSED, or UNREFERENCED.  The master needs a list of OPEN and
CLOSED logs for dead tservers.  While the master is trying to obtain
this list its possible that the Accumulo GC may delete an UNREFERENCED
WAL.  If this happened then the code before this commit would return an
empty list of WALs. This could result in OPEN and CLOSED logs being
ignored for recovery which could result in data loss.  This patch fixes
the race condition.
This bug was observed while looking into an exception I noticed while
writing test for #860.  In the IT I was frequently calling another
WalStateManager function and noticed NoNodeExceptions.  As a result I
examined …
> Fix race condition when getting WALs for dead tserver

- assemble/bin/accumulo-util
- minicluster/src/main/java/org/apache/accumulo/cluster/standalone/StandaloneClusterControl.java
- minicluster/src/test/java/org/apache/accumulo/cluster/standalone/StandaloneClusterControlTest.java
* Command doesn't work well now that Accumulo does
not match Hadoop's dependenices
* Users should create shaded jar instead and submit
using Hadoop's 'yarn jar' command
* Command was used by StandaloneClusterControl but only
by unit test
> Remove 'accumulo-util hadoop-jar' command

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/master/src/main/java/org/apache/accumulo/master/Master.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- test/src/main/java/org/apache/accumulo/test/replication/MultiTserverReplicationIT.java
* Only start the replication services in TabletServer if the required
properties are set at startup
I noticed tserver will always start multiple threads for replication, even if replication name is not configured.  As far as I can tell, this is the only required property for replication and if it is not set at startup anyway, there is a good chance not all data will be replicated.
> Make replication services start when configured

- core/src/main/java/org/apache/accumulo/core/client/ZooKeeperInstance.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/KeyShortenerTest.java
- server/base/src/main/java/org/apache/accumulo/server/ServerInfo.java
- server/base/src/main/java/org/apache/accumulo/server/util/MasterMetadataUtil.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tservers/TabletServerResource.java
* Remove import statement for deprecated class
* Restore some deleted KeyShortenerTest code, and make use of the
expected parameter for verifying shortened keys
* Remove some unused variables
> Fix latest round of warnings

- core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/BulkImport.java
- proxy/src/main/java/org/apache/accumulo/proxy/ProxyServer.java
- shell/src/main/java/org/apache/accumulo/shell/commands/ImportDirectoryCommand.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkLoadIT.java
* Also add new test to BulkLoadIT for tableTime
The fluent API for the new Bulk Import has an option to set the time on bulk import:
` c.tableOperations().importDirectory(dir).to(tableName).tableTime().load();`
But this can be awkward if you have a boolean in your code to set the time so making it take a boolean seems less awkward:
`    c.tableOperations().importDirectory(dir).to(tableName).tableTime(setTime).load();
`
> Make new Bulk Import tableTime take boolean

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java
In a situation where a tablet had lots of write ahead logs, log
recovery consumed a lot of memory.  The reason for the memory
consumption was that all recovery logs are opened at once.  This
means the index for each file and a few key/values from each file
are read into memory.
This patch modifies the code to first open logs one at time to see if
they define the tablet. Then only the logs that define the tablet are
opened at the same time.  This has the potential to use less memory
when a subset of the logs define a tablet.
> During tablet recovery filter logs out that do not define tablet.

- core/src/main/java/org/apache/accumulo/core/cli/ClientOpts.java
- core/src/main/java/org/apache/accumulo/core/client/mapred/AbstractInputFormat.java
- core/src/main/java/org/apache/accumulo/core/client/mapred/AccumuloFileOutputFormat.java
- core/src/main/java/org/apache/accumulo/core/client/mapred/AccumuloOutputFormat.java
- core/src/main/java/org/apache/accumulo/core/client/mapred/InputFormatBase.java
- core/src/main/java/org/apache/accumulo/core/client/mapreduce/AbstractInputFormat.java
- core/src/main/java/org/apache/accumulo/core/client/mapreduce/AccumuloFileOutputFormat.java
- core/src/main/java/org/apache/accumulo/core/client/mapreduce/AccumuloOutputFormat.java
- core/src/main/java/org/apache/accumulo/core/client/mapreduce/InputFormatBase.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ConnectorImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/mapreduce/lib/ConfiguratorBase.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/mapreduce/lib/FileOutputConfigurator.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/mapreduce/lib/InputConfigurator.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/mapreduce/lib/OutputConfigurator.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/mapreduce/lib/ConfiguratorBaseTest.java
- test/src/main/java/org/apache/accumulo/test/mapred/TokenFileIT.java
- test/src/main/java/org/apache/accumulo/test/mapreduce/RowHash.java
- test/src/main/java/org/apache/accumulo/test/mapreduce/TokenFileIT.java
* Fix broken core/mapred* ITs
* Revert serialization to previous (1.9) serialization in core
* Make use of stored fields in input splits before reading job
configuration for constructing client
* Use ConnectorImpl's ClientContext in core/mapred
* Revert unnecessary closing of ClientContext from ConnectorImpl
* Revert unnecessary "simplification" of Configurators to manage
deprecated types (remove unnecessary deprecation of internal
configurator classes)
* Slight simplifications to ITs to ease debugging
* Check failure state when core/mapred ITs fail
> Revert core/mapred* serialization

- core/src/main/java/org/apache/accumulo/core/client/TableDeletedException.java
- core/src/main/java/org/apache/accumulo/core/client/TableOfflineException.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/IsolationException.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ScannerIterator.java
In addition to cleaning up the exception handling I also switched from a background thread putting a batch of mutations on a queue to using a future.  Doing this made the code simpler making it easier to clean up the exception handling.
> fixes #736 avoid dropping exceptions in scanner

- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/Bulk.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkSerialize.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/ConcurrentKeyExtentCache.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/LoadMappingIterator.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/bulk/BulkSerializeTest.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/bulk/ConcurrentKeyExtentCacheTest.java
- server/base/src/main/java/org/apache/accumulo/server/util/FileUtil.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/BulkImportMove.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/LoadFiles.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/PrepBulkImport.java
My attempt to make the new code easier to follow and maintain. 
* Move bulk import clientImpl code to its own bulk package
* Pull some FaTE logic out of BulkImport
* Made the LoadMappingIterator its own class and push some of the reader logic into it
* Added comments to BulkSerialize
* Removed some VisibileForTesting annotations from ConcurrentKeyExtentCache where its used in BulkImport
* Pulled some logic out of LoadFiles.loadFiles and created some new methods for readability
> Organize new Bulk Import code

- pom.xml
Snyk CLI tool was flagging this Thrift dependency.  Excluding it from our pom seems to have no effect.
> Exclude vuln thrift dep from build

- server/master/src/main/java/org/apache/accumulo/master/Master.java
When Accumulo is configured to use Kerberos for client authentication the
administrative user is configured at security initialization. Before this
change the upgrade process would attempt to grant access to the system
namespace to the 'root' user rather than to the configured administrative
user.
> Upgrade process should not assume the administrative user is named 'root'.

- assemble/pom.xml
- assemble/src/main/assemblies/component.xml
- pom.xml
* Accumulo can be run with Java 11. More work needed
to get Accumulo to build using Java 11.
* Added depedencies that are no longer included by JVM in Java 11
> Fix #952 - Support running Accumulo using Java 11

- fate/src/main/java/org/apache/accumulo/fate/AdminUtil.java
- test/src/main/java/org/apache/accumulo/test/functional/FateConcurrencyIT.java
- test/src/main/java/org/apache/accumulo/test/functional/TableChangeStateIT.java
Refactor AdminUtil to provide refactor the existing fate status methods into two - one that provides the existing behaviour and a second
that does not need to process lock information when that information is not required. This refactoring is a step to providing FATE metrics
where a count of existing FATES does not need the lock information.
* Adds unit test
* Includes code analysis clean-up.
> Refactor FATE AdminUtil spliting getStatus method.

- minicluster/src/main/java/org/apache/accumulo/minicluster/MiniAccumuloConfig.java
* This allows accumulo-maven-plugin to only use public API
See related PR: apache/accumulo-maven-plugin#3
> Fix #910 - Add setClasspathItems() to MiniAccumuloConfig

- core/src/main/java/org/apache/accumulo/core/client/ScannerBase.java
- core/src/main/java/org/apache/accumulo/core/spi/scan/HintScanPrioritizer.java
- core/src/main/java/org/apache/accumulo/core/spi/scan/SimpleScanDispatcher.java
- core/src/test/java/org/apache/accumulo/core/spi/scan/HintScanPrioritizerTest.java
- core/src/test/java/org/apache/accumulo/core/spi/scan/SimpleScanDispatcherTest.java
- core/src/test/java/org/apache/accumulo/core/spi/scan/TestScanInfo.java
While working on apache/fluo#1055 I found it cumbersome to configure
Fluo and Accumulo to dispatch Fluo notification scans to a dedicated
executor.  With these changes its much simpler to do that.  Fluo can
set an execution hint  like `scan_type=fluo-ntfy` and Accumulo can be
configured to execute the scan based on the type without changing Fluo
config or source code.
Before these changes, Fluo would have required either a custom
dispatcher or custom Fluo config for Accumulo executors. With these
changes nothing needs to be done in Fluo.
> Support dispatching and prioritizing by user scan types

- test/src/main/java/org/apache/accumulo/test/TransportCachingIT.java
Count the number of times the log message is printed and limit it.   Also kick out of loops after 1000 failed attempts at calling pool.getAnyTransport.
> Fixes #600 - TransportCachingIT fills up disk with messages

- core/src/main/java/org/apache/accumulo/core/clientImpl/ConditionalWriterImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletLocator.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/MultiLevelIndex.java
Also use lambdas and computeIfAbsent with these types while I was in the area.
These changes should fix 3 java/abstract-to-concrete-cast alerts from lgtm.
> Use appropriate types to prevent casting

- core/src/main/java/org/apache/accumulo/core/conf/AccumuloConfiguration.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- test/src/main/java/org/apache/accumulo/test/performance/RollWALPerformanceIT.java
After the changes in #860 having a tablet property for max write ahead
logs no longer makes sense.  This should be a tserver property because
the behavior controls the max walogs per tserver.  This commit replaces
the table property with a tablet server property.
> Make max walogs a tserver property

- server/base/src/main/java/org/apache/accumulo/server/conf/NamespaceConfiguration.java
- server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java
- server/base/src/main/java/org/apache/accumulo/server/conf/ZooCachePropertyAccessor.java
This fixes a bug introduced by #1008 which attempted to call isPropSet
for a table config object.  Table config did not implement that method
before this change.
> Support isPropSet for table config

- test/src/main/java/org/apache/accumulo/test/functional/ConfigurableMacBase.java
* Return client properties from MiniAccumuloCluster
* SSL configuration was not being returned by MiniAccumuloCluster
causing SSL ITs to fail
>  #1013 Fix ConfigurableMacBase

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/master.js
Java script code was looking for a JSON "time" member and not a JSON "runtime" member off of the RecoveryStatusInformation JSON object.
> Fixes #917 - Wrong date on monitor for log recovery. 

- pom.xml
Apply update for THRIFT-4506 CVE-2018-1320
Generator does not change between 0.9.3 and 0.9.3-1, only libthrift jar
> Update to libthrift 0.9.3-1

- server/base/src/main/java/org/apache/accumulo/server/log/SortedLogState.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogReader.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/log/RecoveryLogsReaderTest.java
One possible fix for this issue.  This just ignores the failed file.  AFAIK we aren't actually doing anything with this failed file so it could just be removed.  But maybe that be done for 2.0
> Possible fix and unit test. Fixes #961

- assemble/bin/bootstrap_config.sh
- assemble/conf/templates/accumulo-site.xml
Consider tserver.total.mutation.queue.max in example configs and
bootstrap_config.sh
Use size somewhat proportional to the size of the cluster
> Fix #994 Consider mutation queue in example config

- server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java
This change restores the exception handling in TabletServerLogger to the way it was before the changes in #1005.  This changes makes TabletServerGivesUpIT pass.
> restore exception handling #949 #1005

- server/master/src/main/java/org/apache/accumulo/master/Master.java
Addresses issue 1058 - the registration of metrics should be independent of replication.
> Move metrics registration to master run.

- server/base/src/main/java/org/apache/accumulo/server/rpc/CustomThreadedSelectorServer.java
- server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java
- server/base/src/main/java/org/apache/accumulo/server/rpc/ThriftServerType.java
- server/base/src/test/java/org/apache/accumulo/server/rpc/ThriftServerTypeTest.java
Before this change Accumulo's used the THsHaServer thrift server. This
server has a single select threads that read and writes frames to
sockets.  The select thread puts the frames on a thread pool for
processing.  On a machine with a lot of cores, this single thread can
become a bottleneck.  This commit switches to use the thrift
TThreadedSelectorServer server which support multiple select threads.
To demonstrate the differernce this change can make, the
RandomCachedLookupsPT performance test in accumulo-testing was run with
and without this change.  The test was run on a machine with 16 cores.
The test loads a table into cache and then does random lookups with
varying numbers of threads.  It measures the average lookup time for
each lookup. Below is a table of running this test.
| …
> Switch to thrift server with multiple selector threads.

- server/base/src/main/java/org/apache/accumulo/server/rpc/CustomThreadedSelectorServer.java
- server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java
- server/base/src/main/java/org/apache/accumulo/server/rpc/ThriftServerType.java
- server/base/src/test/java/org/apache/accumulo/server/rpc/ThriftServerTypeTest.java
After the changes in #1059 some of the ITs were failing. The new thrift
server was failing.  This change reverts to the previous thrift server
type as the default while leaving the new type configurable.
> Revert thrift server to custom_hs_ha

- test/src/main/java/org/apache/accumulo/harness/SharedMiniClusterBase.java
- test/src/main/java/org/apache/accumulo/test/ConditionalWriterIT.java
- test/src/main/java/org/apache/accumulo/test/NamespacesIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkLoadIT.java
Change NamespacesIT, ConditionalWriterIT and BulkLoadIT to be a single cluster IT base class (SharedMinClusterBase).  These were the 3 ITs with the most tests.
Running times greatly improved:
NamespacesIT ~5 mins -> 1 min
ConditionalWriterIT ~4 mins -> 1 min
BulkLoadIT ~2 mins -> 20s
> Speed up some longer running ITs 

- server/monitor/pom.xml
- server/monitor/src/main/java/org/apache/accumulo/monitor/EmbeddedWebServer.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/XMLResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/bulkImports/BulkImportResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/gc/GarbageCollectorResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/master/MasterResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/problems/ProblemsResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/replication/ReplicationResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/scans/ScansResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/statistics/StatisticsResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/status/StatusResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tables/TablesResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/trace/TracesResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tservers/TabletServer.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tservers/TabletServerInformation.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tservers/TabletServerResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/view/WebViews.java
- server/monitor/src/test/java/org/apache/accumulo/monitor/it/WebViewsIT.java
- server/monitor/src/test/java/org/apache/accumulo/monitor/rest/tservers/TabletServerInformationTest.java
* Convert all static fields/methods in Monitor to instance members
(except for constants)
* Use dependency injection to wire the Monitor through Jetty and into
the Jersey application resources
* Remove unnecessary code to asynchronously get the instanceName (it's
available on server startup, and can be obtained from the ServerContext)
* Ensure the Monitor is properly instantiated with the ServerContext
* Simplify fetching lock mechanism (using a simple AtomicBoolean instead
of synchronization)
* Simplify some Monitor internals, especially those pertaining to
initializing container resources by inlining MaxList into an anonymous
subclass of LinkedList that is constructed by a convenience method; this
makes some of the many Monitor members more readable by reducing the
number of lines which …
> Make Monitor service non-static

- assemble/pom.xml
- assemble/src/main/assemblies/component.xml
- pom.xml
Include Guava's only runtime dependency in the binary tarball assembly.
failureaccess was separated from Guava's main jar and updated to include
OSGi stuffs for Android, and is no longer bundled with Guava in 27.1 and
later.
> Include Guava's failureaccess in assembly

- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/bulkImport.ftl
Tested old bulk import works on New Monitor page so just change the label.  If we have long running new Bulk Imports in the future, we can add something to handle them.
> Update Bulk import monitor page. Closes #475

- test/src/main/java/org/apache/accumulo/test/functional/FateConcurrencyIT.java
Test previously looked for a compaction and then tried to match that with a table id. This
improves the check so that it also considers the table when checking for compaction has started.
This is to reduce transient errors reported in #1079.
> Improve FateConcurrencyIT to reduce transient test errors (Issue #1079).

- core/src/main/java/org/apache/accumulo/core/conf/ObservableConfiguration.java
- server/base/src/main/java/org/apache/accumulo/server/conf/NamespaceConfWatcher.java
- server/base/src/main/java/org/apache/accumulo/server/conf/TableConfWatcher.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- test/src/main/java/org/apache/accumulo/test/functional/FateConcurrencyIT.java
When a tserver looses lock, the Session expired message is log for every watcher.
- reduce current message to trace.
- add summary logging messages that give number of sessions expired
> Improve logging for session expired events.

- server/tserver/src/main/java/org/apache/accumulo/tserver/OnlineTablets.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerMetricsUtil.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/BulkImportCacheCleaner.java
Profiling Accumulo during running a performance test showed lots of lock
contention for the map of online tablets.  Most operations need to read
this map.  This change creates a read only snapshot of the online
tablets that is used to avoid lock contention.
> Avoid locking in tserver when reading online tablets

- server/base/src/main/java/org/apache/accumulo/server/conf/NamespaceConfiguration.java
- server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java
Lock contentions was observed in table configuration during profiling.
This change replaces a syncronized pointer to a ZooCache with an
AtomicReference.
> Avoid lock contention in table configuration

- server/base/src/main/java/org/apache/accumulo/server/AbstractServer.java
- server/base/src/main/java/org/apache/accumulo/server/ServerContext.java
- server/gc/src/main/java/org/apache/accumulo/gc/GCExecutable.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/gc/src/test/java/org/apache/accumulo/gc/SimpleGarbageCollectorOptsTest.java
- server/gc/src/test/java/org/apache/accumulo/gc/SimpleGarbageCollectorTest.java
- server/master/src/main/java/org/apache/accumulo/master/Master.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/EmbeddedWebServer.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/MonitorExecutable.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
Create base class to help standardize the way Accumulo servers are
initialized from configuration files, launch, run, and clean up
resources during shutdown.
This establishes the base class as a concept, but over time, more
implementation that servers have in common can be put here, to make
server-side code more maintainable, and so the code in the individual
servers can be limited to the bits that make them different.
> Create AbstractServer type for Accumulo servers

- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/overview.ftl
Added "display:none" to table column - attempted to use bootstrap .hide but was attributed with !important so could not be overwritten.
> Fixes #593 Hide Master is Down message on startup

- assemble/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/accumulo/core/client/rfile/RFileWriter.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ConditionalWriterImpl.java
- core/src/main/java/org/apache/accumulo/core/iterators/system/VisibilityFilter.java
- core/src/main/java/org/apache/accumulo/core/iterators/user/RowEncodingIterator.java
- core/src/main/java/org/apache/accumulo/core/iterators/user/TransformingIterator.java
- core/src/main/java/org/apache/accumulo/core/iterators/user/VisibilityFilter.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/RowEncodingIteratorTest.java
- core/src/test/java/org/apache/accumulo/core/util/format/ShardedTableDistributionFormatterTest.java
- pom.xml
- server/base/pom.xml
- server/base/src/main/java/org/apache/accumulo/server/problems/ProblemReports.java
- server/base/src/main/java/org/apache/accumulo/server/util/RemoveEntriesForMissingFiles.java
- server/tserver/pom.xml
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogReader.java
- shell/pom.xml
- shell/src/main/java/org/apache/accumulo/shell/commands/TablesCommand.java
Just get some tests running in Travis
> Commons collections

- shell/src/main/java/org/apache/accumulo/shell/commands/ScanCommand.java
* Consistently use the shell's logger to print the error messages so
they don't get automatically mixed in to scan results output.
* Remove extraneous newlines in log messages
> Handle shell scan error messages consistently

- core/src/main/java/org/apache/accumulo/core/client/rfile/RFileWriter.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ConditionalWriterImpl.java
- core/src/main/java/org/apache/accumulo/core/iterators/system/VisibilityFilter.java
- core/src/main/java/org/apache/accumulo/core/iterators/user/TransformingIterator.java
- core/src/main/java/org/apache/accumulo/core/iterators/user/VisibilityFilter.java
- server/base/src/main/java/org/apache/accumulo/server/problems/ProblemReports.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogReader.java
- shell/src/main/java/org/apache/accumulo/shell/commands/TablesCommand.java
Since the update to commons-collections 4.3 in #1110, the LRUMap now
accepts generic parameter types. This change adds those that were
missing, which gives us better type safety when using these maps.
> Add missing LRUMap generic parameters

- test/src/main/java/org/apache/accumulo/test/BulkImportVolumeIT.java
- test/src/main/java/org/apache/accumulo/test/ImportExportIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkFileIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkSplitOptimizationIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
The main issue was importDirectory, when running a standalone instance, looked inside the users local filesystem instead of in hdfs which is what was causing this error. My fix for it was using the filesystem's default name key (mine being hdfs://localhost:8020 for example) and adding that to the front of the base path the test was using. This allowed the importDirectory function to have access to the full path so it would look inside hdfs instead of the users local filesystem. 
I added the delete on exit command since this change altered the test when run with MiniAccumuloCluster. The path wouldn't be just the tmp directory like it was previously so it wouldn't properly be deleted. This caused license issues when building. 
In reference to issue #1084
> Ref #1084 Fixes File not Found Error

- assemble/pom.xml
- assemble/src/main/assemblies/component.xml
- core/pom.xml
- core/src/main/java/org/apache/accumulo/core/client/ClientConfiguration.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/conf/SiteConfiguration.java
- core/src/main/java/org/apache/accumulo/core/file/blockfile/cache/impl/ClassSize.java
- minicluster/pom.xml
- minicluster/src/main/java/org/apache/accumulo/cluster/RemoteShellOptions.java
- minicluster/src/test/java/org/apache/accumulo/minicluster/MiniAccumuloClusterTest.java
- pom.xml
- start/pom.xml
- start/src/main/java/org/apache/accumulo/start/classloader/AccumuloClassLoader.java
- test/pom.xml
- test/src/main/java/org/apache/accumulo/harness/conf/AccumuloClusterPropertyConfiguration.java
- test/src/main/java/org/apache/accumulo/test/RewriteTabletDirectoriesIT.java
- test/src/main/java/org/apache/accumulo/test/VolumeIT.java
* Update dependencies
* Use FileBasedConfigurationBuilder to load configuration files
* Use PropertiesConfigurationLayout to serialize/deserialize when needed
* Simplified some calls to get system properties en route to updating
the PropertiesConfiguration usages.
Note: list delimiter is disabled by default now, so those API calls
aren't needed and were removed; also removed setThrowsOnMissing(false)
calls becuase that was also the default behavior
> Update to commons-configuration2.5

- test/src/main/java/org/apache/accumulo/harness/AccumuloClusterHarness.java
- test/src/main/java/org/apache/accumulo/test/IteratorEnvIT.java
- test/src/main/java/org/apache/accumulo/test/functional/AccumuloClientIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ManyWriteAheadLogsIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ReadWriteIT.java
- test/src/main/java/org/apache/accumulo/test/functional/YieldingIterator.java
AccumuloClientIT, - fixed in AccumuloClusterHarness (avoid setting Servercontext)  Will likely still fail if running SASL.  The tests were not cleaning up the users so used more the scheme already in the harness but that could really be cleaned up even more for all tests and probably a separate ticket.
ManyWariteaheadLogsIT - Needed to alter standalone config.
ReadWriteIT, -  reduced what was necessary to identify an SSL monitor and removed dependency on reading the props file.
YieldScannersIT, - adding a cleanup to the YieldingIterator
BadDeleteMarkers...IT and others that failed due to null in the command prefix - One solution is to always have an entry in the accumulo.it.properties file for server and client prefix but additionally added the cleanup in AccumuloClusterHarness to ensure …
> Fix #1084 partial - IT tests failing on Standalone

- fate/src/main/java/org/apache/accumulo/fate/zookeeper/ZooReader.java
- fate/src/main/java/org/apache/accumulo/fate/zookeeper/ZooUtil.java
- pom.xml
This fixes a bug in Accumulo where we were using an unauthenticated
ZooKeeper session to read ACLs on a node that we had previously written.
ZooKeeper 3.4.14 fixed a bug in their code that allowed unauthenticated
connections to read ACLs on paths for which they did not have READ
permission.
Using Accumulo with that version of ZooKeeper exposed the bug in our
code that passed the incorrect ZooKeeper session when retrieving ACLs.
> Ensures correct use of ZooKeeper getAcl

- core/src/main/java/org/apache/accumulo/core/client/mapreduce/lib/partition/RangePartitioner.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/mapreduce/lib/ConfiguratorBase.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/mapreduce/lib/DistributedCacheHelper.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/partition/RangePartitioner.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/lib/ConfiguratorBase.java
- shell/src/main/java/org/apache/accumulo/shell/ShellOptionsJC.java
- shell/src/test/java/org/apache/accumulo/shell/PasswordConverterTest.java
- test/src/main/java/org/apache/accumulo/test/mapred/TokenFileIT.java
- test/src/main/java/org/apache/accumulo/test/mapreduce/TokenFileIT.java
Update DistributedCacheHelper to both add a cached file to a MapReduce
job and to retrieve an InputStream from the DistributedCache (or HDFS,
if the item was not successfully cached).
Ensure uniqueness in the local cached file names and that the files are
read from the correct filesystem.
Add some tests to TokenFileIT
Specify the charset explicitly when java.util.Scanner is used (most
occurrences were related to code using the DistributedCache, but also
fixed two trivial occurrences in shell-related code).
> Improve the use of Hadoop's DistributedCache

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
I noticed that the time calculation is using nano times, but was not using a delta, which could cause a numerical overflow according to the System.nanoTime() javadocs.  Wondering if these changes would be "more" correct or if I'm missing something.  Did not look for other occurrences until confirmation that the current calculation could be an issue and my changes are an improvement.
> fixed time calculation to use nano delta

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/master/src/main/java/org/apache/accumulo/master/Master.java
Adds two parameters:
- MASTER_STARTUP_TSERVER_AVAIL_MIN_COUNT - sets desried number of tservers
- MASTER_STARTUP_TSERVER_AVAIL_MAX_WAIT - sets maximum time to wait.
This is the same changes submitted as pull request #1158 for 1.9.x, merged to
2.0.  Request #1158 will be available as a patch, but is not expected to be merged
becuase of semver requirements.
> Allow master start to block waiting for a number of tservers

- .travis.yml
- core/src/main/spotbugs/exclude-filter.xml
- hadoop-mapreduce/src/main/spotbugs/exclude-filter.xml
- minicluster/src/main/spotbugs/exclude-filter.xml
- pom.xml
- server/base/src/main/spotbugs/exclude-filter.xml
- server/master/src/main/spotbugs/exclude-filter.xml
- server/tracer/src/main/spotbugs/exclude-filter.xml
- server/tserver/src/main/spotbugs/exclude-filter.xml
* Configure Maven to build with Java 11
* Remove animal-sniffer (unnecessary with new javac release flag)
* Add exceptions to spotbugs to avoid false positive bug
(https://github.com/spotbugs/spotbugs/issues/756)
* Update Travis to use OpenJDK11
This is a much more conservative change than my initial. The build is broken, but it's much easier to do this incrementally. Eventually, all the build tests will be fixed, but this is a necessary starting point.
> Update Accumulo to build and run with Java 11

- core/src/main/java/org/apache/accumulo/core/cli/ClientOpts.java
This will also make CLI more backwards compatible for scripts and ease the pain of upgrading.  
I want to throw an error if user provides a legacy property but haven't figured out where to do that yet.
> Added a catch all for dropped Client properties.

- core/src/test/java/org/apache/accumulo/core/data/NamespaceIdTest.java
- core/src/test/java/org/apache/accumulo/core/data/TableIdTest.java
- pom.xml
- start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloVFSClassLoader.java
- start/src/test/java/org/apache/accumulo/start/classloader/vfs/AccumuloVFSClassLoaderTest.java
* Primarily fixes some bad unit tests
* But also helps build and run unit tests on Java 11
* Fixes #1195 Updates EasyMock and PowerMock
* Fixes #1194 Remove assumptions in AccumuloVFSClassLoader about the
type of the system class loader and the system's app class loader
(specifically, stop assuming they are a URLClassloader instance by
accounting for some other instances they could also be)
> Fix bad unit tests found while building on Java 11

- core/src/main/java/org/apache/accumulo/core/client/ZooKeeperInstance.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/InstanceOperationsImpl.java
- core/src/main/java/org/apache/accumulo/fate/zookeeper/ZooUtil.java
Revert "Revert "De-dupe some code (#1211)""
This reverts commit ca5b62d81b21a35bb260f1c5d3257811eeb9ae6e.
(This reverts the revert, and then adds fixes)
Preserve behavior prior to #1211 that verifies (using ZooCache) that the
instanceId actually points to a valid instanceId path in ZooKeeper.
This verification is done regardless of whether instanceId is resolved
using the instanceName, or if it is set explicitly in client
configuration (in the case of ZooKeeperInstance). It also verifies on
each call to getInstance() (just in case the instance is deleted from
ZooCache unexpectedly, things won't continue operating as though
everything is fine).
> Fix #1212 re-apply #1211 preserving prior behavior

- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/TabletMutatorBase.java
- server/base/src/main/java/org/apache/accumulo/server/util/MasterMetadataUtil.java
@keith-turner , I pushed this for review.  It's pretty straightforward.  the sunny tests ran and I ran many of the Split IT tests that seemed to use it.  In process of testing against the standalone instance I ran into problems and need to recreate my whole setup and will provide a status on that when its working.
Note my comment on the collections assumed "not null".  Personally I dislike null checks and usually try to ensure objects floating around are not null  and have noticed they are not prevalent in the code base BUT, often the checks do serve a needed purpose.
> Fix #1181 Update MasterMetadataUtil to use new Ample api

- test/src/main/java/org/apache/accumulo/harness/conf/AccumuloClusterPropertyConfiguration.java
This update changes logs to RuntimeExceptions so that bad standalone IT properties do not automatically convert to a mini cluster.
> Add exceptions to standalone IT property file loading (#1168)

- core/src/main/java/org/apache/accumulo/fate/AgeOffStore.java
- core/src/main/java/org/apache/accumulo/fate/Fate.java
- core/src/main/java/org/apache/accumulo/fate/FateTxId.java
- core/src/main/java/org/apache/accumulo/fate/ZooStore.java
- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
- server/base/src/main/java/org/apache/accumulo/server/iterators/MetadataBulkLoadFilter.java
- server/base/src/main/java/org/apache/accumulo/server/util/MasterMetadataUtil.java
- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer1/BulkImport.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer1/CleanUpBulkImport.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer1/CopyFailed.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer1/LoadFiles.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/BulkImportMove.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/CleanUpBulkImport.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/LoadFiles.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/TabletData.java
- shell/src/main/java/org/apache/accumulo/shell/commands/FateCommand.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkFailureIT.java
Before this change the bulk import code was serializing and logging fate
transaction ids differently than other parts of the code.  When adding
FATE transaction ids to blip markers, I decided it would be best if they
were consistently persisted (in metadata table ) and logged. That
decision made this change much larger than simply adding something to
the blip value, but I feel its worth it.
The following are the main changes :
* Introduce new class FateTxId with methods for consistenly formatting
fate transaction ids.
* Make bulk fate logging use FateTxId
* Update ~blip and loaded family to use FateTxId.  Made loaded family
backwards compat.
* Update existing fate logging code to use FateTxId.  Instead of
String.format
Follow on work to update all Repos to use FateTxId would be nice. …
> fix #1247 store fate txid in ~blip marker value

- core/src/main/java/org/apache/accumulo/core/metadata/schema/LinkingIterator.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/LinkingIteratorTest.java
The LinkingIterator checks the structure of the AccumuloMetadata table
as it is scans.   It was not properly handling a split of the first
tablet.  It was also not ensuring the last tablet for a table was seen.
This patch fixes those two issues.  These issues were discovered while
researching #1260, however I am not sure if these issues could have
caused #1260.
> correctly handle first and last tablets in LinkingIterator #1260

- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/MetadataTime.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadata.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/MetadataTimeTest.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/TabletMetadataTest.java
- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/TabletMutatorBase.java
- server/base/src/main/java/org/apache/accumulo/server/tablets/TabletTime.java
- server/base/src/main/java/org/apache/accumulo/server/util/MasterMetadataUtil.java
- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
- server/base/src/test/java/org/apache/accumulo/server/tablets/LogicalTimeTest.java
- server/base/src/test/java/org/apache/accumulo/server/tablets/MillisTimeTest.java
- server/base/src/test/java/org/apache/accumulo/server/tablets/TabletTimeTest.java
- server/master/src/main/java/org/apache/accumulo/master/TabletGroupWatcher.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/TableInfo.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/create/CreateTable.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/create/PopulateMetadata.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/TabletData.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitRecoveryIT.java
- test/src/main/java/org/apache/accumulo/test/performance/scan/CollectTabletStats.java
Created a MetadataTime object  and utilized the TimeType instead of a single
char M and L; Also removed the MetadataTableUtil.getDataFileSizes which
was only used by tests.  It was replaced with using
getFileAndLogEntries(..).getSecond();
Quite a few files were effected by this change but most of them are small.  More work can be done to clean the time data passed around.  I would like to remove the getMetadataValue methods from the TabletTime  (replaced with the getMetadataTime methods) but that can be a second pass.  Additionally I will write a small unit test for the MetadataTime class.
> Fix #1210 Create type for time in metadata

- core/src/main/java/org/apache/accumulo/core/client/lexicoder/ListLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/SequenceLexicoder.java
- core/src/test/java/org/apache/accumulo/core/client/lexicoder/ListLexicoderTest.java
- core/src/test/java/org/apache/accumulo/core/client/lexicoder/SequenceLexicoderTest.java
This provides a replacement for ListLexicoder that supports empty lists, resolving #1252 .
This PR replaces #1253 , which was originally targeted to `master` and Java 11. This one targets the `2.0` branch and Java 8.
> Created SequenceLexicoder to resolve #1252 (2.0)

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
Made the requested changes from Christopher in issue #1222. 
Tested using continuous ingest with agitation and did not run into the bug. Please let me know if I should do further testing or make any corrections
> Fix: #1222 Verify size is valid

- core/pom.xml
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/AbstractEncoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/BigIntegerLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/DateLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/DoubleLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/Encoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/FloatLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/IntegerLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/ListLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/PairLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/StringLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/TextLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/UIntegerLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/ULongLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/UUIDLexicoder.java
- core/src/main/java/org/apache/accumulo/core/iterators/LongCombiner.java
- core/src/main/java/org/apache/accumulo/core/iterators/TypedValueCombiner.java
- core/src/main/java/org/apache/accumulo/core/iterators/user/BigDecimalCombiner.java
- core/src/main/java/org/apache/accumulo/core/iterators/user/SummingArrayCombiner.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/BigDecimalCombinerTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/CombinerTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/VersioningIteratorTest.java
* Remove public API use of internal ValueFormatException and
TypedValueCombiner.Encoder interface
* Remove exception in Apilyzer configuration for ValueFormatException in
Lexicoder public APIs
* Remove redundant and no-longer needed TypedValueCombiner.Encoder
interface
* Remove unnecessarily overridden decode methods that merely call
super.decode; these were kept for binary compatibility, with very old
versions of Accumulo, but that can be dropped in a major version now,
since Accumulo code isn't compatible with those versions anyway.
> Lexicoder API improvements

- assemble/conf/log4j-service.properties
- test/src/main/resources/log4j.properties
We no longer have a dependency on mortbay versions of jetty, so there
should be no reason to regulate its spamminess in our config files.
> Purge mortbay logger from example configs

- core/src/main/java/org/apache/accumulo/core/metadata/schema/MetadataTime.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/MetadataTimeTest.java
- server/base/src/main/java/org/apache/accumulo/server/tablets/TabletTime.java
- server/base/src/test/java/org/apache/accumulo/server/tablets/TabletTimeTest.java
- server/master/src/main/java/org/apache/accumulo/master/TabletGroupWatcher.java
Replaced string processing with MetadataTime objects. 
Renamed MetadataTime class method valueOf(char) to getType(char) .  The valueOf was confusing and didn't really make sense once it was pulled from the ENUM TimeType class.
> Fix #1281 Update TabletTime.maxMetatdataTime

- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/gc/src/test/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogsTest.java
This fix moved the creation of the live tserver set to the simple garbage collector, outside of the run loop and passes it to the wal collector.
modified log message by putting guard to only print on changes and to include number of tservers.
> Fix #1314 fixes gc thread issue by creating one timed task instance

- shell/src/main/java/org/apache/accumulo/shell/commands/ImportDirectoryCommand.java
- shell/src/test/java/org/apache/accumulo/shell/commands/ImportDirectoryCommandTest.java
- test/src/main/java/org/apache/accumulo/test/ShellServerIT.java
Issue 1294.
the -t tablename is optional to preserve original behavior. Without
the option, the current table is used.
Contains new unit tests, need to look into adding IT or at least running on cluster before merging
> Add optional -t tablename to importdirectory shell command.

- server/master/src/main/java/org/apache/accumulo/master/Master.java
- server/master/src/main/java/org/apache/accumulo/master/TabletGroupWatcher.java
- server/master/src/main/java/org/apache/accumulo/master/state/MergeStats.java
- server/master/src/main/spotbugs/exclude-filter.xml
- shell/src/main/java/org/apache/accumulo/shell/commands/ImportDirectoryCommand.java
For review to close issue #1338 - this reduces one of the repeated messages.  
There is another that is being logged by TabletGroupWatcher - it seems to print all of the locations of the table being merged.  From a fast review, the change is not as obvious and will be dealt with separately.
> Reduce merge operations logging of extent info at - issue #1338

- server/master/src/main/java/org/apache/accumulo/master/TabletGroupWatcher.java
After merge of pull request #1348 - Shell It tests failed - this change moves the Accumulo client out of the try-with-resources and restores previous behavior.
> Avoid calling auto-close on Accumulo client

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/BulkImportCacheCleaner.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
While analyzing some tablet code I noticed a Guava cahce was being used
like a map.  When I first saw the code I was concerned the cache may
evict entries (which would be a bug).  However the cache was created
with default settings, which according to the javadoc does not
automatically evict.  This commit replaces the cache with a concurrent
map so no one has to do this analysis again.
> Use concurrent map instead of cache for bulkImported map

- core/src/main/java/org/apache/accumulo/core/metadata/schema/MetadataSchema.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/SortSkew.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/DeleteMetadataTest.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/SortSkewTest.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
- server/base/src/main/java/org/apache/accumulo/server/util/ListVolumesUsed.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorIT.java
This commit addresses the modification of metadata ~del mutations to reduce hotspots and stablize split points but does not yet address the migration update required.  
If this solution is accepted then the migration path would be to convert the existing ~del entries to the new ~del entries doing something like the following:
```
for each key with ~del prefix and value.isEmpty(){
create new del key with value("Converted on initialization")
delete old delete entry
}
```
> Fix #1043 Support stable ~del split points

- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/MetadataSchema.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
- server/master/src/main/java/org/apache/accumulo/master/upgrade/UpgradeCoordinator.java
- server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorIT.java
- test/src/main/java/org/apache/accumulo/test/upgrade/GCUpgrade9to10TestIT.java
- test/src/main/java/org/apache/accumulo/test/upgrade/GCUpgradeTestIT.java
This is fairly simple code to modify the ~del entries on the master upgrade startup.  The IT test is just for verification of the upgrade processsing and should probably not be included if this is actually merged.  Attempts to test this in a "real time" upgrade process were not successful due to errors unrelated to this code. (so she says ;))
> Fix #1365 2.1 Upgrade processing for #1043 ~del

- core/src/main/java/org/apache/accumulo/core/client/mapreduce/lib/impl/InputConfigurator.java
- test/src/main/java/org/apache/accumulo/test/mapreduce/AccumuloInputFormatIT.java
Currently, `InputConfigurator.validatePermissions` only checks whether the user has `Table.READ` permission. However, access may also be allowed if the user has `Namespace.READ` instead. This expands the check to pass if either permission is present. This resolves #1370 .
> Expanded InputConfigurator permissions checks to include Namespace.READ

- server/base/src/main/java/org/apache/accumulo/server/util/TabletIterator.java
- server/base/src/test/java/org/apache/accumulo/server/util/TabletIteratorTest.java
Added unit test to excercise the code that checks the consistency of the
metadata table during GC scans.  Also added a check to ensure the last
tablet was seen.  This should cause an error to be thrown if the scanner
stops returning data for any reason.  These changes were already made in
2.0 in #1266.  However the code in 1.9 is so different that they could
not be backported, but had to be reimplelmented.
> Improved metadata table consitency checking and testing

- assemble/bin/accumulo-service
accumulo-service currently writes pid files to $ACCUMULO_HOME/run by default.  this isn't so great in an environment where $ACCUMULO_HOME is shared.  this patch adds the ability to override the location of the PID directory in the same manner as the log directory.  adds ACCUMULO_PID_DIR which defaults to ${basedir}/run
> allow overriding of directory for pid files in accumulo-service

- server/tracer/src/main/java/org/apache/accumulo/tracer/AsyncSpanReceiver.java
- server/tracer/src/main/java/org/apache/accumulo/tracer/TraceServer.java
> Fixes #1398 trace server advertising default bind address (0.0.0.0) in zookeeper

- test/src/main/java/org/apache/accumulo/test/functional/GcMetricsIT.java
The test previously did not account for metrics that were published from previous runs or if multiple IT tests were run without cleaning the target directory.  The metrics are read from a file that is appended, so previous test values could cause test failures - with this change, the GcMetricsIT test ignores the first line and then processes the subsequent updates generated during the test.
> Fix GcMetricsIT test when multiple IT tests run

- core/src/main/java/org/apache/accumulo/core/client/lexicoder/AbstractLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/BigIntegerLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/BytesLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/DateLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/DoubleLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/FloatLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/IntegerLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/ListLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/PairLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/ReverseLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/SequenceLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/StringLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/TextLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/UIntegerLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/ULongLexicoder.java
- core/src/main/java/org/apache/accumulo/core/client/lexicoder/UUIDLexicoder.java
- core/src/main/java/org/apache/accumulo/core/iterators/LongCombiner.java
- core/src/main/java/org/apache/accumulo/core/iterators/user/BigDecimalCombiner.java
- core/src/main/java/org/apache/accumulo/core/iterators/user/SummingArrayCombiner.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/lexicoder/AbstractLexicoderTest.java
Curious as to why this is the only lexicoder class not in the public API... this change will assist in #1390
> Move AbstractLexicoder to API

- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeManager.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeManagerImpl.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
hsync() and hflush() are silent no-ops when using HDFS erasure coding.  this change will check the base WAL directory at tserver startup, and also check log files when they are created, to make sure they are not using EC.  right now this just generates a warning.
> check that the WAL directory and log files can sync

- test/src/main/java/org/apache/accumulo/test/functional/FateConcurrencyIT.java
- test/src/main/java/org/apache/accumulo/test/util/SlowOps.java
This is code back-port from Fate Metrics in 2.1 that improved the code for concurrency tests by refactoring the slow ops with common improvements.
> Fix #1308 - Refactor fate concurrency IT

- core/pom.xml
Hello, I noticed that dependencies `com.google.guava:listenablefuture`, `org.apache.httpcomponents:httpcore`, and `io.netty:netty` are not used. Hence, these transitive dependencies with compile scope can be safely excluded in the `pom`. This makes the core of accumulo slimmer in size and its dependency tree becomes less complex and easier to maintain.
> Exclude unused transitive dependencies

- test/src/main/java/org/apache/accumulo/harness/conf/AccumuloClusterPropertyConfiguration.java
Revert the revert for #1189 and cleanup the check to only throw error when appropriate.
>  Fix check for Standalone properties file. Fixes #1168 

- assemble/conf/accumulo-env.sh
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
* Concurrent Mark Sweep (CMS) garbage collector is deprecated in Java
9 and later, and will likely be removed in a future version
* This change removes the explicit use of a specific java garbage
collector, instead relying on users to configure their own in their
environment, as appropriate for their circumstances
* If users do not set their JVM garbage collector explicitly, then we
shouldn't override default Java behavior with our own preferred
default, which may be worse than Java's defaults
> Remove java flags for CMS java garbage collector

- server/master/src/main/java/org/apache/accumulo/master/Master.java
- server/master/src/main/java/org/apache/accumulo/master/upgrade/UpgradeCoordinator.java
- server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader.java
- server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader8to9.java
- server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java
While working on #1389 I noticed that tablets were being assigned to tservers
before their metadata was upgraded.  This commit makes assignment wait until a
tablets metadata is upgraded.  For example, assignment of the root tablet should
wait for zookeeper to be upgraded,  assignment of metadata tablets should wait
for the root tablet to be upgraded, and assignment of user tablets should wait
for metadata tablets to be upgraded.
The way waiting is done is by considering the upgrade status when computing
a tablets goal state.  If a tablets metadata store is not upgraded, then its
goal state will be unassigned.
> Made tablet assignment wait on upgrade.

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/scan/LookupTask.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/scan/ScanParameters.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/MultiScanSession.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/ScanSession.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/SingleScanSession.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Scanner.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
While working on #1383 I found it difficult to get caching parameters
from one part of the tserver to another for a scan.  The difficulty was
caused by many methods with many parameters that were mostly the same.
This commit changes the code to pass a single object around.
I decided to make these changes separate from #1383 inorder to make it
easier to review the changes for #1383.
> Streamline passing scan parameters within tserver

- server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java
- test/src/main/java/org/apache/accumulo/test/upgrade/GCUpgrade9to10TestIT.java
This changes the batching strategy for the Upgrader9to10 class.
The previous strategy was to fill a data structure until JVM memory was
sufficiently used up (50% of heap size), then process the upgrade for
those entries, and repeat until no more entries are left to upgrade.
This new strategy batches candidates for upgrade in batches of size 4
million characters (approx. 8MB batches), regardless of memory.
This stabilizes the testing, as it is much simpler to reproduce and test
fixed-size batches, than it is to manipulate the JVM heap size during
testing. As a result, many improvements to the GCUpgrade9to10TestIT were
made here. This also fixes that IT, which began failing with the use of
the G1GC instead of CMS (#1427), because G1GC didn't work well with a
master configured with a 16MB …
> Improve Upgrader9to10 code

- pom.xml
I found this very useful when debugging failed ITs.  The failsafe plugin will trim stack traces by default, only showing the error message.
> Turn off trim stacktrace on failsafe plugin

- server/master/src/main/java/org/apache/accumulo/master/Master.java
- server/master/src/main/java/org/apache/accumulo/master/recovery/RecoveryManager.java
For the case where a lot of tablet servers died, the master was
frequently checking for the existence of a recovery log for each tablet.
Its very likely that many tablets point to the same recovery logs and
the existence checks are redundant.  This patch caches the result of
existence checks for a short period.
> Temporarily cache existence of recovery wals

- core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java
- core/src/main/java/org/apache/accumulo/core/file/BloomFilterLayer.java
- core/src/main/java/org/apache/accumulo/core/file/FileOperations.java
- core/src/main/java/org/apache/accumulo/core/file/blockfile/impl/BasicCacheProvider.java
- core/src/main/java/org/apache/accumulo/core/file/blockfile/impl/CachableBlockFile.java
- core/src/main/java/org/apache/accumulo/core/file/blockfile/impl/CacheProvider.java
- core/src/main/java/org/apache/accumulo/core/file/blockfile/impl/OpportunisticBlockCache.java
- core/src/main/java/org/apache/accumulo/core/file/blockfile/impl/ScanCacheProvider.java
- core/src/main/java/org/apache/accumulo/core/file/map/MapFileOperations.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/MultiIndexIterator.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/RFile.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/RFileOperations.java
- core/src/main/java/org/apache/accumulo/core/iteratorsImpl/system/MapFileIterator.java
- core/src/main/java/org/apache/accumulo/core/iteratorsImpl/system/SequenceFileIterator.java
- core/src/main/java/org/apache/accumulo/core/spi/scan/DefaultScanDirectives.java
- core/src/main/java/org/apache/accumulo/core/spi/scan/ScanDirectives.java
- core/src/main/java/org/apache/accumulo/core/spi/scan/ScanDirectivesImpl.java
- core/src/main/java/org/apache/accumulo/core/spi/scan/ScanDispatcher.java
- core/src/main/java/org/apache/accumulo/core/spi/scan/SimpleScanDispatcher.java
- core/src/main/java/org/apache/accumulo/core/summary/SummaryReader.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/RFileTest.java
- core/src/test/java/org/apache/accumulo/core/spi/scan/SimpleScanDispatcherTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/FileManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/scan/ScanParameters.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/compaction/DefaultCompactionStrategyTest.java
This commit enables per scan control over cache usages.  This was done
via extending the scope of ScanDispatchers to include cache control.
The built in SimpleScanDispatcher was improved to support mapping
scanner execution hints of the form scan_type=X to
cache usage directives for a scan.
Accumulo caches open files.  Before this change the cache was bound to
the file when it was opened.  Now a cache can be bound to an already
open file. The internal interface CacheProvider was created to
facilitate this.
> Give scans control over cache via scan dispatchers #1383

- core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftTransportPool.java
The thrift transport pool closer thread was only stopping when shutdown
and there were connections to close.  If there was nothing to close, it
would keep running when shutdown.  This was causing test to hang.  Made
it always stop when shutdown.
> Always stop transport pool closer thread #1449

- core/src/main/java/org/apache/accumulo/core/client/admin/CloneConfiguration.java
- core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java
- core/src/main/java/org/apache/accumulo/core/client/impl/CloneConfigurationImpl.java
- core/src/main/java/org/apache/accumulo/core/client/impl/TableOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/client/mock/MockTableOperations.java
- core/src/test/java/org/apache/accumulo/core/client/impl/TableOperationsHelperTest.java
- server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/CloneInfo.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/CloneTable.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/FinishCloneTable.java
- shell/src/main/java/org/apache/accumulo/shell/commands/CloneTableCommand.java
- test/src/main/java/org/apache/accumulo/test/ShellServerIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CloneTestIT.java
* Added an optional keepOffline option to TableOperations.clone
* Updated the shell clone command with a -k option
* Updated the CloneTestIT to test the keepOffline option
> fixes #1474: Option to leave cloned tables offline

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java
Changes in 2.x to DatafileManager with how the root table stores its metadata left only one call to waitForScansToFinish, where it always passed in a false boolean.  See PR #1313
> Remove unreachable code in DatafileManager

- core/src/main/java/org/apache/accumulo/core/metadata/TabletFileUtil.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeUtil.java
- server/base/src/test/java/org/apache/accumulo/server/fs/VolumeUtilTest.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/master/src/main/java/org/apache/accumulo/master/recovery/RecoveryManager.java
* Make VolumeUtil.switchVolume() return the Path object it created
instead of returning a string. This allows callers to use the Path
object or call toString if one is needed. There are a few cases where
the string returned was used to create another Path object
> Reduce Path obj creation with VolumeUtil

- core/src/main/java/org/apache/accumulo/core/logging/Logging.java
- core/src/main/java/org/apache/accumulo/core/logging/TabletLogger.java
- core/src/main/java/org/apache/accumulo/core/logging/package-info.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java
- server/base/src/main/java/org/apache/accumulo/server/master/state/Assignment.java
- server/base/src/main/java/org/apache/accumulo/server/master/state/LoggingTabletStateStore.java
- server/base/src/main/java/org/apache/accumulo/server/master/state/MetaDataStateStore.java
- server/base/src/main/java/org/apache/accumulo/server/master/state/RootTabletStateStore.java
- server/base/src/main/java/org/apache/accumulo/server/master/state/TabletStateStore.java
- server/base/src/main/java/org/apache/accumulo/server/master/state/ZooTabletStateStore.java
- server/base/src/main/java/org/apache/accumulo/server/util/FindOfflineTablets.java
- server/base/src/test/java/org/apache/accumulo/server/master/state/RootTabletStateStoreTest.java
- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java
- server/master/src/main/java/org/apache/accumulo/master/Master.java
- server/master/src/main/java/org/apache/accumulo/master/TabletGroupWatcher.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Compactor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/MinorCompactor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- test/src/main/java/org/apache/accumulo/test/MasterRepairsDualAssignmentIT.java
- test/src/main/java/org/apache/accumulo/test/master/MergeStateIT.java
- test/src/main/java/org/apache/accumulo/test/performance/NullTserver.java
Centralized in code logging related to tablet files and location.
Removed and supressed redundant logging, with the goal of logging a
single message for an event like assignment or compaction.
> Clean up tablet event logging #1316

- core/src/main/java/org/apache/accumulo/fate/zookeeper/ZooSession.java
Updated class to use nanoTime() as the base start time for duration calculations.
> Fixes #1458 - ZooSession now uses nanoTime vice currentTimeMillis

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java
* Stop creating a second HashMap in DatafileManager when the calling
method in Tablet already creates a HashMap for this method
The only place this method is called is in Tablet [here](https://github.com/apache/accumulo/blob/7a2ab3bccb32e57cb6f82bdbf6c7d06ea887f876/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java#L2314).
> Optimize DatafileManager bulk import method

- test/src/main/java/org/apache/accumulo/test/SampleIT.java
While updating another issue I noted two occasions where created BatchScanner's were not closed properly. This update closes them to remove the exception output that appeared in the test output.
> Close open BatchScanner's in SampleIT

- core/src/main/java/org/apache/accumulo/core/util/UnsynchronizedBuffer.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/RelativeKeyTest.java
- core/src/test/java/org/apache/accumulo/core/util/UnsynchronizedBufferTest.java
Limit UnsynchronizedBuffer maximum size to Integer.MAX_VALUE - 8, the
same limit as ArrayList, because of some JVM behavior being unable to
allocate arrays with Integer.MAX_VALUE.
> Fix #1520 Limit UnsynchronizedBuffer max size

- server/master/src/main/java/org/apache/accumulo/master/Master.java
* This should help timing of ITs which deal with recovery but will
still prevent too many exist calls to NN in production
> Decrease recovery cache time from 45s to 15s

- core/pom.xml
- minicluster/pom.xml
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
- pom.xml
- server/base/pom.xml
- server/base/src/main/java/org/apache/accumulo/server/zookeeper/DistributedWorkQueue.java
- server/master/pom.xml
- test/src/test/java/org/apache/accumulo/test/fate/zookeeper/ZooLockTest.java
This change bumps our ZooKeeper minimum version to the latest patch release of 3.5, which eliminates our last log4j 1.2 transitive dependency.
This work was previously stalled due to https://issues.apache.org/jira/browse/ZOOKEEPER-3737, but the workaround suggested there to disable log4j jmx for minicluster works fine.
> Bump ZooKeeper dependency to 3.5.7

- core/src/main/java/org/apache/accumulo/core/logging/FateLogger.java
- core/src/main/java/org/apache/accumulo/fate/Fate.java
- server/master/pom.xml
- server/master/src/main/java/org/apache/accumulo/master/Master.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/TraceRepo.java
This change add detailed trace logging for FATE.  To enable this add the following to `log4j-service.properties`
```
log4j.logger.org.apache.accumulo.fate.store=TRACE
```
The following is logging output when trace is enabled for create table FATE transaction.
```
2020-02-20 15:59:54,574 [fate.store] TRACE: created FATE[38dabaad752bd105]
2020-02-20 15:59:54,623 [fate.store] TRACE: pushed FATE[38dabaad752bd105] class org.apache.accumulo.master.tableOps.create.CreateTable {"tableInfo":{"tableName":"test99","namespaceId":{"canonical":"+default"},"timeType":"MILLIS","user":"root","initialTableState":"ONLINE","initialSplitSize":0,"props":{"table.iterator.majc.vers":"20,org.apache.accumulo.core.iterators.user.VersioningIterator","table.constraint.1":"org.apache.accumulo.core.constraints.DefaultKe …
```
> Added detailed trace logging for FATE #1316

- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeUtil.java
I bisected the commits in 1.9 and found commit that broke VolumeIT.  It was:
7513626cc Optimize Tablet volume replacement (#1505)
> Fixes #1525 - remove lines added in b67d3f9 in VolumeUtil

- core/src/main/java/org/apache/accumulo/core/client/admin/DiskUsage.java
- core/src/main/java/org/apache/accumulo/core/client/mapreduce/InputTableConfig.java
- core/src/main/java/org/apache/accumulo/core/data/Condition.java
Utilize newer Java language features to simplfy code by using Object.equals() rather than equals().
> Replace use of equals() with Object.equals()

- core/src/main/java/org/apache/accumulo/core/clientImpl/ServerClient.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftTransportPool.java
* Inline method overrides only called once or twice. They obscure actual
method calls and bloat the code
> Drop obscuring overrides in thrift client code

- test/src/main/java/org/apache/accumulo/test/functional/HalfDeadTServerIT.java
- test/src/main/resources/log4j2-test.properties
- test/src/test/c/fake_disk_failure.c
Remove use of miniDFS from IT, because sometimes miniDFS is slow to
start up, and it causes the IT to time out. It is not needed for the
test, since the test case works fine on LocalFileSystem-based DFS.
Use java.util.scanner to clean up boilerplate BufferedReader stuffs.
Suppress some spammy ZK logs in IT log4j2 config.
Add prefix to DumpOutput class in HalfDeadTServerIT to help troubleshoot
the IT in future.
> Remove miniDFS from HalfDeadTServerIT

- core/src/main/java/org/apache/accumulo/core/rpc/TTimeoutTransport.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- start/src/main/java/org/apache/accumulo/start/Main.java
Remove unnecessary reflection to load methods that are contained in
public stable Hadoop APIs.
This reflection was added for simultaneous Hadoop 1 and Hadoop 2
support. We now require Hadoop 3 and these APIs are stable, so
reflection is not needed.
Also reduce visibility of some methods in TTimeoutTransport exposed for
testing and delete unnecessary code.
> Remove some reflection where not needed

- core/src/main/java/org/apache/accumulo/core/volume/VolumeConfiguration.java
- server/base/src/main/java/org/apache/accumulo/server/ServerConstants.java
- server/base/src/main/java/org/apache/accumulo/server/fs/InterfaceEvolutionWarner.java
- server/base/src/main/java/org/apache/accumulo/server/fs/PerTableVolumeChooser.java
- server/base/src/main/java/org/apache/accumulo/server/fs/PreferredVolumeChooser.java
- server/base/src/main/java/org/apache/accumulo/server/fs/RandomVolumeChooser.java
- server/base/src/main/java/org/apache/accumulo/server/fs/SpaceAwareVolumeChooser.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeChooser.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeManager.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeManagerImpl.java
- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
- server/base/src/main/java/org/apache/accumulo/server/util/ZooKeeperMain.java
- server/base/src/main/java/org/apache/accumulo/server/util/ZooZap.java
- server/base/src/test/java/org/apache/accumulo/server/ServerConstantsTest.java
- server/base/src/test/java/org/apache/accumulo/server/fs/PreferredVolumeChooserTest.java
- server/base/src/test/java/org/apache/accumulo/server/fs/SpaceAwareVolumeChooserTest.java
- server/base/src/test/java/org/apache/accumulo/server/fs/VolumeManagerImplTest.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/tableImport/CreateImportDir.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/TabletServerSyncCheckTest.java
- test/src/main/java/org/apache/accumulo/test/FairVolumeChooser.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitRecoveryIT.java
Originally ACCUMULO-3376, this change replaces the use of `String[]`
with `Set<String>` throughout the VolumeChooser and VolumeManager code.
This makes the API for VolumeChooser a bit more friendly, making it
easier to use Streams and lambdas to filter and transform volumes
throughout the code.
This change also adds some more sanity checks on the instance volumes
configuration (checking for empty list and duplicates).
This also includes a utility to warn about planned API changes in
internal pluggable code (such as the VolumeChooser), but without being
too spammy.
Update the default `VolumeChooser.choosable()` to return the full set of
volumes, so that all are checked for flush and sync support on tserver
startup. This choosable mechanism is a bit dubious anyway, because
choosers could …
> Use sets instead of arrays for volumes

- core/src/test/java/org/apache/accumulo/core/clientImpl/lexicoder/ByteUtilsTest.java
- core/src/test/java/org/apache/accumulo/core/conf/AccumuloConfigurationTest.java
- core/src/test/java/org/apache/accumulo/core/conf/ClientPropertyTest.java
- core/src/test/java/org/apache/accumulo/core/crypto/CryptoTest.java
- core/src/test/java/org/apache/accumulo/core/util/PreAllocatedArrayTest.java
- core/src/test/java/org/apache/accumulo/core/util/UnsynchronizedBufferTest.java
- core/src/test/java/org/apache/accumulo/fate/util/RetryTest.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/mapred/AccumuloInputFormatTest.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/mapreduce/AccumuloInputFormatTest.java
- pom.xml
- server/base/src/test/java/org/apache/accumulo/server/fs/PerTableVolumeChooserTest.java
- server/base/src/test/java/org/apache/accumulo/server/fs/PreferredVolumeChooserTest.java
- server/base/src/test/java/org/apache/accumulo/server/fs/VolumeManagerImplTest.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/InMemoryMapTest.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/compaction/CompactionPlanTest.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/log/SortedLogRecoveryTest.java
- start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoader.java
- start/src/test/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoaderTest.java
- test/pom.xml
- test/src/main/java/org/apache/accumulo/test/functional/ClassLoaderIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ScannerContextIT.java
- test/src/main/java/org/apache/accumulo/test/functional/TableIT.java
- test/src/main/java/org/apache/accumulo/test/rpc/ThriftBehaviorIT.java
Fix warnings due to updated dependencies
* Use new vfs2 method instead of deprecated one
* Use assertThrows instead of ExpectedException
* Remove hamcrest dependency, because it's not needed any more
> Update dependency and plugin versions

- test/src/main/java/org/apache/accumulo/test/functional/ManyWriteAheadLogsIT.java
CLOSED and UNREFERENCE WALS (not OPEN) causing open == 0
> Fixes #1488 - ManyWriteAheadLogsIT asserts open WALS equal to zero.

- test/src/main/java/org/apache/accumulo/test/NamespacesIT.java
- test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java
* Using `Assert.assertThrows()` with lambda
* Replace expected exception parameter
* Replace complex try/catch statements
* Avoid most uses of `Assert.fail()`
* Replace absurd switch statements in NamespacesIT for checking
multiple operations with complex exception handling checks with
convenience methods that takes a lambda and use assertThrows and any
follow on cause checks
* Make waiting-on-constraint changes to retry until test times out
* Replace `Assert.assertTrue(!p)` with `Assert.assertFalse(p)`
* Use `StringUtils.repeat` to construct long table/namespace names
* Use `Assert.assertSame` instead of switch statements to check enums
> Improve TableOperationsIT and NamespacesIT

- assemble/conf/log4j2-service.properties
- core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/Compression.java
When running 2.1.0-SNAPSHOT locally I am seeing debug logs for lots of dependencies (like Hadoop and Guava) in the tserver logs.  This makes the default configuration unusable for me.  This change narrows the default config to only have debug logging for Accumulo and info for everything else.
> Narrow default debug logging to only Accumulo

- core/src/main/java/org/apache/accumulo/core/client/ZooKeeperInstance.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- server/base/src/main/java/org/apache/accumulo/server/ServerContext.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/replication/AccumuloReplicaSystem.java
* Moved some logic to classes creating ClientContext objects
* Overloaded constructors obscured the object creation and static
singleton management
* Also commented the constructor
> Drop overloaded ClientContext constructors

- shell/src/main/java/org/apache/accumulo/shell/commands/ImportDirectoryCommand.java
**Fix details**
The importdirectory command implementation within the shell now checks for the expected number of arguments and safely handles the case where no arguments are supplied for importdirectory.
**Bug details**
The issue is trivial to reproduce (in master and in publicly released Accumulo 2.0.0 as well). Just switch to a table context within the Accumulo shell and issue an importdirectory command without any arguments:
```
root@uno t1> importdirectory 
2020-03-24T22:16:16,107 [shell.Shell] ERROR: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
```
> Fix ArrayIndexOutOfBoundsException in importdir

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer1/BulkImport.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/tableImport/MoveExportedFiles.java
Improves performance as calls to fs.rename are now made in parallel
from multiple threads within a SimpleThreadPool. Thread pool size is
controlled by new property master.importtable.rename.threadpool.size
> Fixes #1464 - SimpleThreadPool for importtable

- assemble/bin/accumulo-cluster
- assemble/bin/accumulo-service
- assemble/conf/accumulo-env.sh
If NUM_TSERVERS is defined (typically by adding it in accumulo-env.sh
this modification to accumulo-service enables trivial support for
running more than 1 tserver per node. Of course, the corresponding
changes in accumulo.properties (tserver.port.search and
replication.receipt.service.port) are still needed.
> Support multiple tservers / node in accumulo-service

- server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java
- server/base/src/test/java/org/apache/accumulo/server/util/TServerUtilsTest.java
Fixes #1573. Includes debug logging for ports being skipped. This has been tested by running 4 TableServer instances on a single node using Uno. Debug logs added in this PR are below, clearly showing the reserved ports being skipped:
```
2020-03-28T15:04:31,877 [rpc.TServerUtils] WARN : Error attempting to create server at 0.0.0.0:9997. Error: Could not create ServerSocket on address /0.0.0.0:9997.
2020-03-28T15:04:31,883 [rpc.TServerUtils] DEBUG: Adding port 9999 to list of restricted ports
2020-03-28T15:04:31,884 [rpc.TServerUtils] DEBUG: Adding port 10001 to list of restricted ports
2020-03-28T15:04:31,884 [rpc.TServerUtils] DEBUG: Adding port 9997 to list of restricted ports
2020-03-28T15:04:31,884 [rpc.TServerUtils] DEBUG: Adding port 9998 to list of restricted ports …
```
> Skip restricted ports in TServer port search

- pom.xml
Newer spotbugs release uses newer version of asm, required for parsing
class files created with newer JDK versions. Spotbugs 4.0.0 supports at
least Java 13, possibly up to 15.
> Bump spotbugs to 4.0

- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/tableImport/CreateImportDir.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/tableImport/FinishImportTable.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/tableImport/ImportPopulateZookeeper.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/tableImport/ImportTable.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/tableImport/ImportedTableInfo.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/tableImport/MapImportFileNames.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/tableImport/MoveExportedFiles.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/tableImport/PopulateMetadataTable.java
- server/master/src/test/java/org/apache/accumulo/master/tableOps/tableImport/ImportTableTest.java
- test/src/main/java/org/apache/accumulo/test/ImportExportIT.java
- Import table now takes a comma-delimited set of directories
to import from. A separate mapping file is generated for each
and the rfiles are loaded into the volume corresponding to
each directory.
- It is expected that there will be a single export metadata zip file
present in one of the import directories.
- Currently a work in progress, needs unit/integration tests
up for early review to validate the approach
> Closes #1053 add multi-volume support to import table command.

- server/base/src/main/java/org/apache/accumulo/server/ServerContext.java
- server/base/src/main/java/org/apache/accumulo/server/ServiceEnvironmentImpl.java
- server/base/src/main/java/org/apache/accumulo/server/client/ClientServiceHandler.java
- server/base/src/main/java/org/apache/accumulo/server/conf/ConfigSanityCheck.java
- server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java
- server/base/src/main/java/org/apache/accumulo/server/conf/ZooConfiguration.java
- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
- server/base/src/main/java/org/apache/accumulo/server/master/balancer/HostRegexTableLoadBalancer.java
- server/base/src/main/java/org/apache/accumulo/server/master/balancer/RegexGroupBalancer.java
- server/base/src/main/java/org/apache/accumulo/server/master/balancer/TableLoadBalancer.java
- server/base/src/main/java/org/apache/accumulo/server/replication/ReplicationUtil.java
- server/base/src/main/java/org/apache/accumulo/server/tabletserver/LargestFirstMemoryManager.java
- server/base/src/main/java/org/apache/accumulo/server/util/LoginProperties.java
- server/base/src/test/java/org/apache/accumulo/server/master/balancer/HostRegexTableLoadBalancerReconfigurationTest.java
- server/base/src/test/java/org/apache/accumulo/server/master/balancer/HostRegexTableLoadBalancerTest.java
- server/base/src/test/java/org/apache/accumulo/server/master/balancer/TableLoadBalancerTest.java
- server/master/src/main/java/org/apache/accumulo/master/Master.java
- server/master/src/main/java/org/apache/accumulo/master/TabletGroupWatcher.java
- server/master/src/main/java/org/apache/accumulo/master/replication/WorkMaker.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/tableExport/WriteExportFiles.java
- server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java
- server/tracer/src/main/java/org/apache/accumulo/tracer/TraceServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/FileManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
Divided this PR into 2 commits:
~~1 - Deprecates the init method in MemoryManager that took ServerConfigurationFactory as a parameter.  Replace it with a method that takes ServerContext.  Updated Test to mock ServerContext.~~
2 -  Inline some of the methods of ServerConfigurationFactory into ServerContext to reduce references to it.  Removed sychronization on the methods now they are a part of ServerContext because i don't think its needed since each server should only have one instance.  This is just a first step into eliminating internal use of ServerConfigurationFactory.
Update: Broke out changes to MemoryManager in a separate branch.
> Refactor use of ServerConfigurationFactory

- pom.xml
Removed errorprone profile from pom.xml as it currently does not work with jdks above 8 using maven. May re-introduce in the future if the status changes.
> Remove errorprone profile from pom.xml

- .gitignore
- pom.xml
Added VSCode resources to .gitignore and apache-rat excludes (#1582)
> Fix #1582 Ignore VSCode IDE files

- server/base/src/main/java/org/apache/accumulo/server/client/ClientServiceHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/AssignmentHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ThriftClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/UnloadTabletHandler.java
Moved ThriftClientHandler into it's own file out of TabletServer. Also moved AssignmentHandler and UnloadTabletHandler into separate files (from TabletServer) since they are created by ThriftClientHandler and can no longer be inner classes.
ThriftClientHandler is still tightly coupled to TabletServer and can't really exist on it's own.
> Moved ThriftClientHandler out of TabletServer for #1581

- test/src/main/java/org/apache/accumulo/test/gc/replication/CloseWriteAheadLogReferencesIT.java
- test/src/main/java/org/apache/accumulo/test/performance/scan/CollectTabletStats.java
* Only use ServerConfigurationFactory outside of ServerContext where it
is used in API and tests
> Use ServerContext instead of conf factory

- core/src/main/java/org/apache/accumulo/core/data/Key.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/FileManager.java
Make use of the Long.compare() method, introduced in JDK 7, to compare longs instead of more verbose constructs.
> Use Long.compare() to compare longs values.

- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletLocatorImpl.java
- core/src/main/java/org/apache/accumulo/core/conf/IterConfigUtil.java
- core/src/main/java/org/apache/accumulo/core/iterators/user/TransformingIterator.java
- core/src/main/java/org/apache/accumulo/fate/ZooStore.java
- core/src/test/java/org/apache/accumulo/core/client/lexicoder/LexicoderTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/RFileTest.java
- core/src/test/java/org/apache/accumulo/core/spi/scan/HintScanPrioritizerTest.java
- core/src/test/java/org/apache/accumulo/core/spi/scan/IdleRatioScanPrioritizerTest.java
- server/base/src/main/java/org/apache/accumulo/server/master/balancer/DefaultLoadBalancer.java
- server/tracer/src/main/java/org/apache/accumulo/tracer/TraceDump.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/CompactionQueue.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ConditionalMutationSet.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compaction/DefaultCompactionStrategy.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/LogSorter.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/compaction/DefaultCompactionStrategyTest.java
- shell/src/main/java/org/apache/accumulo/shell/commands/ActiveCompactionIterator.java
- shell/src/main/java/org/apache/accumulo/shell/commands/GetAuthsCommand.java
- test/src/main/java/org/apache/accumulo/test/functional/NativeMapIT.java
As of JDK 1.8, calls to Collections.sort(list, comparator) can be replaced with List.sort(comparator).
> Replace Collections.sort() with List.sort()

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java
Fix #1588 : Refine rename during minor compaction
PR addresses a few issues:	
- Spurious rename failures where rename failed but actually succeeded
- The check for file existence should only be done before attempting rename
- Should not delete file if it exists (an admin may want to investigate).
> Handle spurious failure were rename succeeded but reported it failed (#1588)

- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletLocatorImpl.java
The 'updateCache' method within TabletLocatorImpl.java contains two identical 'if' conditions, both of which throw 'IllegalStateExceptions'. I removed the second, given that it would never be reached if the
condition is true. Even though the conditional checks are identical, the message provided to the exceptions differ. I kept the first since that would be the one presented to the user if this condition was satisfied.
> Removed duplicate 'if' condition in TabletLocatorImpl.

- core/src/main/java/org/apache/accumulo/core/clientImpl/ReplicationClient.java
- test/src/main/java/org/apache/accumulo/test/ThriftServerBindsBeforeZooKeeperLockIT.java
ReplicationClient.java and ThriftServerBindsBeforeZooKeeperLockIT.java contain instances of 'while' loops which never loop.
In the case of ReplicationClient, the loop is always entered but either returns or throws an exception.
ThriftServerBindsBeforeZooKepperLockIT contains three 'while' blocks that never loop. Each of the outer 'while' blocks contain another 'while' which does loop until a condition is met resulting in a  'return' case being satisfied.
The outer loop does not appear to be necessary in each of these cases. These loops have been removed to increase readability of the code.
> Remove non-looping 'while' loops.

- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeManager.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeManagerImpl.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/BulkImportMove.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/tableImport/MoveExportedFiles.java
* Refactor fate code in BulkImportMove (bulkVer2) and MoveExportedFiles to call the
new method for handling renames of lots of files
* Work related to #1620 
* Made bulkRename method return the list of completed Futures so FATE operations can handle errors accordingly
> Create bulkRename method in VolumeManager

- core/src/main/java/org/apache/accumulo/core/client/Connector.java
- test/src/main/java/org/apache/accumulo/test/functional/AccumuloClientIT.java
While working on apache/fluo-recipes#150 I encountered a situation where was being passed a Connector.  I could not easily change the method being passed a connector.  I wanted to refactor the code being passed a connector to use an AccumuloClient internally, however I could not see a way to convert a connector to a client using Accumulo's public API. That is why this PR was created.
> Add method to create client from connector

- core/pom.xml
According to the link https://bugs.eclipse.org/bugs/show_bug.cgi?id=541772#c30, I observed that such issue had already been fixed in 4.12M1 release. The workaround for this profile is not needed in my opinion.
I suggest to remove this profile.
The workaround profile:
https://github.com/apache/accumulo/blob/07bc9d329ea0b8da9a577863acfe009910e189cd/core/pom.xml#L386-L401
> Remove an workaround profile exists in core/pom.xml file since the related issue had been already fixed.

- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
- minicluster/src/main/java/org/apache/accumulo/minicluster/MiniAccumuloRunner.java
- test/src/main/java/org/apache/accumulo/test/functional/FateConcurrencyIT.java
- test/src/main/java/org/apache/accumulo/test/functional/MasterMetricsIT.java
- test/src/main/java/org/apache/accumulo/test/util/SlowOps.java
This patch fixes periodic FateConcurrencyIT failures due to insufficient
threads available for concurrent compactions, caused by the introduction
of the property
'tserver.compaction.major.service.default.planner.opts.executors' to
replace 'tserver.compaction.major.concurrent.max'.
This change now sets a sufficient number of executors to run the test
consistenly, when one tserver tries to compact 3 or 4 of the 4 total
tables, and the other is responsible for compacting only 0 or 1.
Additionally:
* Fix a javadoc issue for the improper use of less-than symbol in
DefaultCompactionPlanner
* Use a non-deprecated property as an example in MiniAccumuloRunner
instead of the deprecated 'tserver.compaction.major.concurrent.max'
* Set instance-wide compaction property only once instead of each time a …
> Fix FateConcurrencyIT periodic failures

- .gitignore
-  Added the JetBrains IDE `*.ipr` and `*.iws` with are generated by IntelliJ.
---
Signed-off-by: ben <git@benjamin.ie>
> Ignore IntelliJ IDE .ipr and .iws files

- assemble/conf/templates/hadoop-metrics2-accumulo.properties
- pom.xml
- test/pom.xml
- excluded hadoop-metrics2-accumulo.properties from jar plugin
- added gc metrics config sample to template
> Fix #1663 - Missing metrics files running CI tests

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/MinorCompactionTask.java
* Fixes the situation when MinorCompactionTask creates a
new File and an IOException leaves the Tablet in a bad state
* Moves the new file code into the try/catch block that will
retry during an IOException
I was not able to create a test for this scenario but I did simulate it by manually throwing the exception in the Tablet code.  I ran TableIT with the simulated IOException and it was able to recover.
> Move MinorCompaction method call into retry catch block. Fixes #1298

- iterator-test-harness/src/main/java/org/apache/accumulo/iteratortest/IteratorTestInput.java
- iterator-test-harness/src/main/java/org/apache/accumulo/iteratortest/testcases/DeepCopyTestCase.java
- iterator-test-harness/src/main/java/org/apache/accumulo/iteratortest/testcases/IsolatedDeepCopiesTestCase.java
- iterator-test-harness/src/main/java/org/apache/accumulo/iteratortest/testcases/MultipleHasTopCalls.java
- iterator-test-harness/src/main/java/org/apache/accumulo/iteratortest/testcases/ReSeekTestCase.java
- iterator-test-harness/src/main/java/org/apache/accumulo/iteratortest/testcases/YieldingTestCase.java
- test/src/test/java/org/apache/accumulo/test/iterator/SummingCombinerTest.java
* Adds the ability to provide a custom IteratorEnvironment to the
iterator-test-harness
* This fixes a test failure in SummingCombinerTest caused by recent
changes to Combiner in #1680
Note: this only fixes the test failure after merging to the main branch. There is no test failure in the 1.10 branch because for some reason, these tests are not executing in the 1.10 builds.
> Support IteratorEnvironment in test harness

- pom.xml
Fix permissions mangling caused by the latest versions of the assembly
plugin.
Use maven-assembly-plugin-3.1.1 because of MASSEMBLY-941
https://issues.apache.org/jira/browse/MASSEMBLY-941
> Fix file permissions in source assembly tarball

- server/base/src/main/java/org/apache/accumulo/server/master/state/MetaDataStateStore.java
- server/base/src/main/java/org/apache/accumulo/server/util/MasterMetadataUtil.java
- test/src/main/java/org/apache/accumulo/test/functional/MasterAssignmentIT.java
This the one-line change leftover after the revert of pull request #1453. The rest of those changes will be tested more thoroughly and hopefully can be salvaged. In the meantime, this change fixes the issue without a bunch of the refactoring done in the previous pull request. I apologize for the delay. 
I ran the entire IT suite, and I didn't see any relavent breakages from this change besides the one mentioned below. 
Also, an AssertNull was removed from the MasterAssignmentIT. Let me know if that is acceptable or if I need to refactor that IT further.
> Update Last Location. Fix #1169 

- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/lib/InputConfigurator.java
- test/src/main/java/org/apache/accumulo/test/NamespacesIT.java
For ticket #1385 ------- I added the Namespace.READ fix from ticket #1371 to the new accumulo-hadoop MapReduce module code. Before the fix, InputConfigurator.validatePermissions only checks whether the user has Table.READ permission. Now, access may also be allowed if the user has Namespace.READ instead.
> #1385 Ensure Namespace.READ is sufficient for fast-failure checks in new

- core/src/main/java/org/apache/accumulo/core/client/Instance.java
- core/src/main/java/org/apache/accumulo/core/client/ZooKeeperInstance.java
- core/src/main/java/org/apache/accumulo/core/client/admin/InstanceOperations.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/InstanceOperationsImpl.java
* Partially revert bc6fa04283d1dda3bfcde5ef193027d171adb37b to prevent
addition of new API methods in already-deprecated API classes (#1703)
* Add a new getManagerLocations() API to InstanceOperations
> Add new public API to get manager locations

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
This is in relation to #1664. This allows the batch size for garbage collecting implemented in #1650 to be configurable. 
After a discussion with @ctubbsii, I determined that I couldn't fully test out the upper limits (batch sizes of 64MB for example). With that in mind, I went ahead and made it configurable but kept it at its current default batch size.
> Related #1664. Allow Candidate batch size to be user configurable

- core/src/main/java/org/apache/accumulo/core/clientImpl/ReplicationOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadata.java
- core/src/main/java/org/apache/accumulo/core/tabletserver/log/LogEntry.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/TabletMetadataTest.java
- core/src/test/java/org/apache/accumulo/core/tabletserver/log/LogEntryTest.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeUtil.java
- server/base/src/main/java/org/apache/accumulo/server/master/state/MetaDataStateStore.java
- server/base/src/main/java/org/apache/accumulo/server/master/state/ZooTabletStateStore.java
- server/manager/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- test/src/main/java/org/apache/accumulo/test/MissingWalHeaderCompletesRecoveryIT.java
- test/src/main/java/org/apache/accumulo/test/replication/ReplicationIT.java
- test/src/main/java/org/apache/accumulo/test/replication/ReplicationOperationsImplIT.java
* Remove unused server parameter from the WAL LogEntry
* Remove overloaded fromKeyValue method and rename to fromMetaWalEntry
* Remove unused LogEntry copy constructor
* Prevent extent inside LogEntry from leaving LogEntry by making it
private, to ensure prevEndRow won't matter in any code outside the
class, because log entries don't contain the prevEndRow information in
the metadata tables
* Deprecate LogEntry methods used only for upgrading the root table's
WAL entries from previous versions (Upgrader9to10)
> Simplify and clean up LogEntry

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/test/java/org/apache/accumulo/core/conf/SiteConfigurationTest.java
Even though our configurations are not case-sensitive, this
change makes the default values of our properties, and their
descriptions, use uppercase or lowercase based on the SI
prefixes for `PropertyType.BYTES` units for consistency.
> Use SI prefix cases in properties

- test/src/main/java/org/apache/accumulo/test/IteratorEnvIT.java
- test/src/main/java/org/apache/accumulo/test/RecoveryCompactionsAreFlushesIT.java
- test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java
- test/src/main/java/org/apache/accumulo/test/UserCompactionStrategyIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
- test/src/main/java/org/apache/accumulo/test/functional/MasterMetricsIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SummaryIT.java
* Prevent several ITs that have compaction behavior from running in
standalone mode by overriding the canRunTest method.  These tests
currently don't work well in standalone mode and will fail.
* Remove standalone specific code in functional.CompactionIT
> Make ITs with compactions run in MINI only. Fixes #1713

- assemble/bin/tool.sh
ZooKeeper changed directory structure between versions 3.4 and 3.5. This update corrects tool.sh script to set the correct ZooKeeper command depending upon version used.
> Update tool.sh to set correct ZOOKEEPER_CMD.

- test/system/continuous/run-verify.sh
This PR resolves the issue reported in #1695. Noticed the ZK lib change has already been done via PR #1716.
> Update run-verify.sh to not fail when optional arguments passed are empty

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/problems.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/problems.ftl
This will fix the bug but we lose the ability to filter the details table.  I couldn't get the search box to look right with the two tables and don't think its intuitive to be used to filter anyway.  I think the making the table links filter the details table can be a follow on task.  This PR just makes the links go to the table page.
> Convert Monitor table problems to datatables. Fixes #1719

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
* Make the instance.security properties boolean instead of a classname
* This will remove security interfaces from the properties without
losing the functionality provided.
* The instance.security.authenticator, instance.security.authorizor
and instance.security.permissionHandler properties used interfaces that
contain internal types and were not friendly for public use.
> Mark security properities experimental

- assemble/build.sh
- pom.xml
Improving generated output:
* show link to staging repo website
* show full commits
* show reminders of which buttons to click on the staging site
* show reminder to replace `$origin` with actual remote name
* place `-s` in `git tag` command with the other options
* update draft release notes link to point to staged site
Optimizing performance:
* create the `-next` branch and switch to it in one command
* skip tests during release prep because the release can (and should) be
tested outside of the actual release candidate creation process and
this speeds things up significantly
* change release prep goal to only do `package`, because it's not
necessary to run `verify` during `release:prepare`; all the QA checks
done at `verify` can be done before/after release candidate staging
Being more …
> Update release candidate script

- server/base/src/main/java/org/apache/accumulo/server/AbstractServer.java
ServerContext creates a ServerInfo which initializes the hdfs connection
and among others a LeaseRenewer is started with the current
UserGroupInformation. To make sure the correct UserGroupInformation is
used I moved the serverLogin call before ServerContext creation.
> Initilaize hdfs connection with correct ugi

- assemble/bin/tool.sh
- test/system/continuous/run-verify.sh
Modify the regex in tool.sh to successfully determine zookeeper version. Previous commit needed to be slightly modified to work correctly. Replacing ^3[.][01234].*$ with .*-3[.][01234].*$
> Update regex expression in tool.sh

- assemble/bin/build_native_library.sh
Fixes https://github.com/apache/accumulo/issues/1731
> Fix build_native_library.sh so that it runs on alpine-based (e.g. Alpine)-based distros

- server/manager/src/main/java/org/apache/accumulo/master/tableOps/create/CreateTable.java
Uses the same cleanup logic that is used if the operation is successful. Closes #1739
> Close #1739. Cleanup Splits file if CreateTable FaTE operation fails.

- .github/workflows/maven.yaml
- minicluster/pom.xml
- pom.xml
- test/src/test/scripts/run-test.sh
* Create new configuration properties in the build configuration for
surefire.forkCount and failsafe.forkCount to enable configuring them
independently of one another
* Create a profile to set both surefire.forkCount and failsafe.forkCount
together, if desired
* Remove forkCount settings from the build workflow, instead selecting
sane defaults that are equivalent
* Force minicluter to use one surefire fork only (along with start
module) to avoid potential conflicts
> Configure surefire/failsafe forkCount separately

- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
* Since Java 5 the java debugger uses "-agentlib" for JDWP
https://docs.oracle.com/javase/7/docs/technotes/guides/jpda/conninv.html
> Update jvm option for JDWP in Mini

- server/base/src/main/java/org/apache/accumulo/server/master/state/TabletLocationState.java
- server/base/src/test/java/org/apache/accumulo/server/master/state/TabletLocationStateTest.java
- server/manager/src/main/java/org/apache/accumulo/master/Master.java
- server/manager/src/main/java/org/apache/accumulo/master/TabletGroupWatcher.java
* Create TabletLists to hold the many different data structures being
tracked in the run method of TabletGroupWatcher
* Create methods for some of the logic in the switch case
* Pass TabletLists to the flush method and break flush into methods
* Rename TabletLocationState.getServer() to getLocation() as location is
a more meaningful name instead of server
> Refactor TabletGroupWatcher

- core/src/main/java/org/apache/accumulo/fate/zookeeper/ZooReader.java
- core/src/main/java/org/apache/accumulo/fate/zookeeper/ZooReaderWriter.java
- core/src/test/java/org/apache/accumulo/fate/zookeeper/ZooReaderWriterTest.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/RootTabletMutatorImpl.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
- server/base/src/main/java/org/apache/accumulo/server/security/delegation/ZooAuthenticationKeyDistributor.java
- server/base/src/main/java/org/apache/accumulo/server/tables/TableManager.java
- server/base/src/main/java/org/apache/accumulo/server/tablets/UniqueNameAllocator.java
- server/base/src/test/java/org/apache/accumulo/server/problems/ProblemReportTest.java
- server/base/src/test/java/org/apache/accumulo/server/security/delegation/ZooAuthenticationKeyDistributorTest.java
- server/manager/src/main/java/org/apache/accumulo/master/MasterClientServiceHandler.java
- server/manager/src/main/java/org/apache/accumulo/master/tableOps/Utils.java
- server/manager/src/main/java/org/apache/accumulo/master/tableOps/compact/CompactRange.java
- server/manager/src/main/java/org/apache/accumulo/master/tableOps/compact/cancel/CancelCompactions.java
- server/manager/src/main/java/org/apache/accumulo/master/tableOps/namespace/rename/RenameNamespace.java
- server/manager/src/main/java/org/apache/accumulo/master/tableOps/rename/RenameTable.java
- server/manager/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java
Separate out the two distinct use cases for calling
`ZooReaderWriter.mutate()` into two separate methods, with fewer
required parameters and more clear naming. This also allows for stricter
null checking in the parameters that are passed.
> Minor cleanup of ZooReaderWriter mutate

- core/src/main/java/org/apache/accumulo/core/iterators/IteratorEnvironment.java
- test/src/main/java/org/apache/accumulo/test/IteratorEnvIT.java
* This fixes #1766
* Return an actual implementation for
`IteratorEnvironment.getPluginEnv()`
* Clean up `IteratorEnvIT.testEnv()` method to:
* Verify implementation of `getPluginEnv()` (same object as
`getServiceEnv()`, but with the newer API that doesn't leak internal
types
* Remove duplicate check of the same table configuration via
`getServiceEnv()` and `getPluginEnv()`
* Remove duplicate (identical) check from the deprecated `getConfig()`
method to get the table's configuration as `AccumuloConfiguration`
* Ensure system configuration is covered in the test via
`getPluginEnv().getConfiguration()`
* Ensure getting the property by the full property name via `get()`
works as well as by the `getTableCustom()` convenience method
> Implement IteratorEnvironment.getPluginEnv()

- server/manager/src/main/java/org/apache/accumulo/master/tableOps/create/ChooseDir.java
- server/manager/src/main/java/org/apache/accumulo/master/tableOps/create/CreateTable.java
- server/manager/src/main/java/org/apache/accumulo/master/tableOps/create/FinishCreateTable.java
In response to [comment](https://github.com/apache/accumulo/pull/1746/files#r514604929) from @keith-turner. I added a try block around my previous change on #1746. With the unreserveNamespace call in the finally block.
> Wrap undo in try block

- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/ConcurrentKeyExtentCache.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/bulk/ConcurrentKeyExtentCacheTest.java
* Remove exceptions from BulkImport and ConcurrentKeyExtentCache
internal classes that were declared but never thrown
* Remove some unused code in findOverlappingTablets
* Shorten a few lines that use lambdas
> Minor cleanup in BulkImport

- shell/src/main/java/org/apache/accumulo/shell/commands/InsertCommand.java
- test/src/main/java/org/apache/accumulo/test/ShellIT.java
This change adds the <code>--tablename</code> option to the insert command when inside the shell or when using the accumulo command with <code>accumulo shell -e \<task\></code>. The option is not required, but if used it allows data to be inserted into a table in situations where the shell is not within a table context or when in a table context to insert data into another table.
Although I would not expect this option to be utilized very often, I found myself in need of it when working with the various accumulo examples in the accumulo-examples repo. I had many situations where I wished to insert some test data from a bash shell using the form:
<code>accumulo shell -u user -p pwd -e "insert r f q v"</code>
but this would fail due to there being no table name context for the insertion. …
> Add tablename option to shell insert command.

- core/src/test/java/org/apache/accumulo/core/data/NamespaceIdTest.java
- core/src/test/java/org/apache/accumulo/core/data/TableIdTest.java
TableId and NamespaceId have tests to ensure their caches work
correctly. Previously, the tests would only *attempt* to increase the
cache before checking that it decreased again. However, a garbage
collection could have reduced the size of the cache before we checked
its size. This change *guarantees* the cache will reach a specific size
before proceeding.
> Stabilize NamespaceIdTest and TableIdTest

- core/src/main/java/org/apache/accumulo/core/data/NamespaceId.java
- core/src/main/java/org/apache/accumulo/core/data/TableId.java
- core/src/test/java/org/apache/accumulo/core/data/NamespaceIdTest.java
- core/src/test/java/org/apache/accumulo/core/data/TableIdTest.java
* Add comments explaining the purpose of the Guava cache used in TableId
and NamespaceId
* Create utility method for counting the cache entries in the tests and
include a comment explaining why we need to count them the way we do
> Add comments for TableId/NamespaceId cache

- pom.xml
Update version of hadoop to 3.3.0 in order to remove warnings. With 3.3.0 version the "An illegal reflective access operaion has occurred" errors no longer appear as the issue has been corrected in that version of Hadoop (actually, corrected in 3.2.2 and above).
> Update hadoop version to 3.3.0 in pom.xml

- shell/src/main/java/org/apache/accumulo/shell/commands/DeleteCommand.java
- test/src/main/java/org/apache/accumulo/test/ShellIT.java
This ticket examined the table-related shell commands to verify they provide a means to indicate the table name. After examination all but the 'delete' command did so. The PR added the ability for the 'delete' command to specify a target table. With this update all 39 shell commands that can take a table name parameter. This closes #1776.
> Add table option to shell delete command.

- assemble/conf/accumulo-env.sh
- assemble/pom.xml
- assemble/src/main/assemblies/component.xml
- assemble/src/main/resources/NOTICE
- pom.xml
Include additional jars in the binary tarball assembly to redirect logs
sent to other logging frameworks to log4j by default:
* log4j-jcl to redirect commons-logging (commons-logging jar still
needed as a transitive dependency)
* log4j-jul to redirect java.util.logging
(From https://logging.apache.org/log4j/2.x/faq.html#which_jars)
Propagate an additional NOTICE from log4j-core's jar in our binary
tarball assembly.
Include rules to ban other transitive dependencies from the project that
are likely to cause conflicts with our logging at runtime, as a sanity
check for our build quality.
Bump log4j to latest version 2.14.0
> Redirect other log frameworks to log4j

- server/base/src/test/java/org/apache/accumulo/server/util/time/SimpleTimerTest.java
Did my best to resolve #1763. Replaced the assert statements with an if statement so that they could be repeated if they don't pass immediately. The test will repeat until passed or until the added timeout occurs. As suggested, I left the assert statement after the loop which verifies the thread pool size remains unchanged after the previous operations. Not sure if I should have kept the other asserts as well but I don't see the point if the same conditions were verified already. Please suggest any changes or improvements.
> Fixes #1763 - Flaky test: SimpleTimerTest

- test/src/main/java/org/apache/accumulo/test/functional/MetadataMaxFilesIT.java
remove stop / start of MAC because flushes are waiting for completion. Reduce number of tables created so test does not time out.
> fixes #1574: remove stop / start of MAC because flushes are waiting for completion. Reduce number of tables created so test does not time out.

- server/base/src/main/java/org/apache/accumulo/server/security/SecurityOperation.java
Reverse the order of permissions checks to check if the current user is
asking about themselves. This prevents an unnecessary audit log message
showing a denial when the user does not also have system privileges.
> Fix unneeded audit message about denial

- server/manager/src/main/java/org/apache/accumulo/master/MasterClientServiceHandler.java
Add and throw missing exceptions when permissions checks fail. This
prevents certain operations that the user does not have privileges to
perform from succeeding anyway.
> Throw exceptions when permissions checks fail

- server/master/src/main/java/org/apache/accumulo/master/MasterClientServiceHandler.java
- test/src/main/java/org/apache/accumulo/test/AuditMessageIT.java
Based on #1828 in main. This is to back to 1.10. Confirmed the bug did exist on that branch as well.
> Throw sercurity exceptions when permissions checks fail. Backport to 1.10

- core/src/main/java/org/apache/accumulo/core/Constants.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/dataImpl/KeyExtent.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/VisMetricsGatherer.java
- server/base/src/main/java/org/apache/accumulo/server/security/SystemCredentials.java
- server/base/src/main/java/org/apache/accumulo/server/security/handler/ZKSecurityTool.java
- server/base/src/test/java/org/apache/accumulo/server/security/SystemCredentialsTest.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tservers/TabletServerResource.java
- shell/src/main/java/org/apache/accumulo/shell/commands/GetSplitsCommand.java
This PR contains two small commits:
---
Consolidate tablet obscuring code
This fixes #1805
Move implementation of tablet obscuring code into KeyExtent and remove
duplicate implementations.
Also fixup trivial constant in VisMetricsGatherer, so it is private and
fix typo in ZKSecurityTool to clarify that the salt length is 8 bytes by
default, not the hash length
---
Update SystemCredentials to use crypt(3) format
This fixes #1810
This updates the SystemToken generation to use SHA-512 while hashing the
system's `instance.*` configuration properties (including
`instance.secret`) by using commons-codec's crypt(3) implementation.
It also adds more javadocs and makes the code a bit more readable, while
removing a hard-coded global constant and an unneeded new instance
property introduced in …
> Remove centralized crypto constants

- core/src/main/java/org/apache/accumulo/core/util/HostAndPort.java
- shell/src/main/java/org/apache/accumulo/shell/commands/ActiveCompactionHelper.java
Fixing issue #1760. Adding more helpful error messages for the listcompactions command when a tserver address is passed.
> Fixes #1760 - `listcompactions` command error is not helpful

- core/src/main/java/org/apache/accumulo/core/conf/ClientConfigGenerate.java
- core/src/main/java/org/apache/accumulo/core/conf/ConfigurationDocGen.java
- pom.xml
- server/tserver/src/main/java/org/apache/accumulo/tserver/NativeMap.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerMetricsUtil.java
- test/src/main/java/org/apache/accumulo/test/WaitForBalanceIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BalanceInPresenceOfOfflineTableIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BatchScanSplitIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BinaryStressIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ChaoticBalancerIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SimpleBalancerFairnessIT.java
* Update to exec-maven-plugin 3.0.0
* Make main classes public
* Remove ERROR about native library loading when an optional setting is
not configured
* Remove ERROR from metrics that occurs before compaction manager is
initialized
* Scale back the resources required to run WaitForBalanceIT and
SimpleBalancerFairnessIT, to improve their stability
* Fix compaction threads dying in some tests because of mixconfigured
compaction checking delay time (must be greater than 1ms; some tests
were setting it to 0, which was a non-sensical setting)
> Stabilize some build elements

- test/src/main/java/org/apache/accumulo/test/AuditMessageIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ManagerApiIT.java
- test/src/main/java/org/apache/accumulo/test/functional/PermissionsIT.java
In relation to #1830, I only added an audit check for flushing a table at the moment but I am working on adding additional ones for set/remove system property and any other that is requested.
> Add additional permission checks in AuditMessageIT

- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloConfigImpl.java
- pom.xml
- test/src/main/java/org/apache/accumulo/harness/AccumuloClusterHarness.java
- test/src/main/java/org/apache/accumulo/harness/MiniClusterHarness.java
- test/src/main/java/org/apache/accumulo/harness/SharedMiniClusterBase.java
- test/src/main/java/org/apache/accumulo/test/TotalQueuedIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkNewIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkOldIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CreateInitialSplitsIT.java
- test/src/main/java/org/apache/accumulo/test/functional/TabletIT.java
* Increase the default memory for mini-based ITs (from 128MB to 256MB)
The justification for this is that using the G1GC in newer JVMs seems
to use a little bit more base memory than the old CMS, which was
removed. Some of our tests seem to push the memory limits a bit.
Increasing the default memory for mini processes in our ITs makes many
ITs a bit more reliable, and less prone to OutOfMemoryErrors killing
background threads (which I've noticed a lot more during development
since running my development environment with newer versions (11+) of
Java).
* Use more meaningful directory name for SharedMiniClusterBase ITs to
make it easier to debug specific failed tests.
* Remove a bunch of unused overloaded static create methods from
MiniClusterHarness and remove constants kerberos constants …
> Improve some IT framework and build-related code

- server/master/src/main/java/org/apache/accumulo/master/replication/FinishedWorkUpdater.java
- server/master/src/main/java/org/apache/accumulo/master/replication/RemoveCompleteReplicationRecords.java
- server/master/src/main/java/org/apache/accumulo/master/replication/ReplicationDriver.java
- server/master/src/main/java/org/apache/accumulo/master/replication/WorkDriver.java
- server/master/src/main/java/org/apache/accumulo/master/replication/WorkMaker.java
* Reduce logging level to trace of retries when replication is offline
* User can easily see if repl table is online through monitor, no need
to keep spamming logs when it is offline
> Reduce log level of replication offline retries

- test/src/main/java/org/apache/accumulo/test/functional/ConcurrentDeleteTableIT.java
Added a timeout to both of the tests in this IT because they were observed taking far too long to complete as detailed in #1841. When I run these tests they both take about 40 seconds so I added a 3 minute timeout which should be plenty of time if they are running correctly. Not too sure why these tests took so long to complete, but these timeouts should ensure they are not running incorrectly for a long period of time.
> Fixes #1841 - Broken or Flaky test: ConcurrentDeleteTableIT takes 30 minutes to run

- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadata.java
- shell/src/main/java/org/apache/accumulo/shell/Shell.java
- shell/src/main/java/org/apache/accumulo/shell/commands/ListTabletsCommand.java
- shell/src/test/java/org/apache/accumulo/shell/commands/ListTabletsCommandTest.java
- test/src/main/java/org/apache/accumulo/test/functional/TabletMetadataIT.java
* New command for debugging tablets called listtablets
* Added getLiveTServers() to TabletMetadata for generating a list of
tservers that currently have a lock in ZK, similar to master.
* The list of live tservers is passed to TabletMetadata in order to get
the current state of a tablet
* Command will print one line for every tablet in a table
* Created TabletMetadataIT for testing getLiveTServers()
Co-authored-by: EdColeman <dev1@etcoleman.com>
> Create listtablets shell command. Closes #1317

- core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftTransportPool.java
- test/src/main/resources/log4j2-test.properties
* Avoid closing already closed transports
* For TIOStreamTransport, which does not implement a reasonable isOpen()
method, suppress its log messages during integration testing, so logs
don't contain spammy errors about closed network connections that are
expected during testing
> Make ThriftTransportPool logs a little less spammy

- server/tracer/src/main/java/org/apache/accumulo/tracer/ZooTraceClient.java
I kept seeing this NPE every time I started the shell in a test cluster:
```
2021-01-06 07:35:30,584 [tracer.AsyncSpanReceiver] WARN : Exception sending spans to destination
java.lang.NullPointerException
at org.apache.accumulo.tracer.ZooTraceClient.sendSpans(ZooTraceClient.java:146)
at org.apache.accumulo.tracer.AsyncSpanReceiver$1.run(AsyncSpanReceiver.java:116)
at java.util.TimerThread.mainLoop(Timer.java:555)
at java.util.TimerThread.run(Timer.java:505)
```
It looks like ZooTraceClient varibles are not yet fully initialized when the timer created in AsyncSpanReceiver constructor calls sendSpans and hosts.isEmpty() throws an NPE. It's caught in the timer and the object is fully initialized by the next run so it causes no problems. This is just a small change to prevent the unnecessary …
> sendSpans NPE fix

- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
Ran into a case on a large cluster where the scan rate was so high that the graph flatlined at Java's max integer value.
> Use long instead of int for monitor scan rate (#1858)

- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/LogSorter.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/logger/LogReader.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/replication/AccumuloReplicaSystem.java
Fix an error message that the stream is closed after a successful
recovery in LogSorter.java. This occurred because a try-with-resources
block automatically closed the file input stream, and then it was
attempted to be closed again in the finally block in the
LogSorter.LogProcessor.sort() method. This resulted in an error message
always being shown in the finally block, even if the try-with-resources
block successfully finished without error and closed the input stream
already. This change removes the use of try-with-resources, and relies
on the finally block to close the resources once.
Related changes include:
* Remove unnecessary wrapping class to carry the original input stream
alongside the decrypting wrapper input stream, since the original
input stream is already available to all …
> Remove error message on recovery success

- server/tserver/src/main/java/org/apache/accumulo/tserver/log/LogSorter.java
* Check for finished file in LogSorter before performing sort
* LogSorter was always removing the destination sort directory even if
it had previously been successfully sorted, creating lots of duplicate
and unnecessary work during recovery
I discovered this issue while looking into #1844
> Add check for finished to LogSorter

- fate/src/main/java/org/apache/accumulo/fate/util/LoggingRunnable.java
There is a robust fix in #1818 that is probably too much to backport to 1.10. This fix simply re-throws the original exception (unless there is an exception when logging and that is more serious (i.e., it's an Error and the original Throwable was not an Error)).
> Re-throw exception from LoggingRunnable (re #1808)

- pom.xml
* Include missing hadoop-mapreduce module's classes to the generated
javadocs when building the aggregate javadocs for the public API to
publish on the website
* Sort list of javadoc classes
* Add comment in the profile explaining how to run
> Add missing hadoop-mapreduce module API javadocs

- shell/src/main/java/org/apache/accumulo/shell/Shell.java
There are a few possible options on where we could authenticate so if anyone has feedback on a better way, let me know. 
Results after the change: 
The user stays as root since the wrong credentials were entered for the user 'jeff'. 
Closes #1867
> Fixes #1867. Move authentication before attempting to create new Client object

- assemble/bin/accumulo-cluster
- assemble/bin/accumulo-service
- assemble/conf/accumulo-env.sh
- server/manager/src/main/java/org/apache/accumulo/master/ManagerExecutable.java
- test/src/main/java/org/apache/accumulo/test/start/KeywordStartIT.java
While running test against 2.1.0-SNAP I noticed a master.log file was being created. I tried to fix that and ended up with this PR which modifies the scripts to support manager and also fixes the log file name.
> Updates shell scripts and logs to use manager

- pom.xml
This change bumps the zookeeper version to the latest 3.5.x release. With 2.1 we are changing the zookeeper version to 3.5.x, this would keep the 2.1 release consistent with the current zookeeper release.
> Update zookeeper 3.5.x version to 3.5.9

- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
Ensure the DfsLogger.fail() method includes the stack trace for the
exception that occurred, in case something happens and it doesn't get
wrapped and rethrown later. Also, use slf4j substitution syntax.
> Include stack trace in log for DfsLogger.fail()

- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
This PR address 'accumulo init' command being hanging when TLS enabled on Zookeeper. The related PR (https://github.com/apache/accumulo/pull/1586) addressed the 'accumulo master' being hanging with TLS-enabled zookeeper.
> Fix Accumulo-init hanging when TLS enabled on Zookeeper

- server/manager/src/main/java/org/apache/accumulo/master/Master.java
* When the Master killed a tserver due to holdTime, it would just
disappear on the Monitor because it was being dropped from the active
tserver list. Instead of dropping it, this will add it to the list of
badservers, giving the Monitor a chance to see it dead.
> Add tserver to badservers instead of dropping. Fixes #1775

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
* If a tablet is in the process of being opened, the UnloadTabletHandler
will wait for a tablet to be removed from the list before proceeding
with the unload.  This could take a long time so log info before waiting.
> Make UnloadTabletHandler log before waiting

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
* The CleanUp step of deletes will wait until all tablets of a tablet
are unassigned. This will stop the memory mgr from flushing if the table
is being deleted, allowing it to be unassigned faster.
> Add check to not flush when table is being deleted.

- server/base/src/main/java/org/apache/accumulo/server/zookeeper/TransactionWatcher.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/BulkImportCacheCleaner.java
* Check if the parent node exists before performing a sync and getting
the children in TransactionWatcher, preventing NoNodeExceptions.
Here is the exception that I have seen:
<pre>
2021-01-29T10:02:32,310 [tablet.BulkImportCacheCleaner] DEBUG: Error reading bulk import live transactions {}
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /accumulo/cc552965-f3c2-48b6-b200-9d1f2a7c48c5/bulkTx
at org.apache.zookeeper.KeeperException.create(KeeperException.java:118) ~[zookeeper-3.6.2.jar:3.6.2]
at org.apache.zookeeper.KeeperException.create(KeeperException.java:54) ~[zookeeper-3.6.2.jar:3.6.2]
at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:2746) ~[zookeeper-3.6.2.jar:3.6.2]
at org.apache.accumulo.fate.zookeeper.ZooReader.lambda$getChildren$5(Zoo …
> Improvements to BulkImportCacheCleaner

- test/src/main/java/org/apache/accumulo/test/ShellIT.java
This fixes [ACCUMULO-1119](https://issues.apache.org/jira/browse/ACCUMULO-1119?orderby=cf[12310200]+ASC%2C+priority+DESC%2C+updated+DESC). Since `ShellTest` became `ShellIT` (in 2.0), this test can be uncommented, assuming this is still something worthwhile to test. I confirmed it passes now, even without having to properly enter any passwords. 
`ShellServerIT` also has a user test but doesn't directly test for the "User Exists" exception. This could be added to that if it fits better or it can stay here.
> Add user test to ShellIT

- server/tserver/src/main/java/org/apache/accumulo/tserver/InMemoryMap.java
In my investigation of [ACCUMULO-2407](https://issues.apache.org/jira/browse/ACCUMULO-2407), I found that the task has been completed already for both 2.0 and 1.10. Therefore, this TODO is no longer needed.
> Remove TODO comments in InMemoryMap

- shell/src/main/java/org/apache/accumulo/shell/commands/GrantCommand.java
- shell/src/main/java/org/apache/accumulo/shell/commands/RevokeCommand.java
In conjunction with the conversation from #1903, I added a more explicit error message or granting and revoking System permissions in case the user forgets to add the '-s' option. Before, It would throw an error with "Unrecognized permission" and not really tell you why it was unrecognized.  
This is how it looked before: 
<pre>
org.apache.accumulo.core.util.BadArgumentException: Unrecognized permission near index 7
revoke System.ALTER_USER -u jeff
</pre>
This is how it looks now: 
<pre>
org.apache.accumulo.core.util.BadArgumentException: Missing required option for granting System Permission: s  near index 7
revoke System.ALTER_USER -u jeff
^
</pre>
This is similar formatting to the error message if the user forgets to add  `-u <user>` to a command. I can alter it if there is a preferred …
> Explicit error message for grant/revoke System perm Closes:  #1903

- test/src/main/java/org/apache/accumulo/test/BulkImportMonitoringIT.java
- test/src/main/java/org/apache/accumulo/test/CompactionExecutorIT.java
- test/src/main/java/org/apache/accumulo/test/ConditionalWriterIT.java
- test/src/main/java/org/apache/accumulo/test/CountNameNodeOpsBulkIT.java
- test/src/main/java/org/apache/accumulo/test/MasterRepairsDualAssignmentIT.java
- test/src/main/java/org/apache/accumulo/test/TestBinaryRows.java
- test/src/main/java/org/apache/accumulo/test/TestIngest.java
- test/src/main/java/org/apache/accumulo/test/UserCompactionStrategyIT.java
- test/src/main/java/org/apache/accumulo/test/VerifySerialRecoveryIT.java
- test/src/main/java/org/apache/accumulo/test/VolumeIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BinaryIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkOldIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CloneTestIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ConcurrentDeleteTableIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CreateAndUseIT.java
- test/src/main/java/org/apache/accumulo/test/functional/FateStarvationIT.java
- test/src/main/java/org/apache/accumulo/test/functional/LogicalTimeIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ManyWriteAheadLogsIT.java
- test/src/main/java/org/apache/accumulo/test/functional/MaxOpenIT.java
- test/src/main/java/org/apache/accumulo/test/functional/MergeIT.java
- test/src/main/java/org/apache/accumulo/test/functional/MetadataMaxFilesIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ScanRangeIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SummaryIT.java
In many cases, tables are created and then splits are added. This is not as efficient as creating the tables with the splits.  Significant decreases in time taken in tests with pre-split tables is observed, especially in cases with many splits. This PR aims to convert to pre-split tables in cases where improvement is obvious, and discuss to what extent and in what scenarios this conversion should take place.
> Converting table creation to pre-split

- test/src/main/java/org/apache/accumulo/test/TestIngest.java
On my last PR, #1892, which converted to pre-split tables, it was pointed out [in a comment](https://github.com/apache/accumulo/pull/1892#issuecomment-774045325) that the changes broke some ITs. This change fixes those broken ITs.
> Fix broken ITs caused by #1892

- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterControl.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/ManagerExecutable.java
- server/manager/src/main/java/org/apache/accumulo/manager/MasterExecutable.java
Commit e6164901a3acdd464a7a9beff0126097b53fc06f removed the main method
from Manager. In order to work around this, minicluster was modified to
use KeywordExecutable classes to launch. However, this caused all
minicluster log files to be named "Main" since the main class is always
org.apache.accumulo.start.Main. This could be worked around with a
log4j2 properties file and variable name to cause the file logger to use
the right class name, but then that would require all minicluster users
to use the supplied logger configuration, or replicate the same
configuration. Instead, the main method was added back to Manager so
that minicluster logging will work as expected. This also fixes the
broken ITs BackupManagerIT and ThriftServerBindsBeforeZooKeeperLockIT
which were both broken since they …
> Fix log names in minicluster, some broken ITs.

- test/src/main/java/org/apache/accumulo/test/randomwalk/multitable/BulkImport.java
- test/src/main/java/org/apache/accumulo/test/randomwalk/multitable/MultiTableFixture.java
- test/src/main/java/org/apache/accumulo/test/randomwalk/multitable/OfflineTable.java
- test/system/randomwalk/conf/modules/MultiTable.xml
- test/system/randomwalk/conf/randomwalk.conf.example
* Create new BulkImport test in MultiTable for more realistic case
* Other improvements to Randomwalk MultiTable
* Modify randomwalk.conf.example to work with Uno by default
> Add Bulk import to randomwalk MultiTable

- core/src/main/java/org/apache/accumulo/fate/zookeeper/ZooLock.java
* Seeing ~300 logs per second per tserver with just these few debug statements
> Drop debug logs to trace in ZooLock

- core/src/main/java/org/apache/accumulo/core/volume/VolumeImpl.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeManager.java
Closes https://issues.apache.org/jira/browse/ACCUMULO-2809 
This no longer throws an NPE  but instead throws :
<details>
<pre>
java.lang.IllegalArgumentException: Can not create a Path from an empty string
at org.apache.hadoop.fs.Path.checkPathArg(Path.java:172) ~[hadoop-client-api-3.3.0.jar:?]
at org.apache.hadoop.fs.Path.<init>(Path.java:184) ~[hadoop-client-api-3.3.0.jar:?]
at org.apache.hadoop.fs.Path.<init>(Path.java:119) ~[hadoop-client-api-3.3.0.jar:?]
at org.apache.accumulo.core.volume.VolumeImpl.prefixChild(VolumeImpl.java:137) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
at org.apache.accumulo.server.ServerConstants.getInstanceIdLocation(ServerConstants.java:175) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
at …
> Better error message when instance.volumes does not specify the accumulo directory

- core/src/main/java/org/apache/accumulo/core/client/rfile/RFile.java
- core/src/main/java/org/apache/accumulo/core/client/rfile/RFileWriter.java
- core/src/main/java/org/apache/accumulo/core/client/rfile/RFileWriterBuilder.java
This was unclear to me and I had to look at the code to figure it out. The API will throw an error without the proper extension. I think we can improve it in 2.1 but for 1.10, we can improve the javadoc.
> Improve filename extension usage in RFile API

- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletLocator.java
- core/src/main/java/org/apache/accumulo/core/util/Interner.java
- core/src/test/java/org/apache/accumulo/core/util/InternerTest.java
Create an Interner class that implements a deduplicating intern
function for any object type. Add corresponding unit test, and
convert TabletLocator's custom WeakHashMap over to use this
instead.
> Move String intern code and make it generic

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/memory/LargestFirstMemoryManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/memory/LargestFirstMemoryManagerTest.java
* The CleanUp step of deletes will wait until all tablets of a tablet
are unassigned. This will stop the memory mgr from flushing if the table
is being deleted, allowing it to be unassigned faster.
* Remove deleted tablet from memory reports in TabletServerResourceManager
so it won't keep trying to flush delete tablets when they are large
* Add TableState param to Tablet.initiateMinorCompaction() so calling code
in TabletServerResourceManager only has to get the state once
* Add debug to Tablet.completeClose() for better insight when waiting
> Prevent deleted tablets from being flushed

- test/src/main/java/org/apache/accumulo/test/functional/TabletStateChangeIteratorIT.java
* Modified copyTable method to gather info about the metadata first
before creating the copy, preventing information about the copy itself
from being seen.
* Added debugging information
> Improvements to TabletStateChangeIteratorIT

- core/src/main/java/org/apache/accumulo/core/clientImpl/OfflineIterator.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/ConcurrentKeyExtentCache.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/AmpleImpl.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java
- core/src/main/java/org/apache/accumulo/core/summary/Gatherer.java
- core/src/main/java/org/apache/accumulo/core/util/Merge.java
- server/base/src/main/java/org/apache/accumulo/server/manager/balancer/BalancerEnvironmentImpl.java
- server/base/src/main/java/org/apache/accumulo/server/master/balancer/GroupBalancer.java
- server/base/src/main/java/org/apache/accumulo/server/util/ListVolumesUsed.java
- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
- server/base/src/test/java/org/apache/accumulo/server/manager/state/RootTabletStateStoreTest.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/LoadFiles.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/PrepBulkImport.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/CompactionDriver.java
- shell/src/main/java/org/apache/accumulo/shell/commands/ListTabletsCommand.java
- test/src/main/java/org/apache/accumulo/test/CompactionExecutorIT.java
- test/src/main/java/org/apache/accumulo/test/functional/AccumuloClientIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkNewIT.java
- test/src/main/java/org/apache/accumulo/test/functional/MetadataIT.java
* Modify TabletsMetadata to impl readTablets in Ample
* Modify classes calling TabletsMetadata to pass the client object as
part of the builder init, instead of the final build method
* Add testAmpleReadTablets to MetadataIT
Co-authored-by: cradal <20303105+cradal@users.noreply.github.com>
Updated version of #1651
> Create readTablets method in Ample. Closes #1473

- server/tserver/src/main/java/org/apache/accumulo/tserver/memory/LargestFirstMemoryManager.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/memory/LargestFirstMemoryManagerTest.java
* Increases the difference between the large memory values used in the
test so the likelihood of tablets getting keyed at the same
timeMemoryLoad is much less
* Also set the ZERO_TIME of LargestFirstMemoryManagerTest equal to
LargestFirstMemoryManager to prevent different times between classes
loading
> Increase difference between test values. Fixes #1789

- test/src/main/java/org/apache/accumulo/harness/MiniClusterHarness.java
- test/src/main/java/org/apache/accumulo/test/functional/ConfigurableMacBase.java
- test/src/main/java/org/apache/accumulo/test/util/CertUtils.java
- test/src/test/java/org/apache/accumulo/test/util/CertUtilsTest.java
* Use 4096 bit RSA keys and SHA512withRSA instead of SHA1withRSA for the
certificate signing algorithm for certificates generated for testing
Accumulo's TLS support
* This avoids problems with test breakages in environments, such as
Fedora 33, with strong default crypto policies for Java that restrict
weak crypto, or if the user has restricted their Java security
policies themselves
> Use stronger crypto settings for test certificates

- core/src/main/java/org/apache/accumulo/core/file/blockfile/impl/ScanCacheProvider.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/CompactionDispatch.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/CompactionDispatchBuilder.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/CompactionDispatchImpl.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/CompactionDispatcher.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/SimpleCompactionDispatcher.java
- core/src/main/java/org/apache/accumulo/core/spi/scan/DefaultScanDispatch.java
- core/src/main/java/org/apache/accumulo/core/spi/scan/ScanDispatch.java
- core/src/main/java/org/apache/accumulo/core/spi/scan/ScanDispatchImpl.java
- core/src/main/java/org/apache/accumulo/core/spi/scan/ScanDispatcher.java
- core/src/main/java/org/apache/accumulo/core/spi/scan/SimpleScanDispatcher.java
- core/src/test/java/org/apache/accumulo/core/spi/scan/SimpleScanDispatcherTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/scan/ScanParameters.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Make Scan/Compaction Dispatchers return a Dispatch object when they
dispatch() by renaming Directives objects to use Dispatch in the name
instead.
> Return a Dispatch object from Dispatchers

- shell/src/main/java/org/apache/accumulo/shell/Shell.java
- shell/src/main/java/org/apache/accumulo/shell/commands/ScriptCommand.java
Mark the shell's ScriptCommand as deprecated and log a warning when used.
This fixes #1949
> Deprecate the shell script command

- core/src/main/java/org/apache/accumulo/core/logging/FateLogger.java
- core/src/main/java/org/apache/accumulo/fate/AdminUtil.java
- core/src/main/java/org/apache/accumulo/fate/AgeOffStore.java
- core/src/main/java/org/apache/accumulo/fate/ReadOnlyStore.java
- core/src/main/java/org/apache/accumulo/fate/ReadOnlyTStore.java
- core/src/main/java/org/apache/accumulo/fate/ZooStore.java
- core/src/test/java/org/apache/accumulo/fate/SimpleStore.java
From https://issues.apache.org/jira/browse/ACCUMULO-4161. An age/created column was added to the `fate print ` command in the shell. 
Image below is what the timestamp looks like in its current state.
> Add created column to Fate Print command

- pom.xml
Fixes #2004. 
This sets the reuseForks flag in maven to 'true' for unit tests while keeping it 'false' for ITs. There are some unit tests that fail with this change so they have been excluded directly in the pom file. 
Though unit tests pass consistently now, there may be others that are affected by this change and may need to be investigated further.
> Set reuseForks to true for unit tests, false for ITs

- core/src/main/java/org/apache/accumulo/fate/zookeeper/ServiceLock.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/ServiceLockIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitRecoveryIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ZombieTServer.java
* Remove constructor in ServiceLock and make all services use the
constructor that takes a ZooKeeper object
* Get the authenticatedSession ZK from ServerContext instead of passing
in conf and parsing properties everytime.
* Simplify method in ServiceLockIT
> Drop duplicate constructor in ServiceLock

- server/manager/src/main/java/org/apache/accumulo/manager/state/SetGoalState.java
This is the same problem fixed for managers and tservers to use the keytab file for kerberos authentication previously (https://github.com/apache/accumulo/pull/1727/commits/b6a9ad000d261f201b6322031d34c60fcbbb9d5a).   **serverLogin** should be called before **ServerContext** is created in order to initialize hdfs connection with correct ugi for **SetGoalState**
> Initialize hdfs connection with correct ugi for SetGoalState

- core/src/main/java/org/apache/accumulo/core/client/sample/RowColumnSampler.java
- core/src/main/java/org/apache/accumulo/core/client/sample/RowSampler.java
- core/src/main/java/org/apache/accumulo/core/client/summary/SummarizerConfiguration.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TableMap.java
- core/src/main/java/org/apache/accumulo/core/conf/AccumuloConfiguration.java
- core/src/main/java/org/apache/accumulo/core/data/LoadPlan.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadata.java
- core/src/main/java/org/apache/accumulo/core/spi/scan/HintScanPrioritizer.java
- core/src/main/java/org/apache/accumulo/core/spi/scan/SimpleScanDispatcher.java
- core/src/main/java/org/apache/accumulo/core/summary/SummarySerializer.java
- core/src/main/java/org/apache/accumulo/core/util/ConfigurationImpl.java
- core/src/main/java/org/apache/accumulo/core/util/LocalityGroupUtil.java
- core/src/test/java/org/apache/accumulo/core/iterators/FirstEntryInRowIteratorTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/system/MultiIteratorTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/LargeRowFilterTest.java
- server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java
- server/base/src/main/java/org/apache/accumulo/server/util/FileUtil.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
- server/manager/src/test/java/org/apache/accumulo/manager/tableOps/bulkVer2/PrepBulkImportTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/OnlineTablets.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/InMemoryMapTest.java
- shell/src/main/java/org/apache/accumulo/shell/ShellUtil.java
- test/src/main/java/org/apache/accumulo/test/functional/SummaryIT.java
Utilize some Java 11 features for immutable maps, sets, and lists, to
minimize our dependence on equivalent Guava features. Some use of Guava
builders for these are still used, since Java 11 doesn't have convenient
immutable collection builders, but they have been made final to ensure
we use them correctly and don't re-assign them once built.
> Use builtin immutable maps/sets/lists when available

- .github/workflows/maven-full-its.yaml
- .github/workflows/maven-on-demand.yaml
- .github/workflows/maven.yaml
Fix #2016 by adding an entry to /etc/hosts to fix incorrect DNS entries,
which return an IP for the current machine's hostname that does not
match any IP address in the machine. Adding an entry to /etc/hosts
to force the hostname to match on eth0's IP address.
> Fix IP address in GitHub Actions container

- server/base/src/main/java/org/apache/accumulo/server/master/balancer/HostRegexTableLoadBalancer.java
- server/base/src/test/java/org/apache/accumulo/server/master/balancer/HostRegexTableLoadBalancerReconfigurationTest.java
Ensure that the HostRegexTableLoadBalancer property changes are picked up.
When properties are set at the system level for the HostRegexTableLoadBalancer, the changes are not picked up and require the master to be restarted.  This change ensures that the property changes are always picked up whenever balance or getAssignments is called.
> Ensure that the HostRegexTableLoadBalancer property changes are picked up

- core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java
- shell/src/main/java/org/apache/accumulo/shell/commands/ImportDirectoryCommand.java
- shell/src/main/java/org/apache/accumulo/shell/commands/OptUtil.java
- shell/src/test/java/org/apache/accumulo/shell/commands/ImportDirectoryCommandTest.java
- test/src/main/java/org/apache/accumulo/test/ShellServerIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkNewIT.java
Update the new bulk import operations to allow empty source directories to be ignored rather than throwing an exception. There is now a '-i' option that will log an info message indicating that the source directory was empty and no files were imported rather than throwing an IllegalArgumentException.
This will support the use case of users who want to write idempotent bulk import code.
> Add bulk import option to ignore empty dirs

- core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java
- shell/src/main/java/org/apache/accumulo/shell/commands/ImportDirectoryCommand.java
- shell/src/test/java/org/apache/accumulo/shell/commands/ImportDirectoryCommandTest.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkNewIT.java
Update the importdirectory ignoreEmptyDir option to use the bulk import fluent API. The ignoreEmptyDir option is moved into the ImportOptions interface and can be set during the call to the load method.
> Move ignoreEmptyDir opt to ImportOptions interface

- core/src/main/java/org/apache/accumulo/core/metadata/CompactableFileImpl.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
Name 'getStortedTabletFile' has been refactored by 'getStoredTabletFile' in method 'getStoredTabletFile()' of Class 'CompactableFileImpl'
> Fixed issue #2048 wrong name in CompactableFileImpl method

- core/src/test/java/org/apache/accumulo/core/util/NumUtilTest.java
- Identified in PR#2040 by hguercan, the test can fail for systems that
have a Locale different that US set.
> Fix NumUtilTests to set Locale to US

- server/base/pom.xml
`AuthenticationTokenSecretManagerTest` failed on slim occasion. To be safe, I have excluded it from using reuseForks=true. 
As also seen here: https://github.com/apache/accumulo/pull/2015#issuecomment-828379142
> Addition unit test to exclude from using reuseForks

- core/src/test/java/org/apache/accumulo/core/data/KeyTest.java
Fixes #2042  This succeeds https://github.com/apache/accumulo/pull/2043 - contains auto-format correction.
> Fix #2042 - Replace assertTrue with assertArrayEquals in KeyTest

- TESTING.md
Remove an unneeded instance of the word 'to'. It had inadvertently been typed two times in a row within a sentence.
> Remove duplicated word in TESTING.md

- core/src/main/java/org/apache/accumulo/core/data/Mutation.java
- core/src/test/java/org/apache/accumulo/core/data/MutationTest.java
- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
- test/src/main/java/org/apache/accumulo/test/MetaConstraintRetryIT.java
This week we saw many "Failed to do close consistency check" errors. The log showed that the accumulo.metadata table had additional RFiles that were not present in the tserver's DatafileManager.datafileSizes map. We believe that this may have been due to a temporary network drop where a bulk importing tserver sent accumulo.metadata updates - the metadata updates were persisted but the bulk importing tserver's writer client did not receive a successful response. 
We'd like to add some additional logging to MetadataTableUtil so that we can tie the failures back to particular tablets to see if these correlate.
> Add optional extent to metadata update failure logs

- core/src/main/java/org/apache/accumulo/core/spi/crypto/AESCryptoService.java
- core/src/test/java/org/apache/accumulo/core/crypto/CryptoTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/RFileTest.java
* Also add tests to CryptoTest
* Closes #2000
> Add option to disable encryption to AESCryptoService

- pom.xml
* Bump jackson and use jackson-bom for everything
(some deps previously were not listed in the bom, but now they are)
* Bump other dependencies
* Review license/notice files (no changes)
> Bump dependencies for 2.1

- test/src/main/java/org/apache/accumulo/test/ShellServerIT.java
Fixes #2091.
The history command was failing due to the executed commands not being written to the history file. This change will write the expected commands to the history file but solely for the history test at this moment since some tests broke with the change.
> Fix history test inside ShellServerIT

- core/pom.xml
- core/src/test/java/org/apache/accumulo/core/util/InternerTest.java
Move InternerTest and NamespaceIdTest to the second execution of
maven-surefire-plugin, that does not reuse forks for running tests; this
ensures all tests that call System.gc are not affected by other tests
reusing the same JVM and affecting the garbage collector behavior,
because they will run in their own JVM
> Run tests that use System.gc in their own fork

- server/tserver/src/main/java/org/apache/accumulo/tserver/logger/LogReader.java
- test/src/main/java/org/apache/accumulo/test/start/KeywordStartIT.java
Use the KeywordExecutable service to make wal-info (the WAL LogReader class) available as part of the Accumulo command line. Can be used by running:
accumulo wal-info
Closes #2100
> Make LogReader more discoverable

- core/src/main/java/org/apache/accumulo/core/client/admin/compaction/CompactionConfigurer.java
- core/src/main/java/org/apache/accumulo/core/client/admin/compaction/CompressionConfigurer.java
- server/base/src/main/java/org/apache/accumulo/server/ServiceEnvironmentImpl.java
- server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeChooserEnvironmentImpl.java
- server/base/src/test/java/org/apache/accumulo/server/fs/VolumeManagerImplTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compaction/strategies/ConfigurableCompactionStrategy.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionService.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableUtils.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/compaction/strategies/ConfigurableCompactionStrategyTest.java
While reviewing code in ConfigurationImpl to assess #947, I noticed that ConigurationImpl was doing some caching however the way that ConigurationImpl is made availabe for use could continually create new instances invalidating the caching.  This change makes it so that when ServiceEnvironmentImpl is exposed to plugins it does not continually create new instances, which would cause new instances of ConfigurationImpl to be creatd.
> Avoid recreating ServiceEnvironment

- core/src/main/java/org/apache/accumulo/core/util/LocalityGroupUtil.java
To address issue #2041, this commit contains minor changes to utilize Map.forEach() method instead of Map.entrySet().
> Improve LocalityGroupUtil.java

- server/base/src/main/java/org/apache/accumulo/server/AbstractServer.java
The -a option for server processes was being ignored because the impl read the
argument before arguments were parsed.
> Fixes bug with -a server option

- core/src/main/java/org/apache/accumulo/core/client/AccumuloClient.java
- core/src/main/java/org/apache/accumulo/core/client/ConditionalWriterConfig.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/conf/ClientProperty.java
- test/src/main/java/org/apache/accumulo/test/ConditionalWriterIT.java
- test/src/main/java/org/apache/accumulo/test/functional/AccumuloClientIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SessionDurabilityIT.java
Closes #680
Two main changes:
- Create an overloaded createConditionalMutation(String tableName) method which creates a new ConditionalWriterConfig() so the config is optional to pass
- Allow client properties to be set in the client properties file
> ConditionalWriterConfig - update create method and props gathering

- core/src/main/java/org/apache/accumulo/core/spi/balancer/HostRegexTableLoadBalancer.java
- test/src/main/java/org/apache/accumulo/test/manager/SuspendedTabletsIT.java
The previous attempt to fix SuspendedTabletsIT attempted to use
HostRegexTableLoadBalancer as a per-table balancer. Unfortunately,
HostRegexTableLoadBalancer was not designed to be used that way but
instead was meant to replace TableLoadBalancer and use regular
expressions to divide the hosts into pools. Therefore, the balancer was
failing to initialize and wasn't actually doing any work.
* Performed minor refactoring on HostRegexTableLoadBalancer so that it
can be extended to include the port when performing regex checks.
* Extend HostRegexTableLoadBalancer and configure it to use the port as
well as host name for regex checks so that a single tserver on a host
with multiple tservers running can be isolated and used for a table.
In particular, this is used to send all metadata table …
> Improve SuspendedTabletsIT reliability

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/ClientContextTest.java
Created two unit tests for the conversion of client properties to BatchWriterConfig. One using default values and another using modified values.
Refactored getBatchWriterConfig as suggested in initial ticket.
Added code in getBatchWriterConfig to allow for updating BATCH_WRTIER_THREADS_MAX as it was missing in the method as it existed.
> Unit test converting client props to BatchWriterConfig

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/ClientContextTest.java
Created two unit tests for the conversion of client properties to ConditionalWriterConfig. One using default values and another using modified values.
Refactored getConditionalWriterConfig into two methods to facilitate unit testing.
Closes #2131
> Test converting client props to ConditionalWriterConfig

- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
Noticed the following log messages were very chatty and constantly reporting that a compactor asked for work and there was none.
```
2021-06-04T03:47:45,756 [coordinator.CompactionCoordinator] DEBUG: getCompactionJob called for queue DCQ1 by compactor 10.2.0.236:9133
2021-06-04T03:47:45,756 [coordinator.CompactionCoordinator] DEBUG: No tservers found for queue DCQ1, returning empty job to compactor 10.2.0.236:9133
2021-06-04T03:47:45,995 [coordinator.CompactionCoordinator] DEBUG: getCompactionJob called for queue DCQ1 by compactor 10.2.1.15:9133
2021-06-04T03:47:45,995 [coordinator.CompactionCoordinator] DEBUG: No tservers found for queue DCQ1, returning empty job to compactor 10.2.1.15:9133
2021-06-04T03:47:46,008 [coordinator.CompactionCoordinator] DEBUG: getCompactionJob called for …
```
> Removes chatty logging in coordinator

- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/DeadCompactionDetector.java
Modified the DeadCompactionDetector to fail compactions if
they are dead for more than two cycles. This should handle
the case where there is a transient network issue talking
to another component.
Closes #2125
> Make DeadCompactionDetector handle network hiccups

- core/src/main/java/org/apache/accumulo/core/metadata/schema/ExternalCompactionMetadata.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/TabletFileTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableUtils.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/compaction/CompactableUtilsTest.java
Compute the name of the newly compacted file from the tmp file in
DatafileManager.bringMajorCompactionOnline instead of pre-computing
it, passing it around, and storing it in the external metadata entry
Closes #2110
> Remove redundant information in tablets external compaction entry

- core/src/test/java/org/apache/accumulo/core/clientImpl/TableOperationsHelperTest.java
- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
- shell/src/main/java/org/apache/accumulo/shell/commands/ConfigCommand.java
Fixes #2149 
Fixes the bug where the `config` command inside the accumulo shell returns the properties unordered by using `ImmutableSortedMap.copyOf`.
There is only one instance that the shell output is directly effected by this so the other TreeMaps that were replaced I left alone and did not want to import additional things if it was not needed.
If there are other spots in the commit [4ea9bf1](https://github.com/apache/accumulo/commit/4ea9bf1ac916d66896eaaba329da04714a1e8cba) that would directly benefit from the `ImmutableSortedMap.copyOf` change, I can make those changes as well.
> Change shell 'config' command to display sorted output

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionFinalizer.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/DeadCompactionDetector.java
- test/src/main/java/org/apache/accumulo/test/ExternalCompactionIT.java
Modified the external compaction properties to be in line with other properties
in the codebase. Specifically, I changed
1. the enum names starting with `COORDINATOR` to `COMPACTION_COORDINATOR`
2. the keys starting with `coordinator` to `compaction_coordinator`
3. properties having to with compaction of files to include the term
`compaction` in the key
Closes #2142
> Fix external compaction properties names and keys

- core/src/main/java/org/apache/accumulo/core/file/blockfile/cache/lru/CachedBlock.java
Add blockName to CachedBlock's IllegalStateExceptions, to make the
exceptions more informative and easier to troubleshoot when things go
wrong. This would have helped debug issue #1973 more easily.
> Specify blockName in CachedBlock exceptions

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
Add certain blockcache-related properties to the "fixed" properties
list, which will ensure they are documented as not taking effect until
after a restart. This is already the current behavior, because the cache
manager is instantiated as a singleton only at tserver startup, but this
helps ensure that is predictably the case, and will document it as
requiring a restart in our property documentation.
Also organize the fixed properties into logical groups, just to make it
easier to maintain slightly.
> Document some cache props as requiring restart

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/MinorCompactor.java
Potential fix for #2035. 
The issue with #2035 occurs at https://github.com/apache/accumulo/blob/30ce59fd94f51b60a30ced328156f02d3223330b/server/tserver/src/main/java/org/apache/accumulo/tserver/AssignmentHandler.java#L175
If an iterator is misconfigured, this line will never complete and hang in `MinorCompactor.java`. This potential fix adds a retry counter (only a small amount of retries for testing purposes), solely used when the reason for the minor compaction is recovery. The exception thrown is just a placeholder for now. 
The result from this change is the exception thrown allows the assignments to get rescheduled so other tablets can be loaded in.
> Add retry counter for log recovery with MinC

- core/src/main/java/org/apache/accumulo/core/data/KeyBuilder.java
- core/src/test/java/org/apache/accumulo/core/data/KeyBuilderTest.java
Found this weird bug in `KeyBuilder` while working on #2117. The Java UTF-8 Charset encoder puts an empty byte at the end of the string when there is an underscore present and I can't figure out why. Opening this PR to show the test failure, if anyone has any ideas.
> Add test and fix for bug in KeyBuilder

- test/src/main/java/org/apache/accumulo/test/ExternalCompactionIT.java
Modified the test to use a different parent class that uses a
shared MiniAccumuloCluster for the different tests. Also reduced
the time based configuration properties in an attempt to make
things faster.
Closes #2159
> Make ExternalCompactionIT faster by reusing MiniAccumuloCluster

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/LogSorter.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogReader.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/logger/LogFileKey.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/logger/LogFileValue.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/log/SortedLogRecoveryTest.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/log/TestUpgradePathForWALogs.java
- test/src/main/java/org/apache/accumulo/test/MultiTableRecoveryIT.java
* Change LogSorter and SortedLogRecovery to write/read RFile instead of MapFile
* Rewrite LogSorter writeBuffer method and make static to test
* Create toKey() and fromKey() methods in LogFileKey for converting WAL keys
* Create toValue() and FromValue() methods in LogFileValue for converting WAL values
* Byte encode the rows of the Key to sort WAL events properly
* Make RecoveryLogsIterator convert Key Value pairs on next()
> Make sorted recovery write to RFiles

- server/tserver/src/main/java/org/apache/accumulo/tserver/logger/LogFileKey.java
Fix bitwise operations to encode and decode the tabletId and sequence
number to/from a row
This fixes #2173
> Fix row encoding/decoding in LogFileKey

- server/manager/src/main/java/org/apache/accumulo/manager/FateServiceHandler.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/Utils.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/cancel/CancelCompactions.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/DeleteTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/PreDeleteTable.java
Check to see if the locks are already held for deleting the table.
If they are, then we likely already canceled the compactions. Related
to #2030
> Make DeleteTable fate lock reentrant

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/test/java/org/apache/accumulo/core/conf/SiteConfigurationTest.java
- core/src/test/resources/accumulo2.properties
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloConfigImpl.java
- server/base/src/main/java/org/apache/accumulo/server/master/recovery/HadoopLogCloser.java
- server/manager/src/main/java/org/apache/accumulo/manager/recovery/RecoveryManager.java
- server/manager/src/test/resources/conf/accumulo-site.xml
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- test/src/main/java/org/apache/accumulo/test/MetaRecoveryIT.java
- test/src/main/java/org/apache/accumulo/test/TabletServerGivesUpIT.java
- test/src/main/java/org/apache/accumulo/test/UnusedWALIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ManyWriteAheadLogsIT.java
- test/src/main/java/org/apache/accumulo/test/functional/RestartStressIT.java
- test/src/main/java/org/apache/accumulo/test/functional/WALSunnyDayIT.java
- test/src/main/java/org/apache/accumulo/test/functional/WriteAheadLogIT.java
- test/src/main/java/org/apache/accumulo/test/replication/CyclicReplicationIT.java
- test/src/main/java/org/apache/accumulo/test/replication/GarbageCollectorCommunicatesWithTServersIT.java
- test/src/main/java/org/apache/accumulo/test/replication/KerberosReplicationIT.java
- test/src/main/java/org/apache/accumulo/test/replication/MultiInstanceReplicationIT.java
- test/src/main/java/org/apache/accumulo/test/replication/ReplicationIT.java
- test/src/main/java/org/apache/accumulo/test/replication/UnorderedWorkAssignerReplicationIT.java
Fixes #2146 
This fix makes the property names regarding write ahead logs uniform. All properties that used `walog` were tagged as deprecated and with a `@ReplacedBy` tag to its respected `wal` replacement. 
For some uses of the new property names, the `conf.resolve()` function was used in order to read the values from whichever key the user used (whether it be the deprecated or new one).
While making these changes I decided to exclude the use of the `resolve` function in the ITs where the new properties were used. From what I understood, there would be no real reason to resolve the usages. There were also some places where Null Pointer Exceptions would occur if they were to be resolved. Please let me know if this was wrong.
I also found a section in `HadoopLogCloser` where I did not see …
> Change WALOG Property Names to WAL

- server/tserver/src/main/java/org/apache/accumulo/tserver/log/LogSorter.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/log/SortedLogRecoveryTest.java
* Refactor LogSorter writeBuffer to allow use of system configuration
when writing out sorted rfiles. This will use configured settings on the
sorted files instead of only the defaults.
> Refactor LogSorter to use config

- server/base/src/main/java/org/apache/accumulo/server/util/CheckForMetadataProblems.java
Fixes #2166 
This PR updates the output of the CheckForMetadataProblems utility. It previously included a mix of table ids and names.
The output now offers more information and is much more easily read.
Some changes and additions that are included:
- `checkTable` function now accepts a String tableName 
- Uses `Tables.getTableID()` and `Tables.getTableName()` to get information about the specific tables
- Places the client scanner inside of the try block in `checkMetadataAndRootTableEntries()`
- Updates potential error messages that were not shown in the output in the initial ticket.
During my testing I did notice that there is an extra line that shows some log info about the path to accumulo.properties that gets displayed before the expected output. I am not sure if this is a big issue …
> Update CheckForMetadataProblems Utility Output

- core/src/main/java/org/apache/accumulo/core/client/TableOfflineException.java
- core/src/main/java/org/apache/accumulo/core/client/mapred/AbstractInputFormat.java
- core/src/main/java/org/apache/accumulo/core/client/mapreduce/AbstractInputFormat.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ConditionalWriterImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ConnectorImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ReplicationOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/Tables.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchDeleter.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchReader.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchReaderIterator.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftScanner.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/TabletServerBatchReaderTest.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapred/AccumuloRecordReader.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/AccumuloRecordReader.java
- server/base/src/main/java/org/apache/accumulo/server/master/balancer/TableLoadBalancer.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tables/TablesResource.java
Improve client-side table exception handling by providing tableNames
from the client to avoid looking them up later to format an exception
message.
* Add TableOfflineException constructor to provide a formatted message
without requiring a ClientContext to look up the name or id
* Reuse code to check for TableNotFoundException, TableDeletedException,
and TableOfflineException using convenience methods in ClientContext
* Pass along tableName alongside tableId, in some internal client-side
code, for use in exception messages, if needed later
* Make check for requiring that a table not be offline explicit, rather
than entangled with the tableId lookup in ClientContext
* Update ConnectorImpl to proxy to ClientContext in a few cases where
it previously wasn't, to ensure consistent behavior and …
> Improve client table exceptions

- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- test/src/main/java/org/apache/accumulo/test/functional/SummaryIT.java
Fix SummaryIT, broken by #2195; restore late table existence checks, so
table doesn't need to exist until you call retrieve() on the
SummaryRetriever
Improve SummaryIT by making it share a cluster, so it runs faster, and
by using assertThrows() instead of try-catch blocks and fail()
> Fix and improve SummaryIT

- core/src/main/java/org/apache/accumulo/core/conf/ConfigurationDocGen.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
Fixes #1117 
In this PR the following has been added:
- A new enum constructor parameter in `Property.java` that provides `since` information about when the property was first introduced
- Updated the information provided in `server-properties.md`
- Added `deprecated since` information where applicable
- Added `replaced by` information where applicable
- Added `available since` information where applicable
- Provided all existing properties with their `availableSince` information
- Removed redundant information within existing property descriptions that are now found elsewhere
> Add since information to properties

- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
While looking at https://issues.apache.org/jira/browse/ACCUMULO-3694 and testing the 'accumulo init --reset-security' feature, I ran into an error related to jline3 and how LineReader uses a default terminal and terminal type if none is specified.  A terminal object will now be created in the same way it is done in the shell.
Error:
> Fix initialize.java by using terminalBuilder instead of default terminal

- core/src/main/java/org/apache/accumulo/core/metadata/schema/AmpleImpl.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java
- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Fixes: #2154
Marked this as WIP because there are several possible ways that this issue could be handled. Two of which are implemented in these changes:
- In `AmpleImpl.readTablet()` check that the `prevEndRow`s match before returning
- In `TabletsMetadata.forTablet()`, instead of `toMetaRow()`, use `toMetaRange()` which accounts for `prevEndRow`
There are likely other solutions to this. I wanted to create this to get feedback and discussion on this issue.
I also added small improvements to TabletsMetadata.java while I was making changes.
> Make Ample only return exact matches for KeyExtents

- core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java
- core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScannerBuilder.java
- core/src/main/java/org/apache/accumulo/core/client/rfile/RFileSummariesRetriever.java
- core/src/main/java/org/apache/accumulo/core/file/blockfile/impl/CachableBlockFile.java
- core/src/main/java/org/apache/accumulo/core/summary/SummaryReader.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/MultiLevelIndexTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/RFileTest.java
The code between the BCFile cache and the RFile API is a mess. This is an attempt to prevent cacheId from being null. I am hoping with all the tests passing we can catch all the spots where it isn't set.
> Make CachableBlockFile builder require nonNull for cacheId 

- server/manager/src/main/java/org/apache/accumulo/manager/FateServiceHandler.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/create/PopulateZookeeper.java
Fixes #2196.
A check has been added to `FateServiceHandler` to check the properties before the create table operation is kicked off. This check makes use of the return value of the already-in-place `TablePropUtil.setTableProperty`
A redundant check is added to `PopulateZookeeper`.
These two additions essentially do the same thing, so [it has been mentioned](https://github.com/apache/accumulo/issues/2196#issuecomment-879415745) that a single static method could be added and used in these two places. I wanted to get some feedback on the trade off between these changes which make use of the existing code, and the possibility of using a single method here instead.
> Sanity check table properties prior to creation of fate operation

- core/src/main/java/org/apache/accumulo/core/metadata/schema/ExternalCompactionMetadata.java
- server/base/src/main/java/org/apache/accumulo/server/compaction/CompactionInfo.java
- server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
There are several places where the word 'prop**a**gate' is incorrectly spelled 'prop**o**gate'.
> Fix typo 'propogate'

- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
- server/base/src/main/java/org/apache/accumulo/server/util/ListVolumesUsed.java
- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectionAlgorithm.java
- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectionEnvironment.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/gc/src/test/java/org/apache/accumulo/gc/GarbageCollectionTest.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorIT.java
Updated Garbage Collection code to no longer use a continue point when processing deletion candidates. The GC  now uses an iterator that lasts during the lifetime of a GC cycle.
The GarbageCollectionTest was updated to work with the update, as was the GC integration test.
Closes #1351
> Remove continue point from Garbage Collector

- core/src/main/java/org/apache/accumulo/core/iterators/user/TransformingIterator.java
In reference to JIRA ticket: https://issues.apache.org/jira/browse/ACCUMULO-4149
I am not quite sure what JIRA issue the Javadoc was referencing (I tried to investigate but came up empty) but it was also discussed that referencing JIRA issues directly in a Javadoc was unnecessary. Removing the line to clean up the doc but I am open to suggestions if more information should be added to that paragraph.
> Remove unnecessary line in javadoc of TransformingIterator

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/Compression.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/LogSorter.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/log/SortedLogRecoveryTest.java
- test/src/main/java/org/apache/accumulo/test/MultiTableRecoveryIT.java
* Closes #2187 
* Create new property prefix "tserver.wal.sort.file." to configure the
rfiles written during sorted recovery
* Add method to LogSorter to convert the sort file properties to table
files properties
* Create new tests in SortedLogRecoveryTest
* Make method public in Compression to use in test
* Add property to MultiTableRecoveryIT to allow testing in an IT
> Add new property to configure rfile sorted recovery

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/LogSorter.java
* Create tserver.wal.sort.buffer.size to replace tserver.sort.buffer.size
* Create tserver.wal.sort.concurrent.max to replace tserver.recovery.concurrent.max
* All LogSorter properties now start with tserver.wal.sort
> Rename LogSorter properties to be consistent

- core/src/main/java/org/apache/accumulo/core/spi/common/ContextClassLoaderFactory.java
- start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloVFSClassLoader.java
* Rename new class loader variable from context to contextName to avoid
confusion with other types of context objects
> Rename new Class loader variable to contextName

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
For the refactoring done in #2213, the semantics of the following code that existed prior to the change were not properly translated.
https://github.com/apache/accumulo/blob/146b1d3d0dc2ade6f1888c9905d83e37d98aedbe/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java#L665-L671
This caused the exceptions in #2239.  This PR reintroduces the above semantics.
> fixes #2239 fixed bug in gathering compaction candidates

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
I noticed when looking into #2239 that when a compaction job starts and reserves files that there is no check to ensure the tablet still has those files.  I think this race condition is unlikely to occur, but not impossible.  This PR add a check for this.  This check prevents unnecessary work from occurring.  The code is correct without the check in that it would currently fail after the compaction runs if this situation were to occur.
> Prevents compaction when tablet does not know of files

- core/src/main/java/org/apache/accumulo/core/client/admin/compaction/CompactableFile.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/CompactionPlan.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionPlanImpl.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionService.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
* Split compact method in CompactionService into to 2 methods:
getCompactionPlan() and submitCompactionJob()
* Rename other compact() in CompactionManager and CompactionService to submitCompaction()
* Add javadoc comments to various methods
* Add final to various private members
* Drop redundant enum check and boolean assignment
Edit: ~~Add getCandidates() method to CompactionPlan~~
> Split compact method into two more specific methods

- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/ExtCEnv.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableUtils.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/MajCEnv.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/MinCEnv.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/MinorCompactor.java
- test/src/main/java/org/apache/accumulo/test/ExternalCompactionIT.java
* Make compact method in CompactableUtils just call compact and return
the majc stats, removing the need to mutate the object across method calls. 
* Pass the CompactionInfo object as a param to reduce the number of params 
to the compact method. 
* Pull logic from compact method and put into new bringOnline method, further 
reducing the number of params to the compact method. The bringOnline method
returns the completed StoredTabletFile 
* Replace anonymous CompactionEnv classes with 2 new classes: MinCEnv & MajCEnv
* Rename CompactionEnvironment to ExtCEnv to differentiate from the
other types of CompactionEnv implementations
* Add javadoc comments describing methods
> Clarify compact method

- core/src/main/java/org/apache/accumulo/core/util/ThriftMessageUtil.java
- pom.xml
- server/base/src/main/java/org/apache/accumulo/server/rpc/TimedProcessor.java
- server/base/src/main/java/org/apache/accumulo/server/rpc/UGIAssumingProcessor.java
In Apache Thrift all versions up to and including 0.12.0, a server or client may run into an endless loop when feed with specific input data.
Some of the classes Accumulo relied on (ie AutoExpandingBufferWriteTransport) are no longer public so the utility methods had to be rewritten. Unfortunately there is no TTransport implementation with the same functionality AutoExpandingBufferWriteTransport provided so I had to switch to TMemoryBuffer as a substitute. However this can not be reset and a new object have to be created for each serialization which is less then optimal. I considered adding a custom implementation, but the changes in the deserialize method should compensate for the the loss of performance.
> Upgrade Thrift to 0.13.0

- core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java
- server/base/src/main/java/org/apache/accumulo/server/ServerContext.java
- server/base/src/main/java/org/apache/accumulo/server/fs/FileManager.java
- server/base/src/main/java/org/apache/accumulo/server/manager/LiveTServerSet.java
- server/base/src/main/java/org/apache/accumulo/server/zookeeper/DistributedWorkQueue.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/recovery/RecoveryManager.java
- server/manager/src/main/java/org/apache/accumulo/manager/replication/DistributedWorkQueueWorkAssigner.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer1/CopyFailed.java
- server/tracer/src/main/java/org/apache/accumulo/tracer/TraceServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/AssignmentHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/LogSorter.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/replication/ReplicationWorker.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactionWatcher.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/AssignmentWatcherTest.java
Commit e62ace6a9d37572d95999f5412c6148efbba50b9 removed SimpleTimer in favor of
a new ThreadPools class that centralized the creation of thread pools. However, I
missed the fact that SimpleTimer used a shared thread pool. This change reintroduces
a shared generic ScheduledThreadPoolExecutor that can be obtained by calling
ServerContext.getSharedGenericScheduledExecutorService().
Closes #2280
> Recreated the SimpleTimer functionality with the new ThreadPools class

- core/src/main/java/org/apache/accumulo/core/data/constraints/Constraint.java
- server/gc/src/test/java/org/apache/accumulo/gc/GarbageCollectionTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableUtils.java
* Remove unused import
* Remove unused log field in test class
* Remove misleading javadoc about renamed constraint check method that
wasn't renamed
> Fix trivial warnings

- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/CompactionInfo.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/CompactionsResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/scans/ScanInformation.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/scans/ScansResource.java
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/compactions.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/scans.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/compactions.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/scans.ftl
* Drop fetchScans and fetchCompactions threads and just let the page
refresh get the data as needed. Created constant to prevent fetching
more then once a minute. Created time constant for age off
* Replace active scans table with datatables and add fetched column
* Add fetched column to Active compactions table
* Refactored fetch methods to catch thrift error and log.
* Made entry point methods getCompactions and getScans synchronized to
allow removal of synchronized code blocks.
> Improve fetching scans and compactions in Monitor

- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java
- core/src/test/java/org/apache/accumulo/core/util/compaction/CompactionPrioritizerTest.java
Currently Accumulo uses the total number of files in a tablet as the priority for compactions that run against a tablet. So for the following queued tablet compactions
Tablet Name | Total files | Files to compact
-|-|-
A | 20 | 10
B | 22 | 3
The tablet B with 22 total files would have a higher priority than A and would compact first.  The goal of the priority is to reduce the overall number of files per tablet.  Running the compaction for A before B would better accomplish this goal because it will compact 10 files resulting in the tablet having 11 files after the compaction.  The compaction for B will compact 3 files resulting in a total of 20 file after the compaction.  However the current priority scheme chooses B before A.
This PR changes a compactions priority from totalTabletFiles …
> Use numFilesCompacting+totalTabletFiles for compaction priority

- test/src/main/java/org/apache/accumulo/test/functional/ManagerApiIT.java
* Closes #2327
* Drop the second RPC call in the last test of the ManagerApiIT
* ThriftTransportPool is now a part of ClientContext and only allows for
a single remaining connection after shutting down
> Modify shutdown test in ManagerApiIT

- core/pom.xml
- core/src/test/java/org/apache/accumulo/core/crypto/CryptoTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/RFileTest.java
- server/base/pom.xml
- server/tserver/pom.xml
* Make CryptoTest and RFileTest use unique key files, so they don't
interfere with one another when run concurrently
* Fix tests being run twice when specified explicitly with -Dtest=
parameter (found while testing this PR) by creating separate profile
in pom.xml files that had a second surefire execution, that is
automatically disabled when that property is used
Fixes #2343
> Use unique test file locations for crypto tests

- core/src/main/java/org/apache/accumulo/core/logging/TabletLogger.java
- server/base/src/main/java/org/apache/accumulo/server/util/ManagerMetadataUtil.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- test/src/main/java/org/apache/accumulo/test/functional/FlushNoFileIT.java
- test/src/main/java/org/apache/accumulo/test/functional/FunctionalTestUtils.java
This PR creates an IT to expose a bug introduced in #1605. If a flush doesn't produce any entries in `DataFileValue`, then a `StoredTabletFile` won't be created, since nothing was inserted into the metadata, and the newFile object will be null. Refactoring was done in `DatafileManager` to the bringMinorCompactionOnline() method so that it now returns the newFile. But this file could be null, if nothing was written to the metadata table. I am not sure what should be done to fix this issue but I was at least was able to reproduce it in an IT. ~~This bug is particularly nasty since Accumulo thinks the flush succeeds but the error will be thrown towards the end of the process and the file never gets created.~~
Server error printed in tablet server log:
<pre>
2021-11-02T13:23:03,134 …
> Create FlushNoFileIT and fix NPE in tablet file flush code 

- server/tserver/src/main/java/org/apache/accumulo/tserver/AssignmentHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/CheckTabletMetadataTest.java
Fixes : #2208 
Note: AssignmentHandler has a lot of spacing changes. only the method has been moved and a string constant has been introduced.
> Move checkTableMetaData to AssignmentHandler file

- core/src/main/java/org/apache/accumulo/core/client/mapred/AccumuloFileOutputFormat.java
- core/src/main/java/org/apache/accumulo/core/client/mapreduce/AccumuloFileOutputFormat.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/mapreduce/lib/FileOutputConfigurator.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/Compression.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/bcfile/CompressionTest.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/FileOutputFormatBuilder.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/lib/FileOutputConfigurator.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compaction/strategies/BasicCompactionStrategy.java
- shell/src/main/java/org/apache/accumulo/shell/commands/CompactCommand.java
Hadoop compression support for 'lz4' and 'bzip2' codecs.  Updates javadoc and normalizes comments for lz4, bzip2, and zstd.
Implements #2366
> Add support for LZ4 and BZip2 Codecs

- shell/src/main/java/org/apache/accumulo/shell/commands/GetSplitsCommand.java
- test/src/main/java/org/apache/accumulo/test/ShellIT.java
In the Accumulo shell, calling getsplits with the verbose option can result in incorret output. It occurs when the tableId of the table
happens to be a single character and there are other tables where the tableId starts with the same character. This results in the output of getsplits displaying splits for the other tables as well.
Closes #2356
> Fix incorrect scan range output in getsplits command

- core/src/main/java/org/apache/accumulo/core/metadata/schema/RootTabletMetadata.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/RootTabletMutatorImpl.java
The root table mutation was pretty printing the mutation json object, causing the log statement to extend over multiple lines. This change removes the pretty print and combines the form / to so that it is one (very long line)
The information seemed useful, but trace may be a better level, but I was unsure.
I also tried using guava Map.compare, but the result did not seem much easier to read than just removing pretty printing.
<details>
<summary>Click to expand!</summary>
Before:
```  
2021-12-07T01:18:14,946 [metadata.RootTabletMutatorImpl] DEBUG: Before mutating : {
"version": 1,
"columnValues": {
"file": {
"file:[dir...]/test/target/mini-tests/org.apache.accumulo.test.compaction.ExternalCompaction_2_IT_testExternalCompactionsSucceedsRunWithTableOffline/accumulo/tables/+r/root_tablet/A000 …
```
> reduce root table mutation logging to single line

- server/base/src/main/java/org/apache/accumulo/server/ServerInfo.java
See the discussion and the thread dumps at https://lists.apache.org/thread/rwt4nomkmhty1dy4tsp620sf49o3qnbx
Without this improvement  org.apache.accumulo.test.functional.ConcurrentDeleteTableIT takes 785.503 s on my machine, and I need to use -Dtimeout.factor=3 to pass.
With this improvement the test now passes in 127.771 s, i.e. almost 6 times faster!
```
"tablet migration-Worker-1" #4380 daemon prio=5 os_prio=0 cpu=68425.44ms elapsed=75.42s tid=0x0000fffeac074800 nid=0x33077e runnable  [0x0000fffe8f3fd000]
java.lang.Thread.State: RUNNABLE
at sun.security.provider.SHA5.implCompressCheck(java.base@11.0.11/SHA5.java:232)
at sun.security.provider.SHA5.implCompress(java.base@11.0.11/SHA5.java:221)
at sun.security.provider.DigestBase.engineUpdate(java.base@11.0.11/DigestBase.java:124)
at …
```
> Cache the credentials because they are expensive to fetch

- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/compactor/src/test/java/org/apache/accumulo/compactor/CompactorTest.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalDoNothingCompactor.java
The Thread in the Compactor that runs the FileCompactor was throwing an
exception as part of the error handling routine. It's not necessary for
that to occur to convey the exception information to the main thread,
the exception information was already being conveyed. This will reduce
the error logging in the Compactor log regarding the uncaught exception
being thrown and handled by the AccumuloUncaughtExceptionHandler.
Another background thread checks every 5 seconds to determine whether
or not the current compaction should be canceled. Call this method
when the compaction completes in case something happens that would
cause the compaction to be canceled and it has not been noticed yet.
Closes #2350
> Exception and cancellation changes in Compactor process

- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- test/src/main/java/org/apache/accumulo/test/ShellIT.java
Refactored listSplits method in TableOperationsImpl. This change affects the listSplits command which takes maxSplits as an option.
* Renamed variable names to enhance readability.
* Added documentation for the method.
* Replaced while-loop with if-loop after determining while-loop was only run at most once each time.
* Created IT test for method in ShellIT class.
Closes #2371
> Refactor listSplits operation when using maxSplits

- pom.xml
Since #2382 log4j released version 2.16.0 that has minor fixes to further mitigate log4j CVEs.
> bump log4j2 version to 2.16.0

- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/CompactorInfo.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/ECResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/RunningCompactions.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/RunningCompactorDetails.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/RunningCompactorInfo.java
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/ec.js
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java
* Limits data brought to the browser from the Monitor by adding a
separate AJAX call to get the details of the compaction
* Creates a new type and endpoint for RunningCompactorDetails
* Move the files from RunningCompactorInfo to details object
* Supports #2365
> Improvements to monitor external compactions page

- assemble/conf/accumulo-env.sh
* Remove unneeded/useless exports; they don't need to be exported by
default, since the env script is sourced by bin/accumulo, and they
don't need to be passed to child processes; the user can modify their
own env script if they need these to be passed to their child
processes because of their specific needs
* Treat ACCUMULO_JAVA_OPTS as scalar variable containing space-delimited
command-line options to prepend to JAVA_OPTS in accumulo-env.sh rather
than assume it's an array, because arrays can't currently be exported
in bash, so it's not possible for users to have set it in their
environment as an array to be picked up here
> Fix accumulo-env.sh variables

- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/ECResource.java
* Monitor would stop checking for the coordinator once it found it
* This fix will detect if the coordinator moves or is no longer available
> Fix coordinator check in Monitor

- pom.xml
Update log4j2 to 2.17.1 (released 12/27/2021) - fixes cve
Update slf4j to 1.7.32 (released 7/20/2021) - minor updates
> Update log4j2 to 2.17.1 and slf4j to 1.7.32

- core/src/main/java/org/apache/accumulo/core/util/compaction/RunningCompaction.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/RunningCompactionInfo.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/CompactorInfo.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/ECResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/RunningCompactions.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/RunningCompactorDetails.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java
* Create RunningCompactionInfo in core to be reused outside the Monitor
* Moves the logic for parsing progress from running compactions to core so that
server utilities can get the progress as well
> Create RunningCompactionInfo in core for reuse

- assemble/bin/accumulo-util
- core/src/main/java/org/apache/accumulo/core/client/AccumuloClient.java
- core/src/main/java/org/apache/accumulo/core/client/admin/CompactionStrategyConfig.java
- core/src/main/java/org/apache/accumulo/core/conf/AccumuloConfiguration.java
- core/src/main/java/org/apache/accumulo/core/logging/Logging.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/CompactionPlanner.java
- core/src/main/java/org/apache/accumulo/fate/AdminUtil.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/MultiThreadedRFileTest.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapred/AccumuloRowInputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/AccumuloInputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/AccumuloRowInputFormatIT.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compaction/MajorCompactionRequest.java
- start/src/main/java/org/apache/accumulo/start/spi/KeywordExecutable.java
This pull request serves to correct more mistakes in potential user-facing areas. 
In my first PR regarding misspellings (#2400), I did not include mistakes found in Javadocs. Most of the corrections in this PR focus on Javadoc as well as a few other mistakes that were overlooked in the original.
This will be my final PR that focuses on misspellings.
> Correct user-facing misspellings (Part 2)

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java
This PR aims to address issue #2355.
Removed deadcode regarding an unused while-loop which condition was always false. This condition was evaluated with the value of a variable called 'reservationsBlocked', which was initialized with value 'false' and it was never changed.
> Removed deadcode regarding unused while-loop

- core/src/main/java/org/apache/accumulo/core/clientImpl/OfflineIterator.java
Closes #2413 
#2413 was created to address the possibility of two things:
* Reusing common code within ScanDataSource
* Closing resources that were left open (readers, files)
It seems that neither of these should be done. 
The original Jira ticket referenced shared code between OfflineIterator and Tablet, but since then, the code has moved to ScanDataSource and changed significantly meaning extracting commonalities between the two may not be worth it/feasible. 
The second point about closing the resources proves to cause error. If the readers or files are closed, the iterator fails to read the intended data therefore I think its best if they are not closed.
The changes made in this PR:
* Remove the comments that refer to these issues
* Make some variables final
* Simplify some logic
> Remove obsolete comments and add minor improvements to OfflineIterator

- server/tserver/src/main/java/org/apache/accumulo/tserver/InMemoryMap.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/NativeMap.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/memory/NativeMapLoader.java
- test/src/main/java/org/apache/accumulo/test/InMemoryMapIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ConfigurableMacBase.java
- test/src/main/java/org/apache/accumulo/test/functional/NativeMapIT.java
* Create a separate NativeMapLoader and relocate into that new class the
code to load the native libraries that was previously in NativeMap
alongside the actual code for handling native maps
* Remove unnecessarily redundant `isLoaded()` checks, since the behavior
is now to `System.exit(1)` if the native code is configured to be
used, but cannot be loaded. There is no longer a question of whether
they are loaded. They are always loaded if configured to be, or else
the tserver will die on startup.
* Simplify and organize the loader code
* Make the loader code work better with tests by providing a method
specifically for testing (for NativeMapIT, and InMemoryMapIT,
specifically, because they need to load native maps inside the test
thread, and not on a tserver)
* Update ConfigurableMacBase …
> Separate native map loading from native map code

- test/src/main/java/org/apache/accumulo/test/start/KeywordStartIT.java
Fixes KeywordStartIT error by adding ec-admin to expected keywords.
> Add ec-admin to expected in KeywordStartIT

- core/src/test/java/org/apache/accumulo/core/client/admin/NewTableConfigurationTest.java
- core/src/test/java/org/apache/accumulo/core/spi/fs/SpaceAwareVolumeChooserTest.java
- server/base/src/test/java/org/apache/accumulo/server/security/delegation/ZooAuthenticationKeyDistributorTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/replication/ManagerReplicationCoordinatorTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/upgrade/AccumuloTest.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/TabletServerSyncCheckTest.java
- test/src/main/java/org/apache/accumulo/test/MetaConstraintRetryIT.java
- test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java
- test/src/main/java/org/apache/accumulo/test/ShellServerIT.java
- test/src/main/java/org/apache/accumulo/test/functional/KerberosIT.java
Improve assertThrows changes by limiting the wrapping of methods to only
the method that actually throws the exception.
Found and fixed a few EasyMock replay problems in
ManagerReplicationCoordinatorTest that only worked with a specific test
execution order, and wouldn't work when tests were run individually.
Moved some NewTableConfigurationIT tests to NewTableConfigurationTest,
because they didn't need to be integration tests, as they are expected
to fail during construction of the NewTableConfiguration, and don't
require the NTC to be used to actually create a table on a test
instance.
Replace complicated try-catch blocks that check for e.getCause() with an
assertThrows that preserves the thrown exception and checks .getCause()
directly with a subsequent assertEquals statement.
Add a …
> Wrap only method that throws with assertThrows

- core/src/main/java/org/apache/accumulo/core/metrics/MetricsProducer.java
- test/src/main/java/org/apache/accumulo/test/functional/LateLastContactIT.java
- test/src/main/java/org/apache/accumulo/test/functional/RestartIT.java
- test/src/main/java/org/apache/accumulo/test/functional/WatchTheWatchCountIT.java
- test/src/main/java/org/apache/accumulo/test/metrics/MetricsIT.java
* Increase timeout for LateLastContactIT
* Fix broken RestartIT by cleaning up stopped processes before restarting
* Fix broken MetricsIT by streamlining the logic, after which it became
apparent that the flaky metrics shouldn't have been included in the
metrics the test expects to see; also removed seemingly unnecessary 30
second pause, since the test runs consistently in about 15 seconds
without it and it didn't seem to be waiting on any particular
condition
> Fix some broken/flaky ITs

- core/src/main/java/org/apache/accumulo/core/trace/TraceUtil.java
- core/src/main/java/org/apache/accumulo/core/trace/TraceWrappedCallable.java
- core/src/main/java/org/apache/accumulo/core/trace/TraceWrappedRunnable.java
- core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java
- core/src/main/java/org/apache/accumulo/core/util/threads/Threads.java
- server/base/src/main/java/org/apache/accumulo/server/AbstractServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/InternalCompactionExecutor.java
Wrap Runnable and Callable objects properly inside thread pools in a way
that allows us to unwrap them to make comparisons in priority blocking
queues, and to remove them from blocking queues when we're directly
manipulating those thread pool queues.
This fixes #2362
> Wrap and unwrap tasks in thread pools properly

- core/src/main/java/org/apache/accumulo/core/util/HostAndPort.java
Removed a self-assignment of the hostPortString variable to itself.
If the hostPortString is non-null, nothing happens and the variable is unchanged. If the hostPortString is null, a ullPointerException is thrown. There is no need to assign it to itself.
Change suggested by errorprone analysis.
> Remove self-assignment statement.

- server/tserver/src/main/java/org/apache/accumulo/tserver/NativeMap.java
Remove redundant call to NativeMapLoader.load() in NativeMap, which
isn't needed because the TabletServerResourceManager already loads it
when the tserver starts up. This static initializer caused problems with
test references to NativeMap, and tried to load the native map library
before the test had a chance to load it from the search path.
Instead, if NativeMap is attempted to be used without loading the native
library, it will just naturally throw an UnsatisfiedLinkError.
This fixes #2450
> Remove redundant native map loading

- server/base/src/main/java/org/apache/accumulo/server/rpc/CustomNonBlockingServer.java
- server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java
- server/base/src/test/java/org/apache/accumulo/server/util/TServerUtilsTest.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/compactor/src/test/java/org/apache/accumulo/compactor/CompactorTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- test/src/main/java/org/apache/accumulo/test/rpc/ThriftBehaviorIT.java
With newer versions of Thrift, the executor service used inside the
server is reachable by calling `getInvoker()`. So, it is no longer
necessary to use reflection to try to access the private field to shut
it down. This change removes that reflection code and shuts down the
executor service in the stop() method of our custom subclass. Since that
is substantially simpler, it is no longer necessary to have a dedicated
static utility method to stop a server. That method is removed and
stop() is called directly.
> Remove unnecessary TServerUtils stop method

- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionTestUtils.java
Stabilize some external compaction ITs by ensuring the compaction
coordinator is using port search when it starts up, in case the
requested port is not available.
> Use port search for compaction coordinator in ITs

- core/src/main/java/org/apache/accumulo/core/client/admin/DelegationTokenConfig.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/AuthenticationTokenIdentifier.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/DelegationTokenImpl.java
- core/src/test/java/org/apache/accumulo/core/client/security/tokens/DelegationTokenImplTest.java
- core/src/test/java/org/apache/accumulo/core/rpc/SaslConnectionParamsTest.java
- core/src/test/java/org/apache/accumulo/core/security/AuthenticationTokenIdentifierTest.java
- server/base/src/main/java/org/apache/accumulo/server/security/delegation/AuthenticationTokenSecretManager.java
- server/base/src/test/java/org/apache/accumulo/server/rpc/SaslDigestCallbackHandlerTest.java
* Refactor the class by removing extra constructors and making the
private impl object final. This allowed removal of null checks
* Create method in AuthenticationTokenSecretManager to set the user
overriden values. This prevents having to hang config object off of
AuthenticationTokenIdentifier
* Possibly closes #2456
> Refactor AuthenticationTokenIdentifier & DelegationTokenImpl

- core/src/main/java/org/apache/accumulo/fate/AdminUtil.java
- core/src/main/java/org/apache/accumulo/fate/AgeOffStore.java
- core/src/main/java/org/apache/accumulo/fate/Fate.java
- core/src/main/java/org/apache/accumulo/fate/ReadOnlyTStore.java
- core/src/main/java/org/apache/accumulo/fate/ZooStore.java
- server/manager/src/main/java/org/apache/accumulo/manager/metrics/fate/FateMetrics.java
- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/FateIT.java
When a FaTE transaction is created in the Manager its status is set
to IN_PROGRESS even though it's not actually running, it could be
waiting to run. The output from the `fate print` command will show
that the newly created transaction is IN_PROGRESS and could be
confusing to users. This change introduces the SUBMITTED state, which
is the state of the transaction after it has been created but before
it is executed.
> Added FaTE TStatus.SUBMITTED

- assemble/bin/accumulo
- assemble/pom.xml
- assemble/src/main/assemblies/component.xml
- core/pom.xml
- docs/pom.xml
- examples/simple/pom.xml
- fate/pom.xml
- iterator-test-harness/pom.xml
- maven-plugin/src/it/plugin-test/pom.xml
- minicluster/pom.xml
- minicluster/src/main/java/org/apache/accumulo/minicluster/impl/MiniAccumuloClusterImpl.java
- pom.xml
- proxy/pom.xml
- server/base/pom.xml
- server/gc/pom.xml
- server/master/pom.xml
- server/monitor/pom.xml
- server/native/pom.xml
- server/tracer/pom.xml
- server/tserver/pom.xml
- shell/pom.xml
- start/pom.xml
- test/pom.xml
For the 1.10.x branch, use reload4j instead of the EOL log4j1.2, which
contains several CVEs and is no longer supported by its Apache project.
Reload4j is the continuation of log4j1.2, forked from the Apache
project by the original log4j1 creator. It is largely a drop-in
replacement for log4j1.2.
> Swap in reload4j instead of log4j1.2

- core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/Utils.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- test/src/main/java/org/apache/accumulo/test/replication/UnorderedWorkAssignerReplicationIT.java
From errorpone bug pattern description:
Performing an arithmetic expression on arguments of type int and then
assigning the result to a long is error-prone. The result is widened to
a long as the final step, and the intermediate results may overflow.
> Expresion of type int may overflow before assignment to long.

- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/ServiceLockIT.java
Replace t.join within the try/catch of ServiceLockIT with the use of Uninterruptibles.joinUninterruptibly.
> Utilize Uninterruptibles.joinUninterruptibly in ServiceLockIT

- core/src/main/java/org/apache/accumulo/core/file/FileOperations.java
- core/src/main/java/org/apache/accumulo/fate/zookeeper/ZooCache.java
- server/base/src/main/java/org/apache/accumulo/server/client/BulkImporter.java
- server/base/src/main/java/org/apache/accumulo/server/log/WalStateManager.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/replication/AccumuloReplicaSystem.java
- test/src/main/java/org/apache/accumulo/test/rpc/Mocket.java
Several classes were flagged by errorprone as inner classes which could
be made static. Per errorprone justification:
"An inner class should be static unless it references members of its
enclosing class. An inner class that is made non-static unnecessarily
uses more memory and does not make the intent of the class clear."
> Class can be static

- core/src/main/java/org/apache/accumulo/fate/Fate.java
- server/manager/src/main/java/org/apache/accumulo/manager/FateServiceHandler.java
- server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java
- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/FateIT.java
> Add goal message to Fate

- assemble/bin/accumulo-util
Remove the jar loading utility, which is broken, from the accumulo-util
script. This utility was intended as a convenience to help users copy
jars to HDFS to be used with the VFS classloader. However, that utility
is in process of being separated from Accumulo's core, and so this tool
makes a lot of assumptions about the user's classloader configuration.
Furthermore, it's not really necessary for Accumulo to maintain a helper
tool for copying files for the user, as they can copy files on their
own, according to their specific needs.
This fixes #2440
> Remove load-jars-hdfs from bin/accumulo-util

- pom.xml
- server/tserver/src/test/java/org/apache/accumulo/tserver/log/SortedLogRecoveryTest.java
Closes #2489
The changes in this PR delete `SortedLogRecoveryTest.testMissingDefinition()`.
Based off the name of the test (testMissingDefinition) it seems that this test assumes that an exception will be thrown when there is no definition present. Instead, this information is just logged and does not cause an exception to be thrown:
```
[log.SortedLogRecovery] INFO : Tablet table<< is not defined in recovery logs [testlog]
```
Additionally, this test is incorrectly set up to handle the `fail()` statement which will just be caught in the catch block instead of making the test actually fail.
> Fix faulty test: `SortedLogRecoveryTest.testMissingDefinition`

- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/FateIT.java
- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/ServiceLockIT.java
- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/ZooMutatorIT.java
- test/src/main/java/org/apache/accumulo/test/zookeeper/ZooKeeperTestingServer.java
Modify ZooKeeperTestingServer to use Junit TemporaryFolder
for creating the ZooKeeper data directory instead of /tmp.
Related to #2474
> Modify ZooKeeperTestingServer to use Junit TemporaryFolder

- .github/workflows/maven.yaml
- core/src/main/java/org/apache/accumulo/core/client/security/tokens/AuthenticationToken.java
- core/src/main/java/org/apache/accumulo/core/client/security/tokens/PasswordToken.java
- core/src/test/java/org/apache/accumulo/core/client/security/tokens/PasswordTokenTest.java
- core/src/test/java/org/apache/accumulo/core/conf/ClientPropertyTest.java
- core/src/test/java/org/apache/accumulo/core/security/CredentialsTest.java
- pom.xml
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/compactor/src/test/java/org/apache/accumulo/compactor/CompactorTest.java
Ensure it is possible to successfully build using Java 17
These changes were tested with `mvn clean verify -Psunny`
* Add JDK 17 build to GitHub Actions
* Change format of `PasswordToken` serialization so it doesn't use GZip
from Hadoop's `WritableUtils.writeCompressedByteArray()`, which seems
to have changed format slightly between Java 11 and 17, resulting in
slightly different GZip header information. However, still support
reading the old version (added tests for these)
* Pass absurd jdk adds-opens options to ensure test code has access
parts of the JDK needed for mocking / junit testing
> Make build work on Java 17

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/cancel/CancelCompactions.java
Added the synchronized modifier to CancelCompactions.mutateZooKeeper which
could be called from concurrent delete table or cancel compaction operations
> Synchronize method shared between FaTE ops

- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionTestUtils.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_1_IT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_2_IT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_3_IT.java
Modified the methods in ExternalCompactionTestUtils that wait for
some condition to only sleep if the condition is not true. Modified
the test methods to use their own compaction queue for each test.
> More improvements to ExternalCompactionITs

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Fixes #2153 
This PR addresses the following:
- Creates a consistency check for `getFlushID` & `lastFlushID`
- Creates a consistency check for `getCompactionID` & `lastCompactID`
- Removes TODO relating to change
- Fixes a minor misspelling in the area of the original change
<s>In my changes I have created two try / catch blocks surrounding the getFlushID and getCompactionID assignments. One for each consistency check. I was not sure whether the NoNodeException should be thrown, logged or just printed. If anyone has any input regarding that, I would appreciate it.</s>
> Add consistency checks for lastFlushID and lastCompactID

- core/src/test/java/org/apache/accumulo/core/data/NamespaceIdTest.java
- core/src/test/java/org/apache/accumulo/core/data/TableIdTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/bcfile/CompressionTest.java
- core/src/test/java/org/apache/accumulo/core/util/InternerTest.java
- core/src/test/java/org/apache/accumulo/fate/zookeeper/ZooSessionTest.java
In #2427 I converted to the new syntax for timeouts but overlooked the fact that the default units have changed from milliseconds to seconds. This PR changes the timeouts back to their intended duration.
> Change timeouts to correct unit in accumulo-core module

- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterControl.java
Add two missing override annotations within the
MiniAccumuloClusterControl class.
> Add two missing override annotations

- core/src/test/java/org/apache/accumulo/core/classloader/ContextClassLoaderFactoryTest.java
- core/src/test/java/org/apache/accumulo/core/file/BloomFilterLayerLookupTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/GenerateSplitsTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/RFileTest.java
It looks like these tests were being ignored because the `@Tempdir` files were either `final` or `static` which appears to cause issues in certain cases.
When the `File` is used in a `@BeforeAll` method it cannot be final, and otherwise cannot be static. I reran these tests and they all pass and look to be running as intended.
> Fix usage of `@Tempdir` in accumulo-core module

- core/src/test/java/org/apache/accumulo/core/classloader/ContextClassLoaderFactoryTest.java
- core/src/test/java/org/apache/accumulo/core/file/BloomFilterLayerLookupTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/GenerateSplitsTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/RFileTest.java
It looks like the new JUnit 5 `@Tempdir` does not behave quite how I thought it did. In the tests that we use `@Tempdir`, we specify a parent directory where we want the new directory to be created as well as a name for the new directory. However after some testing it looks like these parameters don't make a difference in where the directory is actually created or what it is named.
Here is a quick example to illustrate this point:
```java
@TempDir
private static File tempdir = new File(System.getProperty("user.dir") + "/target", "FooBarClassname/");
@TempDir
private static File tempdir1 = new File(System.getProperty("user.dir") + "/target");
@TempDir
private static File tempdir2 = new File("");
@TempDir
private static File tempdir3;
@BeforeAll
public static void setup() throws Exception { …
```
> Simplify creation of `@Testdir`

- pom.xml
- shell/src/test/java/org/apache/accumulo/shell/commands/HistoryCommandTest.java
- test/src/main/java/org/apache/accumulo/harness/AccumuloClusterHarness.java
- test/src/main/java/org/apache/accumulo/test/compaction/UserCompactionStrategyIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BalanceInPresenceOfOfflineTableIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ClassLoaderIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CloneTestIT.java
- test/src/main/java/org/apache/accumulo/test/functional/PermissionsIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ScannerContextIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitIT.java
- test/src/main/java/org/apache/accumulo/test/functional/TableIT.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java
This PR adds a rule to ensure assume statements are statically imported and corrects the offending cases of that rule.
We have a rule to ensure assert statements are always statically imported. We don't have nearly as many assume statements but it would be nice if all of those were consistent as well.
> Add rule to always use static imports for assume

- .github/workflows/maven.yaml
- pom.xml
- server/base/src/main/java/org/apache/accumulo/server/zookeeper/DistributedWorkQueue.java
Bump Hadoop to latest bugfix release (3.3.0 to 3.3.1)
Bump ZooKeeper from 3.5 to 3.7
Recent conversations on the ZooKeeper mailing lists suggest that
community will soon mark 3.5 as EOL, and may also move to make 3.6 EOL
after 3.8 is released.
This change updates the default ZooKeeper used to build Accumulo to
3.7.0, but updates the GitHub Actions to test that 3.5 still works.
Additionally, since a new event type (PersistentWatchRemoved) was added
after 3.5, all unhandled event types in switch statements in
DistributedWorkQueue are collapsed into a single default case to ensure
it includes the new event type without directly referencing it, which
would cause a compile failure against 3.5.
> Bump ZooKeeper and Hadoop dependencies

- assemble/pom.xml
- assemble/src/main/assemblies/component.xml
- core/src/main/java/org/apache/accumulo/core/client/sample/AbstractHashSampler.java
- core/src/main/java/org/apache/accumulo/core/client/summary/SummarizerConfiguration.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/SortSkew.java
- core/src/main/java/org/apache/accumulo/core/summary/Gatherer.java
- pom.xml
- server/base/src/main/java/org/apache/accumulo/server/util/RemoveEntriesForMissingFiles.java
* Bump jackson and use newer jakarta artifact names instead of jakarta
classifiers
* Bump guava and use newer murmur3_32 method that fixes the previous
broken implementation
* Bump other deps: curator, micrometer, opentelemetry, jakartaee,
log4j2, jetty, hk2, jaxb, jersey, caffeine, auto-service, gson,
error_prone_annotations, commons-vfs2, checker-qual, jakarta.el,
hibernate-validator, jboss-logging, jline, snakeyaml
* Ensure the legacy junit version is explicitly managed, in case it gets
brought in transitively and conflicts with other dependencies
* Bump formatter-maven-plugin to recently released, and remove redundant
default configs
> Bump dependencies

- core/src/main/java/org/apache/accumulo/core/file/rfile/CreateEmpty.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/Compression.java
- core/src/main/java/org/apache/accumulo/core/spi/file/rfile/compression/Bzip2.java
- core/src/main/java/org/apache/accumulo/core/spi/file/rfile/compression/Gz.java
- core/src/main/java/org/apache/accumulo/core/spi/file/rfile/compression/Lz4.java
- core/src/main/java/org/apache/accumulo/core/spi/file/rfile/compression/Lzo.java
- core/src/main/java/org/apache/accumulo/core/spi/file/rfile/compression/NoCompression.java
- core/src/main/java/org/apache/accumulo/core/spi/file/rfile/compression/Snappy.java
- core/src/main/java/org/apache/accumulo/core/spi/file/rfile/compression/ZStandard.java
- pom.xml
This follows up from the work done in #2518 to remove the use of the
Java ServiceLoader for built-in known compression configs. Instead of
loading all compression configs through the ServiceLoader, this change
loads the known ones, and combines those with those discovered by the
ServiceLoader. This prevents issues during development where the
integration tests cannot be run inside an IDE, like Eclipse, due to the
auto-service annotation processor not having been executed in that
environment to make the implementing classes known to the ServiceLoader.
Now, they are always available for integration tests.
This also prevents the `@AutoService` annotation from being exposed in
SPI classes, although it's not clear that's necessarily a problem.
Additionally, this cleans up some of the previous …
> Improvements to loading of compression configs

- core/src/main/java/org/apache/accumulo/fate/Fate.java
A comment was added to Fate.java to indicate how the deferTime variable
is being used. It clarifies that the value is used in the manner of an
exit code for the particular if/else loop after the comment.
But it also makes clear that the value of deferTime is used as a wait
value later on within the ZooStore class.
No code was modified with this ticket.
> Fate op defer time is not used

- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/FateIT.java
Fix FateIT stability issues by ensuring the ZooKeeper client is sync'd
to the quorum state when verifying the transaction status.
This fixes #2474 and supersedes #2546
> Sync FateIT.getTxStatus

- minicluster/pom.xml
- minicluster/src/test/java/org/apache/accumulo/WithTestNames.java
- minicluster/src/test/java/org/apache/accumulo/cluster/standalone/StandaloneAccumuloClusterTest.java
- minicluster/src/test/java/org/apache/accumulo/cluster/standalone/StandaloneClusterControlTest.java
- minicluster/src/test/java/org/apache/accumulo/minicluster/MiniAccumuloClusterExistingZooKeepersTest.java
- minicluster/src/test/java/org/apache/accumulo/minicluster/MiniAccumuloClusterStartStopTest.java
- minicluster/src/test/java/org/apache/accumulo/minicluster/MiniAccumuloClusterTest.java
- minicluster/src/test/java/org/apache/accumulo/minicluster/WithTestNames.java
- minicluster/src/test/java/org/apache/accumulo/miniclusterImpl/CleanShutdownMacTest.java
- minicluster/src/test/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImplTest.java
- minicluster/src/test/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloConfigImplTest.java
Part of issue #2441 This PR contains changes for the conversion from JUnit4 to JUnit5 for the accumulo-minicluster module.
> Migrate Minicluster module to JUnit5

- core/src/main/java/org/apache/accumulo/core/util/HostAndPort.java
- core/src/test/java/org/apache/accumulo/core/util/HostAndPortTest.java
- pom.xml
The utility class, VerifyTabletAssignements, uses a TreeMap collection
to hold HostAndPort values. This requires the HostAndPort class to
implement the Comparable interface. This ticket adds the compareTo
method to HostAndPort. Given that the utility is seldom used, the
compareTo uses a simple compare on the Host portion and an integer
compare on the Port if required.
A HostAndPortTest class was added to verify changes.
This was first found when running ErrorProne. The ErrorProne check for
this condition had been disabled due to this issue. The check has now
been re-enabled in the ErrorProne configuration within the POM file.
> Add compareTo method to HostAndPort class

- core/src/main/java/org/apache/accumulo/core/util/HostAndPort.java
Based upon suggestion in code review, created a static privae final
Comparator field to be used within the HostAndPort compareTo method
rather than constructing a new comparator each time.
> Create static private final Comparator for HostAndPort

- core/src/test/java/org/apache/accumulo/core/util/HostAndPortTest.java
Update the test methods for the HostAndPort class.
testCompareTo() contained an unused variable, hostPortSame, that is now used.
testOrder() was updated to make use of the Streams API vs. individually adding each test IP line by line.
Thanks to @DomGarguilo for suggesting the changes.
> Update HostAndPortTest methods

- core/src/main/java/org/apache/accumulo/core/clientImpl/ScannerImpl.java
- test/src/main/java/org/apache/accumulo/test/functional/CleanUpIT.java
* Throw correct runtime exception when accessing a closed scanner
(should be an illegal state, not an illegal argument)
* Close the scanner before closing the client in CleanUpIT because
closing the scanner requires the client to not be closed in order to
execute cleanup tasks without blocking
> Fix CleanUpIT failure

- test/src/main/java/org/apache/accumulo/test/shell/MockShell.java
#2545 migrated the test module from JUnit4 to JUnit5. This class must have slipped through the cracks somehow.
> Migrate MockShell to junit5

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/WalRemovalOrderTest.java
Very trivial changes found in TabletServer while spelunking during a code review
* Replace unneeded copyClosedLogs method with built-in List.copyOf
* Replace ReferenceRemover with built-in Consumer
> Remove unneeded VisibleForTesting TabletServer stuff

- server/manager/pom.xml
- server/manager/src/test/java/org/apache/accumulo/manager/WithTestNames.java
- server/manager/src/test/java/org/apache/accumulo/manager/metrics/ReplicationMetricsTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/replication/DistributedWorkQueueWorkAssignerHelperTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/replication/ManagerReplicationCoordinatorTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/replication/SequentialWorkAssignerTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/replication/UnorderedWorkAssignerTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/replication/WorkMakerTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/tableOps/ShutdownTServerTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/tableOps/bulkVer2/PrepBulkImportTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/tableOps/compact/CompactionDriverTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/tableOps/tableImport/ImportTableTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/upgrade/AccumuloTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/upgrade/RootFilesUpgradeTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/upgrade/Upgrader9to10Test.java
This PR migrates the tests in server/manager module from JUnit4 to JUnit5.
All tests pass before and after these changes.
Part of #2441
> Migrate manager module to JUnit5

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
* Closes #2577 
* Add trace span and time measurement around consistency check
so we get an idea of how long metadata scans are taking
* Create new property tserver.health.check.interval to make it configurable
* Create new method watchCriticalFixedDelay() in ThreadPools
> Add trace and debug log to consistency check

- core/src/main/java/org/apache/accumulo/core/conf/ClientProperty.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/MetadataTime.java
- core/src/test/java/org/apache/accumulo/core/conf/ClientPropertyTest.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/MetadataTimeTest.java
- test/src/main/java/org/apache/accumulo/test/util/SerializationUtil.java
Hi! I'm working on a tool that identifies exceptions that could be thrown in given methods. It found some missing documentation and I'm submitting some to check if you find them useful.
I added a few `@throws` tags on methods that already had documentation. I also added tests when possible.
I'm assuming adding documentation to an existent javadoc could be more valuable than doing so on methods that don't have any.
In addition to missing javadoc, in `SerializationUtil` the exception was IAE when it should be a NPE. It's likely a problem originated in Commons Lang. Anyways, the class seems to be used only by `BatchWriterIterator`. So I understand if this is not the most useful change.  https://github.com/apache/accumulo/blob/69c31d48058e8fbf121ace69324f186ab56a4e70/test/src/main/java/org/apa …
> Add missing javadoc for exceptions thrown on invalid arguments

- server/base/src/main/java/org/apache/accumulo/server/ServerContext.java
- server/manager/src/main/java/org/apache/accumulo/manager/ManagerTime.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java
Reviewed the direct usage of ThreadPools.createGeneralScheduledExecutorService
and compared it to the usage of Timer and SimpleTimer in version 2.0.1. Found
and fixed a case in SessionManager where a new SheduledThreadPool was being created
in each SessionManager but a shared instance of SimpleTimer was being used in
the previous version.
> Use ServerContext.getScheduledExecutor where appropriate

- pom.xml
* Bypass buggy 3.0.0-M5 version; this fixes #2555
> Bump surefire and failsafe plugins to 3.0.0-M6

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftTransportPool.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/ClientConfConverterTest.java
- server/base/src/main/java/org/apache/accumulo/server/ServerContext.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
* Remove unnecessary memoization of the checker thread
* Inline the Closer Runnable type and make it a lambda
* Use primitive long for `ERROR_THRESHOLD`
* Reorder all the class members before all the inner-classes, and place
the fields above the methods to make it easier to navigate the class
* Make constructor private and use a static method to construct and
start the checker thread after construction, then return the instance
* Make ThriftTransportPool immutable by passing in the maximum age of
idle transports, rather than setting it after it is constructed; this
also changes the default to the general purpose RPC timeout config
value for all servers, rather than just the manager; clients continue
to use the hard-coded 3 seconds, just as before this change
> Minor cleanup of ThriftTransportPool

- core/src/main/java/org/apache/accumulo/core/trace/TraceUtil.java
Start a span, even if tracing is disabled on our end, if we find our
code inside a valid span. This implies that we're running inside a
user's span, started in user code.
This prevents us from needing to expose Accumulo internal
enabling/disabling utilities to client code. Users can enable
client-side tracing merely by wrapping our code with their own valid
spans.
> Start spans when inside a valid span

- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapred/AccumuloFileOutputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapred/AccumuloInputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapred/AccumuloRowInputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapred/MultiTableInputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapred/TokenFileIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/AccumuloFileOutputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/AccumuloInputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/AccumuloOutputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/AccumuloRowInputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/MultiTableInputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/TokenFileIT.java
- test/src/main/java/org/apache/accumulo/test/CloseScannerIT.java
- test/src/main/java/org/apache/accumulo/test/functional/AccumuloClientIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CredentialsIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ReadWriteIT.java
- test/src/main/java/org/apache/accumulo/test/functional/RecoveryWithEmptyRFileIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SslIT.java
* Remove conversions of client Properties into ClientInfo, only to
convert them back to Properties again; just use Properties directly
* Remove unnecessary ClientInfo parameter from test utilities where
client would suffice (client.properties() was also available)
* Replace uses of clusterHarness.getClientInfo().getProperties() with
just-as-good clusterHarness.getClientProps()
> Remove unnecessary uses of ClientInfo in ITs

- minicluster/src/main/java/org/apache/accumulo/minicluster/MiniAccumuloCluster.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
* Use a memoized Supplier to lazily load client properties and server
context and remove now unnecessary synchronization for these
* Make a protective copy of the client properties when returning in the
public API method, getClientProperties(), and update javadoc
* Make fields final where possible
* Relocate constructors to just under the fields, prior to other
methods, for easier class navigation
This fixes #2619
> MiniAccumuloCluster improvements

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftTransportPool.java
- core/src/main/java/org/apache/accumulo/core/conf/ClientProperty.java
- server/base/src/main/java/org/apache/accumulo/server/ServerContext.java
* Create new client-side property for ThriftTransportPool's idle
transport timeout. This allows the default value for clients to be
configured independently of the default value for servers.
* Set default value for clients back to 3 seconds, like it was
hard-coded prior to the changes in #2612
* Fix debug logging of the transport pool idle time value
This fixes #2626
> Fix ThriftTransportPool client idle timeout default

- server/base/src/main/java/org/apache/accumulo/server/util/ChangeSecret.java
- server/manager/src/test/resources/conf/accumulo-site.xml
There are inconsistencies in how ChangeSecret should be run, as well as
exceptions thrown when attempting to execute ChangeSecret.
In two locations, instructions for executing ChangeSecret indicate
./bin/accumulo org.apache.accumulo.server.util.ChangeSecret
But within accumulo-site.xml, instructions indicate
./bin/accumulo org.apache.accumulo.server.util.ChangeSecret [oldpasswd] [newpasswd]
Neither one of the two methods work properly.
Running with no parameters throws a NullPointerException. Running with
the indicated parameters presents a usage message with an error
message provided. Additionally, the usage message makes no mention of
the old and new password parameters.
This PR updates site.xml to match the instructions within the rest of
the code, i.e., execute the command with no …
> Update ChangeSecret to work as documentation states

- core/src/main/java/org/apache/accumulo/core/client/IsolatedScanner.java
- core/src/test/java/org/apache/accumulo/core/client/rfile/RFileClientTest.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapred/AccumuloOutputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapred/TokenFileIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/AccumuloOutputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/TokenFileIT.java
- iterator-test-harness/src/main/java/org/apache/accumulo/iteratortest/IteratorTestBase.java
- test/src/main/java/org/apache/accumulo/test/IsolationAndDeepCopyIT.java
- test/src/main/java/org/apache/accumulo/test/SplitRecoveryIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BigRootTabletIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ClassLoaderIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CombinerIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CreateAndUseIT.java
- test/src/main/java/org/apache/accumulo/test/functional/DeleteEverythingIT.java
- test/src/main/java/org/apache/accumulo/test/functional/DeleteRowsIT.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorIT.java
- test/src/main/java/org/apache/accumulo/test/functional/KerberosIT.java
- test/src/main/java/org/apache/accumulo/test/functional/MetadataIT.java
- test/src/main/java/org/apache/accumulo/test/functional/RowDeleteIT.java
- test/src/main/java/org/apache/accumulo/test/functional/TableIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ZookeeperRestartIT.java
- test/src/main/java/org/apache/accumulo/test/mapred/AccumuloOutputFormatIT.java
- test/src/main/java/org/apache/accumulo/test/mapred/TokenFileIT.java
- test/src/main/java/org/apache/accumulo/test/mapreduce/AccumuloOutputFormatIT.java
- test/src/main/java/org/apache/accumulo/test/mapreduce/TokenFileIT.java
I was looking through places where the use of `Scanner.Iterator` might be improved by using the new `Scanner.stream` method and found a few patterns to replace that seemed worth-while. 
* In a lot of places, we create an interator, assert that the iterator `hasNext`, get the next entry, compare that entry to what we expect it to be, then assert that `hasNext` is false. All this to make sure there is just one entry. To simplify I changed these places to `.stream().collect(onlyElement())` and then perform the `assertEquals` on the single returned value.
* Convert `Iterators.size(s.iterator()) == 0` -> `s.stream().findAny().isEmpty()`
* Convert `Iterators.size(s.iterator()) > 0` -> `s.stream().findAny().isPresent()`
I also wanted to see if anyone had an opinion on which of the following …
> Replace iterator usage

- server/base/src/main/java/org/apache/accumulo/server/security/AuditedSecurityOperation.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- test/src/main/java/org/apache/accumulo/test/AuditMessageIT.java
Updated three instances where the number of format arguments did not
match number of arguments.
In CompactionCoordinator the compactorAddress was a third argument for
a statement containing only two format arguments. The compactorAddress
was dropped as it did not seem to be necessary.
In AuditedSecurityOperation there were two occasions of mismatched
formats and arguments. In both cases, an additional format argument was
added to allow both the tableName and tableId to be displayed in the
audit log.
> Resolve unused format arguments

- core/src/main/java/org/apache/accumulo/core/conf/DefaultConfiguration.java
- core/src/main/java/org/apache/accumulo/core/conf/SiteConfiguration.java
- core/src/test/java/org/apache/accumulo/core/conf/SiteConfigurationTest.java
- core/src/test/java/org/apache/accumulo/core/spi/balancer/HostRegexTableLoadBalancerReconfigurationTest.java
- core/src/test/java/org/apache/accumulo/core/spi/balancer/HostRegexTableLoadBalancerTest.java
- server/base/src/main/java/org/apache/accumulo/server/ServerContext.java
- server/base/src/main/java/org/apache/accumulo/server/conf/ServerConfigurationFactory.java
- server/base/src/test/java/org/apache/accumulo/server/ServerContextTest.java
- server/base/src/test/java/org/apache/accumulo/server/conf/ServerConfigurationFactoryTest.java
- server/base/src/test/java/org/apache/accumulo/server/master/balancer/BaseHostRegexTableLoadBalancerTest.java
- server/base/src/test/java/org/apache/accumulo/server/security/SystemCredentialsTest.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/gc/src/test/java/org/apache/accumulo/gc/SimpleGarbageCollectorTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader9to10.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
* Remove the need to synchronize on reads for lazily initialized
singleton resources, particularly in the configuration and context
utilities, using Suppliers.memoize
* Apply to DefaultConfiguration.getInstance() to avoid unnecessary
object creation whenever that is called
* Make all ServerContext fields final, and use memoize to lazily load
anything that was previously checking if it was set in a synchronized
getter method
* Use computeIfAbsent in ServerConfigurationFactory, and make its caches
of configuration objects non-static, so they only live as long as the
ServerContext that created it lives; this, along with using
ConcurrentHashMaps, dramatically simplifies this code
* Reduce ServerContext reliance on ServerConfigurationFactory when it
already has the information (notably, it has …
> Use memoized suppliers to lazy load resources

- core/src/main/java/org/apache/accumulo/core/iteratorsImpl/system/SourceSwitchingIterator.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletHostingServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ThriftScanClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/scan/LookupTask.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/scan/NextBatchTask.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/scan/ScanTask.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Scanner.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/TabletBase.java
This commit introduces TabletBase, a base class for Tablets, and TabletHostingServer,
an interface for server components that host Tablets. These changes will be used by
the ScanServer feature that is in the works.
Related to #2411
> Add base objects for Tablet and TabletServer for the upcoming ScanServer feature

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/bulkImport.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/compactions.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/ec.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/functions.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/gc.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/global.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/listType.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/manager.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/navbar.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/overview.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/problems.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/replication.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/scans.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/server.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/show.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/summary.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/table.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/tservers.js
* Add the JS "use strict"; directive to all JS in Monitor
* This will execute scripts in "strict mode" and prevent use of undeclared variables
> Add js strict directive to Monitor javascript

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/replication.js
Related to issue #2653
---
Based on discussion in PR #2666, the default message in the Replication page in the Monitor was updated to inform the user that replication is disabled and the table is offline by default.
> Update Replication Table offline message in Monitor

- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tservers/TabletServerResource.java
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/tservers.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/tservers.ftl
A bug was found in the feature added in #2663 where the caption explaining the highlighted rows would be visible in certain scenarios when there were no highlighted rows in the table. The caption is only meant to be visible when there are highlighted rows. The changes in this PR make it so that the caption is hidden by default and only shown when a row is actually highlighted.
Additionally, I renamed the variable representing the tservers table to make it more clear.
> Bug fix for caption in tservers table in monitor

- start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloVFSClassLoader.java
- start/src/test/java/org/apache/accumulo/start/test/AccumuloDFSBase.java
Add VFS type mapping for the new jar mime type added in newer versions
of Java 17, application/java-archive, to ensure it is associated with
the "jar" scheme in VFS. This ensures VFS loads jars correctly when run
on a newer version of Java.
This fixes #2682
See related: https://issues.apache.org/jira/browse/VFS-819
> Add VFS type mapping for new jar mime type

- server/base/src/main/java/org/apache/accumulo/server/metadata/RootGcCandidates.java
- removes multi-line json output from logs
With this change, the log looks like:
```
2022-05-06T13:53:04,574 [metadata.ServerAmpleImpl] DEBUG: Root GC candidates before change : {"version":1,"candidates":{}}
2022-05-06T13:53:04,576 [metadata.ServerAmpleImpl] DEBUG: Root GC candidates after change  : {"version":1,"candidates":{"hdfs://localhost:8020/accumulo/tables/+r/root_tablet":["00000_00000.rf","F0000000.rf","F0000004.rf"]}}
```
Before, the logs looked like:
```
2022-05-05T22:02:10,056 [metadata.ServerAmpleImpl] DEBUG: Root GC candidates before change : {
"version": 1,
"candidates": {}
}
2022-05-05T22:02:10,056 [metadata.ServerAmpleImpl] DEBUG: Root GC candidates after change  : {
"version": 1,
"candidates": {
"hdfs://localhost:8020/accumulo/tables/+r/root_tablet": [
"A00000ax.rf", …
```
> Remove json prettyPrint from RootGcCandidates

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/scans.js
On the `Active Scans` page in the Monitor, the console complains about `scansList` not being defined.
This update was made using `compactions.js` as a reference.
> Add declaration for scansList prior to usage

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/tservers.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/tservers.ftl
This PR:
* Converts `deadtservers` and `badtservers` to DataTables
* Add a title and caption to the online tservers table
* Conform to eslint formatting
Here is a screenshot of the current `/tservers` page:
> Convert deadTServers and badTServers tables to DataTables

- minicluster/src/test/java/org/apache/accumulo/minicluster/MiniAccumuloClusterTest.java
I noticed that this test failed after merging in #2685. I'm fairly certain the test failure is unrelated since #2685 only touched JavaScript and FreeMarker files.
Commit: https://github.com/apache/accumulo/commit/19e420da392c3905dbe9f3b020a4a60d03615d55
CI run: https://github.com/apache/accumulo/runs/6393887792?check_suite_focus=true
I'm not too sure why this test failed and have been unable to reproduce the failure but while investigating, I made various changes that seem like improvements to me:
* Use unique names for tables (this may have caused the error if it collided with a table name from another test)
* Refactor into several new constants and variables
* Add resources to try-with-resources blocks
* Use NewTableConfiguration to create tables
> Improvements to MiniAccumuloClusterTest

- server/base/src/main/java/org/apache/accumulo/server/conf/store/impl/ZooPropStore.java
The method was taking a ZooReaderWriter - but is only doing a read. Narrow signature to match usage.
> Narrow static util method, writer not needed, use ZooReader

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/functions.js
Closes #2659 
---
Added console logs for REST calls that indicate:
- What was called
- JSON data string returned from call
REST calls used on the Monitor Overview page use `console.debug()` to avoid clogging up the console. These log messages are filtered out by default in some browsers but can be shown if toggled on. Otherwise, the rest of the REST calls use `console.info()`.
> Add front-end console logging in Monitor

- core/src/main/java/org/apache/accumulo/core/rpc/TTimeoutTransport.java
When closing a socket as the result of an exception, also keep any
exception from the attempt to close it, appended to the original
exception as a suppressed exception
> Keep new exception when closing socket

- server/monitor/pom.xml
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/bulkImport.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/compactions.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/ec.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/gc.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/listType.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/manager.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/navbar.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/overview.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/problems.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/replication.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/scans.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/server.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/show.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/summary.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/table.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/tservers.js
- server/monitor/src/main/scripts/format-js.sh
As part of the formatting profile during the Maven build, attempt to
format JavaScript files in the monitor if the `npx` command is available
to run js-beautify
Include formatting changes to the monitor's JavaScript files
This fixes #2713
> Configure opportunistic formatting of JavaScript

- server/base/src/main/java/org/apache/accumulo/server/conf/util/ConfigPropertyUpgrader.java
- server/base/src/main/java/org/apache/accumulo/server/util/ChangeSecret.java
As follow-on to #2651, I noticed that the help no longer worked:
`bin/accumulo org.apache.accumulo.server.util.ChangeSecret --help`
This change ensures that the ServerUtilOpts is parsed in ChangeSecret,
so that if the config file name is specified, the ServerContext can
still be constructed correctly, and so the help feature works correctly
to view the command's usage.
Also, remove an unnecessary subclass of ServerUtilOpts that didn't add
any new parameters, and use the ServerUtilOpts class directly in
ConfigPropertyUpgrader.
> Ensure ServerUtilOpts is parsed

- test/src/main/java/org/apache/accumulo/test/conf/store/PropStoreZooKeeperIT.java
- test/src/main/java/org/apache/accumulo/test/conf/store/ZooBasedConfigIT.java
- test/src/main/java/org/apache/accumulo/test/conf/util/ConfigTransformerIT.java
- test/src/main/java/org/apache/accumulo/test/upgrade/ConfigPropertyUpgraderIT.java
- test/src/main/java/org/apache/accumulo/test/zookeeper/ZooKeeperTestingServer.java
Fix ZooKeeper-related ITs broken by #2721, which added authentication to
configuration nodes stored in ZooKeeper. This adds the auth info to the
ZooKeeper object used by the ITs, matching the ZooKeeperTestingServer's
SECRET.
> Fix recently broken ZooKeeper ITs

- server/native/src/main/c++/nativeMap/Field.h
- server/native/src/main/c++/nativeMap/SubKey.h
The C++ standard requires that memory allocated via operator new[] be
freed via operator delete[], but we were freeing it via operator
delete() in a few places.  This was UB, and it causing warnings on GCC
12 with -Wmismatched-new-delete.
Fixes #2719 .
> Match new[] with delete[]

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
* Merging minor compactions can lead to bad situations where a Tablet
can't flush. They have been removed in version 2.1.
> Disable Merging MINC by default

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionTestUtils.java
- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/FateIT.java
- Added property with new name
- Marked old property as Deprecated
- Updated usages
Fixes #2618
>  Rename property GENERAL_SIMPLETIMER_THREADPOOL_SIZE

- core/src/main/java/org/apache/accumulo/core/spi/fs/DelegatingChooser.java
- core/src/test/java/org/apache/accumulo/core/spi/fs/DelegatingChooserTest.java
- core/src/test/java/org/apache/accumulo/core/spi/fs/PerTableVolumeChooserTest.java
- server/base/src/main/java/org/apache/accumulo/server/fs/PerTableVolumeChooser.java
- test/src/main/java/org/apache/accumulo/test/VolumeChooserIT.java
Addresses #2699 
This PR addresses the following:
- Removal of some of the TODOs throughout the code. 
- Changes the name of `PerTableVolumeChooser` to `DelegatingChooser` where needed.
- Renames `PerTableVolumeChooser.java` to `DelegatingChooser.java`
- Fixes a grammatical error addressed in original issue
> Remove TODOs and rename PerTableVolumeChooser

- assemble/conf/accumulo-env.sh
Update the default conf/accumulo-env.sh script to support overriding
some of the default java options it sets by placing user-provided
options specified by the `ACCUMULO_JAVA_OPTS` environment variable after
any options set in the script (because Java will likely take the last
value set on the command-line).
This fixes #2744
> Allow overriding default env without editing conf

- core/src/main/java/org/apache/accumulo/core/conf/AccumuloConfiguration.java
- core/src/test/java/org/apache/accumulo/core/conf/AccumuloConfigurationTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Resolve a sequence of deprecation changes, instead of just a single
deprecation with a replacement (for example, if property A is deprecated
and replaced with property B, then B is deprecated and replaced with C,
we'd resolve like:
```java
resolve(C, B, A);
```
rather than:
```java
resolve(C, resolve(B, A));
```
Also:
* To avoid errors, ensure that the current property isn't deprecated
* Check that the deprecated properties are actually deprecated
* Add a unit test case
* Update the javadoc
> Improve deprecated property resolution

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/functions.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/log.ftl
Fixes #2731
There was an issue where the refresh() function was being called before the POST request to clear the table was completed so when clicking the clear logs button, the logs would not be cleared.
This PR adds a parameter to functions.clearLogs() so that we can refresh via a callback which will be called only after the POST request completes to clear the page.
> Fix async bug when clearing logs in monitor

- server/base/src/main/java/org/apache/accumulo/server/conf/ServerConfigurationFactory.java
- test/src/main/java/org/apache/accumulo/test/conf/PropStoreConfigIT.java
This PR is in response to comments on https://github.com/apache/accumulo/pull/2769 - it adds the delete watcher to ServerConfigurationFactory so that configurations are removed from the local copy on prop store deletes.  
The synchronization will be handled in a separate PR.
> Add delete event watcher to ServerConfigurationFactory

- core/src/main/java/org/apache/accumulo/core/security/Authorizations.java
It looks like all the serialization done for `Authorizations` is done with custom methods that we have created over the years.  I am not sure why we need the interface on the class anymore.
> Make auths classes in Authorizations

- server/base/src/main/java/org/apache/accumulo/server/ServerContext.java
- server/base/src/main/java/org/apache/accumulo/server/conf/ServerConfigurationFactory.java
- server/base/src/main/java/org/apache/accumulo/server/conf/store/impl/ZooPropStore.java
- server/base/src/test/java/org/apache/accumulo/server/conf/ServerConfigurationFactoryTest.java
- test/src/main/java/org/apache/accumulo/test/conf/util/ConfigTransformerIT.java
- test/src/main/java/org/apache/accumulo/test/conf/util/TransformTokenIT.java
Lazy load the PropStore to reduce the potential for creating multiple prop store instances.
Also addresses a duplicate server configuration being create in ServerConfigurationFactory - uses the instance from the context.
> Address #2635 by lazy loading prop store in ServerContext

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/table.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/table.ftl
This PR converts the table in table.js to a DataTable.
The table should behave the same except for one small change:
Current table:
Table with the changes from this PR:
I broke the scans and compactions columns up into running and queued instead of having the queued compactions in the same column within the parenthesis.
> Convert table.js to DataTables

- core/src/main/java/org/apache/accumulo/core/summary/Gatherer.java
- core/src/main/java/org/apache/accumulo/core/util/CompletableFutureUtil.java
- core/src/test/java/org/apache/accumulo/core/util/CompletableFutureUtilTest.java
Attempt to fix #2696. This replaces the complicated mutation retry logic in `Gatherer` with a more structured/algebraic approach. 
This new approach is recursive. Making the recursive call asynchronously should prevent a stack overflow (it does in the tests that I've run), since the task is submitted to the common ForkJoinPool rather than being called directly. This probably imposes a performance penalty, but I don't know how that compares to the cost of the I/O in this codepath.
> Improve use of Futures in Gatherer

- minicluster/src/test/java/org/apache/accumulo/minicluster/MiniAccumuloClusterClasspathTest.java
- minicluster/src/test/java/org/apache/accumulo/minicluster/MiniAccumuloClusterTest.java
MiniAccumuloClusterTest.testPerTableClasspath is intermittently failing with
a MutationsRejectedException when the BatchWriter is closed because the TabletServer
is not seeing property changes made in the test right before the BatchWriter is
created. This change introduces a small sleep in an attempt to allow the
TabletServer to react to the configuration changes before the BatchWriter is used
in the test thread.
> Wait for server process to notice property changes in MiniAccumuloClusterTest

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/replication.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/replication.ftl
The PR converts the table in replication.js to a DataTable. This table is present at '/replication' in the monitor.
Here is the table before and after these changes. I hard coded example data to be returned from the rest endpoint for these examples:
before:
after:
> Convert table in replication.js to DataTable

- server/base/src/main/java/org/apache/accumulo/server/ServerContext.java
- server/base/src/main/java/org/apache/accumulo/server/tables/TableManager.java
- server/base/src/main/java/org/apache/accumulo/server/util/PropUtil.java
- server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/create/PopulateZookeeper.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/namespace/create/PopulateZookeeperWithNamespace.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/ImportPopulateZookeeper.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader9to10.java
- test/src/main/java/org/apache/accumulo/test/ZooKeeperPropertiesIT.java
The PropUtil class does not require any state - this modifies the class to only contain static methods and to prevent instantiation.
> Modify PropUtil to a true utility class with static methods

- assemble/bin/accumulo-cluster
I was playing around with the `accumulo-cluster create-config` command and accidentally blew my config away.  Thinking it would be best if this command only created the file if didn't exists.
> checks if file already exists in accumulo-cluster create-config

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/util/format/HexFormatter.java
- core/src/main/java/org/apache/accumulo/core/util/interpret/DefaultScanInterpreter.java
- core/src/main/java/org/apache/accumulo/core/util/interpret/HexScanInterpreter.java
- core/src/main/java/org/apache/accumulo/core/util/interpret/ScanInterpreter.java
- core/src/test/java/org/apache/accumulo/core/util/format/HexFormatterTest.java
- shell/src/main/java/org/apache/accumulo/shell/Shell.java
- shell/src/main/java/org/apache/accumulo/shell/commands/DeleteManyCommand.java
- shell/src/main/java/org/apache/accumulo/shell/commands/FormatterCommand.java
- shell/src/main/java/org/apache/accumulo/shell/commands/GrepCommand.java
- shell/src/main/java/org/apache/accumulo/shell/commands/InterpreterCommand.java
- shell/src/main/java/org/apache/accumulo/shell/commands/MaxRowCommand.java
- shell/src/main/java/org/apache/accumulo/shell/commands/ScanCommand.java
I just did a quick commit here to mark the API as deprecated as there's already some comments that print for the shell output if used.
Do we want to specify when it will be removed? I would think targeting 2.2 for removal would be good. Is there anything else to do here?
> Mark ScanInterpreter related API as deprecated (#2787)

- server/manager/src/main/java/org/apache/accumulo/manager/metrics/fate/FateMetrics.java
- Change FateMetrics to use ReadOnlyStore (same as in UpgradeCoordinator)
- minor lamdba ide suggested replacement
> Modify FateMetrics to enforce ReadOnlyStore required for ZooKeeper

- core/src/main/java/org/apache/accumulo/core/crypto/streams/NoFlushOutputStream.java
Writes to the DFSLogger output stream are already synchronized
by the DFSLogger.write method. Looking at the other output streams
in the write stack (DataOutputStream, FSDataOutputStream,
BlockedOutputStream, etc.) their write methods are not synchronized.
Related to #2165
> Remove synchronized modifier from NoFlushOutputStream.write

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
This change splits the prior memoized check into two, one that
is less expensive and is checked more often and one that is more
expensive, likely to change less often and is checked less often
Closes #1610
> Modify CompactionCheck logic to run expensive checks less often

- pom.xml
Noticed there is a more recent version of sec-bugs.  qa checks pass without any changes needed.
> bump sec-bugs version

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/rpc/SslConnectionParams.java
- core/src/main/java/org/apache/accumulo/core/rpc/ThriftUtil.java
Working with user testing SSL setup with Accumulo 2.1.0 and seeing general slowness.  I modified SslIT to include the following:
```
@Override
public void configure(MiniAccumuloConfigImpl cfg, Configuration hadoopCoreSite) {
+    System.setProperty("javax.net.debug", "ssl:handshake");
+    Map<String,String> sys = new HashMap<>();
+    sys.put("javax.net.debug", "ssl:handshake");
+    cfg.setSystemProperties(sys);
+    cfg.setProperty(Property.RPC_SSL_ENABLED_PROTOCOLS, "TLSv1.3");
+    cfg.setProperty(Property.RPC_SSL_CLIENT_PROTOCOL, "TLSv1.3");
+    cfg.setProperty(Property.MONITOR_SSL_INCLUDE_PROTOCOLS, "TLSv1.3");
+    cfg.setClientProperty(Property.RPC_SSL_CLIENT_PROTOCOL.getKey(), "TLSv1.3");
super.configure(cfg, hadoopCoreSite);
configureForSsl(cfg, …
```
> Cache SSLContext

- server/monitor/src/test/java/org/apache/accumulo/monitor/it/WebViewsIT.java
In #2822, the trace tables were removed from the monitor. This test should have been removed as part of that PR.
> Remove test for trace table

- core/src/main/java/org/apache/accumulo/core/util/FastFormat.java
- core/src/main/java/org/apache/accumulo/fate/AdminUtil.java
- core/src/main/java/org/apache/accumulo/fate/Fate.java
- core/src/main/java/org/apache/accumulo/fate/FateTxId.java
- core/src/main/java/org/apache/accumulo/fate/ZooStore.java
- core/src/test/java/org/apache/accumulo/core/util/FastFormatTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/FateServiceHandler.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/Utils.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/CompactRange.java
- shell/src/main/java/org/apache/accumulo/shell/commands/FateCommand.java
- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/FateIT.java
* Replace String.format() with new method in FastFormat that should be faster
* Modify FateTxId.formatTid to use new method that should be equivalent
* Replace uses of Long.toHexString in Utils with FateTxId.formatTid to
improve logging
* Add new tests to FastFormatTest
* Supports #2495
> Create new method in FastFormat for FATE

- core/src/main/java/org/apache/accumulo/core/client/MutationsRejectedException.java
- core/src/main/java/org/apache/accumulo/core/client/TimedOutException.java
* Change private interface types to concrete classes to stop Java 18
warnings about non-serializable types
* Supports #2776
> Fix serializable warnings

- core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/CompressionAlgorithm.java
> Don't log full stack trace by default when unable to load compression codec

- core/src/main/java/org/apache/accumulo/fate/ZooStore.java
PR #2829 changed the Fate ZooKeeper path for storing and retrieving
the Fate properties for a specific Fate transaction. But, one was
missed.
Closes #2837
> Fix issue with ZooStore properties not being read due to name change

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientConfConverter.java
- core/src/main/java/org/apache/accumulo/core/conf/AccumuloConfiguration.java
- core/src/main/java/org/apache/accumulo/core/conf/ConfigurationCopy.java
- core/src/main/java/org/apache/accumulo/core/conf/DefaultConfiguration.java
- core/src/main/java/org/apache/accumulo/core/conf/SiteConfiguration.java
- core/src/test/java/org/apache/accumulo/core/conf/AccumuloConfigurationTest.java
- server/base/src/main/java/org/apache/accumulo/server/conf/ZooBasedConfiguration.java
- server/base/src/test/java/org/apache/accumulo/server/conf/ServerConfigurationFactoryTest.java
The getProperties method which takes a filter is inefficient when
you know that you want to get all properties or you know the names
of the properties. Provide a mechanism to get the properties w/out
using a filter
> Provide getProperties method on Configuration that does not filter

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientConfConverter.java
- core/src/main/java/org/apache/accumulo/core/conf/SiteConfiguration.java
- server/base/src/main/java/org/apache/accumulo/server/conf/ZooBasedConfiguration.java
#2834  added a getProperties method to AccumuloConfiguration.
Most of the implementations handled the case where the varargs
parameter is null or empty. This commit adds the same
logic to the classes where it was missing
Related to #2834
> Add missing logic to Configuration.getProperties

- core/src/main/java/org/apache/accumulo/core/iterators/user/RegExFilter.java
- core/src/main/java/org/apache/accumulo/core/metadata/MetadataLocationObtainer.java
- core/src/main/java/org/apache/accumulo/core/util/LocalityGroupUtil.java
- core/src/main/java/org/apache/accumulo/fate/ZooStore.java
- core/src/test/java/org/apache/accumulo/core/client/ClientPropertiesTest.java
- core/src/test/java/org/apache/accumulo/core/spi/balancer/TableLoadBalancerTest.java
- core/src/test/java/org/apache/accumulo/core/spi/fs/SpaceAwareVolumeChooserTest.java
- core/src/test/java/org/apache/accumulo/core/util/PreAllocatedArrayTest.java
- core/src/test/java/org/apache/accumulo/fate/util/RetryTest.java
Fix spotbugs errors identified by temporarily setting the spotbugs effort maxRank at 17 (normally 16).  In core, there are 35 errors identified - this PR address 17 of them.
<details>
<summary>Fixed errors - Click to expand!</summary>
- [ERROR] Medium: Hard coded reference to an absolute pathname in org.apache.accumulo.core.client.ClientPropertiesTest.testBasic() [org.apache.accumulo.core.client.ClientPropertiesTest] At ClientPropertiesTest.java:[line 45] DMI_HARDCODED_ABSOLUTE_FILENAME
- [ERROR] Medium: Return value of java.util.regex.Pattern.matcher(CharSequence) ignored, but method has no side effect [org.apache.accumulo.core.iterators.user.RegExFilter, org.apache.accumulo.core.iterators.user.RegExFilter, org.apache.accumulo.core.iterators.user.RegExFilter, …
> Fix additional spotbugs errors in core

- core/src/main/java/org/apache/accumulo/core/conf/AccumuloConfiguration.java
Prior commit attempted to create a Property by enum value using the key.
Fixed this to call Property.getPropertyByKey instead.
> Fix AccumuloConfiguration.get(String) to get Property by key

- core/src/main/java/org/apache/accumulo/core/client/admin/CloneConfiguration.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/CloneConfigurationImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- server/manager/src/main/java/org/apache/accumulo/manager/FateServiceHandler.java
- test/src/main/java/org/apache/accumulo/test/functional/CloneTestIT.java
* Add new convenience method for empty object and use in CloneTestIT
* Create private methods for sharing in TableOperationsImpl
* Clean up on the CloneConfiguration interface
> Add empty method to CloneConfiguration API

- shell/pom.xml
- shell/src/main/java/org/apache/accumulo/shell/Shell.java
These changes should not modify the behavior.  (Noticed the class had a lot of warning while working something else)  
This fixes all but two - wanting to autoclose the terminal printWriter (line 986 - wants a try-with-resources) and an empty if (line 786) but changing the condition removing that seemed make the code more confusing.
> fix code style warnings in Shell code

- start/src/main/java/org/apache/accumulo/start/Main.java
Async Logging may not flush the exception to the file before the
process terminates. Print the error to stderr as well.
Closes #2885
> Print exceptions that cause the server process to exit to stderr

- assemble/bin/accumulo-cluster
get_ip returns a single ip address for the host, but could return
the incorrect one in the case where a host has multiple interfaces.
This commit modifies the logic to use hostname -I instead and checks
to see if the host we are looking for is in the list of returned IPs
Closes #2884
> Replace accumulo-cluster get_ip function with hostname -I

- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
- server/base/src/main/java/org/apache/accumulo/server/util/ChangeSecret.java
- server/base/src/main/java/org/apache/accumulo/server/util/DeleteZooInstance.java
- server/base/src/main/java/org/apache/accumulo/server/util/DumpZookeeper.java
- server/base/src/main/java/org/apache/accumulo/server/util/RestoreZookeeper.java
- server/base/src/main/java/org/apache/accumulo/server/util/TabletServerLocks.java
- server/base/src/main/java/org/apache/accumulo/server/util/VerifyTabletAssignments.java
Remove main methods from utilities now that they are exposed through
KeywordExecutable and the accumulo command. Also sort the commands in
the help section alphabetically.
> Cleanup Accumulo Admin utilities

- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
Logs when instance id is written to hdfs
- Add checking for successful file instance id creation
- Other checkstyle fixes
Supplements changes made in https://github.com/apache/accumulo/pull/2873
> Add log messages to initialization, checkstyle fixes

- core/src/main/java/org/apache/accumulo/core/spi/crypto/AESCryptoService.java
- core/src/test/java/org/apache/accumulo/core/crypto/CryptoTest.java
* Reduce Cipher.getInstance calls to once per file vs once per block
* Move wrap cipher to ThreadLocal thread
* Add flush at the end of createCryptoParameters() before returning the byte array
* Add logger and init checks
> Improvements to AESCryptoService

- assemble/bin/accumulo-cluster
- core/src/main/java/org/apache/accumulo/core/conf/cluster/ClusterConfigParser.java
- core/src/test/java/org/apache/accumulo/core/conf/cluster/ClusterConfigParserTest.java
- core/src/test/resources/org/apache/accumulo/core/conf/cluster/cluster-with-optional-services.yaml
Added tservers_per_host and sservers_per_host to cluster.yaml file. This file is parsed
and transformed into environment variables that are read in by the accumulo-cluster script.
This change adds the environment variables NUM_TSERVERS and NUM_SSERVERS to the environment
with a default value of 1 if not specified in cluster.yaml and in a way that the value is
in cluster.yaml is overridden if the environment variable already exists in the environment
> Added servers per host to cluster.yaml

- core/src/main/java/org/apache/accumulo/core/util/Merge.java
I went with `toPrintableString` since that format is pretty readable, but if some other encoding is preferred for some reason, I don't have a preference. Just want to avoid getting vt100 control characters that reconfigure my terminal.
> convert text to printable string before logging in merge tablets

- core/src/main/java/org/apache/accumulo/core/metadata/TabletLocationState.java
To ensure that the location is correctly serialized in this exception,
do not mark it transient, but convert it to a byte array, since Text is
not Serializable.
This addresses the warning in #2776 without assuming the exception will
never be serialized, which was made in #2897. Instead, this change
avoids errors if it ever were to be serialized and the location were
silently changed to a null value because the field was transient.
> Serialize location in BadLocationStateException

- pom.xml
Update the error prone version to latest and use pom variable for both errorprone core and annotations.
There are no code changes with the PR.
> Update errorprone version

- core/src/main/java/org/apache/accumulo/core/client/BatchWriter.java
Comment refers to an upcoming fix in [ACCUMULO-2990](https://issues.apache.org/jira/browse/ACCUMULO-2990) but that issue was closed as could not reproduce.
> Remove stale Javadoc comment that references closed Jira issue

- test/src/main/java/org/apache/accumulo/test/functional/KerberosRenewalIT.java
Recently, KerberosRenewalIT.testReadAndWriteThroughTicketLifetime had failed once on [a jenkins build](https://ci-builds.apache.org/job/Accumulo/job/main/org.apache.accumulo$accumulo-test/388/testReport/junit/org.apache.accumulo.test.functional/KerberosRenewalIT/testReadAndWriteThroughTicketLifetime/). I couldn't find record of this test failing in the past but I figure its an easy enough change to ensure it won't fail again.
Stacktrace:
<details>
```
org.apache.accumulo.core.client.TableExistsException: Table testReadAndWriteThroughTicketLifetime_table exists
at org.apache.accumulo.core.clientImpl.TableOperationsImpl.doFateOperation(TableOperationsImpl.java:391)
at org.apache.accumulo.core.clientImpl.TableOperationsImpl.doFateOperation(TableOperationsImpl.java:359)
at …
```
> Attempt to make KerberosRenewalIT more stable

- core/src/main/java/org/apache/accumulo/core/rpc/clients/ThriftClientTypes.java
Use shorter name for the registered Thrift processors. The side effect here is that a smaller number of bytes is sent over the wire.
Closes #2642
> Minimize registered Thrift processor names

- core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java
Compaction strategies have been deprecated in favor of compaction services that are defined on the table.
Closes #2833
> Updated TableOperations javadoc to remove compaction strategy ref

- test/src/main/java/org/apache/accumulo/test/LargeSplitRowIT.java
This IT has failed a few times due to timeout ([here](https://ci-builds.apache.org/job/Accumulo/job/main/org.apache.accumulo$accumulo-test/382/testReport/junit/org.apache.accumulo.test/LargeSplitRowIT/automaticSplitLater/) and [here](https://ci-builds.apache.org/job/Accumulo/job/main/org.apache.accumulo$accumulo-test/396/testReport/junit/org.apache.accumulo.test/LargeSplitRowIT/automaticSplitLater/)). This PR primarily increases the timeout for the failing IT.
While editing this file i saw a few places for improvements so I also added the following changes to this PR:
* adds resources to try-with-resources blocks
* make use of `Arrays.fill()`
* create and use variables with descriptive names
* make use of `NewTableConfiguration` to set properties where possible
* simplify logic where …
> LargeSplitRowIT.automaticSplitLater - increase timeout and other improvements

- .github/workflows/maven-full-its.yaml
- .github/workflows/maven-on-demand.yaml
- .github/workflows/maven.yaml
- .github/workflows/scripts.yaml
This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using https://github.com/step-security/secure-workflows. 
GitHub Actions workflows have a GITHUB_TOKEN with `write` access to multiple scopes. 
Here is an example of the permissions in one of the workflows:
https://github.com/apache/accumulo/runs/8277621128?check_suite_focus=true#step:1:19
After this change, the scopes will be reduced to the minimum needed for each workflow. 
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced. 
- GitHub recommends defining minimum GITHUB_TOKEN permissions. 
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-gith …
> Add minimum GitHub token permissions for workflows

- pom.xml
* Update Apache parent pom to 27
* Update Hadoop to 3.3.4
* Update Jackson, Jetty, Micrometer, Opentelemetry, checker-qual, snakeyaml, objenesis, javassist
* Add dependency convergence for jboss transitive logging deps
* Update plugins spotbugs, checkstyle
> Update parent pom and some others

- server/base/src/main/java/org/apache/accumulo/server/ServerContext.java
- server/base/src/main/java/org/apache/accumulo/server/conf/ServerConfigurationFactory.java
- test/src/main/java/org/apache/accumulo/test/functional/PerTableCryptoIT.java
* Hold instance of SystemConfiguration in ServerConfigurationFactory alongside other ZooBasedConfiguration instances (TableConfiguration and NamespaceConfiguration), and server it to ServerContext from there, rather than indirectly accessing it via an instance maintained in ServerContext
* Also fix warning about resource leak in PerTableCryptoIT by surrounding the scanner in a try-with-resources block
> Hold system config in ServerConfigurationFactory

- pom.xml
* Update Log4j2 to 2.19.0
* Update Curator to 5.3.0
* Update Jersey to 3.0.8
* Update Protobuf to 3.21.6
Log4j2 2.19.0 was released yesterday so this updates to that version (which will allow Slf4j 2.x at some point) and other minor dependency updates I noticed that we could bump.
> Update to Log4j2 2.19.0 and other dependency updates

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/functions.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/problems.js
Fixes #2941
This issue came from `functions.doLoggedPostCall()`. When sanitize was set to true, it would invoke a call to `sanitize()` which was not getting picked up as a call to the method with the same name (`functions.sanitize()`) but rather the boolean variable `sanitize`.
This PR changes the boolean variable name to `shouldSanitize` to avoid conflict/confusion with the method `sanitize()`.
To verify this change, follow the steps in #2941 to reproduce the issue then click the clear button. The respective entries should be cleared from the table.
> Fix the 'clear problems' buttons in the monitor

- core/src/test/java/org/apache/accumulo/core/crypto/CryptoTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/logger/LogReader.java
- test/src/main/java/org/apache/accumulo/test/functional/PerTableCryptoIT.java
* Added the -e option to LogReader to not read the whole WAL and just print the crypto params
* Make the LogReader options extend ConfigOpts to allow passing in properties and changed the -p option to --regex to differentiate from the properties option
* Added checkWALEncryption() to PerTableCryptoIT that calls the LogReader 
* Rename a test in CryptoTest
* Supports #2930
> Modify LogReader to print just the crypto params

- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/navbar.ftl
Fixes #2944 
This PR removes the underlining when hovering over the instance name in the top left corner of the monitor.
Before this change:
After this change:
> Make it so the instance name is not highlighted in the monitor

- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader9to10.java
I investigated upgrading a 2.0.1 instance that has data encrypted to the modified per-table encryption and it won't work with the properties that have changed. This change just uses No Crypto when reading data in the upgrade code.
If anyone is using the 2.0.1 encryption and needs to translate it to the 2.1 encryption, a custom utility will have to be written and used.
> Make Upgrader9to10 use No Crypto

- core/src/main/java/org/apache/accumulo/fate/zookeeper/ZooUtil.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader9to10.java
Fixes https://github.com/apache/accumulo/issues/2955 by using ZooKeeper digest in ACL checks.  (Code was provided by @dlmarion)
Manually performed upgrade from 2.0.1 to 2.1-0-SNAPHOT without problems.
Original issue is https://github.com/apache/accumulo/issues/2890
> fix #2955 - upgrade zk authorization check

- server/manager/src/main/java/org/apache/accumulo/manager/metrics/fate/FateMetrics.java
* Revert "Modify FateMetrics to enforce ReadOnlyStore required for Zooeeper (#2810)"
* This reverts commit 76092fc58eab7a3d4cc1fb87c376dc25b6f87537.
* Fixes #2968
> Revert ReadOnlyStore wrapping in FateMetrics

- server/base/src/main/java/org/apache/accumulo/server/manager/state/LoggingTabletStateStore.java
After restarting my Uno test cluster, a NullPointerException was thrown while trying to log suspended Tablets.
<pre>
2022-09-27T11:24:49,611 [manager.Manager] ERROR: Error processing table state for store Normal Tablets
java.lang.NullPointerException: null
at org.apache.accumulo.server.manager.state.LoggingTabletStateStore.suspend(LoggingTabletStateStore.java:88) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
at org.apache.accumulo.manager.TabletGroupWatcher.handleDeadTablets(TabletGroupWatcher.java:868) ~[accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
at org.apache.accumulo.manager.TabletGroupWatcher.flushChanges(TabletGroupWatcher.java:918) ~[accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
at org.apache.accumulo.manager.TabletGroupWatcher.run(TabletGroupWatcher.java:3 …
> Fix NPE in suspend logging

- server/base/src/main/java/org/apache/accumulo/server/util/FileUtil.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
* Revert some changes to FileUtil that used TabletFile. If a tablet is splitting and exceeds the tserver.tablet.split.midpoint.files.max then we will reduce the number of index files using temporary files. These temporary files don't conform to standard TabletFile directories so just use strings in this special case.
* Closes #2977
> Partial revert changes from #1519

- core/src/main/java/org/apache/accumulo/core/client/admin/InstanceOperations.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/InstanceOperationsImpl.java
- test/src/main/java/org/apache/accumulo/test/conf/PropStoreConfigIT.java
Removed API method that exposed Thrift object from InstanceOperations API. Modified method that called it to use the method internal directly and fixed up the test
Closes #2983
> Removed API method from InstanceOperations that exposed Thrift object

- core/src/main/java/org/apache/accumulo/core/iterators/Combiner.java
This PR removes a TODO from Combiner.java
The TODO says to test `Combiner.deepCopy()` and it looks like it is already being tested in several places including `CombinerTest.deepCopy()`
> Remove TODO that has already been addressed in Combiner

- hadoop-mapreduce/pom.xml
- iterator-test-harness/pom.xml
- minicluster/pom.xml
- pom.xml
- server/base/pom.xml
- server/compaction-coordinator/pom.xml
- server/compactor/pom.xml
- server/gc/pom.xml
- server/manager/pom.xml
- server/native/pom.xml
- server/tserver/pom.xml
- shell/pom.xml
- start/pom.xml
- test/pom.xml
Updates to log4j versions require log4j-core to be present for test logging.
> add log4j-core for test logging

- server/manager/src/main/java/org/apache/accumulo/manager/FateServiceHandler.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java
Explicitly block use of fate in the Manager service until the Manager starts up the fate functionality and it is ready for use. Attempt to provide useful logging information when this occurs, to ease troubleshooting, because this should not normally happen.
Fix #2980
> Block use of fate in Manager until fate is ready

- server/base/src/main/java/org/apache/accumulo/server/util/ManagerMetadataUtil.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableUtils.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/tablet/CompactableImplFileManagerTest.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
This commit fixes a bug where :
* user compactions take multiple compaction steps (because the tablet has many files)
* the intermediate steps produce no output
When the above happened CompactableImpl and Tablet would disagree about what files there were. The Tablet code would ignore the empty file produced by an intermediate compaction. CompactableImpl would expect Tablet to know of this file. When this happened things would hang until a tserver was restarted.
Ran into this bug while continually running Bulk random walk test to reproduce #2667
> fixes user compaction stuck when producing no output

- server/base/src/main/java/org/apache/accumulo/server/master/balancer/TabletBalancer.java
Trivial change to remove TODO comments from within the TabletBalancer.java `run` method.
The TODO referenced an older Jira ticket, ACCUMUO-2938, that has been marked resolved and closed. The TODO is no longer relevant.
> Remove unneeded TODO comments in TabletBalancer

- server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java
This ticket closes #3017 (SortedLogRecoveryTest failures).
That issue described a situation where a large number of tests within SortedLogRecoverTest.java were failing within certain environments. It failed consistently for me as well as on the Apache Jenkins server.
The problem was tracked down to a issue where the 'getFiles' method within RecoveryLogsIterator was returning a List of logFiles that were presumed to be in lexicographical order by file name. But on my particular instance (and presumably the Jenkins server), the files were not returned in that order. Therefore when 'validateFirstKey' retrieved the first file from the provided list, it was not actually checking the first key, but instead, whatever key was in the first file provided by the list. In cases where the order was …
> Change List to SortedSet in RecoveryLogsIterator

- .github/workflows/maven-full-its.yaml
- contrib/ci/it-matrix.sh
set-output was previously used to create the IT matrix, but it is now deprecated. So, this change makes use of the environment files instead.
See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
> Make use of GitHub Actions environment files

- core/src/main/java/org/apache/accumulo/core/clientImpl/NamespaceOperationsHelper.java
- shell/src/main/java/org/apache/accumulo/shell/commands/CreateNamespaceCommand.java
- test/src/main/java/org/apache/accumulo/test/NamespacesIT.java
Similar to #2965 
This PR aims to use `NamespaceOperations.modifyProperties()` in places where it seems to be a better fit. Mostly looked for places where multiple properties where being set with concurrent calls to `setProperty()`, often in a loop.
> Use NamespaceOperations.modifyProperties() in more places

- server/base/src/main/java/org/apache/accumulo/server/conf/store/PropStore.java
- server/base/src/main/java/org/apache/accumulo/server/conf/store/impl/PropCacheCaffeineImpl.java
- server/base/src/main/java/org/apache/accumulo/server/conf/store/impl/ZooPropStore.java
- server/base/src/test/java/org/apache/accumulo/server/conf/store/impl/PropCacheCaffeineImplTest.java
- server/base/src/test/java/org/apache/accumulo/server/conf/store/impl/ZooPropLoaderTest.java
While working on the concurrent property updates in https://github.com/apache/accumulo/issues/2996 noticed that the getWithoutCaching name could be misleading - changing to getIfCached to highlight that it only returns a value from the cache (and will not load values from ZooKeeper)
> rename method getWithoutCaching to getIfCached

- core/src/main/java/org/apache/accumulo/core/Constants.java
- server/base/src/main/java/org/apache/accumulo/server/conf/store/NamespacePropKey.java
- server/base/src/main/java/org/apache/accumulo/server/conf/store/PropStoreKey.java
- server/base/src/main/java/org/apache/accumulo/server/conf/store/SystemPropKey.java
- server/base/src/main/java/org/apache/accumulo/server/conf/store/TablePropKey.java
- server/base/src/main/java/org/apache/accumulo/server/conf/store/impl/ZooPropLoader.java
- server/base/src/main/java/org/apache/accumulo/server/conf/store/impl/ZooPropStore.java
- server/base/src/main/java/org/apache/accumulo/server/conf/util/ConfigPropertyUpgrader.java
- server/base/src/main/java/org/apache/accumulo/server/conf/util/ConfigTransformer.java
- server/base/src/main/java/org/apache/accumulo/server/conf/util/TransformToken.java
- server/base/src/main/java/org/apache/accumulo/server/conf/util/ZooInfoViewer.java
- server/base/src/main/java/org/apache/accumulo/server/init/ZooKeeperInitializer.java
- server/base/src/main/java/org/apache/accumulo/server/tables/TableManager.java
- server/base/src/test/java/org/apache/accumulo/server/conf/store/PropStoreKeyTest.java
- server/base/src/test/java/org/apache/accumulo/server/conf/store/impl/PropStoreEventTest.java
- server/base/src/test/java/org/apache/accumulo/server/conf/store/impl/ZooPropLoaderTest.java
- server/base/src/test/java/org/apache/accumulo/server/conf/store/impl/ZooPropStoreTest.java
- server/base/src/test/java/org/apache/accumulo/server/conf/util/ConfigPropertyUpgraderTest.java
- server/base/src/test/java/org/apache/accumulo/server/conf/util/ZooInfoViewerTest.java
- test/src/main/java/org/apache/accumulo/test/conf/PropStoreConfigIT.java
- test/src/main/java/org/apache/accumulo/test/conf/util/ConfigTransformerIT.java
- test/src/main/java/org/apache/accumulo/test/conf/util/TransformTokenIT.java
The original rework of the prop store was using a separate ZooKeeper node under the "original"  configuration node.  In ZooKeeper the structure looked like:
```
/accumulo/[instance id]/config/encoded_props  <-- system props
/accumulo/[instance id]/namespaces/[nid]/conf/encoded_props  <-- namespace props
/accumulo/[instance id]/tables/[tid]/conf/encoded_props  <-- table props
```
This removed that extra node an stores the configuration directly in the configuration node.  The structure now looks like:
```
/accumulo/[instance id]/config  <-- system props
/accumulo/[instance id]/namespaces/[nid]/config  <-- namespace props
/accumulo/[instance id]/tables/[tid]/config  <-- table props
```
> remove extra node in prop path

- core/src/main/java/org/apache/accumulo/core/clientImpl/ScanServerAttemptImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ScanServerAttemptReporter.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ScanServerAttemptsImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchReaderIterator.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/ScanAttemptsImplTest.java
- core/src/test/java/org/apache/accumulo/core/spi/scan/ConfigurableScanServerSelectorTest.java
As a follow-up to #2880:
* Remove unused and undocumented endTime in ScanAttempt API
* Rename ScanAttemptImpl method and variables from "mutationCounter" to
"attemptNumber" with corresponding comments to make it clear how this
is used for the snapshot
* Set attemptNumber in ScanAttemptImpl constructor as an immutable
value, rather than setting it immediately after construction
* Remove unnecessary synchronization and use an AtomicLong for the
currentAttemptNumber
* IDE changes also removed some unneeded keywords in the interface and
converted an anonymous inner class to a lambda
* Create the snapshot using Java streams instead of using "forEach()"
> Updates to ScanAttempts

- test/src/main/java/org/apache/accumulo/test/conf/store/ZooBasedConfigIT.java
The config changes in #3003 broke ZooBasedConfigIT that failed with full IT run - this fixes the test.
> fix ZooBasedConfigIT for config node changes

- core/src/main/java/org/apache/accumulo/core/client/summary/SummarizerConfiguration.java
- pom.xml
This PR bumps the version of the following plugins:
* versions-maven-plugin
* maven-checkstyle-plugin
* sortpom-maven-plugin
* formatter-maven-plugin
The changes in `SummarizerConfiguration.java` were automatically generated and must have been due to one of these plugins being updated.
> Bump several plugin versions

- test/src/main/java/org/apache/accumulo/test/conf/PropStoreConfigIT.java
This only changes the PropStoreSonfigIT test, with no other code changes.  Using a shared min instance in this test speeds up the my test runs by about 60 to 90 seconds and now completes in around 3:30.
> speed up test using shared cluster instance

- core/src/main/java/org/apache/accumulo/core/file/blockfile/impl/CachableBlockFile.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/BlockIndex.java
Make trivial improvements seen while investigating #2697
* Get rid of unnecessary generic method in internal implementation
* Drop redundant static modifier on interface
* Add explicit private constructor for BlockIndex
> Trivial improvements to block cache code

- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/ConcurrentKeyExtentCache.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkNewIT.java
Fixes a bug where bulk import would hang when the first row of the file was equal to the last row of the first tablet.
> Prevents bulk import from hanging.

- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/LoadFiles.java
In PR #3044 a bug was introduced that made an Ample operation that was intended to read a single tables metadata read multiple tables metadata.  This change fixes that bug limiting the Ample read a to a single tables metadata.
> fixes #3046 limiting ample to single table

- assemble/conf/log4j2-service.properties
- server/base/src/main/java/org/apache/accumulo/server/rpc/CustomNonBlockingServer.java
When FrameBuffer read and write methods return false it MAY be due to an error. Log at trace level the client address that it was trying to read from or write to. This will allow the user to modify the log level at runtime when they are seeing FrameBuffer errors being logged to try and identify the client.
Closes #3042
> Log the client address when FrameBuffer read or write methods return false

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/ec.js
Closes #3057
This change makes DataTable errors get logged to console instead of creating many, spammy alerts on the page.
> Move DataTable errors to console to avoid alerts

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/functions.js
Fixes the issue in #3048 where the `dateFormat()` function has a bug and returns the original date and not a formatted timestamp.
~~An example of the new format is: `10/28/2022, 11:49:29 AM EDT`~~
Update: I switched to use a modified version of the toISOString() method so the date is YYYY-MM-DD based on comments.
Updated sample of the new format: `2022-10-28 18:51:36,072Z`
> Properly format timestamps in Accumulo Monitor

- core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java
This addresses #3053 by setting thread pool creation logging to trace.  If merged, a follow-on for 3.0 will be created to examine thread pool usage to see if the are places for optimization.
> address #3053 set ThreadPool creation logging to trace

- pom.xml
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- server/compaction-coordinator/src/test/java/org/apache/accumulo/coordinator/CompactionCoordinatorTest.java
I added a unit test and I ran all ITs that matched the pattern `*Compaction*IT` but have not tested the scenario in #3045 with these changes.  The unit test shows it working in isolation, but not end to end.
> fixes #3045 remove stale compactions from coordinator

- core/src/main/java/org/apache/accumulo/core/file/blockfile/cache/lru/CachedBlock.java
- core/src/main/java/org/apache/accumulo/core/file/blockfile/cache/lru/CachedBlockQueue.java
- core/src/test/java/org/apache/accumulo/core/file/blockfile/cache/TestCachedBlockQueue.java
- core/src/test/java/org/apache/accumulo/core/file/blockfile/cache/TestLruBlockCache.java
PR #1333 had some significant test improvements.  Although there was a lot of commentary on the original ticket it did not seem to reach a conclusion.  This PR pulls the test improvements and fixes some check style errors but does not change the functionality of the code as proposed in #13333 - those can be evaluated or abandoned separately from these changes,
> test improvements from PR #1333 and check-style clean up

- contrib/Eclipse-Accumulo-Codestyle.xml
- pom.xml
* Update plugin version
* Update the Eclipse style configuration by:
* Import existing style Eclipse 2022-09 (corresponds to formatter-maven-plugin 2.21.0)
* Re-export the configuration and overwrite the file in the project
* Edit the exported file to sort the configuration lines to make it easier to see diffs later
* Run `mvn clean package -DskipTests` to ensure the license-maven-plugin re-adds the header to the configuration file
* For configuration properties new since the previous version of the config file, set their value to the Eclipse's sensible defaults to avoid using the terrible default value filled in during the import/export process. See related discussion on https://bugs.eclipse.org/bugs/show_bug.cgi?id=545603
> Update formatter-maven-plugin to 2.21.0

- server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
Also only shows stack traces in FileCompactor on file writer close errors when debug is enabled.
This closes #3023
> Reduce logging when external compactions are cancelled

- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/LogSorter.java
WAL files are not read after being written unless there is a failure that causes recovery. We can call setDropBehind on the DFSInputStream and DFSOutputStream to inform the DataNodes that they don't have to cache the WAL information after the file has been read or written.
> Call setDropBehind() when reading/writing WAL files

- server/base/src/test/java/org/apache/accumulo/server/constraints/MetadataConstraintsTest.java
- test/src/main/java/org/apache/accumulo/test/ScanServerMetadataEntriesIT.java
- test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java
- test/src/main/java/org/apache/accumulo/test/VerifySerialRecoveryIT.java
- test/src/main/java/org/apache/accumulo/test/compaction/CompactionExecutorIT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_1_IT.java
Use existing constants for referencing the table names and IDs for built-in tables in a few places that previously used hard-coded string literals. These aren't likely to change, but it makes it easier to find references of these built-ins when they use the constant, and it's easier to avoid typos.
I found these while working on #3080. They are very trivial, but nice to have.
> Use constants for tables instead of string literals

- core/src/main/java/org/apache/accumulo/core/data/ConditionalMutation.java
- core/src/main/java/org/apache/accumulo/core/data/Mutation.java
Add deprecation annotations for replication APIs in Mutation that should have been included in 2.1.0 along with the rest of the replication feature in #2335, but were unintentionally overlooked at the time.
> Add missing deprecation annotations in Mutation

- server/base/src/test/java/org/apache/accumulo/server/security/delegation/AuthenticationTokenSecretManagerTest.java
Part of the ID of the generated token is the issue date which is the current time in millis so this adds a 1 millisecond sleep in between token generation to guarantee the tokens will be unique.
This fixes #3075
> Fix flaky AuthenticationTokenSecretManagerTest

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ScannerImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchReader.java
- server/gc/src/main/java/org/apache/accumulo/gc/GCRun.java
- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java
- test/src/main/java/org/apache/accumulo/test/ScanServerIT.java
Reverts apache/accumulo#3082
This reverts the changes in #3082 from the 2.1 branch. The changes in this PR are not enough to allow Scan Servers to scan offline tables and more work is being done in #3091. #3091 is going to be included in 3.0, so I will duplicate these changes in that PR.
> Revert "Allow ScanServers to scan offline tables"

- start/src/main/java/org/apache/accumulo/start/Main.java
Added a line in 'Core Commands' list on Accumulo help page that shows jshell is a runnable command.
> JShell now documented on Accumulo command help page

- assemble/pom.xml
- pom.xml
The htrace4 dependency is not needed for Accumulo. It may or may not be a dependency of Hadoop, but if it is needed for that, it can be brought in via the Hadoop lib directory and added to Accumulo's runtime class path. However, since it is not needed for Accumulo itself, it should not be redistributed by Accumulo.
> Remove htrace4 from the binary distribution

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java
FileCompactor is also used by MinorCompactor then when the property TABLE_MAJC_OUTPUT_DROP_CACHE is set to true, the output file was being created with CreateFlag.SYNC_BLOCK and setDropBehind. This change modifies FileCompactor to not do that for minc output files.
> Modified FileCompactor to ignore TABLE_MAJC_OUTPUT_DROP_CACHE for minc

- core/pom.xml
- core/src/main/java/org/apache/accumulo/core/conf/ConfigCheckUtil.java
- core/src/main/java/org/apache/accumulo/core/conf/SiteConfiguration.java
- core/src/test/java/org/apache/accumulo/core/conf/ConfigCheckUtilTest.java
- core/src/test/java/org/apache/accumulo/core/conf/DefaultConfigurationTest.java
- server/base/src/main/java/org/apache/accumulo/server/conf/ServerConfigurationFactory.java
The `ConfigCheckUtil.validate` function logs  issues with properties, but does not include an id to help  find where the issue is occurring.  This PR adds the namespace or table id - or if an id is not provided, it assumes the property is from the site configuration.
This was noticed after upgrading a 2.1 instance with replication configured. PR #3137 is independent of these changes, but this PR does provide additional information once upgrades are possible with PR #3137
Before the changes, the logs looks like:
```
2022-12-27T17:55:57,477 [conf.ConfigCheckUtil] WARN : BAD CONFIG unrecognized property key (replication.name)
2022-12-27T17:55:57,477 [conf.ConfigCheckUtil] WARN : BAD CONFIG unrecognized property key (replication.peer.password.peer1)
2022-12-27T17:55:57,477 …
```
> Add id info to config check utility

- server/base/src/main/java/org/apache/accumulo/server/AccumuloDataVersion.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/UpgradeCoordinator.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader10to11.java
- server/manager/src/test/java/org/apache/accumulo/manager/upgrade/Upgrader10to11Test.java
- server/manager/src/test/java/org/apache/accumulo/manager/upgrade/UpgraderRemoveReplicationTest.java
Removes the replication information to allow the upgrade process to complete.  With these changes the upgrade process can successfully run from 2.1 to 3.0.
- removes replication iterator from metadata table.
- removes replication properties from values saved in ZooKeeper.
This PR adds a new data version (from 10 to 11) to separate the replication removal from other upgrade ops that occur.  With 3.0, most (if not all) of the previous upgrade ops can be assumed to have occurred be cause 3.0 will only support upgrades from 2.1.  The new data version may then be unnecessary - but it may make merging between versions easier.  The removal of unnecessary upgrades ops will be addressed as a separate PR.
> Removing replication info necessary for upgrade - resolves issue #3097

- server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java
- test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java
TServerUtils was not correctly setting the max frame size value on the constructor when creating a TNonblockingServerSocket leading to failures if the frame size exceeded the default.
> Make sure maxMessageSize is correctly set when Thrift is configured to use a non blocking server

- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/ScanServerTest.java
The ScanServer was throwing a NotServingTabletException in both the scan and batch scan cases when there was a failure in loading the tablet. Modified the batch scan case to return the failed tablets in the response instead of throwing the exception.
Closes #3144
> Modified ScanServer to correctly handle tablet failures

- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/ScanServerTest.java
The ScanServer was throwing a NotServingTabletException in both the scan and batch scan cases when there was a failure in loading the tablet. Modified the batch scan case to return the failed tablets in the response instead of throwing the exception.
Closes #3144
> Modified ScanServer to correctly handle tablet failures (#3150)

- core/src/main/java/org/apache/accumulo/core/client/impl/TabletLocatorImpl.java
- core/src/test/java/org/apache/accumulo/core/client/impl/TabletLocatorImplTest.java
Found this problem while testing #3143.  Since it was a more general problem, decided to fix it in 1.1
> Fixes tablet location cache bug that caused batch scanner to return duplicate data

- test/src/main/java/org/apache/accumulo/test/LargeSplitRowIT.java
- test/src/main/java/org/apache/accumulo/test/functional/KerberosRenewalIT.java
After reviewing #3177 I realized that some of the spots that `Wait.waitFor()` is used in the tests does not check the value of the returned `boolean`. This PR asserts that the cases that were not being checked, now are.
> Fix usage of Wait.waitFor() in ITs

- server/base/src/main/java/org/apache/accumulo/server/util/SystemPropUtil.java
The exceptions thrown here are already logged at the error level via the calling method `modifySystemProperties` from the
`ManagerClientServiceHandler` class.
https://github.com/apache/accumulo/blob/2.1/server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java#L461-L462
Writing these exceptions at the error level would result in duplicate exception messages in the logs.
Switching these back to only log the exceptions at the debug level.
> Switch log level to trace

- core/src/main/java/org/apache/accumulo/core/client/ClientSideIteratorScanner.java
- core/src/main/java/org/apache/accumulo/core/client/IsolatedScanner.java
- core/src/main/java/org/apache/accumulo/core/client/impl/ScannerIterator.java
- core/src/main/java/org/apache/accumulo/core/client/impl/ScannerOptions.java
- core/src/main/java/org/apache/accumulo/core/client/impl/TabletServerBatchReader.java
- core/src/main/java/org/apache/accumulo/core/client/impl/TabletServerBatchReaderIterator.java
- Fixes parameter check that was using instance variable (timeOut) instead of passed value (timeout)
- Renames variable timeOut to retryTimeout to improve readability and reflect usage
- Renames variable batchTimeOut to batchTimeout for consistent case convention.
Replaces https://github.com/apache/accumulo/pull/3172 that was based on 2.1
> fix parameter check and minor variable rename

- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/UpgradeCoordinator.java
The map  of data version was using Map.of - use TreeMap to guarantee the sort order by data version. Noticed by @ctubbsii while working #3160
> Enforce sort order of data version for upgraders

- core/src/main/java/org/apache/accumulo/core/client/sample/AbstractHashSampler.java
- core/src/main/java/org/apache/accumulo/core/client/sample/RowColumnSampler.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java
Discovered a bug in AbstractHashSampler and RowColumnSampler classes while examining the Sample example. The final portion of the example was failing to return any data. Found that the AbstractHashSampler would produce and error any time an any additional option were provided. It would only handle the required hasher and modulus options correctly.
Conversely, the RowColumnSampler would fail when presented with the require hasher and modulus options.
Updated such that the RowColumnSampler will ignore the required options, allowing the AbstractHashSampler to handle them, and only validate options specific to the RowColumnSampler.
The AbstractHashSampler was updated to ignore any non-required options.
Added comments to indicate that the AbstractHashSampler validates required options while …
> Update validation of options in Sampler code

- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionPlannerInitParams.java
- server/base/src/test/java/org/apache/accumulo/server/conf/CheckCompactionConfigTest.java
Added additional error details for a couple of Compaction configuration failure conditions.
The use of duplicate Compaction Executor ID's in configuration will return an explicit message detailing the issue in the error output.
Similarly, maxSize errors or null Compaction ID's will detail the issue in the error output.
> Added error details for Compaction Configuration failures

- assemble/bin/accumulo-cluster
- core/src/main/java/org/apache/accumulo/core/conf/cluster/ClusterConfigParser.java
- core/src/test/java/org/apache/accumulo/core/conf/cluster/ClusterConfigParserTest.java
- This commit adds support to provide an optional argument to ClusterConfigParser to write the output to a file instead of System.out so that only the output we want is captured and not everything that's written to standard out.
-  This the accumulo-cluster script has also been updated to to provide the temp file as an output file argument instead of capturing System.out so that there are not parsing errors by the script if other output is written to the standard out stream.
This fixes parsing issues if there's anything that writes to standard out/error but the main reason for this PR is to fix https://github.com/apache/accumulo-classloaders/issues/18 because the debug output (or any other output) by the classloader to standard out/err will no longer interfere with the parsing by the …
> Support writing cluster config parser output to a file

- pom.xml
Update several dependencies to new versions. I targed this for 2.1 but if anything should not be part of that and only 3.0 I can remove it. I did not include Log4j2 update as that is already part of https://github.com/apache/accumulo/pull/3204, assuming that PR is changed to merge into 2.1 and not main.
* Apache parent 29
* Slf4j 2.0.6
* Jackson 2.14.2
* Jetty 11.0.13
* Jaxb 4.0.2
* Jersey 3.0.9
* Junit 5.9.2
* Caffeine 3.1.4
* Protobuf 3.22.0
* Jline 3.22.0
* Spotbugs annotations 4.7.3
* Freemarker 2.3.22
Also, I didn't update OpenTelemetry or Micrometer as part of this because updating Micrometer caused dependency convergence issues involving Netty and Zookeeper when running one of the Jenkins CI runs `mvn -B -V -e -ntp "-Dstyle.color=always" -DskipFormat package -DskipTests …
> Update several dependency versions

- pom.xml
Jenkins build is failing after switch to Maven 3.9.0 due to plugin issues. This updates the plugins to fix it.
- modernizer-maven-plugin: 2.5.0
- impsort-maven-plugin: 1.8.0
Example in 2.1 failure: https://github.com/apache/accumulo/actions/runs/4323146250/jobs/7546578107
> Update Maven plugins to support Maven 3.9.0

- core/src/main/java/org/apache/accumulo/core/classloader/URLContextClassLoaderFactory.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java
- core/src/main/java/org/apache/accumulo/core/data/InstanceId.java
- core/src/main/java/org/apache/accumulo/core/data/NamespaceId.java
- core/src/main/java/org/apache/accumulo/core/data/TableId.java
- core/src/main/java/org/apache/accumulo/core/file/FileOperations.java
- core/src/main/java/org/apache/accumulo/core/file/blockfile/impl/CachableBlockFile.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/CompressionAlgorithm.java
- core/src/main/java/org/apache/accumulo/core/iterators/Combiner.java
- core/src/main/java/org/apache/accumulo/core/spi/balancer/HostRegexTableLoadBalancer.java
- core/src/main/java/org/apache/accumulo/core/spi/fs/SpaceAwareVolumeChooser.java
- core/src/main/java/org/apache/accumulo/core/summary/Gatherer.java
- core/src/main/java/org/apache/accumulo/core/summary/SummaryReader.java
- core/src/main/java/org/apache/accumulo/core/util/tables/TableZooHelper.java
- core/src/test/java/org/apache/accumulo/core/iterators/CombinerTestUtil.java
- core/src/test/java/org/apache/accumulo/core/spi/fs/SpaceAwareVolumeChooserTest.java
- pom.xml
- server/base/src/main/java/org/apache/accumulo/server/fs/FileManager.java
- server/manager/pom.xml
- server/manager/src/main/java/org/apache/accumulo/manager/recovery/RecoveryManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
[Caffeine](https://github.com/ben-manes/caffeine) is the replacement for the Guava cache api and has several improvements including efficiency with its admission [policy](https://github.com/ben-manes/caffeine/wiki/Efficiency) and [performance](https://github.com/ben-manes/caffeine/wiki/Benchmarks). Currently the Accumulo code base has a mixture where some places use Guava and some places use Caffeine so it is not consistent. Switching to Caffeine is nearly a drop in replacement and this commit replaces all instances of Guava with Caffeine for consistency and also adds a checkstyle rule to prevent using Guava in the future.
From the Guava [docs](https://guava.dev/releases/31.1-jre/api/docs/com/google/common/cache/CacheBuilder.html) regarding Caffeine: 
> **Prefer …
> Replace all instances of Guava cache with Caffeine

- assemble/pom.xml
- core/pom.xml
- hadoop-mapreduce/pom.xml
- iterator-test-harness/pom.xml
- minicluster/pom.xml
- pom.xml
- server/base/pom.xml
- server/compaction-coordinator/pom.xml
- server/compactor/pom.xml
- server/gc/pom.xml
- server/manager/pom.xml
- server/native/pom.xml
- server/tserver/pom.xml
- shell/pom.xml
- start/pom.xml
- test/pom.xml
Duplicate of the changes in #3204 targeting 2.1
Removes the log4j-core dependency which was previously needed due to https://issues.apache.org/jira/browse/LOG4J2-3601 which is fixed as of version 2.20
> Update log4j and remove log4j-core dependency

- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooUtil.java
- core/src/test/java/org/apache/accumulo/core/fate/zookeeper/ZooUtilTest.java
- Uses Collections.unmodifiableList to limit the exposure of the PRIVATE and PUBLIC collections.
- Adds tests that replicate the current ZooKeeper check (in ZooKeeper, the method is private)
Spotbugs warns (MS_MUTABLE_COLLECTION) for the the public, static definitions in ZooUtil for PRIVATE and PUBLIC ZooKeeper ACLs that expose a mutable collection (ArrayList).  This was discovered when refactoring ServiceLock from fate to another package in core.  Verified, that with this change, spotbugs does not flag the issue.
Using an immutable collection like List.of() or List.copyOf() result in an NPE from ZooKeeper.  ZooKeeper that performs a ACL check on operations like create,... The ZooKeeper check calls `acl.contains((Object) null)` which throws an NPE in Java (JDK-8265905)
> Use Collections.unmodifiableList for static ACL declarations

- .github/workflows/maven.yaml
- server/tserver/src/main/java/org/apache/accumulo/tserver/FileManager.java
This commit switches the filePermits semaphore to a "fair" semaphore which ensures that threads requesting reserved readers are handled in a FIFO queue vs ending up in a starvation state for resources.
This also switches the log statement from an info to a warn since that message is thrown when a property value is exceeded. 
Since the property is configurable, the system should warn that scans are taking that long vs just being a normal info level message. 
Fixes #3198
> Fix scan thread resource starvation

- server/master/src/main/java/org/apache/accumulo/master/Master.java
Replaces the retry object with a wait loop.
Log messages are generated independent of max wait time.
Closes #3159
> Fix wait timeout logic for available tservers

- server/base/src/main/java/org/apache/accumulo/server/metadata/TabletMutatorBase.java
Fixes a bug in Ample that no current code is encountering.  Ran into this bug while working on #3232 and trying to write new code that splits a tablet using conditional mutations. Fixing this bug in 2.1 in case any new code is written that would encounter the bug.
> fixes unencountered bug in ample

- server/master/src/main/java/org/apache/accumulo/master/Master.java
This change keeps the calculated timeouts for a defined maxWait loop while still allowing the infinite loop case to have an incremental backoff.
This ensures that log messages still show up in a semi-frequent manner to alert users of the continued blocking.
Related to #3231 and #3234
> Handle infinite blocking loops

- server/base/src/main/java/org/apache/accumulo/server/mem/LowMemoryDetector.java
The check was executing the action before returning whether or not the server was running low on memory. For actions that included a wait, this would cause those processes to wait unnecessarily. This changes the method such that the action is only executed if the server is running low on memory
Closes #3240
> Fix conditional in LowMemoryDetector

- core/src/main/java/org/apache/accumulo/core/file/blockfile/impl/SeekableByteArrayInputStream.java
Fixes #3218 
This PR converts `cur` and `max` to `AtomicInteger`. This should address the concerns in the ticket.
One thing I considered is converting `buffer` from a `volatile` variable to an `AtomicRefference` but I am not too familiar with the trade offs associated. If anyone has any insight into this that would be helpful.
> Use AtomicInteger for index pointers in SeekableByteArrayInputStream

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/MinorCompactionTask.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
In addition to avoiding tablet lock for split computations, this PR also avoid redoing split computations when the files have not changed.
> Avoids holding tablet lock while doing split computations

- pom.xml
Replace poorly supported `session.executionRootDirectory` property, and fragile, hierarchy-dependent `project.parent.basedir` property for paths to files at the root of the project that are needed by plugin executions in child modules.
Instead, use the build-helper-maven-plugin's rootlocation goal to explicitly set a property that points to the root of the multi-module project to resolve the location of those files consistently.
> Set root location property for paths to contrib files

- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer1/BulkImport.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer1/CleanUpBulkImport.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/BulkImportMove.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/CleanUpBulkImport.java
Refactor's the Bulk Import metadata operations from the MetadataTableUtil class and migrate them to use Ample instead. 
This is a part of #3208.
> Convert Bulk Import metadata actions to use Ample

- core/src/main/java/org/apache/accumulo/core/metadata/schema/DataFileValue.java
- server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java
- server/base/src/main/java/org/apache/accumulo/server/fs/FileManager.java
Centralized wrapping per file iterators based on per file information from the metadata tables. This allows scans and compactions to use the same code to setup their per file iterators.
> centralizes wrapping per file iterators based on metadata

- core/src/main/java/org/apache/accumulo/core/clientImpl/RootTabletLocator.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/SyncingTabletLocator.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletLocator.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletLocatorImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftScanner.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/Writer.java
- core/src/main/java/org/apache/accumulo/core/metadata/MetadataLocationObtainer.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/TabletLocatorImplTest.java
- server/base/src/main/java/org/apache/accumulo/server/client/BulkImporter.java
- server/base/src/test/java/org/apache/accumulo/server/client/BulkImporterTest.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkFailureIT.java
- test/src/main/java/org/apache/accumulo/test/manager/SuspendedTabletsIT.java
This commit has no changes in functionality, it only contains some minor code cleanup of the TabletLocator code.
The following changes were made.
* Encapsulated fields in TabletLocation class
* Replaced a Callable interface with a Supplier interface to avoid the uneeded exception thrown by Callable
* Removed an uneeded compareTo method from TabletLocation class
> Performs some minor cleanup of TabletLocator

- core/src/test/java/org/apache/accumulo/core/util/ValidatorsTest.java
This PR adds a test for the new `NOT_METADATA_TABLE_ID` `Validator`
> Add test for new Validator

- core/src/main/java/org/apache/accumulo/core/security/Authorizations.java
Instead of creating collections with default initial capacities, create them with the known capacities. This will reduce the time taken and amount of memory consumed when populating these objects during Authorizations object creation when the number of elements in the Authorizations is larger than the default initial capacity of the collection data structure. This may also reduce the time it takes the VisibilityEvaluator to determine if the Authorizations object contains a token found in a ColumnVisibility.
> Optimize internal data structures in Authorizations

- server/base/src/main/java/org/apache/accumulo/server/conf/ServerConfigurationFactory.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java
* Clear secondary prop cache in ServerConfigurationFactory more aggressivly on ZooKeeper prop changes
* Add test to ShellServerIT
* Change ShellServerIT to use 'Wait.waitFor()'
The shell server IT exporttable Importtable test occasionally fails. It sets a property, exports then imports a table - expecting to see a modified value for the property in the new, imported table.  There is a race condition and the changed property is not written with the exported configuration.
There is a secondary property cache in ServerConfigurationFactory that was not directly updated / cleared but deferred updates to the property cache.  This change clears the cached item (based in property id) on any ZooKeeper notification for that id.
> Clear ServerConfigurationFactory cache on ZooKeeper notifications. Improve ShellServerIT test.

- core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftScanner.java
The code for resolving which tserver or sserver to use for a scan was spread out across multiple methods responsible for executing a scan. Pulled the code to resolve which server to use into a single place in the code that executes a scan.
Also introduced a new class to represent the server and server type (sserver or tserver) used to process a scan.
These changes clean up two problems in the code. First the tablet server location class was being used to represent a scan server with a special string placed in the tserver session field. Second the decision to use a scan server was deeper in the scan code than error reporting code and the resulted in the need for an odd instance variable to remember that a scan server was used for error reporting.  Removing these two problems makes the code …
> Resolves server to use for scan in a single place

- core/src/main/java/org/apache/accumulo/core/clientImpl/RootTabletLocator.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/SyncingTabletLocator.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletLocator.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletLocatorImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchReaderIterator.java
- server/base/src/test/java/org/apache/accumulo/server/client/BulkImporterTest.java
Refactors the batch scanner code to make two improvements.  First mapping ranges to scan servers or tservers was moved under one method. Second the process of mapping ranges to scan servers using the tablet location cache was improved.  The tablet location cache used to organized data in a a way that was useful for immediate scans and eventual scans had to reorganize the data.  A new method was added to the tablet location cache that passes the raw data to a consumer that can orgranize it in any way.  This new method is used for scan servers.
> Improves scan server resolution in batch scanner code.

- core/src/main/java/org/apache/accumulo/core/spi/scan/ConfigurableScanServerSelector.java
- core/src/main/java/org/apache/accumulo/core/spi/scan/ScanServerSelections.java
- core/src/test/java/org/apache/accumulo/core/spi/scan/ConfigurableScanServerSelectorTest.java
The pluggable scan server selector provided by Accumulo had a minor bug in its configration parsing.  It expected the default profile to always come first in the config, even though it could occur any position.
Also some since tags were missing the for scan servers SPIs, added those.
> Fixes a minor scan server bug and adds some since tags

- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkSerialize.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/LoadMappingIterator.java
- core/src/main/java/org/apache/accumulo/core/util/ByteArrayToBase64TypeAdapter.java
- core/src/test/java/org/apache/accumulo/core/util/ByteArrayToBase64TypeAdapterTest.java
BulkSerialize had a Gson adapter to serialize byte arrays to Base64 encoding that can be re-used by other areas in the code. Also update the uses of the base 64 Gson object to be static and re-used as the objects are thread-safe so can be created just one time.
I noticed this when working on serializing ranges as part of the updates for #1327 and this PR will be the first part of my PR for that task but this was something that could be done separately and pulled out into its own PR.
> Move Gson ByteArrayToBase64TypeAdapter to its own utility class

- pom.xml
Fix flaky build issue with Hadoop 3 profile by using the same Jetty release series as Hadoop 3.0.3,
which is Eclipse Jetty 9.3. Select the latest patched version of 9.3.
> Bump Jetty to 9.3 for Accumulo 1.10

- test/src/main/java/org/apache/accumulo/test/metrics/TestStatsDSink.java
Currently the line length being returned in statsd is exceedingly long. 
Adding a trim line to the parseStatsDMetric test sink for better testing validation.
NOTE: this does not solve any possible issues with metric data size, just testing output.
> Add trim command to parse metrics

- core/src/main/java/org/apache/accumulo/core/metrics/MetricsUtil.java
- pom.xml
- server/base/src/main/java/org/apache/accumulo/server/metrics/ThriftMetrics.java
- server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java
- server/base/src/main/java/org/apache/accumulo/server/rpc/TimedProcessor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- test/src/main/java/org/apache/accumulo/test/metrics/MetricsIT.java
- test/src/main/java/org/apache/accumulo/test/metrics/TestStatsDSink.java
- Fixes tserver initialization so host name and port are reported in metrics
- remove extra tags from thrift metrics
- Update opentelemetry and micrometer versions
- update test to check tag length is sane.
- Includes fix for tag length submitted as PR #3296 
Currently, tserver metrics tags do not include the host and there are extra tags on the thrift metrics.  Currently the tags are reported as:
```
METRICS, name: 'accumulo.thrift.idle' num tags: 4, tags: {process.name=tserver, server=TabletServer, Address=0.0.0.0, thread=Thrift Client Server}
METRICS, name: 'accumulo.thrift.idle' num tags: 4, tags: {process.name=tserver, server=TabletServer, Address=0.0.0.0, thread=Thrift Client Server}
METRICS, name: 'accumulo.thrift.idle' num tags: 4, tags: {process.name=manager, server=Manager, …
```
> fix metrics tags, tserver hostname, remove tags from thrift metrics

- docs/src/main/asciidoc/chapters/iterator_design.txt
Fixes #3287 
This PR applies the changes made to the website, in https://github.com/apache/accumulo-website/pull/383, to the 1.10 User Manual.
> Fix Teardown documentation in 1.10 User Manual

- assemble/pom.xml
With the latest version of micrometer (1.10.6), there is a runtime dependency on micrometer-commons.
@jmark99 discovered running fluo that the manager / tservers were dying with the exception
<details>
<summary>java.lang.NoClassDefFoundError: io/micrometer/common/util/internal/logging/InternalLoggerFactory</summary>
```
Exception in thread "manager" java.lang.NoClassDefFoundError:io/micrometer/common/util/internal/logging/InternalLoggerFactory
at io.micrometer.core.instrument.binder.jvm.ExecutorServiceMetrics.<clinit>(ExecutorServiceMetrics.java:58)
at org.apache.accumulo.core.metrics.MetricsUtil.addExecutorServiceMetrics(MetricsUtil.java:117)
at org.apache.accumulo.core.util.threads.ThreadPools.createScheduledExecutorService(ThreadPools.java:541)
at …
```
> add dependency for packaging, micrometer-core has a runtime dependency on micrometer-commons

- server/base/src/main/java/org/apache/accumulo/server/rpc/TimedProcessor.java
Use nano time instead of System.currentTime in thrift metric calculation.
This also renames an variable to improve readability.  The time captured as stored locally as `now` but was also used as start time for second calculation.  Renamed and added comment,
> update to use nanotime in TimedProcessor calculations

- test/src/main/java/org/apache/accumulo/test/functional/ManagerAssignmentIT.java
Fixes #3311 
This PR adds the following changes to ManagerAssignmentIT
* Use `Wait.waitFor()` blocks in place of while loops
* rename some variables
* add some variable to try-with-resources blocks
Note: this PR targets the elasticity branch since this test is only in that branch.
> Improvements to ManagerAssignmentIT

- core/src/main/java/org/apache/accumulo/core/data/Mutation.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/MetadataSchema.java
- core/src/main/java/org/apache/accumulo/core/util/Encoding.java
- server/base/src/main/java/org/apache/accumulo/server/problems/ProblemReport.java
- server/base/src/main/java/org/apache/accumulo/server/problems/ProblemReports.java
- server/base/src/test/java/org/apache/accumulo/server/problems/ProblemReportTest.java
Adds ProblemReport section to the metadata schema to consolidate metadata table prefixes.
This removes hardcoded prefix strings located in various classes.
> Add ProblemReport section to metadata schema

- server/base/src/main/java/org/apache/accumulo/server/manager/state/MetaDataTableScanner.java
While reviewing #3331 an unused variable in MetaDataTableScanner was noticed.  Seems like the purpose of this variable was to get the most recent last column when there are multiple last cols. Update the code to use the variable and hopefully get the most recent last column.
> use the most recent last column in tablet

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
Make sure to catch and log any errors when the tablet metadata verification task runs to check tablet metadata so that errors do not cause the task and server to halt.
This closes #3346
> Handle exceptions during tablet metadata task

- core/src/main/java/org/apache/accumulo/core/client/admin/NewTableConfiguration.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- core/src/test/java/org/apache/accumulo/core/client/admin/NewTableConfigurationTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/FateServiceHandler.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/TableInfo.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/create/CreateTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/create/PopulateMetadata.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/goal/SetHostingGoal.java
- shell/src/main/java/org/apache/accumulo/shell/commands/CreateTableCommand.java
- test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellCreateTableIT.java
Modified NewTableConfiguration to support users setting initial hosting goals for tables at time of table creation.
Updates allow for setting goals via API and via the Accumulo shell.
CreateTable fate operation was updated to set initial goal upon creation of tables. If splits are set at table creation, each tablet will have the appropriate hosting goal set for the tablet.
Unit and IT tests were created to verify the changes.
> Allow setting of initial hosting goal with NewTableConfiguration

- core/src/main/java/org/apache/accumulo/core/util/threads/AccumuloUncaughtExceptionHandler.java
- core/src/test/java/org/apache/accumulo/core/util/threads/AccumuloUncaughtExceptionHandlerTest.java
Also changes code to assume a deeply nested exception that can not be fully inspected may contain an error.
> halts when nested error seen in uncaught exception handler

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/manager.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/manager.ftl
Fixes #3373 
This PR adds a banner to the Manager page in 2.1 that will be displayed when the Managers state is not normal or when the state and the goal state differ. The new manager state banner will not be displayed if the manager is down.
Here are some screenshots from the updated Manager page:
When state and goal state differ:
After state and goal state converge (and the state is not 'NORMAL'):
When the manager is not running:
> Show manager goal state in monitor

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/conf/PropertyType.java
- core/src/main/java/org/apache/accumulo/core/iterators/system/MapFileIterator.java
- core/src/test/java/org/apache/accumulo/core/conf/PropertyTypeTest.java
Drop MapFile support (#3359) by partially backporting PR #3378, and making minimally disruptive changes to avoid use of MapFiles for 1.10.4 and 2.1.1.
As noted in #3378, MapFile support is already broken and has been for a long time. This change will cause an explicit and detectable failure, rather than a silent one, if a MapFile is attempted to be used.
> Disable MapFile in 1.10 and 2.1 patch releases

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Update the log message for InterruptedException inside the Tablet class to include the full stack trace as it is logged at the error level.
> Include missing stack trace when logging error

- core/src/main/java/org/apache/accumulo/core/metrics/MetricsProducer.java
- core/src/main/java/org/apache/accumulo/core/util/ratelimit/GuavaRateLimiter.java
- core/src/main/java/org/apache/accumulo/core/util/ratelimit/NullRateLimiter.java
- core/src/main/java/org/apache/accumulo/core/util/ratelimit/RateLimiter.java
- core/src/main/java/org/apache/accumulo/core/util/ratelimit/SharedRateLimiterFactory.java
- pom.xml
* Update our plugins with versions that we specify to the latest
* Update plugins whose versions are in the parent POM, to avoid warnings about deprecations in Maven 3.9
* Fail on javadoc doclint issues, and fix the single issue in the MetricsProducer
* Work around revelc/impsort-maven-plugin#72 by renaming the "permits" variable in rate limiter APIs
* Bump some low-risk dependencies: curator, jackson, micrometer, netty, opentelemetry, jetty, hk2, caffeine, gson, commons-io, commons-configuration2, checker-qual, hibernate-validator, jline, snappy-java, snakeyaml
> Minor POM quality updates

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientTabletCache.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/RootClientTabletCache.java
The root tablet client cache was not handling request that did not require a location.  Adds support for handling that case in a manner that is similar to the non-root tablet client cache.
fixes #3420
> handles case where location is not required in root tablet cache

- core/src/main/java/org/apache/accumulo/core/util/Retry.java
- core/src/test/java/org/apache/accumulo/core/util/RetryTest.java
> Fix Long overflow in Retry when backoff factor > 1.0

- assemble/bin/accumulo-cluster
- assemble/bin/accumulo-service
- assemble/bin/accumulo-util
- core/pom.xml
- core/src/main/scripts/generate-thrift.sh
- core/src/main/scripts/mkdirs.sh
- minicluster/pom.xml
- pom.xml
- server/monitor/pom.xml
Reduce warnings at the end of the build from using Maven 3.9.2 by updating several plugins whose versions are specified in the parent POM to the latest, which resolves the warnings from Maven. Specifically, update maven-resources-plugin, maven-compiler-plugin, exec-maven-plugin, apilyzer-maven-plugin, maven-dependency-plugin, and maven-enforcer-plugin.
Update some dependency declarations, based on new detections from latest version of maven-dependency-plugin (specifically, zookeeper-jute in minicluster and libthrift in the monitor).
Updating exec-maven-plugin required addressing #3033 with a workaround, and testing the script added for that workaround caught some additional shellcheck issues in the assembly module's cluster management scripts (unreachable redundant exit command) and …
> More build updates to reduce warnings

- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java
~~This PR addresses a TODO about using a binary search. In addition I moved the `FileSKVIterator index` to the try-with-resources block.~~
Edit:
This PR now removes a TODO comment about using binary search (after determining that it is not an improvement) and moves a resource to a try-wth-resources block in `BulkImport.estimateSizes()`
> Minor improvements to BulkImport.estimateSizes()

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloConfigImpl.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeManagerImpl.java
- server/gc/src/main/java/org/apache/accumulo/gc/GCRun.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/gc/src/test/java/org/apache/accumulo/gc/SimpleGarbageCollectorTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/upgrade/RootFilesUpgradeTest.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorTrashBase.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorTrashDefaultIT.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorTrashDisabledIT.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorTrashEnabledCustomPolicyIT.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorTrashEnabledIT.java
- test/src/main/resources/log4j2-test.properties
This commit:
1. Deprecated GC_TRASH_IGNORE
2. Modifies MiniAccumuloCluster so that the user can provide Hadoop properties for the Hadoop configuration that is used by the MiniDFS cluster.
3. Adds ITs that confirm:
a. Deleted files do not get put into the Trash in the default configuration (Accumulo enabled / Hadoop disabled) 
because the default value for fs.trash.interval is zero, which means disabled.
b. Deleted files do get put into the Trash when the default Accumulo configuration is used (GC_TRASH_IGNORE = false) and fs.trash.interval is set to a nonzero value. 
c. Deleted files do not get put into the Trash when GC_TRASH_IGNORE is set to true and fs.trash.interval is set to a nonzero value. 
d. Deleted files do not get put into the Trash when Accumulo and Hadoop are enabled, but a …
> Deprecate GC_TRASH_IGNORE, add tests to confirm Trash works

- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/TabletMutatorBase.java
- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
This fixes instances identified in #3417 where updates to existing files in the metadata table were using the normalized path by mistake and not the existing path.
> Make sure existing file path is used for metadata updates

- test/src/main/java/org/apache/accumulo/test/functional/FileNormalizationIT.java
Adds a test for misnormalized files in the metadata table.  The test currently does not run because splits do not handle misnormalized files.  The split code will duplicate files in the existing tablet when it tries to update the estimated size.  Surprisingly the duplicated files causes the tserver to crash on tablet assignment.
Seeing the following error when the tserver tries to load a tablet with duplicated files entries (multiple entries that normalize to the same path).
```
2023-05-26T17:56:22,089 [tserver.AssignmentHandler] WARN : Failed to verify tablet 1<;row_0000050000
java.lang.IllegalArgumentException: Multiple entries with same key: file:/home/ubuntu/git/accumulo/test/target/mini-tests/org.apache.accumulo.test.functional.FileNormalizationIT_SharedMiniClusterBase/accumulo/tables …
```
> adds tests for file misnormalization

- core/src/main/java/org/apache/accumulo/core/cli/ConfigOpts.java
The ConfigOpts used -s option for safemode. Remove the deprecated option to allow utilities to reuse ConfigOpts and use -s for set to match the shell option.
> Remove the deprecated -s (safemode) option from ConfigOpts

- core/src/main/java/org/apache/accumulo/core/file/BloomFilterLayer.java
- core/src/main/java/org/apache/accumulo/core/metadata/ReferencedTabletFile.java
- core/src/main/java/org/apache/accumulo/core/metadata/ScanServerRefTabletFile.java
- core/src/main/java/org/apache/accumulo/core/metadata/StoredTabletFile.java
- core/src/main/java/org/apache/accumulo/core/metadata/UnreferencedTabletFile.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/ExternalCompactionMetadata.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/ReferencedTabletFileTest.java
- server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeUtil.java
- server/base/src/main/java/org/apache/accumulo/server/init/FileSystemInitializer.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/TabletMutatorBase.java
- server/base/src/main/java/org/apache/accumulo/server/util/FileUtil.java
- server/base/src/main/java/org/apache/accumulo/server/util/ManagerMetadataUtil.java
- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
- server/base/src/test/java/org/apache/accumulo/server/util/TableDiskUsageTest.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/LoadFiles.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/ExternalCompactionJob.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableUtils.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/MinorCompactionTask.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/MinorCompactor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/TabletData.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/compaction/CompactableUtilsTest.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorTrashBase.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitRecoveryIT.java
Renaming `TabletFile` to `ReferencedTabletFile` so it matches `UnreferencedTabletFile` and will allow adding a new more generic `TabletFile` interface in a future commit.
The plan is to add a new `TabletFile` interface that can be used everywhere instead of `AbstractTabletFile` in the code but that needs to be added in a separate commit otherwise git won't detect the file rename from `TabletFile` to `ReferencedTabletFile`. Having git detect the rename is important so that things will merge cleanly. 
I figure I can add a follow on PR with the addition of the `TabletFile` interface if/when this is merged since we can't chain PRs.
The original comment I made that was the basis of this is here: https://github.com/apache/accumulo/pull/3417#issuecomment-1557160881
> Rename TabletFile to ReferencedTabletFile

- core/src/main/java/org/apache/accumulo/core/file/DispatchingFileFactory.java
- core/src/main/java/org/apache/accumulo/core/file/FileOperations.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/RFileOperations.java
- core/src/main/java/org/apache/accumulo/core/logging/TabletLogger.java
- core/src/main/java/org/apache/accumulo/core/metadata/AbstractTabletFile.java
- core/src/main/java/org/apache/accumulo/core/metadata/TabletFile.java
- server/base/src/main/java/org/apache/accumulo/server/util/FileUtil.java
- test/src/main/java/org/apache/accumulo/test/performance/scan/CollectTabletStats.java
This is a follow on to #3449 and adds a new `TabletFile` interface that can be used instead of having to use the abstract class `AbstractTabletFile` everywhere.
> Add a new TabletFile interface

- core/src/main/java/org/apache/accumulo/core/conf/cluster/ClusterConfigParser.java
- core/src/test/java/org/apache/accumulo/core/conf/cluster/ClusterConfigParserTest.java
- core/src/test/resources/org/apache/accumulo/core/conf/cluster/bad-cluster.yaml
Parsing of the cluster.yaml file would ignore unrecognized config keys before this changes.  After this change it should throw an exception.
> fail when unknown config seen in cluster.yaml

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/PrepBulkImport.java
Before this change bulk import files ended up with a name like BULK_IMPORT000008h.rf after this change the name would be I000008h.rf instead.
> fixes bulk import filename prefix

- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
The change updates TabletGroupWatcher to remove servers being shutdown from being sent as candidates for assignment. There was previous logic (e.g. v1.10) that filtered the servers being shutdown from being included in the candidate list. 
Verified that on t-server shutdown the tablets are unloaded and assigned to a different host (with HostRegexTableLoadBalancer).
```
$> bin/accumulo admin stop localhost:9997
...
[manager.EventCoordinator] INFO : tablet 1;20230601_1728;20230601_1727 was unloaded from localhost:9997
...
[balancer.HostRegexTableLoadBalancer] DEBUG: Sending 40 tablets to balancer for table test_1 for assignment 
within tservers [localhost:10000[10001cc843d0007], localhost:10003[10001cc843d000a],
localhost:10004[10001cc843d000b], localhost:10005[10001cc843d000c]]
```
Closes …
> TabletGroupWatcher update to handle servers being shutdown

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitIT.java
This commit fixes a bug where a bulk import into a tablet that could not split would leave the tablet in bad state where it could not compact. The cause of the bug was the split code calling Tablet.initiateClose() which closed the tablets compactable object.  Then split code would decided it did not want to close the tablet and reset Tablet.closeState to OPEN, however the compactable object would be left closed.
This bug existed before #3249, however the changes in #3249 exposed a reliable path to the bug via bulk import.  Before #3249 I suspect the only path to access the bug was a race conditions where an unsplittable file was added at just the right time while the split code was running.
This particular bug with the closing of the compacatable and subsequent reopening of the tablet …
> fixes bug where bulk import could cause compcation to hang

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/css/screen.css
Small caps might look nicer, but it's harder to read and can make some case-sensitive items to appear to be upper case when they are lower. This is especially important for table names.
This was identified as a potential problem in https://github.com/apache/accumulo/issues/3489#issuecomment-1590010243
> Don't use small-caps in monitor

- core/src/main/java/org/apache/accumulo/core/metadata/AbstractTabletFile.java
- core/src/main/java/org/apache/accumulo/core/metadata/ReferencedTabletFile.java
- core/src/main/java/org/apache/accumulo/core/metadata/StoredTabletFile.java
- core/src/main/java/org/apache/accumulo/core/metadata/UnreferencedTabletFile.java
This improves performance during GC cycles by about 3x because creating a `ReferencedTabletFile` does a lot of validation which can be slow due to the calls to Path.getParent() if there are several files created. Filename validation was also removed from the constructor as well to further improve performance. This PR is a follow on to #3501 for #3500 in main.
Removing/delaying the validation checks should be safe because a `StoredTabletFile` references an existing Tablet file that was already stored in Metadata so the Path has already been validated before. Also, the `ReferencedTabletFile` is not needed often so it makes sense to delay the creation/validation until it's actually needed.
It turns out that the refactoring I just did in #3417 made this super easy because the bottleneck is …
> StoredTabletFile should lazy load ReferencedTabletFile

- test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java
This PR adds a suggested additional test for the setting/getting of TabletHostingGoals in TableOperationsImpl.java.
Specifically, the new tests verifies that when a table that already contains mixed TabletHostingGoals splits further, the new splits retain the hostingGoal of the tablet from which they were split. The new test, testGetHostingGoals_StaggeredSplits, does the following:
- create table
- add split 'm'
- set the hostingGoal of the last tablet to ALWAYS, leaving the first tablet with the default ONDEMAND
- add additional splits 'd' and 's'
- verify the first two tablets now have a hostingGoal of ONDEMAND
- verify the last two tablets, which were split from an existing tablet with ALWAYS as the goal, both have a goal of ALWAYS
The additional test was suggested in #3340
> Verify hostingGoals in table with mixed goals

- core/src/main/java/org/apache/accumulo/core/metrics/MetricsProducer.java
The major compaction stuck metric is currently showing up as `accumulo.compactormajc.stuck`.
This commit fixes the metric prefix format so the metric is reported correctly as `accumulo.compactor.majc.stuck`
> Fix the compactor prefix format

- server/base/src/main/java/org/apache/accumulo/server/mem/LowMemoryDetector.java
- test/src/main/java/org/apache/accumulo/test/functional/MemoryFreeingIterator.java
- test/src/main/java/org/apache/accumulo/test/functional/MemoryStarvedMajCIT.java
- test/src/main/java/org/apache/accumulo/test/functional/MemoryStarvedMinCIT.java
- test/src/main/java/org/apache/accumulo/test/functional/MemoryStarvedScanIT.java
- test/src/main/java/org/apache/accumulo/test/util/Wait.java
Fix low memory detector to clear/proceed when memory is available.
Update memory calculation to account for JVM resizing.
Update tests.
The low memory detector metric test(s) reveled an issue with the method that low memory detector was calculating free memory and also would clear the low memory flag without checking that memory was available.  The previous tests were passing because the low memory flag would clear, not that memory was available.  This PR fixes both the low memory detector flag set / reset issue and improves the tests to free memory in the low memory condition.
- resolves issue #3372 
- replaces PR #3384
> fix low memory detector and test updates

- server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java
- server/base/src/main/java/org/apache/accumulo/server/conf/ZooBasedConfiguration.java
* Simplify ZooBasedConfiguration's implementation of isPropertySet, and
* Remove TableConfiguration's redundant implementation, as it's the same as its super class (it just didn't look the same until it was simplified)
> Simplify isPropertySet and remove redundant code

- core/src/main/java/org/apache/accumulo/core/metadata/StoredTabletFile.java
A validation method was added as part of #2688 but is not used anywhere so this removes it.
This targets 2.1 but I could change the PR to be based on main instead but I think it makes sense to clean it up from 2.1 as well since it's not actually called.
> Remove unused validate method in StoredTabletFile

- server/gc/src/main/java/org/apache/accumulo/gc/GCRun.java
This is an optimization that was made in #3501 that was unrelated to the lazy evaluation.
> avoids indirection for normally empty scans in GC ref stream

- core/src/main/java/org/apache/accumulo/core/metadata/ScanServerRefTabletFile.java
This optimizes the Path creation and prevents a regex validation.
This closes #3557
> Update ScanServerRefTabletFile to create Path with a URI

- server/base/src/main/java/org/apache/accumulo/server/compaction/CompactionPluginUtils.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
Any compaction initiated in the manager should now execute a compaction
configurer plugin if its set on the table.
Fixes #3468
Marking this PR as draft because it includes commits from #3513.   Once #3513 is merged can take this out of draft.
> Execute compaction configurer plugin set on table

- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/InternalCompactionExecutor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/CompactionExecutorsMetrics.java
* Use more specific AutoCloseable type for metrics closer, since it doesn't thrown exceptions, and there's no point in forcing the caller to handle them because the super-class has `throws Exception` that this one doesn't use
* Narrow the catch block on compaction failures to handle only RuntimeExceptions, since it can't throw any checked exceptions
I noticed the opportunity to make these tiny improvements after seeing the wide net `catch (Exception e)` statements while reviewing #3555
> Remove unneeded handling of exceptions not thrown

- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/InternalCompactionExecutor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/tablet/CompactableImplFileManagerTest.java
- test/src/main/java/org/apache/accumulo/test/TestIngest.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction4_IT.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ErrorThrowingIterator.java
- test/src/main/java/org/apache/accumulo/test/functional/ReadWriteIT.java
When a user compaction failed CompactionManager.completed
was not called with a null output file to unreserve the compaction
files and the compactable was not put on the queue for recheck.
Fixes #3553
> User compaction not retried after failure

- server/tserver/src/main/java/org/apache/accumulo/tserver/session/ScanSession.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/Session.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java
This is a potential fix for #3512.  It ensures that when a sesssions cleanup method returns false that cleanup will be attempted again later.
> ensures sessions are always cleaned up

- core/src/main/java/org/apache/accumulo/core/client/mapred/AccumuloOutputFormat.java
- core/src/main/java/org/apache/accumulo/core/client/mapreduce/AccumuloOutputFormat.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapred/AccumuloRecordWriter.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/AccumuloRecordWriter.java
In profiling of an Accumulo map reduce job it was noticed that a good bit of time was spent calling toString on a Text object to check if it was empty. This commit avoids the toString() call and instead checks the text length.
> avoids calling toString on Text for isEmpty

- server/base/src/main/java/org/apache/accumulo/server/conf/util/ZooPropEditor.java
Updated zoo-prop-editor to provide feedback using log statements and improved exception messages as mentioned in PR #3445
- adds log statements showing success on set
- improved exception messages.
- command exit with -1 on errors.
> add feedback to zoo-prop-editor

- shell/src/main/java/org/apache/accumulo/shell/commands/CreateNamespaceCommand.java
- shell/src/main/java/org/apache/accumulo/shell/commands/CreateTableCommand.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellCreateNamespaceIT.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellCreateTableIT.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java
Currently the copy-configuration option in createnamespace and createtable commands copy the entire effective configuration into the target.  This PR adds a flag to ignore the parent configuration.  This prevents the copied properties from masking properties higher in the hierarchy (see issue #3233)
- adds --exclude-parent as an option to --copy-config in createnamespace and createtable shell commands.
- adds IT tests
- uses NewTableConfiguration in create table command
- minor checkstyle fixes
> Fixes 3233. Add copy-properties option for createnamespace and createtable shell commands

- core/src/main/java/org/apache/accumulo/core/file/blockfile/impl/CachableBlockFile.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/RFile.java
Added parameter to LocalityGroupReader.reset to indicate if method was being called due to an exception. When true, reset then calls CachableBlockFile.Reader.close(). Also modified that close method to set an AtomicReference to null.
Closes #3617
> Close Reader when IOException thrown in LocalityGroupReader

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Scanner.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/TabletBase.java
Rfiles were not reused when IOException happened, but were reused when a runtime exception happened.  This changes the code to not reuse when a runtime exception happens.
See #3617
> Avoids reusing rfile objects when runtime exception happens

- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java
While working on metadata code in the elasticity branch, I realized it would be good to sync ZK before reading the root tablet metadata.  Did not want to make that change only in the elasticity branch and it seemed like a good change for 2.1.2.
> syncs ZK before reading root tablet metadata

- core/src/main/java/org/apache/accumulo/core/util/ConfigurationImpl.java
- core/src/test/java/org/apache/accumulo/core/util/ConfigurationImplTest.java
- server/base/src/main/java/org/apache/accumulo/server/ServiceEnvironmentImpl.java
- server/base/src/test/java/org/apache/accumulo/server/ServiceEnvironmentImplTest.java
ConfigurationImpl which is provided to plugin impl cached a snapshot of custom props indefinitely.  However other props were not cached in this way.  This change removes the indefinited caching of custom props.
> Avoid caching a snapshot of custom props

- core/src/test/java/org/apache/accumulo/core/util/ConfigurationImplTest.java
This is a follow up to #3588.  Realized that ConfigurationCopy supported the Deriver that ConfigrationImpl uses to detect changes, so added unit test that leverage this.
> tests custom prop changes are seen

- test/src/main/java/org/apache/accumulo/test/functional/WatchTheWatchCountIT.java
Fixes recent CI failure were expected ZK watch count was *less* than expected values.
> Adjust expected ZK watcher count (lower) in IT

- server/base/src/main/java/org/apache/accumulo/server/conf/ServerConfigurationFactory.java
Using a cache instead of a map to ensure that configs are eventually cleaned up on deletions. The issue was raised in PR #3588
> Replace ConcurrentHashMap with Caffine cache for configs

- test/src/main/java/org/apache/accumulo/test/functional/ManagerAssignmentIT.java
- Increase the waitFor timeout to 60 seconds (from default 30.)
- IDE checkstyle suggestions.
> Increase timeouts in ManagerAssignmentIT to address CI failures

- core/src/main/java/org/apache/accumulo/core/metadata/schema/DataFileValue.java
- test/src/main/java/org/apache/accumulo/test/ScanConsistencyIT.java
The IT ensures that when there are concurrent writes, scans, and table operations that scans always see any data written before the scan started.
> Adds IT that verifies scans see data written by concurrent writers

- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
- core/src/test/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlannerTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
The DefaultCompactionPlanner would only emit one compaction job per tablet.  This commit changes it to be able to emit multiple compactions for a single tablet as long as doing so is optimal w.r.t. to the compaction ratio.
> Makes DefaultCompactionPlanner emit multiple jobs
