apache/accumulo

- shell/src/main/java/org/apache/accumulo/shell/commands/CreateNamespaceCommand.java
- shell/src/main/java/org/apache/accumulo/shell/commands/CreateTableCommand.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellCreateNamespaceIT.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellCreateTableIT.java
- Change command option from `exclude-parent` to `exclude-parent-properties` for clarity.
- clarify command description present to uses
- comment clean-up
From additional comment in PR #3562 made after merge.
> make option exclude-parent-properties, other minor clean-up

- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionTestUtils.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_1_IT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_2_IT.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
Removed tests from CompactionIT that had a matching test in `ExternalCompaction*IT`. Updated tests in `ExternalCompaction*IT` that were missing some recent updates in CompactionIT.
> Deduplicate compaction tests

- shell/src/main/java/org/apache/accumulo/shell/commands/ConfigCommand.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellIT.java
Adds a prompt y/n when setting a deprecated property with the shell.  Also adds --force as an option to bypass the prompt.
Working with a user, we set a deprecated property - the consequence was that the tserver logs started to be spammed with warning that a deprecated property was set. If we had not been actively monitoring the monitor logs it likely would have gone unnoticed for quite a while.  The noisy log behavior has been stated as desirable. With this change, shell users need to consciously set the deprecated property by answering a y/n prompt, or using the --force option.
The prompt looks like 
```
Trying to set deprecated property `tserver.compaction.major.concurrent.max` continue (yes|no)? no
2023-08-08T17:56:11,361 [shell.Shell] ERROR: …
```
> Prevent setting deprecated properties in the shell unless forced

- core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- shell/src/main/java/org/apache/accumulo/shell/commands/GetTabletHostingGoalCommand.java
Remove the `getTabletHostingGoal` method from `TableOperations` as the information can now be retrieved with the more robust `getTabletInformation` method.
The shell command, `getgoals`, still works as before, but the `GetTabletHostingGoalCommand` was updated to use the new `getTabletInformation` method to retrieve the necessary information rather than the removed `getTabletHostingGoal` method.
> Remove getTabletHostingGoal method from TableOperations

- core/src/main/java/org/apache/accumulo/core/conf/ConfigurationTypeHelper.java
- server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/MinorCompactionTask.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/MinorCompactor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTablet2IT.java
- test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java
Prior to this change Tablet.initiateClose would close the compactable, wait for the current minor compaction to finish, and then kick off another minor compaction. In the case where minor compactions are failing, the compactable will get closed and the call to wait for the current minor compaction to finish will hang indefinitely leaving the Tablet in a half-closed state. Tablet.initiateClose is called when either the TabletServer is closing the Tablet (due to migration or shutdown) or on a Tablet split. Therefore, a failing minor compaction will prevent Tablet migration and split or normal TabletServer shutdown.
This change adds some logic at the start of Tablet.initiateClose to try and detect a currently or previously failing minor compaction. In these cases an exception is thrown …
> Attempt to prevent half-closed Tablet due to failing minc

- test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java
This test was already removed as part of b51bab1 as a follow on to https://github.com/apache/accumulo/pull/3456 but came back in the latest merge of 2.1 into main.
This test is now causing a build failure in main.
> Remove old/broken shell fate test

- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/AccumuloInputFormatIT.java
- test/src/main/java/org/apache/accumulo/test/functional/TabletIT.java
- test/src/main/java/org/apache/accumulo/test/mapreduce/AccumuloInputFormatIT.java
Fix the incorrect use of assert statements in test code when a JUnit assertTrue is the appropriate solution to resolve the error caught by the errorprone compiler.
This issue was only seen on the 2.1 branch after bumping the version of errorprone to the same version as in the main branch. The issue still exists on the main branch, but for some reason, erorrprone doesn't flag on it in that branch. It was seen after creating 2.1.2-rc1, but is not important enough to warrant creating an rc2. If rc1 fails the vote, this can be included in rc2.
This PR does not replace all assert statements, only those that were obviously incorrect, which was enough to make the errorprone check pass locally. This does not change assert statements in non-test code, and does not change them in the test-adjacent …
> Fix bad assert statements in tests

- assemble/bin/accumulo
- assemble/conf/accumulo-env.sh
- server/base/src/main/scripts/generate-protobuf.sh
* Update the interpretation of the `ACCUMULO_JAVA_PREFIX` option in `accumulo-env.sh` so it can be passed as an array
* Add a check to help the user use the variable correctly, and add comments to explain
* Also fix shellcheck errors in generate-protobuf.sh
This fixes #3697
> Allow ACCUMULO_JAVA_PREFIX to be an array

- server/base/src/test/java/org/apache/accumulo/server/util/fateCommand/SummaryReportTest.java
I am working on research that investigates test smell refactoring in which we identify alternative implementations of test cases, study how commonly used these refactorings are, and assess how acceptable they are in practice.
The first smell is when inappropriate assertions are used, while there exist better alternatives. For example, in [SummaryReportTest.java](https://github.com/apache/accumulo/commit/a657b6ee75d7c6a0556d0059dc3bc1317594d34b#diff-d0c6de0d5f496d76d1c71a7b39cb5ddc4060d8c68ddcf9893fd1f7fd5395d626), I refactored `assertTrue(report.getReportTime() != 0);` using `assertNotEquals` instead.
The second smell is known as _Assertion Roulette_, where a test method has multiple asserts without explanatory messages, which can sometimes make it difficult to identify which assert has …
> Refactor assertTrue(!=) with assertNotEquals & Add explanatory messages

- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooReader.java
- core/src/test/java/org/apache/accumulo/core/fate/zookeeper/ZooReaderWriterTest.java
Always use the retry backoff when always retrying. This fixes an issue where an "always retry" condition is triggered, it will not barrage ZooKeeper with repeated immediate retries.
This fixes #3718
> Always use retry backoff in ZooReader(Writer)

- shell/src/main/java/org/apache/accumulo/shell/Shell.java
This PR adds presents additional information to the shell when the re-authentication is automatically performed using the value from accumulo-client.properties.
Once merged, the update will be applied to 3.x where it corrects an situation where an endless loop can be triggered when attempting re-authentication if the accumulo-client.properties file password is altered after initial setup.
See #3495 for more detail.
> Adjust shell to indicate how re-authtication occurs

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/base/src/main/java/org/apache/accumulo/server/tablets/UniqueNameAllocator.java
Update the UniqueNameAllocator to support a configurable filename range size. The default values match what was previously there so there is no behavior change unless you override the properties.
> Allow configurable name allocations

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/base/src/main/java/org/apache/accumulo/server/tablets/UniqueNameAllocator.java
* Replace "base" and "jitter" concepts, which are confusing and require defining, with explicit "min" and "max" values for the configuration options for UniqueNameAllocator.
* Adjust formatting of Property descriptions so they don't excessively exceed our line length style.
* Reorder property names so RPC props aren't split up and stay together instead.
This fixes #3722
> Improve the UniqueNameAllocator configurability

- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchReaderIterator.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java
- core/src/main/java/org/apache/accumulo/core/rpc/AccumuloTFramedTransportFactory.java
- core/src/main/java/org/apache/accumulo/core/rpc/ThriftUtil.java
- core/src/test/java/org/apache/accumulo/core/rpc/ThriftUtilTest.java
- test/pom.xml
- test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java
- test/src/main/java/org/apache/accumulo/test/util/Wait.java
Use a custom TFramedTransport.Factory implementation so that when getTransport is called, the frame and message size are set on the underlying configuration.
Fixes #3731
> Use custom Transport Factory to set Transport message and frame size

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- test/src/main/java/org/apache/accumulo/test/functional/ZombieTServer.java
- test/src/main/java/org/apache/accumulo/test/performance/NullTserver.java
> Added property to configure TCP backlog for Thrift server sockets

- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/Compactable.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/InternalCompactionExecutor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
- test/src/main/java/org/apache/accumulo/test/compaction/CompactionConfigChangeIT.java
Fixes a bug where a change in compaction config that deleted a compaction thread pool would leave any tablets compacting on that thread pool in a bad state. The problem was caused by shutdownNow being called on the thread pool which could cause an interrupted exception during commiting the compaction.
This change allows compactions running on the thread pool to complete while canceling any compactions queued on the thread pool.
fixes #3749
> fixes bug w/ deletion of compaction thread pool

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
The tablet code was structured in such a way that an exception could leave a lock related to write ahead logs locked forever.  This change does two things to fix this.
* In Tablet.beginClearingUnusedLogs() the lock is released on exception.
* In DatafileManager.bringMinorCompactionOnline() the call to Tablet.beginClearingUnusedLogs() is moved to be immediately before the try{}finally{} that releases the lock.
> fixes bug where lock is not unlocked on exception

- server/gc/src/main/java/org/apache/accumulo/gc/GCRun.java
<details>
<summary>Original Ticket Contents</summary>
This change allows easy logging targeting by putting all file deletion actions into a separate logger.
* Adds a separate file logger to GCRun to allow for easy filtering of file deletion log messages.
* Fixes #3744 by changing how the standard logger is created.
* Moves datalevel to the end of the logger name. 
This approach was chosen because log4j2 regexFilters only work against the message body.
That solution would work as long as log messages were written in a specific format with no validation.
By using a completely separate logger, the contents of the log message don't matter.
Instead, as long as the correct logger is used, the contents can be targeted fairly easily.
This logger is created under the existing GCRun prefix, so any …
> Add Message Prefix for File deletion actions in GCRun

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Reverts a validation to prevent deadlock that was being covered by the code path to close a tablet.  #3759 was opened to investigate this. This commit removes the new check as the code path that could cause deadlock has existed for a long time and may never actually cause deadlock.
fixes #3757
> reverts changes from #3747 that caused tablet split to fail

- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectionAlgorithm.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/gc/src/test/java/org/apache/accumulo/gc/GarbageCollectionTest.java
Add validation that dir and prevRow are present when the gc is scanning for in-use file references.  If a row is processed and the dir and prevRow entries are not present, an IllegalStateException is throw to abort the current gc cycle.
This is to help detect / prevent partial metadata scans from missing file references that are in use.
Fixes #3696 for 1.10
> add check to gc to validate metadata scan is complete

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/gc/GcCandidate.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/RootGcCandidates.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
- server/base/src/main/java/org/apache/accumulo/server/util/ListVolumesUsed.java
- server/gc/src/main/java/org/apache/accumulo/gc/GCRun.java
- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectionAlgorithm.java
- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectionEnvironment.java
- server/gc/src/test/java/org/apache/accumulo/gc/GarbageCollectionTest.java
- server/gc/src/test/java/org/apache/accumulo/gc/SimpleGarbageCollectorTest.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorIT.java
The current GC behavior does not remove InUse candidates and would spend subsequent runs processing and discarding the same InUse Candidates in each batch size.
This is inefficient and can lead to unnecessarily long GC run times in high-load system environments.
This change adds the ability to remove Garbage Collection Candidates that still have matching tablet references.
A new class called GcCandidate and a GcCandidateType Enum have been added. The new GcCandidate type values are "VALID, INUSE, and INVALID". 
A new property has been added called `GC_REMOVE_IN_USE_CANDIDATES` which controls if the garbage collector deletes the InUse candidates.
This property is disabled by default to ensure that existing behavior is not changed. 
Additional tests have been added to the GarbageCollectorIT …
> Remove GC candidates found to still be referenced

- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java
- core/src/main/thrift-gen-java/org/apache/accumulo/core/tabletserver/thrift/TabletClientService.java
- core/src/main/thrift/tabletserver.thrift
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java
- test/src/main/java/org/apache/accumulo/test/performance/NullTserver.java
This commit is a follow up to #3733. When a failure happens on a batch write, the batch writer will continually try to close the write session. Each time it tried to close the session it created a thread that may wait on the tserver trying to reserve the session which takes up a server side thrift thread pool slot.  After the 2 min default connection timeout it will try to close the session again, creating another thread on the tserver that is trying to close the session (the previous threads are still there).  This will only happen when something is preventing the the session from closing.  So in the case where many clients are doing this it has the potential to make an existing problem worse.
This change introduces a new tablet server RPC named cancelUpdate. The new method does not try …
> avoids creating server side threads when canceling failed write

- test/src/main/java/org/apache/accumulo/test/functional/FileMetadataIT.java
- test/src/main/java/org/apache/accumulo/test/functional/MergeIT.java
Updates ITs to make sure that compactions will not run which could cause non-deterministic failures when verifying files and counts in the metadata table. This addresses part of #3766
> Update no-chop merge tests to disable compaction

- server/base/src/main/java/org/apache/accumulo/server/AccumuloDataVersion.java
- server/base/src/test/java/org/apache/accumulo/server/ServerContextTest.java
Adds a new Accumulo data version (12) to reflect no-chop changes that encode the metadata file entries in json to support fencing.  
The json file entries are incompatible with metadata file entries prior to 3.1.  Until the upgrade code is implemented trying to upgrade from a previous version will fail.  This change makes it explicit why.
For example, with this change, trying to upgrade from a 2.1.x will include the following in the manager log. 
```
2023-09-26T14:34:03,211 [start.Main] ERROR: Thread 'manager' died.
java.lang.IllegalStateException: This version of accumulo (3.1.0-SNAPSHOT) is not compatible with files stored using data version 10. Please upgrade from 3.1.0 or later.
at org.apache.accumulo.server.ServerContext.ensureDataVersionCompatible(ServerContext.java:308) …
```
> New data version to support no-chop changes, disable upgrade

- pom.xml
This supersedes #1438  
Note: This doesn't currently work, because of bugs in maven-javadoc-plugin which seem to force the use of a module path, even though our dependencies don't all have modules, and we're not explicitly using modules. The maven-javadoc-plugin seems to require that we go full modular or not at all... no middle ground is apparently available.
Edit: it works now with maven-javadoc-plugin 3.6.0
> Apply automatic module names

- core/src/main/java/org/apache/accumulo/core/lock/ServiceLockData.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadata.java
- core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/ExternalCompactionUtil.java
- core/src/test/java/org/apache/accumulo/core/lock/ServiceLockDataTest.java
- server/base/src/main/java/org/apache/accumulo/server/manager/LiveTServerSet.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
* Simplify ServiceLockData's if conditions in methods that return null
* Ensure ServiceLockData.getAddress() returns null when .getAddressString() returns null
* Handle null toString() in ServiceLockData.equals() using Objects.equals()
* Simplify TabletMetadata.checkServer(), TServerClient.getTabletServerConnection(), ExternalCompactionUtil.findCompactionCoordinator(), LiveTServerSet.checkServer(), and Monitor.fetchGcStatus() by using Optional.map(), Optional.ifPresent(), and Optional.orElse(null)
* Improve Monitor.fetchGcStatus() by short-circuiting the warning and returning null results when the address is null, rather than wait for an exception to be thrown while trying to connect to the service using a null address
* Update ServiceLockDataTest to ensure getAddress() returns null when …
> Fix use of ServiceLockData Optional and nulls

- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchReaderIterator.java
This commit partially reverts b1b2557f949e9212a1b1ca9b65f2d66c01a69edb from #3737, to restore the previous infinite retry behavior when an EOFException occurs in the transport. While this EOFException can be an indicator of a fatal exception that should not be retried, it also occurs during transient network failures, where a retry should occur. It is not possible to easily detect which of these two cases is ocurring. Since transient network failures are routine, and the fatal exception that caused the issue that #3737 tried to address has a workaround via configuration, this commit restores the previous behavior that assumes the exception is caused by a transient issue.
This fixes #3762
This fixes the issue in #3762, where the ManagerRepairsDualAssignmentIT intentionally triggered a …
> Revert #3737's EOFException changes

- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
Cloning tables was not copying the hosting goal which left the cloned table unscannable. Changes clone table to copy hosting goal.
> Fixes cloning tables

- test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java
Multiple tests in ShellServerIT only ran when their table id was 1 or 2. This commit updates the test to run with any table id.
> fixes multiple tests in ShellServerIT

- core/src/main/java/org/apache/accumulo/core/metadata/schema/MetadataTime.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ConditionalTabletMutatorImpl.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/LoadFiles.java
- test/src/main/java/org/apache/accumulo/test/functional/AmpleConditionalWriterIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkNewIT.java
Implements setting time for unhosted tablets for bulk imports.  Setting time for a bulk import will fail if the tablet is hosted.  Before this commit it always failed.
see #3354
> partially implements setting time for bulk imports

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientTabletCacheImpl.java
The change in #3429 modified ClientTabletCache so that it would preload Tablets for Scanners. It appears this change may have caused the test in #3809 to fail. I modified the comparison of the range to the tablet end key using the same logic that ThriftScanner uses and it fixed the test.
Fixes #3809
> Modify ClientTabletCacheImpl.findExtentsToHost end key comparison

- core/src/main/java/org/apache/accumulo/core/util/compaction/ExternalCompactionUtil.java
> Modified ExternalCompactionUtil.findCompactionCoordinator to use ZooCache

- pom.xml
- server/tserver/src/main/java/org/apache/accumulo/tserver/AssignmentHandler.java
- test/pom.xml
- test/src/main/java/org/apache/accumulo/test/ScanServerIT.java
In #3425 the Manager was modified to set the TabletGoalState to UNASSIGNED for Tablets that have an OperationId. This changes the AssignmentHandler to return false in the same condition. This will cause both the TabletServer and the ScanServer to not host a Tablet when there is an OperationId.
Closes #3741
> Modified AssignmentHandler to return false for Tablets with OpId

- test/src/main/java/org/apache/accumulo/test/shell/MockShell.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java
Some tests that used the shell scan command in testing file imports were passing because the shell output contained the input command. This PR adds a random value that is used with the expected data to verify that the values returned are tested and that they do not contain text in the command.
Also fixes check style warnings seen while making these changes. (mostly removing un-thrown exceptions)
Fixes #3806
> improve scan output checks with unique values

- server/base/src/main/java/org/apache/accumulo/server/compaction/CompactionPluginUtils.java
Compaction selection functionality that opened files was not implemented because it opens user files in the manager.  This change implements the functionality inorder to get integration test passing.  There is already an open issue about finding a better way to do this. See #3526
> Implements missing compacton selection functionality

- test/src/main/java/org/apache/accumulo/test/functional/ManagerAssignmentIT.java
Revert change introduced in #3654 to ManagerAssignmentIT for an extra tablet being brought online, something that was introduced in #3429 and fixed in #3812.
> Fix off-by-one in ManagerAssignmentIT test

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- test/src/main/java/org/apache/accumulo/test/functional/MonitorSslIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ReadWriteIT.java
This also adds TLSv1.3 to the list of accepted protocols for the RPC server and Monitor server, while still supporting TLSv1.2.
I didn't add any extra tests as all of the existing SSL/TLS testing should provide sufficient coverage.
This closes #3786
> Bump default Accumulo RPC client to TLSv1.3

- server/compactor/pom.xml
- start/pom.xml
After the changes in #3817 junit is no longer a dependency for the start and compactor modules and this causes errors when running int tests as failsafe gives an error because Junit is not a dependency.
Adding back junit as a dependency also fails as there are no unit tests to run currently so this disables the failsafe plugin inside the modules. It can be re-enabled in the future if tests are added.
> Disable failsafe plugin in start and compactor modules

- core/src/main/java/org/apache/accumulo/core/metadata/StoredTabletFile.java
This commit adds two new methods to initialize a StoredTabletFile with just a path or a URI and will default to an infinite range which makes it a little bit more concise in the code when not needing to provide a range.
> Add additional initializer methods to StoredTabletFile

- test/src/main/java/org/apache/accumulo/test/functional/AmpleConditionalWriterIT.java
After the changes with no-chop merge the StoredTabletFile metadata is now a json string that includes a range along with the path. This change updates the test to serialize the path into the new format with an infinite range.
This closes #3831
> Update AmpleConditionalWriteIT to use new file metadata format

- core/src/main/java/org/apache/accumulo/core/metadata/CompactableFileImpl.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/ReferencedTabletFileTest.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/TabletMetadataTest.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
- server/base/src/test/java/org/apache/accumulo/server/constraints/MetadataConstraintsTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/LoadFiles.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/tablet/CompactableImplFileManagerTest.java
- test/src/main/java/org/apache/accumulo/test/CloneIT.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorIT.java
Makes use of the new methods added in #3836. Also cleans up a bit more of some usage of `StoredTabletFile`. Namely I converted some usage of the `.of(URI path)` method to `.of(Path path)` since the former converts to `Path` anyways.
> Clean up some usage of StoredTabletFile

- shell/src/main/java/org/apache/accumulo/shell/commands/GetTabletHostingGoalCommand.java
- shell/src/main/java/org/apache/accumulo/shell/commands/SetTabletHostingGoalCommand.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java
Rename the setgoal and getgoal shell commands to sethostinggoal and gethostinggoal, respectively. This change is being made to provide more clarity as to what the commands are doing and make them less generic.
Several other instances if 'goal' were changed to 'hostinggoal' in order to add more clarity.
Closes #3800
> Rename setgoal/getgoal to sethostinggoal/gethostinggoal

- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/data/Mutation.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/CompactionDriver.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/LogSorter.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/logger/LogFileValue.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/logger/LogReader.java
- shell/src/main/java/org/apache/accumulo/shell/commands/GetAuthsCommand.java
* Fix various issues of improper conversion from byte arrays to String or vice versa where the charset was not specified explicitly, in order to standardize on the consistent use of UTF-8, so we don't have errors due to mismatches in decoding. This is particularly important in the serialization and deserialization of service lock data, which was being encoded inconsistently prior to this patch.
* Also avoid unnecessary conversion of Text to String in order to convert to bytes, especially since they may contain binary data. If they contain binary data, it will now be preserved. If the Text was constructed from a String and encoded as UTF-8 bytes, then the UTF-8 encoding will now be preserved, rather than converted to String type and then subsequently converted to bytes using the system's …
> Fix String-to-bytes and bytes-to-String for UTF-8

- core/src/main/java/org/apache/accumulo/core/data/Range.java
- core/src/main/java/org/apache/accumulo/core/file/BloomFilterLayer.java
- core/src/main/java/org/apache/accumulo/core/file/FileSKVIterator.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/MultiIndexIterator.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/RFile.java
- core/src/main/java/org/apache/accumulo/core/iteratorsImpl/system/SequenceFileIterator.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/AbstractRFileTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/MultiThreadedRFileTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/RFileTest.java
- server/base/src/main/java/org/apache/accumulo/server/util/FileUtil.java
- server/base/src/test/java/org/apache/accumulo/server/util/FileInfoTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
This commit changes FileSKVIterator getFirstKey and getLastKey methods to return the first and last row instead. These methods are only used for splits and in that case only the row is relevant. This was done because fenced RFiles will only return the row portion of a key when these methods are called (if the fencing is being enforced) so this keeps the API consistent.
This closes #3798
> Change getFirstKey/getLastKey to getFirstRow/getLastRow

- test/src/main/java/org/apache/accumulo/test/ComprehensiveIT.java
- test/src/main/java/org/apache/accumulo/test/functional/LocalityGroupIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ReadWriteIT.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellCreateNamespaceIT.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellCreateTableIT.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellIT.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java
This change adds a new security test to Comprehensive IT and moves some test from ReadWriteIT into comprehensive IT.  Each test in ReadWriteIT spins up a mini cluster, which takes a lot of time for really simple test.  Also remove the sunny tag from shell ITs as ComprehensiveIT now covers most of what thost test were covering, but using public API instead of shell.
> improves ComprehensiveIT and adjust sunny ITs

- test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java
A previous commit had corrected several tests in ShellServerIT where the tests would fail if the tableId was a value other than 1 or 2. The testGetHostingGoalCommand test failed to get that fix. This commit updates that IT test to handle tableId's of any value.
> Fix bug in testGetHostingGoalCommand test

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableExport/WriteExportFiles.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/PopulateMetadataTable.java
- test/src/main/java/org/apache/accumulo/test/ComprehensiveIT.java
Modified export table to write out the hosting goal. Modified import table to read the hosting goal or set it to a default if not seen. Also added setting and getting hosting goals to ComprehensiveIT
fixes #3850
> adds hosting goal support to import/export table

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
The tablet refresh code was comparing a tablet metdata object to itself. The intention was to compare the tablet metadata to the previous version of the tablet metadata.
> fixes bug in tablet refresh

- core/src/main/java/org/apache/accumulo/core/client/admin/compaction/CompactableFile.java
- core/src/main/java/org/apache/accumulo/core/metadata/CompactableFileImpl.java
Now that tablet files have an associated range, this information should be made available to compaction plugins.  Making this information available to plugins enable uses cases like selecting files with ranges for compaction. This commit makes that information avialable by adding a getRange method to CompactableFile
> adds range to compactable file

- core/src/main/java/org/apache/accumulo/core/metadata/schema/MetadataTime.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- test/src/main/java/org/apache/accumulo/test/functional/RestartIT.java
During write ahead log recovery the tablet server was trying to write a new file and require the tablets current location to be the tablet server.  However at that time the tablet server was the tablets future location and therefore the update failed.  This commit adust the expected location to be the future location during recovery.
> fixes tablet location checks in tabletserver

- core/src/main/java/org/apache/accumulo/core/clientImpl/RootClientTabletCache.java
When the root tablet had no location, writes to it were failing.
> fixes bug writing to root tablet

- pom.xml
This closes #3485 to update Jline past 3.21.0 to version 3.24.0.
Verified that stdout and stderr output is redirected to the desired files using uno and the following:
```
accumulo shell -e 'tables -np' 1>/tmp/ashell.stdout 2>/tmp/ashell.stderr
```
The output of the stdout file:
```
Loading configuration from [...]/fluo-uno/install/accumulo-2.1.3-SNAPSHOT/conf/accumulo-client.properties
accumulo.metadata
accumulo.replication
accumulo.root
tableA
tableB
tableC
tableD
```
The output of the stderr file:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jline.terminal.impl.exec.ExecTerminalProvider$ReflectionRedirectPipeCreator (file:[...]/fluo-uno/install/accumulo-2.1.3-SNAPSHOT/lib/jline-3.24.0.jar) to constructor …
```
> Fixes 3485. Update jline version to 3.24.0

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java
- fixes log incorrect number of parameters (TabletClientHandler.conditionalUpdate())
- simplifies method that always returned true (SessionManager.removeIfNotReserved))
- other small changes recommended by IDE.
This started by looking a synchronization issue of locking on a method parameter in SessionManager - not sure what should be done, but submitting these as a separate PR to keep them out of a PR that would have deeper implications.
> minor QA fixes

- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
- server/manager/src/main/java/org/apache/accumulo/manager/state/MergeStats.java
- server/manager/src/test/java/org/apache/accumulo/manager/state/MergeStatsTest.java
- test/src/main/java/org/apache/accumulo/test/manager/MergeStateIT.java
Add extra verification to make sure that no tablets that are merged contain any WALs to prevent losing data
This fixes #3845 for the 2.1 branch. For main there will be some slight modifications due to no-chopped merge but the fix is mostly going to be the same and I can fix conflicts on the merge.
> Make sure tablets with WALs are not merged

- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterControl.java
- test/src/main/java/org/apache/accumulo/test/functional/RestartIT.java
The call to Manager.shutdown does not stop the ScanServers and Compactors.
> Modify MiniAccumuloClusterControl.adminStopAll to stop sserver and compactor

- pom.xml
Bump ZooKeeper to 3.8.3 to address warnings about CVE-2023-44981
(Note: this CVE affects SASL-configured server deployments of ZK, not ZK client code, like how Accumulo uses it, but this removes the warning from GitHub about critical vulnerabilities in Accumulo, and in general, Accumulo tries to develop against the latest patched version of a particular release anyway.)
> Bump ZooKeeper for CVE-2023-44981

- server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletManagementIterator.java
- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/DeleteRows.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/MergeTablets.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/ReserveTablets.java
This commit updates the merge and delete rows FATE ops to verify that if tablets being processed do not have any wals
This closes #3845
This PR makes the following changes:
1. Modifies ReserveTablets FATE op to check that the tablets have no wals when reserving
2. Modifies `MergeTablets` and `DeleteRows` FATE ops to add verification that the tablets have no wals
3. Modifies `TabletManagementIterator` to return a tablet back for processing again by TGW if there's no location, an op id set and wals exist
4. Modifies `TabletGroupWatcher` to set the tablet goal to be hosted to bring a tablet online if wals exist and a fate id is also set
I have marked this as a draft for now because I believe these are all the changes needed but I wanted to explore adding a test or 2 if possible (maybe …
> Prevent merge/delete operations when wals exist

- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
There was a missing quote in the json in DefaultCompactionPlanner javadoc:
After adding the quote and adding a line:
> Fix errors in DefaultCompactionPlanner javadoc

- test/src/main/java/org/apache/accumulo/test/WaitForBalanceIT.java
It appears that Manager.waitForBalance may return and then the isBalanced method returns false. I think this is due to the fact that the current location for the Tablet is set in the TabletServer AssignmentHandler, which leaves a gap where
InstanceOperations.waitForBalance returns but the locations are not yet set.
> Fixes WaitForBalanceIT

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- test/src/main/java/org/apache/accumulo/test/functional/OnDemandTabletUnloadingIT.java
The previous logic used the ingest and scan rates and would say a Tablet was not in use when the rates were zero. However, due to a smoothing function on the Rate class, this may not happen or would take a really long time. The logic was modified to use the internal Tablet activeScans and writesInProgress variables to determine if activity was currently happening instead of using the Rate-based metrics.
Fixes #3907
> Replace logic for determining whether a Tablet is in use

- core/src/main/thrift-gen-java/org/apache/accumulo/core/manager/thrift/TableInfo.java
- core/src/main/thrift/manager.thrift
- server/base/src/main/java/org/apache/accumulo/server/util/TableInfoUtil.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/statistics/StatisticsResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tables/CompactionsTypes.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tables/TableInformation.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tservers/TabletServerInformation.java
- server/monitor/src/test/java/org/apache/accumulo/monitor/rest/tservers/TabletServerInformationTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- test/src/main/java/org/apache/accumulo/test/GetManagerStats.java
> Removed TableInfo.majors field

- test/src/main/java/org/apache/accumulo/test/functional/FunctionalTestUtils.java
- test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java
- test/src/main/java/org/apache/accumulo/test/lock/ServiceLockIT.java
This PR improves the messages logged when an assert fails. 
[`HalfClosedTablet2IT.testInvalidContextCausesVolumeChooserFailure` ](https://ci-builds.apache.org/job/Accumulo/job/main/org.apache.accumulo$accumulo-test/593/testReport/junit/org.apache.accumulo.test.functional/HalfClosedTablet2IT/testInvalidContextCausesVolumeChooserFailure/)and [`ServiceLockIT.testLockParallel`](https://ci-builds.apache.org/job/Accumulo/job/main/org.apache.accumulo$accumulo-test/594/testReport/junit/org.apache.accumulo.test.lock/ServiceLockIT/testLockParallel/) have both seen failures in recent builds (linked). I have not looked into what might be causing these failures yet but figured this is a good first step which might help if they fail again.
> Improve logging of failing tests

- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/AsyncConditionalTabletsMutatorImpl.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/CleanUp.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/DeleteTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/PreDeleteTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/ReserveTablets.java
- test/src/main/java/org/apache/accumulo/test/functional/AmpleConditionalWriterIT.java
Updates the delete table fate operation to use conditional mutations. Also introduces a new mechanism in Ample for processing conditional mutations that does not buffer everything in memory.  This avoid buffering large amounts of tablet metadata in memory when deleting a large table.  The IT that creates 1 million splits in a table and deletes it passes with these changes.
> updates delete table to use conditional muations

- test/src/main/java/org/apache/accumulo/test/functional/TabletManagementIteratorIT.java
This updates tests in `TabletManagementIteratorIT` to verify that the iterator properly detects tablets needing attention if WALs exist on tablets that are part of a merge operation. It also will test that if op type is `DELETING` that the tablet does not care if there are WALs.
This PR only updates the tests in TabletManagementIteratorIT and doesn't try and do anything with TGW because after the refactoring in #3904 both the iterator and TGW share the same code for checking the goal state (where the WAL checks are done)
However, another possible follow on test improvement would be to create a test for the `TabletGoalState` class where all the logic was refactored to inside of compute() to test the different cases for computing the resulting state. This could likely just be a normal unit …
> Update TabletManagementIteratorIT for merge and wal checks

- core/src/main/java/org/apache/accumulo/core/metadata/schema/RootTabletMetadata.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/UpgraderDeprecatedConstants.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/RootTabletMetadataTest.java
- server/base/src/main/java/org/apache/accumulo/server/AccumuloDataVersion.java
- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
- server/base/src/test/java/org/apache/accumulo/server/ServerContextTest.java
- server/manager/pom.xml
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/UpgradeCoordinator.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader11to12.java
- server/manager/src/test/java/org/apache/accumulo/manager/upgrade/Upgrader11to12Test.java
Resolves #3768.  Completes all three sub-tasks:
- modifies StoredTabletFile references to new json encoding
- removed obsolete references that may contain old file reference format
- chopped references
- external compaction references.
The obsolete references are not normally expected during an upgrade.  Upgrades will not start if there are outstanding FATE transactions - so if those references are present, it would have been from an operation that did not complete cleanly and were not cleaned up.  The will not be from an active operation.  The obsolete references are logged for information and to help determine if those operations should be re-run at some point in the future.
> 3.1 upgrade process with no chop changes

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/CountFiles.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/DeleteTablets.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/MergeTablets.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/ReserveTablets.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/UnreserveAndError.java
- test/src/main/java/org/apache/accumulo/test/functional/DeleteRowsIT.java
- test/src/main/java/org/apache/accumulo/test/functional/MergeIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitMillionIT.java
Using the conditional writer changes from https://github.com/apache/accumulo/pull/3929 this commit updates the
merge code to support merging more tablets than will fit in memory. Also
adds merge and clone operations to the SplitMillionIT and merges a table
with one million tablets in the test.  Without the changes in this
commit that test would cause the manager to die with an out of memory
error.
> Updates merge code to support merging many tablets

- test/src/main/java/org/apache/accumulo/test/MetaSplitIT.java
As part of validating the metadata table MetaSplitIT was requiring tablets to have a location.  However locations may be temproarily absent and that is ok.  Changed the test to validate the time field was present as it should always be there.
> fixes validation in MetaSplitIT

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
Enable the in-use candidate deletion behavior by default in 3.1
> Switch property default state to enabled

- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/rpc/clients/ClientServiceThriftClient.java
- core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java
- core/src/main/java/org/apache/accumulo/core/rpc/clients/TabletManagementClientServiceThriftClient.java
- core/src/main/java/org/apache/accumulo/core/rpc/clients/TabletServerThriftClient.java
- server/base/src/main/java/org/apache/accumulo/server/rpc/ThriftProcessorTypes.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
Modified Compactor and ScanServer to advertise Client service and modified client code to use TabletServer, ScanServer, and Compactor addresses when trying to execute an operation on the Client service API.
Fixes #3624
> Modified Compactor and ScanServer to advertise Client service

- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/rpc/clients/ClientServiceThriftClient.java
- core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java
- core/src/main/java/org/apache/accumulo/core/rpc/clients/TabletManagementClientServiceThriftClient.java
- core/src/main/java/org/apache/accumulo/core/rpc/clients/TabletServerThriftClient.java
- server/base/src/main/java/org/apache/accumulo/server/rpc/ThriftProcessorTypes.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
Modified Compactor and ScanServer to advertise Client service and modified client code to use TabletServer, ScanServer, and Compactor addresses when trying to execute an operation on the Client service API.
Fixes #3624
(cherry picked from commit 65f0204884f04e339699d25426e499c046b127d9)
> Modified Compactor and ScanServer to advertise Client service (#3928)

- core/pom.xml
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/conf/PropertyType.java
- core/src/test/java/org/apache/accumulo/core/conf/PropertyTest.java
- core/src/test/java/org/apache/accumulo/core/conf/PropertyTypeTest.java
- test/src/main/java/org/apache/accumulo/test/shell/ConfigSetIT.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellIT.java
Adds a JSON PropertyType and minimal validation that verifies the property value can be parsed into a JSON object.
This was inspired by issue #3909, but does not directly address it.
1. Some current properties defer validation until use and this PR does not address that. (That could be done in a follow-on PR)
2. Some configurations require multiple, independent properties be set for a valid configuration, This PR does not  attempt to perform that validation - that responsibility is deferred to the implementations that use those properties.
This implementation was to provide a minimal check, that follow on PRs could extend / leverage to introduce additional property validation.
> Add json property type with simple validation

- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorIT.java
Renames the DataLevel method tableId to metaTableId to help clarify that the id returned is the reference to the meta data that contain information for that level (USER points to metadata table, METADATA points to ROOT and ROOT point to ZooKeeper)
Also adds some javadoc to emphasize the level, meta data relationship for forLevel and forTable in TabletsMetadata
> rename DataLevel tableId() to metaTableId(), doc updates

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- minicluster/src/main/java/org/apache/accumulo/minicluster/MiniAccumuloRunner.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloConfigImpl.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- test/src/main/java/org/apache/accumulo/test/LargeSplitRowIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BalanceInPresenceOfOfflineTableIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BatchScanSplitIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BigRootTabletIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BinaryStressIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkSplitOptimizationIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ChaoticBalancerIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ConcurrencyIT.java
- test/src/main/java/org/apache/accumulo/test/functional/DeleteEverythingIT.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorIT.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorTrashDefaultIT.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorTrashEnabledIT.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorTrashEnabledWithCustomPolicyIT.java
- test/src/main/java/org/apache/accumulo/test/functional/LargeRowIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ManyWriteAheadLogsIT.java
- test/src/main/java/org/apache/accumulo/test/functional/MetadataMaxFilesIT.java
- test/src/main/java/org/apache/accumulo/test/functional/MetadataSplitIT.java
- test/src/main/java/org/apache/accumulo/test/functional/RestartStressIT.java
- test/src/main/java/org/apache/accumulo/test/functional/RowDeleteIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SimpleBalancerFairnessIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitIT.java
- test/src/main/java/org/apache/accumulo/test/functional/WriteAheadLogIT.java
The tserver no longer does compactions, therefore the `tserver.compation.major.delay` property is no longer needed. This PR removes the property and associated references within the code.
Closes #3606
> Remove property tserver.compaction.major.delay

- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ConditionalTabletMutatorImpl.java
- test/src/main/java/org/apache/accumulo/test/functional/AmpleConditionalWriterIT.java
> Add support for checking WALs in condition mutations

- test/pom.xml
- test/src/main/java/org/apache/accumulo/test/CloneIT.java
This updates tests that cloned tables work correctly with files that are fenced with non-infinite ranges
The test will test infinite ranges (which is identical to the version of CloneIT) and then the same tests are run again using non-infinite ranges by using the junit parameterized test feature
This addresses part of #3766
> Add tests for ranged files to CloneIT

- test/pom.xml
- test/src/main/java/org/apache/accumulo/test/ImportExportIT.java
This change updates `ImportExportIT` to also test that files that are fenced off by ranges will work correctly with export/import of a table
This addresses part of #3766
> Update ImportExportIT to test fenced files

- core/src/main/java/org/apache/accumulo/core/metadata/schema/MetadataSchema.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadata.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/MetadataSchemaTest.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/TabletMetadataTest.java
- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/MergeState.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
- server/manager/src/main/java/org/apache/accumulo/manager/state/MergeStats.java
- server/manager/src/test/java/org/apache/accumulo/manager/TabletGroupWatcherTest.java
- test/src/main/java/org/apache/accumulo/test/MetaSplitIT.java
- test/src/main/java/org/apache/accumulo/test/functional/MergeIT.java
- test/src/main/java/org/apache/accumulo/test/util/FileMetadataUtil.java
This PR fixes no-chop merge so that it is idempotent and will no longer fail on recovery if the last tablet in the merge range was already fenced. Previously on resume if it tried to fence the files again there would be disjoint files seen from previously copied files during the merge. See #3938 for more details.
**This PR makes the following changes:**
1. A new `MERGED` column marker is inserted into the last tablet as part of the mutation that contains all the fenced file metadata update so the marker is flushed and atomic with the metadata updates. If a failure occurs after this point and before completion on resume this marker can be read to know that fencing was already completed so we can skip this operation and continue to tablet deletion. Note that this marker is only set for …
> Add a merge column marker to make merge idempotent

- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadata.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/TabletMetadataTest.java
Validation for unknown column families in TabletMetadata was dropped. Restored the validation and added a test.
> Restores column family validation in TabletMetadata

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/tablet/CompactableImplFileManagerTest.java
User compactions can preempt selector compaction under certain conditions.  There was a bug in the code where a user compaction could preempt a selector compaction that was in the middle of selecting its files.  The way the code is structured doing this causes an exception. This change makes the preemption wait until file selection is complete.
> fixes bug with compaction preemption

- core/src/main/java/org/apache/accumulo/core/metrics/MetricsProducer.java
The metrics javadocs, which are referenced from the user manual, have a table that currently contains java constant names.  From the perspective of a user they would probably prefer the value of the java constant, which is currently cumbersome to obtain. This commit replaces the java constant name with the values in the javadoc.
> Replaces java constant name with value in metrics javadocs

- test/src/main/java/org/apache/accumulo/test/manager/MergeStateIT.java
Updates the LogEntry used in the MergeStateIT so test passes.
> Fix LogEntry in test that was failing MergeStateIT

- core/src/main/java/org/apache/accumulo/core/manager/balancer/TabletStatisticsImpl.java
- core/src/main/java/org/apache/accumulo/core/spi/balancer/SimpleLoadBalancer.java
- core/src/main/java/org/apache/accumulo/core/spi/balancer/data/TabletStatistics.java
> Removed TabletStatistics.getSplitCreationTime SPI method

- pom.xml
Set fork to true in the maven-compiler-plugin's configuration for the errorprone profile, so that the -J options in the profile takes effect and the profile works on JDK 16 and later without creating local configuration for maven toolchains or setting JVM flags via .mavenrc or .mvn/jvm.config
See https://errorprone.info/docs/installation#maven
Also update the jdk17 profile to jdk16, since that's technically the first version where the exports are needed.
> Fork compiler in errorprone profile

- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader11to12.java
- server/manager/src/test/java/org/apache/accumulo/manager/upgrade/Upgrader11to12Test.java
This is an optimization of the upgrade code from PR #3876.  This code processes each row and emits one mutation for all of the changes needed to upgrade that row.  At a minimum this should reduce the number of mutations needed by 50% by combining the `add updated file reference with fencing` and the `delete obsolete file reference` into a single mutation.  When there are multiple files, chopped or external compaction references for the row, the reduction will be greater. 
The changes simplified error handling so individual methods for each column type was not providing clarity and were removed.  The tests were modified using a mock scanner to provide equivalent coverage that was done for the individual methods.
This code was also testing manually upgrading an uno instance from …
> Use single mutation during no chop fence upgrade

- server/tserver/src/main/java/org/apache/accumulo/tserver/compaction/CompactionStrategy.java
Adds javadoc to warn against using a CompactionStrategy (pre-2.1) and CompactionPlanner (added in 2.1) together.
> update CompactionStrategy to warn against using with CompactionPlanner

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionPlannerInitParams.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionServicesConfig.java
- core/src/test/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlannerTest.java
- core/src/test/java/org/apache/accumulo/core/util/compaction/CompactionServicesConfigTest.java
- server/base/src/main/java/org/apache/accumulo/server/compaction/CompactionWatcher.java
- server/base/src/main/java/org/apache/accumulo/server/conf/CheckCompactionConfig.java
- server/base/src/test/java/org/apache/accumulo/server/conf/CheckCompactionConfigTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionService.java
- test/src/main/java/org/apache/accumulo/test/compaction/BadCompactionServiceConfigIT.java
- test/src/main/java/org/apache/accumulo/test/compaction/CompactionConfigChangeIT.java
- test/src/main/java/org/apache/accumulo/test/compaction/CompactionExecutorIT.java
- test/src/main/java/org/apache/accumulo/test/compaction/CompactionRateLimitingIT.java
- test/src/main/java/org/apache/accumulo/test/shell/ConfigSetIT.java
- test/src/main/java/org/apache/accumulo/test/util/SlowOps.java
These changes are part of #3472 and also handles the movement of the compaction properties out of the `TSERV` prefix and under a new compaction service prefix. 
* Part of the SPI deprecation means that the JSON object in `opts.executors` needed to be modified and only use a subset of its current fields. 
* This PR creates a new property for the compaction service called `opts.queues` which allows external compaction queues to be defined.
* While this new property has overlap with `executors` use, it does not allow for internal compaction executors to be defined.
* I did not add the new property to the Property.java definition as that would require the default compaction services (`meta`, `root`, `default`) to use external compaction executors. 
* This PR also fixes issue in DocGen where …
> Moves compaction properties and adds 'compaction.opts.queue' property.

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/metadata/ReferencedTabletFile.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/ExternalCompactionId.java
- server/base/src/main/java/org/apache/accumulo/server/tablets/TabletNameGenerator.java
- server/base/src/main/java/org/apache/accumulo/server/util/FindCompactionTmpFiles.java
- server/base/src/test/java/org/apache/accumulo/server/tablets/TabletNameGeneratorTest.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/DeadCompactionDetector.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionTestUtils.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_1_IT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_2_IT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_3_IT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalDoNothingCompactor.java
- test/src/main/java/org/apache/accumulo/test/functional/FindCompactionTmpFilesIT.java
Modified TabletNameGenerator.getNextDataFilenameForMajc to add the external compaction id to the filename. When a compaction fails, or the DeadCompactionDetector notices a Compactor is down, CompactionCoordinator.compactionFailed is called to remove the external compaction id from the tablet metadata. Modified this method to also remove corresponding tmp files from the tablet directory when the external compaction id is successfully removed from the tablet metadata. Created the FindCompactionTmpFiles utility to find, and optionally delete, compaction tmp files at a system level. This utility requires that no Compactors are running to avoid any collisions.
Fixes #3577
> Cleanup failed compaction tmp files

- core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java
This fixes an issue introducted in #3951 where the Compactor and ScanServer now expose the ClientService. The issue fixed here is that #3951 did not account for the extra part in the compactor path in ZooKeeper that is used for the queue name.
> Fix TServerClient.getThriftServerConnection for compactor queue names

- core/src/main/java/org/apache/accumulo/core/client/admin/InstanceOperations.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/CompactionPlanner.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
- server/base/src/test/java/org/apache/accumulo/server/conf/CheckCompactionConfigTest.java
- test/src/main/java/org/apache/accumulo/test/compaction/CompactionRateLimitingIT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionTestUtils.java
As part of #3915, a log message was added for instructing users to update their compaction properties if they were using an old prefix. 
https://github.com/apache/accumulo/blob/e12e033df1721fb8a851017ffe39c8a9a49b7a49/core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionServicesConfig.java#L109-L113 
Unfortunately, there are also a number of accumulo tests that modified the accumulo config to set compaction service properties. 
So the test logs starting showing a `Please update property to use the compaction.service prefix` message which isn't ideal. 
This PR* fixes those tests by switching the remaining hardcoded references from `tserver.compaction.major.service` to `compaction.service`. and also updates some documentation references for clarity.
*Includes the …
> Remove remaining references to deprecated prefix

- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/AsyncConditionalTabletsMutatorImpl.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/CleanUp.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/CompactionDriver.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/ReserveTablets.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/DeleteTablets.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/FinishTableRangeOp.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/ReserveTablets.java
- test/src/main/java/org/apache/accumulo/test/functional/AmpleConditionalWriterIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitMillionIT.java
Removes buffering of all conditional results in memory in the compaction code.  This allows compacting more tablets than would fit in memory.
Changed the condition result BiConsumer to a Consumer because it was passing the extents twice, so a BiConsumer was not needed and made the code more verbose.
Updated the compaction code to collect stats and log a trace.  It was logging a lot of per tablet information at debug.  When compacting one million tablets, this resulted in a lot of information in the manager logs.  Moved the per tablet information to trace logging.  Added collection of stats for the different per tablet information and logged the stats once for all tablets scanned.
Added compaction to the SplitMillionIT. Without the other changes in this PR adding compaction to the …
> adds support for compacting lots of tablets

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkNewIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkOldIT.java
The bulk import code had a bug where if an exception was thrown in a certain place in the tablet code that it would mark the bulk import as complete.  After the exception, other code would retry and see the bulk import was complete even though it was not.  This commit changes the behavior to only note success when there is no exception. In addition test were added that recreated this bug.  These test set a constraint on the metadata table that cause bulk import writes to fail.
> fixes bug with bulk import RPC failure and retry

- server/base/src/main/java/org/apache/accumulo/server/AccumuloDataVersion.java
- server/base/src/test/java/org/apache/accumulo/server/ServerContextTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/UpgradeCoordinator.java
Align the upgrade code to match the main branch conventions/style, but keep it disabled for now, until it's working on the elasticity branch.
> Refresh the upgrade code

- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeUtil.java
- server/base/src/test/java/org/apache/accumulo/server/fs/VolumeUtilTest.java
VolumeUtil.switchVolumes is used to perform
volume replacement on LogEntry objects. However,
there was no test for it.
Related to #4004
> Add Volume replacement test for logs

- test/src/main/java/org/apache/accumulo/test/functional/TabletManagementIteratorIT.java
MOdify filename used to create the log entry, such that it is now a fully qualified path
Fixes #4004
> Fix TabletManagementIteratorIT log volume replacements test

- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
- test/src/main/java/org/apache/accumulo/test/VolumeIT.java
When log recovery and volume replace were both needed for a tablet it was not working.  Modified TGW to fix this.
Noticed that tablets needing volume replacement were compacting while looking into this.  Those compactions were starting and failing. Modified TGW to avoid split and compact for tablets needed vol replacement.
> fixes volume replace when log recovery is needed

- test/src/main/java/org/apache/accumulo/test/CloseScannerIT.java
This PR adds a retry to the condition we are testing for once all scanners are closed. I also added logs when the condition does not pass.
I am not sure why the condition in the test is checking that the number of scans is less than 3. If anyone has insight on this maybe we can create a variable name for this number or a comment. I tried changing the condition to check that there are 0 scans and still could not get it to fail locally.
This IT has failed twice recently:
- https://ci-builds.apache.org/job/Accumulo/job/main/org.apache.accumulo$accumulo-test/611/testReport/junit/org.apache.accumulo.test/CloseScannerIT/testManyScans/
- https://ci-builds.apache.org/job/Accumulo/job/main/org.apache.accumulo$accumulo-test/605/testReport/junit/org.apache.accumulo.test/CloseScannerIT/testManyScans/ …
> Add retry and logging to CloseScannerIT

- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
- test/src/main/java/org/apache/accumulo/test/functional/AccumuloClientIT.java
Calling getServerContext() ends up down a path where it sets the SingletonManager to SERVER mode. Modify the method in MiniAccumuloClusterImpl to create a ServiceEnvironment object that can be used to get the compactor group names with calling getServerContext()
> Fixes AccumuloClientIT.testClose

- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
- test/src/main/java/org/apache/accumulo/test/ManagerRepairsDualAssignmentIT.java
The exception handling for the BadLocationStateException in the TabletGroupWatcher was not correct, so the repairMetadata method was not being called.
> Fix ManagerRepairsDualAssignmentIT

- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ServiceLock.java
- core/src/test/java/org/apache/accumulo/core/fate/zookeeper/ServiceLockTest.java
- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/ServiceLockIT.java
Fixes the UUID parsing check / validation in ServiceLock. The parsing of the lock string had a logic error with the indices used to parse out the parts.  The error in the index parsing would pass not pass the complete UUID for validation.  
The uuid check would pass for things that were UUID like, but not strictly a UUID.  For example, it would accept 1-1-1-1-1 as a valid UUID string.  This also allowed the incomplete uuid that was parsed from the lock string to pass.
This was found while reducing the reported check style errors and to favor Wait instead of sleep in the tests.
> Fix error in uuid validation, checkstyle fixes

- test/src/main/java/org/apache/accumulo/test/DetectDeadTabletServersIT.java
- test/src/main/java/org/apache/accumulo/test/GarbageCollectWALIT.java
- test/src/main/java/org/apache/accumulo/test/ManagerRepairsDualAssignmentIT.java
- test/src/main/java/org/apache/accumulo/test/ScanFlushWithTimeIT.java
- test/src/main/java/org/apache/accumulo/test/TestMultiTableIngest.java
- test/src/main/java/org/apache/accumulo/test/WriteAfterCloseIT.java
- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/FateIT.java
- test/src/main/java/org/apache/accumulo/test/functional/AssignLocationModeIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BackupManagerIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BalanceAfterCommsFailureIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BalanceInPresenceOfOfflineTableIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BloomFilterIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactLocationModeIT.java
- test/src/main/java/org/apache/accumulo/test/functional/DeletedTablesDontFlushIT.java
- test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ManagerAssignmentIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ScannerContextIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ScannerIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SummaryIT.java
- test/src/main/java/org/apache/accumulo/test/functional/TabletStateChangeIteratorIT.java
- test/src/main/java/org/apache/accumulo/test/util/SlowOps.java
Replaces the UtilWaitThread.sleep() method with Wait.waitFor or standard Thread.sleep() in tests.  Excludes changes to compaction tests for now.
> Replace UtilWaitThread.sleep() in tests.

- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
- test/src/main/java/org/apache/accumulo/test/GCRunIT.java
- test/src/main/java/org/apache/accumulo/test/GarbageCollectWALIT.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorIT.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorTrashDefaultIT.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorTrashEnabledIT.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorTrashEnabledWithCustomPolicyIT.java
The call to putGCCandidates was lost in #3604 with the removal of ManagerMetadataUtil.replaceDatafiles.
> Call Ample.putGCCandidates on compaction completion

- core/src/main/java/org/apache/accumulo/core/client/admin/ActiveCompaction.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/manager/balancer/TabletStatisticsImpl.java
- core/src/main/java/org/apache/accumulo/core/spi/balancer/SimpleLoadBalancer.java
- core/src/main/java/org/apache/accumulo/core/spi/balancer/data/TabletStatistics.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionServicesConfig.java
- core/src/test/java/org/apache/accumulo/core/util/compaction/CompactionServicesConfigTest.java
- pom.xml
- server/base/src/main/java/org/apache/accumulo/server/util/ManagerMetadataUtil.java
- server/base/src/test/java/org/apache/accumulo/server/util/ManagerMetadataUtilTest.java
- test/src/main/java/org/apache/accumulo/test/compaction/CompactionRateLimitingIT.java
- test/src/main/java/org/apache/accumulo/test/functional/AssignLocationModeIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactLocationModeIT.java
- test/src/main/java/org/apache/accumulo/test/shell/ConfigSetIT.java
- test/src/main/java/org/apache/accumulo/test/util/SlowOps.java
Avoid use of `forRemoval = true` to indicate terminally deprecated items. Although explicitly communicating that something may be removed is a nice-to-have, the justification for avoiding it is:
1. terminal deprecations are new in Java, and optional to use; ordinarily deprecated items can still be subject to removal, especially for code that was ordinarily deprecated prior to the introduction of this new forRemoval attribute; so, users cannot rely on only terminally deprecated items being removed
2. terminal deprecations behave differently than ordinary deprecations in that the use of terminally deprecated items in deprecated code still triggers a compiler warning, and the proper use of these and suppression of these warnings are difficult to use correctly or reason about (see …
> Remove and prevent use of terminal deprecations

- core/src/test/java/org/apache/accumulo/core/tabletserver/log/LogEntryTest.java
* Make constants private
* Use SimpleImmutableMap instead of anonymous inner class
* Include getFilePath method in testEquals
* Test all methods using the constructor
* Test all methods using fromMetaWalEntry
* Remove testing of invalid "foo" path that wasn't actually read
> Fix issues with LogEntryTest

- core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionServicesConfig.java
Fixes an incorrect logging statement from appearing during normal startup conditions when processing `service.<service>.planner` compaction properties.
Bug was introduced in #3915. 
Log message: 
```
[main] WARN  org.apache.accumulo.core.util.compaction.CompactionServicesConfig [] - Ignoring compaction property default.planner as does not match the prefix used by the referenced planner definition
```
Steps to replicate bug:
1. git checkout `main`
2. Run any of the tests in `CompactionServicesConfigTest`
3. See the log message in the output.
> Fixes compaction property log message bug

- core/src/main/java/org/apache/accumulo/core/fate/AgeOffStore.java
- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
- core/src/main/java/org/apache/accumulo/core/fate/FateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/ReadOnlyFateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/SignalCount.java
- core/src/main/java/org/apache/accumulo/core/fate/ZooStore.java
- core/src/main/java/org/apache/accumulo/core/logging/FateLogger.java
- core/src/test/java/org/apache/accumulo/core/fate/TestStore.java
- test/src/main/java/org/apache/accumulo/test/ComprehensiveIT.java
This change modifies FATE to use singe thread to find work.  It also cleans up some of the signaling between threads in FATE and fixes a synchronization bug in FATE that was introduced in #4017.  The bug introduced in #4017 is that somethings are syncronizing on the wrong object because a new inner class was introduced.
These changes were pulled from #3964 and cleaned up and improved.
> modifies FATE to use a single thread to find work

- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
- test/src/main/java/org/apache/accumulo/test/WriteAfterCloseIT.java
- test/src/main/resources/log4j2-test.properties
There was a race condition between the two thread in tablet group watcher that caused a tablet to be marked as assigned to a dead tablet server when that was not true.
This commit fixes that race condition, enables a test that was failing because of it, and adds the thread id to test logging.  The thread id was useful in confirming this bug so it will probably be useful in the future.
Below are some log messages from tracking this bug down.  The number after the timestamp is the thread id.  Can see thread 47 assigns tablet 1<< and then thread 46 assumes its assigned to a dead tablet server. However it was a not a dead tserver, it had just started as the test restarted tservers.
```
2023-12-09T16:04:54,439 47 [manager.Manager] TRACE: [Normal Tablets] Shutting down all Tservers: false, …
```
> fixes a race condition in tablet group watcher

- test/src/main/java/org/apache/accumulo/test/functional/MemoryStarvedMajCIT.java
- test/src/main/java/org/apache/accumulo/test/functional/MemoryStarvedScanIT.java
In #3951 the ScanServer and Compactor advertise the Thrift Client service. However, the test is only consuming memory in the tabletServer, so we need to connect to a tableServer, not a Compactor or ScanServer. Modified freeServerMemory to only connect to the TabletServer and introduced a wait in MemoryStarvedMajCIT as it was trying to connect before the Compactor was fully up.
> Fix MemoryStarved ITs

- test/src/main/java/org/apache/accumulo/test/functional/FlushNoFileIT.java
- test/src/main/java/org/apache/accumulo/test/functional/FunctionalTestUtils.java
The test was failing because it was expecting that all tablets had the same flushID. However, it is only inserting data into one tablet in a tablet with the ONDEMAND tablet availability. Since only one tablet was hosted, only that tablet has a flushID and the others had none.
> Fixed FlushNoFileIT, re-enabled the test

- core/src/main/java/org/apache/accumulo/core/client/MutationsRejectedException.java
- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
- server/base/src/test/java/org/apache/accumulo/server/constraints/MetadataConstraintsTest.java
Removes the active FateTx ID constraint for metadata mutations when creating bulk import file markers.
Also changes the MutationsRejectedException to return the violation type code.
closes #4047
> Remove active FateTx constraint for bulk import

- core/src/main/java/org/apache/accumulo/core/fate/ZooStore.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/ReserveTablets.java
This fixes a bug where when a FATE operation was not ready and was deferred that it may never run again.  Also improved some logging that was encountered while debugging this.  This bug was causing test in ConcurrentDeleteTableIT to hang forever because concurrent fate operations were deferred and then never ran again.
> Fixes FATE deferral

- server/base/src/main/java/org/apache/accumulo/server/manager/state/MetaDataTableScanner.java
Use LogEntry.fromMetaWalEntry to parse log entries from the metadata table in MetaDataTableScanner. It previously implemented a manual parsing of a very old and outdated schema that just happened to still work with the current format.
This fixes #4065 and will be compatible with the changes in PR #3997.
> Use LogEntry to parse log entries

- core/src/main/java/org/apache/accumulo/core/tabletserver/log/LogEntry.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/TabletMetadataTest.java
- core/src/test/java/org/apache/accumulo/core/tabletserver/log/LogEntryTest.java
- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeUtil.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/TabletMutatorBase.java
- test/src/main/java/org/apache/accumulo/test/MissingWalHeaderCompletesRecoveryIT.java
- test/src/main/java/org/apache/accumulo/test/manager/MergeStateIT.java
Remove the `LogEntry.getValue()` method and use the column qualifier for the file path, without the redundant storage in the Value
* Remove `getValue()` method and use empty `new Value()`
* Create addToMutation method to remove boilerplate for storing the LogEntry in the metadata
* Strictly validate the metadata log entries' column qualifier
This re-applies the reverted change for this ticket, 0cdf6dd2de0ca382c3881169bfe90c3bbd4367b3, but without the renaming of filePath to logReference, since with further analysis of the schema, it was discovered that these are, in fact, file paths, and not just generic references to log IDs.
This re-application also removes the metadata constraint that expected the value to be non-empty, which was overlooked on the first attempt.
---------
> Remove redundant LogEntry value (#3997)

- server/manager/src/main/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueue.java
Handles a `NullElementException` that is thrown if `getLowestPriority` is called on an empty compaction priority queue.
This is expected to fix the flaky MetricsIT test as the metric `METRICS_COMPACTOR_JOB_PRIORITY_QUEUE_JOBS_PRIORITY` will always return a value for a given queue.
@keith-turner If a queue is empty, what should the queue priority return? Right now it's `0` but I'm not sure if that's the correct "empty"  value we want to set.
> Handle exception when compaction queue is empty

- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterControl.java
- test/src/main/java/org/apache/accumulo/test/compaction/CompactionExecutorIT.java
Gets all tests working in CompactionExecutorIT. 
Adds additional method to stop compactors by resource group names.
Compaction groups are now created on an as needed basis for each test and cleaned up afterwards without affecting compactions for the root or metadata tables.
> Enables more tests in CompactionExecutorIT

- core/src/main/java/org/apache/accumulo/core/logging/TabletLogger.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- core/src/main/java/org/apache/accumulo/core/tabletserver/log/LogEntry.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/TabletMetadataTest.java
- core/src/test/java/org/apache/accumulo/core/tabletserver/log/LogEntryTest.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeUtil.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/MetaDataStateStore.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/MetaDataTableScanner.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/ZooTabletStateStore.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/TabletMutatorBase.java
- server/base/src/main/java/org/apache/accumulo/server/util/ListVolumesUsed.java
- server/base/src/main/java/org/apache/accumulo/server/util/ManagerMetadataUtil.java
- server/base/src/test/java/org/apache/accumulo/server/fs/VolumeUtilTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/WalRemovalOrderTest.java
- test/src/main/java/org/apache/accumulo/test/MissingWalHeaderCompletesRecoveryIT.java
- test/src/main/java/org/apache/accumulo/test/manager/MergeStateIT.java
* Use LogEntry type in more places where just the logEntry's filename as a String was being used
* Keep the UUID and HostAndPort in LogEntry that are created for validation, rather than their String equivalents
* Remove no longer needed deleteWal(String) and create a deleteFromMutation method on LogEntry to keep the schema serialization/deserialization in LogEntry (may want to move that to LogColumnFamily class in the MetadataSchema later, but for now, at least it's in one place)
* Use private constructor in LogEntry, do validation in a fromFilePath static method before calling the constructor with the strongly typed results
* Update javadocs to clarify the filename format
* Fix the validation of the host+port in the filename (it's a plus sign not a colon, because colons weren't valid …
> Stronger type checking and other WAL improvements

- core/src/main/java/org/apache/accumulo/core/metadata/TabletLocationState.java
- core/src/main/java/org/apache/accumulo/core/tabletserver/log/LogEntry.java
- core/src/test/java/org/apache/accumulo/core/tabletserver/log/LogEntryTest.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeUtil.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/MetaDataTableScanner.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/ZooTabletStateStore.java
- server/base/src/test/java/org/apache/accumulo/server/manager/state/TabletLocationStateTest.java
- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java
- server/gc/src/test/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogsTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/recovery/RecoveryManager.java
- server/manager/src/test/java/org/apache/accumulo/manager/state/MergeStatsTest.java
- test/src/main/java/org/apache/accumulo/test/manager/MergeStateIT.java
* Track the actual column qualifier read from the metadata table, so when it is deleted, it can delete the actual entry, rather than try to delete the existing entry with the new format (requires no longer strictly requiring that log entries start with a `-/`). This fixes #4061 for the main branch for 3.1; a similar issue may still exist for 2.1, but will require a different fix.
* Remove use of `Collection<Collection<String>>` and use `Collection<LogEntry>` where possible, since the former was for a previous WAL storage format that we do not support, and the latter preserves the strongly-typed LogEntry in more places
> Use LogEntry concrete type in more places

- .github/ISSUE_TEMPLATE/post_vote_checklist.md
- .github/workflows/maven-full-its.yaml
- .github/workflows/maven-on-demand.yaml
- .github/workflows/maven.yaml
- .github/workflows/scripts.yaml
- assemble/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/accumulo/core/trace/TraceUtil.java
- pom.xml
- server/base/src/main/java/org/apache/accumulo/server/util/RestoreZookeeper.java
- server/monitor/pom.xml
In preparation for 2.1.3 release, update some of the build tools and dependencies to enhance the quality of the next release.
* Update post-release checklist template
* Update GitHub Actions workflows
* Require JDK 17 for the build, for build consistency/reproducibility (still target Java 11 for runtime)
* Update the parent POM version to 31
* Update opentelemetry version and drop the semantic conventions jar as a dependency, which is no longer available (and not really needed)
* Update bouncycastle, slf4j, zookeeper, jackson, micrometer, log4j, jetty, junit, guava, easymock, and snappy dependencies
* Update plugin versions (leave spotbugs back at an earlier version for now, because of some overly aggressive and spammy checks in the latest version that disallows exceptions being thrown in …
> Pre-release build quality updates

- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/logger/LogReader.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/log/DfsLoggerTest.java
- Move the assert check to a unit test and deletes redundant check
- simple IDE suggested QA checks.
Fixes #4100
> Fix 4100 - move header length check to test

- pom.xml
With distruptor version 4.0.0 SequenceReportingEventHandler.class needed by log4j is missing.  This change reverts distruptor back to 3.4.4
Verified that uno will run an instance with this change (main branch), fails with version 4.0.0
> revert disruptor version to 3.4.4 for log4j compatibility

- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
Although the NoCryptoService's decrypter returns the same stream that it was given in the current implementation, that behavior is not guaranteed in the future. So, instead of relying on that insider knowledge about the NoCryptoService implementation, ask the decrypter for the stream like normal, and then check if it's already a DataInputStream before re-wrapping it, since that's the condition we actually should check in order to avoid rewrapping. This allows us to avoid duplicate wrapping of other implementations as well, instead of treating NoCryptoService as a special case.
> Avoid DfsLogger unencrypted WAL special case

- server/base/src/main/java/org/apache/accumulo/server/ServerContext.java
- server/base/src/main/java/org/apache/accumulo/server/ServerDirs.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeUtil.java
- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
- server/base/src/test/java/org/apache/accumulo/server/fs/VolumeUtilTest.java
- server/gc/src/main/java/org/apache/accumulo/gc/GCRun.java
- server/manager/src/main/java/org/apache/accumulo/manager/recovery/RecoveryManager.java
* Use LinkedHashMap for order-preserved mapping of volume replacements instead of a List of Pairs
* Use this to simplify VolumeUtil.switchVolume
* Rename VolumeUtil.switchVolumes to switchVolume so it's actually an overloaded method for LogEntry, rather than merely having a similar name
* Also remove redundant trace logging for switching volumes for LogEntry, say "No replacement available" instead of the more concerning-sounding "Could not find replacement" (which implies there's supposed to be one, when it's fine if there isn't), and include the FileType in the trace log when the replacement is found
> Use a Map for volume replacements

- core/src/main/java/org/apache/accumulo/core/conf/ConfigurationCopy.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionPlannerInitParams.java
- core/src/test/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlannerTest.java
Fixes an issue with the deprecated `tserver.compaction.major.thread.files.open.max` property. 
If the `open.max` property was set, the replacement property `tserver.compaction.major.service.default.planner.opts.maxOpen` would not be used and any user-defined compaction service would also only use the old `open.max` property value. 
The cause was an error in the `getFullyQualifiedOption` of `CompactionPlannerInitParams`. 
This has now been fixed and a test included to reproduce the problematic behavior.
a268958ddf411e460e85b9eb2cf71ab5fee5a4cd will fail the tests, and 4042529ac0491f0d25b7dc0f6cc89d547a1245cc includes the one line fix.
> Fix bug in compaction props

- core/src/main/java/org/apache/accumulo/core/conf/ConfigurationCopy.java
Modifies `isPropertySet` to also check the parent config if it exists.
> Update isPropertySet to check parent config

- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionPlannerInitParams.java
- core/src/test/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlannerTest.java
This fixes a bug in the compaction properties to ensure the replacement
property is always preferred over the deprecated open.max compaction
property when it is set.
Add tests for maxOpen to override open.max:
* Adds a test to ensure that setting the maxOpen option for a compaction
service will override the deprecated `open.max` property if set
* Condenses helper methods in planner tests
* Uses CompactionPlannerInitParams for tests instead of custom test code
* Adds test case for default compaction service used with deprecated
property
* Removes hardcoded maxOpen value with reference to default property
value
* Modifies the getFullyQualifiedOption to return the correct path for
the `<service>.planner.opts.` properties
This is a reapplication of #4092 after it was reverted, to use …
> Fix bug in compaction props (reapply #4092)

- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorIT.java
GcCandidates are "Valid" when the filepaths they reference have been removed from HDFS.
Because the file no longer exists, the putDelete mutation should not include a timestamp to ensure no newer versions of that same GcCandidate are processed a second time.
> Remove mutation timestamp for valid GcCandidates

- core/src/main/java/org/apache/accumulo/core/fate/AdminUtil.java
- core/src/main/java/org/apache/accumulo/core/fate/AgeOffStore.java
- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
- core/src/main/java/org/apache/accumulo/core/fate/ReadOnlyTStore.java
- core/src/main/java/org/apache/accumulo/core/fate/ZooStore.java
- core/src/main/java/org/apache/accumulo/core/logging/FateLogger.java
- core/src/test/java/org/apache/accumulo/core/fate/AgeOffStoreTest.java
- core/src/test/java/org/apache/accumulo/core/fate/TestStore.java
- shell/src/test/java/org/apache/accumulo/shell/commands/FateCommandTest.java
closes https://github.com/apache/accumulo/issues/4068
- `ZooStore` now uses `System.nanoTime()` instead of `System.currentTimeMillis()`
- Added `TimeUnit` param to `unreserve()`
- Renamed 'defered' -> 'deferred'
Also have branch ready to be compared against elasticity if these changes are good (changes were also requested for AccumuloStore in elasticity)
> ZooStore deferral time to use System.nanoTime()

- core/src/main/java/org/apache/accumulo/core/client/admin/compaction/CompactionConfigurer.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/PrintBCInfo.java
- core/src/test/java/org/apache/accumulo/core/compaction/ShellCompactCommandConfigurerTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableUtils.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
Closes https://github.com/apache/accumulo/issues/3937
Changes:
- Added getSelectedFiles() method to CompactionConfigurer.InputParameters
- Added method functionality in the two implementations of this: ShellCompactCommandConfigurerTest and CompactableUtils
- Tested functionality in new IT: testGetSelectedFilesForCompaction() in CompactionIT
- Added new method getCompressionType() to PrintBCInfo (used in the test)
- Changed several method signatures to pass around necessary info for getSelectedFiles() implementations
- Renamed 'files' variable to 'inputFiles' in CompactableUtils and CompactableImpl for a more clear distinction between inputFiles and the (new) selectedFiles.
- Moved 'fsin' in PrintBCInfo to try-with-resources block
Potentially still left TODO:
- Add this functionality for …
> Added Indication of Intermediate Compactions to CompactionConfigurer

- core/src/main/java/org/apache/accumulo/core/client/admin/InstanceOperations.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/InstanceOperationsImpl.java
- test/src/main/java/org/apache/accumulo/test/conf/PropStoreConfigIT.java
Closes https://github.com/apache/accumulo/issues/4095
- Added getSystemProperties() to InstanceOperations which functions similary to getTableProperties() and getNamespaceProperties() from TableOperations and NamespaceOperations.
- Added its implementation in InstanceOperationsImpl.
- Added a test getSystemPropertiesTest() to PropStoreConfigIT to test that the new method functions as intended.
> Return non-merged view of System config

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
- core/src/test/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlannerTest.java
This change updates the DefaultCompactionPlanner to honor the table.file.max property.  When a tablet has more files than is configured in table.file.max and its not compacting, it will try to find a compaction ratio that will cause a compaction.
Using a lower compaction ratio will find files of a similar size to compact. This avoids the problem with deprecated DefautlCompactionStrategy where it may select a 1K and 1G file for compaction because it selected the N smallest files that would bring the tablet under the table.file.max limit.
> Updates DefaultCompactionPlanner to honor table.file.max prop

- core/src/main/java/org/apache/accumulo/core/fate/AbstractFateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/AdminUtil.java
- core/src/main/java/org/apache/accumulo/core/fate/AgeOffStore.java
- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
- core/src/main/java/org/apache/accumulo/core/fate/FateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/ReadOnlyFateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/ZooStore.java
- core/src/main/java/org/apache/accumulo/core/fate/accumulo/AccumuloStore.java
- core/src/main/java/org/apache/accumulo/core/logging/FateLogger.java
- core/src/test/java/org/apache/accumulo/core/fate/AgeOffStoreTest.java
- core/src/test/java/org/apache/accumulo/core/fate/TestStore.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/UpgradeCoordinator.java
- test/src/main/java/org/apache/accumulo/test/fate/FateIT.java
- test/src/main/java/org/apache/accumulo/test/fate/accumulo/AccumuloFateIT.java
- test/src/main/java/org/apache/accumulo/test/fate/accumulo/AccumuloStoreReadWriteIT.java
- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/ZookeeperFateIT.java
As we change Accumulo to use FATE for per tablet operations its important to avoid reading all FATEs persisted data into memory. This commit modifies FATE to use Streams internally instead of Collections. For the Accumulo implemention of FATE storage this makes it possible to have java stream backed by a scanner which avoids reading all of the FATE ids into memory.  The Zookeeper storage implementation will still read everything into memory.
Another change that was made in the PR was optimizing the Accumulo storage layer to read the status while reading the id.  Before this change ids were read from scanner, then for each id a scanner was created to read the status. Now the status and id are read in stream from the same scanner which should be much faster.  This change was not possible …
> Avoids reading all fate ids into memory.

- server/manager/src/main/java/org/apache/accumulo/manager/FateServiceHandler.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/FinishImportTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/ImportTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/ImportedTableInfo.java
- test/src/main/java/org/apache/accumulo/test/ImportExportIT.java
Fixes #4045 
This PR adds logic to properly transition the state of a new table created via `importTable()` to offline (or online) depending on the value supplied via the `ImportConfiguration`.
This was corrected by the change in `FinishImportTable` where the table was never transitioned from the NEW to OFFLINE table state when the (then `onlineTable`) param was set.
Other changes:
* added a check in the IT to make sure the new table is in the OFFLINE state instead of just "not online"
* renamed the member variable from `onlineTable` to `keepOffline` for clarity and consistency
> Fix ImportConfiguration.builder().setKeepOffline()

- core/src/main/java/org/apache/accumulo/core/client/admin/NamespaceOperations.java
- core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java
closes #4038 
InstanceOperations:
Did not find any changes needed to be made:
- modifyProperties() returns non-composite (System level only) view as
stated in the javadocs
- getSystemConfiguration() returns composite view as stated in the
javadocs
- getSiteConfiguration() returns non-composite (Site level only) view as
stated in the javadocs
NamespaceOperations:
- modifyProperties() returns non-composite (Namespace level only) view
as stated in the javadocs (no changes here)
- getProperties() returns a composite view. Updated javadocs.
- getConfiguration() returns a composite view. Updated javadocs.
- getNamespaceProperties() returns a non-composite (Namespace level
only) view. Updated javadocs.
TableOperations:
- modifyProperties() returns non-composite (Table level only) view
as stated …
> Update javadoc to indicate composite view returned or not

- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java
- test/src/main/java/org/apache/accumulo/test/VolumeIT.java
The GC Wal scan was doing consitency checking and filtering which caused a runtime excecption that prevented wal GC.  Consistency checking is not needed becasue a tablet with a wal will not split or merge. Prior to the change in 5c454e12a144e3543175d2cbc0b54bc0900749b1 consistency checking was not done.  It was added w/o a specific reason so removing the consistency check instead of removing filtering. Fixing GC for wals fixes VolumeIT which was failing because no GC was happening.
> removes consitency check in GC wal scan

- server/base/src/main/java/org/apache/accumulo/server/util/ManagerMetadataUtil.java
When a metadata tablet splits it writes to the root table.  The code that handles split recovery was always reading from the metadata table. Therefore if a tablet server was in the middle of splitting a metadata tablet and died, then it would not recover correctly.  This change modifies the split recovery code to use the appropriate table.
Noticed this while working on #4136
> fixes split recovery for metadata tablet

- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/DistributedReadWriteLock.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/Utils.java
Validate recovered lock type against expected type (read or write) and throw IllegalStateException with detailed information on mismatch. If lock is not recovered, create a new lock as usual. Fixes issue #4066
> Validate recovered lock type

- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java
- core/src/test/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlannerTest.java
- core/src/test/java/org/apache/accumulo/core/util/compaction/CompactionPrioritizerTest.java
Makes the default compaction planner use the table id when prioritizing compactions.  The root table id is always given the highest priority, followed by the metadata table, then user tables.
Fixes #4033
> uses table id in compaction prioritization

- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionService.java
Switch from Guava to Caffeine to fix the build errors
This PR fixes the failing build which resulted from 2.1 code being merged to main and not realizing the main branch has a build check to disallow Guava
> Fixes 2.1 merge to main

- core/src/main/java/org/apache/accumulo/core/spi/compaction/CompactorGroupId.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/QueueMetrics.java
The metricsWithoutQueues variable is a SetView
which is sensitive to changes in the underlying
sets. The loop was modifying one of the underlying objects. To prevent the CME from being raised I
copied the objects into a new set.
Closes #4144
> Fix ConcurrentModificationException in QueueMetrics

- server/base/src/main/java/org/apache/accumulo/server/tables/TableManager.java
- server/manager/src/main/java/org/apache/accumulo/manager/FateServiceHandler.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/ChangeTableState.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/clone/FinishCloneTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/create/FinishCreateTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/DeleteTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/FinishImportTable.java
Closes #4132
Prior to these changes, users were able to manually transition a table from the NEW state to another state. More specifically, calls to TableOperations.online() and TableOperations.offline() when the table was in the NEW state were acceptable. Users should not be able to transition a table from the NEW state as this should only be done by the system upon successfully creating/cloning/importing the table.
Changes:
- Added new param expectedCurrStates to TableManager.transitionTableState()
- Users can now only manually change a table from [ONLINE/OFFLINE]->[ONLINE/OFFLINE] (FateServiceHandler)
- Added field expectedCurrStates to ChangeTableState
- Table clones, creations, and imports now explicitly expect the current state before completion to be NEW (FinishCloneTable, …
> Stricter checks before transitioning table state

- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
As part of #4133 the null check for fateRef inside of setManagerState() method in the Manager was inadvertently [changed](https://github.com/apache/accumulo/pull/4133/files#diff-07984c23da1745b22dd4fde5c4b8877dfb190ea19e5e60ab79d8a93e752031c7R339) to check if the map size was non empty but the actual check should be that it's null which means not initialized. The map will never be non empty if it is set.
This restores the previous check that used to check for a null ref
> Fix fateRefs init check when setting the manager state

- server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionFinalizer.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/DeadCompactionDetector.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/compactor/src/test/java/org/apache/accumulo/compactor/CompactorTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalDoNothingCompactor.java
Closes #4075
Changes:
- CompactionFinalizer
- Added compactionId to log of compaction failure (tableId is already included from 'ecfs')
- CompactionCoordinator
- Added extent/tableId to log of compaction failure (compactionId already included)
- CompactableImpl
- Added extent/tableId to two logs of compaction failure (compactionId already included)
- Compactor
- Added extent/tableId and compactionId to three of the logs
- ExternalDoNothingCompactor
- Added extent/tableId and compactionId to log of compaction failure
- DeadCompactionDetector
- Added extent/tableId to log (compactionId already included)
- FileCompactor
- Added extent/tableId, input files, output file, iterators, and thread start time to log when error occurs
Potentially still left TODO:
- Any more logs that need to be …
> More Detailed Compaction Errors

- core/src/main/java/org/apache/accumulo/core/logging/TabletLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
Closes #4139
Related to [pull/4148](https://github.com/apache/accumulo/pull/4148) / [issue/4075](https://github.com/apache/accumulo/issues/4075)
Changes:
- Methods compactionFailed() and externalCompactionFailed() in TabletLogger
- Small change to arg passed to updateTimer()
- Calls to compactionFailed() and externalCompactionFailed() in CompactableImpl
> Compaction Failed Logging in TabletLogger

- shell/src/main/java/org/apache/accumulo/shell/ShellOptionsJC.java
- shell/src/main/java/org/apache/accumulo/shell/commands/FateCommand.java
- shell/src/test/java/org/apache/accumulo/shell/commands/FateCommandTest.java
* Show shell config load info as a log message, so it can be suppressed from output more easily (depending on logging config)
* Throw command line parse exception when an invalid shell option is used in FateCommand, instead of merely printing to System.out and returning
* Use shellState.getWriter() for command-output messages instead of hard-coded System.out (use System.out for related unit tests)
> Remove direct use of System.out in shell

- core/src/main/java/org/apache/accumulo/core/clientImpl/InstanceOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/lock/ServiceLockData.java
- core/src/main/java/org/apache/accumulo/core/metadata/TServerInstance.java
- core/src/main/java/org/apache/accumulo/core/util/AddressUtil.java
- core/src/test/java/org/apache/accumulo/core/util/AddressUtilTest.java
- server/base/src/main/java/org/apache/accumulo/server/manager/LiveTServerSet.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletStateChangeIterator.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/manager/ManagerResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tservers/TabletServerResource.java
The utility AddressUtil,parseAddress() had a boolean parameter to allowed addresses to be created without a port. Other than another utility method that allows setting the default port the value was always false (required port)  This PR removes the boolean from the method signature.
Discovered this while trying to use HostAndPort in favor of strings where possible.  Submitting this a separate PR because it is stand-alone change that is easier to review.
> clean up AddressUtil.parseAddress usage

- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/QueueMetrics.java
- test/src/main/java/org/apache/accumulo/test/compaction/CompactionPriorityQueueMetricsIT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionMetricsIT.java
Adds back in the use of the MetricsUtil.formatString method when creating metric tags
Removes missed "e." external queue name prefixes
> Fixes Queue Metric Tag format

- core/src/main/java/org/apache/accumulo/core/fate/AbstractFateStore.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/MetadataSchema.java
- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java
The upgrade code deletes the compact column in the metadata table.  The metadata constraint would cause this to fail (confirmed w/ a manual test). This change adds the compact column to the metadata constraint so the upgrade code can delete it.
> allows compact column in metadata constraint

- server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletManagementParameters.java
- server/base/src/test/java/org/apache/accumulo/server/manager/state/TabletManagementParametersTest.java
TabletManagementParameters was still using a List<Pair<Path,Path>> for volume replacements serialization. This was changed to a Map<Path,Path> in other places of the code because there was an issue with Gson serialization. I added a test for serialization and deserialization and was able to successfully use a Map when setting enableComplexMapKeySerialization() on the Gson object.
Fixes #4107
> Fixed TabletManagmentParameters serialization of replacements

- .github/workflows/maven-full-its.yaml
- .github/workflows/maven-on-demand.yaml
- .github/workflows/maven.yaml
Updated GitHub action cache@v3 to v4.  Node 16 has been deprecated in GitHub actions and v4 was updated to use node 20.  
This eliminates warnings in the GitHub action runner, for example:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
> update cache workflow action to v4, replaces node 16 with node 20

- core/src/main/java/org/apache/accumulo/core/iterators/user/RowFilter.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/RowFilterTest.java
If a RowFilter implemented init and used the options, then these options would be lost if the RowFilter was deep copied.  When RowFilters are chained the 2nd RowFilter in the chain will deep copy the first. This commit fixes the bug by saving options and calling init with them in deep copy.
> Fixes RowFilter bug with deep copy

- test/src/main/java/org/apache/accumulo/test/compaction/CompactionPriorityQueueMetricsIT.java
CompactionPriorityQueueMetricsIT was waiting for a queue to report zero size.  However when the queue is empty it may be removed and then no reports are generated for it.  Added an additional check for zero total queues to the test.
> fixes CompactionPriorityQueueMetricsIT

- server/base/src/test/java/org/apache/accumulo/server/security/delegation/AuthenticationTokenSecretManagerTest.java
There fixes a test race condition in the `AuthenticationTokenSecretManager#testVerifyPassword` test that could occasionally cause the test to fail if it ran too quickly. Token generation uses System.currentTimeMillis() so the test previously would fail when trying to generate a new token if the timestamp didn't update as the same token would be returned. This commit adds a short sleep of 1 ms to guarantee that the test won't fail.
Before this fix when running that test in a loop in my IDE it would typically fail within 3-5 iterations. With this change I was able to run 10k iterations in a loop without failure.
> Fix intermittent failure in AuthenticationTokenSecretManagerTest

- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction4_IT.java
The test is failing because as the testErrorDuringCompactionNoOutput test is creating files (50) the default max files limit (15) is exceeded and compaction start.  When the files creation completes, the test was expecting 50 files, but these can be less because of the compactions.  It think this is related to changes in #4127.
Also fixed places where TabletsMetadata was created without try-with-resources.
Also, not sure if the number of files is important.  The test could be changed to accept a number of files >= max files instead of wanting an absolute number, this would reduce the need for an absolute number of files.  The other test was already setting max number of files, so went that way.
> set max files to fix ExternalCompaction4_IT test

- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
The test CompactionIT.testConcurrentSplit() would periodically fail because it relied on the old behavior of WaitFor.  Changed the test to use custom code that waits up to three seconds for a condition to be met and then continues.
> fixes periodic failure with CompactionIT

- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
- core/src/test/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlannerTest.java
Gson returns a null array when `executors` either isn't defined, or is an empty string.
The code then throws an NPE when attempting to iterate through the array.
```
ExecutorConfig[] execConfigs =
new Gson().fromJson(params.getOptions().get("executors"), ExecutorConfig[].class);
List<Executor> tmpExec = new ArrayList<>();
for (ExecutorConfig executorConfig : execConfigs) {
```
This change throws an IllegalStateException before the NPE would occur and adds an actionable exception message.
This change is only targeted to `2.1` as this situation is already handled in `main`.
> Better error when compaction executors are not set

- .github/workflows/maven-full-its.yaml
- .github/workflows/maven-on-demand.yaml
- .github/workflows/maven.yaml
This updates the actions/upload-artifact from v3 to v4. This fixes build failures like:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/upload-artifact@v3.
```
[Encountered here](https://github.com/apache/accumulo/actions/runs/7757481597)
> Update upload-artifact workflow action to v4, replaces node 16 with node 20

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
Since this property is enabled by default it should no longer be considered `experimental` status.
> Remove Experimental tag from GC property

- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
When testing scan servers this log message was spamming the contents of the log.
Dropping it down to `trace` level from `debug` to help improve readability.
> Remove excessive logging message

- server/base/src/main/java/org/apache/accumulo/server/manager/recovery/RecoveryPath.java
Make RecoveryPath more strictly check that a WAL file path includes the expected server that created it, and improve exception messages.
This fixes #4087
> Make RecoveryPath more strict

- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
Noticed error logging from the compactor process and found it was caused by a race condition.  The logging indicated a compaction was not running when it was expected to, but the compaction started shortly after.  The background thread had not yet populated a set that the foreground thread was examining.  Adjusted the error logging to debug since it can happen spuriously.
> Adjusts compactor error logging because of race

- core/src/main/java/org/apache/accumulo/core/Constants.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java
- minicluster/src/test/java/org/apache/accumulo/minicluster/MiniAccumuloClusterClasspathTest.java
- minicluster/src/test/java/org/apache/accumulo/minicluster/MiniAccumuloClusterTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/BulkFailedCopyProcessor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/LogSorter.java
LogSorter was creating a ThreadPool based off of the property TSERV_WAL_SORT_MAX_CONCURRENT, but then the reference to the thread pool was being overwritten to a thread pool that is created to copy failed bulk import files.
Fixes #4235
> LogSorter was creating a ThreadPool and not using it

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/gc/src/main/java/org/apache/accumulo/gc/GCRun.java
- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectionAlgorithm.java
- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectionEnvironment.java
- server/gc/src/test/java/org/apache/accumulo/gc/GarbageCollectionTest.java
Removes the property allowing disabling of the in-use GC candidate deletion feature. 
closes #4240
> Makes inuse GC deletion default behavior

- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
Fixed bug, by replacing `System.currentTimeMillis()` with `System.nanoTime()`. 
Fixes  [issue 4245](https://github.com/apache/accumulo/issues/4245)
> Replaced System.currentTimeMillis() with System.nanoTime()

- server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletGoalState.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletManagementIterator.java
- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
VolumeIT was failing because of two problems with volume replacement. First, tablets needing volume replacement were being assigned preventing volume replacement from happening. A change was made to TabletGoalState to fix this.  Second when tablet was assigned to dead server, the location of the dead server was never removed preventing volume replacement.  A change was made to TabletManagementIterator to fix this.
> fixes volume replacement failures

- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/SplitRecovery12to13.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitRecoveryIT.java
SplitRecoveryIT is a tricky test to maintain because it is testing upgrade code that deals with older metadata columns that Accumulo no longer recognizes.  This commit adjust the test to work with recent changes to the metadata schema in the elasticity branch.
> fixes SplitRecoveryIT to work with newer columns

- server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletManagementIterator.java
This commit fixes #4251.  The WalSunnyDayIT was failing because the root tablet needed recovery, but the tablet mgmt iterator was not indicating this becaue the manager was in safe mode.  Therefore recovery never happened and the test timed out.
> always sets needs recovery flag in tablet mgmt iterator

- core/src/main/java/org/apache/accumulo/core/util/compaction/ExternalCompactionUtil.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterControl.java
- test/src/main/java/org/apache/accumulo/test/functional/MemoryStarvedMajCIT.java
It appears that the test was stopping the Compactors, but not waiting for their ZooKeeper locks to be removed, before moving on and checking the number of zookeeper locks. I think what was happening is that the test code moved forward thinking that the Compactors were stopped, but the Compactors were actually stopping after this point and during the next step in the test.
> Resolved timeout issue in MemoryStarvedMajCIT

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/TabletBase.java
MemoryStarvedScanIT was timing out because the IT was deleting tables as part of the test and scans on the new FATE table were being blocked because of the low memory condition. Adjusted the check for whether the table is a user table or not to include all tables in the accumulo namespace.
> Fixed MemoryStarvedScanIT timeout

- test/src/main/java/org/apache/accumulo/test/RecoveryIT.java
Test was waiting for 60s to confirm that recovery logs were sorted. However, the default interval for checking if recovery logs needed to be sorted was 1m. Increased the timeout in the test so that it would not fail.
> Fixed RecoveryIT timeout issue

- test/src/main/java/org/apache/accumulo/test/functional/FateStarvationIT.java
This test had two problems.  First it was using the offline operation to check if all compactions were finished.  However compactations that were queued in fate when the offline started would start after the offline and potentially have fate locks for the check at the end of the test. Second the test starts a large number of compactions, but there was only one compactor process.  Started multiple compactor process to process compactions faster.
> fixes FateStarvationIT

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- server/compaction-coordinator/src/test/java/org/apache/accumulo/coordinator/CompactionCoordinatorTest.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/compactor/src/test/java/org/apache/accumulo/compactor/CompactorTest.java
Adds a property to configure the max wait interval in the compactor as well as the minimum wait period.
Changes the logic in compaction-coordinator to use this new property when calculating the wait period for sending warning messages
closes #4217
> Add Compaction Job Min & Max Wait properties

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientTabletCacheImpl.java
When writing to unhosted ondemand tablets the batch writer was performing a metadata lookup per mutation before it requested hosting.  This was of course extremely slow.  This commit makes a quick change to perform a metadata lookup per extent instead of per mutation.  This could be further improved because its still not as good as the pre elasticity code. There is an ELASTICITY_TODO in the commit about further improvements.
This is a massive improvement.  Was running FateStarvationIT which writes 100K rows.  Without this change it took 53 secs.  With this change it took 1.7 secs.
This mostly solves #3708, there may be some further minor improvements that could be made.
> avoids a metadata lookup per mutation for batch writer

- server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java
A test in MergeIT was running slower than expected. Debugged and saw the following happen in the manager logs.
```
2024-02-20T22:21:40,578 80 [manager.Manager] INFO : Tablet hosting requested for: 1;row_0000000250<
2024-02-20T22:21:40,587 80 [manager.EventCoordinator] DEBUG: Tablet hosting requested for 3 tablets in 1
2024-02-20T22:21:42,718 93 [manager.EventCoordinator] DEBUG: tablet 1;row_0000000250< was unloaded from localhost:35711
2024-02-20T22:21:45,136 85 [manager.Manager] INFO : Tablet hosting requested for: 1;row_0000000250<
2024-02-20T22:21:45,136 85 [manager.Manager] TRACE: Ignoring hosting request because it was recently requested 1;row_0000000250<
2024-02-20T22:21:45,242 98 [manager.Manager] INFO : Tablet hosting requested for: 1;row_0000000250<
2024-02-20T22:21:45,242 98 …
```
> replaces hosting requested cache with in progress set

- core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/PopulateMetadataTable.java
- test/src/main/java/org/apache/accumulo/test/ImportExportIT.java
- test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java
This PR changes the logic in PopulateMetadataTable to make all tablets in an imported table ONDEMAND.
Other minor improvements were made to that file and and IT was added to test these changes.
> Set all tablets availability to ONDEMAND on import

- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/FateIT.java
Closes #4266
This adds a test `testRepoFails()` to `FateIT` in 2.1 which ensures `undo()` is called and in the expected order when an error occurs in a Repo's `call()` or `isReady()` methods.
> FateIT Repo Error Test

- test/src/main/java/org/apache/accumulo/test/fate/accumulo/FateStoreIT.java
This test was failing because delete() requires a certain Status. This PR adds that status before calling delete.
This started failing because of the changes added in #4242.
I also removed a stray semicolon that was in the test case.
> Fix AccumuloStoreFateIT.testCreateWithKeyInProgress

- core/pom.xml
- core/src/main/java/org/apache/accumulo/core/conf/ConfigCheckUtil.java
- core/src/main/java/org/apache/accumulo/core/conf/SiteConfiguration.java
- core/src/test/java/org/apache/accumulo/core/conf/ConfigCheckUtilTest.java
- core/src/test/java/org/apache/accumulo/core/conf/DefaultConfigurationTest.java
- server/base/src/main/java/org/apache/accumulo/server/conf/ServerConfigurationFactory.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/UpgradeCoordinator.java
Backported second parameter to CheckConfigUtil.validate and updated all call locations to supply the second parameter. Added method to UpgradeCoordinator to call CheckConfigUtil.validate after the upgradeMetadata method is called on all Upgraders
Fixes #3972
> Added validation of configuration during upgrade

- test/src/main/java/org/apache/accumulo/test/ScanConsistencyIT.java
The following failure was observed when running ScanConsistencyIT in the elasticity branch.
```
java.util.concurrent.ExecutionException: java.util.NoSuchElementException
at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
at org.apache.accumulo.test.ScanConsistencyIT.testConcurrentScanConsistency(ScanConsistencyIT.java:186)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: …
```
> fixes intermittent failure in ScanConsistencyIT

- server/base/src/main/java/org/apache/accumulo/server/manager/state/MetaDataStateStore.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletStateChangeIterator.java
- test/src/main/java/org/apache/accumulo/test/manager/SuspendedTabletsIT.java
There was code in the manager that seemed to have the intent of clearing suspension markers in tablets for an offline table.  This code was not working or tested.  This commit fixes this code and adds a tests that validates that suspension markers are removed when a table is taken offline.
fixes #3314
> fixes clearing suspension for offline tables

- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadata.java
Remove unused `supressError` boolean argument from `setOperationIdOnce` method in `TabletMetadata` class.
Adjust JavaDoc accordingly.
> Remove unused argument in setOperationIdOnce

- server/base/src/main/java/org/apache/accumulo/server/conf/store/impl/ZooPropStore.java
- removed unnecessary suppression of PREDICTABLE_RANDOM that is not needed.
> Remove unneeded SuppressFBWarnings annotation from ZooPropStore

- core/src/main/java/org/apache/accumulo/core/fate/accumulo/AccumuloStore.java
- test/src/main/java/org/apache/accumulo/test/fate/accumulo/AccumuloStoreIT.java
When FATE cleans up transactions that are successful, it will check the `auto_clean` flag and if set will delete the transaction. But if it is false or not set then it will iterate over all the repos and call pop to remove them to save space so we need to add `SUCCESSFUL` to the allowed statuses for pop, along with `FAILED_IN_PROGRESS`.
We don't need to add `FAILED` because when `FAILED_IN_PROGRESS` is set FATE will already pop all the repos and clean up before setting the status to `FAILED` so pop should never be called in a `FAILED` state.
This closes #4300
> Allow a status of Successful when popping FATE repos

- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/DistributedReadWriteLock.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/ChangeTableState.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/Utils.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/clone/CloneTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/clone/CloneZookeeper.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/clone/FinishCloneTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/CompactRange.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/cancel/CancelCompactions.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/cancel/FinishCancelCompaction.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/create/CreateTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/create/FinishCreateTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/create/PopulateZookeeper.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/CleanUp.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/DeleteTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/PreDeleteTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/TableRangeOp.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/TableRangeOpWait.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/namespace/create/FinishCreateNamespace.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/namespace/create/PopulateZookeeperWithNamespace.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/namespace/delete/DeleteNamespace.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/namespace/delete/NamespaceCleanUp.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/namespace/rename/RenameNamespace.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/rename/RenameTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableExport/WriteExportFiles.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/FinishImportTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/ImportPopulateZookeeper.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/ImportTable.java
- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/FateIT.java
Instead of using a boolean value for obtaining table locks, use an enum which makes the code more readable and makes it easier to search and catch errors with the lock type. The enum used already existed in DistributedReadWriteLock. 
This closes #4276
> Replace boolean with enum for table locks in 3.1

- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/DistributedReadWriteLock.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/ChangeTableState.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/Utils.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/availability/SetTabletAvailability.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/clone/CloneTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/clone/CloneZookeeper.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/clone/FinishCloneTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/CompactRange.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/cancel/CancelCompactions.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/cancel/FinishCancelCompaction.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/create/CreateTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/create/FinishCreateTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/create/PopulateZookeeper.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/CleanUp.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/DeleteTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/PreDeleteTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/FinishTableRangeOp.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/TableRangeOp.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/namespace/create/FinishCreateNamespace.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/namespace/create/PopulateZookeeperWithNamespace.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/namespace/delete/DeleteNamespace.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/namespace/delete/NamespaceCleanUp.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/namespace/rename/RenameNamespace.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/rename/RenameTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableExport/WriteExportFiles.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/FinishImportTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/ImportPopulateZookeeper.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/ImportTable.java
Instead of using a boolean value for obtaining table locks, use an enum which makes the code more readable and makes it easier to search and catch errors with the lock type. The enum used already existed in `DistributedReadWriteLock`. This PR is for the same changes to elasticity as in main that is being done in #4297. Because everything conflicts #4297 will need to be merged forwards from main to elasticity as an empty commit and then this can be merged.
This closes #4276
> Replace boolean with enum for table locks in Elasticity

- core/src/main/java/org/apache/accumulo/core/manager/state/TabletManagement.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletManagementIterator.java
The tablet mgmt iterator was configuring a scanner to fetch almost all of the tablets columns.  Since most columns were being fetched the filtering offered no benefit and probably added extra cost.  It also added code complexity.  This commit removes the fetch columns calls on the scanner so that everything is fetched.
> fetches all columns in tablet mgmt iterator

- server/manager/src/main/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueue.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/queue/CompactionJobQueues.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueueTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/queue/CompactionJobQueuesTest.java
Adds a unit test that concurrently calls add() and poll() on CompactionJobsQueues. This test validates that race conditions between these methods are handled. Fixed a race condition found by running the test.
> Adds race condtion test for CompactionJobQueues

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/CompactionDriver.java
CompactionDriver.cleanupTabletMetadata was not fetching the newly added metadata column USER_COMPACTION_REQUESTED causing CompactionExecutorIT and ExternalCompaction_2_IT to fail. The column was added in #4254.
> Fixed CompactionDriver after new column added to metadata

- core/src/main/java/org/apache/accumulo/core/Constants.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/SimpleCompactionDispatcher.java
- server/base/src/main/java/org/apache/accumulo/server/conf/CheckCompactionConfig.java
- test/src/main/java/org/apache/accumulo/test/compaction/BadCompactionServiceConfigIT.java
Fixes the documentation which directed users to use "selected" while the code actually checked for "selector".
Also replaced the hardcoded "default" compaction service name string with a constant.
> Fixes compaction dispatcher documentation

- test/src/main/java/org/apache/accumulo/test/fate/accumulo/AccumuloFateIT.java
- test/src/main/java/org/apache/accumulo/test/fate/accumulo/AccumuloStoreFateIT.java
- test/src/main/java/org/apache/accumulo/test/fate/accumulo/AccumuloStoreIT.java
This commit updates the different FATE ITs to create the test table that is used to match the same configuration that is used when creating the system table in InitialConfiguration.
This closes #4321
> Update FATE tests to create fate table with system config

- test/src/main/java/org/apache/accumulo/test/functional/MetadataIT.java
This adds tests to verify that the table properties that are related to correctness of the system tables (root and metadata) are set properly when the configuration is initialized
This closes #4330
> Add test to verify Root and Metadata tables are correctly initalized

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftTransportKey.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftTransportPool.java
- core/src/main/java/org/apache/accumulo/core/rpc/ThriftUtil.java
- core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java
- core/src/main/java/org/apache/accumulo/core/rpc/clients/ThriftClientTypes.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/ThriftTransportKeyTest.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- test/src/main/java/org/apache/accumulo/test/TransportCachingIT.java
The previous logic in this class would gather all of the Tserver ZNodes in ZooKeeper, then get the data for each ZNode and validate their ServiceLock. Then, after all of that it would randomly pick one of the TabletServers to connect to. It did this through the ZooCache object which on an initial connection would be empty and causes a lot of back and forth to ZooKeeper. The side effect of this is that the ZooCache would be populated with TabletServer information.
This change modifies the ClientContext to populate the ZooCache in a single-shot background task and modifies the default logic for getting a connection to a TabletServer. The new logic will make 2 calls to ZooKeeper in the best case scenario, one to get the list of TServer ZNodes in Zookeeper and another to get the ZNode data …
> Optimized logic for getting a random TabletServer connection

- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/CompactionCoordinatorTest.java
Changes the compaction coordinator to not return jobs for a table that is offline.  The point where this check was added to the coordinator needed unit test, so also added the unit test.
> Unit test compaction reservation and deny offline

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/split/UpdateTablets.java
- server/manager/src/test/java/org/apache/accumulo/manager/tableOps/split/UpdateTabletsTest.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitIT.java
Made the following changes to the split code that adds new tablets and updates the existing tablet.
* fixed potential NPE w/ tablet operation id check by reversing order of equals check
* Throws IllegalStateException when attempting to split tablet with merged or cloned markers
* Removed adding wals when creating new tablets in split, its not expected that the parent tablet would have wals and this is checked earlier
* Deleted any user compaction requested, hosting requested, suspended, or last columns in the parent tablet
Added a unit test that attempts to exercise the split code with all tablet columns.  The unit test also has a set of tablet columns that were verified to work with split and it is checked against the set of columns in the code.  The purpose of this test is to fail when …
> Considers all tablet metadata columns in split code

- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/state/TableStats.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/CleanUp.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/DeleteTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/ReserveTablets.java
Noticed an integration test was taking 0 to 5 seconds to delete a table. Investigated this and found some code in delete table that was waiting on the TabletGroupWatcher to cycle as the cause of the delay.
Investigated why this wait was there and could not find a definite answer.  Speculating that the purpose of the wait was to deal with possible concurrent writes to tablet metadata by the tablet group watcher in the case it has not yet noticed the table state is DELETING. Changes in elasticity make this wait unnecessary because the delete table fate sets an operation id on each tablet that should prevent any writes to the tablet after its set.  After being set this would prevent any in flight writes by the tablet group watcher from succeeding. Before elasticity there was no way for the …
> fixes bug and removes unneeded wait in delete table

- core/src/main/java/org/apache/accumulo/core/file/blockfile/cache/lru/LruBlockCache.java
- core/src/main/java/org/apache/accumulo/core/file/blockfile/cache/tinylfu/TinyLfuBlockCache.java
The LRU caches use a thread pool with 1 thread to generate cache statistics. The pool size is not configurable. It seems unnecessary to produce detail pool metrics for these caches. This disable metrics for those caches.
other minor changes:
* resolve quality check for missing isPresent for weighted size, default to 0 if not present (in TinyLfuBlockCache)
* other minor quality check improvements. (final variables, unneeded initialization...)
Breaking up general metrics changes into small PRs to make reviews easier.
> Remove pool metrics instrumentation from LRU caches

- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
- core/src/main/java/org/apache/accumulo/core/fate/ReadOnlyFateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/ZooStore.java
- core/src/main/java/org/apache/accumulo/core/fate/accumulo/AccumuloStore.java
- core/src/main/java/org/apache/accumulo/core/logging/FateLogger.java
- core/src/test/java/org/apache/accumulo/core/fate/TestStore.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/DeadCompactionDetector.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/commit/PutGcCandidates.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/commit/RefreshTablet.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_1_IT.java
- test/src/main/java/org/apache/accumulo/test/fate/accumulo/FateStoreIT.java
Compactors were waiting on the Fate transaction that does compaction commit.  They were doing this so that the dead compaction detector would not kill the compaction during commit.  This change removes the need for compactors to wait on compaction commit, freeing them to run another compaction.
To accomplish this the dead compaction detector was modified to look for fate operations commiting compactions.  This work leveraged the new FateKey.  A bonus for this changes is that duplicate RPC messages reporting a compaction as completed will no longer spin up duplicate Fate operations to commit.  The Fate operations would have likely been harmless, but would have consumed resources.
A new method was added to Fate to list transactions with a certain FateKeyType.  Tests were added for this new …
> Stop waiting on fate when reporting compaction complete

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/DeleteRows.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/MergeTablets.java
- server/manager/src/test/java/org/apache/accumulo/manager/tableOps/merge/MergeTabletsTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/tableOps/split/UpdateTabletsTest.java
Adds tests for all tablet metadata columns to ensure the merge code handles them.  Some columns were not handled, so new code was added to handle them.
In the process of adding unit test for the merge code, also added test for some odd conditions in the code that would be hard to test in an integration test.
> Updates merge code to handle all tablet metadata columns

- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/TabletMetadataTest.java
This PR is to address the comment https://github.com/apache/accumulo/pull/4354#discussion_r1518637550
Before this change if stream() was used the the TabletsMetadata close method still had to be called manually as the close method on the stream did not delegate. With this change if the stream is used in a try-with-resources to autoClsoe the stream or if the stream is closed manually, TabletsMetadata will also be closed.
Note that in 2.1, there wasn't anything else to update but the stream() method itself (and a test) because currently there is no where in the code that calls the onClose() method on a stream, but in main and elasticity there are so I will have follow on PRs/changes for those branches.
I thought it was best to change this in 2.1, 3.1 and elasticity so it's consistent and we …
> Update TabletsMetadata stream() to autoclose TabletsMetadata - 2.1

- core/src/main/java/org/apache/accumulo/core/fate/AdminUtil.java
- core/src/main/java/org/apache/accumulo/core/fate/AgeOffStore.java
- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
- core/src/main/java/org/apache/accumulo/core/fate/ReadOnlyTStore.java
- core/src/main/java/org/apache/accumulo/core/fate/ZooStore.java
- core/src/main/java/org/apache/accumulo/core/logging/FateLogger.java
- core/src/test/java/org/apache/accumulo/core/fate/AgeOffStoreTest.java
- core/src/test/java/org/apache/accumulo/core/fate/TestStore.java
This PR replaces the use of a long and a TimeUnit with a Duration object. The motivation behind this change is to use the Duration object to simplify and make usage more evident.
> Replace long + TimeUnit with Duration in ReadOnlyTStore.unreserve()

- core/src/main/java/org/apache/accumulo/core/file/rfile/GenerateSplits.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/GenerateSplitsTest.java
Adds an explicit error message when base64 encoding should have been used. 
Removes special character modification in favor of the user piping the output to `base64 -d`
closes: 4347
> Throw error when non-standard chars exist

- core/src/main/java/org/apache/accumulo/core/metadata/TabletState.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletGoalState.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletManagementIterator.java
Removed the logic that always returns the TabletMetadata when the Manager state is not normal, or there are no tablet servers, or no online tables. The code now just calls computeTabletManagementActions in all cases.
Closes #4256
> Removed special handling logic in TabletManagementIterator

- core/src/main/java/org/apache/accumulo/core/util/compaction/RunningCompaction.java
While working on #4382 I ran into an issue where a CME was being raised in a Thrift thread that was trying to serialize the updates from the RunningCompaction object.
> Fixes ConcurrentModificationException in RunningCompaction

- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/compactor/src/test/java/org/apache/accumulo/compactor/CompactorTest.java
* Start threadpools when service is run, not when it is constructed (and importantly, after metrics have been fully initialized); this ensures that ServerContext, which is created during construction, is available before threadpools and metrics are started
* Use Supplier to start lazily load security operation instead of calling abstract impl method in constructor (bad practice)
* Remove unneeded second constructor with config overrides (can provide overridden config in test subclass instead)
* Remove redundant printStartupMsg (already printed the same details in AbstractServer base class)
* Make sure SuccessFulCompactor's close method is called in try-with-resources to remove unclosed resource warning in CompactorTest
> Several small improvements to Compactor impl

- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
- core/src/main/java/org/apache/accumulo/core/fate/MetaFateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/user/FateMutator.java
- core/src/main/java/org/apache/accumulo/core/fate/user/FateMutatorImpl.java
- core/src/main/java/org/apache/accumulo/core/fate/user/StatusMappingIterator.java
- core/src/main/java/org/apache/accumulo/core/fate/user/UserFateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/user/schema/FateSchema.java
- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/metrics/fate/FateMetrics.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/UpgradeCoordinator.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_1_IT.java
- test/src/main/java/org/apache/accumulo/test/fate/FateStoreIT.java
- test/src/main/java/org/apache/accumulo/test/fate/meta/MetaFateIT.java
- test/src/main/java/org/apache/accumulo/test/fate/meta/MetaFateOpsCommandsIT.java
- test/src/main/java/org/apache/accumulo/test/fate/meta/MetaFateStoreFateIT.java
- test/src/main/java/org/apache/accumulo/test/fate/meta/ZooMutatorIT.java
- test/src/main/java/org/apache/accumulo/test/fate/user/FateMutatorImplIT.java
- test/src/main/java/org/apache/accumulo/test/fate/user/UserFateIT.java
- test/src/main/java/org/apache/accumulo/test/fate/user/UserFateOpsCommandsIT.java
- test/src/main/java/org/apache/accumulo/test/fate/user/UserFateStoreFateIT.java
- test/src/main/java/org/apache/accumulo/test/fate/user/UserFateStoreIT.java
- test/src/main/java/org/apache/accumulo/test/functional/FateConcurrencyIT.java
- test/src/main/java/org/apache/accumulo/test/functional/FunctionalTestUtils.java
This renames ZooStore to `MetaFateStore` and AccumuloStore to `UserFateStore` to be more descriptive and better align with what the different Fate stores are used for. This also aligns the names with the FateInstanceType enum.
This closes #4253
> Rename Fate store implementations

- server/tserver/src/main/java/org/apache/accumulo/tserver/UnloadTabletHandler.java
Resolved TODO in UnloadTabletHandler by using the Tablets metadata reference, removing the code that was looking up the tablet metadata.
> Modified UnloadTabletHandler to use Tablets metadata

- minicluster/src/main/java/org/apache/accumulo/minicluster/MiniAccumuloConfig.java
- minicluster/src/main/java/org/apache/accumulo/minicluster/MiniAccumuloRunner.java
These methods are removed in the elasticity branch in favor of a cluster server configuration object
> Deprecated MiniAccumuloConfig setNumServer methods

- test/src/main/java/org/apache/accumulo/test/compaction/CompactionConfigChangeIT.java
The test waits for 60s for the number of F files to reach zero. However, there are 100 files and there is a comment that says each compaction should take about 1s. I reduced the number of files from 100 to 50 to allow the test to complete in the allotted time.
> Reduced number of compactions in CompactionConfigChangeIT

- core/src/main/java/org/apache/accumulo/core/client/ClientSideIteratorScanner.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/OfflineIterator.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ScannerImpl.java
- test/src/main/java/org/apache/accumulo/test/ClientSideIteratorIT.java
Accumulo code that ran user iterators client side would throw an unsupported operations exception when attempting to access the PluginEnv.  This commit adds support for PluginEnv in situations where iterators are run client side.
> adds PluginEnv support to client side iterators

- server/manager/src/main/java/org/apache/accumulo/manager/FateServiceHandler.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/split/FindSplits.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/split/PreSplit.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/split/UpdateTablets.java
Removed TODOs in the code related to #3415, #3709, #3412.  These todos were done or had issues opened.
Added some best effot checks to avoid doing splits if a table is offline. The checks have race conditions as the table lock is not acquired by the split fate op.  However as outlined in a comment on #3412 the offline code that waits could be made more comprehensive to account for this.
One TODO was handled by using
`Ample.RejectionHandler.acceptAbsentTablet()` which likely did not exists when the TODO was written.
> cleaned up a few TODOs in the split code

- server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java
There are several tests in TServerUtilsTest that have the form:
```
TServer server = null;
try {
ServerAddress address = startServer();
server = address.getServer();
} finally {
if (server != null) {
server.stop();
}
}
```
The TServerUtilsTest.startServer method calls TServerUtils.startServer which ends up creating a Thread that calls TServer.serve(). When TServer is a TThreadPoolServer, the serve method calls preServe first, which sets the internal boolean variable `stopped_` to false, and then calls execute which will loop while `stopped_` is false.
In the case where the Thread created by TServerUtils.startServer is not started right away, then it's possible that the test method will call stop (setting `stopped_` to true) before the TServer.serve method calls preServe (setting …
> Fixed race condition in TServerUtils exposed by TServerUtilsTest

- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
Code was commented out in the Monitor that called
TabletClientHandler.getActiveCompactions. This method was removed when major compactions were removed from the tserver, then restored in #3827 because we still need to report minor compaction stats to the monitor.
> Uncommented code in Monitor that retrieved TServer active compactions

- pom.xml
- shell/src/test/java/org/apache/accumulo/shell/commands/HistoryCommandTest.java
Jline `3.24.1` throws an illegal reflective access warning when starting an accumulo shell.
```
$ ./accumulo shell
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jline.terminal.impl.exec.ExecTerminalProvider$ReflectionRedirectPipeCreator (file:/data/workspace/fluo-uno/install/accumulo-2.1.3-SNAPSHOT/lib/jline-3.24.1.jar) to constructor java.lang.ProcessBuilder$RedirectPipeImpl()
WARNING: Please consider reporting this to the maintainers of org.jline.terminal.impl.exec.ExecTerminalProvider$ReflectionRedirectPipeCreator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Shell - Apache Accumulo Interactive Shell
- …
```
> Fix Illegal Reflective Access Warning in Shell

- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_2_IT.java
The comment said that the operation id needed to be set when deleting the tablets. This is now done in ReserveTablets.isReady.
> Removed elasticity comment to do in ExternalCompaction_2_IT

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientTabletCache.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientTabletCacheImpl.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/ClientTabletCacheImplTest.java
For ondemand tablets the client tablet cache caches tablets w/o a location.  There was a bug fixed in #4280 where the cache would do a metadata table lookup for each mutation when tablets had no location. The fix in #4280 only partially fixed the problem, after that change more metadata lookups than needed were still being done.
Also there was a bug with the batchscanner that #4280 did not address. Before this change when tablets had no location, the batch scanner would do a metadata lookup for each range passed to the batch scanner (well the client tablet cache would these metadata lookups on behalf of the batch scanner).  For example before this change if the batch scanner was given 10K ranges that all fell in a single tablet w/o a location, it would do 10K metadata lookups.  After this …
> avoid unnecessary metadata reads in client tablet cache

- server/tserver/src/main/java/org/apache/accumulo/tserver/AssignmentHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
Tablet servers have a lock for recovery that has the purpose of preventing concurrent recovery of tablets using too much memory. This lock is acquired for tablets that have no walogs and will therefore do no recovery.  This commit changes the code to only obtain the lock when there are walogs.
Noticed this while reviewing #4404 and while researching found [ACCUMULO-1543](https://issues.apache.org/jira/browse/ACCUMULO-1543) which is an existing issue describing this change.
> avoids acquiring recovery lock when tablet has no wals

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/TabletRefresher.java
Other exceptions which could be more serious than TException would be raised as an ExecutionException when get() is called on the Future and would result in a RuntimeException being raised from TabletRefresher.refreshTablets. If a TException is thrown, then the refresh for all of the Tablets will be retried unless the TabletServer is no longer online.
> Removed TODO in TabletRefresher

- core/src/main/java/org/apache/accumulo/core/metadata/TabletLocationState.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadata.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/TabletMetadataTest.java
Previously the private reference for the extent inside TabletMetadata was passed to the TabletLocationState constructor inside of getTabletState(). The extent may not have been loaded at this point as it is lazy loaded by the getExtent() method and requires PREV_ROW to have been fetched. This change now uses the getter to make sure we do not inadvertently pass a null extent which is invalid.
I discovered this bug while working on https://github.com/apache/accumulo/pull/4437
> Ensure getTabletState() in TabletMetadata does not allow a null extent

- core/src/main/java/org/apache/accumulo/core/metadata/TabletLocationState.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadata.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/TabletMetadataTest.java
This commit refactors all of the fields to be final for TabletMetadata. The object is already treated as immutable in practice, but previously didn't declare fields final so this could lead to potential future bugs and also means not being able to guarantee the state of a field which is now possible.
This was originally done this way to make the construction of the object simpler when constructing from a row as there are so many fields. This refactoring adds a new builder that is used to construct the object and passes that to the constructor so we don't need constructor arguments for all values which simplifies things.
This change will now allow verifying state going forward during construction (such as requiring the files map to be non null) which should reduce the chance for future …
> Update TabletMetadata to be immutable

- server/base/src/main/java/org/apache/accumulo/server/manager/state/AbstractTabletStateStore.java
AbstractTabletStateStore.setFutureLocations was throwing an exception
when it could not set a future location in a tablets metadata. However,
it's possible that a concurrent FATE operation could prevent this and
this is not an error conditition. Modified the code to log a msg instead
as TabletGroupWatcher in the Manager will retry to assign the tablet when
the FATE operation has concluded and assignment is still needed.
> Logged msg instead of throwing exception in setFutureLocations

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/base/src/main/java/org/apache/accumulo/server/util/FileUtil.java
In 4.0.0 split code will no longer run in the tablet server.  This change deprecates a split related property that includes tablet server in the property perfix and replaces it with a property that does not include tablet sever.
> Renames split property to avoid tserver

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanfileManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
In #4436 a tablet update was moved to use conditional mutations. The changed checked tablets current location in the conditional update. However when this code was called in the Tablet constructor the tablet server was the future location.  Adjusted to code to check for the future location when calling from the constructor.
> fixes conditional mutation bug when loading tablet

- assemble/bin/accumulo-cluster
When trying to start and stop multiple groups of scan servers using the accumulo-cluster script the groups would interfere with each other. This change fixes that by making the the scan servers use the group in the instance id like compactors do.
Ran into this while workiing on #4444 and pulled it out as a stand alone fix.
> fixes bug with starting multiple group of scan servers

- server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletManagementIterator.java
- test/src/main/java/org/apache/accumulo/test/functional/TabletManagementIteratorIT.java
Many places in the accumulo code will read a batch of key/values and then use the last key in the batch to construct a range to get the next batch.  The last key in the batch will be a non inclusive start key for the range.  The tablet mgmt iterator was not handling this case and returning the key that should have been excluded.
> fixes continue scan in tablet mgmt iterator

- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
Added logic in the SimpleGarbageCollector that will periodically log a warning when there are no compactors running for the system tables' resource group.
Fixes #4318
> Log warning when no Compactors for system tables

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Changes tablet server code that refreshes tablet metadata to read tablet metadata for multiple tablets in a batch.  Also noticed the refresh code was not handling some race condition correctly and could result in spurious error messages.  It was also not handling closed tablets. Refactored the code to return false when refresh is not possble for acceptable reasons instead of throw an error.  This will cause the the RPC to retry for those tablets later.  Also remove some code that was attempting to handle complex race conditions that would be hard to test, realized if these conditions do happen that it would be best to retry rather than try to handle them.
> batches reading tablet metadata for refresh

- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
Cleanup of the set of migrating tablets would read the entire metadata table and read all tablet extents into memory. This changes limits the scan to the tablets section of the metadata table and avoids reading all tablet extents into memory.
> improves efficiency of migration set clean up

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
Log when the manager reaches out to tablet server and ask it to compact a tablet and it decides there is nothing to do.  The logging includes the data used to make the decision.
> logs when tablet decides there is nothing to do for user compaction

- core/src/main/java/org/apache/accumulo/core/iterators/user/GrepIterator.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/GrepIteratorTest.java
- shell/src/main/java/org/apache/accumulo/shell/commands/GrepCommand.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellIT.java
Add visibility as one of the critera that the grep searches
> Add visibility to grep searches

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
There was check in the tablet refresh code that was preventing tablet refresh while a tablet was in the middle of closing.  Modified the check to only prevent refresh after a tablet is competely closed.
fixes #4477
> allows tablet refresh while in the process of closing

- test/src/main/java/org/apache/accumulo/test/functional/TabletResourceGroupBalanceIT.java
The assertion in testResourceGroupBalanceWithNoTServers started returning zero for the number of hosted tablets after the `waitForBalance`. Not sure which modification caused this to change behavior, but this fix is likely the correct one regardless.
> Fixed check in TabletResourceGroupBalanceIT to use Wait.waitFor

- core/src/main/java/org/apache/accumulo/core/metrics/MetricsProducer.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- test/src/main/java/org/apache/accumulo/test/functional/MemoryStarvedScanIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ZombieTServer.java
Fixes #4499 CI test failures.
- Adds metrics initialization for AbstractServer - 3.1 Change added extends MetricProducer to AbstractServer.
- Adds metrics initialization to test class ZombieTServer to match metrics needed in TabletServer and needed for thrift metrics.
- Removes extra dot in scan paused metrics tags:
- METRICS_SCAN_PAUSED_FOR_MEM was `accumulo.tserver.scans..paused.for.memory`
- METRICS_SCAN_RETURN_FOR_MEM was `accumulo.tserver.scans..return.early.for.memory`
> Fix LateLastContactIT, MemoryStarvedScanIT test failures after metrics merge

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerMetricsUtil.java
Removes references to hadoop 2 metrics that are obsolete with micrometer metrics adoption
Removes unused and deprecated properties:
- GC_METRICS_ENABLED
- MANAGER_FATE_METRICS_ENABLED
Also removes a javadoc comment reference.
Fixes #4501
> Address obsolete hadoop 2 metrics references. 

- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionMetricsIT.java
A recent Jenkins build failed with this test.  It passes locally.  This add metrics logging to file option will provide additional information to help troubleshoot if it continues to fail on Jenkins.
> enable metrics log to file for ExternalCompactionMetricsIT

- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
The log message set to trace in this PR was consuming 20% to 30% of the logs for the compaction coordinator.
> sets compaction coordinator status update log to trace

- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/DeadCompactionDetector.java
For the case of really quick compactions there is a good chance these finish during the check done by the dead compaction detector.  Currently when this happens a log message is logged about a possible dead compaction that is a false positive.  A large number of quick external compactions can cause a lot of these false positives.
This change adjust the first time a possible dead compaction is logged to trace.
> lowers logging level for first seen dead compaction

- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
The tablet server group watcher loop will not make progress when it encounters an RPC error on a single tablet server.  It should continue communicating with the tablet servers it can inorder to make progress in its loop that assigns and unassigns tablets.
> Handles RPC errors when requesting tablet unload

- core/src/main/java/org/apache/accumulo/core/metrics/MetricsProducer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServerMetrics.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ThriftScanClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerScanMetrics.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/ScanServerTest.java
- test/src/main/java/org/apache/accumulo/test/metrics/MetricsIT.java
This PR is based on the changes proposed by @keith-turner in #4458, using the changes in #4459 as the base.
- includes updated documentation in MetricsProducer
- includes cache metrics for table metadata cache in sserver (resolves todo)
These changes have not be test yet.
These changes should not be merged until #4459 is complete.
> scan server metrics from #4458 based on #4459

- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/ScanServerTest.java
These changes are a follow-on to #4461 - and include the file reservation metrics in additional places.  The omission was noticed while merging #4461 into main.
> Update scan server metrics for file reservations

- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
The host:port is added by services to help identify the lock source. This does not replace the http_addr advertisment.
> Add the host:port information to the monitor service lock

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/base/src/test/java/org/apache/accumulo/server/rpc/TServerUtilsTest.java
Changed the default value of TSERV_PORTSEARCH from false to true to provide some consistency in the PORTSEARCH properties. The default values for the Compactors and ScanServers is already set to true.
Closes #4476
> Changed default value of TSERV_PORTSEARCH from false to true

- core/src/main/java/org/apache/accumulo/core/util/time/SteadyTime.java
- core/src/test/java/org/apache/accumulo/core/util/time/SteadyTimeTest.java
- server/manager/pom.xml
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/ManagerTime.java
- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
- server/manager/src/test/java/org/apache/accumulo/manager/ManagerTimeTest.java
This replaces Manager.getSteadyTime() long value with a concrete type to make it more apparent what time is being used. The serialization and deserialization logic have been encapsulated as methods to make the conversion consistent.
This closes #4482
> Create a SteadyTime type in the Manager

- core/src/main/java/org/apache/accumulo/core/logging/TabletLogger.java
- core/src/main/java/org/apache/accumulo/core/metadata/SuspendingTServer.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- core/src/main/java/org/apache/accumulo/core/util/time/SteadyTime.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/TabletMetadataTest.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/LoggingTabletStateStore.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/MetaDataStateStore.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletStateStore.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/ZooTabletStateStore.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/TabletMutatorBase.java
- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/UnloadTabletHandler.java
SteadyTime was added in #4494 which creates a strong type for tracking the total duration for the time the cluster has had a manager. This time is used for suspension so we this updates Ample to use the new type instead of just a long.
> Update Ample to use SteadyTime for suspension

- core/src/main/java/org/apache/accumulo/core/metrics/MetricsProducer.java
- server/manager/src/main/java/org/apache/accumulo/manager/metrics/fate/FateMetrics.java
Renames a fate metric: `accumulo.fate.ops.in.progress` to `accumulo.fate.ops`. Looking at [issues/4498](https://github.com/apache/accumulo/issues/4498), I noticed that `accumulo.fate.ops.in.progress` is a gauge of all transactions in any state (`NEW, IN_PROGRESS, FAILED_IN_PROGRESS, FAILED, SUCCESSFUL, UNKNOWN, SUBMITTED`). `in.progress` may be a bit misleading.
> Renames a fate metric

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/spi/scan/ConfigurableScanServerSelector.java
The provided plugin for working with scan servers sorts the list of scan servers fairly frequently.  This list will not change too often, so it could be sorted less to offer a better amortized cost as the total number of scan servers grows.
Also outside of the plugin, the plugin was being reset every 100ms. Removed this to give the plugin more control.  Also there is currently no way to change client config for a created Accumulo client, so there is no need to recreate the plugin.
> reduce the frequency that the list of scan servers is sorted

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/tablet/CompactableImplFileManagerTest.java
The following is an example of the problem this change fixes
1. Thread 1: A user compaction is currently running for a tablet
2. Thread 2: Tablet server receives a compaction request RPC from manager and it checks to see if the compaction is needed for the same tablet.  If finds it is needed.
3. Thread 1: completes user compaction, so a compaction is no longer needed for the tablet
4. Thread 2: Initiates a user compaction of the tablet because its check in step 2 passed.
This change adds a second check in step 4 above that should prevent this race condition because the check is done at a point when its known no concurrent user compaction is running.  The original check was left as a fail fast check, but a comment was added explaining its not sufficient for correctness.
> Fixes race condition that caused unneeded user compactions to run

- pom.xml
- server/base/pom.xml
- server/base/src/main/java/org/apache/accumulo/server/metadata/AsyncConditionalTabletsMutatorImpl.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/TabletsMutatorImpl.java
- test/pom.xml
- test/src/main/java/org/apache/accumulo/test/ample/TestAmpleIT.java
- test/src/main/java/org/apache/accumulo/test/ample/TestAmpleUtil.java
- test/src/main/java/org/apache/accumulo/test/ample/metadata/ConditionalWriterDelegator.java
- test/src/main/java/org/apache/accumulo/test/ample/metadata/ConditionalWriterInterceptor.java
- test/src/main/java/org/apache/accumulo/test/ample/metadata/TestAmple.java
- test/src/main/java/org/apache/accumulo/test/fate/ManagerRepoIT.java
This moves the TestAmple implementation out of the server/base module test jar and into the test module. TestAmple and associated classes were originally put there to match the same package as Ample but this does not work due to jars being sealed. This changes the visibility of some of the constructors and methods in order to be able to override now that TestAmple is in a new package.
This is a follow on to #4415
> Move TestAmple to test module

- core/src/main/java/org/apache/accumulo/core/metadata/SuspendingTServer.java
- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
- server/base/src/test/java/org/apache/accumulo/server/constraints/MetadataConstraintsTest.java
This adds a new metadata constraint check for the suspend metadata column to ensure that the suspension time is not negative as we should never have a negative value.
This is a follow on to #4494 as I realized when working on that we should probably add a validation check for this
I wasn't sure if we should target this at 2.1 or 3.1 but for now this is targeting 3.1 because there is a (probably very small) risk in 2.1 of something breaking if there was an unexpected negative that existed. Although maybe this isn't a big concern if an existing negative would still cause things to break in other ways (I haven't traced through to see)
> Add a constraint check for suspend column

- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
- core/src/main/java/org/apache/accumulo/core/fate/FateId.java
- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooCache.java
- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooUtil.java
- core/src/main/java/org/apache/accumulo/core/lock/ServiceLock.java
- core/src/main/java/org/apache/accumulo/core/util/UuidUtil.java
- core/src/test/java/org/apache/accumulo/core/fate/FateIdTest.java
- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ConditionalTabletMutatorImpl.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/iterators/SetEncodingIterator.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/DeleteTablets.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitMillionIT.java
The following changes were made as result of running Java Flight Recorder repeatedly on the manager and tablet server while SplitMillionIT was running.  After these changes the following methods would not show up as much in the JFR results.
* Sped up validation of FateId.  When deleting 1 million tablets, 1 million fate id are written and then read.  Was seeing the regex for validation show up when reading 1 million tablets w/ fate ids.
* Sped up getting children from ZooCache.  The code related to service locks was calling this.
* Sped up parsing of server locks by speeding up the UUID validation, that is where it was spending most of its time.
* Sped up metadata constraint.  Seeing conditional mutation metadata updates spend a lot of time checking metadata constraints.
* Sped up the …
> Fixed performance issues that were impacting SplitMillionIT

- core/src/main/java/org/apache/accumulo/core/manager/state/TabletManagement.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadata.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletManagementIterator.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/ZooTabletStateStore.java
- server/base/src/main/java/org/apache/accumulo/server/split/SplitUtils.java
- server/base/src/test/java/org/apache/accumulo/server/manager/state/TabletManagementIteratorTest.java
- server/base/src/test/java/org/apache/accumulo/server/manager/state/TabletManagementTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java
Based on profiling tablet servers while running SplitMillionIT, made the following changes related to TabletManagementIterator
* Made TabletMgmtIterator extend WholeRowIterator instead of stack on top of it.  This avoids encoding->decoding->encoding rows on the iterator stack.
* Avoided lookuping and parsing multiple table props for each tablet inorder to determine if it needs split. Moved this be done once per table.
* Changed a stream to compute file size sum into a loop.
> speeds up tablet mgmt iterator

- core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftTransportPool.java
Wake the "Thrift Connection Pool Checker" thread from sleeping during shutdown, so that it is joined quicker.
> Improve ThriftTransportPool shutdown speed

- test/src/main/java/org/apache/accumulo/test/compaction/CompactionPriorityQueueMetricsIT.java
CompactionPriorityQueueMetricsIT was waiting up to 30s for a dead compactor process to be absent in zookeeper. The default zookeeper timeout is 30s, so there was a good chance it would timeout.  Modified the zookeeper timeout in the test to 10s rather then increase the time to wait for the ZK entry to be absent.
> fixes timeout in CompactionPriorityQueueMetricsIT

- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java
- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitMillionIT.java
This change lowers the time it takes to host ondemand tablets by moving this functionality into TabletGroupWatcher.
The client RPC thread processing the hosting request can now directly call a function in TGW that will immediately start on the work of hosting the tablets.
Updated SplitMillionIT to request hosting of 200 tablets all at once instead of one by one.  This was done by using a BatchScanner instead of lots of scanners.
> lowers time to host ondemand tablets

- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadataBuilder.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMutatorBase.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ConditionalTabletMutatorImpl.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/RootTabletMutatorImpl.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/TabletMutatorImpl.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/DeleteTablets.java
Merging tables in a table deletes tablets.  When tablets were being deleted they were automatically setting a lock, which could leave junk in the metadata table.  Added a toggle to turn off setting these on mutations.
> adds toggle for automatically setting lock on mutation

- core/src/main/java/org/apache/accumulo/core/metrics/MetricsProducer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServerMetrics.java
- test/src/main/java/org/apache/accumulo/test/metrics/MetricsIT.java
Fixes #4509
This PR adds two new metrics:
1. `accumulo.scan.reservation.writeout.timer` which records the amount of time it takes for reservations to be added to the metadata table
2. `accumulo.scan.reservation.collision.count` which adds a `FunctionCounter` that gets incremented if a scan is held up waiting for files that are in flux
I also renamed `accumulo.scan.reservation.timer` to `accumulo.scan.reservation.total.timer`.
supersedes #4541
> Add metrics for scan server reservation write out time and collisions

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/base/src/main/java/org/apache/accumulo/server/AccumuloDataVersion.java
- server/base/src/test/java/org/apache/accumulo/server/ServerContextTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
- test/src/main/java/org/apache/accumulo/test/UnusedWALIT.java
Cleaned up a few TODOs in the elasticity branch.  Added issues to some, implemented an easy one, and removed one that was erroneously added.  The TODO in UnusedWALIT.java was erroneously added to an old comment from 2015.
> cleans up some todos

- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServerMetrics.java
A NPE was being raised in ScanServerMetrics.registerMetrics when the SSERV_CACHED_TABLET_METADATA_EXPIRATION value was zero, which disables the tablet metadata caching and leaves the variable tabletMetadataCache referencing null. A test was failing in ScanServerConcurrentTabletScanIT that led to this discovery.
> Fixed NPE in ScanServerMetrics

- test/src/main/java/org/apache/accumulo/test/metrics/MetricsIT.java
- METRICS_SCAN_RESERVATION_WRITEOUT_TIMER
- METRICS_SCAN_RESERVATION_CONFLICT_COUNTER
metrics were added in #4577
> Add new scan metrics to flaky list in MetricsIT

- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadata.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/TabletMetadataTest.java
- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
This change was made in elasticity as part of a larger change to speedup merge, see #4574.  Backported just the part that replaced a sortedmap w/ a list in TabletMetadata to speed up the code that tracks a tablets key/values.
> replaces sorted map w/ list for key vals in tablet metadata

- core/src/main/java/org/apache/accumulo/core/fate/FateKey.java
- core/src/main/java/org/apache/accumulo/core/fate/user/FateKeyFilter.java
- core/src/main/java/org/apache/accumulo/core/fate/user/UserFateStore.java
This new iterator plus the locality group added in #4589 should make finding fate transactions with a given key type much more efficient.
> adds iterator for filtering on fate key type

- core/src/main/java/org/apache/accumulo/core/fate/AbstractFateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
- core/src/main/java/org/apache/accumulo/core/fate/FateCleaner.java
- core/src/main/java/org/apache/accumulo/core/fate/MetaFateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/ReadOnlyFateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/user/FateStatusFilter.java
- core/src/main/java/org/apache/accumulo/core/fate/user/UserFateStore.java
- core/src/main/java/org/apache/accumulo/core/logging/FateLogger.java
- core/src/test/java/org/apache/accumulo/core/fate/TestStore.java
- server/base/src/main/java/org/apache/accumulo/server/init/InitialConfiguration.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/split/PreSplit.java
- test/src/main/java/org/apache/accumulo/test/fate/FateInterleavingIT.java
- test/src/main/java/org/apache/accumulo/test/fate/FateStoreIT.java
- test/src/main/java/org/apache/accumulo/test/fate/meta/MetaFateInterleavingIT.java
- test/src/main/java/org/apache/accumulo/test/fate/user/UserFateInterleavingIT.java
There are a few improvments to FATE in this PR.  The first is that Fate now continues to execute a transaction as long as its ready. Before it would do one step of a transaction and then persist the result and stop, meaning the next step would not run until the next full scan.
The second change was to make finding runnable transactions look for in progress transaction first in the persisted store followed by the non inprogress ones.  This change causes the search for runnable transactions to scan the store twice. To make this more efficient a locality group and filtering iterator were added.  This should make the scans looking for fate transactions with a certain status much more efficient.
These two improvements should make fate a bit more responsive for getting existing work done. …
> improves fate execution of in progress transactions

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/CompactionDriver.java
This logging can be useful to turn on when a compaction does not seem to be making progress.
> adds trace logging to CompactionDriver

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/ReserveTablets.java
The fate step that reserves tablets for merge was signaling it was ready when it was not in the case where its scan of the metadata table took 0ms.  This was causing some ITs to fail.  The bug was introduced in #4574
> fixes bug in merge tablet reservations

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- test/src/main/java/org/apache/accumulo/test/ScanServerConcurrentTabletScanIT.java
This adds a property to configure the scan server tablet metadata Caffeine cache to refresh cached tablet metadata in the background on cache hits after the refresh time has passed. The refresh time is expressed as a percentage of the expiration time. This allows the cached entries to refresh before expiration if they are frequently used so that scans will not be blocked waiting on a refresh on expiration. Entries still expire if no cache hits come after the refresh time and expiration time passes.
See: https://github.com/ben-manes/caffeine/wiki/Refresh
This closes #4544
> Enable background refresh for the scan server tablet metadata cache

- server/base/src/main/java/org/apache/accumulo/server/util/ServiceStatusCmd.java
- server/base/src/main/java/org/apache/accumulo/server/util/serviceStatus/ServiceStatusReport.java
- server/base/src/test/java/org/apache/accumulo/server/util/ServiceStatusCmdTest.java
- server/base/src/test/java/org/apache/accumulo/server/util/serviceStatus/ServiceStatusReportTest.java
The service host information stored in ZooKeeper changed between 2.1 and 3.1.x.  3.1.x uses ServiceLockData and ServiceDescriptors.  These changes adopt the admin serviceStatus command to use the new data formats.
Fixes #4603
> Admin service status server lock changes

- core/src/main/java/org/apache/accumulo/core/fate/AdminUtil.java
- test/src/main/java/org/apache/accumulo/test/FateSummaryIT.java
closes https://github.com/apache/accumulo/issues/4462
- Fixes bug with admin fate print and summary commands failing due to ZK NoNodeException when a transaction completes between getting the list of transactions and probing for info on that transaction.
- Added test testFatePrintAndSummaryCommandsWithInProgressTxns() to FateSummaryIT to test changes
- Small changes to testFateSummaryCommandWithSlowCompaction() in FateSummaryIT
- Stop the COMPACTOR to avoid seeing unnexpected transactions in the summary
- Wait for the flush to complete
- delete the table at the end of the test
> Fixes 'admin fate --print/--summary' no node exception bug

- server/base/src/main/java/org/apache/accumulo/server/util/ServiceStatusCmd.java
- server/base/src/test/java/org/apache/accumulo/server/util/ServiceStatusCmdTest.java
- The coordinator moved to the manager and is no longer a stand-alone service.
Fixes #4612
> Remove coordinator from service status command

- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/LoadFiles.java
Adds a singal event after a tablet successfully bulk imports into a tablet.  This event will tigger the tablet group watcher to check if the tablet needs a compaction.  This change will lower the latency for compacting newly arrived bulk import files which can benefit scans.
> signal event after bulk import to trigger compaction check

- test/src/main/java/org/apache/accumulo/test/FateSummaryIT.java
part of https://github.com/apache/accumulo/issues/4614
This is an attempt to fix the Jenkins build failure for this test. Locally, I have not been able to reproduce this test timeout (only takes about 1 minute locally and passes). So, I could not test that these changes fix the problem. If anyone knows how I can better test these changes, that would be great.
Since it was timing out at the deletion of the table, I thought this might be caused by creating, using, and deleting a table with the same name twice. I can't think of any other reason this might be timing out here...
> FateSummaryIT Jenkins failure fix attempt

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/split/UpdateTablets.java
When the split code examined files to determine if they should go to a child tablet it did not directly look at any ranges associated with the file becasue it assumed other code would clip.  Added validation that clipping was done since the file ranges are not directly examined by split.
Ran ComprehensiveIT.testMergeAndSplit() to test this change because it does split->merge-split->merge while will cause split of tablets w/ fenced files.
> adds validation of file clipping to split code

- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/TabletRefresher.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/CompactionDriver.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/split/AllocateDirsAndEnsureOnline.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/split/PreSplit.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/split/SplitInfo.java
- test/src/main/java/org/apache/accumulo/test/fate/ManagerRepoIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitIT.java
This commit wraps up #3412 and includes the following changes
* compactors now cancel running compactions when the table state is no longer online, this avoids doing work that will never be used
* coordinator will no longer start commiting compactions when the tablet is offline, this avoid race condition w/ offline+wait of table
* fixed bug found in tablet refresher where it was not properly handling concurrent tablet unloads (found by testing concurrent compaction and offline)
* compaction fate operation that drives table compaction will now fail when table is offline (this change may be needed in older versions)
* reordered when the split fate operation checks for table offline to avoid race condition with offline+wait of table
* added multiple ITs to test running split and compaction …
> fixes race condition w/ split,compaction relative to offline

- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
The compactor was not setting an error reference when it caught a cancelation exception.  This could cause the compactor to report success back to the coordinator.
> sets error ref when compactor catches cancellation exception

- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/ConcurrentKeyExtentCache.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/CompactRange.java
Added conditionals to catch any splits that are outside the specified range. To do so I made `ConcurrentKeyExtentCache` a public class and am using `KeyExtent` to find the tablets that contain the `startRow` and `endRow`. 
Fixes [Issue#4341](https://github.com/apache/accumulo/issues/4341)
> added conditionals to expand compaction range

- server/base/src/main/java/org/apache/accumulo/server/util/fateCommand/FateTxnDetails.java
- test/src/main/java/org/apache/accumulo/test/fate/FateOpsCommandsIT.java
This addresses https://github.com/apache/accumulo/pull/4350#pullrequestreview-1929324130
- Added test to verify name and step of transactions using summary and print commands
- Added check to filter by non-existent FateId in summary and print command tests
- Some other small misc improvemements
> FateOpsCommandsIT enhancements

- server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/CompactionJobHolder.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/compactor/src/test/java/org/apache/accumulo/compactor/CompactorTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableUtils.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalDoNothingCompactor.java
Added interrupt method on FileCompactor that is set to true in CompactableUtils when the majc env is no longer enabled. FileCompactor.interrupt sets an AtomicBoolean to true, and the reference to the AtomicBoolean is set on the RFiles. Only internal compactions will use this interrupt behavior as external compactions already interrupt the compaction thread when compaction cancellation is requested.
Fixes #4485
> Modified FileCompactor to set interruptFlag on RFile

- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/SplitRecovery12to13.java
- test/src/main/java/org/apache/accumulo/test/MetaConstraintRetryIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitRecoveryIT.java
While investigating #3858, noticed these utility metadata utility methods that were not widely used.  Moved the static method where they are actually used to clean up the code.
This refactoring was done using IDE. Planning to merge this PR if GH actions build passes because it was an automated change.
> moves static metadata util methods to only places using them

- server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- test/src/main/java/org/apache/accumulo/test/functional/ZombieTServer.java
- test/src/main/java/org/apache/accumulo/test/performance/NullTserver.java
This log message is encountered as the TServer Util attempts port binding.
This is a log message that is normally occuring when running more than a single tserver process per node. Removed the word "Error" since that creates additional background noise when searching logs.
> Removes Error and drops logging level on message

- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterControl.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloConfigImpl.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/MergeTablets.java
- test/src/main/java/org/apache/accumulo/test/fate/FlakyFate.java
- test/src/main/java/org/apache/accumulo/test/fate/FlakyFateManager.java
- test/src/main/java/org/apache/accumulo/test/functional/DeleteRowsFlakyFateIT.java
- test/src/main/java/org/apache/accumulo/test/functional/MergeFlakyFateIT.java
Adds a way to make Fate in the manager always runs steps multiple times to test idempotence. Created versions of merge and delete rows ITs that uses this test manager. Found and fixed a bug in the merge code when running these new test. Changed mini accumulo to allow specifying a different manager class to use prio to startup.  There was an existing method that would allow starting a manager with a different class, but using it would have meant letting the actuall manager start and then killing it and starting another which would have added time to test.  The change to mini accumulo was not made to its public API, only its implementation.
fixes #4642
> tests merge idempotence and fixes found bug

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/MoveExportedFiles.java
- test/src/main/java/org/apache/accumulo/test/ComprehensiveBaseIT.java
- test/src/main/java/org/apache/accumulo/test/ComprehensiveFlakyFateIT.java
- test/src/main/java/org/apache/accumulo/test/fate/FlakyFate.java
Updated ComprehensiveIT to use FlakyFate because it calls a lot of Fate operations. In the process found a bug with import table where it failed when run a second time.  Import table had code to handle running a second time but it compared filenames to full file paths.  Converted everything in the code to use full file paths to fix the bug.
Updated FlakyFate to interleave isReady() and call() in when rerunning them as this is what would happen with a fault.
> runs comprehensiveIT w/ FlakyFate and fixes found bug

- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterControl.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloConfigImpl.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- test/src/main/java/org/apache/accumulo/test/fate/FlakyFate.java
- test/src/main/java/org/apache/accumulo/test/fate/FlakyFateManager.java
- test/src/main/java/org/apache/accumulo/test/functional/DeleteRowsFlakyFateIT.java
- test/src/main/java/org/apache/accumulo/test/functional/MergeFlakyFateIT.java
This backports the FlakyFate and FlakyFateManager impl from elasticity that was added in #4643 so that fate operations can be easily tested to check if they are idempotent. 
DeleteRowsFlakyFateIT and MergeFlakyFateIT were also backported and pass verifying the operations are idempotent.
**Note:** when this makes it into main, we will want to merge forward an empty commit with git merge -s because these changes already exist in elasticity.
> Backport FlakyFate and idempotent tests for Merge and DeleteRows

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/availability/SetTabletAvailability.java
- test/src/main/java/org/apache/accumulo/test/functional/ManagerAssignmentIT.java
ManagerAssignmentIT had a test that would manually set an operation id on a tablet and then attempt to set the tablet availibility on the tablet using public API.  The changes in #4636 caused this public API call to block because an opid was present.  Modified the test to directly set tablet availability in the API.  Modifed the fate operation to log the opid that is blocking it.
> fixes ManagerAssignmentIT test failure

- test/src/main/java/org/apache/accumulo/test/metrics/MetricsIT.java
MetricsIT was failing because it did not see this metric. The test does not run a compactor so it has been added to the set of unexpected metrics.
> Add new compactor busy metric to unexpected list - fixes MetricsIT failure

- core/src/main/java/org/apache/accumulo/core/fate/AdminUtil.java
- test/src/main/java/org/apache/accumulo/test/FateSummaryIT.java
Changed `FateSummaryIT.testFatePrintAndSummaryCommandsWithInProgressTxns` number of transactions/number of compactions initiated from 250 down to 150. Jenkins still seems to timeout on this test sometimes with 250 txns. In the [previous PR for this](https://github.com/apache/accumulo/pull/4619), I was worried about making the test too flaky going lower than 250. I wasn't aware that Jenkins retries the tests 5 times, so this shouldn't be a problem. Hopefully now Jenkins won't time out. Going lower than 150 will probably be too flaky (fails fairly often making it pretty likely to fail 5 times in a row).
> Jenkins FateSummaryIT fix (again)

- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java
I was seeing this test case fail since the compaction was often not finished before the verify method ran. It now passes.
> ExternalCompactionProgressIT - verify only after compaction completes

- core/src/main/java/org/apache/accumulo/core/client/ConditionalWriter.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ConditionalWriterImpl.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
- test/pom.xml
- test/src/main/java/org/apache/accumulo/test/WriteAfterCloseIT.java
Updated WriteAfterCloseIT to use a conditional writer in addition to a batch writer.  Made a few improvements to the test.
While reviewing how the conditional writer handles timed out writes noticed the tablet server code had an incorrect try/finally block. There was code between session reservation and the beginning of the try block.  If this inbetween code threw an exception, then it would never unreserve the session.  Fixed this and added a few comments to the code.
fixes #3742
> updates WriteAfterCloseIT to also use ConditionalWriter

- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java
This test was validating the compactor busy count metric.  The test has 9 compactor processes running.  When it saw a busy count from any of the 9 it would set an atomic long.  This is made it likely that the 8 of 9 not busy compactors would set zero making the test flaky.  Replaced the atomic long w/ a concurrent map where each compactor process has an entry in the map for its busy count.
> fixes ExternalCompactionProgressIT

- server/base/src/main/java/org/apache/accumulo/server/AbstractServer.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- test/src/main/java/org/apache/accumulo/test/ComprehensiveFlakyAmpleIT.java
- test/src/main/java/org/apache/accumulo/test/ample/FlakyAmpleManager.java
- test/src/main/java/org/apache/accumulo/test/ample/FlakyAmpleServerContext.java
- test/src/main/java/org/apache/accumulo/test/ample/FlakyAmpleTserver.java
- test/src/main/java/org/apache/accumulo/test/ample/FlakyInterceptor.java
- test/src/main/java/org/apache/accumulo/test/ample/metadata/ConditionalWriterDelegator.java
- test/src/main/java/org/apache/accumulo/test/ample/metadata/ConditionalWriterInterceptor.java
These changes make it possible to instrument the manager and tablet server in integration tests to use TestAmple configured to randomly return UNKNOWN status for conditional mutations.
Servers were instrumented by modifying the AbstractServer constructor to accept a server context factory.  This allowed test version of Manager and Tsever to pass a factory that creates a server context that returns TestAmple.
A version of Comprehensive IT was updated to use the new instrumented servers.  This should provide some base coverage of UNKNOWN handling.  Still need to determine what Ample submit() calls are not being excercised and modify more ITs to use these instrumented servers.
> Tests UNKNOWN return status of conditional mutations

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/MoveExportedFiles.java
This backports the fix from #4646 to make MoveExportedFiles fate step idempotent.
This closes #4655
Note: ComprehensiveIT does not exist in 2.1 so those changes that were part of #4646 were not backported.  I think there are other ITs that exist for table import though, so I wasn't sure if we wanted to test this in some other way or bring back that test and the flaky comprehensive test too. The test does exist in main so we could maybe add it there.
> Backport fix to make Import tablet idempotent

- core/src/main/java/org/apache/accumulo/core/util/compaction/RunningCompactionInfo.java
- core/src/main/thrift-gen-java/org/apache/accumulo/core/compaction/thrift/TCompactionStatusUpdate.java
- core/src/main/thrift/compaction-coordinator.thrift
- server/base/src/main/java/org/apache/accumulo/server/compaction/CompactionInfo.java
- server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/compactor/src/test/java/org/apache/accumulo/compactor/CompactorTest.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalDoNothingCompactor.java
Fixes #4570 
This PR changes the way the duration of a compaction is calculated. The main change is the addition of a field, that was added to `FileCompactor`, which denotes the age of the current running compaction. This field is ultimately propagated to the monitor.
Before these changes, the age of a compaction was calculated by the coordinator which took the difference between the timestamps of the first and last update it had for that compaction. The bug where the duration was never older than the age of the coordinator came from this map of updates it used to calculate the compactor age being reinitialized when the coordinator started up.
Details to help with review:
* `RunningCompactionInfo` is where the diff of timestamps used to be calculated and now it just uses the duration …
> Ensure compaction duration is not reset on coordinator restart

- core/src/main/java/org/apache/accumulo/core/clientImpl/RootClientTabletCache.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/AmpleImpl.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/RootTabletMetadata.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/RootClientTabletCacheTest.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/ZooTabletStateStore.java
After the changes in #4669 only a single location in the code was reading tablet metadata w/ eventual consistency using Ample.  This single location was the root tablet location cache.  Since this was the only use of the code and its a highly nuanced use case, moved the code out of Ample to the only place that was using it. Removing the levels of indirection makes it easier to understand the root tablet location cache. Also added some comments about what the the root tablet location cache is doing and noticed and uneeded cache clear it was doing and removed it.
> Moves reading root tablet metadata w/ zoocache out of Ample

- shell/src/main/java/org/apache/accumulo/shell/commands/ActiveCompactionHelper.java
- shell/src/main/java/org/apache/accumulo/shell/commands/ListCompactionsCommand.java
* remove the need to create lists and just use a single stream per method
* create `static final Comparator` for reuse in both methods. Improve age comparison
* rename `stream()` to `activeCompactions()` for consistency
> Improve ActiveCompactionHelper retrieval methods

- core/src/main/java/org/apache/accumulo/core/spi/scan/ConfigurableScanServerSelector.java
- core/src/test/java/org/apache/accumulo/core/spi/scan/ConfigurableScanServerSelectorTest.java
- test/src/main/java/org/apache/accumulo/test/ScanServerIT_NoServers.java
- test/src/main/java/org/apache/accumulo/test/functional/OnDemandTabletUnloadingIT.java
Closes [issue#4532](https://github.com/apache/accumulo/issues/4532) 
Changed `enableTabletServerFallback` to `timeToWaitForScanServers` and made it a timeout value. Please take a look at the class description and see if the explanation `timeToWaitForScanServers`  is sufficient enough. This update will need to be added into 2.1 as well.
> Timeout value addd to wait for scans servers

- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchReaderIterator.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftScanner.java
- core/src/main/java/org/apache/accumulo/core/spi/scan/ConfigurableScanServerSelector.java
- core/src/main/java/org/apache/accumulo/core/spi/scan/ScanServerSelector.java
- core/src/test/java/org/apache/accumulo/core/spi/scan/ConfigurableScanServerSelectorTest.java
- test/src/main/java/org/apache/accumulo/test/ScanServerIT_NoServers.java
This PR is inline with [pull #4638 ](https://github.com/apache/accumulo/pull/4638), where it is adding the client option to wait for scan servers
> Back ported Timeout value to 2.1

- core/src/main/java/org/apache/accumulo/core/metadata/AccumuloTable.java
- core/src/main/java/org/apache/accumulo/core/metadata/ScanServerRefStore.java
- core/src/main/java/org/apache/accumulo/core/metadata/ScanServerRefTabletFile.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/MetadataSchema.java
- minicluster/src/test/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImplTest.java
- server/base/src/main/java/org/apache/accumulo/server/init/FileSystemInitializer.java
- server/base/src/main/java/org/apache/accumulo/server/init/InitialConfiguration.java
- server/base/src/main/java/org/apache/accumulo/server/init/ZooKeeperInitializer.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ScanServerRefStoreImpl.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
- server/base/src/main/java/org/apache/accumulo/server/util/ScanServerMetadataEntries.java
- server/gc/src/main/java/org/apache/accumulo/gc/GCRun.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- test/src/main/java/org/apache/accumulo/test/MetaSplitIT.java
- test/src/main/java/org/apache/accumulo/test/NamespacesIT.java
- test/src/main/java/org/apache/accumulo/test/ScanServerMetadataEntriesCleanIT.java
- test/src/main/java/org/apache/accumulo/test/ScanServerMetadataEntriesIT.java
- test/src/main/java/org/apache/accumulo/test/ScanServerShutdownIT.java
- test/src/main/java/org/apache/accumulo/test/functional/WALSunnyDayIT.java
This change moves scan server refs to a separate table from metadata in order to improve performance. The prefix was dropped as nothing else is stored in the table anymore.
This is a backport of the change in elasticity that was done in #4650 into 3.1
When this is merged into main, we need to do a "git merge -s" into elasticity with this commit only as the changes already exist in elasticity.
> Backport Scan Server File refs table from elasticity to 3.1

- core/src/main/java/org/apache/accumulo/core/fate/MetaFateStore.java
- test/src/main/java/org/apache/accumulo/test/fate/FateStoreIT.java
The two different fate stores had slightly different behavior when reading an absent fateId.  Changed the behavior to make it consistent and added a test to ensure they stay consistent.
> makes behavior of reading absent fate consistent

- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
Fixes #4633 
This PR changes the way split fate operations are carried out in `addSplits()`. Before these changes, `addSplits()` would call `doFateOperation()` for each split which would start then wait for it to finish. The changes in this PR start all of the fate ops and then once all have started, wait for them all to finish.
So that error handling was not duplicated, I created a new method that executes a lambda within the original try-catch block from `doFateOperation()`
I did some crude benchmarking using `SplitMillionIT` and saw a decrease in time taken per 10,000 splits in the test. Per 10,000 splits, over 5 runs I saw an average time of 827.8ms on elasticity and 822.4ms on this branch. This difference seems negligible but I at least did not notice a performance decrease.
> addSplits() improvement - start all fate ops before waiting on any

- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletOperationId.java
- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
- server/base/src/main/java/org/apache/accumulo/server/util/FindOfflineTablets.java
- server/base/src/test/java/org/apache/accumulo/server/util/AdminTest.java
Added the ability to check for tablets that reference fate operations that are no longer active.  This was added to the `accumulo admin checkTablets` command.
A unit test was added that validates the algorithm and the extraction of fate ids from tablet metadata. Manual testing was done to validate end to end functionality.
For manual test the following command were run in the shell
```
grant Table.WRITE -t accumulo.metadata -u root
insert 1< srv opid SPLITTING:FATE:USER:dfdb85a6-65a0-47d2-a9e2-4c671b499829
```
and then the following was run
```
$ accumulo admin checkTablets
*** Looking for offline tablets ***
Scanning zookeeper
Scanning accumulo.root
Scanning accumulo.metadata
1<< is UNASSIGNED  #walogs:0
*** Looking for missing files ***
Scanning : accumulo.root (-inf,~ : [] …
```
> adds admin check for dangling fate references

- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/UpgradeCoordinator.java
- test/src/main/java/org/apache/accumulo/test/functional/FateConcurrencyIT.java
- test/src/main/java/org/apache/accumulo/test/functional/FunctionalTestUtils.java
closes #4647
- `UpgradeCoordinator.abortIfFateTransactions()` now uses both stores
- `FunctionalTestUtils.getFateStatus()` now uses both stores. As this method is currently only used in `assertNoDanglingFateLocks()`, technically only the `MetaFateStore` is needed, but based on the method name and if it is used for other purposes in the future, both stores should be used.
I also attempted to change the FATE metrics to include both types of transactions (currently only includes META) (issue: https://github.com/apache/accumulo/issues/4534), but I ran into an issue I couldn't resolve. Including the `UserFateStore` in the map passed to `AdminUtil.getTransactionStatus()` resulted in `getTransactionStatus()` never completing (see `FateMetricValues.getFromZooKeeper()`). It would get hung up …
> Update places where one fate store is used when both should be

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/Utils.java
When a create table fate step ran twice it would detect its table name as in use.  However the table name was reserved by the first run of the fate step.  Made the code idempotent.  Some ITs were failing that ran fate steps multiple times.
> fixes create table when fate step runs twice

- test/src/main/java/org/apache/accumulo/test/ComprehensiveBaseIT.java
ComprehensiveIT was covering all fate table op steps except for the one related to automatic splits. This commit adds a test to ComprehensiveIT that excercise autosplits.  This covers that fate step that is only run for automatic splits. Automatic splits are an important feature of Accumulo, so in general its good to cover them in ComprehensiveIT.
> adds auto split test to ComprehensiveIT

- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
This is a follow on of #4697.
In this PR the begin and execute steps of the add splits fate operations have been wrapped in `Future`s and executed in a thread pool. This further speeds up the addSplits operation.
I benchmarked these changes on elasticty before #4697 was merged, after it was merged, and after the changes in this PR. Below are the results from [this IT](https://github.com/apache/accumulo/pull/4697#issuecomment-2187560469) averaged over two runs:
| Branch                                    | Time to Seed 587 (ms) | Time to Add 1000 Splits (ms) |
|-------------------------------------------|-----------------------|------------------------------|
| Current Changes                           | 2690                  | 6348                         |
| Elasticity …
> Parallelize split seeding in TableOperationImpl.addSplits()

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/Utils.java
- test/src/main/java/org/apache/accumulo/test/CreateTableIT.java
Method was changed in #4685, but that changed missed the namespace handling that was being performed in TableMap. This was causing NamespacesIT.cloneTable to fail. Also lowered the number of tables being created in CreateTableIT because it's timing out in the IT builds but is passing locally.
> Added namespace support to Utils.checkTableNameDoesNotExist

- server/base/src/main/java/org/apache/accumulo/server/AccumuloDataVersion.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/UpgradeCoordinator.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java
Fixed a bug where upgrade code was attemptnig to read the managers service lock before it was set.
Fixed a bug with deteting fate operations.  The code to detect fate operations would hang trying to read the fate table which did not exists yet.
Scans of the metadata table running as the !SYSTEM user would fail if no auths were specified.  The !SYSTEM user has not auths set in zookeeper and an exception would happen when trying to find them.
A new zookeeper node related to compaction changes needed to be created.
Simplified code for setting tablet availability by using DataLevel.
> fixes multiple upgrade bugs found when testing

- server/manager/src/main/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueue.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/queue/CompactionJobQueues.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueueTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/queue/CompactionJobQueuesTest.java
Adds completeable futures to the queue of compaction jobs.  This allows for async notification when something is added to the queue.
The compaction queues code would drop queues that became empty.  The concept of queues being empty became more complex with this change. A queue would be considered empty when there were no futures and the queue was empty.  This increased complexity of empty would have made the code for dropping empty queues more complex.  Instead of increasing the complexity of this code chose to drop removing empty queues.  This means that if a compaction group is used and then no longer used that it will have a small empty datastructure sitting around in map for the process lifetime.  That is unlikely to cause memory issues.  Therefore decided the increased complexity was …
> Adds completable futures to compaction queue

- server/manager/src/main/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueue.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueueTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/queue/CompactionJobQueuesTest.java
For the case where nothing is ever added to a compaction job prioq and futures are continually obtained and canceled these canceled futures would keep building up in memory.  This commit fixes that by periodically cleaning out canceled futures.
> periodically clean up canceled futures in compaction job prioq

- core/src/main/java/org/apache/accumulo/core/metadata/schema/MetadataSchema.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java
Deletes the bulk file columns from the metadata table on upgrade to 4.x, if they exist.
closes #4637, related to #4587
> Metadata table bulk file columns deleted on upgrade

- core/src/test/java/org/apache/accumulo/core/metadata/schema/DataLevelOrderTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
> Always balance root and metadata tables

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ConditionalWriterImpl.java
- test/src/main/java/org/apache/accumulo/test/ConditionalWriterIT.java
Closes #4708
- Fixed `ClientContext.createConditionalWriter(String)` to include client props
- Added `testCreateConditionalWriterUsesClientProps` to `ConditionalWriterIT` (verified to fail before changes and pass after)
> Conditional writer creation now always includes the client properties

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
Closes #4460
- Confirmed that these changes fix the issue: no longer shows hints on SYSTEM compactions which follow a USER compaction that had hints
- This may not be the best way to fix this issue but this keeps the amount of code changes small. Figured filtering them out at the time they are logged may not be the best approach in case these incorrect hints would be seen/used deeper in the code. But also didn't filter them out at the deepest level where they are set. This would have required larger refactoring.
- This issue made me think that maybe these execution hints would carry over to new USER compactions. For example, if a user compaction is initiated with execution hints "hints1", and later another user compaction was initiated with no execution hints, we may still see "hints1". I …
> Fixed bug with USER compaction hints showing on SYSTEM compactions

- assemble/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/accumulo/core/client/mapred/AbstractInputFormat.java
- core/src/main/java/org/apache/accumulo/core/client/mapreduce/AbstractInputFormat.java
- core/src/main/java/org/apache/accumulo/core/metadata/ScanServerRefTabletFile.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapred/AccumuloRecordReader.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/AccumuloRecordReader.java
- minicluster/pom.xml
- pom.xml
- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
- server/base/src/main/java/org/apache/accumulo/server/metrics/MetricsInfoImpl.java
- server/base/src/main/java/org/apache/accumulo/server/util/ServiceStatusCmd.java
- server/base/src/test/java/org/apache/accumulo/server/metrics/MetricsInfoImplTest.java
- server/compaction-coordinator/pom.xml
- server/compactor/pom.xml
- server/manager/src/main/java/org/apache/accumulo/manager/metrics/ManagerMetrics.java
- server/monitor/pom.xml
- start/pom.xml
- test/src/main/java/org/apache/accumulo/test/ClientSideIteratorIT.java
- test/src/main/java/org/apache/accumulo/test/PrintInfoIT.java
- test/src/main/java/org/apache/accumulo/test/ScanServerMetadataEntriesCleanIT.java
* Bump commons-logging to 1.3, so it natively supports sending logs to slf4j or log4j without the log4j-jcl bridge See https://github.com/apache/commons-logging/pull/177
* Fix issue described in https://github.com/apache/accumulo/pull/4558#issuecomment-2231991529 regarding log4j-api being required for log4j-1.2-api in core/pom.xml
* Fix some false-positive Closeable resource warnings from wrapping a Scanner with an IsolatedScanner
* Suppress some deprecation warnings for scan server metadata schema
* Remove log4j-1.2-api from minicluster and compactor modules, where they weren't used
* Fix some incorrect `@SuppressWarnings` comments
* Fix generics with the ServiceStatusCmd's Result class, which had a generic `A extends Integer` parameter, but `Integer` is final and cannot be extended
* …
> Clean up the 2.1 build a bit

- core/src/main/java/org/apache/accumulo/core/security/Authorizations.java
After the changes in #4743 can now use a new API from accumulo-access that is only present in the snapshot version.  This new API efficiently returns an empty accumulo-access Authorization object.   Can call this new API and drop a bit of custom code that did the same thing.
> uses new accumulo-access API for empty authorization

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/ec.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/ec.ftl
compactor.queue was renamed to compactor.group in #3591 and this updates the Monitor to use the new name so Compactors can be displayed correctly in the table on the external compations page. Before this change there the table was empty and there were errors in the javascript console.
> Fix Compactors table on EC Monitor page

- server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellIT.java
Modifed ManagerServiceClientHandler alterProperty method so it no longer removes/deletes a property when set to null or empty string.
Added configPropertyTest integration tests to ShellIT.
Fixes #4456
> Setting empty property value no longer deletes property

- server/base/src/main/java/org/apache/accumulo/server/AbstractServer.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/compactor/src/test/java/org/apache/accumulo/compactor/CompactorTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- test/src/main/java/org/apache/accumulo/test/functional/IdleProcessMetricsIT.java
This PR simplifies the check for the Compactor that is used to determine when to change the idle process metric for the Compactor. The new code just returns true when no compaction is running and false when one is. It defers the time checking portion to the upstream logic in `AbstractServer`.
The old method was to check how much time has passed since the last compaction was completed. There are at least two issues with this:
1. There is logic that makes sure the amount of time since the last compaction happened is at least `idleReportingPeriodNanos`. This check also happens upstream when the `Supplier<boolean>` is read in `AbstractServer` so we are getting rid of that duplicate check in the new code.
2. There is a check that the `System.nanoTime()` value of the last completed compaction …
> Simplify idle check used for idle process metric in Compactor

- core/src/main/java/org/apache/accumulo/core/conf/AccumuloConfiguration.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/base/src/main/java/org/apache/accumulo/server/conf/RuntimeFixedProperties.java
- server/base/src/main/java/org/apache/accumulo/server/conf/SystemConfiguration.java
- server/base/src/test/java/org/apache/accumulo/server/conf/AccumuloConfigurationIsPropertySetTest.java
- server/base/src/test/java/org/apache/accumulo/server/conf/SystemConfigurationTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- test/src/main/java/org/apache/accumulo/test/ScanServerMetadataEntriesIT.java
* Add more comments (including javadocs) to explain fixed properties
* Add the ability to track whether a fixed property was set on startup by recording the runtime state of whether a user had set the property or not
* Update AccumuloConfigurationIsPropertySetTest to ensure that the runtime properties behavior is working correctly
* Also, rename a scan server property enum to match the others
This fixes #3529
> Make isPropertySet work for fixed properties

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
The tablet close code was acuiring the log lock after the tablet lock, which is the opposite order of other code.  This could cause deadlock.  Reversed the acuisition order.
Also added validation of the lock acquisition order.
Fixes #3759
> acquires two locks in correct order in tablet close

- core/src/main/java/org/apache/accumulo/core/metadata/ScanServerRefTabletFile.java
- server/base/src/main/java/org/apache/accumulo/server/init/FileSystemInitializer.java
- server/base/src/main/java/org/apache/accumulo/server/init/InitialConfiguration.java
- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
- server/base/src/main/java/org/apache/accumulo/server/init/ZooKeeperInitializer.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ScanServerRefStoreImpl.java
- server/base/src/main/java/org/apache/accumulo/server/util/ScanServerMetadataEntries.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader11to12.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- test/src/main/java/org/apache/accumulo/test/upgrade/ScanServerUpgrade11to12TestIT.java
Updates the ScanServerRef format and moves the UUID entry forward so sorting is done on UUID instead of filename.
Also adds the removal of the scan serverref range from the metadata table
This PR is ensuring that the changes from #4682 are merged into main without introducing a large number of merge conflicts.
closes #4652 and #4493
> Update ScanServerRefFile format to sort on UUID

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java
- server/base/src/test/java/org/apache/accumulo/server/rpc/TServerUtilsTest.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java
* Deprecate max message properties in favor of a replacement
* Simply remove the experimental ones (but they could be restored and
deprecated like the non-experimental ones, if that's desired)
* Ensure new property defaults to `Integer.MAX_VALUE`
* Handle detecting whether a user set the new property and fall back on
the old properties if a user customized them already
* Set the default value for the maxMessageSize to `Integer.MAX_VALUE` in
`TServerUtils`. However, that case should only apply when the property
passed to the method is `null`, which it never should be. A future
improvement could validate that the property is non-null instead.
* Ensure all the max message properties that remain are added to the
fixed properties, since they all require a restart to take effect
* Slightly …
> Increase Thrift max message size defaults

- server/base/src/main/java/org/apache/accumulo/server/init/FileSystemInitializer.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java
Upgrader now calls the same code for fate table creation as the init code
closes #4692
> Handle Fate table creation on upgrade

- test/src/main/java/org/apache/accumulo/test/functional/IdleProcessMetricsIT.java
Fixes the compliation error with IdleProcessMetricsIT for not using the return value of the stream.
> Fix ReturnValueIgnored on IdleProcessMetricsIT

- test/src/main/java/org/apache/accumulo/test/functional/WALFlakyAmpleIT.java
- test/src/main/java/org/apache/accumulo/test/functional/WALSunnyDayBaseIT.java
- test/src/main/java/org/apache/accumulo/test/functional/WALSunnyDayIT.java
Modified a log recovery test to run using FlakyAmple. This will provide coverage for the case of flaky conditional mutations that are written to tablets as part of log recovery.
Most of the code in WalSunnyDayIT was moved to WalSunnyDatBaseIT w/o modification.  So even though this commit has lots of diffs, there are very little actual changes.
This change is for #4710
> tests log recovery using FlakyAmple

- test/src/main/java/org/apache/accumulo/test/functional/OnDemandTabletUnloadingFlakyAmpleIT.java
When a tablet server unloads ondemand tablets
after a period inactivity it writes a conditional
mutation.  This new test will use FlakyAmple for
that write.
> tests ondemand tablet unload using FlakyAmple

- server/manager/src/main/java/org/apache/accumulo/manager/metrics/ManagerMetrics.java
- server/manager/src/main/java/org/apache/accumulo/manager/metrics/fate/FateMetricValues.java
- server/manager/src/main/java/org/apache/accumulo/manager/metrics/fate/FateMetrics.java
- server/manager/src/main/java/org/apache/accumulo/manager/metrics/fate/meta/MetaFateMetricValues.java
- server/manager/src/main/java/org/apache/accumulo/manager/metrics/fate/meta/MetaFateMetrics.java
- server/manager/src/main/java/org/apache/accumulo/manager/metrics/fate/user/UserFateMetricValues.java
- server/manager/src/main/java/org/apache/accumulo/manager/metrics/fate/user/UserFateMetrics.java
- server/manager/src/test/java/org/apache/accumulo/manager/metrics/fate/meta/MetaFateMetricValuesTest.java
- test/src/main/java/org/apache/accumulo/test/metrics/MetricsIT.java
This commit updates the fate metrics that are published to include the user fate transactions and not just Meta (zookeeper). The metric names are the same and a tag is now added to the metrics to indicate the fate instance type of either user or meta.
This closes #4534
I ended up refactoring the metrics classes to share common code in an abstract class between both types. There's a couple extra metrics for ZK only so I wanted to separate that out. I didn't add any new metrics for the User metrics that might be different than from Meta but we could always add some in the future. I noticed the MetricsIT already scans all the metrics to make sure they are published and I added one new test there to check that the instance type tag was being set properly. Actually testing the values of the …
> Add metrics for User fate transactions

- test/src/main/java/org/apache/accumulo/test/functional/CompactionBaseIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactionFlakyAmpleIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
Through analyzing code coverage data it was discovered that the conditional mutations related to user compaction requested were not being exercised in tests.  This commit refactors an existing test so that it can run with and without FlakyAmple which will exercise that conditional mutation.
> tests user compaction requested using FlakyAmple

- assemble/bin/accumulo-cluster
- assemble/bin/accumulo-service
- core/src/main/java/org/apache/accumulo/core/conf/cluster/ClusterConfigParser.java
- core/src/test/java/org/apache/accumulo/core/conf/cluster/ClusterConfigParserTest.java
- core/src/test/resources/org/apache/accumulo/core/conf/cluster/cluster-with-optional-services.yaml
Adds the ability to start and stop compactors and scan servers by compaction queue or scan server group.
This is important when attempting to run scan servers or compactors and not want to stop/start other accumulo services (gc, monitor, manager, compaction-coordinator).
> Improves accumulo-cluster for start and stop commands

- assemble/bin/accumulo-service
When ACCUMULO_SERVICE_INSTANCE is an empty string the service_name is set to the next OPT "-a". 
This causes an issue with the run files being named "accumulo--a.pid"
This change checks to make sure it's not "-a" and sets the service name correctly.
> Fix issue when SERVICE_INSTANCE is empty string

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloConfigImpl.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueue.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/queue/CompactionJobQueues.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/CompactionCoordinatorTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueueTest.java
- test/src/main/java/org/apache/accumulo/test/compaction/CompactionPriorityQueueMetricsIT.java
Modified the logic in CompactionCoordinator to clear the priority queue for a compactor group when there are no compactors remaining or to set the max size based on the number of remaining compactors multiplied by some factor set by the user.
Closes #3635
> Modifications to make compaction queue size dynamic

- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
- test/src/main/java/org/apache/accumulo/test/VolumeFlakyAmpleIT.java
- test/src/main/java/org/apache/accumulo/test/VolumeIT.java
- test/src/main/java/org/apache/accumulo/test/VolumeITBase.java
- test/src/main/java/org/apache/accumulo/test/ample/FlakyAmpleServerContext.java
The goal of these changes is to excercise the conditional mutation code used to replace volumes in tablets.
Refactored some code in VolumeIT into VolumeBaseIT so that VolumeBaseIT could be extended by VolumeFlakyAmpleIT that injects manager and tservers that use FlakyAmple. Ran into problems during this change. First problem was that manager and tserver processes were dying because of OOME. Using heap dumps found that TestAmple objects were continually being created and each TestAmple object created a hadoop configuration object. Eventually memory would fill up with these configuration objects. Do not fully understand why the hadoop config object never went away because it seemed like the TestAmple objects should have been transient. This problem may be worth further investigation.  In …
> test volume replacement with flaky ample

- core/src/main/java/org/apache/accumulo/core/data/Key.java
This PR is meant to add overloaded methods to `Key` class which populate existing `ArrayByteSequence` objects with respective fields row, column family, and column qualifier. The methods are modeled after `getColumnVisibilityData` which was added in #4735. 
The following files have been modified:
- `core/src/main/java/org/apache/accumulo/core/data/Key.java`: Added overloaded `getRowData`, `getColumnFamilyData`, and `getColumnQualifierData` methods.
Fixes #4749 "Add methods to Key that populate existing ArrayByteSequence"
> Add getData methods to Key that populate ArrayByteSequence

- core/src/test/java/org/apache/accumulo/core/util/TimerTest.java
Modified the checks of elapsed duration of Thread.sleep calls such that they are now checking that at the elapsed duration is at least the number of millis specified in the method parameter instead of performing an exact check, which could sometimes fail.
> Fixed TimerTest elapsed duration checks

- core/src/main/java/org/apache/accumulo/core/util/Timer.java
- core/src/test/java/org/apache/accumulo/core/util/TimerTest.java
This PR adds two new `startNewWithOffset()` methods to the Timer class that add the supplied value to the internal start time of the object. This change was suggested [here](https://github.com/apache/accumulo/pull/4785#discussion_r1706098227).
These new methods allow for us to use the Timer object to pick a point in time in the future and check the object to see if that point has elapsed yet.
> Add static creation method that applies offset to Timer object

- server/base/src/main/java/org/apache/accumulo/server/metadata/AsyncConditionalTabletsMutatorImpl.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ConditionalTabletsMutatorImpl.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
- test/src/main/java/org/apache/accumulo/test/ample/metadata/TestAmple.java
Ample has two ways to write conditional mutations.  TestAmple was only intercepting conditional mutations for one of these methods. This commit updates TestAmple to incercept both.
Also made TestAmple set more aggressive retry times for failed conditional muations.  This speeds up all of the FlakyAmple ITs. This change is important because more conditional mutations are failing with these changes and the those tests were running slower.
> always uses conditional writer interceptor in test ample

- test/src/main/java/org/apache/accumulo/test/LargeSplitRowIT.java
- test/src/main/java/org/apache/accumulo/test/fate/ManagerRepoIT.java
The new test in this commit covers the following code
https://github.com/apache/accumulo/blob/d1456fcaa440f94b03e2a7e7f557fb77f8ef2426/server/manager/src/main/java/org/apache/accumulo/manager/tableOps/split/FindSplits.java#L142-L148
> adds test to cover deleting unsplittable col in split code

- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction2BaseIT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction2_IT.java
- test/src/main/java/org/apache/accumulo/test/compaction/FlakyExternalCompaction2IT.java
This refactors `ExternalCompaction_2_IT` so that the same tests can be run using a Flaky Ample implementation which will randomly return an UNKNOWN status when submitting conditional mutations. The tests being run are related to cancelling compaction jobs so this test makes sure the rejection handlers related to job cancellation in CompactionCoordinator work correctly, such as the rejection handler used inside of `CompactionCoordinator.compactionFailedForLevel`
This implements one of the methods detected as missing code coverage that is listed in #4710
I first looked at using TestAmple directly but there would have a been a ton of changes to isolate and test as there would have been a lot of refactoring to be able to ceate a CompactionCoordinator in an IT and inject a test Ample instance. …
> Add Flaky external compaction tests for failed compactions

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/CompactionDriver.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionTestUtils.java
- test/src/main/java/org/apache/accumulo/test/fate/ManagerRepoIT.java
This commit adds tests using TestAmple to verify that the cleanupTabletMetadata method, which is called from undo, properly cleans up any compaction metadata for a given fate Id across the tablets that match the range provided to the CompactionDriver
This closes #4795
> Add tests for CompactionDriver cleanupTabletMetadata

- core/src/main/java/org/apache/accumulo/core/metrics/MetricsProducer.java
Switches from `<th>` to `<td>` for metric entry documentation
> Fix javadoc format error with metrics

- server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletStateStore.java
- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java
- server/gc/src/test/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogsTest.java
Fixes #4753
The changes in this PR were closely modeled after the changes in #4207
This PR:
These new methods are `createWalStateManager()` and `createStore()`. Moving this logic into separate methods allows us to override these methods for testing. It also makes it easier to construct the collection of `TabletLocationState` that is used in the `collect()` method.
This new method returns a `Stream<TabletLocationState>` that is created off of the `ClosableIterator<TabletLocationState> iterator()`. The goal of this PR is to make sure that these `ClosableIterator<TabletLocationState>` objects are closed so the stream adds an `onClose()` for this.
This stream method lets us more easily concatonate and then close multple streams of `TabletLocationState` that are returned in …
> Ensure resources are closed in GarbageCollectWriteAheadLogs

- server/base/src/main/java/org/apache/accumulo/server/conf/CheckCompactionConfig.java
- server/base/src/test/java/org/apache/accumulo/server/conf/CheckCompactionConfigTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
> Added runtime check for shared compaction queues

- test/src/main/java/org/apache/accumulo/test/ScanServerShutdownIT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction2BaseIT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_2_IT.java
- test/src/main/java/org/apache/accumulo/test/compaction/FlakyExternalCompaction2IT.java
- test/src/main/java/org/apache/accumulo/test/functional/MemoryStarvedMajCIT.java
Update a few ITs that were stopping a normal server instance and starting up a test impl by taking advantage of changes in #4643 to set the server instance type before start up. This simplifies the tests and also prevents weird behavior by having servers start up and be shut down quickly.
I took a look around the tests and I didn't see too many tests that could be updated to use the new method as some required keeping the original servers around but these were the ones I found.
This closes #4644
**Note:** Another nice side effect of this is that the changes here actually fix the hanging `ExternalCompacttion_2_IT` test I was having issues with and mentioned in the gRPC prototype in this [comment](https://github.com/apache/accumulo/pull/4715#issuecomment-2241699447). 
The issue for the …
> Configure test server classes before starting MAC

- core/src/main/java/org/apache/accumulo/core/metrics/MetricsProducer.java
- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
- server/manager/src/main/java/org/apache/accumulo/manager/metrics/ManagerMetrics.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/UpgradeCoordinator.java
- test/src/main/java/org/apache/accumulo/test/compaction/BadCompactionServiceConfigIT.java
- test/src/main/java/org/apache/accumulo/test/compaction/CompactionExecutorIT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction2BaseIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
Changes introduced in #4800 to validate compaction configurations caused several ITs to start failing. In these cases the ITs were using invalid configurations. The changes here fix the ITs by either isolating the invalid configurations to only the associated tests (vs having the invalid configuration persist for all the tests in the class), or I made modifications to the test so that they would continue to work.
> Fix failing ITs due to recent features

- core/src/main/java/org/apache/accumulo/core/util/Timer.java
- core/src/test/java/org/apache/accumulo/core/util/TimerTest.java
#4796 added CountDownTimer which replaces the functionality of these methods in a way that makes more sense. These methods are not used in 2.1 and their usages have already been replaced in main.
> Remove Timer.startNewWithOffset() methods

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientTabletCacheImpl.java
- core/src/main/java/org/apache/accumulo/core/util/Timer.java
- core/src/test/java/org/apache/accumulo/core/util/TimerTest.java
This [comment][1] identified a flaky unit test. The test was likely flakey because it compared elapsed times on two timers.  Each call to elapsed time would call System.nanoTime. Depending on how much nano time drifted between the two calls different results could be obtained making the code non-deteministic. Added a method to check if one timer started after another and used it for this check making the code deterministic.  Its also much easier to understand the intent of the code with this change.
[1]:https://github.com/apache/accumulo/pull/4821#issuecomment-2307244079
> adds startedAfter method to Timer

- server/tserver/src/main/java/org/apache/accumulo/tserver/session/Session.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java
Using an IDE automatically encapsulated Session.state.  This change is needed in support of changes being made for #4756.  In #4756 need the ability to react to the state of a session changing.  Did this refactoring in its own PR to exclude automated changes from the eventual #4756 PR.
> encapsulates Session.state field

- server/tserver/src/main/java/org/apache/accumulo/tserver/session/SingleScanSession.java
Normals scans were not running all session cleanup code like batch scans were.  AFAICT this change does not impact tablet severs and only scan severs.  The code that was not being called only seems to do some clean up on scan severs.  Following the code this change should cause SnapshotTablet.close() to be called now when a normal scan session is cleaned up on a scan server.
> Does all session clean up for normal scans

- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ThriftScanClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/MultiScanSession.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/ScanSession.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/SingleScanSession.java
This is manual refactor of how scan sessions track scan task. MultiScanSession and SinceScanSession both extend ScanSession.  Each was tracking  scan task separately.  Moved this tracking into the parent class ScanSession.  This refactoring is needed for #4756 but want to do it on its own to simplify review for bug fix release changes.
> refactors how scan sessions track scan task

- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
The ServiceLock calls ZooKeeper.exists(path, this) in the constructor, where "this" is a Watcher. Looking at the places where ServiceLock is constructed I found several places where this was being done inside of a loop which may end up creating multiple watchers in the ZooKeeper client instance. This change moves the ServiceLock construction outside of the loop.
Reported in https://lists.apache.org/thread/23c6g3rpbmclnwm4lmbskt1w4mw2h6ty
> Reuse ServiceLock instances

- core/src/main/java/org/apache/accumulo/core/metrics/MetricsProducer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ThriftScanClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerScanMetrics.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/scan/LookupTask.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/scan/NextBatchTask.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/scan/ScanTask.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/ScanSession.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/Session.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java
- test/src/main/java/org/apache/accumulo/test/ZombieScanIT.java
Changes in this commit :
* Removed scan sessions with an associated running thread will continue to show up in listscans.  Previously they would stop showing up after the interrupt atomic boolean was set.
* When a scan session is removed and it has an associated runing thread then it will be interrupted.  This is in addition to setting the interrupt atomic boolean.  Previously only the atomic boolean was set.
* A new metric will count removed scan session that still have a running thread.  Scan session are removed when the client is no longer interested in the result.  The new metric name is `accumulo.scan.zombie.threads`.
* A new test that checks the new metric is working, listscans shows zombie scans, and that stuck threads are interrupted.
* Scan sessions can have an associated scans …
> adds metric to count zombie scans

- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchReaderIterator.java
- test/src/main/java/org/apache/accumulo/test/functional/ScanSessionTimeOutIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ScannerIT.java
When not all data is read from a scanner it can leave server side scan sessions open.  When the scanner object is closed on the client side it should close these server side scan sessions.  The batch scanner was not doing this.  Updated the batch scanner to close sever side sessions. Added test for the scanner and batch scanner to ensure sessions are cleaned up.  Improved an existing test related to session timeout.
> cleanup scan session when batch scanner closed

- server/tserver/src/main/java/org/apache/accumulo/tserver/ThriftScanClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/scan/ScanParameters.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/Session.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/session/SessionManagerTest.java
- test/src/main/java/org/apache/accumulo/test/ZombieScanIT.java
Before this change when a tablet was closing it would prevent new scans from starting and wait for running scans to finish.  This could cause the tablet to become unavailable for long periods of time.  After this change tablets will no longer wait on running scans to complete.  They will set something to interrupt the thread and then disable the client scan session which prevents the client form ever seeing any data after the tablet is closed.  Once all scan sessions are disabled the tablet will proceed to close.  Disabling the scan session will cause the client side scanner to eventually switch to the new tablet server where the tablet is loaded.
Its possible that threads may be left running on the tablet server therefore it will be important to also implement #4756
fixes #4757
> Stops waiting on scans during tablet close.

- core/src/test/java/org/apache/accumulo/core/file/rfile/AbstractRFileTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/IndexedDocIteratorTest.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/MapReduceIT.java
- minicluster/src/test/java/org/apache/accumulo/minicluster/MiniAccumuloClusterExistingZooKeepersTest.java
This PR attempts to address all String-to-bytes and bytes-to-String conversions so they all consistently use UTF-8 (see more commentary in https://github.com/apache/accumulo/pull/3815). This is a follow-on to #4791 and **covers fixes to code in the main branch that was not present in 2.1.**
The following fixes have been made:
- String-to-bytes: `String.getBytes()` -> `String.getBytes(UTF_8)`
- Bytes-to-String: `new String(byte[])` -> `new String(byte[], UTF_8)`
- No instances of `String::new` or `String::getBytes` were found that were missing UTF-8 specification
Fixes https://github.com/apache/accumulo/issues/4765 "Fix String-to-bytes and bytes-toString for UTF-8 for all remaining code"
> Fix String-to-bytes and bytes-to-String for UTF-8 Pt. 3: main

- core/src/main/java/org/apache/accumulo/core/client/admin/InstanceOperations.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/InstanceOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletLocator.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ZookeeperLockChecker.java
- shell/src/main/java/org/apache/accumulo/shell/commands/ListCompactionsCommand.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_1_IT.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
Modified InstanceOperations.getActiveCompactions to handle addresses for Compactors in addition to TabletServers. Added InstanceOperations method to get Compactor addresses, it was missing.
> Modified InstanceOperations.getActiveCompactions for Compactors

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/memory/LargestFirstMemoryManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/memory/TabletMemoryReport.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/memory/LargestFirstMemoryManagerTest.java
- test/src/main/java/org/apache/accumulo/test/ScanServerMaxLatencyIT.java
Adds a new property that will initiate a minor compaction based on the age of data in memory. Tablets now roughly track that age of the first write to a tablets in memory map and when this age exceeds a configured threshold a minor compaction is initiated.
fixes #3397
> Adds property to minor compact based on age of data in memory

- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/Bulk.java
- core/src/main/java/org/apache/accumulo/core/lock/ServiceLockData.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/ExternalCompactionFinalState.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/RootTabletMetadata.java
- core/src/main/java/org/apache/accumulo/core/util/LazySingletons.java
- core/src/main/java/org/apache/accumulo/core/util/json/ByteArrayToBase64TypeAdapter.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/RootGcCandidates.java
- server/base/src/main/java/org/apache/accumulo/server/util/ServiceStatusCmd.java
- server/base/src/main/java/org/apache/accumulo/server/util/fateCommand/FateSummaryReport.java
- server/base/src/main/java/org/apache/accumulo/server/util/fateCommand/FateTxnDetails.java
- server/base/src/main/java/org/apache/accumulo/server/util/serviceStatus/ServiceStatusReport.java
- server/base/src/main/java/org/apache/accumulo/server/util/serviceStatus/StatusSummary.java
Configure Gson to no longer use JDK sun.misc.Unsafe as that can cause some strange behavior and Unsafe could change in future JDKs. This required making sure any serialized class has a default constructor and removing the final keyword from any member variables.
Issue #4837
> Disable Gson JDK sun.misc.Unsafe usage

- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchReaderIterator.java
The iterator now uses a Timer for tracking elapsed time which is based on nano time instead of System millis
This closes #4804
Also I noticed a possible bug with this that I will open another issue for. I also plan to open up a follow on PR to fix up ThriftScanner as well as it could use some of the same changes
> Update TabletServerBatchReaderIterator to use nanotime

- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
The Metadata constraint was allowing rows that started with `!!~` a free pass. AFAIK no code in Accumulo should produce a row with this prefix, so removed the code.  I suspect this may be somehow related to previous versions of accumulo where the root table was instead a root tablet which was  special tablet in the metadata table, but not really sure.
> remove mysterious pass in MetadataConstraints class

- core/src/main/java/org/apache/accumulo/core/clientImpl/ScannerImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ScannerIterator.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftScanner.java
- core/src/main/java/org/apache/accumulo/core/util/Timer.java
Update `ThriftScanner` to use nano time to be consistent with elapsed time tracking in other locations. Also, convert `timeOut` to be a Duration to prevent future errors. This value was being converted to seconds from millis which is error prone as there was not a good indication the unit was in seconds.
This is a follow on to #4864
As a side note, there are plenty of other timeout related properties that are part of the scanner code. I started to convert those as well to Duration but it cascaded and started touching a lot of classes which i didn't think was a good idea for 2.1. However, I was thinking as part of 3.1 and 4.0 we may want to update some more fields in classes from a long to a Duration (assuming no performance concerns). Here are some examples I found but I am sure there are …
> Update ThriftScanner to use nanotime

- server/monitor/pom.xml
- server/monitor/src/main/java/org/apache/accumulo/monitor/util/logging/RecentLogs.java
This improves concurrency by removing the synchronized blocks and replacing the LinkedHashMap with a Caffeine cache. The cache size is set to a max of 50 which matches the previous map limit.
> Replace RecentLogs LinkedHashMap with Caffeine

- server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java
- test/src/main/java/org/apache/accumulo/test/functional/ScanIdIT.java
closes #4868
- Batch scans scan ids are now set
- At the same time, got rid of code duplication and improved readability of `SessionManager.getActiveScans()`
- Added functionality to test this case in `ScanIdIT`
> Bug fix no scan id for batch scans

- core/src/main/java/org/apache/accumulo/core/client/admin/InstanceOperations.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/SnapshotTablet.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/TabletBase.java
- test/src/main/java/org/apache/accumulo/test/CloseScannerIT.java
- test/src/main/java/org/apache/accumulo/test/ZombieScanIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ScanSessionTimeOutIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ScannerIT.java
New ITs were added in #4840 and #4841 for zombie scan metrics and ensuring that scanners close scan sessions.  This commit adapts these new test to also run against scan servers.  For the zombie scan case found a bug in the scan sever where the session manager cleanup thread would get stuck forever in SnapshotTablet.close() preventing any further session cleanup.  Fixed this bug by changing SnapshotTablet.close() to no longer wait forever for scans to finish.
> adapts new scan session tests to also run on scan servers

- server/monitor/pom.xml
- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/ECResource.java
Each request to the monitor for the list of external compactions would create a copy of the per compaction information in the o.a.a.m.r.c.RunningCompaction constructor.  For many concurrent request when there are lots of external compactions running this could cause memory problems on the monitor.
This commit changes the code to only create a single RunningCompaction object every 30 seconds that is used by all request.  This should lower the amount of memory used when there are concurrent request or even refreshing the page really frequently.
> lowers memory burden of listing external compactions in monitor

- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
Variables used with nanoTime were being initialized to zero.  If nanoTime were negative it would lead to the elasped time computation with these variables always being negative. Initialized the variables using nanoTime instead of zero to fix the elapsed time computation.
> fixes nanoTime bug in Monitor

- core/src/main/java/org/apache/accumulo/core/file/blockfile/impl/ScanCacheProvider.java
- core/src/main/java/org/apache/accumulo/core/logging/LoggingBlockCache.java
- core/src/main/java/org/apache/accumulo/core/summary/SummaryReader.java
- src/build/ci/find-unapproved-chars.sh
Addes detailed trace logging for the accumulo block caches that can be used for scans.
With the following log4j config
```
logger.cache.name = org.apache.accumulo.cache
logger.cache.level = trace
```
can see output like the following with these changes when running a few scans.
```
2024-09-10T23:08:47,821 [accumulo.cache] TRACE: INDEX loader:299585732 getDependencies() returned [hdfs://localhost:8020/accumulo/tables/1/default_tablet/A000003t.rf!RootData]
2024-09-10T23:08:47,828 [accumulo.cache] TRACE: INDEX loader:299585732 load(201326592,{hdfs://localhost:8020/accumulo/tables/1/default_tablet/A000003t.rf!RootData=65}) returned 113 bytes in 823μs
2024-09-10T23:08:47,828 [accumulo.cache] TRACE: INDEX getBlock(hdfs://localhost:8020/accumulo/tables/1/default_tablet/A000003t.rfMRFile.index, …
```
> adds detailed trace logging for block caches

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/ResolvedSortedLog.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/logger/LogReader.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/log/RecoveryLogsIteratorTest.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/log/SortedLogRecoveryTest.java
The log recovery code would list the sorted walog files 3 to 4 times during recovery.  These changes modify the code to only list the files once.  Also the listing is cached for a short period of time to improve the case of multiple tablet referencing the same walogs.  This along with #4873 should result in much less traffic to the namenode when an entire accumulo cluster shutsdown and needs to recover.
Noticed this while working on #4873.  While working on that was generally trying to understand where the tsever was spending time when loading a tablet w/ walogs.  Noticed these directory listing showing up a little bit in timing logging I added.  Just a few milliseconds, but it seemed unnecessary to repeatedly list the same dir over and over.  Suspect the impact is worse at scale.
> Avoids listing the sorted logs dir multiple times during log recovery.

- server/base/src/main/java/org/apache/accumulo/server/constraints/BulkFileColData.java
- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/RootTabletMutatorImpl.java
- server/base/src/test/java/org/apache/accumulo/server/constraints/MetadataConstraintsTest.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkNewIT.java
closes #3505
- new class `BulkFileColData` to store the data needed to validate a BulkFileColumn update
Changes to check():
- now uses switch instead of if
- validation logic of each column now done in separate methods
- removed unnecessary checks and simplified logic where applicable (e.g., if checks that would never be true, same check done more than once)
- violations are no longer added to and returned by `validate` methods, only added to. Avoids confusion with how the methods should be used.
- initialized violations at start as a list instead of dealing with null. Null added extra unnecessary complexity.
Question:
- In this PR, I did not add any new check logic, only reorganized existing code to avoid making the PR too complicated. If it is more clear now that more checks need to be …
> Reorganizes MetadataConstraints

- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
- server/base/src/main/java/org/apache/accumulo/server/util/checkCommand/CheckRunner.java
- server/base/src/main/java/org/apache/accumulo/server/util/checkCommand/MetadataTableCheckRunner.java
- server/base/src/main/java/org/apache/accumulo/server/util/checkCommand/RootMetadataCheckRunner.java
- server/base/src/main/java/org/apache/accumulo/server/util/checkCommand/RootTableCheckRunner.java
- server/base/src/main/java/org/apache/accumulo/server/util/checkCommand/SystemConfigCheckRunner.java
- server/base/src/main/java/org/apache/accumulo/server/util/checkCommand/SystemFilesCheckRunner.java
- server/base/src/main/java/org/apache/accumulo/server/util/checkCommand/UserFilesCheckRunner.java
- test/src/main/java/org/apache/accumulo/test/AdminCheckIT.java
This is part of https://github.com/apache/accumulo/issues/4687
Changes:
- Added new `admin check` command
- `admin check list` prints the checks that can be run along with their descriptions and dependencies
- `admin check run` runs all the checks or a specified list of checks (explicitly provide each check, provide a regex of the checks to run, or just run all if no further args are provided). The dependencies are run first and if a checks dependency fails, the check is skipped
- Current impl of `admin check run` does not do any actual work besides printing that the check is running (to ensure correct run order) and returning an `OK` status
- New IT AdminCheckIT
- This IT includes a verion of the Checks where no work is actually done (right now, this is equivalent to the actual …
> New `admin check` command structure implementation

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
In #4873 a check was added to inspect walogs during tablet load to see if they had any data for the tablet.  This check happens prior to volume replacement that also runs during tablet load. Therefore if volume replacement is needed for the walogs then this check will fail because it can not find the files and the tablet will fail to load.
To fix this problem modified the new check to switch volumes if needed prior to running the check.
> switches volumes prior to recovery check

- server/tserver/src/main/java/org/apache/accumulo/tserver/NativeMapCleanerUtil.java
Observed many scan threads in the native map code attempting to create a native map iterator and blocking in registering a cleaner for the iterator.  The block was happening in jdk.internal.rf.PhantomCleanable.insert() which has a synchronized code block.  There is a single static cleaner object on the accumulo code so all scan threads that internact with a native map could end up contending on this single lock in the process.
This change creates 7 cleaners and therefore 7 locks to reduce the contention between scan threads.
> reduce scan thread contention on native maps

- server/tserver/src/main/java/org/apache/accumulo/tserver/NativeMap.java
- test/src/main/java/org/apache/accumulo/test/functional/NativeMapIT.java
Registering cleaners takes up resources and currently bumps into a global lock. The native map code is registering a cleaner for iterators, even in the case where the native code did not allocate an iterator. This code is called very frequently by scan threads.
This change does not register the cleaner in the case where the native code did not allocate a native iterator.  This should cause less contention between scan threads that are unrelated to each other.
> only registers cleaner in native map when needed

- core/src/main/java/org/apache/accumulo/core/file/rfile/RFile.java
Calls to Text.getBytes() should always be accompanied with a call to getLength() because an array that is longer than the data could be returned if set() was ever called on the Text object.
Replaced with a call to getRowData().toArray() that is more efficient and does not have the length problem.
Did a partial review of the code and found this one case.  Could be other cases like this lurking.
> removes bare usage of Text.getBytes()

- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
- server/base/src/test/java/org/apache/accumulo/server/constraints/MetadataConstraintsTest.java
MetadataConstraints has been updated to validate the format of the directory column. I noticed this validation was missing when looking at #4857
I made a comment [here](https://github.com/apache/accumulo/issues/4857#issuecomment-2365151923) about why this is targeted for main currently and not for 3.1. I can backport or target this in 3.1 once we decide how to handle the constraint code number (assuming we want to put this change into 3.1)
> Validate the format of a directory column

- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
- server/base/src/test/java/org/apache/accumulo/server/constraints/MetadataConstraintsTest.java
MetadataConstraints used to use the presence of a directory column to detect a split mutation. In version 4.0 split mutations will now set an operation id so this change updates the metadata constraints code to check that id vs the directory.
This closes #4857
Also, I added in a TODO marker in the code. It's also a placeholder because #4913 will add in a new validation check when merged and also because I was wondering if it would make sense to still validate that the directory exists in addition to the opid or not. The marker is obliviously temporary and can be removed when those questions are figured out.
> Use opid column to detect split mutation in MetadataConstraints

- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
- server/base/src/test/java/org/apache/accumulo/server/constraints/MetadataConstraintsTest.java
This change refactors the MetadataConstraint error codes that are new in version 3.1 to beginning with 3100. This makes future expansion easier and will allow keeping codes consistent across versions.
Issue #4915
**Note:** It is simpler to fix main separately as some codes have diverged and there are other conflicts, so there will be another PR opened up shortly for main and when this PR is merged this commit should be merged forward as an empty commit using `git merge -s ours`
Edit: PR for main is #4919
> Refactor error codes to allow future expansion in 3.1

- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
- server/base/src/test/java/org/apache/accumulo/server/constraints/MetadataConstraintsTest.java
This change refactors the MetadataContraint error codes that are new in version 3.1 to beging with 3100 and new in 4.0 to begin with 4000. This makes future expansion easier and will allow keeping codes consistent across versions.
3.1 branch is being fixed in #4918 and will be merged forward as an empty commit.
This closes #4915
> Refactor error codes to allow future expansion in 4.0

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/file/blockfile/cache/lru/LruBlockCacheManager.java
- core/src/test/java/org/apache/accumulo/core/file/blockfile/cache/BlockCacheFactoryTest.java
- core/src/test/java/org/apache/accumulo/core/file/blockfile/cache/TestLruBlockCache.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/AbstractRFileTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/RFileTest.java
If the TinyLfu cache works well as the default going forward then the LRU cache could eventually be dropped.
> deprecates lru block cache and makes TinyLfu the new default

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
Updates documentation and log message to instruct users on how to correctly run the changeSecret command.
> Fixes documentation for changeSecret command

- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
This fixes a bug with the admin "checkTablets" command (and maybe others) where the ZK connection is closed but is attempted to be accessed again leading to an exception. This makes sure the threads that try to access ZK are stopped before closing the connection
Discovered working on https://github.com/apache/accumulo/issues/4892. Fixed by @keith-turner
> Bug fix admin cmd

- server/manager/src/main/java/org/apache/accumulo/manager/metrics/fate/FateMetricValues.java
- server/manager/src/main/java/org/apache/accumulo/manager/metrics/fate/FateMetrics.java
In this PR
* refactored FateMetrics to use an EnumMap for TStatus metric counters
* this allows us to avoid coverting to/from strings for the TStatuses
* we can simplify the code to loop through this map when updating or constructing these metrics
* refactored the map of `txStateCounters` in `FateMetricValues` to use an EnumMap as well.  `FateMetrics` is the only spot where this map is retrieved so we simplify converting to/from Strings there too.
> Improvements to FateMetrics

- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchReaderIterator.java
Partially Fixes #4865 
So far I have implemented the change suggested in #4865.
Some things I've noticed while working on this:
1. It seems like this could be a good use for the [CountDownTimer](https://github.com/apache/accumulo/blob/main/core/src/main/java/org/apache/accumulo/core/util/CountDownTimer.java) util object since we could just create the object with `retryTimeout` and use `timeLeft()` to get the remaining time. This would simplify this code and make things more intuitive. The only issue is CountDownTimer only exists in 3.1 and above. If others agree, I could backport it into 2.1 and use it here.
2. Is it possible for the `timeoutLeft` value to be negative here? If so, what are the implications of that.
> Fix bug with calculating remaining timeout in TabletServerBatchReaderIterator

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/CompactionCoordinatorTest.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionTestUtils.java
Changes in how compactions work left three compaction properites unused and this change removes them.
> removed unused compaction properties

- core/src/main/java/org/apache/accumulo/core/fate/AbstractFateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/FateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/MetaFateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/ReadOnlyFateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/user/RowFateStatusFilter.java
- core/src/main/java/org/apache/accumulo/core/fate/user/UserFateStore.java
- core/src/main/java/org/apache/accumulo/core/logging/FateLogger.java
- core/src/test/java/org/apache/accumulo/core/fate/TestStore.java
- test/src/main/java/org/apache/accumulo/test/fate/FateStoreIT.java
- test/src/main/java/org/apache/accumulo/test/fate/user/UserFateStoreIT.java
This PR changes the usages of `Set<ReadOnlyFateStore.TStatus>` to `EnumSet<ReadOnlyFateStore.TStatus>`. EnumSet is typically more efficient.
The only thing that is a bit different after this conversion is the `public static final EnumSet<TStatus> ALL_STATUSES` within the TStatus enum used to be unmodifiable since it was constructed via `Collectors.toUnmodifiableSet()`. I could not find a way to create an unmodifiable EnumSet, so `ALL_STATUSES` is technically modifiable now. `ALL_STATUSES` is just used for convenience so we don't have to write out the code to create a set of this Enum each time. Looking at the calling code I don't think it is an issue that it is modifiable now.
> Use EnumSet for TStatus instead of Set

- core/src/main/java/org/apache/accumulo/core/fate/AbstractFateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/MetaFateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/WrappedFateTxStore.java
- core/src/main/java/org/apache/accumulo/core/fate/user/UserFateStore.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/UnSplittableMetadata.java
- core/src/test/java/org/apache/accumulo/core/fate/FateCleanerTest.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletManagementParameters.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ConditionalTabletMutatorImpl.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ConditionalTabletsMutatorImpl.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
- server/gc/src/test/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogsTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/metrics/fate/FateMetricValues.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/availability/LockTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/CompactRange.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/CleanUp.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/split/FindSplits.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- test/src/main/java/org/apache/accumulo/test/functional/AmpleConditionalWriterIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BinaryStressIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkNewIT.java
- test/src/main/java/org/apache/accumulo/test/functional/LargeRowIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ManyWriteAheadLogsIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitIT.java
- test/src/main/java/org/apache/accumulo/test/metrics/MetricsIT.java
- test/src/main/java/org/apache/accumulo/test/performance/NullTserver.java
* Fix incorrect generics on AbstractFateTxStoreImpl (an unused generic type parameter was hiding the generic parameter from the FateTxStore interface); AbstractFateTxStoreImpl does not need, and should not have, a generic parameter of its own
* Remove several unused variables and imports
* Remove unrecognized nonstandard warning suppression UnstableApiUsage
* Remove unused assignment in FateCleanerTest, keeping the side-effect
* Suppress unused warnings about private no-arg constructors that exist only for GSon (I wonder if there's a better way to do this... perhaps with explicit type adaptors that use the regular constructors?)
* Remove unused "parent" argument and field for ConditionalTabletMutatorImpl
* Cast `tabletMutator` to concrete TabletMutatorImpl type, rather than the abstract …
> Fix some code quality issues

- server/tserver/src/main/java/org/apache/accumulo/tserver/memory/LargestFirstMemoryManager.java
Removed maps in LargestFirstMemoryManager that cached time duration property values by table id. #4890 implemented caching for calls to AccumuloConfiguration.getTimeInMillis, so this higher level caching can be removed.
Closes #4860
> Removed cached configuration times

- core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftScanner.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ThriftScanClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/Session.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java
- test/src/main/java/org/apache/accumulo/test/ZombieScanIT.java
Previously, when a scan session was attempted to be cleaned up but couldn't and was deferred for later, the scan session id would still be visible from things like the `listscans` command but would have a value of -1. This change:
- makes it so that the session id is still available in this situation
- improves logging related to scan session ids and logs the scan session ids in more places
- tests that invalid (0 = never set, -1 = no longer tracking) scan session ids are no longer seen
TODOs from issue
- most logs were just printing the `Session` so just added the id to the toString()
- no changes needed here, covered by addition of the session id to Session.toString()
- Surveyed some classes of interest 
- TabletClientHandler
- Considered from its use of `Session` objects, but there is …
> scan session id now available when session cleanup is deferred

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/InstanceOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ZookeeperLockChecker.java
- core/src/main/java/org/apache/accumulo/core/lock/ServiceLockPaths.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadata.java
- core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/ExternalCompactionUtil.java
- core/src/test/java/org/apache/accumulo/core/lock/ServiceLockPathsTest.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
- server/base/src/main/java/org/apache/accumulo/server/manager/LiveTServerSet.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/DeadServerList.java
- server/base/src/main/java/org/apache/accumulo/server/util/AccumuloStatus.java
- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
- server/base/src/main/java/org/apache/accumulo/server/util/ServiceStatusCmd.java
- server/base/src/main/java/org/apache/accumulo/server/util/TabletServerLocks.java
- server/base/src/main/java/org/apache/accumulo/server/util/ZooZap.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- test/src/main/java/org/apache/accumulo/test/ScanServerConcurrentTabletScanIT.java
- test/src/main/java/org/apache/accumulo/test/ScanServerGroupConfigurationIT.java
- test/src/main/java/org/apache/accumulo/test/ScanServerIT.java
- test/src/main/java/org/apache/accumulo/test/ScanServerMetadataEntriesIT.java
- test/src/main/java/org/apache/accumulo/test/ScanServerMultipleScansIT.java
- test/src/main/java/org/apache/accumulo/test/ScanServerShutdownIT.java
- test/src/main/java/org/apache/accumulo/test/functional/MemoryStarvedScanIT.java
- test/src/main/java/org/apache/accumulo/test/functional/TabletManagementIteratorIT.java
- test/src/main/java/org/apache/accumulo/test/functional/TabletResourceGroupBalanceIT.java
- test/src/main/java/org/apache/accumulo/test/lock/ServiceLockPathsIT.java
Updated ServiceLockPaths to use Predicates for resource group and hostname matching.  Hoping this can lead to more advanced and efficient server filtering in the shell and monitor.
> updated ServiceLockPaths to use Predicates

- core/src/main/java/org/apache/accumulo/core/clientImpl/ZookeeperLockChecker.java
- core/src/main/java/org/apache/accumulo/core/lock/ServiceLockPaths.java
- core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java
- core/src/test/java/org/apache/accumulo/core/lock/ServiceLockPathsTest.java
- server/base/src/main/java/org/apache/accumulo/server/manager/LiveTServerSet.java
- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
- server/base/src/main/java/org/apache/accumulo/server/util/TabletServerLocks.java
ServiceLockPaths allows filtering hosts using a predicate.  In the case where a predicate was passed in that always returned true a HostPort object needlessly allocated to pass to the predicate.  These changes refactor the predicate to only allocate the HostAndPort object when needed.  Before the changes in #4943 this was the behavior, that when all host were wanted no objects were allocated.
> avoids uneeded object allocation on ServiceLocksPath

- server/manager/src/main/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueue.java
CompactionJobPriorityQueue.getAsync was not doing clean up of internal data strucs when it removed a job from the queue.  Changed it call an existing method that does this cleanup.
> fixes bug in CompactionJobPriorityQueue

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
The property instance.volumes.upgrade.relative was used by 2.1.0 upgrade code is no longer used and is removed in this change.
> removes unused property

- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
Fixes #4956
The stack track included in the ticket indicates that a ConcurrentmodificationException occurred in Monitor.EventCounter:
```
java.util.ConcurrentmodificationException
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1511)
at java.util.HashMap$HashIterator.next(HashMap.java:1544)
at java.util.HashMap$HashIterator.next(HashMap.java:1542)
at org.apache.accumulo.monitor.Monitor$EventCounter.calculateRate(monitor.java:23)
at org.apache.accumulo.monitor.Monitor.getLookupRate(Monitor.java:977)
at org.apache.accumulo.monitor.rest.tservers.TabletServerInformation.updateTabletServerInfo(TabletServerinformation.java:162)
at org.apache.accumulo.monitor.rest.tservers.TabletServerInformation.(TabletServerInformation:101)
at …
```
> Make EventCounter thread safe

- core/src/main/java/org/apache/accumulo/core/client/admin/InstanceOperations.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/InstanceOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/lock/ServiceLockPaths.java
Changes filtering in the getServers API call so that it can prune branches while walking the tree of servers in zookeeper.
> refactors filtering in getServers API call

- assemble/bin/accumulo-cluster
- assemble/bin/accumulo-service
- assemble/conf/accumulo-env.sh
Consistently setting the env variable to include the group
and process number for all processes enables us to remove
code in the other scripts that try and find / apply the
group to various things. The specific issue this solves
is that the PID file name ended up being incorrect when
trying to stop the manager and garbage collector. The
PID file could not be found, because the calculated name
was incorrect, and the processes were not stopped.
Closes #4951
> Set ACCUMULO_SERVICE_INSTANCE consistently for all processes

- core/src/main/java/org/apache/accumulo/core/client/PluginEnvironment.java
- core/src/main/java/org/apache/accumulo/core/spi/common/ServiceEnvironment.java
- core/src/test/java/org/apache/accumulo/core/spi/balancer/HostRegexTableLoadBalancerTest.java
- core/src/test/java/org/apache/accumulo/core/spi/balancer/TableLoadBalancerTest.java
- core/src/test/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlannerTest.java
Adds static methods for creating PluginEnv.Configuration objects from a Map<String,String> and updates tests to use them.  These new methods make it easier for downstream projects to create these object using only public APIs.
> adds a static method for creating a configuration object

- server/base/src/main/java/org/apache/accumulo/server/conf/store/PropStoreKey.java
- server/base/src/main/java/org/apache/accumulo/server/conf/util/PropSnapshot.java
PropStore was logging on some events that caused a need to refresh the properties and not others.  Modified to consistently log whenever an event caused the properties to be invalidated.
> Consistently log when property stores is invalidated

- core/src/main/java/org/apache/accumulo/core/classloader/DefaultContextClassLoaderFactory.java
- start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloVFSClassLoader.java
- start/src/main/java/org/apache/accumulo/start/classloader/vfs/ContextManager.java
When a new classloader context is set and then used its possible the config change has not propagated to all servers by the time a scan attempts to use the context.  This change invalidates the config cache and retries when when a context is not found.
> invalidates config cache and retries when classloader context not found

- server/base/src/main/java/org/apache/accumulo/server/security/delegation/AuthenticationTokenSecretManager.java
AuthenticationTokenSecretManager was calling System.currentTimeMillis() twice causing the following sporadic failure. Modified to only get time once to avoid test failure.
```
[ERROR] org.apache.accumulo.server.security.delegation.AuthenticationTokenSecretManagerTest.testGenerateToken -- Time elapsed: 0.011 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <1729199138567> but was: <1729199138568>
at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:166)
at …
```
> fixes test failure for AuthenticationTokenSecretManager

- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
When a hosting request was sent to the manager and the manager determined there was nothing to do it would attempt to create a batch scanner with an empty set of ranges and this would fail.  Added a check to see if the ranges were empty.
> fixes bug in ondemand tablet hosting

- core/src/main/java/org/apache/accumulo/core/metrics/Metric.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/QueueMetrics.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueue.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueueTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/queue/CompactionJobQueuesTest.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionMetricsIT.java
This adds 2 new groups of stats to track information about queued compaction jobs. The first stat is a timer that keeps track of when jobs are being polled and give information on how often/fast jobs are exiting the queue. The second group of stats is a min/max/avg and is tracking age information about how long jobs are waiting on the queue.
This closes #4945
This is a draft for now because there is a couple outstanding things to do and it probably still needs a little bit of polishing but I wanted to post what I had to get feedback. The tests could also be improved a bit I think. I was trying to think of a good way to check that the stats are correct but the values are going to be non-deterministic as it's all timing in based so it would be hard to check exact values. 
Todo/questions:
1. …
> Add metrics to track time compaction jobs are queued

- core/src/main/java/org/apache/accumulo/core/fate/FateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/user/FateMutator.java
- core/src/main/java/org/apache/accumulo/core/fate/user/FateMutatorImpl.java
- core/src/main/java/org/apache/accumulo/core/fate/user/UserFateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooUtil.java
- test/src/main/java/org/apache/accumulo/test/fate/MultipleStoresIT.java
- test/src/main/java/org/apache/accumulo/test/fate/user/FateMutatorImplIT.java
This PR
* Makes it so the reservation column is created on reservation and deleted on unreservation (no longer store an unreserved value in the column)
* Addresses a bug with `MultipleStoresIT.testDeadReservationsCleanup()` (`ZooUtil.LockID` was missing `equals()` and `hashCode()`) (see NOTE)
NOTE about original bug when I first attempted these changes:
After making the reservation column changes, I tested `testDeadReservationsCleanup()` to see if I could recreate the same bug noted in this thread https://github.com/apache/accumulo/pull/4524#discussion_r1670884720 (TLDR - <4 transactions would show as being reserved, even though 4 threads were working on 4 transactions). I was able to recreate the bug (extremely rarely until I messed with the `DeadReservationCleaner` timings), but found …
> Improvements to reservation column in FATE table and bug fix

- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
fixes an issue with how Fates `WorkFinder` handles `InterruptedException`s which can lead to an infinite error loop and leave the `WorkFinder` broken
I'm wondering if this is a problem elsewhere as there are many places that handle an `InterruptedException` the same way
```
} catch (InterruptedException e) {
Thread.currentThread().interrupt();
...
}
````
The conversation which brought about this PR was from:
#4965
This PR in conjunction with #4965 close #4906
> Fixes a Fate bug (part 2)

- server/base/src/main/java/org/apache/accumulo/server/fs/FileManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerScanMetrics.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java
The metrics for computing the current number of open files on a tablet server was incorrect over time.  Used the semaphor limiting open files to compute the number of open files.   The removes the need to correctly
increment and decrement files opened which had a bug.
> corrects open file metric

- core/src/main/java/org/apache/accumulo/core/metrics/MetricsInfo.java
- server/base/src/main/java/org/apache/accumulo/server/metrics/MetricsInfoImpl.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/compactor/src/test/java/org/apache/accumulo/compactor/CompactorTest.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- test/src/main/java/org/apache/accumulo/test/functional/ZombieTServer.java
The server idle metric needs to include the tag for queue information.
Without this tag, compactor metrics cannot be grouped into their respective queues.
> Adds the queue to the common tags for compactor

- core/src/main/java/org/apache/accumulo/core/clientImpl/ZookeeperLockChecker.java
- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooCache.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/ZookeeperLockCheckerTest.java
This change indirectly fixes ZombieScanIT.  That test was creating scanners running in a thread and interrupting those threads.  The interrupts were routinely being ingnored by code in zoocache that ignores interrupts when reading from zookeeper.  Looking at the code that was reading from zookeeper, that code was attempting clear entries in the cache.  Modified this code to avoid reading from zookeeper when clearing the cache.
> avoid reading from zookeeper when clearing zoocache entries

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
Adds additional words to call out the off-heap nature of the memory.maps when using native maps.
> Clarify property descriptions

- server/base/src/main/java/org/apache/accumulo/server/fs/FileManager.java
FileManager has a goal of doing all I/O outside of locks in its code to avoid one scan blocking another w/ I/O related to opening and closing files.  The code violated this goal when closing deep copies on an rfile and did this inside a lock.  This change moves the close outside of the lock.
> closes reader deep copies outside of lock in FileManager

- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/QueueMetrics.java
Fixes the following NPE seen during local testing
```
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "io.micrometer.core.instrument.MeterRegistry.gauge(io.micrometer.core.instrument.Meter$Id, Object, java.util.function.ToDoubleFunction)" because "registry" is null
at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
at org.apache.accumulo.core.util.threads.ThreadPools.checkTaskFailed(ThreadPools.java:143)
at org.apache.accumulo.core.util.threads.ThreadPools.lambda$static$0(ThreadPools.java:113)
at java.base/java.lang.Iterable.forEach(Iterable.java:75)
at org.apache.accumulo.core.util.threads.ThreadPools.lambda$static$1(ThreadPools.java:110)
at …
```
> Fixes NPE in QueueMetrics

- core/src/main/java/org/apache/accumulo/core/metrics/MetricsInfo.java
- server/base/src/main/java/org/apache/accumulo/server/metrics/MetricsInfoImpl.java
- server/compaction-coordinator/pom.xml
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- server/compaction-coordinator/src/test/java/org/apache/accumulo/coordinator/CompactionCoordinatorTest.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/compactor/src/test/java/org/apache/accumulo/compactor/CompactorTest.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- test/src/main/java/org/apache/accumulo/test/functional/ZombieTServer.java
- test/src/main/java/org/apache/accumulo/test/metrics/TestStatsDSink.java
The metrics initialization code supported adding registries prior to initialization, however nothing used this functionality.  Simplified the code by removing support for pending registries.  This simplification allowed avoiding using the composite metrics registry when there is only a single registry.
> Simplifies metrics initialization

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
Some tablet update metrics were incrementing a counter by zero. Changed the increment to one.  Noticed this while working on #4511.
> fixes tablet update metrics incrementing

- server/base/src/main/java/org/apache/accumulo/server/metrics/MetricsInfoImpl.java
There was a meter filter related to the replication metrics that no longer exists.  This filter should be removed.
> removed uneeded replication meter filter

- core/src/main/java/org/apache/accumulo/core/fate/AdminUtil.java
- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
- core/src/main/java/org/apache/accumulo/core/fate/FateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/WrappedFateTxStore.java
- core/src/main/java/org/apache/accumulo/core/fate/user/UserFateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/MetaFateStore.java
- core/src/main/java/org/apache/accumulo/core/logging/FateLogger.java
- core/src/test/java/org/apache/accumulo/core/fate/TestStore.java
`admin fate delete` allows users to delete a transaction. If this transaction is a USER transaction, `UserFateStore.delete()` is how this is achieved. The admin code allows transactions with a status of SUBMITTED, IN_PROGRESS, NEW, FAILED, FAILED_IN_PROGRESS, SUCCESSFUL to call `delete()`, but the `delete()` code only allows NEW, SUBMITTED, SUCCESSFUL, FAILED. I changed the `UserFateStore.delete()` code to match the admin delete code. I'm not sure which one should be changed, but one of them should be.
> Fixes discrepancy between `admin fate delete` and `UserFateStore.delete`

- core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java
When looking for any accumulo server to connect to client code would read all servers and check their locks. This change avoid checking locks for all servers and only checks the locks for the ones the code tries to connect to.
> speeds up finding any server to connect to

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/LoadFiles.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkNewIT.java
The bulk import code was reading all tablets in the bulk import range for each range being bulk imported. This resulted in O(N^2) metadata table scans which made really large bulk imports really slow.
Added a new test that bulk imports thousands of files into thousands of tablets.  Running this test w/o the fixes in this PR the following time is seen for the fate step.
```
DEBUG: Running LoadFiles.isReady() FATE:USER:6320e73d-e661-4c66-bf25-c0c27a0a79d5 took 289521 ms and returned 0
```
With this fix in this PR seeing the following times for the new test, so goes from 290s to 1.2s.
```
DEBUG: Running LoadFiles.isReady() FATE:USER:18e52fc2-5876-4b01-ba7b-3b3c099a82be took 1225 ms and returned 0
```
This bug does not seem to exists in 2.1 or 3.1.  Did not run the test though, may be …
> fixes slow bulk import with many tablets and file

- core/src/main/java/org/apache/accumulo/core/spi/compaction/CompactionPlanner.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java
- core/src/test/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlannerTest.java
- core/src/test/java/org/apache/accumulo/core/util/compaction/CompactionPrioritizerTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionService.java
CompactionManager.mainLoop runs in the TabletServer looking for tablets that need to be compacted. It ends up calling CompactionService.submitCompaction at some interval for each hosted Tablet. CompactionService.getCompactionPlan will make a CompactionPlan for the tablet and log a warning if no CompactionPlan is created but the number of files is larger than TSERV_SCAN_MAX_OPENFILES. When there are no compactions running for the tablet and no plan is calculated, then DefaultCompactionPlanner.makePlan takes into account TABLE_FILE_MAX and TSERV_SCAN_MAX_OPENFILES and will create a system compaction that considers all of the files and calculates which ones need to be compacted to get below the limit. Finally, a priority is calculated by calling CompactionJobPrioritizer.createPriority. …
> Increase majc priority for tablets over file size threshold

- core/src/main/java/org/apache/accumulo/core/clientImpl/InstanceOperationsImpl.java
- test/src/main/java/org/apache/accumulo/test/InstanceOperationsIT.java
There was a bug in InstanceOperationsImpl.getServer() where `getScanServer()` was being used for the `TABLET_SERVER` case.
https://github.com/apache/accumulo/blob/e45b3b400732fddb9b07f8319462e9191d1dcb82/core/src/main/java/org/apache/accumulo/core/clientImpl/InstanceOperationsImpl.java#L504-L521
> Fix bug in InstanceOperationsImpl.getServer()

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionTestUtils.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_1_IT.java
The test was timing out because it never started running compactions created by the test method. Instead, the compactor process was running compactions created by the previous test method because the previous test created a table with a lot of files, started a user compaction, then cancelled the user compaction. The recent changes in #5026 caused a bunch of system compactions to be generated for the table. The two test methods share the same compaction queue, so the compactor was busy running the system compactions.
To fix this issue I backported a property added in #3955 that makes the compactor cancel check method time configurable and I deleted the table in the test method that created a lot of files.
Closes #5052
> Fix ExternalCompaction_1_IT.testPartialCompaction failure

- core/src/main/java/org/apache/accumulo/core/lock/ServiceLockPaths.java
Many operations like listcompactions, listscans, admin serviceStatus check the zookeeper locks of server processes.  These lock checks are currently done serially and each require a RPC to zookeeper.  This change parallelizes the lock checks.
> speeds up checking zoo locks for lots of server processes

- core/src/main/java/org/apache/accumulo/core/Constants.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/NamespaceMapping.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/Namespaces.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/NamespaceMappingTest.java
- server/base/src/main/java/org/apache/accumulo/server/init/ZooKeeperInitializer.java
- server/base/src/main/java/org/apache/accumulo/server/tables/TableManager.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/Utils.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/namespace/create/PopulateZookeeperWithNamespace.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/namespace/delete/NamespaceCleanUp.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/namespace/rename/RenameNamespace.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader11to12.java
- server/manager/src/test/java/org/apache/accumulo/manager/upgrade/Upgrader11to12Test.java
This PR is part of an ongoing work to improve efficiency and reduce slowdown of retrieving and writing namespace names and table names in ZooKeeper. These particular changes modify the namespace names, and **a follow-up PR in the near future will modify the table names**. It replaces the use of the `/name` nodes under namespaces with a namespace id-to-name mapping in a Json format stored under the `/namespaces` node. With this, when any function wants to retrieve a namespace name, ZooKeeper will only need to read the single mapping instead of iterating through all `/name` nodes every time.  
**New files added for implementation:**
- `core/src/main/java/org/apache/accumulo/core/clientImpl/NamespaceMapping.java`: Class that holds functionality for initializing, retrieving, writing, …
> Add ZooKeeper Namespace Id-to-name mapping

- core/src/main/java/org/apache/accumulo/core/util/Validators.java
- core/src/test/java/org/apache/accumulo/core/util/ValidatorsTest.java
Fixes validation for table ids by making sure all tables in the accumulo namespace are considered and not just root and metadata
This closes #5059
> Update Table Id validator to accept all Accumulo tables

- core/src/main/java/org/apache/accumulo/core/clientImpl/NamespaceMapping.java
* Add a check to make sure that if the name exists in the mapping, then it results in a namespace exists exception, rather than only do that if the ID exists in the mapping (this fixes the NamespaceIT failure seen after #4996 was merged)
* Make NamespaceMapping.put() idempotent by checking the current mapping against the desired mapping (this preserves existing behavior at this point in the code, which was previously being handled by the Utils method that was deleted)
Trivial changes:
* Add some stricter checks for parameters to NamespaceMapping methods (final and require non-null)
* Avoid NPE problems by comparing the known non-null string on the left side of the .equals()
* Make name and inline comments consistent between rename and put methods
> Minor fixes to NamespaceMapping

- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueue.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueueTest.java
> Ensure compaction queue max size is at least 1

- assemble/bin/accumulo-cluster
- assemble/bin/accumulo-service
- assemble/conf/accumulo-env.sh
The accumulo-cluster script would ssh to the host for each server that it wanted to start or stop. This change moves the processing of the number of servers that need to be started or stopped to the accumulo-service script so that only one ssh connection needs to be created to the host for that server type and group.
> Reduce ssh connections to hosts in accumulo-cluster

- server/base/src/main/java/org/apache/accumulo/server/metrics/ProcessMetrics.java
When using a sum aggregator for metric queries, the possible negative value removes values causing graphing issues.
Removes the startup value of the service (-1) in favor of reporting an initial error state.
> Remove negative value from server idle

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/manager/src/main/java/org/apache/accumulo/manager/split/SeedSplitTask.java
- server/manager/src/main/java/org/apache/accumulo/manager/split/Splitter.java
When tablets needed to split they were queued in a thread pool to seed a fate operation.  When the tablet group watcher ran again if the tablet was still in queue it would add it again. This would not cause any correctness issues, but it would cause a lot of wasted work. Also if one tablet was queued multiple times it could prevent another tablet that was not queued at all from being added.  This made splitting very when a large number of tablets needed to split very inefficient and slow.
> avoids uneeded work when splitting tablets

- core/src/main/java/org/apache/accumulo/core/lock/ServiceLockPaths.java
- core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPoolNames.java
Changes made in #5058 caused too many threads to be created in the manager when lots service lock paths were being requested. Updated code to avoid creating so many threads.
> fixes bug where service lock code created too many threads

- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
When a single tablet had multiple dead compactions the dead compaction cleanup code would attempt to write separate conditonal mutations for the same tablet.  For simplicity Ample does not support this case and throws an exception.  Reworked the code to only write a single conditional mutation per tablet for dead compaction detection.
> fixes bug with cleaning up multiple dead compactions in single tablet

- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
The status thread would always cancel tasks once the timer reached max wait and never remove them from the list of tasks. This causes the Update Status thread to wait indefinitely when calling gatherTableInformation.
This bug was found in 4.0 but originated in #3167
> Fix Manager hanging on shutdown command

- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
When the tablet group watcher is not making decisions that one would expect it is useful to see the information that it is using to make decisions.  This change adds trace logging of the information used to filter tablets in the TabletManagementIterator used by the TabletGroupWatcher.
> Logs information tablet group watcher uses to make filtering decisions

- core/src/main/java/org/apache/accumulo/core/metrics/MetricsDocGen.java
This PR makes it so that a table of contents is generated on the metrics docs page that links to each metrics category header.
Here is what the generated page looks like:
And here is what the markdown looks like:
```markdown
- [General Server Metrics](#general-server-metrics)
- [Compactor Metrics](#compactor-metrics)
- [Fate Metrics](#fate-metrics)
- [Garbage Collection Metrics](#garbage-collection-metrics)
- [Tablet Server Metrics](#tablet-server-metrics)
- [Scan Server Metrics](#scan-server-metrics)
- [Thrift Metrics](#thrift-metrics)
- [Block Cache Metrics](#block-cache-metrics)
- [Manager Metrics](#manager-metrics)
{::options parse_block_html="true" /}
<div markdown="1" class="metric-section">
**Type:** GAUGE  
...
```
> Add a table of contents to MetricsDocGen

- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooReader.java
- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooReaderWriter.java
- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooSession.java
Trivial change to zookeepers parameter to indicate that it's a connectionString
rather than merely a host or a list of hosts for zookeeper.
> Change names of zookeepers to connectString

- server/tserver/src/main/java/org/apache/accumulo/tserver/scan/LookupTask.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/scan/NextBatchTask.java
An exception was happening when a scan task was canceled before it ever ran.  This was caused by transitionFromRunning() executing when transitionToRunning() had never executed.  When this happened a precondition check that the scanThread was non-null would fail.  These changes only execute transitionFromRunning() when transitionToRunning() has executed.
> fixes exception for canceled scan task

- core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftScanner.java
ThriftScanner was logging a debug message when closing a scan and was too chatty.  Also the message was printing an object w/o a toString method.  Fixed the log message and lowered its level.
> lower level on thrift scanner log message and fix message

- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
Stops a directory not being found from preventing the search through the volumes from continuing
This closes #5087
> Handle FileNotFoundException during failed compaction cleanup

- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
If a tablet needs to both split and compact it is better to split first and compact after splitting so that the compaction work can be divided up better
This close #5101
> Prefer splitting over compacting

- test/src/main/java/org/apache/accumulo/test/functional/MemoryStarvedScanIT.java
Test started failing after recent metrics changes. The comment above the code block mentioned repeating the same check, but the code wasn't doing that. Modifying the code to do the same check fixed the issue.
> Fixed MemoryStarvedScanIT

- assemble/bin/accumulo-service
- assemble/conf/default-group-env.sh
Added per-resource group environment files that allows the user to provide JVM options and Accumulo property overrides
> Added ability for user to provide resource group overrides

- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
Fixes #5098 
* Modified the `ExternalCompactionsSnapshot` constructor to accept an `Optional<Map<String, TExternalCompaction>>`, ensuring the map is unmodifiable or empty if the optional is not present.
> Fix NPE caused by ExternalCompactions page in monitor

- assemble/bin/accumulo-cluster
- server/base/src/main/java/org/apache/accumulo/server/util/ZooZap.java
Closes #5109 
Required modifications to ZooZap to support resource groups.
> Modify accumulo-cluster to support starting and stopping groups of tservers

- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/FateIT.java
Related to #2474 and #2550. The sync fix in #2550 helped ensure that the ZooKeeper client had the updated status, it is still possible for the node to be deleted before the SUCCESSFUL transaction status is observed. This change makes FateIT more stable by accepting that as a valid possible outcome, and no longer fails when that happens.
> Fix flaky FateIT.testTransactionStatus()

- test/src/main/java/org/apache/accumulo/test/conf/store/PropCacheCaffeineImplZkIT.java
- test/src/main/java/org/apache/accumulo/test/conf/store/PropStoreZooKeeperIT.java
- test/src/main/java/org/apache/accumulo/test/conf/store/ZooBasedConfigIT.java
- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/ZooMutatorIT.java
- test/src/main/java/org/apache/accumulo/test/lock/ServiceLockIT.java
- test/src/main/java/org/apache/accumulo/test/zookeeper/ZooKeeperTestingServer.java
* Remove automatically-generated client object
* Simplify the way new client objects are constructed by using a functional interface to specify the constructor, and then automatically attaching the digest and checking that it's connected before returning
* Inline the private constructor into the public one
* Remove unused public methods
* Remove initPaths (redundant with ZooReaderWriter.mkdirs)
Also, make related changes to tests that use ZooKeeperTestingServer:
* Remove unnecessary exception handling
* Remove unused generated instanceId and path initialization in ZooMutatorIT and ServiceLockIT
* Update ServiceLockIT to remove unneeded inner classes and to simplify constructing ZooKeeper clients, relying on the fact that ZooKeeperTestingServer returns clients that have been verified …
> Simplify ZooKeeperTestingServer

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
The StatusThread.balanceTablets method could loop indefinitely in some cases, like when a TabletServer dies but is the target of a current migration. The status of the TabletServers is checked before this method is invoked and never updated. Created a new property to indicate how many iterations should pass before the Tablet Server status is re-checked.
> Check for tserver failure in balance loop after some iterations

- core/src/main/java/org/apache/accumulo/core/manager/balancer/BalanceParamsImpl.java
- core/src/main/java/org/apache/accumulo/core/spi/balancer/GroupBalancer.java
- core/src/main/java/org/apache/accumulo/core/spi/balancer/HostRegexTableLoadBalancer.java
- core/src/main/java/org/apache/accumulo/core/spi/balancer/TableLoadBalancer.java
- core/src/main/java/org/apache/accumulo/core/spi/balancer/TabletBalancer.java
- core/src/test/java/org/apache/accumulo/core/spi/balancer/BaseHostRegexTableLoadBalancerTest.java
- core/src/test/java/org/apache/accumulo/core/spi/balancer/GroupBalancerTest.java
- core/src/test/java/org/apache/accumulo/core/spi/balancer/HostRegexTableLoadBalancerReconfigurationTest.java
- core/src/test/java/org/apache/accumulo/core/spi/balancer/HostRegexTableLoadBalancerTest.java
- core/src/test/java/org/apache/accumulo/core/spi/balancer/SimpleLoadBalancerTest.java
- core/src/test/java/org/apache/accumulo/core/spi/balancer/TableLoadBalancerTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- test/src/test/java/org/apache/accumulo/test/ChaoticLoadBalancerTest.java
After merging #5070 RegexGroupBalanceIT started failing. Both GroupBalancer and HostRegexTableLoadBalancer have logic that throttles the frequency that they can be called do not return any migrations in this scenario. The change in #5070 modified the frequency in which the balancer is called from once for all DataLevel's to once per DataLevel. This caused the GroupBalancer and HostRegexTableLoadBalancer to return migrations for the ROOT DataLevel, but not the METADATA and USER DataLevels.
The solution in this commit is to push the DataLevel down to the Balancer in the BalancerParams so that the throttling can be done at the DataLevel level.
> Fixed failures in RegexGroupBalanceIT after merging PR #5070

- core/src/main/java/org/apache/accumulo/core/util/cleaner/CleanerUtil.java
- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
Reuses the zooCache from the serverContext instead of creating a new one for each instantiation of MetadataConstraints
This should result in less zookeeper connections as there is a higher chance of the serverContext's zooCache already being populated.
@ctubbsii I found this issue when testing 4.0 code and found that the fix could be applied in the 2.1 branch. 
Given your comment in CleanerUtil it looks like this change should be okay to do in 2.1, but I'm happy to target a later accumulo version.
> Reuse the zooCache from serverContext

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
Added two new properties that control the checking of the Fate transaction queue size in the background thread that resizes the Fate thread pool. This new logic will print a warning in the log that the Fate thread pool size property should be increased if the number of transactions in the queue is consistently larger than some multiple of the Fate transaction thread pool size.
> Enable check of Fate queue size for recommending property change

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/thrift-gen-java/org/apache/accumulo/core/tabletserver/thrift/TabletServerClientService.java
- core/src/main/thrift/tabletserver.thrift
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/LoadFiles.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/PrepBulkImport.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/TabletRefresher.java
- server/manager/src/test/java/org/apache/accumulo/manager/tableOps/bulkVer2/PrepBulkImportTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkNewIT.java
- test/src/main/java/org/apache/accumulo/test/performance/NullTserver.java
Bulk imports can add files to a tablet faster than compactions can shrink the number of files.  There are many scenarios that can cause this. The following are some of the situations that could cause this.
* Compactors are all busy when new bulk imports arrive.
* Many processes bulk import a few files to a single tablet at around the same time
* A single process bulk imports a lot of files to a single tablet
When a tablet has too many files it can eventually cause cascading problems for compaction and scan.  The change adds two properties to help avoid this problem.
The first property  is`table.file.pause`.  The behavior of this property is to pause bulk imports, and eventually minor compactions, when a tablets current file counts exceeds this property.  The default is unlimited and …
> Pauses bulk imports into tablets w/ too many files

- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZcNode.java
- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooCache.java
- core/src/main/java/org/apache/accumulo/core/util/cache/Caches.java
- core/src/test/java/org/apache/accumulo/core/fate/zookeeper/ZooCacheTest.java
- test/src/main/java/org/apache/accumulo/test/zookeeper/ZooCacheIT.java
- test/src/main/resources/log4j2-test.properties
For a nodes data in zookeeper ZooCache was caching when a node did not exist.  However for getChildren when a node did not exist it would not cache this and would always go to zookeeper. Also ZooCache was handling a null return from Zookeeper.getChildren that would never happen.  Fixed these issues.
fixes #5047
> Caches non-existence of ZK node for ZooCache.getChildren

- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ConditionalTabletMutatorImpl.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/commit/CommitCompaction.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/commit/CompactionCommitData.java
- test/src/main/java/org/apache/accumulo/test/functional/AmpleConditionalWriterIT.java
Previously the conditional mutation to commit a compaction would require all files in the tablet be the same as read earlier and on a busy tablet this could fail and retry often. The check has now been narrowed to only verify that the files involved with the compaction still exist. A new method was added to Ample called requireFiles(Set<StoredTabletFile> files) which creates a condition for each file column to verify each one exists.
This closes #5117
> Narrow the files checked by compaction commit

- server/base/src/main/java/org/apache/accumulo/server/split/SplitUtils.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitIT.java
This test was making a incorrect assumption that a table with no splits and data for a single row could not split.  What would actually happen is that the table would split once for the single row in the data and then still need to split but be unable to.  Added single split at table creation time to fix this.
Before these changes the test would add data to a table and then immediately check that its splits were zero.  The table would eventually split, but usually the check in the test would happen prior to this. This race condition in the test hid the flawed assumption in the test. Added a wait to the test to fix this.
> fixes SplitIT.bulkImportThatCantSplitHangsCompaction

- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZcNode.java
- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooCache.java
Adds an access count to the trace logging when a zoocache entry is removed because it was not used recently.  This will help find data that is being stored in zoocache and accessed infrequently which may cause uneedd watches.
> tacks number of accesses to zoocache entry for logging

- core/src/main/java/org/apache/accumulo/core/fate/AbstractFateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
- core/src/main/java/org/apache/accumulo/core/fate/FateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/user/FateMutator.java
- core/src/main/java/org/apache/accumulo/core/fate/user/FateMutatorImpl.java
- core/src/main/java/org/apache/accumulo/core/fate/user/RowExistsIterator.java
- core/src/main/java/org/apache/accumulo/core/fate/user/UserFateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/MetaFateStore.java
- core/src/main/java/org/apache/accumulo/core/logging/FateLogger.java
- core/src/test/java/org/apache/accumulo/core/fate/TestStore.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/iterators/SetEncodingIterator.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
- server/manager/src/main/java/org/apache/accumulo/manager/split/SeedSplitTask.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_1_IT.java
- test/src/main/java/org/apache/accumulo/test/fate/FateIT.java
- test/src/main/java/org/apache/accumulo/test/fate/FateStoreIT.java
Modified fate to seed fate transaction in single conditional mutation instead of multiple.
fixes #5097
> Makes seeding a fate transaction more efficient

- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
Using the new method added in #5153 the set of files checked in the conditional mutation for compacaction reserervation was reduced from all tablet files to only the files in the compaction job.  Noticed the conditinal mutation was not checking the user compaction requested field while making this change and added it.
> Narrows the set of files checked during compaction reservervation

- assemble/bin/accumulo-cluster
- assemble/bin/accumulo-service
* Update help descriptions for deprecated items
* Streamline debug output and add "DEBUG:" prefix
* Bash grammar fixes (double square brackets, remove unneeded quotes/curlies, etc.)
* Remove eval (use `bash -c` for local case instead)
* Use printf instead of bash 4.4 features for printing command to execute
* Use local variables where possible
* Remove unneded quoting in calls to accumulo-service using guilty knowledge of the fact that most of the options passed will be scalars without any spaces or special characters (improves readability)
* Fix broken computation of localhost addresses by filtering getent entries
> Fix accumulo-cluster

- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ConditionalTabletMutatorImpl.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/LoadFiles.java
- test/src/main/java/org/apache/accumulo/test/functional/AmpleConditionalWriterIT.java
Bulk load fate code was reading a tablets loaded flags, checking it was not in them, and then making a conditional mutation that required the set of bulk flags to to be the same.  Requiring the set to be the same caused unnecessary  collisions between bulk imports.  Modified the conditional check to require the loaded flags for the fate operation to be absent.
> narrows check of loaded files in conditional mutation

- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/PrepBulkImport.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkNewIT.java
For the case when a bulk import exceeds the configured files per tablet limit improves the error message to include range info and the relevant property name.
> improves bulk import error message

- test/src/main/java/org/apache/accumulo/test/functional/SimpleBalancerFairnessIT.java
Addresses one of the flaky tests from #5123
* uses waits for conditions we are checking for instead of sleeps and single asserts
> Improve SimpleBalancerFairnessIT

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPoolNames.java
- core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
Conditional mutations currently execute in the thrift thread pool which can grow unbounded in size.  Having an unbounded number of conditional mutations executing concurrently could degrade a tablet servers health in some cases.  This change adds threads pools for executing conditional updates.  This will help limit the CPU and memory used by executing conditional mutations.  Conditional mutations can also contain data as part of the mutation that needs to be checked, if this is large that could still cause memory issues.  This change more limits the memory used by reading current tablet data to check the condition.  Limiting the memory used by conditional mutations waiting to execute is something that would need to somehow be controlled by thrift.  So this change protects memory and CPU …
> Executes conditional mutations in a thread pool

- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
Was incorrectly calculating the number of TransactionRunners to execute.
`getQueue().size()` is the number of tasks that have been submitted to the pool that currently don't have a thread available to work on them. This should instead be the number of tasks that are currently running. Before this was submitting new TransactionRunners unnecessarily
Noticed when working on #5130
> Fix Fate pool watcher bug

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/navbar.js
The method being called here `updateDebugDropdownNotification()` was removed in #5118. There was a warning in the browser dev console saying `updateDebugDropdownNotification()` was not defined.
> remove call to method that does not exist in monitor

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
When creating the thread pool for metadata conditional update in the tablet server the config for user tables was used.
> fixes tserver conditional update thread pool config

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/bulkImport.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/compactions.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/ec.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/gc.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/manager.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/navbar.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/overview.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/scans.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/systemAlert.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/tservers.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/default.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/server.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/table.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/tables.ftl
The use of jquerys `$( document ).ready( handler )` is deprecated and [their docs](https://api.jquery.com/ready/) suggest a new syntax to "Specify a function to execute when the DOM is fully loaded." This PR converts our usages to that new syntax.
> Use new jquery api in monitor

- assemble/bin/accumulo-cluster
- assemble/bin/accumulo-service
- assemble/conf/accumulo-env.sh
- assemble/conf/accumulo.properties
- core/src/main/java/org/apache/accumulo/core/conf/cluster/ClusterConfigParser.java
This backports the improvements to the accumulo-cluster and accumulo-service scripts to 2.1 to improve script maintenance and functionality across the branches.
Notable differences with the main branch:
* This version includes deprecated commands that are replaced by newer versions: start-non-tservers, start-servers, stop-servers, start-tservers, and stop-tservers
* This vesion includes the ability to control starting a compaction-coordinator, which was removed in the main branch for 4.0
* This version does not allow specifying tserver groups (unsupported by its cluster.yaml version) and uses a hard-coded value of "default"
* As before these changes, this version checks for old deprecated config files present in conf/
* As before these changes, this version parses the cluster.yaml that …
> Backport the cluster scripts to 2.1

- assemble/bin/accumulo-cluster
Moves the "done" message up to the end of each tserver group operation instead of being at the end.
Changes `accumulo-cluster start` output to having separate lines for each tserver group instead of a continuous line for all groups.  
Old output:
```
$ ./bin/accumulo-cluster start
Executing start on tablet servers for group default ....Executing start on tablet servers for group special ....done
```
New output:
```
./bin/accumulo-cluster start
Executing start on tablet servers for group default ....done
Executing start on tablet servers for group special ....done
```
> Fixes accumulo-cluster message format for tserver operations

- core/src/main/java/org/apache/accumulo/core/util/compaction/RunningCompactionInfo.java
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/ec.js
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java
Converts the compaction duration from nanos to mills in RunningCompactionInfo.
This removes the need to handle the data conversion in the monitor and ec-admin utility.
Closes #5204
> Convert compaction duration to mills

- assemble/bin/accumulo-cluster
Switches the property override back to `compactor.group` so the compactors join the correct queue.
`compactor.queue` was replaced with `compactor.group` in 4.0
> Fix compactor.queue to compactor.group

- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ConditionalTabletMutatorImpl.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ConditionalTabletsMutatorImpl.java
- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/commit/CommitCompaction.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/availability/SetTabletAvailability.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/CleanUpBulkImport.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/LoadFiles.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/CompactionDriver.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/ReserveTablets.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/DeleteRows.java
- test/src/main/java/org/apache/accumulo/test/functional/AmpleConditionalWriterIT.java
Addresses #5202
Adds an overloaded `submit` method to accept a description for the conditional mutation. This description gets logged if the mutation is rejected.
Used this new overloaded submit method in AmpleConditionalWriterIT to make sure it works. I am not too sure where other good spots to use this are but will continue to look into it.
> Improve Ample logging for rejected conditional mutations

- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java
The metric prefix changed causing the test to fail
> Fix ExternalCompactionProgressIT metrics test

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Wrapped call to getTabletMemory().mutate() in try/finally so that a RuntimeException does not short circuit the code in the method that decrements the writes. Added logging in TabletClientHandler to note which client was causing the failure.
Closes #5208
> Better handling for runtime exception in Tablet.commit 

- core/src/main/java/org/apache/accumulo/core/conf/SiteConfiguration.java
- start/src/main/java/org/apache/accumulo/start/classloader/AccumuloClassLoader.java
Fixes error when using `include` or `includeOptional` property directives in accumulo.properties
```
Caused by: org.apache.commons.configuration2.ex.ConfigurationException: Load operation not properly initialized! Do not call read(InputStream) directly, but use a FileHandler to load a configuration.
at org.apache.commons.configuration2.PropertiesConfiguration.loadIncludeFile(PropertiesConfiguration.java:1395)
at org.apache.commons.configuration2.PropertiesConfiguration.propertyLoaded(PropertiesConfiguration.java:1479)
at org.apache.commons.configuration2.PropertiesConfigurationLayout.load(PropertiesConfigurationLayout.java:444)
at org.apache.commons.configuration2.PropertiesConfiguration.read(PropertiesConfiguration.java:1500)
at …
```
> Use a FileHandler when loading properties

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/file/blockfile/cache/impl/BlockCacheManagerFactory.java
- core/src/test/java/org/apache/accumulo/core/file/blockfile/cache/BlockCacheFactoryTest.java
- core/src/test/java/org/apache/accumulo/core/file/blockfile/cache/TestLruBlockCache.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/RFileTest.java
The block cache manager is not only used in the tserver, it's also used in the sserver and by a client that might be reading from an RFile.
Closes #4663
> Replaced tserv block cache mgr property with a more general one

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/UpdateSession.java
- test/src/main/java/org/apache/accumulo/test/CorruptMutationIT.java
Was looking into an issue were a mutation was corrupted on the network. This caused the mutation to be written to the write ahead log and then a failure occurred in the tablet server which left the tablet in an inconsistent state.  Modifed the tablet server code to deserialize mutations as early as possible (it used to deserialize after writing to the walog, now it does it before).
Wrote an IT to recreate this problem and found another bug.  Writing data to Accumulo does the following.
1. Make a startUpdate RPC to create an update session
2. Make one or more applyUpdates RPCs to add data to the session.  These RPCs are thrift oneway calls, so nothing is reported back.
3. Call closeUpdate on the session to see what happened with all of the applyUpdates RPCs done in step 2.
If an unexpected …
> Checks for corruption earlier and always report errors

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
> decrements total queued mutation size when update idles

- server/base/src/main/java/org/apache/accumulo/server/conf/util/ZooInfoViewer.java
- server/base/src/main/java/org/apache/accumulo/server/conf/util/ZooPropEditor.java
- server/base/src/test/java/org/apache/accumulo/server/conf/util/ZooInfoViewerTest.java
Before this change, the `accumulo.pool.scheduled.future.checker` thread would be created when all KeywordExecutable classes are loaded in.
https://github.com/apache/accumulo/blob/a320bbe87bf6c01031044c7681c05d89579809e2/start/src/main/java/org/apache/accumulo/start/Main.java#L231 
By moving the nullWatchers to the execute method, the threads are only created when the classes are executed.
> Only create Threadpools when calling ZooInfoViewer or ZooPropEditor

- core/src/main/java/org/apache/accumulo/core/classloader/ClassLoaderUtil.java
- server/base/src/main/java/org/apache/accumulo/server/util/PropUtil.java
- server/base/src/main/java/org/apache/accumulo/server/util/SystemPropUtil.java
- server/base/src/test/java/org/apache/accumulo/server/util/PropUtilTest.java
The root cause of the issue is that ClassLoaderUtil.initContextFactory was not being called which caused an NPE to be thrown which returned false from ClassLoaderUtil.isValidContext.
Closes #5198
> Fix issue with ZooPropEditor setting classloader context property

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/monitor/pom.xml
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/manager/ManagerResource.java
> Enable supression of dead servers in Monitor by resource group

- assemble/conf/accumulo-env.sh
- shell/src/main/java/org/apache/accumulo/shell/Shell.java
When the shell is being used with an execute command and pipe `./accumulo shell -e '<command>' | grep "<>"`,
jline does not write the output on stdout and instead writes it to stderr.
This causes frustration when attempting to script actions using the accumulo shell.
Without Property Set:
```
$ ./accumulo shell -e 'scan -t accumulo.root -np' | grep localhost 
2024-12-31T05:15:59,532 [shell.Shell] INFO : Loading configuration from /workspace/fluo-uno/install/accumulo-2.1.3/conf/accumulo-client.properties
!0;~ file:hdfs://localhost:8020/accumulo/tables/!0/table_info/0_1.rf []	0,0
!0;~ loc:10000501ae30004 []	localhost:9997
!0;~ srv:dir []	table_info
!0;~ srv:flush []	4
!0;~ srv:lock []	tservers/localhost:9997/zlock#d923681f-93ab-498f-b32e-0abf799b8354#0000000000$10000501ae30004
!0;~ srv:time …
```
> Adds property for jline to prefer using stdout vs stderr

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ZookeeperLockChecker.java
- core/src/main/java/org/apache/accumulo/core/lock/ServiceLockPaths.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/ZookeeperLockCheckerTest.java
- core/src/test/java/org/apache/accumulo/core/lock/ServiceLockPathsTest.java
- server/base/src/test/java/org/apache/accumulo/server/util/AdminTest.java
- server/base/src/test/java/org/apache/accumulo/server/util/ServiceStatusCmdTest.java
- test/src/main/java/org/apache/accumulo/test/fate/FateOpsCommandsIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ManagerAssignmentIT.java
ServiceLockPaths cannot use ClientContext because that can be closed, and ServiceLockPaths needs to be reused inside the tablet locator thread pool, which is a static singleton that can survive longer than the client context.
This removes context from ServiceLockPaths and causes ZookeeperLockChecker to provide it with a separate root path and ZooCache.
This fixes the ITs broken after the merge of #5192 in e745a5dcd4646059f71a026caa277651295f5df0
> Use ZooCache detached from Context for ServerPaths

- core/src/test/java/org/apache/accumulo/core/data/constraints/VisibilityConstraintTest.java
- core/src/test/java/org/apache/accumulo/core/file/streams/RateLimitedInputStreamTest.java
- core/src/test/java/org/apache/accumulo/core/file/streams/RateLimitedOutputStreamTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ActiveAssignmentRunnable.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/AssignmentWatcherTest.java
- shell/src/test/java/org/apache/accumulo/shell/format/DeleterFormatterTest.java
* Remove the use of mock objects created using EasyMock.niceMock to improve the rigor of our test coverage a little, and the reliability of those affected tests
Trivial changes in related non-test code:
* make use of return value from Objects.requireNonNull
* avoid passing redundant AccumuloConfiguration object when ServerContext suffices
> Remove niceMocks

- core/src/main/java/org/apache/accumulo/core/trace/TraceUtil.java
- test/src/main/java/org/apache/accumulo/test/SelfStoppingScanServer.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalDoNothingCompactor.java
- test/src/main/java/org/apache/accumulo/test/functional/MemoryConsumingCompactor.java
Update Proxy/reflection code to gather all the thrift interfaces from the proxied instances, so you don't need to declare them all explicitly on each subclass.
> Remove redundant interfaces for thrift services

- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooCache.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterControl.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
- server/base/src/main/java/org/apache/accumulo/server/util/ZooZap.java
Modified MAC so that it cleaned up lock paths
in ZooKeeper and ZooCache when stopping. Noticed
that in tests that restarted MAC the Manager
process would wait for the previous lock to be
removed on the session timeout. The lock paths
would also be cached in ZooCache and not updated
right away because the Watcher would not fire
when MAC was stopped, a ConnectionLoss error
would be returned when MAC started, and it would
take a while for ZooCache to fix itself.
> Made ITs that restart MAC faster

- shell/src/main/java/org/apache/accumulo/shell/commands/HelpCommand.java
Sets a default column size of 80 characters if the terminal width is set to 0. This supports running the help command in a dumb terminal while still throwing an IllegalArgumentException for terminal widths under 40 characters. 
This fixes the current `ShellServerIT.help` and `ShellServerIT.extensions` test failures.
> Sets default column size when terminal size is 0

- core/src/main/java/org/apache/accumulo/core/file/rfile/RFile.java
Rfile.closeLocalityGroupReaders() was suppressing IOExceptions. This method was called by Rfile.closeDeepCopies() which is called by FileManager.releaseReaders().  Suppressing the exception meant that releaseReaders() did not see the exception and would decided to return the rfile to the pool when it should not.
The only other code calling Rfile.closeLocalityGroupReaders() was Rfile.close(). Refactored the code so that Rfile.close() still suppressed the exception and Rfile.closeDeepCopies() does not suppress.  Tried to preserve the behavior that Rfile.close() closes as many of its underlying resource as possible even if some exceptions occur.
> Propagates errors in Rfile.closeDeepCopies

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloConfigImpl.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueue.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/queue/CompactionJobQueues.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/queue/SizeTrackingTreeMap.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueueTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/queue/CompactionJobQueuesTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/queue/SizeTrackingTreeMapTest.java
- test/src/main/java/org/apache/accumulo/test/compaction/CompactionPriorityQueueMetricsIT.java
Modified the compaction queue limit to use the data size of the compaction jobs instead of the number of compaction jobs for limiting the number of compaction jobs buffered.
fixes #5186
> Used data size instead of entry size of compaction queue

- minicluster/pom.xml
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
Use ZooReaderWriter to do ZK updates in MiniAccumuloClusterImpl instead of requiring zookeeper-jute on the classpath (also makes the code shorter and more readable)
> Remove zookeeper-jute from minicluster

- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
- test/src/main/java/org/apache/accumulo/test/fate/FastFate.java
- test/src/main/java/org/apache/accumulo/test/fate/FatePoolResizeIT.java
- test/src/main/java/org/apache/accumulo/test/fate/meta/MetaFatePoolResizeIT.java
- test/src/main/java/org/apache/accumulo/test/fate/user/UserFatePoolResizeIT.java
Adds some missing FATE functionality
- Previously, if a user configured fewer FATE threads to work on transactions (via MANAGER_FATE_THREADPOOL_SIZE property), the pool size would not actually be decreased. These changes safely stop excess workers in the case where the property value is decreased.
- Added test FatePoolResizeIT (tests both META and USER transactions: MetaFatePoolResizeIT and UserFatePoolResizeIT) to ensure the pool size is correctly increased and decreased with configuration changes.
- Fate.shutdown() was not waiting on termination of the fate pool watcher when needed. Added the missing wait.
Another potential solution to this problem is disallowing decreasing the pool size, but I'm not sure if that's the way we want to go about this.
Confirmation/changes to the thread …
> Adds some missing FATE functionality

- core/src/main/java/org/apache/accumulo/core/metrics/Metric.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/QueueMetrics.java
- test/src/main/java/org/apache/accumulo/test/compaction/CompactionPriorityQueueMetricsIT.java
- test/src/main/java/org/apache/accumulo/test/metrics/MetricsIT.java
Because of recent changes a compaction metric was always reporting the value of a configuration property.  Removed this mertic and also renamed and moved a variable from instance level to local level.
> removes compaction metrics that is no longer useful

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientInfo.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientInfoImpl.java
- minicluster/src/main/java/org/apache/accumulo/cluster/standalone/StandaloneAccumuloCluster.java
- server/base/src/main/java/org/apache/accumulo/server/ServerInfo.java
- server/base/src/test/java/org/apache/accumulo/server/MockServerContext.java
- server/base/src/test/java/org/apache/accumulo/server/rpc/TServerUtilsTest.java
- test/src/main/java/org/apache/accumulo/test/server/security/SystemCredentialsIT.java
These changes are small quality fixes to ensure that ClientContext.ensureOpen is used when it is needed, and not used when it isn't. This fixes an issue seen where the client RPC timeout value is being retrieved from a supplier in a thread pool when returning RPC transports after a client is closed. In these cases, ensureOpen does not need to be checked. However, there were a few context API methods where it was not checked but should have been.
Also, improved the close method to ensure close activities are only called at most once, and made private and renamed an internal method to get the client properties from the ClientInfo object, so it's more clear which properties the method is returning and isn't exposed for misuse.
> Improvements to ClientContext for ensureOpen

- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueue.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/queue/CompactionJobQueues.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/CompactionCoordinatorTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueueTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/queue/CompactionJobQueuesTest.java
Updates the manager to reset the max size on compaction queues when config changes.  In the case where the current data size of the queue exceeds the new configured size the lowest priority jobs are dropped until the size is acceptable.
> Resets compaction queue max size when config changes

- pom.xml
GitHub actions has been running out of memory with some PRs during SpotBugs execution and this will bump member to prevent that.
> Increase spotbugs heap to 1024m

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientInfo.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientInfoImpl.java
- server/base/src/main/java/org/apache/accumulo/server/ServerInfo.java
* Add support to ClientInfo (and implementations) for providing a chroot path to the ZooKeeper (ZooSession) supplier
* Fix typo in two ZooSession client names to lookup the instanceId or instanceName from the other (the client names were the reverse of the operation being performed, creating a little confusion in the logs)
> Allow providing a chroot to ZK suppliers

- test/src/main/java/org/apache/accumulo/test/functional/WatchTheWatchCountIT.java
WatchTheWatchCountIT has been failing in main (again). A recent change lowered the max watch count down to 200. Running this locally about 10 times, only one time was it lower than 200. Bumped the max to 300 to get this test passing.
> Bumped max watch count from 200 to 300

- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionFinalizer.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/DeadCompactionDetector.java
`AmpleImple.getExternalCompactionFinalStates()` creates a `Scanner` and returns a `Stream` off of that `Scanner`. This PR adds an `onClose()` to the stream that will close the `Scanner`.
I changed things so that the `Stream` returned by this method is explicitly closed in a try-with-resources block.
There were other spots that use this method but they were in the testing code so I left those alone. I'll probably clean those up too in 3.1 and main once this is merged up.
> Close scanner in AmpleImpl.getExternalCompactionFinalStates()

- core/src/main/java/org/apache/accumulo/core/client/rfile/FSConfArgs.java
- core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScannerBuilder.java
- core/src/main/java/org/apache/accumulo/core/client/rfile/RFileWriterBuilder.java
- core/src/test/java/org/apache/accumulo/core/client/rfile/RFileClientTest.java
Modified the rfile client code to get the filesystem based on the path being written or read.  This covers the case of having multiple filesystems defined in hadoop config.
> Gets the correct filesystem when writing an rfile

- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/DistributedReadWriteLock.java
- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/FateLock.java
- core/src/test/java/org/apache/accumulo/core/fate/zookeeper/DistributedReadWriteLockTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/Utils.java
Instead of passing around byte arrays for DistributedReadWriteLock and related classes we can use LockType and FateId to make the code easier to work with and to understand as those values are serialized as part of the lock. A new FateLockEntry type has been created which is passed around instead and that is serialized/deserialized into the correct byte array format when reading/writing to zookeeeper.
This closes #5264
Note: I didn't add much for new tests because all the existing Fate tests should provide coverage for the changes (at least i think so)
> Refactor Fate lock code to use concrete types

- core/src/main/java/org/apache/accumulo/core/metadata/TabletState.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletGoalState.java
Adds trace level logging of the tablet state and tablet goal state. This logging will help understand why the manager is making the decisions it does regarding a particular tablet.  For example if the manager is not assigning a tablet that one would expect to be assigned turning on this logging could help.  Because the manager uses an iterator to filter tablet metadata in the tablet server, may need to look in the log of manager and tablet servers serving root and metadata tables to see it.
Manually tested this by enabling the trace level logging and runnin some ITs.  Found a bug with calling TableMetadata.getExtent() in this testing and corrected that.
> adds trace logging of tablet state computations

- core/src/main/java/org/apache/accumulo/core/data/LoadPlan.java
- core/src/test/java/org/apache/accumulo/core/data/LoadPlanTest.java
The encoding in LoadPlan was using GSon default settings which encoded some HTML chars like `=` as unicode escape sequences.  This did not cause any problems because GSon would reverse this encoding.  However it was not documented in the javadoc for LoadPlan and it seems unnecessary.
Disabled the HTML escaping so the code aligns w/ the javadoc.  Also updated the unit test to produce `=` in the base64 and see how that behaves in the json.  This allows the test to better detect changes in the way the code persist data.
> Disables HTML escaping in LoadPlan json encoding.

- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionTestUtils.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_1_IT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_2_IT.java
In #5283 I made sure the Scanner that was used to construct a Stream returned by Amples `getExternalCompactionFinalStates()` got closed. I did not touch the test code when that PR was merged into 2.1. This PR improves the usages of that method in the test code by closing the Stream and therefore the resources used in that method. I added a helper method to get the count of these states to make some of the test code cleaner too.
> Improvements to ExternalCompaction ITs

- test/src/main/java/org/apache/accumulo/test/MaxWalReferencedIT.java
Fixes #5200 
Adds a a test to make sure that `tserver.wal.max.referenced` works.
> Add test for tserver.wal.max.referenced

- core/src/main/java/org/apache/accumulo/core/trace/TraceUtil.java
- core/src/main/java/org/apache/accumulo/core/util/ClassUtil.java
- server/base/src/main/java/org/apache/accumulo/server/rpc/HighlyAvailableServiceWrapper.java
- server/base/src/main/java/org/apache/accumulo/server/rpc/TCredentialsUpdatingWrapper.java
The issue fixed in #5260 was that a class that was implementing a Thrift interface had to declare it, even if it was declared in a parent class. #5260 fixed the logic in one place and then removed the interface declarations from the subclasses. It appears that there are other locations in the code where the same problem exists. This commit moves the fix to a utility class and updates the places where this was being done to use the utility method.
> Applied fix from #5260 in other locations

- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/LogSorter.java
The merge of #5193 from 2.1 to main reverted some changes in main to LogSorter causing RecoveryIT to fail.
> Fixed LogSorter from changes due to incorrect merge

- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletLocatorImpl.java
When many accumulo client threads all decided to invalidate some servers at the same time in the tablet location cache each threads would scan though all metadata looking for those servers.
This change adds servers to a set for deferred processing when invalidated.  This has two advantages.  First for multiple threads adding servers at around the same time it can lower the number of scans done over all the cached tablet locations.  Second the amount of work done to invalidate servers is lowered.  The code used to find cache entries for a server, add the extent for that cache entry to badExtents, and then later look for everything in badExtents and remove it.  This change removes all of that work and directly removes entries from the cache and avoids adding anything to badExtents.
> Defers server invalidation in tablet location cache

- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloConfigImpl.java
Was seeing slow ITs related to recent changes that cause more ZK clients to be created.  ZK client creation was slow.  The cause was ZOOKEEPER-3100 and MiniAccumulo setting 127.0.0.1 in ZK server config and using localhost for ZK in accumulo config. This caused the ZK server to listen on 127.0.0.1 and the ZK client to sometimes attempt to use the IPV6 addr for localhost which failed and retried possibly adding seconds to each ZK connection attempt.
This changes updates accumulo config created by mini accumulo to use 127.0.0.1 for zookeeper.
> uses consistent zk host addr in MAC

- server/base/src/main/java/org/apache/accumulo/server/metadata/iterators/TabletMetadataCheckIterator.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionReservationCheck.java
Only load required columns for check to avoid reading unnecessary data into memory
Closes #5254
> Filter columns in CompactionReservationCheck

- server/base/src/main/java/org/apache/accumulo/server/mem/LowMemoryDetector.java
- server/base/src/main/java/org/apache/accumulo/server/metrics/ProcessMetrics.java
- test/src/main/java/org/apache/accumulo/test/functional/MemoryStarvedScanIT.java
Minor fixes and better volatile variable handling in LowMemoryDetector
> Another attempt at fixing MemoryStarvedScanIT

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/Utils.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/clone/CloneTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/clone/CloneZookeeper.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/create/PopulateZookeeper.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/rename/RenameTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/ImportPopulateZookeeper.java
- test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java
When trying to create a table with the name `metadata` it failed because `accumulo.metadata` existed.  The code doing the check for existing tables was not properly checking namespaces.  Fixed the check and added some test for the same table name in different namespaces.
> fixes creating same table name in different namespaces

- .github/workflows/maven.yaml
Changed the distribution from adopt to temurin as recommended at https://github.com/actions/setup-java#supported-distributions because AdoptOpenJDK has moved to Eclipse Temurin and is not being updated anymore.
> Updated Java distribution for GitHub Actions builds

- core/src/main/java/org/apache/accumulo/core/data/Key.java
- core/src/main/java/org/apache/accumulo/core/data/KeyBuilder.java
- core/src/test/java/org/apache/accumulo/core/data/KeyTest.java
Key has methods to get data as ByteSequences but no methods to create keys using ByteSequence.  This leads to either using Text or ByteSequence plus byte[].  Text always does an intermediate copy and ByteSequence plus byte[] is cumbersome.  These new method make it easier to efficiently create a new Key from an existing Key w/ less code and less copying of data.
> Adds ByteSequence constructors to Key

- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadata.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadataCheck.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/TabletMetadataCheckTest.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/iterators/TabletMetadataCheckIterator.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionReservationCheck.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/CompactionReservationCheckTest.java
Adds filtering to TabletMetadataCheckIterator that will use matching families for the provided columns in order to reduce the amount of data that is fetched. A ResolvedColumns instance is returned by each TabletMetadataCheck instance that contains the set of columns and set of matching families to read.
CompactionReservationCheck caches the ResolvedColumns instance statically to avoid having to recreate the set of columns and familes for each scan.
This closes #5254
> Filter based on columns declared in TabletMetadataCheck

- core/src/main/java/org/apache/accumulo/core/clientImpl/ScannerIterator.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftScanner.java
When the thread running an accumulo scanner is interrupted it may cause the server the scanner was reading from to be cleared from the cache. This can be disruptive in the case where the server is fine. This change makes a narrow exception to clearing the server from the cache for the case where the scanner was closed and an interrupt was seen.  The reason this is so narrow is to avoid failing to invalidate the cache in the case where there is actually a problem with the server.
> avoid clearing server in cache when scanner closed and interrupted

- core/src/main/java/org/apache/accumulo/core/fate/AdminUtil.java
- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
- core/src/main/java/org/apache/accumulo/core/fate/FateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/user/FateMutator.java
- core/src/main/java/org/apache/accumulo/core/fate/user/FateMutatorImpl.java
- core/src/main/java/org/apache/accumulo/core/fate/user/UserFateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/user/schema/FateSchema.java
- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/MetaFateStore.java
- core/src/main/java/org/apache/accumulo/core/logging/FateLogger.java
- core/src/test/java/org/apache/accumulo/core/fate/TestStore.java
- server/base/src/main/java/org/apache/accumulo/server/util/fateCommand/FateSummaryReport.java
- server/base/src/main/java/org/apache/accumulo/server/util/fateCommand/FateTxnDetails.java
- server/base/src/test/java/org/apache/accumulo/server/util/fateCommand/SummaryReportTest.java
- server/base/src/test/java/org/apache/accumulo/server/util/fateCommand/TxnDetailsTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/metrics/fate/FateMetricValues.java
- test/src/main/java/org/apache/accumulo/test/fate/FateExecutionOrderIT.java
- test/src/main/java/org/apache/accumulo/test/fate/FateIT.java
- test/src/main/java/org/apache/accumulo/test/fate/FateOpsCommandsIT.java
- test/src/main/java/org/apache/accumulo/test/fate/FateStoreIT.java
- test/src/main/java/org/apache/accumulo/test/functional/FateConcurrencyIT.java
Replaced occurrences of TxName, txName, and similar references with fateOp.
Changes
Renamed `txName` → `fateOp` where applicable
Updated related method names
Fixes #5230
> Rename TxName to fateOp for clarity (#5230)

- core/src/main/java/org/apache/accumulo/core/metadata/schema/MetadataSchema.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadata.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMutatorBase.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java
- server/base/src/test/java/org/apache/accumulo/server/constraints/MetadataConstraintsTest.java
- test/src/main/java/org/apache/accumulo/test/CloneIT.java
A bug was introduced in #5335 to TabletsMetadata.fetch where the columns being passed as arguments to the function where not being used. This has the side effect of fetching all columns in the TabletMetadata which was causing some ITs to time out. The ITs in these cases were fetching and counting specific columns in the TabletMetadata.
This bug also highlighted another bug in CloneIT where an invalid directory was being inserted into the TabletMetadata which would then subsequently fail when fetched. The directory column name was being validated on most, but not all, places where it was being inserted into the TabletMetadata. I added validation to the ServerColumnFamily.DIRECTORY_COLUMN.put method and fixed CloneIT.
> Fixed bug in TabletsMetadata.fetch

- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java
- server/manager/src/test/java/org/apache/accumulo/manager/upgrade/Upgrader12to13Test.java
The Upgrader12to13.validateEmptyZKWorkerServerPaths method was checking for no children in the zookeeper paths for compactors, scan servers, tablet server, and dead tablet servers as an indication that no servers were current running. Prior to recent changes in 4.0, zookeeper paths were not cleaned up for server processes when those processes are stopped. Modified the logic in the method to remove any children under those paths that are empty. Started the Upgrader12to13 unit test.
Closes #5343
> Started upgrade test, fixed issue in upgradeZookeeper

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/LoadFiles.java
- test/src/main/resources/log4j2-test.properties
related to #5201 
Adds some extra trace statements to bulkv2 loadFiles to determine future improvements
> Added trace logging for determining tablet lookup

- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
Accumulo 4.0 has some logging of timing for Fate operations that has been very useful in finding performance problems.  This change brings that logging back to 2.1.
> Logs timing information for Fate

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/TraceRepo.java
Made three improvments to tracing of fate operations. Included the fate id in tracing of fate operations.  The tracing data for fate operations would include the class name twice, changed this to `<class name>::<method name>`.  Included the delay that isReady returns in the trace data.
> improves tracing of fate operations

- core/src/main/java/org/apache/accumulo/core/Constants.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/PreUpgradeValidation.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/UpgradeCoordinator.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/UpgradeProgress.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/UpgradeProgressTracker.java
- server/manager/src/test/java/org/apache/accumulo/manager/upgrade/AccumuloTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/upgrade/UpgradeProgressTest.java
- test/src/main/java/org/apache/accumulo/test/upgrade/UpgradeProgressTrackerIT.java
During an upgrade the UpgradeCoordinator will run Upgraders for each version between the current version of the stored data and the current version of the installed software. The UpgradeCoordinator runs all of the necessary Upgraders on ZooKeeper, then runs all of them on the root table, and then finally runs all of them on the metadata table. This means that when upgrading through multiple versions the version of the data stored in ZooKeeper could be multiple versions ahead of the root and metadata tables, until the Upgraders are run on those tables.
When a failure occurs in the Upgrade the system is left in a partially upgraded state. The user needs to find and fix any issues before trying to start the system again. When the Manager starts the next time it will attempt to do the upgrade …
> Track state of upgrade to eliminate re-running upgrade code

- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/UpgradeCoordinator.java
A minor bug introduced in #5357 where the UpgradeCoordinator was comparing the stored progress version against the wrong variable which ended up skipping the Upgraders altogether.
> Fixed bug in UpgradeCoordinator comparing against the same version

- test/src/main/resources/log4j2-test.properties
This change is already present in the main branch.  Pulling it back to 2.1 as its very useful for debugging some problems to know which thread logged a message.
> logs thread id for integration tests

- server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/CompactionExecutorsMetrics.java
CeMetrics.queued, CeMetrics.running, ExMetrics.queued, ExMetrics.running are only initialized if registry is not null, but have `set()` called on them without checking registry (or equivalently, queued/running). Now check if queued/running is null before calling `set()`.
Checked all fields in `CompactionExecutorsMetrics` to see if there were any other places a NPE might occur, those 4 fields were the only ones that seemed to have this issue.
closes #5356
> Tablet server compaction metrics NPE fix

- server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/CompactionExecutorsMetrics.java
This variable is accessed by multiple thread outside of sync block and is not final, so made if volatile to ensure changes are seen.
> Makes CompactionExecutorsMetrics.registry volatile

- core/src/main/java/org/apache/accumulo/core/file/blockfile/impl/CachableBlockFile.java
- pom.xml
Code to read an rfile data block would close in a finally block.  If close threw an IOException then any exception in the try block would be lost in the stack trace.  Changed the code to use try w/ resources which has much better exception handling for this case.
> uses try w/ resources to close rfile block

- server/base/src/main/java/org/apache/accumulo/server/AbstractServer.java
- server/base/src/main/java/org/apache/accumulo/server/AccumuloDataVersion.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- server/compaction-coordinator/src/test/java/org/apache/accumulo/coordinator/CompactionCoordinatorTest.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/UpgradeCoordinator.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
Prevent the CompactionCoordinator, GarbageCollector, and ScanServer from fully starting until the current version of software matches the version stored on disk. Backported AccumuloDataVersion.getCurrentVersion for this change.
Closes #5367
> Don't fully start some servers until upgrade is complete.

- core/src/main/java/org/apache/accumulo/core/spi/crypto/AESCryptoService.java
- core/src/test/java/org/apache/accumulo/core/crypto/CryptoTest.java
A single Cipher object was shared between multiple inputstreams when decrypting AES data. This caused decryption to fail when mutliple threads created input streams for decryption.  This could potentially cause failure for a single thread also if it interleaves reading from multiple streams that use the same Cipher.
Modified the code to create a Cipher per input stream.
> fixes AES decryption threading issue

- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
- core/src/main/java/org/apache/accumulo/core/fate/FateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/user/UserFateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/MetaFateStore.java
- core/src/main/java/org/apache/accumulo/core/logging/FateLogger.java
- core/src/test/java/org/apache/accumulo/core/fate/TestStore.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_1_IT.java
- test/src/main/java/org/apache/accumulo/test/fate/FateStoreIT.java
- test/src/main/java/org/apache/accumulo/test/fate/FateStoreUtil.java
This adds a new Seeder API that can be used to seed transactions with a FateKey. The purpose of this new API is to allow for eventual batching of multiple seeding attempts together into one conditional mutation to improve performance. This change just updates the api and all calls to the seeder to attempt seeding will be performed individually. A future update will support the new functionality of batching and commiting all the changes together when the Seeder is closed.
This change is for Part 1 of #5160
> Modify FateStore to introduce a Seeder API

- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
Noticed that one of the tests failed the assertion, causing the test to fail instead of retrying the wait loop.
> Test fix: Check compactions are system compactions in the wait condition

- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
Updated Manager to account for the status of an upgrate when starting processes. For example, the new fate table is created during the 4.0 upgrade, so we can't start Fate or anything that uses Fate (e.g. Splitter) until after the table has been created.
Closes #5368
> Modified Manager.run startup to account for upgrade stages

- server/base/src/main/java/org/apache/accumulo/server/compaction/CompactionInfo.java
- server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableUtils.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/MinorCompactor.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SlowIterator.java
Changed this from adding a test to adding a test and adding functionality.  Added the ability to interrupt compaction threads on tablet close.  Added an IT that covers the two ways compactions can be interrupted on compaction close.
> implements interuption of compactions and adds an IT to verify compaction cancels on tablet migration

- core/src/main/java/org/apache/accumulo/core/crypto/streams/BlockedOutputStream.java
- core/src/main/java/org/apache/accumulo/core/spi/crypto/AESCryptoService.java
- core/src/main/java/org/apache/accumulo/core/spi/crypto/CryptoService.java
- core/src/main/java/org/apache/accumulo/core/spi/crypto/FileEncrypter.java
- core/src/test/java/org/apache/accumulo/core/crypto/BlockedIOStreamTest.java
- core/src/test/java/org/apache/accumulo/core/crypto/CryptoTest.java
Modified AESCryptoService to detect creation of multiple encryptions streams at the same time. The implementation in AESCryptoService does not support this because it uses shared Cipher object and shrared intialization vectors.  The code that uses CryptoService does not seem to have a need for creating more that one encryption stream at a time. If the usage pattern of the code change, then the detection added in this commit should catch that.
fixes #5386
> prevents creating overlapping encryption streams

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPoolNames.java
- core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java
- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java
- server/gc/src/test/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogsTest.java
Uses the same property and technique used for deleting RFiles to delete wal and recovery files.
Closes #5397
> Make garbage collecting wal and recovery files faster

- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/UpgradeCoordinator.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/UpgradeProgressTracker.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java
- test/src/main/java/org/apache/accumulo/test/upgrade/UpgradeProgressTrackerIT.java
Updated the UpgradeCoordinator to fix what is essentially an off by one bug. The version of the instance and the key in the upgraders map did not match the way the code was processing the versions.
Updated the UpgradeProgressTracker with additional checks.
Updated Upgrader12to13 methods to be invoked during the appropriate phase and to be re-entrant.
> Fixed UpgradeCoordinator, UpgradeProgressTracker, and Upgrader12to13

- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionMetricsIT.java
This test fails periodically, adding debug to see which metric its missing.
> adds debug to ExternalCompactionMetricsIT

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
> Bumped general scheduled executor default thread size from 1 to 3.

- test/src/main/java/org/apache/accumulo/test/functional/MetadataIT.java
PR #5353 changed the default TabletMergeability setting for initial system tablets to be always for scanref, fate, and the default metadata tablet. The root tablet and tablets section metadata tablet are still set to "never" and the test needed to be updated to account for this.
This closes #5406
> Fix MetadataIT tablet mergeability check

- core/src/main/java/org/apache/accumulo/core/clientImpl/ConditionalWriterImpl.java
- core/src/main/java/org/apache/accumulo/core/fate/FateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooUtil.java
- core/src/main/java/org/apache/accumulo/core/lock/ServiceLock.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMutatorBase.java
- core/src/test/java/org/apache/accumulo/core/fate/zookeeper/LockIdTest.java
- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
- server/base/src/main/java/org/apache/accumulo/server/manager/LiveTServerSet.java
- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
- server/base/src/test/java/org/apache/accumulo/server/metadata/ConditionalTabletsMutatorImplTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
In order to make this change needed to analyze how the code uses LockId, based on this anylsis ended up making a few changes.
Some code was caching the serialized form of the lock id and keeping a string around.  Its better to keep the lock id type around instead of a string, so made lock id memoize serialization to support doing this.
The lock id constructor was removing extraneous slashes at the end of the lock path.  However it seemed this would never happen in the code. Removed this handling and instead added a check that paths do not end w/ a slash.  Also added some other validation in the constructor. Noticed this object is created alot in the manager and tablet server, to avoid the repeated validation made ServiceLock cache the LockId instead of always creating it.
fixes #5410
> removes root path from lock id serialization

- server/base/src/main/java/org/apache/accumulo/server/init/ZooKeeperInitializer.java
- server/base/src/main/java/org/apache/accumulo/server/tables/TableManager.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/namespace/create/PopulateZookeeperWithNamespace.java
Static methods are removed in favor of non-static ones, since these methods are only ever called with the ServerContext, which already has an instance of the TableManager object. This allows removing an overloaded prepareNewTableState method, since the extra parameters on the overloaded method are always provided by methods on the ServerContext anyway.
Additionally, this change removes the static set of registered ZooCache observers and table state cache, since the lifetime of ZooCache is already bound to the lifetime of the ServerContext, and these static objects should not exist longer than the TableManager instance attached to the same ServerContext.
This fixes a potential bug with the ZooCache observers registered statically never firing again if the ServerContext is closed, even if …
> Remove static methods and fields from TableManager

- core/src/main/java/org/apache/accumulo/core/spi/balancer/HostRegexTableLoadBalancer.java
This line is constantly generated in the `manager.out` log file if the HostRegexTableLoadBalancer is used.
Removed the word `hrtlb` as the logger name will be included in the log message layout.
> Switch to using logger for conf build message

- core/src/main/java/org/apache/accumulo/core/clientImpl/InstanceOperationsImpl.java
ServiceLockData.getAddressString returns null if the ThriftService parameter is not found. The code was not protecting against this condition, and it started occurring with the changes in Manager is fully up, but the lock exists.
> Protected against NPE in InstanceOperationsImpl.getServers

- core/src/main/java/org/apache/accumulo/core/spi/balancer/GroupBalancer.java
Code in GroupBalancer was calling
`HashBasedTable.columnKeySet().removeAll(aList)`.  The Guava HashBasedTable code would iterator over all of its rows and columns and then call contains on the list passed in by GroupBalancer. So this code
was doing `ROWS*COLS*LIST_SIZE` operations.   Changed the list to a
hashset in this PR so now it only does `ROW*COLS` operations.
> Fixes performance bug in GroupBalancer

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/thrift-gen-java/org/apache/accumulo/core/tabletserver/thrift/TabletClientService.java
- core/src/main/thrift/tabletserver.thrift
- server/base/src/main/java/org/apache/accumulo/server/rpc/CustomNonBlockingServer.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/LoadFiles.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkNewIT.java
- test/src/main/java/org/apache/accumulo/test/performance/NullTserver.java
- test/src/main/resources/log4j2-test.properties
While profiling bulk load v2 noticed that the manager would send a message to a tablet containing a lot of tablets to load.  The tablet server would process each tablet one at time and do a metadata write for it.  This caused a lot of serial metadata writes per tablet server which caused this part of bulk import to take longer.
Attempted to parallelize these metadata writes by changing the manager to send a RPC per tablet.  The hope was that the tablet server would process each RPC request in a separate thread and this would avoid the serial metadata writes.
However this is not currently working and I am not sure why.  The manager is getting a thrift client and then sending a lot of one way RPCs to load tablets.  These one way messages all appear to be being processed by a single thread …
> Attempted to parallelize bulk import loading

- core/src/main/java/org/apache/accumulo/core/util/PeekingIterator.java
- core/src/test/java/org/apache/accumulo/core/util/PeekingIteratorTest.java
PeekingIterator was not handling null properly and was not following the iterator contract and throwing NoSuchElementException when it should. The null bug was if the source iterator returned null for next() this would cause peeking iterator to falsely claim there was no next.  When the iterator did not have a next it would return null for next() instead of throwing an exception.
Fixed both bugs and added unit test.  Looked at the test coverage of the class and added a few other test that cover more then these bugs to get 100% coverage.
> fixes bugs in peeking iterator

- core/src/main/java/org/apache/accumulo/core/util/PeekingIterator.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkNewMetadataSkipIT.java
Adds tablet gaps of size 1,2,3,...,9 tablets to the bulk import load plan in the skip test. The goal of this is to attempt to cover different edge case w/ the bulk import skip property.  Like when the skip property is set to 4 the load plan will have gaps of 3,4,5 tablets that is has to deal with.
> Add more test cases to bulk skip test

- assemble/bin/accumulo-cluster
The parse_config function was dynamically creating variables that were scoped to the function. When the code attempted to read these variables in the execute_command function it did not find them. This caused the script to only start one compactor per host even if multiple were configured. Added -g to declare builtin to make the variables global.
> fixes accumulo-cluster bug with starting multiple compactors

- server/base/src/main/java/org/apache/accumulo/server/util/UpgradeUtil.java
- test/src/main/java/org/apache/accumulo/test/upgrade/UpgradeUtilIT.java
I thought I saw an issue with #5438 post-commit which was likely a copy-paste error where the lookup for fate transactions was missing the zookeeper root path. Created an IT to test it and found an issue with the Opts too.
> Created UpgradeUtilIT, fixed issues in UpgradeUtil

- shell/src/main/java/org/apache/accumulo/shell/commands/MergeCommand.java
Prior to #5450 the all option in the merge command used an empty string for the short option. In 5450 we changed MergeCommand to use the Option.Builder, which allows specifying a long option only, but
we didn't use the long option when getting the
option value which causes a ShellServerIT failure.
> Fixed MergeCommand to use longOpt for all option

- assemble/conf/log4j2-service.properties
- assemble/conf/log4j2.properties
- core/src/test/resources/log4j2-test.properties
- hadoop-mapreduce/src/test/resources/log4j2-test.properties
- iterator-test-harness/src/test/resources/log4j2-test.properties
- minicluster/src/test/resources/log4j2-test.properties
- server/base/src/test/resources/log4j2-test.properties
- server/gc/src/test/resources/log4j2-test.properties
- server/manager/src/test/resources/log4j2-test.properties
- server/monitor/src/test/resources/log4j2-test.properties
- server/tserver/src/test/resources/log4j2-test.properties
- shell/src/test/resources/log4j2-test.properties
- start/src/test/resources/log4j2-test.properties
- test/src/main/resources/log4j2-test.properties
After bumping the log4j2 dependency to version 2.24.3 we started noticing extra logging output during the build. This issue has been reported at https://github.com/apache/logging-log4j2/issues/3100 and is due to the change to the AbstractConfiguration class in https://github.com/apache/logging-log4j2/pull/3043. As described in log4j2 issue #3100 and at
https://logging.apache.org/log4j/2.x/manual/status-logger.html the status configuration element is now deprecated and we are advised to use a system property instead.
Closes #5453
> Changed log4j2 statusLogger level from info to warn

- core/src/main/java/org/apache/accumulo/core/fate/AbstractFateStore.java
AbstractFateStore's `deferred` collection was being iterated over without locking
Noticed when working on https://github.com/apache/accumulo/issues/5427
> Fixes unsafe iteration over a collection

- core/src/main/java/org/apache/accumulo/core/data/LoadPlan.java
- core/src/test/java/org/apache/accumulo/core/data/LoadPlanTest.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkNewIT.java
Converting bulk load plan json to a LoadPlan was not very strict and for cases that it did fail it threw many different runtime exceptions.  Made validation of the json more strict and made the code always throw the same exception type when json is not valid. Added unit test for many different cases of illegal input.
> improved validation of load plan json

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
Increased thrift server thread minimum property values for CompactionCoordinator and ScanServer to 20 to match the minimums for other server processes. Increased minimum to 4 for the Compactor process.
Closes #5459
> Increased thrift server thread mininum property values

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/LoadFiles.java
The stats log message is confusing as the stats are not for the entire bulk import process, but just this specific fate step.
Removed incorrect wording for messages related to bulk import.
Removed duplicate words due to logger class name.
Added Fate TxID to log message for recreating the TabletMetadata
> Cleanup log messages in bulkv2 LoadFiles

- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionMetricsIT.java
ExternalCompactionMetricsIT was looking for some metrics to be greater than zero when its possible it may never see that.  Relaxed the test to look for >=0 instead of >0 for these metrics because once the compactors are started the queues are emptied and after that the values are always zero.  Earlier in the test there is a place where it seems like the metrics could reliably be seen w/ a value >0, so added some checks there.  Earlier in the test compactors are not started and the compaction queue should have stuff in it causing >0 metrics.
Also added some more debug logging in case the test ever gets stuck in the first loop.  The debug logging in the second loop was useful in tracking this problem down.
> fixes intermittent failure in ExternalCompactionMetricsIT

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java
- server/base/src/main/java/org/apache/accumulo/server/fs/AccumuloFileType.java
- server/base/src/main/java/org/apache/accumulo/server/fs/FileTypePrefix.java
- server/base/src/test/java/org/apache/accumulo/server/fs/FileTypePrefixTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/PrepBulkImport.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/MapImportFileNames.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/MinorCompactionTask.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
In #3079 we modified the FileCompactor to call FSDataInputStream.setDropBehind on compaction input files. This could cause an issue when certain types of files are used for compaction input. Created a property to allow the user to specify which file types should be excluded from this behavior.
> Added property for setting setDropBehind on compaction input streams

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/LoadFiles.java
Only a subset of tablet added for bulk load were logged.  Copied an existing log statement to another place where tablets were added.
> added missing log message to bulk load code

- server/base/src/main/java/org/apache/accumulo/server/security/handler/ZKAuthorizor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ThriftScanClientHandler.java
This change removes the logging of a stack trace with an unhelpful message that was done only for batch scans and replaces it with a log message that notes the specific Authorization that the user is trying to use that they don't have. This logging is only done on the server side, the client receives a BAD_AUTHORIZATIONS error.
> Log user attempting to use Authorization they don't have on server

- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java
The TabletServerBatchWriter uses a ScheduledExecutorThreadPool for dealing with failed mutations. The TabletServerBatchWriter code was calling ThreadPools.createGeneralScheduledExecutorService which creates the ThreadPoolExecutor with metrics enabled. If more than one TabletServerBatchWriter is created, then debug messages start showing up in the logs saying that the associated Gauge's have already been registered and will be ignored. This change calls the same underlying code, but disables metrics for the thread pool
> Disabled metrics for ThreadPool used for resending failed mutations

- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/util/Validators.java
- server/manager/src/main/java/org/apache/accumulo/manager/FateServiceHandler.java
noticed when working on https://github.com/apache/accumulo/issues/5427
> prevent offline all system tables

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/LoadFiles.java
Skips the sleep calculation when bulkv2 returns 1 or 0 as success cases. 
Also removes an unnecessary max comparison as `sleepTime` will always be less than or equal to `locationLess`
> Reduce sleep time for finished bulkv2 jobs

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/LoadFiles.java
- server/manager/src/test/java/org/apache/accumulo/manager/tableOps/bulkVer2/LoadFilesTest.java
Prior to this change bulkv2 code would serially scan the metadata table looking for tablets that need to bulk load and after finding work would make rpcs to tablet servers to load the files. After this change, bulkv2 will scan metadata and make RPCs to tablets servers in parallel.  The foreground thread will scan the metadata table, find a batch of RPC work, push that batch to a background thread, and then continue scanning building up a new batch.
> parallelizes metadata scan and rpcs in bulkv2

- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadata.java
- test/src/main/java/org/apache/accumulo/test/functional/ManagerAssignmentIT.java
- test/src/main/java/org/apache/accumulo/test/functional/TabletAvailabilityIT.java
Modified TabletMetadata.getTabletAvailability to return HOSTED for tables in the system namespace. Added some more tests.
> Modified TabletMetadata to return HOSTED for all system tables

- server/base/src/main/java/org/apache/accumulo/server/client/ClientServiceHandler.java
- server/base/src/main/java/org/apache/accumulo/server/security/AuditedSecurityOperation.java
- server/base/src/main/java/org/apache/accumulo/server/security/SecurityOperation.java
- server/base/src/main/java/org/apache/accumulo/server/security/handler/ZKAuthorizor.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/replication/ManagerReplicationCoordinator.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/create/SetupPermissions.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/namespace/create/SetupNamespacePermissions.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/ImportSetupPermissions.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ThriftScanClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TservConstraintEnv.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/replication/ReplicationServicerHandler.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/TservConstraintEnvTest.java
* Revert the new log message added to the ZKAuthorizor in 3825d582e7ddecb2d3661f96a707c13120bec609 for #5480 because the information is already available to the users by another means, and it's not worth the risk of bad user requests spamming the server logs
* Remove a similar extraneous exception and try-catch block for getActiveScans method that was removed in #5480
* Improve exception handling of TabletClientHandler.checkPermission by separating out the nested try-throw-catch of ThriftSecurityException into separate steps, so that the correct messages can be logged when the exception occurs due to permission being denied, rather than due to an unauthenticatable user (previously, the log message would always say it was from an unauthenticatable user, which is not true); this also …
> Revert new log message from #5480

- server/base/src/main/java/org/apache/accumulo/server/util/TableDiskUsage.java
- server/base/src/test/java/org/apache/accumulo/server/util/TableDiskUsageTest.java
Code did not consider ROOT table, and was always returning 0 for the disk usage as it would scan the ROOT table if the input was the METADATA table and would scan the METADATA table otherwise. Should have been scanning ZK if the input was ROOT. Changed to use Ample instead, which handles this issue nicely.
Discovered when working on #5474
> Fixes bug with getting disk usage of the ROOT table

- core/src/main/java/org/apache/accumulo/core/spi/balancer/HostRegexTableLoadBalancer.java
- core/src/test/java/org/apache/accumulo/core/spi/balancer/HostRegexTableLoadBalancerTest.java
The HostRegexTableLoadBalancer creates a default pool of tablet servers
in which to assign and balance tablets for tables that do not have a regular
expression defined. Users can define a regex for the default pool and the
tablet servers matching the regex will be added to the default pool along
with all of the servers that do not match one of the defined regular expressions.
Added a test for this case.
Closes #5489
> Created HostRegexTableLoadBalancer test for defining default pool

- server/manager/src/main/java/org/apache/accumulo/manager/FateServiceHandler.java
Prevents `tableOperations().deleteRows` of system tables in 4.0.
2.1 system tables:
- root <-- `cannot` delete rows
- metadata <-- `cannot` delete rows
- replication <-- `can` deleteRows
4.0 system tables:
- root <-- before: `cannot` delete rows, after: same
- metadata <-- before: `cannot` delete rows, after: same
- scan_ref <-- before: `can` delete rows, after: `cannot` delete rows
- fate <-- before: `can` delete rows, after: `cannot` delete rows
I did not target 2.1 because I was unsure if we want `deleteRows` for the replication table (seems like that was the intent, but table expectations changed in 4.0).
Created from discussion: https://github.com/apache/accumulo/pull/5474#discussion_r2042456618
> prevent deleteRows of system tables

- server/tserver/src/main/java/org/apache/accumulo/tserver/log/LogSorter.java
The old code collected mutations by creating a new list, copying existing and new mutations into it, and putting the list into a map. The new code creates a single list, adds all of the mutations to that list, and puts the list in the map.
Closes #5496
> Changed how mutations are collected in LogSorter.writeBuffer

- server/tserver/src/main/java/org/apache/accumulo/tserver/logger/LogFileKey.java
There are two trace statements that use Arrays.toString() as an argument. The methods where these log statements are found are used frequently in log recovery and the call to Arrays.toString may be unnecessary if trace logging is disabled.
> Added log.isTraceEnabled to LogFileKey

- assemble/bin/accumulo-service
Moves the sourcing of accumulo-env.sh to after all of the variables are defined for accumulo-service.
This allows for better handling of specific processes and actions in accumulo-env.sh
> Create all vars before sourcing accumulo-env.sh

- core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java
- core/src/main/java/org/apache/accumulo/core/iteratorsImpl/ClientIteratorEnvironment.java
> Removed table name and id from RFileScanner.

- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
- server/base/src/test/java/org/apache/accumulo/server/constraints/MetadataConstraintsTest.java
Adds a metadata constraint that prevents setting tablet availability on system tables.
closes #5507
> Adds a metadata constraint that prevents setting tablet availability on system tables

- .github/workflows/maven-full-its.yaml
- .github/workflows/maven-on-demand.yaml
- .github/workflows/maven.yaml
- README.md
- pom.xml
Bumps the parent pom version from 31 to 34 and adds
the apache.snapshots property that was included in
https://github.com/apache/maven-apache-parent/pull/183
to enable pulling of snapshots from the apache snapshot
repository during the build.
> Bump Apache Parent POM from version 31 to 34

- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
- server/base/src/test/java/org/apache/accumulo/server/constraints/MetadataConstraintsTest.java
reverts a breaking change which prevented setting tablet availability on system tables with a metadata constraint. This broke splits which needs to set the availability of new tablets.
Did not use `git revert` as keeping most of the new test added in this commit is fine
> Revert changes from #5514 that added new metadata constraint

- server/monitor/src/test/java/org/apache/accumulo/monitor/it/WebViewsIT.java
If not configure, the WebViewsIT parent class will always use port 9998. This could conflict with other running tests. Setting the property to zero enables the port selected to be a random free port.
> Configure WebViewsIT to use a random free port.

- test/src/main/java/org/apache/accumulo/test/CreateTableIT.java
This test times out pretty consistently when resource constrained. The following improvement was made to speed the test up:
* use `Arrays.stream(tableNames).parallel().forEach()` instead of for loop to parallelize the test
Other improvements that don't necessarily improve runtime:
* use `Timer` objects instead of System.millis for timekeeping
* use `Logger` instead of System.out
I assume this test was not created explicitly to run serially. When run locally this speeds runtime up from ~1 min to ~15 seconds.
> Parallelize CreateTableIT.testCreateLotsOfTables() to speed it up

- test/src/main/java/org/apache/accumulo/test/functional/BloomFilterIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ConcurrencyIT.java
- test/src/main/java/org/apache/accumulo/test/functional/MergeTabletsBaseIT.java
* Use NewTableConfiguration in two test cases instead of setProperty() calls after the table was already created
* removed  a duplicate call to set TABLE_MAJC_RATIO in MergeTabletsBaseIT.noChopMergeDeleteAcrossTablets()
> Trivial - improve table property setting in tests

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/ExternalCompactionFinalState.java
- core/src/main/java/org/apache/accumulo/core/util/threads/Threads.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionFinalizer.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/SharedBatchWriter.java
- test/src/main/java/org/apache/accumulo/test/compaction/TestCompactionCoordinatorForOfflineTable.java
The compaction coordinator was creating a batch writer per a completed external compaction.  The batch writer was used to write a single small mutation.  This caused a lot of thread creation and RPCs in the coordinator.  Changed the coordinator to use a single batch writer for these mutations.  Also update some logging in the coordinator to lower levels to trace and add some timing information.
> Avoids creating a batch writer per completed ext compaction

- core/src/main/java/org/apache/accumulo/core/util/compaction/RunningCompactionInfo.java
The monitor was logging a lot per external compaction.  Lowered the log levels to trace.
> lower level of per compaction logging in monitor

- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction4_IT.java
This IT would take about 7 minutes to run since it would produce three failed compactions and then complete on the fourth run.
Lowered the flush after rows value to reduce the number of files in the compaction jobs from 1000 to 50. 
This drops the test runtime to about a minute.
> Shorten ExternalCompaction4_IT test runtime

- core/src/main/java/org/apache/accumulo/core/metadata/schema/ExternalCompactionId.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionFinalizer.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/SharedBatchWriter.java
Parition the work of updating the metadata table across multiple BatchWriters. The incoming call will add the Mutation to a SharedBatchWriter instance that maps to the first character of the ECID UUID and wait for the mutation to be written.
> Create 16 SharedBatchWriters instead of 1 in CompactionFinalizer

- assemble/bin/accumulo-cluster
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
- server/base/src/main/java/org/apache/accumulo/server/util/UpgradeUtil.java
- server/base/src/main/java/org/apache/accumulo/server/util/ZooZap.java
As the cluster.yaml file is changed it can leave extra server process around. The accumulo-cluster script currently does not have a way to look for extra servers processes, it only operates on what is specified in the cluster.yaml file.  This WIP commit is initial work to make the accumulo-cluster script look for server processes in zookeeper that are not specified by the cluster.yaml file.  For example if host1 had 5 compactor processes for group G1 in zookeeper and cluster.yaml only specified 2, then there are 3 extra servers on host1.  Another example would be if some hosts were completely removed from cluster.yaml but still had servers in zookeeper.  The desired count for these host would be zero and the actual counts would greater than zero.
The goal would be to add commands like the …
> adds prune command to accumulo-cluster

- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
After these changes, under normal conditions, there will only be two debug messages per compaction in the coordinator.  One message when a compactor starts a compaction and one when it finishes.
> makes coordinator logs less chatty

- core/src/main/java/org/apache/accumulo/core/spi/compaction/CompactionPlanner.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
- core/src/test/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlannerTest.java
- core/src/test/java/org/apache/accumulo/core/util/NumUtilTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionService.java
For the case when a tablet has more than tablet.file.max files and a compaction can not be planned, log more information about what went into the planning process.
> Log more information about why compaction can not be planned

- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- server/manager/src/main/java/org/apache/accumulo/manager/FateServiceHandler.java
- Added early `return true` for all system tables for `TableOperations.exists()`
- Move built in table check for `TableOperations.setTabletAvailability()` to be handled on server side instead of client side. Result is RPC now occurs for a built in table, and exception for calling `setTabletAvailability` on a built in table is changed from `IllegalArgumentException` to `AccumuloException`. All the other `TableOperations` that can't be called on a system table result in an `AccumuloException` if they are called on a system table, so this change keeps consistency with the other `TableOperations`
- This commit additionally made it so that, for all `TableOperations`, the only validation done on the client side for a table is checking whether the argument is formatted correctly (via …
> Minor TableOperations changes

- server/base/src/main/java/org/apache/accumulo/server/conf/ServerConfigurationFactory.java
Noticed that site, namespaces, and table configuration were being validated in servers the first time used.  System configuration did not seem the be validated though.  Added validation of system config.  Have not test this yet.
> validate system config on server startup

- core/src/main/java/org/apache/accumulo/core/classloader/DefaultContextClassLoaderFactory.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java
- core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java
- server/base/src/main/java/org/apache/accumulo/server/metrics/MetricsInfoImpl.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- server/compaction-coordinator/src/test/java/org/apache/accumulo/coordinator/CompactionCoordinatorTest.java
- test/src/main/java/org/apache/accumulo/test/compaction/TestCompactionCoordinatorForOfflineTable.java
This change includes the following code modifications:
1. Modified code to use existing shared general
scheduled thread pool from the context.
2. Modified the BatchWriter to not use the general
scheduled thread pool. Reusing the thread pool
causes log messages about the same Meter being
registered.
3. Modified ThreadPools to not register the
ExecutorServiceMetrics with the MeterRegistry
until after the MeterRegistryFilter has been set.
A stack trace was being logged about this.
> Micrometer thread pool fixes

- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloConfigImpl.java
- pom.xml
- test/pom.xml
- test/src/main/java/org/apache/accumulo/harness/MiniClusterConfigurationCallback.java
- test/src/main/java/org/apache/accumulo/harness/SharedMiniClusterBase.java
- test/src/main/java/org/apache/accumulo/suites/SimpleSharedMacTestSuite.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_1_IT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_3_IT.java
- test/src/main/java/org/apache/accumulo/test/compaction/FlakyExternalCompaction2IT.java
- test/src/main/java/org/apache/accumulo/test/functional/ManagerAssignmentIT.java
- test/src/main/java/org/apache/accumulo/test/functional/OnDemandTabletUnloadingIT.java
Brief background: #5536 added a suite to run many of the SharedMiniClusterBase ITs against a single, shared cluster.
The test suite currently includes the ITs which do not set a custom config prior to start up (i.e., those that call `SharedMiniClusterBase.startMiniCluster()`). This PR was originally going to add the shared mini ITs which set a custom config to the new test suite (i.e., those that call `SharedMiniClusterBase.startMiniClusterWithConfig()`). However, almost all of the tests which start with a config (except for ~5) change something about server configuration which is needed *before* starting the servers (e.g., setting the number of servers, setting max memory, changing the class used for the server, etc.). I could not come up with a way to include these in the suite without …
> Shared mini test suite minor follow on

- test/src/main/java/org/apache/accumulo/test/RootRecoveryIT.java
- test/src/main/java/org/apache/accumulo/test/upgrade/ScanServerUpgrade11to12TestIT.java
Created IT that exhibits an issue introduced with #5416 that moved migrations from an in-memory object to a entries in the root and metadata table. Deleted ScanServerUpgrade11to12TestIT.testScanRefTableCreation.
Closes  #5566 #5577
> Added RootRecoveryIT that exhibits bug in root table assignment

- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java
- test/src/main/java/org/apache/accumulo/test/BrokenBalancerIT.java
The change in #5530 added code to clear the
property cache in initializeBalancer because
the property change was not immediately seen.
BrokenBalancerIT was changing the property
then checking the balance to see if the new
balancer had taken effect.
This commit changes BrokenBalancerIT to give
it more time in the test thread for the
property change to take effect in the Manager
and changes how the Manager responds to system
property changes so that the property cache
invalidation can be removed.
Related to #5530
> Fixed issue with balancer property updates

- core/src/main/java/org/apache/accumulo/core/client/admin/compaction/CompressionConfigurer.java
CompressionConfigurer.override() would throw an NPE if its options were set to null.  Changed CompressionConfigurer.init() to disallow null options to provide a better error message.
> Disallow null options in CompressionConfigurer

- core/src/main/java/org/apache/accumulo/core/file/BloomFilterLayer.java
Fixes https://github.com/apache/accumulo/issues/5517
Using the same setup as in the linked issue I confirmed that this resolves the problem. But I'm hoping you have some context as to why an UnsupportedOperationException is thrown here, possibly I'm missing something.
> Implement estimate overlapping entries for BloomFilterLayer

- assemble/conf/accumulo-env.sh
- assemble/conf/log4j2-service.properties
- assemble/conf/log4j2.properties
- core/src/test/resources/log4j2-test.properties
- hadoop-mapreduce/src/test/resources/log4j2-test.properties
- iterator-test-harness/src/test/resources/log4j2-test.properties
- minicluster/src/test/resources/log4j2-test.properties
- server/base/src/test/resources/log4j2-test.properties
- server/compaction-coordinator/src/test/resources/log4j2-test.properties
- server/compactor/src/test/resources/log4j2-test.properties
- server/gc/src/test/resources/log4j2-test.properties
- server/manager/src/test/resources/log4j2-test.properties
- server/monitor/src/test/resources/log4j2-test.properties
- server/tserver/src/test/resources/log4j2-test.properties
- shell/src/test/resources/log4j2-test.properties
- start/src/test/resources/log4j2-test.properties
- test/src/main/resources/log4j2-test.properties
The log4j2 status property was deprecated from the properties file in log4j2 version 2.24.0 and
replaced by a System property. This change removes property from all log4j2 properties files and adds the system property with default value to accumulo-env.sh
Closes #5482
> Replace status logger property with system property

- test/src/main/java/org/apache/accumulo/test/ScanServer_NoServersIT.java
Two test in ScanServer_NoServersIT expected scans to fallback to tablet servers when no scan servers were present.  However the configuration was not correct.  Modified the test to use correct config to cause expected behavior.
> fixes ScanServer_NoServersIT to fallback to tablet servers

- test/src/main/java/org/apache/accumulo/test/ChaoticLoadBalancer.java
- test/src/test/java/org/apache/accumulo/test/ChaoticLoadBalancerTest.java
When assigning the root tablet after other tablets were assigned, the getAssignment function in ChaoticLoadBalancer would never return an assignment. This would cause the test to hang until it timed out.  Not sure what the intention of the code was, but made it do something different that would always eventually yield an assignment.
> fixes chaotic balancer IT

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/DeleteRows.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/split/UpdateTablets.java
- server/manager/src/test/java/org/apache/accumulo/manager/tableOps/split/UpdateTabletsTest.java
The delete rows table operation was clipping a file to a row range like (f,f] and adding this to tablet with a row range of (f,g].  The files row range did not overlap the tablets row range causing reads of the tablet to fail with the changes in #5340.  This was causing DeleteRowsIT to fail, modified the code to avoid adding the non overlapping row range and now DeleteRowsIT passes.
Made a lot of logging changes while tracking this down, kept those in this commit.
> fixes incorrect file range clipping in deleterows

- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java
Each batch writer created was creating a thread pool intrumented with metrics.  This would cause Meters to continually be added to the global registry which could eventually cause memory problems.  Disabled metrics instrumentation on these thread pools.
> avoid creating thread pool metrics per batch writer

- server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletManagementIterator.java
The DoNothingBalancer was added in 2.1 as a fallback when balancer creation fails.  In main there is a new place that creates balancers that was not changed when merging the fix forward from 2.1.  Made this new place fall back.  Found this because BrokenBalancerIt was failing, after this change it passes.
> Adds overlooked DoNothingBalancer fallback

- core/src/main/java/org/apache/accumulo/core/classloader/DefaultContextClassLoaderFactory.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java
- server/base/src/main/java/org/apache/accumulo/server/metrics/MetricsInfoImpl.java
Metrics were being registered and emittied for thread pools regardless of the metrics property setting. Added a mechanism to disable metrics collection for thread pools when the property is false.
> Disable metrics for thread pools when metrics disabled

- core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java
This change just clears the list of the executor services that were created before the MeterRegistry, after they are finally added to the MeterRegistry.
> Clear list of early executor services after binding to registry

- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
When the compaction coordinator requested a connection to a tserver from LiveTserverSet it could return null. If this happened an NPE would be thrown.  Modified the coordinator to handle null for these cases.
> fixes NPE in coordinator

- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
- core/src/test/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlannerTest.java
When a tablet has too many files and its not compacting with the configured compaction ratio the planner would search for the highest ratio that would cause a compaction.  Encountered a problem with this search were two constraints in the code would cause nothing to be found. One constraint was a check to only accept compactions that satisfied `filesToCompact.size() < goalCompactionSize`.  The other constraint was that `DefaultCompactionPlanner.findDataFilesToCompact()` would find the largest set of small files to compact. Putting these two together in some cases `findDataFilesToCompact()` would keep finding a set of files smaller than `goalCompactionSize` and log a warning that it could not find anything.  However the set it did find would have been good to compact.
Looking into fixing …
> Fixed compaction planning search bug

- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
- core/src/test/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlannerTest.java
When planning compactions for a tablet that currently has compactions running, then planning process will estimate what the size of the file the running compactions would produce and see if its more optimal to wait for these.  When doing this it only looks ahead once.  This change makes the planning process look ahead more for files to compact.
> Looks ahead more than once in compaction planning.

- server/base/src/main/java/org/apache/accumulo/server/iterators/SystemIteratorEnvironment.java
- server/base/src/main/java/org/apache/accumulo/server/iterators/SystemIteratorEnvironmentImpl.java
SystemIteratorEnvironmentImpl was added in #5587, but did not implement the isRunningLowOnMemory method. It deferred to its parent class implementation, ClientIteratorEnvironment.isRunningLowOnMemory, which just returns false.
> Modified SystemIteratorEnvironmentImpl to implement isRunningLowOnMemory

- core/src/main/java/org/apache/accumulo/core/data/Range.java
- core/src/main/java/org/apache/accumulo/core/dataImpl/RangeImpl.java
- core/src/main/java/org/apache/accumulo/core/iteratorsImpl/system/ColumnFamilySkippingIterator.java
- core/src/test/java/org/apache/accumulo/core/data/RangeTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/system/ColumnFamilySkippingIteratorTest.java
In #5621 a bug was introduced where if an iterator seeks with range and columns families that are disjoint it will throw an exception.  This was caused by Range.bound() that had this behavior.
To fix this copied the code in Range.bound() into RangeImpl and made a very slight modification.  This was done to preserve the existing behavior of the public API method Range.bound() and reuse 99% of its code and test for a slightly different behavior.  Also documented the behavior of Range.bound(), considered changing its behavior but this subtle change in runtime behavior seemed dicey w/ hard to predict outcomes (like it would change the runtime behavior of Scanner and BatchScanner which currently use Range.bound()).
Now when the range and column families are disjoint …
> fixes bug in seeking iterator w/ disjoint range and columns

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/namespace/create/SetupNamespacePermissions.java
- test/src/main/java/org/apache/accumulo/test/NamespacesIT.java
- test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java
Added the system user check logic that is defined in SetupPermissions for CreateTable.
https://github.com/apache/accumulo/blob/3af3fde6232bd11bd1cb05731d667723aaa2984a/server/manager/src/main/java/org/apache/accumulo/manager/tableOps/create/SetupPermissions.java#L43 
This fixes the "USER_DOESNT_EXIST" error that was being reported when the system user was attempting to create a namespace
> Allow system user to create namespaces

- core/src/main/java/org/apache/accumulo/core/util/tables/TableMapping.java
TableMapping.update was added as part of #5451 and it validated that the accumulo namespace contained all of the system tables. This is technically correct, except when upgrading. Since this is used as part of the client, there is not a good way to determine whether or not the instance is upgrading to implement an alternate check. This change modifies the check in TableMapping.update to only check that root and meta tables exist to allow the upgrade code to run.
Closes #5640
> Modified TableMapping.update to only check root and meta exist

- core/src/main/java/org/apache/accumulo/core/metadata/schema/RootTabletMetadata.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/filters/HasColumnFilter.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/filters/TabletMetadataFilter.java
- test/src/main/java/org/apache/accumulo/test/functional/TabletsMetadataIT_SimpleSuite.java
Filters on TabletMetadata were not being applied to the root tablet metadata causing an exception in in Manager.shouldCleanupMigration. The code was applying a filter to only return tablet metadata that contained a migration, then checking that the migration was not null. Because the filter was not being applied to the root tablet, it was being returned as matching the filter but with no migration.
Applying the fix in TabletsMetadata to run the filter on the root tablet metadata caused a subsequent issue in the GcWalsFilter where acceptTablet() would return null. Modified TabletMetadataFilter to protect against this condition.
Closes #5643
> Modified TabletsMetadata to run filters on root tablet

- server/base/src/main/java/org/apache/accumulo/server/AbstractServer.java
The default value of the bind address changed
recently and this was not updated.
> Fixed advertise address check for metrics rpc

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Resolves a deadlock in Tablet related code. Expected lock order is refreshLock -> logLock -> tablet, but `Tablet.completeClose()` would lock tablet -> refreshLock -> logLock, which could (and did) result in deadlocks. ChaoticBalancerIT would previously timeout almost every run. I ran it 10+ times with these changes with no deadlocks. I did not find any other situations where we do not acquire the locks in the order refreshLock -> logLock -> tablet, so Tablet code should now be deadlock free.
closes #5597
> Resolves TabletServer deadlock

- server/base/src/main/java/org/apache/accumulo/server/tablets/UniqueNameAllocator.java
- server/base/src/test/java/org/apache/accumulo/server/tablets/UniqueNameAllocatorTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/PrepBulkImport.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/create/ChooseDir.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/CreateImportDir.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/MapImportFileNames.java
- server/manager/src/test/java/org/apache/accumulo/manager/tableOps/tableImport/ImportTableTest.java
- test/src/main/java/org/apache/accumulo/test/UniqueNameAllocatorIT.java
Bulk import and other operations would repeatedly request new unique file names one at a time, possibly making multiple trips to zookeeper. For the case of bulk import and some other places in the code, the number of unique names needed is known ahead of time.  Changed name allocation to support requesting a batch of names.  For bulk import this means that bulk import would go to zookeeper at most once.
> Adds support for getting batches of names

- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java
On upgrading to 4.0 (13), the fate table would exist on listing the tables with something like `tables -ls` but there were no entries in the metadata table for the fate table. This left accumulo in a broken state where table operations could not be handled.
Listing the tables is done through scanning ZooKeeper for the table info. Upgrading ZooKeeper is done first then upgrading the metadata is done. The ZooKeeper step completed fine, which is why the fate table would show up on listing the tables. But the upgrade metadata step would check if the fate table already exists (via TableOperations.exists()) before populating the metadata with the fate table data. The problem is that TableOperations.exists() always returns true for system tables so the metadata table would never get populated. …
> fixes an issue with upgrade 12 to 13

- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
During upgrade testing a NullPointerException was seen in the TabletGroupWatcher when referencing Manager.getSplitter(). This change will prevent the TabletGroupWatcher from splitting or compacting tablets while the upgrade is in progress.
> Modified TabletGroupWatcher to only assign/balance during upgrade

- server/manager/src/main/java/org/apache/accumulo/manager/BalanceManager.java
- server/manager/src/main/java/org/apache/accumulo/manager/EventCoordinator.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
- test/src/main/java/org/apache/accumulo/test/functional/SimpleBalancerFairnessIT.java
- test/src/main/java/org/apache/accumulo/test/functional/TabletResourceGroupBalanceIT.java
> Moved balancing into three dedicated threads

- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/ExternalCompactionExecutor.java
Ran into an issue when running random walk bulk test where a compaction that needed to happen was never running.  The code fixed in this PR used to change the state to running and then forget about it in some cases. However [this code][1] would still remember it.  That would cause this [this code][2] to filter out planned jobs when there were running compactions in submitted jobs. Hopefully this change will cause [this code][3] to filter this from submitted jobs.
Ran all Compaction ITs w/ this change and they passed.
[1]:https://github.com/apache/accumulo/blob/5bba2f3cf36717d0e2fabbf4abb93c3455c0619e/server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionService.java#L84 [2]:https://github.com/apache/accumulo/blob/5bba2f3cf36717d0e2fabbf4abb93c3455c0619e/server/tser …
> fixes bug where external compaction never starts

- test/src/main/java/org/apache/accumulo/test/fate/FateOpsCommandsITBase.java
- test/src/main/java/org/apache/accumulo/test/fate/meta/MetaFateOpsCommandsIT.java
- test/src/main/java/org/apache/accumulo/test/fate/user/UserFateOpsCommandsIT.java
MetaFateOpsCommandsIT and UserFateOpsCommandsIT would take 10 minutes each before this commit, now take 3 minutes each
- modified test to be able to use SharedMiniClusterBase instead of ConfigurableMacBase, which improved run times
- this required extra cleanup between tests (cleaning up fate ops), and restarting the Manager for tests that stop it
- now only stop the compactors at the start of the test (BeforeAll), instead of BeforeEach, which improved run times. This was made possible by the switch to SharedMiniClusterBase
- fates are now correctly shutdown in the test. Previously, were not shutdown in a finally, leading to issues if assertions fail and shutdowns don't happen.
- one test (testTransactionNameAndStep) was only testing USER FATE transactions for both MetaFateOpsCommandsIT …
> Sped up FateOpsCommandsIT, other test improvements

- pom.xml
This change avoids unnecessarily accessing the configured repository.apache.org/snapshots snapshot repository. To do this, it affixes a specific version from the range in one of the transitive dependencies (in this case, bouncycastle), so Maven does not query all of the configured repositories for the versions they contain. The apparent behavior of Maven's dependency resolution is to query all repositories, whether they are configured for snapshots or releases, in order to resolve dependency ranges. However, this [may be a bug in Maven](https://github.com/apache/maven/issues/2558)
It is important to avoid unnecessary accesses to
repository.apache.org/snapshots, because Apache's INFRA team blocks network clients for too many accesses to repository.apache.org that result in 404s. Any …
> Avoid unnecessarily accessing snapshot repositories

- core/src/main/java/org/apache/accumulo/core/util/Validators.java
- test/src/main/java/org/apache/accumulo/test/functional/CloneTestIT_SimpleSuite.java
CloneTestIT_SimpleSuite.testCloneSystemTables() was failing because it was possible to clone the scanref and fate tables.  It seems like it would be safe to allow cloning those tables, but decided to disallow for now for consistency.  Can relax the restriction in the future if needed.
> disallows cloning fate and scanref tables

- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- test/src/main/java/org/apache/accumulo/test/functional/ShutdownIT.java
Client side table operations that used fate could see exceptions during manager shutdown before this fix.  After this fix hopefully that is not the case.  Was occasionally seeing this problems in a ShutdownIT test. Modified ShutdownIT to more reliably cause the problem before this fix, after this fix the test is passing consistently.
fixes #5714
> Avoid client side errors during manager shutdown.

- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloConfigImpl.java
- test/src/main/java/org/apache/accumulo/test/TotalQueuedIT.java
Problem was two-fold:
1) ed40b628514750c95e3e40abcd8330493f4d99a3 updated the set of fixed
properties to be more accurate. This test was changing a property
that was newly declared as fixed, so config change wasn't being picked up since related servers weren't restarted. Now restart related servers (the TServers) after config change.
2) The config set before starting the MAC called `cfg.useMiniDFS()`
which simply returned the value of `useMiniDFS`, and didn't set
anything. This caused things to hang after restarting the TServers. Changed to `cfg.useMiniDFS(true)` and renamed `useMiniDFS()` -> `getUseMiniDFS()`
> Fixes broken TotalQueuedIT 2.1+

- core/src/main/java/org/apache/accumulo/core/fate/Fate.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/FateIT.java
In FateIT fate threads were hanging around after a test method completed and sometimes causing problems for subsequent test.  Made the test methods wait for all threads in to stop in Fate
> Fixes FateIT being flaky

- assemble/pom.xml
- server/monitor/pom.xml
- server/monitor/src/main/java/org/apache/accumulo/monitor/next/CustomObjectMapper.java
Saw the following Error message in console log that mentioned the Duration datatype was not able to be serialized.
```
Java 8 date/time type `java.time.Duration` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: java.util.Collections$SynchronizedRandomAccessList[1]->org.apache.accumulo.monitor.next.SystemInformation$SanitizedTabletInformation["tabletMergeabilityInfo"]->org.apache.accumulo.core.client.admin.TabletMergeabilityInfo["tabletMergeability"]->org.apache.accumulo.core.client.admin.TabletMergeability["delay"])
```
Added the jackson JavaTimeModule to fix the 404 return.
Tested locally and confirmed the 404 return code was fixed.
> Fixes 404 return code when calling tabletMergabilityInfo.

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
Updates the property description for `monitor.root.context` to remove the trailing slash.
Also adds the property to the fixed property list so generated documentation is accurate.
> Update property description and fixed status

- core/src/main/java/org/apache/accumulo/core/metadata/SuspendingTServer.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadata.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/TabletMetadataTest.java
Improved the test coverage of metadata columns by adding a test within the testAllColumns method of TabletMetadataTest that fails if new columns are added to the metadata stores but are untested. Added tests for all current ColumnTypes that had not been tested.
Closes #5521
> Improved metadata columns test coverage

- server/base/src/main/java/org/apache/accumulo/server/manager/LiveTServerSet.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java
- server/manager/src/test/java/org/apache/accumulo/manager/tableOps/ShutdownTServerTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
When a tablet server is gracefully shutdown it notifies the manager it is shutting down. The manager would remove the server from the set of live tservers which caused the manger to treat all tablets on that tserver as assigned to dead tservers.
Saw this when debugging a failure with GracefulShutdownIT. Saw the manager initiate log recovery and reassignment for the root tablet before it unloaded from the tserver that was shutting down. This caused errors with the metadata tablet consistency check during unload of the root tablet because the manager had modified the tablet metadata before unload.
This fix modifies the tablet server to use the existing fate operation for shutting down a tserver.
> avoids reassignment of hosted tablet during shutdown

- assemble/bin/accumulo-cluster
- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
- server/base/src/main/java/org/apache/accumulo/server/util/ZooZap.java
- test/src/main/java/org/apache/accumulo/test/functional/GracefulShutdownIT.java
Currently the admin stop command takes a list of hostnames which are assumed to be tservers.  This change allows admin stop to also take a list of host:port pairs.  For these host:port pairs they can be any accumulo server type and the new gracefulShutdown code will be called for them.  The admin signalShutdown command was removed since the stop command is calling the same code internally now.
When ports are not specified the command behaves exactly as it used to. However a deprecation warning is logged because the old command would use local config to guess at ports, so it would never stop tservers on a host where its local config had different ports. Hopefully the deprecated behavior of only specifying host can be replaced w/ something like the following.  Need to see what the actual …
> Merges admin signalShutdown into admin stop command

- test/src/main/java/org/apache/accumulo/test/functional/ShutdownIT.java
The IT was expecting the tserver to be down, but now it may take a little time for the tserver to stop. Modified the test to wait for the tserver to stop.
> Fixed ShutdownIT after recent Admin.stop change

- core/src/main/java/org/apache/accumulo/core/security/ColumnVisibility.java
- core/src/main/java/org/apache/accumulo/core/security/VisibilityEvaluator.java
- core/src/test/java/org/apache/accumulo/core/security/ColumnVisibilityTest.java
- core/src/test/java/org/apache/accumulo/core/security/VisibilityEvaluatorTest.java
Since column visibility changes are no longer being deprecated in 3.1.0, restored the code that was deprecated and then removed.
Made the following changes in this commit
* Reverted commit d1caa6411c2f5c5deb3a89be4f3e2afb5abdf530
* pulled changes from commit 355ef24bc512ab893f8f6bf33f8d3f4052f9ee10
* Changed deprecated since 3.1.0 to 4.0.0
> Restores deprecated column visibility code

- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
- server/base/src/main/java/org/apache/accumulo/server/util/ServiceStatusCmd.java
- server/base/src/main/java/org/apache/accumulo/server/util/serviceStatus/ServiceStatusReport.java
- server/base/src/main/java/org/apache/accumulo/server/util/serviceStatus/StatusSummary.java
- server/base/src/test/java/org/apache/accumulo/server/util/ServiceStatusCmdTest.java
Closes [issue #5051 ](https://github.com/apache/accumulo/issues/5051)
I changed ServiceStatusCmd option json from a boolean to a sting to allow for the option from having the full summary of the system (the current output) and condense version of it ( new desired output). I also went a head and added a new option for ServiceStatusCmd to output in csv format as well.
> new options display option for ServiceStatusCmd

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientTabletCacheImpl.java
Fixes the following race condition.
1. Thread 1 reads the cache and finds it stale/missing
2. Thread 2 reads the cache and finds it stale/missing
3. Thread 2 goes through the entire process of reading metadata and updating the cache
4. Thread 1 does the pre lock read of the cache (this reread of the cache causes the race condition).
5. Thread 1 does the post lock read of the cache and finds its the same and unessecairly reads the metadata table
This change avoids reading from the cache twice before locking and updating and only reads once.  This way the cache entry used to make a decision after the lock is obtianed is the same one that was seen as stale.
> fixes race condition in ClientTabletCacheImpl

- server/base/src/main/java/org/apache/accumulo/server/util/ZooZap.java
Modified ZooZap to delete individual servers rather than entire resource groups.  This makes it work with prune which excludes some host in a resource group.
fixes #5753
> Makes ZooZap work with accumulo-cluster prune

- pom.xml
The current minumum version for maven that is enforced via the maven-enforcer-plugin is version 3.6.3 as defined in the parent pom [here](https://github.com/apache/maven-apache-parent/blob/b8689ef9c894f0fd8ab202e6eb55acc97793fa4a/pom.xml#L99)
This version is no longer being supported. This PR overrides that minimum to 3.9.11 which is the current LTS version.
This fixes a discrepancy between a feature of the .mvn/maven.config file added in #5716 which has a comment and the version 3.6.3 not supporting that comment.
> Add override for min maven version to version 3.9.11

- core/src/main/java/org/apache/accumulo/core/client/admin/compaction/CompactionConfigurer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableUtils.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/compaction/strategies/ConfigurableCompactionStrategyTest.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
Adds two methods to compaction configurer that provide the tablet and output path for the compaction.  This allows different configuration to be generated based on the tablet or volume.
> Support configuring compactions by tablet and output path

- core/src/main/java/org/apache/accumulo/core/client/admin/compaction/CompressionConfigurer.java
- core/src/main/java/org/apache/accumulo/core/client/admin/compaction/ErasureCodeConfigurer.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/conf/PropertyType.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/EcEnabled.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/RFileOperations.java
- core/src/test/java/org/apache/accumulo/core/conf/PropertyTypeTest.java
- core/src/test/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlannerTest.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloConfigImpl.java
- server/base/src/main/java/org/apache/accumulo/server/util/PropUtil.java
- test/src/main/java/org/apache/accumulo/test/compaction/ErasureCodeIT.java
Adds Erasure Codes support in Accumulo.  The changes to RFileOperations allow EC to be treated similarly to replication.  Two new table properties are introduced.  One to enable EC on a per table basis and one to set the specific ec policy for the table.  CompressionConfigurer was extended with ErasureCodeConfigurer as an example for more specialized ec handling.  It will enforce constraints on ec.  File size limits can be imposed to encode only larger files.
> Adds per table and compaction erasure code support

- .mvn/maven.config
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/clone/CloneTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/create/CreateTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/namespace/create/CreateNamespace.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/ImportTable.java
- test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java
Create test `testUniquenessOfTableId()` in TableOperationsIT to ensure that concurrent calls will get a unique table id, and that the lock in Manager can be removed.
Closes #5723
> Remove Table id lock in Manager

- core/src/main/java/org/apache/accumulo/core/file/rfile/RFileOperations.java
Changes in #5743 made RFileOperations use a HDFS builder to create an output stream.  Prior to using the builder the calls to HDFS to create an output stream would also create parent directories if they did not exist.  Seems the log recovery code in accumulo was relying on this behavior.  Added an option to the builder to create parent dirs if they do not exists.
This problem was detected by TotalQueuedIT which was failing in log recovery and the tserver had exception about a parent directory not existing.  With these changes TotalQueuedIT now passes.
Could not find javadoc on the old HDFS API calls that mentioned that the parent directory was created.  Wrote some test code that called the previous APIs and confirmed that parent dirs were created if needed.
> fixes log recovery by creating parent directories

- test/src/main/java/org/apache/accumulo/test/functional/AdvertiseAndBindIT.java
Doubled the wait time when calling Wait.waitFor to try and reduce flakiness of test on other test
platforms. Wait.waitFor is timing out in some
cases.
> Increase wait time in AdvertiseAndBindIT

- test/src/main/java/org/apache/accumulo/test/functional/TabletsMetadataIT_SimpleSuite.java
When run with SimpleSharedMacTestSuiteIT there are other entries in the metadata table that cause these assertions to fail.
> Removed assertions that fail with SimpleSharedMacTestSuiteIT

- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
- server/base/src/main/java/org/apache/accumulo/server/util/ServiceStatusCmd.java
- server/base/src/main/java/org/apache/accumulo/server/util/serviceStatus/ServiceStatusReport.java
- server/base/src/main/java/org/apache/accumulo/server/util/serviceStatus/StatusSummary.java
- server/base/src/test/java/org/apache/accumulo/server/util/ServiceStatusCmdTest.java
- server/base/src/test/java/org/apache/accumulo/server/util/serviceStatus/ServiceStatusReportTest.java
Adds resource group summary information to the printed and json reports produced by the `admin serviceStatus` command. 
closes #5051 
new printed summary output
```
ZooKeeper read errors: 0
Managers: count: 1
Monitors: count: 1
Garbage Collectors: count: 1
Tablet Servers: count: 3
Scan Servers: count: 3
resource groups:
default: 3
Coordinators: count: 1
Compactors: count: 5
resource groups:
q1: 2
q2: 3
```    
new json summary output 
```
./accumulo admin serviceStatus --json | jq 
{
"reportTime": "2025-08-05T22:00:03.481Z",
"zkReadErrors": 0,
"showHosts": false,
"summaries": {
"COMPACTOR": {
"serviceType": "COMPACTOR",
"resourceGroups": {
"q1": 2,
"q2": 3
},
"serviceByGroups": {},
"serviceCount": 5,
"errorCount": 0
},
"COORDINATOR": {
"serviceType": "COORDINATOR",
"resourceGroups": {}, …
```
> adds group summary information to reports.

- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/LoadMappingIterator.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/bulk/LoadMappingIteratorTest.java
Closes [issue #5045 ](https://github.com/apache/accumulo/issues/5045)
Added a validation check in `LoadMappingIterator`, to ensure that KeyExtents are sorted.
> Validation check for KeyExtents

- shell/src/main/java/org/apache/accumulo/shell/commands/CreateTableCommand.java
Describes the acceptable format for setting multiple init properties on table creation
> Changes description of createTable command

- LICENSE
- assemble/src/main/resources/LICENSE
- core/src/main/appended-resources/META-INF/LICENSE
- server/monitor/src/main/appended-resources/META-INF/LICENSE
* Fix version numbers for bundled monitor dependencies
* Make it more clear where files can be found
* Add text present in one LICENSE files but not others, that the dual-licensed library shipped with flot is being distributed by this project under the MIT license
* Make the text of the various LICENSE files consistent, so it's easier to use a diff tool to compare them
> Fix LICENSE files

- server/base/src/main/java/org/apache/accumulo/server/AbstractServer.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
The use of try-with-resources in the server process' main method causes the server's close method to always be called. When an exception occurs in the runServer method it may not be logged because the invocation of the close method consumes enough time that the lock watcher is fired which ends up halting the JVM.
Closes #5794
> Fixed issue with exception in server run method not being logged

- core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java
Fixes #5791
From what I can tell the feature mentioned in the TODO comment (updating existing splits) can be removed because:
* putSplits() properly collects and handles existing splits that need TabletMergeability updates
https://github.com/apache/accumulo/blob/a893ee5c5327748e101369850b983248cabf6153/core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java#L524
* `updateSplitWithMergeabilityTest()` seems to properly cover this case
* there are also tests covering concurrently updating overlapping splits properly
> Remove outdated TODO in TableOperations.putSplits

- core/src/main/java/org/apache/accumulo/core/fate/FateExecutor.java
This fixes the test failures testing the cancel command, which were resulting in NPE.
Will run the full set of FATE tests now to verify fix.
> Fixes NPE from recent FATE changes

- pom.xml
- test/src/main/java/org/apache/accumulo/test/zookeeper/ZooCacheIT.java
> Bump compiler source and target versions from Java 11 to Java 17

- core/src/main/java/org/apache/accumulo/core/fate/AdminUtil.java
- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/DistributedReadWriteLock.java
- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/FateLock.java
- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/LockRange.java
- core/src/test/java/org/apache/accumulo/core/fate/zookeeper/DistributedReadWriteLockTest.java
- core/src/test/java/org/apache/accumulo/core/fate/zookeeper/FateLockTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/FateServiceHandler.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/ChangeTableState.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/Utils.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/availability/LockTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/CleanUpBulkImport.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/ComputeBulkRange.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/PrepBulkImport.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/CleanUp.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/CompactRange.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/merge/TableRangeOp.java
- server/manager/src/test/java/org/apache/accumulo/manager/tableOps/bulkVer2/PrepBulkImportTest.java
- test/src/main/java/org/apache/accumulo/test/fate/FateOpsCommandsITBase.java
- test/src/main/java/org/apache/accumulo/test/fate/RangedTableLocksIT.java
Added ranges to table locks using the ranges from fate operations.  For write locks these ranges are widened to the nearest splits, see comments in Utils.reserveTable for details.  See comments and code in DistributedReadWriteLock.WriteLock.tryLock() and
DistributedReadWriteLock.ReadLock.tryLock() for details about how these ranges change lock behavior.  Added tests to excercise this new locking behavior. Modified the `accumulo admin fate -l` command to display lock ranges.  Also modified how this command determines if a lock is held or waiting.
fixes #2483
> adds ranges to table locks

- test/src/main/java/org/apache/accumulo/test/fate/RangedTableLocksIT.java
This is a follow on fix for #5786.  Made some changes after getting the test working that broke the test.  Plan to merge this if GH actions all pass.
> fixes RangedTableLocksIT

- test/src/main/java/org/apache/accumulo/test/functional/ConcurrentTableNameOperationsIT.java
Adds the test cases added in #5822 from main. These test cases cover various concurrent scenarios that all test that a targeted table name will only be created once.
> Backport concurrent table name collision tests

- test/src/main/java/org/apache/accumulo/test/ComprehensiveTableOperationsIT_SimpleSuite.java
making it such that there were no ITs that get run as part of SimpleSharedMacTestSuiteIT with the sunny profile. This caused the sunny profile test run to fail because the SimpleSharedMacTestSuiteIT would not find any tests to run and fail. Adding the sunny tag to one test that runs as part of the suite fixes the issue.
Closes #5851
> Add Sunny tag to ComprehensiveTableOperationsIT_SimpleSuite

- shell/src/main/java/org/apache/accumulo/shell/Shell.java
> stop removing backslashes in shell

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java
scanParams.getClassLoaderContext() is always null when this log message is generated. 
Use the correct context instead.
> Print the correct context in the log message

- shell/src/main/java/org/apache/accumulo/shell/commands/ConfigCommand.java
The config command will print all matching resource
group properties by default. There is no need for
the resource group to be specified unless setting
or deleting a property.
Related to #5859
> Fail if config cmd used with rg but not -s or -d

- server/base/src/main/java/org/apache/accumulo/server/util/UpgradeUtil.java
When running `accumulo -help` the description of the upgrade command is really long compared to other commands.  Shortened the description by moving information into the options so that the more detailed information is displayed when running `accumulo upgrade --help`.  Some of the information in the description was redundant w/ the existing help for `--prepare` and did not need to be moved.
> shortens help description for accumulo upgrade

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/test/java/org/apache/accumulo/core/conf/PropertyTest.java
ExistingMacIT was failing w/ the following error.  Seemed that a newline in the default fate config json was causing apache commons config to only see up to the first newline for the value.  Removed the newlines in the default config to fix the issue.
```
org.apache.accumulo.core.conf.ConfigCheckUtil$ConfigCheckException: BAD CONFIG improperly formatted value for key (manager.fate.user.config, type=fate user config) : { for site config
at org.apache.accumulo.core.conf.ConfigCheckUtil.fatal(ConfigCheckUtil.java:150)
at org.apache.accumulo.core.conf.ConfigCheckUtil.validate(ConfigCheckUtil.java:62)
at org.apache.accumulo.core.conf.SiteConfiguration.<init>(SiteConfiguration.java:206)
at org.apache.accumulo.core.conf.SiteConfiguration$Builder.build(SiteConfiguration.java:171)
at …
```
> removes newlines in default fate config json

- test/src/main/java/org/apache/accumulo/test/DumpConfigIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ChaoticBalancerIT.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorTrashEnabledIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ManyWriteAheadLogsIT.java
These are some of the easier fixes to test that were broken by the changes in #5886.  Removed setting table props in the site config in the test.
> fixes tests that place table props in site config

- test/src/main/java/org/apache/accumulo/test/VolumeChooserIT.java
- test/src/main/java/org/apache/accumulo/test/VolumeIT.java
* Limit visibility of fields and methods where possible
* Restore intent of fourth volume prior to #1813 cleanup that broke it,
but leave test disabled, as documentation for future test fixes
* Convert between Path, Text, and String less often
* Simplify code paths and improve method names, inlining code where
possible
* Use Ample to verify volumes
* Add test case for the default preferred volume at the system level
> Improve VolumeChooserIT

- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader11to12.java
- server/manager/src/test/java/org/apache/accumulo/manager/upgrade/Upgrader11to12Test.java
* Avoid public API when looking up namespace names/ids
* Use NamespaceMapping for simpler code
* Update unit test accordingly and give unique test namespace id and name based on test method name
> Improve Upgrader11to12 to avoid public API
