apache/accumulo

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
To test this patch, I made the following changes and ran the WriteLotsIt and ConditionalWriterIT
```
diff --git a/server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java b/server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
index 7c0eedc..4483fe8 100644
--- a/server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
+++ b/server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
@@ -469,6 +469,9 @@ public class TabletServerResourceManager {
}
void waitUntilCommitsAreEnabled() {
+    if(Math.random() < .1)
+      throw new HoldTimeoutException("test");
+
if (holdCommits) {
long timeout = System.currentTimeMillis() + …
```
> ACCUMULO-2388 Make clients retry in case of HoldTimeoutException

- core/src/main/java/org/apache/accumulo/core/client/BatchScanner.java
This will help clear possible confusion on when to use BatchScanners vs Scanners.
> ACCUMULO-3959 More accurate BatchScanner javadoc

- README.md
#91 should be reviewed/merged first before this PR
> ACCUMULO-4189 - Added direct links to documentation on Accumulo website

- README.md
Did not add Travis CI badge as builds are not completing in time.
> ACCUMULO-4179 - Add GitHub badges to README.md

- test/src/main/java/org/apache/accumulo/test/functional/WALSunnyDayIT.java
Trying to make this IT fail less often.  See https://issues.apache.org/jira/browse/ACCUMULO-4110 for discussion.
> ACCUMULO-4110 clean up the WALSunnyDayIT

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
1.6 documentation fix for ACCUMULO-2972
> ACCUMULO-2972: fixed description for instance.secret

- core/src/main/java/org/apache/accumulo/core/client/impl/Namespaces.java
- core/src/main/java/org/apache/accumulo/core/client/impl/Tables.java
- core/src/main/java/org/apache/accumulo/core/client/impl/ThriftTransportPool.java
- core/src/main/java/org/apache/accumulo/core/file/streams/BoundedRangeFileInputStream.java
- fate/src/main/java/org/apache/accumulo/fate/zookeeper/ZooReaderWriter.java
- server/base/src/main/java/org/apache/accumulo/server/conf/ServerConfigurationFactory.java
- server/base/src/main/java/org/apache/accumulo/server/security/SystemCredentials.java
- server/base/src/main/java/org/apache/accumulo/server/tables/TableManager.java
https://issues.apache.org/jira/browse/ACCUMULO-4498
> ACCUMULO-4498 Remove vestigial security permission stuffs

- server/monitor/src/main/java/org/apache/accumulo/monitor/servlets/BasicServlet.java
Added a link to the monitor menu that points to https://accumulo.apache.org/
> ACCUMULO-3891 Added link to Apache Accumulo website on the monitor

- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
Created a prompt when running "accumulo init --reset-security" to warn user and require
entering the instance secret.  Added a "-f,--force" option for scripts to bypass the prompt.
Also fixed message in Initialize about running ChangeSecret tool.
Ticket fix version says 2.0.0 but I think 1.8 and other versions would benefit as well.
> ACCUMULO-3626: Reset security should warn and require instance secret

- server/monitor/src/main/java/org/apache/accumulo/monitor/servlets/MasterServlet.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/servlets/OperationServlet.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/servlets/TablesServlet.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/util/Table.java
- server/monitor/src/main/resources/web/screen.css
Can now filter namespaces on the table list. 
Back end implementation is done, and I would appreciate the feedback on the Front end. 
Front end can be seen on the "Master Server" and "Tables" pages.
> Accumulo 1480 Added namespace filtering to tables

- _includes/nav.html
- governance/bylaws.md
- governance/index.md
* Governance page links to all pages that were
previously in navbar
> Navbar now links to a single governance page

- _layouts/post.html
- _posts/blog/2016-11-16-simpler-scripts-and-config.md
- css/accumulo.scss
* Also minor change to post template
> Blog post about simplified scripts in 2.0.0

- core/src/main/java/org/apache/accumulo/core/rpc/TServiceClientWrapper.java
- core/src/main/scripts/generate-thrift.sh
- core/src/main/thrift/client.thrift
- core/src/main/thrift/master.thrift
- pom.xml
- server/base/src/test/java/org/apache/accumulo/server/rpc/RpcWrapperTest.java
This PR includes changes to update thrift, but without any re-generated Java code for easier review. For the full set of changes, including re-generated code, see #215 . [ACCUMULO-4551](https://issues.apache.org/jira/browse/ACCUMULO-4551)
> ACCUMULO-4551 thrift 0.10.0

- docs/src/main/asciidoc/chapters/administration.txt
@ctubbsii let me know what you think.  After this is approved and I merge it into 1.8, I'll merge it forward to master and then copy the generated html file in the accumulo-website repo.
> ACCUMULO-4480 - update user manual for 1.8

- assemble/bin/accumulo
- assemble/bin/accumulo-service
- assemble/bin/accumulo-util
- assemble/conf/templates/accumulo-env.sh
- server/tserver/src/main/java/org/apache/accumulo/tserver/NativeMap.java
- test/src/main/java/org/apache/accumulo/test/InMemoryMapIT.java
- test/src/main/java/org/apache/accumulo/test/functional/NativeMapIT.java
* Using system property rather than environment variable to configure
native libraries.
* Removed unnnecessary system property for xml parsing
> ACCUMULO-4596 Stopped using ACCUMULO_HOME for native libs

- shell/src/main/java/org/apache/accumulo/shell/Shell.java
- shell/src/test/java/org/apache/accumulo/shell/ShellConfigTest.java
- shell/src/test/resources/accumulo-site.xml
Changes to Shell that should fix this problem without having to revert ACCUMULO-4505
TODO: Fix ShellConfigTest to properly test and not just compile.
> ACCUMULO-4600: Fix to properly read from accumulo-site.xml

- assemble/bin/accumulo
- assemble/conf/templates/accumulo-env.sh
- core/src/main/java/org/apache/accumulo/core/file/rfile/PrintInfo.java
- core/src/main/java/org/apache/accumulo/core/util/Classpath.java
- core/src/main/java/org/apache/accumulo/core/util/CreateToken.java
- docs/src/main/asciidoc/chapters/clients.txt
- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
- shell/src/main/java/org/apache/accumulo/shell/commands/ClasspathCommand.java
- start/src/main/java/org/apache/accumulo/start/Main.java
- start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloVFSClassLoader.java
- start/src/test/java/org/apache/accumulo/start/classloader/vfs/AccumuloClasspathTest.java
* Default output is now colon seperated jars on one line
* Added '-d' option to print old human readable format
* Improved usage for accumulo script commands
> ACCUMULO-4604 Improve 'accumulo classpath' command

- fate/pom.xml
- iterator-test-harness/pom.xml
- maven-plugin/pom.xml
- maven-plugin/src/it/plugin-test/pom.xml
- pom.xml
- server/base/pom.xml
- start/pom.xml
* Now using only one httpclient jar
* Marked xml-apis jar as provided
* Added slf4j-log4j12 to several modules with test scope
> ACCUMULO-4618 Updates from additional code review

- docs/src/main/asciidoc/accumulo_user_manual.asciidoc
* Decreased levels from 4 to 2
> ACCUMULO-4624 Decrease levels in user manual TOC

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeChooser.java
- server/base/src/main/java/org/apache/accumulo/server/master/balancer/TabletBalancer.java
Add a property prefix for custom system-wide properties
> ACCUMULO-3384 support custom system props

- assemble/build.sh
Update to form email for voting.  If approved, will make this in 1.7, 1.8, and master.
> ACCUMULO-4648 - Update voting text in build.sh script

- server/master/src/main/java/org/apache/accumulo/master/replication/SequentialWorkAssigner.java
Hoping someone more familiar with the replication code can make sure this was a bug...
> ACCUMULO-4699 Fixed queued work key in replication

- core/src/main/java/org/apache/accumulo/core/conf/CliConfiguration.java
- core/src/main/java/org/apache/accumulo/core/conf/SiteConfiguration.java
- core/src/test/java/org/apache/accumulo/core/conf/CliConfigurationTest.java
- core/src/test/java/org/apache/accumulo/core/conf/SiteConfigurationTest.java
- server/base/src/main/java/org/apache/accumulo/server/ServerOpts.java
- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
- server/base/src/test/java/org/apache/accumulo/server/ServerOptsTest.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/master/src/main/java/org/apache/accumulo/master/Master.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- server/tracer/src/main/java/org/apache/accumulo/tracer/TraceServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
* Added -o option to Accumulo services to override configuration
* Added --upload-accumulo-site option to 'accumulo init' command
* Tserver replication service now supports port search
> ACCUMULO-4706 Updates to support Accumulo docker image

- core/src/main/java/org/apache/accumulo/core/file/blockfile/cache/BlockCacheManager.java
- core/src/main/java/org/apache/accumulo/core/file/blockfile/cache/impl/BlockCacheConfiguration.java
- core/src/test/java/org/apache/accumulo/core/file/blockfile/cache/BlockCacheManagerTest.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/view/WebViews.java
Initial PR to allow testing done by Keith. Since I can't test locally at the moment. I realize more will most likely need to be done.
> ACCUMULO-4743 Replaced general custom with tserver prefix for cache config

- assemble/pom.xml
- assemble/src/main/assemblies/component.xml
- pom.xml
- server/monitor/pom.xml
- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/problems/ProblemsResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tables/TablesResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/trace/TracesResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tservers/TabletServerResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/util/ParameterValidator.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/view/WebViews.java
- server/monitor/src/test/java/org/apache/accumulo/monitor/util/ParameterValidatorTest.java
- server/monitor/src/test/java/org/apache/accumulo/monitor/view/WebViewsTest.java
- test/pom.xml
- test/src/main/java/org/apache/accumulo/test/monitor/WebViewsIT.java
I took a swing at this one.  I wasn't fully sure what the bounds on some of the params should be (i.e. should minutes be bound between (0-59]  )?  What level of sanitization is sufficient, UrlEncoder kind  of stuff?  Take a look at the ParameterValidator class first if you're interested as it is the piece that's reused across the rest endpoints.
If you had something else in mind, feel free to decline or provide feedback and I can update.  Regards!
Note: Still running a local build and need to add further unit tests etc. if you're interested in this submission.
(Fails on RAT license check currently)
> ACCUMULO-4677 Sanitizing PathParam values in REST-based Monitor

- core/pom.xml
- core/src/main/java/org/apache/accumulo/core/conf/ConfigurationDocGen.java
* Added class='props' to properties for css changes
* Renamed generated file to properties.md
See related PR at apache/accumulo-website#47
> ACCUMULO-4754 Fix links to properties in 2.0 docs

- pom.xml
Added list of our exceptions for the classes we currently use
> ACCUMULO-4704 Added library-detectors 1.2 plugin & configured pom to skip

- core/src/main/java/org/apache/accumulo/core/security/crypto/BlockedOutputStream.java
- core/src/main/java/org/apache/accumulo/core/security/crypto/DefaultCryptoModule.java
Removed duplicate code in DefaultCryptoModule
Added check for existence of array in BlockedOutputStream before using the array in a stream's flush.
> ACCUMULO-4767 Remove duplicate code in DefaultCryptoModule

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/overview.js
Fix a javascript bug in the code which updated the table of ZooKeeper
nodes on the monitor overview page.
> ACCUMULO-4770 Show all ZooKeeper nodes on monitor

- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
Use the name of the localhost from the local name service when the
monitor binds to 0.0.0.0 instead of advertising 0.0.0.0, which other
servers cannot connect to. This fixes log forwarding from other Accumulo
servers to the monitor when the monitor is configured to bind to all
interfaces.
> ACCUMULO-4776 Fix advertised host in monitor

- core/src/main/java/org/apache/accumulo/core/client/impl/ThriftTransportKey.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/base/src/main/java/org/apache/accumulo/server/security/AuditedSecurityOperation.java
* Avoid computing audit log message when level is not enabled
* Faster hash function in thrift transport key
* Avoid accessing site config for frequently accessed properties
> misc performance improvements

- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/LogSorter.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/logger/LogReader.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/replication/AccumuloReplicaSystem.java
Contemplating how to make a test for this, but pushing this build out to our dev system has removed the `CLOSE_WAIT` connections.
> [ACCUMULO-4787] Close input stream in AccumuloReplicaSystem

- CONTRIBUTING.md
Opening this PR to discuss initial workflow on github issues.
> Proposal for switching to github issues

- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/tables.ftl
Update the columns that contain numeric values to use descending sort first. (Issue #423)
> Reverse sort order except for state and table name

- shell/src/main/java/org/apache/accumulo/shell/commands/EGrepCommand.java
- shell/src/main/java/org/apache/accumulo/shell/commands/GrepCommand.java
Allow user to specify -v to negate searches using grep and egrep.
> Expose negation to shell

- core/src/main/java/org/apache/accumulo/core/client/impl/ClientConfConverter.java
- core/src/main/java/org/apache/accumulo/core/client/impl/ConnectionInfoFactory.java
- minicluster/src/main/java/org/apache/accumulo/cluster/AccumuloCluster.java
- minicluster/src/main/java/org/apache/accumulo/cluster/standalone/StandaloneAccumuloCluster.java
- minicluster/src/main/java/org/apache/accumulo/minicluster/MiniAccumuloCluster.java
- minicluster/src/main/java/org/apache/accumulo/minicluster/MiniAccumuloInstance.java
- minicluster/src/main/java/org/apache/accumulo/minicluster/impl/MiniAccumuloClusterImpl.java
- pom.xml
* Update checkstyle to ignore line length checks for lines
with org.apache.accumulo in it
>  #408 - Removed more uses of deprecated ClientConfiguration

- core/src/main/java/org/apache/accumulo/core/client/Connector.java
- core/src/main/java/org/apache/accumulo/core/client/impl/ConnectorImpl.java
- core/src/main/java/org/apache/accumulo/core/client/mock/MockConnector.java
- test/src/main/java/org/apache/accumulo/test/functional/ConnectorIT.java
* Also added method to retrieve ConnectionInfo from Connector
> Fixes #414 - Create Connector for new user from existing

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/test/java/org/apache/accumulo/core/conf/PropertyTest.java
- start/src/main/java/org/apache/accumulo/start/classloader/AccumuloClassLoader.java
- test/src/main/java/org/apache/accumulo/test/MetaRecoveryIT.java
This removes properties that were only used in Property.java and PropertyTest.java for issue #448
> Removing unused properties for #448

- client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapred/AbstractInputFormat.java
- client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapred/AccumuloOutputFormat.java
- client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapreduce/AbstractInputFormat.java
- client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapreduce/AccumuloOutputFormat.java
- client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapreduce/RangeInputSplit.java
- client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapreduce/impl/SplitUtils.java
- client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapreduce/lib/impl/ConfiguratorBase.java
- client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapreduce/lib/impl/InputConfigurator.java
- client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapreduce/lib/impl/MapReduceClientOnDefaultTable.java
- client/mapreduce/src/test/java/org/apache/accumulo/core/client/mapred/RangeInputSplitTest.java
- client/mapreduce/src/test/java/org/apache/accumulo/core/client/mapreduce/RangeInputSplitTest.java
- client/mapreduce/src/test/java/org/apache/accumulo/core/client/mapreduce/impl/BatchInputSplitTest.java
- client/mapreduce/src/test/java/org/apache/accumulo/core/client/mapreduce/lib/impl/ConfiguratorBaseTest.java
- core/src/main/java/org/apache/accumulo/core/client/impl/ConnectionInfoImpl.java
- minicluster/src/main/java/org/apache/accumulo/minicluster/impl/MiniAccumuloClusterImpl.java
- test/src/main/java/org/apache/accumulo/test/mapred/AccumuloInputFormatIT.java
- test/src/main/java/org/apache/accumulo/test/mapred/TokenFileIT.java
- test/src/main/java/org/apache/accumulo/test/mapreduce/AccumuloInputFormatIT.java
- test/src/main/java/org/apache/accumulo/test/mapreduce/TokenFileIT.java
I want to review this some more and maybe push more commits but this is ready for others to start reviewing
>  #408 - Remove deprecated ClientConfiguration from MapReduce API

- core/src/main/java/org/apache/accumulo/core/client/impl/ClientConfConverter.java
- core/src/main/java/org/apache/accumulo/core/client/impl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/client/impl/ConnectionInfoFactory.java
- core/src/test/java/org/apache/accumulo/core/client/ZooKeeperInstanceTest.java
- core/src/test/java/org/apache/accumulo/core/client/impl/ClientConfConverterTest.java
- core/src/test/java/org/apache/accumulo/core/client/impl/ClientContextTest.java
- test/src/main/java/org/apache/accumulo/test/mapred/AccumuloFileOutputFormatIT.java
- test/src/main/java/org/apache/accumulo/test/mapred/AccumuloMultiTableInputFormatIT.java
- test/src/main/java/org/apache/accumulo/test/mapred/AccumuloRowInputFormatIT.java
- test/src/main/java/org/apache/accumulo/test/mapred/TokenFileIT.java
>  #408 - Removed ClientConfiguration

- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java
Acting as proxy on behalf of @ivakegg to port changes from custom fork in order to sync up changes.
> Adding better handling of WAL close exceptions

- core/src/main/java/org/apache/accumulo/core/conf/ConfigurationDocGen.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
Also improved the document generation to use new custom Liquid tags and
fixed some HTML escaping issues.
> Updated scan executor prop docs

- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
- server/base/src/main/java/org/apache/accumulo/server/constraints/SystemConstraint.java
- server/base/src/main/java/org/apache/accumulo/server/constraints/SystemEnvironment.java
- server/base/src/test/java/org/apache/accumulo/server/constraints/MetadataConstraintsTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TservConstraintEnv.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/TservConstraintEnvTest.java
- test/src/main/java/org/apache/accumulo/test/functional/ConstraintIT.java
* Created SystemConstraint and made MetadataConstraints
extend it
* Passed ServerContext to SystemEnvironment
>  #582 - Pass ServerContext to MetadataConstraints

- core/src/main/java/org/apache/accumulo/core/data/Mutation.java
- core/src/test/java/org/apache/accumulo/core/data/MutationTest.java
> ACCUMULO-4746 Fluent API for Mutation

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
Refer to: https://github.com/apache/accumulo-website/pull/104
CC: @mikewalch
> Correct spelling in Property.java

- core/src/main/java/org/apache/accumulo/core/security/crypto/CryptoUtils.java
- core/src/main/java/org/apache/accumulo/core/security/crypto/impl/AESCryptoService.java
Removed duplicate implementations and reduced the number of calls to SecureRandom.getInstance
> Removed duplicate calls and implementation of SecureRandom

- core/src/main/java/org/apache/accumulo/core/client/ClientConfiguration.java
- core/src/main/java/org/apache/accumulo/core/client/impl/BulkSerialize.java
- core/src/main/java/org/apache/accumulo/core/client/sample/AbstractHashSampler.java
- core/src/main/java/org/apache/accumulo/core/client/summary/SummarizerConfiguration.java
- core/src/main/java/org/apache/accumulo/core/data/Value.java
- core/src/main/java/org/apache/accumulo/core/sample/impl/DataoutputHasher.java
- core/src/main/java/org/apache/accumulo/core/security/crypto/CryptoUtils.java
- core/src/main/java/org/apache/accumulo/core/summary/Gatherer.java
- core/src/main/java/org/apache/accumulo/core/util/HostAndPort.java
- core/src/main/spotbugs/exclude-filter.xml
- core/src/test/java/org/apache/accumulo/core/conf/PropertyTypeTest.java
- core/src/test/java/org/apache/accumulo/core/data/KeyBuilderTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/RFileTest.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeUtil.java
- server/base/src/test/java/org/apache/accumulo/server/util/TServerUtilsTest.java
- server/master/src/main/java/org/apache/accumulo/master/MasterTime.java
- shell/src/main/java/org/apache/accumulo/shell/Shell.java
- shell/src/main/java/org/apache/accumulo/shell/commands/ShellPluginConfigurationCommand.java
- shell/src/test/java/org/apache/accumulo/shell/ShellUtilTest.java
- test/src/main/java/org/apache/accumulo/test/ShellServerIT.java
Fix warnings from dependencies updated in #614
> Fix warnings from dependency updates

- core/src/main/java/org/apache/accumulo/core/security/crypto/impl/AESCryptoService.java
- core/src/main/java/org/apache/accumulo/core/security/crypto/impl/AESKeyUtils.java
- core/src/main/spotbugs/exclude-filter.xml
- core/src/test/java/org/apache/accumulo/core/security/crypto/CryptoTest.java
- core/src/test/resources/crypto-on-accumulo.properties
- test/src/main/java/org/apache/accumulo/test/functional/WriteAheadLogEncryptedIT.java
* Changed instance.crypto.opts.kekId -> instance.crypto.opts.key.location
* Changed instance.crypto.opts.keyManager > instance.crypto.opts.key.provider
> Rename some Crypto terms for easier configuration

- TESTING.md
- test/src/main/java/org/apache/accumulo/harness/AccumuloClusterHarness.java
Fixes to Accumulo needed to get the ITs working when I was working on https://github.com/apache/fluo-uno/pull/199
> Updates for standalone cluster

- core/src/main/java/org/apache/accumulo/core/client/ClientConfiguration.java
- pom.xml
* Update to configuration-commons 1.10
* Add deprecation notice for newly inherited method on ClientConfiguration
> Update commons-configuration to latest 1.x on branch 1.9

- server/base/src/main/java/org/apache/accumulo/server/fs/SpaceAwareVolumeChooser.java
- server/base/src/test/java/org/apache/accumulo/server/fs/SpaceAwareVolumeChooserTest.java
Create a volume chooser that uses the remaining free space on a volume to inform its choice. We have an issue on our system with unequal volume sizes that causes the smallest to fill up first.
> Add space aware volume chooser

- .travis.yml
- pom.xml
* Also have TravisCI compile with older versions of
Hadoop & Zookeeper
> Update Accumulo dependencies

- core/src/main/java/org/apache/accumulo/core/client/rfile/RFile.java
> Clarify RFile withTableProps javadoc. Fixes #611

- assemble/bin/accumulo-util
Updated script that builds native libs to work with changes in #667
> Fix script to build native libs

- core/src/main/java/org/apache/accumulo/core/client/rfile/RFile.java
- core/src/main/java/org/apache/accumulo/core/client/rfile/RFileSummariesRetriever.java
- core/src/test/java/org/apache/accumulo/core/security/crypto/CryptoTest.java
Also added summary test to CryptoTest
> Add methods to set props in Rfile summaries. Fixes #612

- core/src/main/java/org/apache/accumulo/core/security/crypto/impl/AESCryptoService.java
- core/src/main/java/org/apache/accumulo/core/security/crypto/impl/AESKeyUtils.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/RFileTest.java
- test/src/main/java/org/apache/accumulo/test/functional/WriteAheadLogEncryptedIT.java
* Removed hard coded SunJCE key provider from AESKeyUtils
* Removed key.provider property from AESCryptoService
> Remove key provider from crypto

- core/src/main/java/org/apache/accumulo/core/cli/ClientOpts.java
- core/src/main/java/org/apache/accumulo/core/client/ClientInfo.java
- core/src/main/java/org/apache/accumulo/core/client/impl/AccumuloClientImpl.java
- core/src/main/java/org/apache/accumulo/core/client/impl/ClientInfoImpl.java
- shell/src/main/java/org/apache/accumulo/shell/ShellOptionsJC.java
* Consolidated all code for reading config file into one method
> Created ClientInfo.from(configFile)

- core/src/main/java/org/apache/accumulo/core/client/impl/AccumuloClientImpl.java
- minicluster/src/main/java/org/apache/accumulo/minicluster/impl/MiniAccumuloClusterImpl.java
- server/base/src/main/java/org/apache/accumulo/server/ServerConstants.java
- server/base/src/main/java/org/apache/accumulo/server/ServerContext.java
- server/base/src/main/java/org/apache/accumulo/server/ServerInfo.java
- server/base/src/main/java/org/apache/accumulo/server/ServerUtil.java
- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
- server/base/src/test/java/org/apache/accumulo/server/AccumuloTest.java
- server/master/src/main/java/org/apache/accumulo/master/Master.java
- server/master/src/main/java/org/apache/accumulo/master/state/SetGoalState.java
- server/tracer/src/main/java/org/apache/accumulo/tracer/TraceServer.java
* Class with same name exist in core & server-base
* Renamed Accumulo class in server-base to ServerUtil
* Updated code to use Accumulo.newClient() instead of impl code
> Removed Accumulo class name conflict

- core/src/main/java/org/apache/accumulo/core/security/crypto/impl/AESKeyUtils.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/RFileTest.java
- core/src/test/java/org/apache/accumulo/core/security/crypto/CryptoTest.java
Added additional crypto unit tests including:
Test for missing KEK uri file
Test for empty KEK uri file
Test for unwrapping with an incorrect KEK
Added IllegalArgumentException to catch in AESKeyUtils.loadKekFromUri
Renamed references to KeyManager to AESKeyUtils in CryptoTest.java
> Add additional crypto unit tests

- hadoop-mapreduce/pom.xml
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/AccumuloInputFormat.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/AccumuloOutputFormat.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/AccumuloRowInputFormat.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/InputFormatBuilder.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/OutputFormatBuilder.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/InputFormatBuilderImpl.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/OutputFormatBuilderImpl.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/lib/MapReduceClientOnDefaultTable.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/lib/MapReduceClientOnRequiredTable.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapred/AccumuloFileOutputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapred/AccumuloInputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapred/AccumuloOutputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapred/AccumuloRowInputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapred/TokenFileIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/AccumuloFileOutputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/AccumuloInputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/AccumuloOutputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/AccumuloRowInputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/RowHashIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/TokenFileIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/mapred/AccumuloInputFormatTest.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/mapred/AccumuloOutputFormatTest.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/mapreduce/AccumuloInputFormatTest.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/mapreduce/AccumuloOutputFormatTest.java
> Replace ClientInfo with properties in MR

- core/src/main/java/org/apache/accumulo/core/client/mapreduce/AccumuloOutputFormat.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/mapreduce/lib/ConfiguratorBase.java
* Check is causing problems in RandomWalk test
even though job is configured correctly
> Remove unnecessary check

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientConfConverter.java
- core/src/main/java/org/apache/accumulo/core/conf/CredentialProviderFactoryShim.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/conf/SiteConfiguration.java
- core/src/test/java/org/apache/accumulo/core/conf/SiteConfigurationTest.java
- core/src/test/resources/accumulo2.properties
* Properties are stored in Map after being loaded
* Improved unit test
> Refactored SiteConfiguration

- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapred/AccumuloOutputFormat.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/AccumuloOutputFormat.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/AccumuloOutputFormatImpl.java
- minicluster/src/main/java/org/apache/accumulo/cluster/standalone/StandaloneClusterControl.java
* AccumuloOutputFormat is using wrong getClientInfo method
> Fix MapReduce bug

- server/base/src/main/java/org/apache/accumulo/server/security/SecurityOperation.java
- server/base/src/main/java/org/apache/accumulo/server/security/handler/KerberosPermissionHandler.java
- server/base/src/main/java/org/apache/accumulo/server/security/handler/PermissionHandler.java
- server/base/src/main/java/org/apache/accumulo/server/security/handler/ZKPermHandler.java
- server/master/src/main/java/org/apache/accumulo/master/Master.java
* Also remove unused initTable method
> Cleanup params in PermissionHandler

- test/src/main/java/org/apache/accumulo/test/mapreduce/MapReduceIT.java
- test/src/main/java/org/apache/accumulo/test/mapreduce/RowHash.java
- test/src/main/resources/log4j.properties
Ensure ssl parameters are properly passed from the Ssl IT to the
mapreduce client process running with ssl.
> Fix SslIT integration tests

- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapred/AccumuloOutputFormat.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/AccumuloOutputFormat.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/InputFormatBuilder.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/OutputFormatBuilder.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapred/AccumuloRecordReader.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapred/AccumuloRecordWriter.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/AccumuloRecordReader.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/AccumuloRecordWriter.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/InputFormatBuilderImpl.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/OutputFormatBuilderImpl.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/lib/ConfiguratorBase.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/lib/InputConfigurator.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/lib/OutputConfigurator.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapred/AccumuloOutputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoopImpl/mapreduce/lib/ConfiguratorBaseTest.java
* Also cleaned up new M/R API by removing unnecessary methods
and using properties in place of ClientInfo
> Fix #883 Specify client props as HDFS path in new M/R API

- server/master/src/main/java/org/apache/accumulo/master/replication/SequentialWorkAssigner.java
* Added back no-args constructor to SequentialWorkAssigner
to fix ITs
> Fix MultiInstanceReplicationIT & KerberosReplicationIT

- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
- test/src/main/java/org/apache/accumulo/test/ScanFlushWithTimeIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ConcurrencyIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SslIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SslWithClientAuthIT.java
- test/src/main/java/org/apache/accumulo/test/functional/WriteAheadLogEncryptedIT.java
* Hadoop config cannot be pulled from ServerContext if it has it has been
constructed yet
* Remove usages of scanner after it has been closed
> Fixes several ITs that are broken

- core/src/main/java/org/apache/accumulo/core/clientImpl/BaseIteratorEnvironment.java
- core/src/main/java/org/apache/accumulo/core/iterators/IteratorEnvironment.java
- iterator-test-harness/src/main/java/org/apache/accumulo/iteratortest/environments/SimpleIteratorEnvironment.java
This will help with 2.0 upgrades
> Add default impl to new IteratorEnvironment method

- core/src/main/java/org/apache/accumulo/core/client/ScannerBase.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ScannerOptions.java
- test/src/main/java/org/apache/accumulo/test/ClientSideIteratorIT.java
- test/src/main/java/org/apache/accumulo/test/ConditionalWriterIT.java
* Modified some but not all tests to use new method
> Add ScannerBase.fetchColumn/Family using CharSequence

- core/src/main/java/org/apache/accumulo/core/client/AccumuloClient.java
- core/src/main/java/org/apache/accumulo/core/client/admin/InstanceOperations.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/InstanceOperationsImpl.java
- server/master/src/main/java/org/apache/accumulo/master/replication/DistributedWorkQueueWorkAssigner.java
- server/master/src/main/java/org/apache/accumulo/master/replication/SequentialWorkAssigner.java
- server/master/src/main/java/org/apache/accumulo/master/replication/UnorderedWorkAssigner.java
- server/master/src/main/java/org/apache/accumulo/master/state/MergeStats.java
- server/master/src/test/java/org/apache/accumulo/master/replication/SequentialWorkAssignerTest.java
- server/master/src/test/java/org/apache/accumulo/master/replication/UnorderedWorkAssignerTest.java
- shell/src/main/java/org/apache/accumulo/shell/Shell.java
- test/src/main/java/org/apache/accumulo/test/BadDeleteMarkersCreatedIT.java
- test/src/main/java/org/apache/accumulo/test/ExistingMacIT.java
- test/src/main/java/org/apache/accumulo/test/ThriftServerBindsBeforeZooKeeperLockIT.java
- test/src/main/java/org/apache/accumulo/test/VolumeIT.java
- test/src/main/java/org/apache/accumulo/test/functional/AccumuloClientIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BackupMasterIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BalanceInPresenceOfOfflineTableIT.java
- test/src/main/java/org/apache/accumulo/test/functional/DynamicThreadPoolsIT.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ReadWriteIT.java
- test/src/main/java/org/apache/accumulo/test/functional/RestartIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SimpleBalancerFairnessIT.java
- test/src/main/java/org/apache/accumulo/test/functional/TableChangeStateIT.java
- test/src/main/java/org/apache/accumulo/test/functional/TabletStateChangeIteratorIT.java
- test/src/main/java/org/apache/accumulo/test/replication/MultiTserverReplicationIT.java
- test/src/main/java/org/apache/accumulo/test/replication/ReplicationIT.java
Made change that was requested.
> Move AccumuloClient.getInstanceID to InstanceOperations

- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/log.ftl
Issue 927 -  Can not clear logs on monitor in 2.0.0-alpha-2 #927
> Fixes #927 - Added 'Clear Logs' link on Recent Logs page 

- core/src/main/java/org/apache/accumulo/core/conf/ClientConfigGenerate.java
- proxy/src/main/java/org/apache/accumulo/proxy/Proxy.java
- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
- shell/src/main/java/org/apache/accumulo/shell/Shell.java
* Use Objects.requireNonNull rather than nonNull
* Close stream
* Set clientProps correctly if using mini in Proxy
> Fix minor code quality issues

- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeUtil.java
- server/base/src/main/java/org/apache/accumulo/server/master/state/TabletStateChangeIterator.java
- server/base/src/main/java/org/apache/accumulo/server/security/handler/ZKAuthorizor.java
- server/base/src/main/java/org/apache/accumulo/server/util/LoginProperties.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer1/LoadFiles.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/status/StatusResource.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/replication/AccumuloReplicaSystem.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
* Removed several cases where collections were
created and populated but never used
* Use equals() rather than == for Long equality
* Fixed log issue
> Fix code quality issues found by lgtm

- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer1/LoadFiles.java
* Added future get() calls
* Future should not return failures
Originally broken by https://github.com/apache/accumulo/commit/010d0c819194944c8d5e3201f3b82a629778bda3
> Fix BulkFileIT

- core/src/main/java/org/apache/accumulo/fate/zookeeper/ZooLock.java
- server/base/src/main/java/org/apache/accumulo/server/master/balancer/HostRegexTableLoadBalancer.java
- server/base/src/main/java/org/apache/accumulo/server/security/AuditedSecurityOperation.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/master/src/main/java/org/apache/accumulo/master/Master.java
- server/master/src/main/java/org/apache/accumulo/master/replication/RemoveCompleteReplicationRecords.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/Utils.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/replication/ReplicationProcessor.java
- shell/src/main/java/org/apache/accumulo/shell/Shell.java
* Fixed logging argument issues
* Removed null checks where never null
> Fixed code quality issues found by lgtm.com

- core/src/main/java/org/apache/accumulo/core/clientImpl/ScannerOptions.java
- core/src/main/java/org/apache/accumulo/core/crypto/streams/NoFlushOutputStream.java
- core/src/main/java/org/apache/accumulo/core/file/blockfile/impl/SeekableByteArrayInputStream.java
- core/src/main/java/org/apache/accumulo/core/file/streams/BoundedRangeFileInputStream.java
- core/src/main/java/org/apache/accumulo/core/file/streams/RateLimitedOutputStream.java
- proxy/src/main/java/org/apache/accumulo/proxy/Proxy.java
* Remove synchronized from getAuthorizations() in ScannerOptions
* Added synchronized to methods that override a sychonrized method
* Stop overriding Thread.start() in Proxy
> Fix more lgtm.com warnings

- core/src/main/java/org/apache/accumulo/core/client/BatchWriterConfig.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ConditionalWriterImpl.java
- core/src/main/java/org/apache/accumulo/core/file/streams/BoundedRangeFileInputStream.java
- core/src/main/java/org/apache/accumulo/core/iterators/system/VisibilityFilter.java
- core/src/main/java/org/apache/accumulo/core/iterators/user/VisibilityFilter.java
- core/src/test/java/org/apache/accumulo/core/data/NamespaceIdTest.java
- core/src/test/java/org/apache/accumulo/core/data/TableIdTest.java
- core/src/test/java/org/apache/accumulo/core/file/FileOperationsTest.java
- core/src/test/java/org/apache/accumulo/fate/AgeOffStoreTest.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapred/AccumuloInputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/AccumuloInputFormatIT.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
- server/base/src/main/java/org/apache/accumulo/server/ServerConstants.java
- server/base/src/main/java/org/apache/accumulo/server/rpc/TCredentialsUpdatingInvocationHandler.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/BulkImportMove.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/master/MasterResource.java
- start/src/main/java/org/apache/accumulo/start/classloader/vfs/MiniDFSUtil.java
- test/src/main/java/org/apache/accumulo/test/mapred/AccumuloInputFormatIT.java
- test/src/main/java/org/apache/accumulo/test/mapreduce/AccumuloInputFormatIT.java
* Use primitive types if variable defined with a boxed/wrapper
type is never null
> Fixed more lgtm warnings

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/master.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/navbar.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/overview.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/server.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/tservers.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/vis.js
* Removed unused variables
* Use delete only on properties
* Use === for string comparison
I ran Accumulo using Uno and the monitor worked fine after these changes.
> Fix JavaScript code quality issues

- core/src/main/java/org/apache/accumulo/core/client/mapred/AccumuloOutputFormat.java
- core/src/main/java/org/apache/accumulo/core/client/mapreduce/AccumuloOutputFormat.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapred/AccumuloRecordWriter.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/AccumuloRecordWriter.java
- shell/src/main/java/org/apache/accumulo/shell/Shell.java
* Fix if statement that is always true
* Remove resource leak
> Fix code quality issues

- test/src/main/java/org/apache/accumulo/test/functional/CreateInitialSplitsIT.java
> Simplify CreateInitialSplitsIT

- test/src/main/java/org/apache/accumulo/test/AuditMessageIT.java
- test/src/main/java/org/apache/accumulo/test/CleanWalIT.java
- test/src/main/java/org/apache/accumulo/test/ClientSideIteratorIT.java
- test/src/main/java/org/apache/accumulo/test/CloneIT.java
- test/src/main/java/org/apache/accumulo/test/CompactionRateLimitingIT.java
- test/src/main/java/org/apache/accumulo/test/ConditionalWriterIT.java
- test/src/main/java/org/apache/accumulo/test/ConfigurableMajorCompactionIT.java
- test/src/main/java/org/apache/accumulo/test/ExistingMacIT.java
- test/src/main/java/org/apache/accumulo/test/FindMaxIT.java
- test/src/main/java/org/apache/accumulo/test/ImportExportIT.java
- test/src/main/java/org/apache/accumulo/test/KeyValueEqualityIT.java
- test/src/main/java/org/apache/accumulo/test/functional/AddSplitIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BadIteratorMincIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BadLocalityGroupMincIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BatchScanSplitIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BatchWriterFlushIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BloomFilterIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ClassLoaderIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CleanTmpIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CombinerIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ConcurrentDeleteTableIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ConfigurableCompactionIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CreateAndUseIT.java
- test/src/main/java/org/apache/accumulo/test/functional/DeleteRowsIT.java
- test/src/main/java/org/apache/accumulo/test/functional/DeleteRowsSplitIT.java
- test/src/main/java/org/apache/accumulo/test/functional/DeletedTablesDontFlushIT.java
- test/src/main/java/org/apache/accumulo/test/functional/DurabilityIT.java
- test/src/main/java/org/apache/accumulo/test/functional/FateConcurrencyIT.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorIT.java
- test/src/main/java/org/apache/accumulo/test/functional/KerberosIT.java
* No need to pass in default BatchWriterConfig
> Use try-with-resources for BatchWriter

- core/src/main/java/org/apache/accumulo/core/client/summary/SummarizerConfiguration.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/lexicoder/ByteUtils.java
- core/src/main/java/org/apache/accumulo/core/iterators/conf/ColumnSet.java
- core/src/main/java/org/apache/accumulo/core/security/ColumnVisibility.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/lexicoder/ByteUtilsTest.java
- core/src/test/java/org/apache/accumulo/core/security/ColumnVisibilityTest.java
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/vis.js
* Add check and Test to prevent Array out of bounds in ByteUtils
* Add Out of bound check to ColumnSet and ColumnVisibility
* Remove unused js variable
* Suppress lgtm alert
> Fix code quality alerts found by lgtm

- core/src/main/java/org/apache/accumulo/core/client/lexicoder/UIntegerLexicoder.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ReplicationClient.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java
- core/src/main/java/org/apache/accumulo/core/file/blockfile/cache/lru/LruBlockCache.java
- core/src/main/java/org/apache/accumulo/core/file/blockfile/impl/SeekableByteArrayInputStream.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/BCFile.java
- core/src/main/java/org/apache/accumulo/fate/zookeeper/ZooSession.java
- server/base/src/main/java/org/apache/accumulo/server/ServerUtil.java
- server/master/src/main/java/org/apache/accumulo/master/metrics/Metrics2ReplicationMetrics.java
- server/master/src/main/java/org/apache/accumulo/master/metrics/ReplicationMetrics.java
- server/master/src/main/java/org/apache/accumulo/master/metrics/ReplicationMetricsMBean.java
- shell/src/main/java/org/apache/accumulo/shell/Shell.java
* Cast or replace with appropriate type to prevent overflow or data loss
> Fix implicit casts of numbers & int multiplication

- core/src/main/java/org/apache/accumulo/core/cli/ClientOpts.java
- core/src/main/java/org/apache/accumulo/core/cli/ConfigOpts.java
- core/src/test/java/org/apache/accumulo/core/cli/TestClientOpts.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/RowHashIT.java
- minicluster/src/main/java/org/apache/accumulo/cluster/AccumuloCluster.java
- minicluster/src/main/java/org/apache/accumulo/cluster/standalone/StandaloneAccumuloCluster.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
- server/base/src/main/java/org/apache/accumulo/server/cli/ServerUtilOpts.java
- server/base/src/main/java/org/apache/accumulo/server/util/RandomizeVolumes.java
- test/src/main/java/org/apache/accumulo/test/RewriteTabletDirectoriesIT.java
- test/src/main/java/org/apache/accumulo/test/TestBinaryRows.java
- test/src/main/java/org/apache/accumulo/test/TestIngest.java
- test/src/main/java/org/apache/accumulo/test/functional/DeleteIT.java
- test/src/main/java/org/apache/accumulo/test/functional/HalfDeadTServerIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ReadWriteIT.java
- test/src/main/java/org/apache/accumulo/test/functional/RestartIT.java
- test/src/main/java/org/apache/accumulo/test/functional/RestartStressIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ShutdownIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitIT.java
- test/src/main/java/org/apache/accumulo/test/mapreduce/MapReduceIT.java
- test/src/main/java/org/apache/accumulo/test/performance/RollWALPerformanceIT.java
- test/src/main/java/org/apache/accumulo/test/performance/scan/CollectTabletStats.java
- test/src/test/java/org/apache/accumulo/test/performance/scan/CollectTabletStatsTest.java
* Updated ITs given changes
* Added -o option to allow properties to be overriden
* Remove ContextOpts
> Simplified options in ClientOpts

- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/problems/ProblemsResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/util/ParameterValidator.java
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/problems.js
The Regexes in the validators in the ProblemsResource REST object had mistakes and a new regex neeed to be added.
> Fixes  #918 - Clear table problems link on monitor page do nothing.

- server/base/src/main/java/org/apache/accumulo/server/metrics/MetricsConfiguration.java
- server/master/src/main/java/org/apache/accumulo/master/state/MergeStats.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Should fix a few alerts from lgtm
> Fix some dead logic checks

- assemble/bin/accumulo
Reverting change that was causing 'accumulo' command to fail
> Fix accumulo script

- core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/BCFile.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/RFileTest.java
I tested this upgrading from 1.9-snapshot to 2.0-snapshot
> Fix NPE in BCFile. Fixes #1021

- core/src/main/java/org/apache/accumulo/fate/ZooStore.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
* Remove checks that will never be true
* Add comments for false positives
> Fix lgtm dead logic alerts

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
* Create methods for increment /decrement writes in progress. 
* Also improve some formatting
> Fix possible bug and improve errors in Tablet

- pom.xml
- server/monitor/src/main/java/org/apache/accumulo/monitor/EmbeddedWebServer.java
* Upgrade jetty to version 9.4.12.v20180830 to fix CVE-2018-12545
> Upgrade jetty to fix CVE

- test/src/main/java/org/apache/accumulo/test/functional/FateConcurrencyIT.java
- Removes NPE that sometimes caused the test to fail during release testing.
> Improve FateConcurrencyIT test

- pom.xml
- start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoader.java
Upgrade vfs2 to version 2.3 and close vfs more cleanly.
I will keep looking at this issue.
> Fix #933 RuntimeException while stopping Accumulo

- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
Fix #1087, add wrapper for FileWriter to improve IO operation performance.
> Fix #1087, wrap FileWriter with BufferedWriter

- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- test/src/main/java/org/apache/accumulo/test/TestIngest.java
- test/src/main/java/org/apache/accumulo/test/VerifyIngest.java
Also fixed a problem in VerifyIngest that I found while trying to use it for upgrade testing.
> fixes #1111 support reading unencrypted WALs from 1.9

- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/OutputFormatBuilder.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/OutputFormatBuilderImpl.java
> Remove Simulation Mode from MR API

- assemble/src/main/assemblies/component.xml
Just throwing this up as a draft in case someone else wants to look at it.  I will continue poking at it but after the change below, now the tserver won't start up.  It is failing during initialize.  This is related to the updates to commons collections 4 here: https://github.com/apache/accumulo/issues/1093
> Attempt #1 to fix Assembly runtime issues

- shell/src/main/java/org/apache/accumulo/shell/commands/ScanCommand.java
* moved ScanInterpreter into Shell
* Dropped support for ScanInterpreter
Not fully tested yet.
> Deprecate cumbersome CLI scan options

- test/src/main/java/org/apache/accumulo/test/functional/ConfigurableCompactionIT.java
- test/src/main/java/org/apache/accumulo/test/functional/LargeRowIT.java
- test/src/main/java/org/apache/accumulo/test/functional/RegexGroupBalanceIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SessionDurabilityIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitIT.java
- test/src/main/java/org/apache/accumulo/test/functional/TabletIT.java
- test/src/main/java/org/apache/accumulo/test/replication/KerberosReplicationIT.java
- test/src/main/java/org/apache/accumulo/test/replication/MultiInstanceReplicationIT.java
- test/src/main/java/org/apache/accumulo/test/replication/ReplicationIT.java
- test/src/main/java/org/apache/accumulo/test/replication/UnorderedWorkAssignerReplicationIT.java
Made requested updates and corrections.   Ran verify on the tests.  The DurabilityIT test was removed from this batch because it has it's own ticket now.
> Fix #405 Utilize NewTableConfiguration in ITs

- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- core/src/main/java/org/apache/accumulo/fate/util/Retry.java
- core/src/main/java/org/apache/accumulo/fate/zookeeper/ZooUtil.java
- core/src/test/java/org/apache/accumulo/fate/util/RetryTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
Initial implementation of solution mentioned in Issue #1119.  I am not sure how adding randomness will produce the exponential time variation @ctubbsii mentioned in the ticket but I may add randomness also if it is requested.
> Fixes #1119 - Improve Retry code

- pom.xml
Should fix github security alert
> Update jackson to 2.9.9

- test/src/main/java/org/apache/accumulo/test/functional/DurabilityIT.java
The performance aspect of this IT is being moved to accumulo-testing.
> Fixes #1159. Refactor DurabilityIT

- core/src/main/java/org/apache/accumulo/core/client/admin/NamespaceOperations.java
- core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java
Updated javadoc with the example provided by @keith-turner .  Why?  I needed something to do and I do like code examples in documentation.
> Fix #418 Javadoc updated with workaround for createIfNotExists

- core/src/main/java/org/apache/accumulo/core/client/ZooKeeperInstance.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/InstanceOperationsImpl.java
- core/src/main/java/org/apache/accumulo/fate/zookeeper/ZooUtil.java
* Create static methods in ClientContext for ZooKeeperInstance
> De-dupe some code

- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoopImpl/mapreduce/InputFormatBuilderTest.java
Unit test classLoaderContext and executionHints() functions
> Fix #811: Unit test InputFormatBuilder.java

- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/bulkImport.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/functions.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/gc.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/listType.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/master.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/overview.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/problems.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/replication.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/scans.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/server.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/show.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/summary.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/table.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/tservers.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/bulkImport.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/gc.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/listType.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/log.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/master.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/overview.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/problems.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/replication.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/scans.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/server.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/show.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/summary.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/table.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/tables.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/tservers.ftl
* Fix #475 display bulk import rows correctly
* Fix #1233 Use thead in tables in monitor page
> Some monitor javascript updates

- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
Previously said:
Bulk import  directory /tmp/concurrent_bulk/b_74f8de6ae3467fd1 does not exist!
Now says:
Bulk import  directory file:/tmp/concurrent_bulk/b_52055c2c1ec5cd73 does not exist!
> Improve Error msg on Bulk checkPath

- server/base/src/main/java/org/apache/accumulo/server/util/MasterMetadataUtil.java
Updated to use the ample api.  Also refactored to use same variable name "tablet" as mutator for consistency.
Observation:  why is it possible for some things like 'unusedwalogs' to be null but not others?
> Fix #1242 - Update MasterMetadataUtil.getUpdateForTabletDataFile

- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/TabletMutatorBase.java
- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
Updated methods listed in #1243
> Fix accumulo-1244 Update MetadataTableUtil to use the ample api

- core/src/main/java/org/apache/accumulo/core/data/AbstractId.java
- core/src/main/java/org/apache/accumulo/core/data/NamespaceId.java
- core/src/main/java/org/apache/accumulo/core/data/TableId.java
> Improve ID javadoc

- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/bulkImports/BulkImportResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/master/MasterResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/scans/ScansResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/status/StatusResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tables/TablesResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tservers/TabletServerResource.java
* Make rest calls fail fast and return empty objects
* This will make the Monitor more stable if the Master is down
> Improve error handling in Monitor. Fixes #1258

- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/log.ftl
This is a 2.0 fix but this commit is on the master branch.  If you want me to put it someplace else please let me know.
> Fix #1272 Reset navbar count for clear logs action

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/BusiestTracker.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/BusiestTrackerTest.java
This is replacement of #1187 with the following improvements : 
* Uses deltas of counters
* Refactored code so that its unit testable
* Fixed a bug with the priority queue use, it was not properly tracking the top N.
>  Improved logging of busiest tablets.

- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java
- core/src/main/java/org/apache/accumulo/core/file/FileOperations.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/bulk/BulkImportFilterInvalidTest.java
- server/master/pom.xml
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/PrepBulkImport.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
Improved some of the logging and messages during a Bulk Import.
Note that TabletServer.java came along for the ride.
> Fix #1273 Fix Bulk Messages

- core/src/main/java/org/apache/accumulo/core/cli/ClientOpts.java
- core/src/main/java/org/apache/accumulo/core/util/CreateToken.java
- core/src/test/java/org/apache/accumulo/core/cli/PasswordConverterTest.java
- core/src/test/java/org/apache/accumulo/core/cli/TestClientOpts.java
- shell/src/main/java/org/apache/accumulo/shell/ShellOptionsJC.java
The ticket seems outdated and while there is some overlap between the two classes, their use looks different enough to keep them separated. So I just unified their password handling.
> ACCUMULO-3455: ShellOptionsJC should extend ClientOpts

- test/src/main/java/org/apache/accumulo/test/continuous/BulkIngest.java
- test/src/main/java/org/apache/accumulo/test/continuous/ContinuousIngest.java
- test/src/main/java/org/apache/accumulo/test/continuous/ContinuousInputFormat.java
- test/system/continuous/continuous-env.sh.example
- test/system/continuous/ingesters.txt.example
- test/system/continuous/run-bulk-generate.sh
- test/system/continuous/run-bulk-ingest.sh
- test/system/continuous/walkers.txt.example
* Created classes for running the bulk ingest
* Created run-bulk-ingest.sh
* Also updated the example test files
> Backport BulkIngest test. Closes #1288

- core/src/main/java/org/apache/accumulo/core/clientImpl/InstanceOperationsImpl.java
Mainly java 11 readability improvements
> Various improvements to InstanceOperationsImpl

- server/master/src/main/java/org/apache/accumulo/master/TabletGroupWatcher.java
* Also make some local vars private
Noticed these while looking at #1339
> Removed unused code in TabletGroupWatcher

- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
* Closes issue #111 in accumulo-testing
https://github.com/apache/accumulo-testing/issues/111
> Fix exception handling in new Bulk Import

- core/src/main/java/org/apache/accumulo/core/cryptoImpl/AESCryptoService.java
- core/src/main/java/org/apache/accumulo/core/cryptoImpl/NoFileEncrypter.java
- core/src/main/java/org/apache/accumulo/core/data/KeyBuilder.java
- core/src/main/java/org/apache/accumulo/core/data/LoadPlan.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
- server/base/src/main/java/org/apache/accumulo/server/util/ConvertConfig.java
- server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java
- server/master/src/test/java/org/apache/accumulo/master/state/RootTabletStateStoreTest.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/MemValueTest.java
- test/src/main/java/org/apache/accumulo/test/ShellServerIT.java
Charset.forName("UTF-8") replaced with StandardCharsets.UTF_8
> Fix #1419 use StandardCharsets in more places

- assemble/pom.xml
- assemble/src/main/assemblies/component.xml
- pom.xml
- server/monitor/pom.xml
Added com.sun.xml.bind dependencies
> Fixes issue#1429

- core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftTransportPool.java
- core/src/main/java/org/apache/accumulo/core/util/Once.java
~~Note: Draft PR only, please do not merge.~~
This is my initial approach to fixing #1122. I'm making this available here for review and suggestions. I am in the process of creating unit tests as well.
> Give ThriftTransportPool higher concurrent granularity

- core/src/main/java/org/apache/accumulo/core/metadata/TabletFileUtil.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletFile.java
- server/base/src/main/java/org/apache/accumulo/server/fs/FileRef.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeManager.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeManagerImpl.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
- server/base/src/main/java/org/apache/accumulo/server/util/LocalityCheck.java
- server/base/src/main/java/org/apache/accumulo/server/util/MasterMetadataUtil.java
- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
- server/base/src/main/java/org/apache/accumulo/server/util/RemoveEntriesForMissingFiles.java
- server/base/src/test/java/org/apache/accumulo/server/fs/VolumeManagerImplTest.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/gc/src/test/java/org/apache/accumulo/gc/SimpleGarbageCollectorTest.java
- server/master/src/main/java/org/apache/accumulo/master/TabletGroupWatcher.java
- server/master/src/main/java/org/apache/accumulo/master/recovery/RecoveryManager.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer1/CopyFailed.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/tableExport/WriteExportFiles.java
- server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/TabletData.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/TabletServerSyncCheckTest.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitRecoveryIT.java
* Drop methods in VolumeManager
* Create TabletFileUtil to do path validation
> Clean up relative path code

- test/src/main/java/org/apache/accumulo/test/functional/GcMetricsIT.java
- test/src/main/java/org/apache/accumulo/test/metrics/MetricsFileTailer.java
Addresses clean-up from comments by @milleruntime in gc_metrics_backport code review (https://github.com/apache/accumulo/pull/1406) - done as a separate request to simplify merging forward into 2.1
> Clean-up / remove comments in code from gc_metrics_backport when merged.

- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeUtil.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
* Stop Tablet constructor from checking every file for volume
replacements when feature not used
> Optimize Tablet volume replacement

- assemble/bin/start-all.sh
- assemble/conf/templates/accumulo-site.xml
> Make Accumulo 1.9 compatible with ZK 3.5

- test/src/main/java/org/apache/accumulo/harness/AccumuloITBase.java
Updated default TimeoutSeconds() method to be 10 minutes
> Updated AccumuloITBase.java to enforce a default timeout

- test/src/main/java/org/apache/accumulo/test/gc/replication/CloseWriteAheadLogReferencesIT.java
- test/src/main/java/org/apache/accumulo/test/replication/CyclicReplicationIT.java
- test/src/main/java/org/apache/accumulo/test/replication/FinishedWorkUpdaterIT.java
- test/src/main/java/org/apache/accumulo/test/replication/GarbageCollectorCommunicatesWithTServersIT.java
- test/src/main/java/org/apache/accumulo/test/replication/KerberosReplicationIT.java
- test/src/main/java/org/apache/accumulo/test/replication/MultiInstanceReplicationIT.java
- test/src/main/java/org/apache/accumulo/test/replication/MultiTserverReplicationIT.java
- test/src/main/java/org/apache/accumulo/test/replication/RemoveCompleteReplicationRecordsIT.java
- test/src/main/java/org/apache/accumulo/test/replication/ReplicationIT.java
- test/src/main/java/org/apache/accumulo/test/replication/ReplicationOperationsImplIT.java
- test/src/main/java/org/apache/accumulo/test/replication/ReplicationRandomWalkIT.java
- test/src/main/java/org/apache/accumulo/test/replication/SequentialWorkAssignerIT.java
- test/src/main/java/org/apache/accumulo/test/replication/StatusCombinerMacIT.java
- test/src/main/java/org/apache/accumulo/test/replication/StatusMakerIT.java
- test/src/main/java/org/apache/accumulo/test/replication/UnorderedWorkAssignerIT.java
- test/src/main/java/org/apache/accumulo/test/replication/UnorderedWorkAssignerReplicationIT.java
- test/src/main/java/org/apache/accumulo/test/replication/UnusedWalDoesntCloseReplicationStatusIT.java
- test/src/main/java/org/apache/accumulo/test/replication/WorkMakerIT.java
Fixes #1226 Disables frequently failing CyclicReplicationIT
> Re #1492 Disable unreliable replication tests

- assemble/conf/accumulo-env.sh
Adresses #1513. The patch has been successfully tested with ZK 3.4.14 & 3.5.6.
> Support ZK 3.5 in Accumulo 2.x

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java
* Don't rename the file if it is empty
* Don't add the file to the list of files if it is empty
> Fix DatafileManager MajC for empty files. Closes #1535

- core/src/main/java/org/apache/accumulo/core/data/Condition.java
Adding an additional simplification to the equals() method of Condition.java.
> Add additional simplification to Condition.java equals() method.

- core/src/main/java/org/apache/accumulo/core/cli/ClientOpts.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/InstanceOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchDeleter.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/RFile.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/PrintInfo.java
- core/src/main/java/org/apache/accumulo/core/util/cleaner/CleanerUtil.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapred/AccumuloRowInputFormatIT.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/AccumuloRowInputFormatIT.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
- server/base/src/main/java/org/apache/accumulo/server/master/LiveTServerSet.java
- test/src/main/java/org/apache/accumulo/test/ThriftServerBindsBeforeZooKeeperLockIT.java
- test/src/main/java/org/apache/accumulo/test/mapreduce/AccumuloRowInputFormatIT.java
Implement the try-with-resources construct available in Java 7+ where applicable.
> Replace try/finally with try-with-resources.

- server/master/src/main/java/org/apache/accumulo/master/tableOps/MoveExportedFiles.java
The previous implementation would fail when an interrupted importtable
operation was retried by FATE, as it would not find (already moved)
files in the exported directory. Additionally, this commit also removes
a chatty fs.exists() check.
> Fix idempotency bug in importtable

- server/base/src/test/java/org/apache/accumulo/server/fs/FileTypeTest.java
- server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java
- server/master/src/test/java/org/apache/accumulo/master/upgrade/Upgrader9to10Test.java
* Also some minor clean up to Upgrader9to10
> Resolve relative delete markers on upgrade. Closes #1463

- minicluster/src/main/java/org/apache/accumulo/cluster/standalone/StandaloneAccumuloCluster.java
- server/base/src/main/java/org/apache/accumulo/server/ServerContext.java
- server/base/src/main/java/org/apache/accumulo/server/cli/ServerUtilOpts.java
- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
- test/src/main/java/org/apache/accumulo/test/performance/NullTserver.java
* Drop ServerContext overloaded constructors
* Create a static methods for special cases
> Some ServerContext clean up

- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
I wasn't handling arguments to the import table command properly in `TableOperationsImpl`, and a comma-delimited string of directories was captured and passed to the FATE operation in a single element `Set<String>` instead of a proper Set of multiple directories. This lead to integration test failures on Jenkins. 
This PR addresses that.
> Closes #1576 - Resolves ImportExportIT failures

- core/src/main/java/org/apache/accumulo/core/singletons/SingletonManager.java
- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
- server/base/src/main/java/org/apache/accumulo/server/util/ZooZap.java
- server/master/src/main/java/org/apache/accumulo/master/state/SetGoalState.java
This PR addresses the issue described in #1578. The code changes has been successfully tested against TLS & non-TLS configured ZK setup. Please review & let me know for any questions/suggestions. 
Like I mentioned in #1578 regarding the warning message during start/stop of services I'll create a separate issue to investigate.
> Fix Accumulo hanging when TLS enabled on ZooKeeper

- core/src/main/java/org/apache/accumulo/core/clientImpl/mapreduce/lib/InputConfigurator.java
- core/src/main/java/org/apache/accumulo/core/data/Key.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/TabletLocatorImplTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/CombinerTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/FilterTest.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/lib/InputConfigurator.java
- server/base/src/main/java/org/apache/accumulo/server/security/handler/ZKPermHandler.java
- server/base/src/test/java/org/apache/accumulo/server/security/handler/ZKAuthenticatorTest.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer1/LoadFiles.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/view/WebViews.java
- shell/src/main/java/org/apache/accumulo/shell/commands/CloneTableCommand.java
- shell/src/main/java/org/apache/accumulo/shell/commands/DeleteAuthsCommand.java
- shell/src/main/java/org/apache/accumulo/shell/commands/TableOperation.java
- test/src/main/java/org/apache/accumulo/test/VolumeChooserIT.java
- test/src/main/java/org/apache/accumulo/test/functional/VisibilityIT.java
Replace instances of copying of array contents to a collection where each element is added individually using a for loop with a call to Collections.addAll().
> Update manual array to collections copy method.

- core/src/main/java/org/apache/accumulo/core/client/rfile/RFileSummariesRetriever.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java
- core/src/main/java/org/apache/accumulo/core/conf/HadoopCredentialProvider.java
- core/src/main/java/org/apache/accumulo/core/trace/TraceUtil.java
- core/src/main/java/org/apache/accumulo/fate/zookeeper/ZooCacheFactory.java
- core/src/test/java/org/apache/accumulo/core/conf/PropertyTypeTest.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/lib/InputConfigurator.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/mapred/MultiTableInputFormatTest.java
- hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/mapreduce/MultiTableInputFormatTest.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeManagerImpl.java
- server/base/src/main/java/org/apache/accumulo/server/master/LiveTServerSet.java
- server/base/src/main/java/org/apache/accumulo/server/master/balancer/HostRegexTableLoadBalancer.java
- server/base/src/main/java/org/apache/accumulo/server/util/TableDiskUsage.java
- server/base/src/test/java/org/apache/accumulo/server/fs/PerTableVolumeChooserTest.java
- server/base/src/test/java/org/apache/accumulo/server/fs/PreferredVolumeChooserTest.java
- server/master/src/main/java/org/apache/accumulo/master/Master.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/BulkImportMove.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/LoadFiles.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/PrepBulkImport.java
- server/tracer/src/main/java/org/apache/accumulo/tracer/TraceFormatter.java
- server/tracer/src/main/java/org/apache/accumulo/tracer/TraceServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ThriftClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compaction/strategies/TooManyDeletesCompactionStrategy.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- test/src/main/java/org/apache/accumulo/test/functional/AccumuloClientIT.java
- test/src/main/java/org/apache/accumulo/test/gc/replication/CloseWriteAheadLogReferencesIT.java
- test/src/main/java/org/apache/accumulo/test/replication/ReplicationIT.java
- test/src/main/java/org/apache/accumulo/test/rpc/SimpleThriftServiceRunner.java
This ticket updates instances of lambdas which can be replaced with method references. There was also one instance of an anonymous type being replaced with a method reference.
> Lambdas replaced with method references.

- test/src/main/java/org/apache/accumulo/test/functional/GcMetricsIT.java
Added check so that the metrics timestamp must be later than test or last update
for the metrics to be valid to address issues with jenkins testing.  Concurrent
tests may still be an issue.
> Address #1591 - Improve GcMetricsIT adding timestamp check.

- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/PrepBulkImport.java
- server/master/src/test/java/org/apache/accumulo/master/tableOps/bulkVer2/PrepBulkImportTest.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkNewIT.java
* Creates the master.bulk.max.tablets property to allow restricting the
number of tablets in a single bulk import
> Create max tablets property in new bulk import

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/MinorCompactor.java
* Updated the minor compaction to gracefully handle temporary VFS class loader issues while minor compacting
> fixes #1644: minor compaction retry

- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/gc/src/test/java/org/apache/accumulo/gc/SimpleGarbageCollectorTest.java
Solution for #1543. Takes @ctubbsii  batching changes on #1441 and applying it to the SimpleGarbageCollector. I am not fully confident on my test for this feature so feadback on that will be much appreciated.
> Batching Strategy for SimpleGarbageCollector Fix #1543

- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorIT.java
GarbageCollectorIT failed after the changes from #1650. The issue was just in the expected output from the log message since that was changed.
> Fix GarbageCollectorIT

- server/master/src/main/java/org/apache/accumulo/master/Master.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionService.java
- shell/src/main/java/org/apache/accumulo/shell/commands/DeleteShellIterCommand.java
Corrected a couple of instances where logging arguments were not in agreement with the number of argument placeholders in the log statement.
Also added a minor readability update in Master.java a adding space in a phrase.
> Correct mismatched format arguments

- pom.xml
- shell/src/test/java/org/apache/accumulo/shell/ShellConfigTest.java
I thought upgrading JC was an issue but I think those problems may have been fixed since 1.71
> Update jcommander to 1.78

- core/src/main/java/org/apache/accumulo/core/client/PluginEnvironment.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/base/src/main/java/org/apache/accumulo/server/ServiceEnvironmentImpl.java
- server/base/src/test/java/org/apache/accumulo/server/ServiceEnvironmentImplTest.java
> Add method to get properties with a prefix

- core/src/main/java/org/apache/accumulo/core/client/Instance.java
- core/src/main/java/org/apache/accumulo/core/client/ZooKeeperInstance.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
- minicluster/src/main/java/org/apache/accumulo/cluster/standalone/StandaloneAccumuloCluster.java
- minicluster/src/main/java/org/apache/accumulo/cluster/standalone/StandaloneClusterControl.java
- minicluster/src/main/java/org/apache/accumulo/minicluster/MiniAccumuloConfig.java
- minicluster/src/main/java/org/apache/accumulo/minicluster/MiniAccumuloRunner.java
- minicluster/src/main/java/org/apache/accumulo/minicluster/ServerType.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterControl.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
- minicluster/src/test/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImplTest.java
- minicluster/src/test/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloConfigImplTest.java
- test/src/main/java/org/apache/accumulo/test/ThriftServerBindsBeforeZooKeeperLockIT.java
- test/src/main/java/org/apache/accumulo/test/functional/KerberosIT.java
- test/src/main/java/org/apache/accumulo/test/functional/MasterFailoverIT.java
- test/src/main/java/org/apache/accumulo/test/functional/RestartIT.java
> Deprecate Master and replace with Manager in public API

- core/src/main/java/org/apache/accumulo/core/client/mapreduce/AccumuloOutputFormat.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java
- core/src/main/java/org/apache/accumulo/core/conf/IterConfigUtil.java
- core/src/main/java/org/apache/accumulo/core/util/format/ShardedTableDistributionFormatter.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/TabletLocatorImplTest.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapred/AccumuloRecordWriter.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/AccumuloRecordWriter.java
- server/base/src/main/java/org/apache/accumulo/server/client/BulkImporter.java
- server/base/src/main/java/org/apache/accumulo/server/master/balancer/HostRegexTableLoadBalancer.java
- server/base/src/main/java/org/apache/accumulo/server/master/balancer/TableLoadBalancer.java
- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
- server/base/src/test/java/org/apache/accumulo/server/master/balancer/DefaultLoadBalancerTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/FileManager.java
Miscellaneous minor clean up found while working on unrelated code,
including:
* Using forEach loops on collections to streamline loops
* Inline one-time-use simple private methods
* Remove braces in some simple one-statement lambdas
> Clean up a few forEach loops

- core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/TableOperationsHelperTest.java
This is based on the jira ticket: https://issues.apache.org/jira/browse/ACCUMULO-3353. 
This is a goal state implementation and has its limitations as pointed out by the javadoc comment.
> Query if table is Online through Goalstate

- test/src/main/java/org/apache/accumulo/test/functional/GcMetricsIT.java
* Check the metrics sink file for the next update after the test starts,
rather than assuming two attempts are sufficient
* For the second read of the metrics sink file, get any update strictly
*after* the first update
* Don't rely on `System.currentTimeMillis()` across cores as much,
because that's not very reliable
> Fix flakey GcMetricsIT

- server/manager/src/main/java/org/apache/accumulo/master/TabletGroupWatcher.java
* For consistency and brevity in TabletGroupWatcher, stop using "this"
keyword to refer to the local reference of master
> Replace use of "this.master" with "master" in TabletGroupWatcher

- core/src/main/java/org/apache/accumulo/core/metadata/TabletFileUtil.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/AmpleImpl.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
- server/manager/src/main/java/org/apache/accumulo/master/TabletGroupWatcher.java
- server/manager/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorIT.java
* Drop static method in favor of method on the Ample interface for
creating delete mutations
* Change GarbageCollectorIT to use Ample for one of the tests
* Reuse Ample object in loops to prevent extra object creation
> Create Ample interface method for createDeleteMutation

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/Compactable.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionExecutor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionService.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/CompactionExecutorsMetrics.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerMetricsUtil.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableUtils.java
- shell/src/main/java/org/apache/accumulo/shell/commands/CompactCommand.java
- test/src/main/java/org/apache/accumulo/test/CompactionRateLimitingDeprecatedIT.java
- test/src/main/java/org/apache/accumulo/test/CompactionRateLimitingIT.java
While waiting for #1632 to be reviewed  I completed multiple follow on issues for the new compaction service.  I am submitting those as a single PR, but there is a commit for each. I can break them into multiple PRs if desired.
> Addresses four compaction service follow on issues.

- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/table.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/tables.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/tservers.ftl
* Also make the description for Ingest the same on all pages
> Improve tool tip for hold time in Monitor

- pom.xml
Support activation of skipQA profile using either of two options:
1. `-PskipQA` (existing option) OR
2. `-DskipQA` (new option in this patch)
> Make skipQA profile more human-proof

- core/src/test/java/org/apache/accumulo/core/data/RangeTest.java
- iterator-test-harness/src/main/java/org/apache/accumulo/iteratortest/testcases/InstantiationTestCase.java
- minicluster/src/main/java/org/apache/accumulo/cluster/standalone/StandaloneAccumuloCluster.java
- server/base/src/main/java/org/apache/accumulo/server/master/balancer/ChaoticLoadBalancer.java
- test/src/main/java/org/apache/accumulo/test/VolumeChooserIT.java
- test/src/main/java/org/apache/accumulo/test/functional/GcMetricsIT.java
Remove some unused code and corresponding warning suppressions.
> Remove some unused code

- server/base/src/main/java/org/apache/accumulo/server/security/SecurityOperation.java
This fixes #1827 correctly this time, after that incorrect fix was
reverted.
* Reverse order of checks, so that checking to see if a user has the
SYSTEM permission is only done if the user is not authenticating
themselves; this removes a redundant audit message indicating that the
user does not have the SYSTEM permission when it isn't necessary to
check for that in the first place
* Ensure that the current user is always authenticated first, regardless
of whether we check if the user is authenticating themselves or if
they are authenticating another user using their SYSTEM permissions
* Inline the unneeded method and add comments to significantly improve
the readability of the code
> Remove a redundant audit message

- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/overview.ftl
> Fix #1848 Update column name in the Monitor UI

- server/manager/pom.xml
- server/manager/src/main/java/org/apache/accumulo/master/metrics/fate/FateMetrics.java
- test/pom.xml
- test/src/main/java/org/apache/accumulo/test/metrics/fate/FateMetricsTest.java
- test/src/main/java/org/apache/accumulo/test/metrics/fate/InMemTestCollector.java
- test/src/main/java/org/apache/accumulo/test/zookeeper/ZooKeeperTestingServer.java
Working on zookeeper related code I wanted to use the curator testing server for tests - this moves it and tests using it to the test module.
> Move tests using curator testing server to more general package.

- server/tserver/src/main/java/org/apache/accumulo/tserver/InMemoryMap.java
> Remove obsolete TODO (#1901)

- core/src/main/java/org/apache/accumulo/fate/AdminUtil.java
- core/src/main/java/org/apache/accumulo/fate/zookeeper/ZooCache.java
- core/src/main/java/org/apache/accumulo/fate/zookeeper/ZooLock.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- test/src/main/java/org/apache/accumulo/test/functional/BackupManagerIT.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorIT.java
* Take into account the new UUID scheme when sorting ZooLock child nodes
* Fix BackupManagerIT missing slash in path to lock node
> Fix incorrect sorting of ZooLock child nodes

- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tservers/TabletServerResource.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/Compactable.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionExecutor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableUtils.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
The stats were missing from the Monitor. See #1930
> Add stats to new Compactable classes. Fixes #1930

- core/src/main/java/org/apache/accumulo/core/client/lexicoder/SequenceLexicoder.java
- core/src/test/java/org/apache/accumulo/core/file/streams/RateLimitedOutputStreamTest.java
- pom.xml
- test/src/main/java/org/apache/accumulo/test/rpc/Mocket.java
- test/src/test/java/org/apache/accumulo/test/metrics/MetricsFileTailerTest.java
* Update code for formatter changes
* Update code for new modernizer detections
> Update plugin versions

- core/src/main/java/org/apache/accumulo/core/crypto/CryptoUtils.java
- core/src/test/java/org/apache/accumulo/core/crypto/CryptoTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
* Organize some of the crypto code in anticipation of improvements
* Move some crypto logic into new CryptoUtils getFileDecrypter method
> Create CryptoUtils getFileDecrypter method

- core/src/main/spotbugs/exclude-filter.xml
- hadoop-mapreduce/src/main/spotbugs/exclude-filter.xml
- pom.xml
- start/src/main/spotbugs/exclude-filter.xml
* Update some plugins, including spotbugs
* Suppress new warnings from spotbugs that aren't important
* Update dependencies and review LICENSE/NOTICE (no change)
> Upgrade more dependencies/plugins

- minicluster/src/main/java/org/apache/accumulo/minicluster/MiniAccumuloCluster.java
- minicluster/src/main/java/org/apache/accumulo/minicluster/MiniAccumuloConfig.java
- minicluster/src/test/java/org/apache/accumulo/minicluster/MiniAccumuloClusterExistingZooKeepersTest.java
Closes #724 
Made MiniAccumuloCluster AutoClosable and made use of it by converting one of the tests to use a try-with-resouces block. A few other minor improvements were made to get this working.
> Make MiniAccumuloCluster AutoCloseable

- core/src/main/java/org/apache/accumulo/core/util/ratelimit/SharedRateLimiterFactory.java
Fixes incorrect WeakHashMap use. Fixes #1924
> Fix WeakHashMap implementation in SharedRateLimiterFactory

- core/src/test/java/org/apache/accumulo/core/data/KeyExtentTest.java
- core/src/test/java/org/apache/accumulo/core/data/MutationTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/MultiThreadedRFileTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/RelativeKeyTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/system/MultiIteratorTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/CombinerTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/IndexedDocIteratorTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/IntersectingIteratorTest.java
- server/base/src/test/java/org/apache/accumulo/server/master/balancer/GroupBalancerTest.java
- server/tracer/src/test/java/org/apache/accumulo/tracer/TracerTest.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/InMemoryMapTest.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/tablet/TabletMutationPrepAttemptTest.java
* Add Test annotations to unused methods that contain test code
* Drop unused helper methods and declarations in various Tests
> Cleanup Tests

- core/src/main/java/org/apache/accumulo/core/file/FileOperations.java
- core/src/test/java/org/apache/accumulo/core/client/security/tokens/KerberosTokenTest.java
- core/src/test/java/org/apache/accumulo/core/iterators/user/RowFilterTest.java
- core/src/test/java/org/apache/accumulo/core/util/NumUtilTest.java
- core/src/test/java/org/apache/accumulo/fate/AgeOffStoreTest.java
- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
- server/base/src/main/java/org/apache/accumulo/server/security/handler/KerberosAuthenticator.java
- server/base/src/main/java/org/apache/accumulo/server/util/FileSystemMonitor.java
- shell/src/test/java/org/apache/accumulo/shell/commands/DeleteTableCommandTest.java
- test/src/main/java/org/apache/accumulo/test/OrIteratorIT.java
- test/src/main/java/org/apache/accumulo/test/ShellServerIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ManagerMetricsIT.java
- test/src/main/java/org/apache/accumulo/test/functional/PermissionsIT.java
replace immutable HashSet usages by Set.of() to reduce code 
* adjusted imports
* closes #2040
> #2040: replace immutable HashSet by Set.of() to reduce code

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
> Renamed fields

- core/src/main/java/org/apache/accumulo/core/constraints/Constraint.java
- core/src/test/java/org/apache/accumulo/core/constraints/DeprecatedConstraintExtendTest.java
* Add method to deprecated API to prevent errors
* Add test to DeprecatedConstraintExtendTest
This should fix ShellServerIT
> Fix for Constraint API

- core/src/main/java/org/apache/accumulo/fate/Fate.java
> Fix #2078 - Marked modifier of fields store, environment and keepRunning in Fate.java as final.

- core/src/main/java/org/apache/accumulo/core/util/ConfigurationImpl.java
Related to ticket #947 
It was determined that the issue could be closed and the comment referring to the issue removed.
> Remove comment in ConfigurationImpl

- core/src/main/java/org/apache/accumulo/core/conf/ConfigurationDocGen.java
- core/src/main/spotbugs/exclude-filter.xml
- pom.xml
- server/base/src/main/java/org/apache/accumulo/server/master/balancer/HostRegexTableLoadBalancer.java
- start/src/main/spotbugs/exclude-filter.xml
- test/src/main/spotbugs/exclude-filter.xml
* Bump plugin versions to latest
* Update spotbugs filters for updated spotbugs version
* Fix spotbugs issue with non-public main class ConfigurationDocGen
* Fix checkstyle issues for updated checkstyle version
* Remove unused import
> Bump plugin versions

- assemble/src/main/scripts/create-jshell.sh
This commit contains changes to construct a client using fromClassPath() method. This PR provides an update for #1995.
> Update JShell Client Build

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
* Apply replaceAll for quotes of all parts of the default JSON values in
Property.java so they are displayed as valid JSON
* Closes #2105
> Apply replaceAll to all parts of JSON strings

- test/src/main/java/org/apache/accumulo/test/start/KeywordStartIT.java
Resolve the errors in KeywordStartIT mentioned in issue #2137.
> Add Compactor and Coordinator to testExpectedClasses in KeywordStartIT

- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader9to10.java
> Skip existing external compaction ZK nodes during upgrade

- core/src/main/java/org/apache/accumulo/core/metadata/schema/ExternalCompactionMetadata.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/CompactionJob.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/CompactionPlan.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobImpl.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionPlanImpl.java
- core/src/main/thrift-gen-java/org/apache/accumulo/core/tabletserver/thrift/TCompactionQueueSummary.java
- core/src/main/thrift/tabletserver.thrift
- core/src/test/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlannerTest.java
- core/src/test/java/org/apache/accumulo/core/util/compaction/CompactionPrioritizerTest.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/QueueAndPriority.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/QueueSummaries.java
- server/compaction-coordinator/src/test/java/org/apache/accumulo/coordinator/CompactionCoordinatorTest.java
- server/compaction-coordinator/src/test/java/org/apache/accumulo/coordinator/QueueSummariesTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/ExternalCompactionExecutor.java
- test/src/main/java/org/apache/accumulo/test/CompactionExecutorIT.java
> Change compaction priority from long to short (#2094)

- core/src/main/thrift-gen-java/org/apache/accumulo/core/compaction/thrift/CompactionCoordinatorService.java
- core/src/main/thrift/compaction-coordinator.thrift
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/DeadCompactionDetector.java
- server/compaction-coordinator/src/test/java/org/apache/accumulo/coordinator/CompactionCoordinatorTest.java
- test/src/main/java/org/apache/accumulo/test/TestCompactionCoordinator.java
> Remove UnknownCompactionIdException from Coordinator state update methods

- assemble/bin/accumulo-cluster
Found from looking into https://issues.apache.org/jira/browse/ACCUMULO-2987.
> Fix warnings in accumulo-cluster scrip

- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionManager.java
Added type property to the planner configuration to resolve
the CompactionIT failures seen in #2137
> Modify default compaction planner opts to include internal type

- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadata.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionFinalizer.java
> Adds Ample support for tablets and uses this in compaction finalizer

- core/src/main/java/org/apache/accumulo/core/file/blockfile/cache/tinylfu/TinyLfuBlockCache.java
Avoid repeated calls to policy.getMaximum() to determine the maximum
cache size from the cache eviction policy for the TinyLfu block cache
manager.
This fixes #1975
> Avoid repeated locking to get max cache size

- server/tserver/src/main/java/org/apache/accumulo/tserver/logger/LogFileKey.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/log/LogFileKeyTest.java
* Fixes #2173 failure with the decoding of row bytes
* Adds tests to LogFileKeyTest
> Adds tests to LogFileKeyTest

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/CompactRange.java
* Fixes #1919
* It is possible for a compaction to run after a table is deleted so
catch the exception and print to debug, avoiding the FATE warning
> Catch NoNodeException in CompactRange

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/test/java/org/apache/accumulo/core/conf/PropertyTest.java
- server/base/src/main/java/org/apache/accumulo/server/util/NamespacePropUtil.java
- server/base/src/main/java/org/apache/accumulo/server/util/TablePropUtil.java
- server/manager/src/main/java/org/apache/accumulo/manager/FateServiceHandler.java
- Move duplcated code for table property validation to one place
- Minor check-style fixes.
- fix possible nulll pointer warning (FateServiceHandler)
> Refactor common table property validation to reduce duplication

- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectionAlgorithm.java
Update location of TraceScope code in GarbageCollectionAlgorithm. With the GCA code now using an iterator rather tnan continue point, the seperate call to getCandidates with GCA is no longer needed as its only purpose purpose was to allow the GCE method to be traced. That method was removed. The trace was instead placed around the call to readCandidatesThatFitInMemory as that is the method responsible for collecting and batching up deletion candidates.
> Update trace code in GarbageCollectionAlgorithm

- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader.java
Capture discussion on PR #2185 to update javadoc comments.
Doc update only - contains no code changes.
> Update Upgrader interface comments to include expected system state.

- core/pom.xml
- core/src/main/java/org/apache/accumulo/core/util/CreateToken.java
- server/base/pom.xml
- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
> Fixes for #2203

- server/base/src/main/java/org/apache/accumulo/server/ServerConstants.java
- server/base/src/main/java/org/apache/accumulo/server/ServerContext.java
- server/base/src/main/java/org/apache/accumulo/server/ServerUtil.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeUtil.java
- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
- server/base/src/main/java/org/apache/accumulo/server/util/ChangeSecret.java
- server/base/src/test/java/org/apache/accumulo/server/ServerConstantsTest.java
- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/manager/src/main/java/org/apache/accumulo/manager/recovery/RecoveryManager.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer1/BulkImport.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/PrepBulkImport.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/CleanUp.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/CreateImportDir.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitRecoveryIT.java
* Remove static state from ServerConstants and remove duplicate methods
* Add final object to ServerContext for getting baseUris and volumeReplacements
* Move static methods that use Volume to ServerUtil
> Replace static state in ServerConstants

- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader9to10.java
- server/manager/src/test/java/org/apache/accumulo/manager/upgrade/Upgrader9to10Test.java
* Follow on work for #2185
* Add support for multiple volumes to upgrade code in 
Upgrader9to10 dropSortedMapWALFiles() and move
method call to upgradeZookeeper
> Rework sorted WAL Upgrade code

- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionService.java
* Split up some single lines of code to make it easier to read
* Add a comment
> Clarify some code in CompactionService

- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionService.java
* Improve readability of CompactionService by creating inner class
for the implementation of PlanningParameters
> Create inner class in CompactionService

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
* Also rename some methods in CompactableImpl
> Reword some comments to clarify

- test/src/main/java/org/apache/accumulo/test/functional/BulkIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ScanIteratorIT.java
- test/src/main/java/org/apache/accumulo/test/functional/WALSunnyDayIT.java
Add ITs for bulk import, WALs and iterators to Sunny Day profile
> Add 3 ITs to Sunny Tests. Closes #2147

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
* Also drop unnecessary boolean and add comment
> Add check for deleted Table to Tablet compactAll

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
* Populate the collection that is used to validate the external
compactions in CompactableImpl.verifyExternalCompactions() and remove
the foreach loop so an atomic boolean isn't required
> Fix check in verifyExternalCompactions

- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
- server/base/src/main/java/org/apache/accumulo/server/util/ChangeSecret.java
- server/base/src/test/java/org/apache/accumulo/server/client/BulkImporterTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/upgrade/RootFilesUpgradeTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/logger/LogReader.java
> Reduce usage of VolumeManagerImpl.get, use ServerContext.getVolumeManager instead

- shell/src/main/java/org/apache/accumulo/shell/commands/QuotedStringTokenizer.java
- shell/src/main/java/org/apache/accumulo/shell/commands/ScanCommand.java
- shell/src/test/java/org/apache/accumulo/shell/commands/ScanCommandTest.java
- test/src/main/java/org/apache/accumulo/test/ShellServerIT.java
> Added Fix for #2227

- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionExecutor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/ExternalCompactionExecutor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/InternalCompactionExecutor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/SubmittedJob.java
* Rename CompactionTask to InternalJob to be consistent with ExternalJob
* Rename some variables to match InternalJob type
* Fix some wording in comments
* Add javadoc to SubmittedJob
> Rename CompactionTask to InternalJob

- core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java
> Make threadpools marked as mutable resizeable

- core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java
- core/src/main/java/org/apache/accumulo/fate/Fate.java
- server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/InternalCompactionExecutor.java
> Resize FaTE thread pool correctly, attempt at making sure it's constantly running

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/tablet/CompactableImplFileManagerTest.java
While writing these unit test one bug was found and fixed.
This adds unit test for the changes made in #2199 plus unit test for code that existed before that.
> Adds unit test for compaction file tracking

- core/src/main/java/org/apache/accumulo/core/util/compaction/ExternalCompactionUtil.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/CompactionInputFile.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/CompactorInfo.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/Compactors.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/CoordinatorInfo.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/ECResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/ExternalCompactionInfo.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/RunningCompactions.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/RunningCompactorInfo.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/view/WebViews.java
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/ec.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/ec.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/navbar.ftl
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionTestUtils.java
* Create multiple new classes for displaying 3 different tables of data
in the new external compaction page in the monitor
* Create 3 new ajax endpoints in ECResource
* Modify Compactor and ExternalCompactionUtil to return Optional for the
compaction coordinator instead of null
* Add check for compaction coordinator to Monitor.fetchData()
* New ExternalCompactionProgressIT for testing progress
* Closes #2290
> Create page in Monitor for external compactions

- server/tserver/src/main/java/org/apache/accumulo/tserver/ThriftClientHandler.java
Fixes Accumulo #2207. Improves logging message and code comments if tablet overlap occurs.
> Improve logging message and comments if tablet overlap occurs.

- assemble/pom.xml
- assemble/src/main/assemblies/component.xml
- core/pom.xml
- core/src/main/java/org/apache/accumulo/core/file/rfile/GenerateSplits.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/PrintInfo.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/GenerateSplitsTest.java
- pom.xml
- test/src/main/java/org/apache/accumulo/test/start/KeywordStartIT.java
* New command line utility to generate splits from 1 or more rfiles
* Create new GenerateSplitsTest
* Add to KeywordStartIT
* Closes #2361
> Create GenerateSplits utility

- test/src/main/java/org/apache/accumulo/harness/SharedMiniClusterBase.java
Minor clean missed with string format clean-up pr #2384
> fix format specification from commit 6ab8d076c5

- core/src/main/java/org/apache/accumulo/core/metrics/MetricsProducer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerScanMetrics.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java
> Add metric for number of open files for scans

- core/src/main/java/org/apache/accumulo/core/file/rfile/SplitLarge.java
- test/src/main/java/org/apache/accumulo/test/start/KeywordStartIT.java
> Make SplitLarge implement KeywordExecutable

- core/src/main/java/org/apache/accumulo/core/file/rfile/CreateEmpty.java
- test/src/main/java/org/apache/accumulo/test/start/KeywordStartIT.java
> Make CreateEmpty implement KeywordExecutable

- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
> Attempt to verify that MAC processes are up and running in start

- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
Fix verifyUp method broken by #2408. The previous code attempted to use
a client singleton resource (ZooSession, created inside ZooReaderWriter)
without instantiating an AccumuloClient. This fix ensures that resource
is created after MiniAccumuloClusterImpl's ServerContext has been
created, so a client context is established before the client singleton
resource is used.
> Fix MiniAccumuloClusterImpl.verifyUp()

- core/src/main/java/org/apache/accumulo/core/protobuf/ProtobufUtil.java
- pom.xml
- server/base/src/main/java/org/apache/accumulo/server/replication/proto/Replication.java
- server/base/src/main/protobuf/replication.proto
- server/base/src/main/scripts/generate-protobuf.sh
* Second commit is the generated code
> Update protobuf to 3.19.2

- test/src/main/java/org/apache/accumulo/test/metrics/MetricsIT.java
Updated MetricsIT to account for new metrics added as part of #2405
> Fix broken MetricsIT

- core/src/main/java/org/apache/accumulo/core/metadata/schema/ExternalCompactionId.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/ExternalCompactionUtil.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/RunningCompactionInfo.java
- core/src/main/thrift-gen-java/org/apache/accumulo/core/compaction/thrift/CompactionCoordinatorService.java
- core/src/main/thrift-gen-java/org/apache/accumulo/core/compaction/thrift/CompactorService.java
- core/src/main/thrift/compaction-coordinator.thrift
- server/base/src/main/java/org/apache/accumulo/server/util/ECAdmin.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/CompactionJobHolder.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/ECResource.java
* Create a few options for external compactions
* Create new RPC calls for cancelling an external compaction
* Closes #2386
> Create new external compactions admin utility

- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
Add a trivial watcher to MiniAccumuloClusterImpl.verifyUp to avoid an
annoying ERROR coming from ZooKeeper that is logged when a ZooKeeper
client is constructed with a null Watcher.
Also address comments on #2414 to remove the redundant use of
requireNonNull for calls to Optional.get(). Instead, use a private
helper method to wait for the Process to be recorded as having a start
time, up to 10 seconds. So, instead of expecting the start time to be
non-null, it is now expected to be non-null within 10 seconds, and it
does so using Optional.isEmpty() instead of requireNonNull.
This fixes #2431
> Add trivial ZK Watcher to MiniAccumuloClusterImpl

- server/base/src/main/java/org/apache/accumulo/server/init/FileSystemInitializer.java
- server/base/src/main/java/org/apache/accumulo/server/init/InitialConfiguration.java
- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
- server/base/src/main/java/org/apache/accumulo/server/init/ZooKeeperInitializer.java
- server/base/src/test/java/org/apache/accumulo/server/init/InitializeTest.java
* Create ZooKeeperInitializer
* Create FileSystemInitializer
* Create InitialConfiguration
* Clean up code in Initialize by dropping redundant try/catch blocks,
improving error handling, passing around new InitialConfiguration object
to get config properties and improve readability
* Create new methods in Initialize: checkSASL(), checkUploadProps(), resetSecurity()
> Refactor Initialize into multiple classes

- core/src/main/java/org/apache/accumulo/core/clientImpl/CloneConfigurationImpl.java
- core/src/main/java/org/apache/accumulo/core/constraints/Constraint.java
- hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/lib/MapReduceClientOpts.java
- server/base/src/main/java/org/apache/accumulo/server/conf/codec/VersionedPropGzipCodec.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/MetaDataStateStore.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/PrintableTable.java
Added missing @Override annotations to several methods amongst six different Accumulo classes.
> Add missing @Override annotations.

- core/src/main/java/org/apache/accumulo/core/rpc/TTimeoutTransport.java
> Apply timeoutMillis to socket.connect() (#2459)

- core/src/main/java/org/apache/accumulo/fate/AgeOffStore.java
- core/src/main/java/org/apache/accumulo/fate/ReadOnlyStore.java
- core/src/main/java/org/apache/accumulo/fate/ZooStore.java
- core/src/test/java/org/apache/accumulo/fate/AgeOffStoreTest.java
- core/src/test/java/org/apache/accumulo/fate/ReadOnlyStoreTest.java
- core/src/test/java/org/apache/accumulo/fate/TestStore.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/FateIT.java
* Replace generic with ZooStore in AgeOffStore and ReadOnlyStore
* Rename SimleStore to TestStore and make it extend ZooStore
> Remove some generics from Fate implementation code

- core/src/test/java/org/apache/accumulo/core/client/ZooKeeperInstanceTest.java
- server/base/src/main/java/org/apache/accumulo/server/util/ListInstances.java
- server/base/src/test/java/org/apache/accumulo/server/util/AdminTest.java
- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/ServiceLockIT.java
- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/ZooMutatorIT.java
Noticed some places where UUID was being used where InstanceId looks appropriate
Also, some minor IDE suggested check style cleanup.
> replace minor cases of UUID with InstanceID, minor checkstyle fixes

- test/src/main/java/org/apache/accumulo/test/zookeeper/ZooKeeperTestingServer.java
> Modified ZooKeepterTestingServer to use PortUtils for finding a ZK port

- minicluster/pom.xml
- minicluster/src/main/java/org/apache/accumulo/cluster/ClusterControl.java
- minicluster/src/main/java/org/apache/accumulo/cluster/standalone/StandaloneClusterControl.java
- minicluster/src/main/java/org/apache/accumulo/minicluster/ServerType.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterControl.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloConfigImpl.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionMetricsIT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionTestUtils.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_1_IT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_2_IT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_3_IT.java
Added CompactionCoordinator and Compactor to MiniAccumuloCluster. Modified ITs
to extend SharedMiniClusterBase so that MAC was not being restarted for each
test method.
> Changes to ExternalCompaction ITs

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/cancel/CancelCompactions.java
> Revert "Synchronize method shared between FaTE ops"

- core/src/main/java/org/apache/accumulo/fate/AdminUtil.java
- server/manager/src/main/java/org/apache/accumulo/manager/util/FateAdmin.java
- shell/src/main/java/org/apache/accumulo/shell/commands/FateCommand.java
- shell/src/test/java/org/apache/accumulo/shell/commands/FateCommandTest.java
- test/src/main/java/org/apache/accumulo/test/functional/FateConcurrencyIT.java
- test/src/main/java/org/apache/accumulo/test/functional/FunctionalTestUtils.java
* Also create FateCommand test
> Refactor FateCommand to be testable

- core/src/main/java/org/apache/accumulo/core/clientImpl/ManagerClient.java
- shell/src/main/java/org/apache/accumulo/shell/commands/FateCommand.java
> Update FateCommand to use CommandLine options

- assemble/bin/accumulo-cluster
> Modified accumulo-cluster to pass -a when host is an IP address

- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionMetricsIT.java
> Refactor ExternalCompactionMetricsIT to reduce probability of timeout

- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
> Modified Initialize to add separator between root table dir and root tablet

- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/view/WebViews.java
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/debug.ftl
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/navbar.ftl
* Create a debug page on the monitor and a debug endpoint to display all
of the REST endpoints available on the monitor
* Also create a variable to store the live port number when the server
starts up
> Add debug page on Monitor

- core/src/main/java/org/apache/accumulo/core/summary/Gatherer.java
- core/src/test/java/org/apache/accumulo/core/classloader/URLClassLoaderFactory.java
- core/src/test/java/org/apache/accumulo/core/conf/ConfigurationTypeHelperTest.java
- core/src/test/java/org/apache/accumulo/core/conf/PropertyTypeTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/Compactable.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/PrintableTable.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/ScanSession.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/tablet/CompactableImplFileManagerTest.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionMetricsIT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_1_IT.java
- test/src/main/java/org/apache/accumulo/test/functional/SummaryIT.java
Various improvements of current usage of streams.
> Improvements to streams usages

- .github/workflows/maven-full-its.yaml
- .github/workflows/maven-on-demand.yaml
- .github/workflows/maven.yaml
* Bump to latest versions of actions
* Specify Java distribution explicitly
(select one that works well with Java 11 and 17)
> Update GitHub Actions workflows

- core/src/main/java/org/apache/accumulo/core/clientImpl/ServerClient.java
- core/src/main/java/org/apache/accumulo/core/rpc/TTimeoutTransport.java
- core/src/main/java/org/apache/accumulo/core/rpc/ThriftUtil.java
- server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java
Handling mirrors ThriftServer while loop handling.
Issue found while running trino + accumulo.
Resolves: #2621
> Handle thread interrupt in server client execute loop.

- server/base/src/main/java/org/apache/accumulo/server/ServerContext.java
- server/base/src/main/java/org/apache/accumulo/server/client/ClientServiceHandler.java
- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
- server/base/src/main/java/org/apache/accumulo/server/security/AuditedSecurityOperation.java
- server/base/src/main/java/org/apache/accumulo/server/security/SecurityOperation.java
- server/base/src/test/java/org/apache/accumulo/server/util/TServerUtilsTest.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/replication/ManagerReplicationCoordinator.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/clone/ClonePermissions.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/create/SetupPermissions.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/delete/CleanUp.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/namespace/create/SetupNamespacePermissions.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/namespace/delete/NamespaceCleanUp.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/ImportSetupPermissions.java
- server/manager/src/test/java/org/apache/accumulo/manager/replication/ManagerReplicationCoordinatorTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ThriftScanClientHandler.java
> Moved AuditedSecurityOperation to ServerContext

- core/src/main/java/org/apache/accumulo/core/trace/TraceUtil.java
- shell/src/main/java/org/apache/accumulo/shell/commands/TraceCommand.java
Removed TraceUtil.enable/disable and modified the Shell to
create a Tracer like a normal application would do when using
Accumulo
Closes #2623
> Modified Shell tracing to use native OpenTelemetry Tracer

- shell/src/main/java/org/apache/accumulo/shell/ShellOptionsJC.java
- test/src/main/java/org/apache/accumulo/test/ConditionalWriterIT.java
- test/src/main/java/org/apache/accumulo/test/ExistingMacIT.java
- test/src/main/java/org/apache/accumulo/test/functional/TooManyDeletesIT.java
I looked through some of the TODOs in the comments and did my best to address those that I could.
> Address TODOs found in code

- server/gc/src/main/java/org/apache/accumulo/gc/GCRun.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/gc/src/test/java/org/apache/accumulo/gc/SimpleGarbageCollectorTest.java
* Pull out the GCEnv inner class of SimpleGarbageCollector into its own
class and call it GCRun.
* Make SimpleGarbageCollector increment the current stats based on what
is returned by the GCRun class
* Changes to GCEnv (now GCRun): 
Make the stats private numbers to allow dropping of synchronized block. 
Pass in ServerContext.
Create separate logger classes for each instance Level type
Make it return the stats gathered during that run
> Create new internal GC class

- core/src/main/thrift-gen-java/org/apache/accumulo/core/gc/thrift/GcCycleStats.java
- core/src/main/thrift/gc.thrift
- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectionAlgorithm.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/gc/src/test/java/org/apache/accumulo/gc/GarbageCollectionTest.java
* Create a thrift object for counting the BLIP markers in the GC
* Modify methods in GC to return the blip count
* Update GarbageCollectionTest to count blips
* Support for #2668
> Add new blip count to GC

- .github/workflows/scripts.yaml
- assemble/bin/accumulo
- assemble/bin/accumulo-cluster
- assemble/bin/accumulo-service
- assemble/bin/accumulo-util
- assemble/build.sh
- assemble/conf/accumulo-env.sh
- assemble/src/main/scripts/create-jshell.sh
- contrib/ci/find-unapproved-chars.sh
- contrib/ci/find-unapproved-junit.sh
- contrib/ci/install-shfmt.sh
- contrib/ci/it-matrix.sh
- contrib/ci/run-shellcheck.sh
- contrib/ci/run-shfmt.sh
- core/src/main/scripts/generate-thrift.sh
- server/base/src/main/scripts/generate-protobuf.sh
- start/src/test/shell/makeHelloWorldJars.sh
- start/src/test/shell/makeTestJars.sh
- test/src/main/scripts/generate-thrift.sh
- test/src/test/scripts/run-test.sh
* Run shfmt to format scripts
* Run shellcheck to check all scripts for bugs
* Add automated check for shfmt and shellcheck during CI
> Run shfmt and shellcheck on scripts

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
> Prevent NPE in TabletServer.run by starting Thrift server after CompactionManager

- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/replication/ReplicationResource.java
> Add check for ReplicationTable online status in Monitor

- core/src/test/java/org/apache/accumulo/core/clientImpl/TabletLocatorImplTest.java
> Make variables/functions more clear in TabletLocatorImplTest

- core/src/main/java/org/apache/accumulo/fate/zookeeper/ZooCacheFactory.java
- Remove the TODO with an explanation that the class supports legacy
clients.
> Update documentation with purpose of the "cache"

- core/src/main/java/org/apache/accumulo/core/metadata/Reference.java
- core/src/main/java/org/apache/accumulo/core/metadata/RelativeTabletDirectory.java
- core/src/main/java/org/apache/accumulo/core/metadata/StoredTabletFile.java
- core/src/main/java/org/apache/accumulo/core/metadata/TabletDirectory.java
- core/src/main/java/org/apache/accumulo/core/metadata/TabletFile.java
- server/gc/src/main/java/org/apache/accumulo/gc/GCRun.java
- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectionAlgorithm.java
- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectionEnvironment.java
- server/gc/src/test/java/org/apache/accumulo/gc/GarbageCollectionTest.java
* Create TabletDirectory and RelativeTabletDirectory
* Move Reference class and improve it so other classes can be children
* Add validate method to compare what was in the metadata to what is
being used in the GC
* Use TabletDirectory in TabletFile
* Refactor some GC code
> Create TabletDirectory classes

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/functions.js
This PR changes the formatting of functions.js to conform to the jslint formatting guidelines. 
These changes include:
* Changing indentation
* Adding brackets for all if statements
* Removing else statements where not needed
* Rearranging resources so they are defined before they are used
No logic in this file should be altered by these changes.
> Format functions.js

- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
* Closes #1753
* Add check to prevent all tservers from being shutdown, unless forced
> Add safety check to Admin

- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
* Also improve stop all description
> Log error in Admin for no servers

- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/server.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/server.ftl
The changes in this PR convert the tables in server.js (which corresponds to the per server pages at http://localhost:9995/tservers?s=hostname) in the monitor.
> Convert monitor tables in server.js to DataTables

- .github/workflows/maven.yaml
- core/src/main/java/org/apache/accumulo/core/clientImpl/mapreduce/lib/ConfiguratorBase.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
- pom.xml
- server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
- server/base/src/test/java/org/apache/accumulo/server/conf/store/impl/ZooPropLoaderTest.java
- server/base/src/test/java/org/apache/accumulo/server/problems/ProblemReportTest.java
- server/base/src/test/java/org/apache/accumulo/server/security/delegation/ZooAuthenticationKeyDistributorTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/replication/SequentialWorkAssignerTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/LogSorter.java
- test/src/main/java/org/apache/accumulo/test/conf/util/TransformTokenIT.java
This bumps the version of several plugins and dependencies.
It does not address spotbugs, as that introduces a bunch of new warnings
which fails the build. So, that will be done in a separate PR.
> Bump versions

- core/src/main/java/org/apache/accumulo/core/gc/Reference.java
- core/src/main/java/org/apache/accumulo/core/gc/ReferenceDirectory.java
- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
- server/manager/src/test/java/org/apache/accumulo/manager/upgrade/Upgrader9to10Test.java
* Closes #2763
* Also fix the misplaced private String member tabletDir
> Fix Reference in TabletGroupWatcher

- server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java
- test/src/main/java/org/apache/accumulo/test/functional/ManagerApiIT.java
> Protect against error in Manager shutdownTabletServer when tserver not found

- core/src/main/java/org/apache/accumulo/core/data/ByteSequence.java
> Make ByteSequence Serializable

- core/src/main/java/org/apache/accumulo/core/client/rfile/RFileWriterBuilder.java
- core/src/main/java/org/apache/accumulo/core/gc/Reference.java
- core/src/main/java/org/apache/accumulo/core/gc/ReferenceDirectory.java
- core/src/main/java/org/apache/accumulo/core/gc/ReferenceFile.java
- core/src/main/java/org/apache/accumulo/core/metadata/TabletFile.java
- core/src/main/java/org/apache/accumulo/core/metadata/ValidationUtil.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/MetadataSchema.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/TabletFileTest.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/TabletMetadataTest.java
- server/base/src/main/java/org/apache/accumulo/server/gc/AllVolumesDirectory.java
- server/base/src/main/java/org/apache/accumulo/server/gc/GcVolumeUtil.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
- server/gc/src/main/java/org/apache/accumulo/gc/GCRun.java
- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectionAlgorithm.java
- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectionEnvironment.java
- server/gc/src/test/java/org/apache/accumulo/gc/GarbageCollectionTest.java
- server/gc/src/test/java/org/apache/accumulo/gc/SimpleGarbageCollectorTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer1/CleanUpBulkImport.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/CleanUpBulkImport.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader9to10.java
- server/manager/src/test/java/org/apache/accumulo/manager/upgrade/Upgrader9to10Test.java
- test/src/main/java/org/apache/accumulo/test/CloneIT.java
- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorIT.java
- test/src/main/java/org/apache/accumulo/test/upgrade/GCUpgrade9to10TestIT.java
* Rename Reference to ReferenceFile and make it implement a Reference interface
to be used to stream both files and directories
* Create the AllVolumesDirectory class, which extends ReferenceDirectory, to be used
for the new special encoded "agcav" volume.
* Comment and clean up GC code
> Create Reference interface for new GC classes

- assemble/bin/accumulo-cluster
- core/src/main/java/org/apache/accumulo/core/conf/cluster/ClusterConfigParser.java
- core/src/test/java/org/apache/accumulo/core/conf/cluster/ClusterConfigParserTest.java
- core/src/test/resources/org/apache/accumulo/core/conf/cluster/cluster-with-external-compactions.yaml
- core/src/test/resources/org/apache/accumulo/core/conf/cluster/cluster.yaml
Simplifies the cluster config yaml for compactor by removing redundant information.
> simplifies accumulo-cluster compactor config

- core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/CompressionAlgorithm.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/bcfile/CompressionTest.java
- core/src/test/java/org/apache/accumulo/core/file/rfile/bcfile/DummyCodec.java
Closes #2416
Co-authored-by: Damon Brown <dbrown@trietop.com>
> Computes correct override class and adds unit test for both Hadoop and System property configuration.

- core/src/main/java/org/apache/accumulo/core/logging/FateLogger.java
> Add a little more context to FateLogger messages

- pom.xml
- server/base/src/main/java/org/apache/accumulo/server/GarbageCollectionLogger.java
Updating spotbugs to current release. This does not change the error check level
Fixes new error 
```
GarbageCollectionLogger.java:[line 117] SSD_DO_NOT_USE_INSTANCE_LOCK_ON_SHARED_STATIC_DATA
```
> Spotbugs plugin update to current version 4.7.1

- core/src/main/java/org/apache/accumulo/core/logging/FateLogger.java
- core/src/main/java/org/apache/accumulo/fate/Fate.java
- core/src/main/java/org/apache/accumulo/fate/ZooStore.java
* Make the variables in Fate.java the full name of their ZK properties
* Closes #2469
> Fix name of properties in FateLogger

- core/src/main/java/org/apache/accumulo/fate/AdminUtil.java
- core/src/main/java/org/apache/accumulo/fate/Fate.java
> Change debug property name in AdminUtil

- core/src/main/java/org/apache/accumulo/fate/ZooStore.java
No code changes with this PR. Resolved https://github.com/apache/accumulo-website/issues/333 with accumulo-website PR #328 - added fate structure details.
> remove todo resolved with web #328

- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
I want to push a commit into `main`, that can be reverted later, to try and get more information about the intermittent ZK failures in the ITs.
> Added logging to try and find the cause of the intermittent ZK failures

- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
- server/base/src/main/java/org/apache/accumulo/server/util/VerifyTabletAssignments.java
> Adding VerifyTabletAssignments utility to accumulo admin command

- shell/src/main/java/org/apache/accumulo/shell/commands/ImportTableCommand.java
> Add multiple dirs description to ImportTableCommand

- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
> Modify exception handling in new ServerAmplImpl methods for ScanServers

- server/base/src/main/java/org/apache/accumulo/server/util/ZooZap.java
> Modified ZooZap to only catch thrown checked exceptions

- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
- server/base/src/main/java/org/apache/accumulo/server/util/ChangeSecret.java
> Adding ChangeSecret utility to the accumulo admin command

- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
- server/base/src/main/java/org/apache/accumulo/server/util/DeleteZooInstance.java
> Adding DeleteZooInstance utility to accumulo admin command

- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
- server/base/src/main/java/org/apache/accumulo/server/util/TabletServerLocks.java
> Adding TabletServerLocks utility to accumulo admin command

- core/src/main/java/org/apache/accumulo/core/logging/FateLogger.java
- core/src/main/java/org/apache/accumulo/fate/AdminUtil.java
- core/src/main/java/org/apache/accumulo/fate/AgeOffStore.java
- core/src/main/java/org/apache/accumulo/fate/Fate.java
- core/src/main/java/org/apache/accumulo/fate/ReadOnlyRepo.java
- core/src/main/java/org/apache/accumulo/fate/ReadOnlyStore.java
- core/src/main/java/org/apache/accumulo/fate/ReadOnlyTStore.java
- core/src/main/java/org/apache/accumulo/fate/TStore.java
- core/src/main/java/org/apache/accumulo/fate/ZooStore.java
- core/src/test/java/org/apache/accumulo/fate/ReadOnlyStoreTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/metrics/fate/FateMetricValues.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/ManagerRepo.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/TraceRepo.java
- shell/src/main/java/org/apache/accumulo/shell/commands/fateCommand/FateSummaryReport.java
- shell/src/main/java/org/apache/accumulo/shell/commands/fateCommand/FateTxnDetails.java
- shell/src/test/java/org/apache/accumulo/shell/commands/fateCommand/SummaryReportTest.java
- shell/src/test/java/org/apache/accumulo/shell/commands/fateCommand/TxnDetailsTest.java
- test/src/main/java/org/apache/accumulo/test/functional/FateConcurrencyIT.java
Also using a new enum type for the txInfo names instead of String values.
This closes #2841
> Renaming ZooStore get/set property methods to get/set transactionInfo

- test/src/main/java/org/apache/accumulo/test/ScanServerConcurrentTabletScanIT.java
- test/src/main/java/org/apache/accumulo/test/ScanServerIT.java
- test/src/main/java/org/apache/accumulo/test/ScanServerIT_NoServers.java
- test/src/main/java/org/apache/accumulo/test/ScanServerMetadataEntriesCleanIT.java
- test/src/main/java/org/apache/accumulo/test/ScanServerMetadataEntriesIT.java
- test/src/main/java/org/apache/accumulo/test/ScanServerMultipleScansIT.java
- Created variables with descriptive names to replace hardcoded numbers
- Refactored common code into methods
- Other misc. changes
> Various modifications to the scan server ITs

- core/src/main/java/org/apache/accumulo/core/clientImpl/ScanAttemptsImpl.java
> Replace use of Guava in ScanAttemptsImpl

- core/src/main/java/org/apache/accumulo/core/metadata/TabletLocationState.java
> Make Text field transient in BadLocationStateException

- core/src/main/java/org/apache/accumulo/core/metrics/MetricsUtil.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
> Narrowed exceptions thrown by MetricsUtil.initialize

- core/src/main/java/org/apache/accumulo/core/logging/FateLogger.java
- core/src/main/java/org/apache/accumulo/fate/AdminUtil.java
- core/src/main/java/org/apache/accumulo/fate/Fate.java
- server/manager/src/main/java/org/apache/accumulo/manager/FateServiceHandler.java
- server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java
- server/manager/src/main/java/org/apache/accumulo/manager/metrics/fate/FateMetricValues.java
- shell/src/main/java/org/apache/accumulo/shell/commands/fateCommand/FateSummaryReport.java
- shell/src/main/java/org/apache/accumulo/shell/commands/fateCommand/FateTxnDetails.java
- shell/src/test/java/org/apache/accumulo/shell/commands/fateCommand/SummaryReportTest.java
- shell/src/test/java/org/apache/accumulo/shell/commands/fateCommand/TxnDetailsTest.java
- test/src/main/java/org/apache/accumulo/test/fate/zookeeper/FateIT.java
- test/src/main/java/org/apache/accumulo/test/functional/FateConcurrencyIT.java
> Fix Fate operation name

- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader9to10.java
> Validate ZNode ACLs prior to upgrade, log unexpected values and fail

- assemble/pom.xml
- assemble/src/main/assemblies/component.xml
- core/pom.xml
- hadoop-mapreduce/pom.xml
- iterator-test-harness/pom.xml
- minicluster/pom.xml
- pom.xml
- server/base/pom.xml
- server/compaction-coordinator/pom.xml
- server/compactor/pom.xml
- server/gc/pom.xml
- server/manager/pom.xml
- server/monitor/pom.xml
- server/native/pom.xml
- server/tserver/pom.xml
- shell/pom.xml
- start/pom.xml
- test/pom.xml
> Update to slf4j 2.0.1

- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
- server/base/src/main/java/org/apache/accumulo/server/util/fateCommand/FateTxnDetails.java
- test/src/main/java/org/apache/accumulo/test/FateSummaryIT.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java
> Move fate summary IT from ShellServerIT to its own class

- core/src/main/java/org/apache/accumulo/core/file/rfile/GenerateSplits.java
> Fix crypto in GenerateSplits

- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
Based on a recent conversation in Slack between @keith-turner  and @ctubbsii about the behavior of ZooKeeper.sync, I looked for other places in the code where we are calling sync. This commit modifies MiniAccumuloClusterImpl.verifyUp, which uses the sync call, but doesn't wait for it to complete.
> Wait for ZooKeeper sync call to complete

- core/src/main/java/org/apache/accumulo/core/metadata/schema/MetadataSchema.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadata.java
> Add missing chopped column to Ample

- LICENSE
- server/monitor/src/main/appended-resources/META-INF/LICENSE
> Update Bootstrap and DataTables licensing

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
> Reduce compaction error to debug

- server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java
RecoveryLogsIterator was using the client side RFile scanner which does not allow for the Recovery scope to be used. This change modifies the RecoveryLogsIterator to use the server side RFile reader code (FileOperations) with the Recovery crypto environment
Closes #2979
> Use internal RFile scan code for RecoveryLogsIterator

- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
> Fixes for new Admin fate command

- LICENSE
- assemble/src/main/resources/LICENSE
- server/monitor/src/main/appended-resources/META-INF/LICENSE
This is a follow on to changes in #2957
> Remove flot plugin description from license files

- server/base/src/main/java/org/apache/accumulo/server/util/DeleteZooInstance.java
- server/base/src/main/java/org/apache/accumulo/server/util/TabletServerLocks.java
* Update DeleteZooInstance to prompt user to confirm if trying to delete the current instance
* Update TabletServerLocks to display <none> instead of null if no locks for the tablet server
This is a follow on to #2807
> Improve output and user experience of accumulo admin utilities

- test/src/main/java/org/apache/accumulo/test/ConditionalWriterIT.java
This PR attempts to resolve a TODO in ConditionalWriterIT:
> TODO verify all columns
> Resolve TODO in ConditionalWriterIT

- server/base/src/main/java/org/apache/accumulo/server/client/ClientServiceHandler.java
This cleans up the code a bit by having the validation methods just throw the permission exception instead of returning a boolean
This is a follow on to #2994
> Update permission validation methods to throw exceptions

- core/src/main/java/org/apache/accumulo/core/data/ConstraintViolationSummary.java
> Make ConstraintViolationSummary implement Serializable

- server/base/src/main/java/org/apache/accumulo/server/conf/util/ConfigTransformer.java
Fixes #3041 by checking  for upgraded props during the upgrade sequence at cluster start when the properties were previously converted with the config-upgrade utility
- includes minor check-style suggestion to factor common code in if statement path.
> fix upgrade utility - resolves #3041

- core/src/main/java/org/apache/accumulo/core/file/FileOperations.java
- core/src/main/java/org/apache/accumulo/core/file/blockfile/impl/CachableBlockFile.java
- core/src/main/java/org/apache/accumulo/core/file/rfile/RFileOperations.java
- server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/LogSorter.java
> Wire up FSDataInputStream.setDropBehind, set to true in FileCompactor

- server/base/src/main/java/org/apache/accumulo/server/rpc/CustomNonBlockingServer.java
The original implementation didn't work correctly because more than one thread will process the same FrameBuffer. This new approach captures the client address from the socket for each new FrameBuffer which is used for each request and doesn't rely on a ThreadLocal.
> Rework #3047 so that the client address is captured correctly

- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/status/StatusInformation.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/status/StatusResource.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/view/WebViews.java
- server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/ec.js
- server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/ec.ftl
Closes #3096 
Made an earlier PR (#3104) which I merged into main. This PR contains the same changes to be merged into 2.1
> Fix compaction coordinator page bug in monitor

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
Sets "X.X.X" property versions to their correct "2.1.0" context. 
closes #3085
> Add correct property versions

- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooReader.java
- server/base/src/main/java/org/apache/accumulo/server/conf/util/ZooInfoViewer.java
- server/base/src/main/java/org/apache/accumulo/server/zookeeper/ZooAclUtil.java
- server/base/src/test/java/org/apache/accumulo/server/zookeeper/ZooAclUtilTest.java
> add option to dump Zk ACls with zoo-info-viewer (#3118)

- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/ScanServerTest.java
Fixed a few bugs found when running [this test](https://gist.github.com/keith-turner/f2159111b025e600a6e0abbaba1d92f3) to exercise offline scans.
> Fixed bugs found when testing offline scans

- shell/src/main/java/org/apache/accumulo/shell/Shell.java
> Add options to JLine3 LineReader to disable highlighting and bracketed paste

- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletLocatorImpl.java
- core/src/test/java/org/apache/accumulo/core/clientImpl/TabletLocatorImplTest.java
- Fix checkstyle errors introduced in cb22cc46bb that fail build checks
- Fix other ide suggested checkstyle changes
- Replace Arrays.asList with List.of (single element replace fixes a checkstyle warning)
> fix checkstyle issues failing commit build checks and other suggestions

- core/src/main/java/org/apache/accumulo/core/client/impl/ThriftScanner.java
> Add comments found in ThriftClientHandler as to why client will wait for writes

- test/src/main/java/org/apache/accumulo/test/LargeSplitRowIT.java
- test/src/main/java/org/apache/accumulo/test/functional/KerberosRenewalIT.java
Duplicate of #3185 to get the changes into 2.1
These changes are trivial so I'll merge them once the checks pass
> Fix usage of Wait.waitFor() in ITs

- core/src/main/java/org/apache/accumulo/core/client/admin/InstanceOperations.java
Documentation update - there are no code changes with this PR
Addresses [ACCUMULO-1068](https://issues.apache.org/jira/browse/ACCUMULO-1068)
> Expand instanceOperations.getSystemConfiguration javadoc (Jira ACCUMULO-1068). 

- core/src/main/java/org/apache/accumulo/core/file/blockfile/impl/CachableBlockFile.java
- pom.xml
- server/manager/src/main/java/org/apache/accumulo/manager/recovery/RecoveryManager.java
* Narrow catch block for exception handling to only UncheckedIOException
* Fix google cache regex in checkstyle rules
> Fix minor issues for #3206

- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
Reworks time delay calculation to use delta between nano time samples.
Follow-on to #3167
> Alternate time wait calculation using nanos

- core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletLocatorImpl.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/metrics/MetricsProducer.java
- core/src/main/java/org/apache/accumulo/core/spi/ondemand/OnDemandTabletUnloader.java
- server/base/src/main/java/org/apache/accumulo/server/tables/TableManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerMetrics.java
- test/src/main/java/org/apache/accumulo/test/functional/ManagerAssignmentIT.java
- test/src/main/java/org/apache/accumulo/test/functional/TabletStateChangeIteratorIT.java
> Fix TableOperations.onDemand() javadoc

- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
Remove unused methods from MetadataTableUtil
> cleanup unused methods

- core/src/main/java/org/apache/accumulo/core/data/Range.java
These errors are present in all branches but can be merged up once this PR is merged.
> Fix Range javadoc

- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader9to10.java
Fixes error identified by updated errorprone in format string.  Identified with changes in PR #3344
> Fix positional argument in format string

- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchReaderIterator.java
> Used Retry to backoff when processing tablet locator failures

- core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/AbstractTabletStateStore.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/MetaDataStateStore.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ConditionalTabletMutatorImpl.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ConditionalTabletsMutatorImpl.java
- server/base/src/test/java/org/apache/accumulo/server/metadata/ConditionalTabletsMutatorImplTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/CleanUpBulkImport.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/LoadFiles.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/split/DeleteOperationIds.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/split/PreSplit.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/split/UpdateTablets.java
- test/src/main/java/org/apache/accumulo/test/functional/AmpleConditionalWriterIT.java
> Improves handling of conditional writer edge cases in Ample

- core/src/main/java/org/apache/accumulo/core/file/rfile/GenerateSplits.java
- pom.xml
* Migrate to datasketches-java 4.0.0
* Add more comments to explain what's going on for the next dev
> Update datasketches-java to 4.0.0

- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkSerialize.java
- core/src/main/java/org/apache/accumulo/core/lock/ServiceLockData.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/ExternalCompactionFinalState.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/ExternalCompactionMetadata.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/RootTabletMetadata.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
- core/src/main/java/org/apache/accumulo/core/spi/scan/ConfigurableScanServerSelector.java
- core/src/main/java/org/apache/accumulo/core/util/GsonSingleton.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/RootGcCandidates.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/TraceRepo.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/util/logging/AccumuloMonitorAppender.java
- test/src/main/java/org/apache/accumulo/test/CountNameNodeOpsBulkIT.java
> Create Gson singleton to use in place of new instances

- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkSerialize.java
- core/src/main/java/org/apache/accumulo/core/lock/ServiceLockData.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/ExternalCompactionFinalState.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/ExternalCompactionMetadata.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/RootTabletMetadata.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
- core/src/main/java/org/apache/accumulo/core/spi/scan/ConfigurableScanServerSelector.java
- core/src/main/java/org/apache/accumulo/core/util/LazySingletons.java
- pom.xml
- server/base/src/main/java/org/apache/accumulo/server/metadata/RootGcCandidates.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/TraceRepo.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/util/logging/AccumuloMonitorAppender.java
- test/src/main/java/org/apache/accumulo/test/CountNameNodeOpsBulkIT.java
* Create LazySingletons class to host singleton suppliers
* Add lazy GSON singleton supplier
* Replace GsonSingleton class from #3516 with this
> Make instantiating Gson singletons easier

- core/src/main/java/org/apache/accumulo/core/client/admin/NewTableConfiguration.java
- shell/src/main/java/org/apache/accumulo/shell/commands/CreateTableCommand.java
Minor IDE suggested changes.
- empty blank lines
- reassignment of a variable.
Looking at changes for issue #3233  to limit props copied, these issues were flagged in the IDE.  Submitting as a small PR to keep other changes separated.
> minor checkstyle fixes

- server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletManagementScanner.java
While running some ITs, saw an exception in the manager logs for code trying to get a value from an empty optional.  Tracked down the cause and attempted to fix.
> fixes bug in tablet mgmt scanner

- test/src/main/java/org/apache/accumulo/test/LargeSplitRowIT.java
- test/src/main/java/org/apache/accumulo/test/conf/PropStoreConfigIT.java
- test/src/main/java/org/apache/accumulo/test/conf/util/ZooPropEditorIT.java
- test/src/main/java/org/apache/accumulo/test/functional/KerberosRenewalIT.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java
- test/src/main/java/org/apache/accumulo/test/util/Wait.java
- Instead of returning a boolean with the condition status, throw an IllegalStateException if the condition
is not satisfied after the wait period expires.
- Fixes #3564
> Change Wait.waitFor to throw IllegalStateException

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
> adds logging when tablet close is waiting on a scan

- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
> Capture lock sessionId after lock acquisition for reuse

- server/base/src/main/java/org/apache/accumulo/server/util/ManagerMetadataUtil.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/UnloadTabletHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
> Uses cached tserver session id in more places

- server/base/src/main/java/org/apache/accumulo/server/conf/util/ZooPropEditor.java
Changed exit status ( From comment in PR #3620 )
> change exit error code for ZooPropEditor

- core/src/main/java/org/apache/accumulo/core/metrics/MetricsProducer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerScanMetrics.java
* Switched metric names to use dot notation.
* Refactored Scans metric to use a prefix.
* Fixed incorrect metric type in documentation
> normalize metric labels and structure

- core/src/main/java/org/apache/accumulo/core/util/compaction/ExternalCompactionUtil.java
Noticed these trying to resolve merge conflicts from a previous merge.
> trivial check style fixes noticed during previous merge

- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
> fixes merge

- core/src/main/java/org/apache/accumulo/core/clientImpl/InstanceOperationsImpl.java
- core/src/main/thrift-gen-java/org/apache/accumulo/core/tabletserver/thrift/TabletServerClientService.java
- core/src/main/thrift/tabletserver.thrift
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
- test/src/main/java/org/apache/accumulo/test/performance/NullTserver.java
Partially reverts some changes from
ec5d51803f37e062eab2ae2eb5425842b8d92cee in order to restore listing minor compactions.
Fixes #3797
> restores ability to list minor compactions

- server/base/src/main/java/org/apache/accumulo/server/metadata/ConditionalTabletMutatorImpl.java
- server/base/src/main/java/org/apache/accumulo/server/util/ManagerMetadataUtil.java
- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- test/src/main/java/org/apache/accumulo/test/ComprehensiveIT.java
- test/src/main/java/org/apache/accumulo/test/functional/AmpleConditionalWriterIT.java
Broke this work into two commits for review purposes.  The first commit refactored existing code inlining methods and variables.  The second commit is what actually switches to conditional mutations.
> Use conditional mutations for minor compactions

- test/src/main/java/org/apache/accumulo/test/ScanServerConcurrentTabletScanIT.java
- test/src/main/java/org/apache/accumulo/test/ScanServerIT.java
- test/src/main/java/org/apache/accumulo/test/ScanServerIT_NoServers.java
- test/src/main/java/org/apache/accumulo/test/ScanServerMetadataEntriesCleanIT.java
- test/src/main/java/org/apache/accumulo/test/ScanServerMetadataEntriesIT.java
- test/src/main/java/org/apache/accumulo/test/ScanServerMultipleScansIT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction4_IT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_1_IT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_2_IT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_3_IT.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkNewIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
- test/src/main/java/org/apache/accumulo/test/functional/MergeIT.java
- test/src/main/java/org/apache/accumulo/test/functional/OnDemandTabletUnloadingIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitIT.java
This reverts commit bdac4cd5b117d489d6947fc2355f87f943dcb6c5.
> Revert "Add Sunny Tag to more tests for elasticity branch (#3816)"

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
> Log tablet file differences on refresh RPC call

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/test/java/org/apache/accumulo/core/conf/PropertyTest.java
Adds a test to ensure that property descriptions either end with a period or are a one line reference to a different property.
> Adds property description formatting

- core/src/main/java/org/apache/accumulo/core/logging/TabletLogger.java
- core/src/main/java/org/apache/accumulo/core/metadata/AbstractTabletFile.java
- core/src/main/java/org/apache/accumulo/core/metadata/CompactableFileImpl.java
- core/src/main/java/org/apache/accumulo/core/metadata/TabletFile.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
- test/src/main/java/org/apache/accumulo/test/ComprehensiveIT.java
There was code that was logging only tablets file names. Now that files can have a row range, need to log it if it exists.
> logs row ranges for files that have them

- test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorIT.java
Deletes candidates if they are found prior to test. 
Replaces instances of assertTrue with assertEquals. 
Cleans up comments.
Fixes #3867
> Fixes flaky GarbageCollectorIT test

- core/src/main/java/org/apache/accumulo/core/tabletserver/log/LogEntry.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/TabletMetadataTest.java
- core/src/test/java/org/apache/accumulo/core/tabletserver/log/LogEntryTest.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeUtil.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/MetaDataStateStore.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/ZooTabletStateStore.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/TabletMutatorBase.java
- server/base/src/main/java/org/apache/accumulo/server/util/ListVolumesUsed.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- test/src/main/java/org/apache/accumulo/test/MissingWalHeaderCompletesRecoveryIT.java
- test/src/main/java/org/apache/accumulo/test/manager/MergeStateIT.java
Fixes #3878 
This is a duplicate of the changes in #3886 but applied to the main branch instead of elasticity. The changes have already been reviewed before they were merged into elasticity.
> Clean up LogEntry class

- core/src/main/java/org/apache/accumulo/core/tabletserver/log/LogEntry.java
- core/src/test/java/org/apache/accumulo/core/metadata/schema/TabletMetadataTest.java
- core/src/test/java/org/apache/accumulo/core/tabletserver/log/LogEntryTest.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/MetaDataStateStore.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/ZooTabletStateStore.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- test/src/main/java/org/apache/accumulo/test/MissingWalHeaderCompletesRecoveryIT.java
- test/src/main/java/org/apache/accumulo/test/manager/MergeStateIT.java
> Remove timestamp from LogEntry

- shell/src/main/java/org/apache/accumulo/shell/commands/GrepCommand.java
- shell/src/main/java/org/apache/accumulo/shell/commands/ScanCommand.java
Updated the IllegalArguementException message.
> Updated the IllegalArguementException message.

- core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionServicesConfig.java
Compaction planning using the new configuration prefix was not working when running in TableManagementIterator. This change fixes planning to work in this environment.
> fixes compactions planning with new prefix

- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
This fixes an edge case bug where delete rows could fail to recover if all tablets are removed during delete and the operation fails before a new default tablet can be created which will prevent the fate operatino from resuming. Instead, now if the last tablet is included in the delete range (null end row) we just keep the tablet and only remove the files and update that tablets prev end row instead of creating a new tablet which will guarantee we always have at least 1 tablet remaining and we can recover the operation if it fails at any point.
This closes #3946
> Update delete rows to be idempotent by always keeping at least 1 tablet

- test/src/main/java/org/apache/accumulo/test/ScanServerIT.java
Removing test based on discussion in #2606.
> Remove ScanServerIT.testScannerTimeout disabled test

- test/src/main/java/org/apache/accumulo/test/functional/SummaryIT.java
Increased TSERV_MAXMEM in SummaryIT based on comments in #4021 about the possibility of a minor compaction occurring and failing the test
Related to #4021
> Increase tserver maxmem in SummaryIT

- test/src/main/java/org/apache/accumulo/test/functional/FateConcurrencyIT.java
- test/src/main/java/org/apache/accumulo/test/util/SlowOps.java
SlowOps class was using getActiveCompaction(TabletServer) to check that majc was running. However, this only reports minc now as majc no longer run in the TabletServer.
> Fix FateConcurrencyIT

- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionMetricsIT.java
Fixes and enables ExternalCompactionMetricsIT
> Fix disabled CompactionITs

- core/src/main/thrift-gen-java/org/apache/accumulo/core/tabletserver/thrift/TabletServerClientService.java
- core/src/main/thrift/tabletserver.thrift
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/CleanUpBulkImport.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/LoadFiles.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- test/src/main/java/org/apache/accumulo/test/ScanConsistencyIT.java
- test/src/main/java/org/apache/accumulo/test/functional/BulkNewIT.java
- test/src/main/java/org/apache/accumulo/test/performance/NullTserver.java
Updates the bulk load code to support setting time for hosted tablets. There is still work to do to persist the changes. If tablet is unloaded uncleanly it may loose the bulk import timestamp updates.
Will make the changes for persisting in a follow on commit.
> implements setting time for hosted tablets

- test/src/main/java/org/apache/accumulo/test/compaction/CompactionConfigChangeIT.java
Modified the IT to use external compactors
> Fix CompactionConfigChangeIT

- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
Rewrites sliding window code to be more readable.  It was difficult to verify the correctness of this code via inspection.
> improves readability of code in DefaultCompactionPlanner

- test/src/main/java/org/apache/accumulo/test/functional/MergeIT.java
> Adds compaction metadata merge test

- core/src/main/java/org/apache/accumulo/core/fate/ZooStore.java
There were some changes in a PR against elasticity branch that should also make it into 2.1. [Mentioned here](https://github.com/apache/accumulo/pull/4121#discussion_r1441006495).
This PR should wait to be merged until after #4126 as there are overlapping changes. I will resolve merge conflicts on this branch once that one is merged into 2.1.
> Fix typo and add resource to try-with-resources block in ZooStore

- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionService.java
Adds a warning message when no files are being selected for compaction and the tablet's files exceed the `TSERV_SCAN_MAX_OPEN_FILES` property
This PR includes the changes from #4099 and also implements logging suppression. 
Tested this by modifying the CompactionIT test and setting `TSERV_SCAN_MAX_OPEN_FILES` to `2`.
The log message was being generated every second. 
Now, the log message is suppressed at the table level for 5 minutes. 
This PR closes #4089
> Warn when tablet needs compacting and is not

- pom.xml
- server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
There was a copy-paste error in the isSafeMode method javadoc for the return description.
> Trivial javadoc update in SimpleGarbageCollector.isSafeMode.

- test/src/main/java/org/apache/accumulo/test/LargeSplitRowIT.java
The way Accumulo finds splits in the elasticity branch changed in such a way that its finding splits points that it was not before.  This was causing LargeSplitRowIT to fail sometimes.  Adjusted to the test to work with the new way splits are found.
> fixes intermittent failure in LargeSplitRowIT

- server/manager/src/main/java/org/apache/accumulo/manager/split/SplitUtils.java
- server/manager/src/test/java/org/apache/accumulo/manager/split/SplitUtilsTest.java
When a tablet needs to split a set of split points is found.  These split points must be under a desired threshold.  The code that found these would buffer everything in memory and then remove any that were over the threshold.  This commit avoid buffering anything that is over the threshold in the first place.
Noticed this behavior while debugging #4172
> Avoids buffering large split points in memory

- assemble/src/main/resources/LICENSE
- pom.xml
Updates various dependencies, including:
- errorprone
- jackson
- micrometer
- opentelemetry
- log4j
- slf4j
- commons-cli
- commons-io
> Update various dependency versions

- assemble/conf/accumulo-env.sh
Changed from original to be off 2.1.
References #4141
> Fix paste invocation to work with Mac OS X

- test/src/main/java/org/apache/accumulo/test/fate/accumulo/AccumuloStoreReadWriteIT.java
This updates AccumuloStoreReadWriteIT deferred overflow test to use a future when calling the store runnable() method so that we can make sure the task has finished and exited the thread before continuing on with the rest of the test. This improves the test to make sure we don't have a situation where two threads are executing the runnable() method at the same time
This is a follow on to #4179
> Use future in Fate deferred overflow test

- server/base/src/main/java/org/apache/accumulo/server/util/FindCompactionTmpFiles.java
- server/base/src/main/java/org/apache/accumulo/server/util/FindOfflineTablets.java
- server/base/src/main/java/org/apache/accumulo/server/util/MetadataTableUtil.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/DeadCompactionDetector.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/goal/SetHostingGoal.java
- shell/src/main/java/org/apache/accumulo/shell/commands/GetTabletHostingGoalCommand.java
- shell/src/main/java/org/apache/accumulo/shell/commands/ListTabletsCommand.java
- test/src/main/java/org/apache/accumulo/test/ComprehensiveIT.java
- test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionTestUtils.java
- test/src/main/java/org/apache/accumulo/test/functional/AmpleConditionalWriterIT.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
- test/src/main/java/org/apache/accumulo/test/functional/FindCompactionTmpFilesIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ManagerAssignmentIT.java
- test/src/main/java/org/apache/accumulo/test/functional/SplitMillionIT.java
- test/src/main/java/org/apache/accumulo/test/functional/TabletResourceGroupBalanceIT.java
This is a continuation of #3980 fixing all the spots that were not present in main but are in elasticity.
> Cleanup usages of TabletsMetadata in elasticity

- core/src/main/java/org/apache/accumulo/core/metrics/MetricsUtil.java
Add additional comments for describing the goal of formatString
closes: #4187
> Add comments

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/CompactionCoordinatorTest.java
> Recreated compaction coordinator unit test

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
Looking at issue #4190 - noticed there is an unnecessary sync in the close method.
Also, added text to the error messages reported in the issue - the same message looks like it can occur from two places, so this may help identity where the issue is occurring.  This does not fix the issue.
> CompactableImpl sync fix and message update

- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
This test was failing because it used the old config for the default compaction planner. Updated to use the new config.
> fixes CompactionIT.testDeleteCompactionService()

- core/src/main/java/org/apache/accumulo/core/manager/state/TabletManagement.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletGoalState.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletManagementIterator.java
- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
- test/src/main/java/org/apache/accumulo/test/functional/TabletManagementIteratorIT.java
Modified the TabletManagementIterator to return NEEDS_RECOVERY when the tablet has wals and is not being deleted. Modified TabletGoalState to return the goal of HOSTED when the tablet has wals and tablet availability is UNHOSTED or ONDEMAND.
Closes #3663
> Host tablets needing recovery

- server/base/src/main/java/org/apache/accumulo/server/compaction/RetryableThriftCall.java
Drops thrift connection errors down to a `debug` level. 
On every 5th error message, the logger will elevate that message to `warn` instead of `debug`.
> Improves thrift error logging level

- test/src/main/java/org/apache/accumulo/test/functional/AmpleConditionalWriterIT.java
PR #4247 had a small bug in AmpleConditionalWriterIT. Mentioned by @dlmarion : https://github.com/apache/accumulo/pull/4247#issuecomment-1946101371
> Bug fix from PR #4247

- test/src/main/java/org/apache/accumulo/test/functional/BalanceInPresenceOfOfflineTableIT.java
BalanceInPresenceOfOfflineTableIT had the following problems
* Was testing balancing of tablets, but did nothing to explicitly
ensure tablets were hosted.  Reads and writes were done that would
cause hosting, however async split would unhost tablets and leave
them unhosted. This could cause the test to fail sometimes.
* The test seemed to expected that splits would happen in one of the
test tables it created, but never verified this.
* The test would sleep for 10s and then check for balancing.  If the
check did not find what it was looking for, it would double the time.
The doubling was unbounded, so saw the test sleep for 320s before
timing out.
The following was done to fix the problems above.
1. The two tables created by the test were set to always host tablets.
This was done because …
> fixes problems in BalanceInPresenceOfOfflineTableIT 

- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java
Use the same code as ZooKeeperInitializer to create the new accumulo.fate table
Fixes #4167
> Create accumulo.fate table during upgrade

- server/manager/src/main/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueue.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/queue/CompactionJobQueues.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueueTest.java
> Added unit test for CompactionJobPriorityQueue

- core/src/main/java/org/apache/accumulo/core/clientImpl/InstanceOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/NamespaceOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchReaderIterator.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java
- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooReader.java
- core/src/main/java/org/apache/accumulo/core/util/Retry.java
- core/src/test/java/org/apache/accumulo/core/util/RetryTest.java
- server/base/src/main/java/org/apache/accumulo/server/compaction/RetryableThriftCall.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java
> Use Duration in Retry instead of long+TimeUnit

- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
Added a counter in TableMgmtStats to help keep track of tablets that have errors while running a full scan. 
Fixes [issue#4234](https://github.com/apache/accumulo/issues/4234)
> Accumulo 4234

- test/src/main/java/org/apache/accumulo/test/fate/accumulo/AccumuloStoreIT.java
This test makes sure configuration that is relevant to the correctness of the Fate table, such as the versioning iterator, are set correctly.
This closes #4322
> Add test to verify correctness of Accumulo fate table

- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueue.java
- server/manager/src/main/java/org/apache/accumulo/manager/compaction/queue/CompactionJobQueues.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/CompactionCoordinatorTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/queue/CompactionJobPriorityQueueTest.java
- server/manager/src/test/java/org/apache/accumulo/manager/compaction/queue/CompactionJobQueuesTest.java
> removed queued jobs for a tablet if no new jobs are seen

- core/src/main/java/org/apache/accumulo/core/fate/MetaFateStore.java
- core/src/main/java/org/apache/accumulo/core/fate/user/UserFateStore.java
- test/src/main/java/org/apache/accumulo/test/fate/user/UserFateIT.java
- test/src/main/java/org/apache/accumulo/test/fate/user/UserFateStoreIT.java
closes https://github.com/apache/accumulo/issues/4389
> removes 'tx_' prefix from UserFateStore

- core/src/main/java/org/apache/accumulo/core/util/Retry.java
- core/src/test/java/org/apache/accumulo/core/util/RetryTest.java
> Add duration based maxRetries option to Retry class

- core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
- test/src/main/java/org/apache/accumulo/test/OfflineTableIT.java
Prior to elasticity a compaction or split could never run unless a tablet was hosted and how these operations can run on unhosted tablets. Taking a table offline should now wait for no OPID and ECOMP columns to exist in addition to the existing check for no location.
This addresses the first checklist item in https://github.com/apache/accumulo/issues/3412#issuecomment-1974916053
I talked to @keith-turner about this and there is likely more work to do here for addressing race conditions but this should get things most of the way and can address anything else in a follow on if needed.
> Update offline operation to wait for no opid or ecomp

- core/src/main/java/org/apache/accumulo/core/clientImpl/InstanceOperationsImpl.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/ExternalCompactionUtil.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/CoordinatorInfo.java
- server/monitor/src/main/java/org/apache/accumulo/monitor/rest/compactions/external/ExternalCompactionInfo.java
> Changed return variable for ExternalCompactionUtil.getCompactorAddrs

- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
This todo was already done in #4072
> removes TODO that is done

- test/src/main/java/org/apache/accumulo/test/functional/TabletManagementIteratorIT.java
`findTabletsNeedingAttention` now returns `Map<KeyExtent,Set<TabletManagement.ManagementAction>>` and tests now check to see if the correct Keyextent and management action is being returned. 
Fixes [Issue#4344](https://github.com/apache/accumulo/issues/4344)
> refactored findTabletsNeedingAttention test to handle new return type.

- core/src/main/java/org/apache/accumulo/core/client/admin/compaction/CompactionSelector.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/ExternalCompactionMetadata.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/CompactionKind.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/DefaultCompactionPlanner.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/DeprecatedCompactionKind.java
- core/src/test/java/org/apache/accumulo/core/util/compaction/CompactionPrioritizerTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableUtils.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/MajCEnv.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/tablet/CompactableImplFileManagerTest.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/tablet/CompactableImplTest.java
- test/src/main/java/org/apache/accumulo/test/compaction/CompactionExecutorIT.java
> Deprecates per table selector compactions

- pom.xml
> bump bouncy castle version from 1.77 to 1.78.1

- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
> Removed duplicate call to Ample.deleteScanServerFileReferences in ScanServer

- server/base/src/main/java/org/apache/accumulo/server/compaction/PausedCompactionMetrics.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServerMetrics.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ThriftScanClientHandler.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerScanMetrics.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerUpdateMetrics.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/TabletBase.java
Fixes #4540
This PR converts the usage of `Counter` to `FunctionCounter` where it makes sense.
> Convert micrometer Counters to FunctionCounters

- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- server/tserver/src/test/java/org/apache/accumulo/tserver/ScanServerTest.java
> Only allow system user to perform eventual scans on root and meta

- core/src/main/java/org/apache/accumulo/core/metrics/MetricsProducer.java
- core/src/main/java/org/apache/accumulo/core/util/compaction/RunningCompactionInfo.java
- server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerMetrics.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java
Fixes #4553 
Adds metrics for entries read and entries written.
> Add metrics for compactor entries read and write

- minicluster/src/main/java/org/apache/accumulo/cluster/ClusterControl.java
- minicluster/src/main/java/org/apache/accumulo/cluster/standalone/StandaloneClusterControl.java
- minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterControl.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- test/src/main/java/org/apache/accumulo/test/ScanServerShutdownIT.java
- test/src/main/java/org/apache/accumulo/test/SelfStoppingScanServer.java
> Added ScanServerShutdownIT to confirm refs deleted on shutdown

- server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/iterators/TabletExistsIterator.java
- test/src/main/java/org/apache/accumulo/test/functional/AmpleConditionalWriterIT.java
Ran AmpleConditionalWriterIT with code coverage and looked at what code was not covered in ConditionalTabletMutatorImpl and wrote test to cover that code.  Found a bug in
requireAbsentTablet in the process, that code was not working at all.
> adds test to cover all conditional updates and fixes bug

- test/src/main/java/org/apache/accumulo/test/functional/TabletAvailabilityIT.java
> adds tests for tablet availability boundry conditions

- test/src/main/java/org/apache/accumulo/test/PrintInfoIT.java
PrintInfoIT obtained a file from tablet metadata to open.  The path from metadata was json and this cause file open to fail.  Updated the code to get just the file path from the json.
> fixes PrintInfoIT

- core/src/main/java/org/apache/accumulo/core/fate/FateCleaner.java
- core/src/test/java/org/apache/accumulo/core/fate/FateCleanerTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
> updates FateCleaner to use SteadyTime

- server/base/src/main/java/org/apache/accumulo/server/metadata/ConditionalTabletsMutatorImpl.java
- test/src/main/resources/log4j2-test.properties
Adds logging to ample for its handling of conditional mutations that were rejected or had an unknown status.
> logs special handling of conditional mutations in ample

- core/src/main/java/org/apache/accumulo/core/util/tables/TableZooHelper.java
- server/base/src/main/java/org/apache/accumulo/server/client/ClientServiceHandler.java
- server/base/src/main/java/org/apache/accumulo/server/security/AuditedSecurityOperation.java
- server/base/src/main/java/org/apache/accumulo/server/security/SecurityOperation.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/Utils.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/clone/ClonePermissions.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/clone/CloneZookeeper.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/create/PopulateZookeeper.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/create/SetupPermissions.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/rename/RenameTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/ImportPopulateZookeeper.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/ImportSetupPermissions.java
- test/src/main/java/org/apache/accumulo/test/CreateTableIT.java
> Reduce calls to ZooCache to get table information when we already have it

- test/src/main/java/org/apache/accumulo/test/functional/BulkNewIT.java
> tests tablet availability plus bulk import

- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
This logging may be useful when debugging issues with balancing in the manager.
> adds trace logging of tserver set diffs to TGW

- test/src/main/java/org/apache/accumulo/test/ComprehensiveIT.java
Added a test to ComprehensiveIT that increases coverage of the compaction API in ComprehensiveIT.  Also increased coverage of compaction functionality based on analyzing code coverage data for CompactionDriver fate step.
> Increases compaction coverage in ComprehensiveIT

- core/src/main/java/org/apache/accumulo/core/spi/balancer/HostRegexTableLoadBalancer.java
Adds back the two log message changes that were removed when merging #4592
See #4689
> Adds back in log message changes from #4689

- core/src/main/java/org/apache/accumulo/core/conf/AccumuloConfiguration.java
- core/src/main/java/org/apache/accumulo/core/conf/ConfigurationTypeHelper.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java
> Modified Deriver to not store null result, use default in calling code

- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
> Cleans up non-existent migrating metadata tablets in manager

- test/src/main/java/org/apache/accumulo/test/functional/IdleProcessMetricsIT.java
This IT was not running correctly since being merged into elasticity.
Fixes issues related to starting the correct server types in mini accumulo. 
Also sets up the compaction service correctly and waits for the compaction to be completed.
> Fixes the IdleProcessMetricsIT

- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
* Block switching manager state to NORMAL when the goal state is specified as NORMAL, periodically logging a message about waiting (related to #2990)
* Also fix some code quality issues by removing redundant check for `oldState != newState`, using a switch statement for newState instead, and using enum equality check as `==` instead of `.equals()`
This fixes #3716
> Block changing manager NORMAL state until fate is ready

- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_3_IT.java
> Modified coordinator restart test to test compaction duration update

- core/src/test/java/org/apache/accumulo/core/iterators/system/VisibilityFilterTest.java
The unit test for VisibilityFilter was not testing caching or default visibility.  Updated to test these features and improved the coverage of the test to almost all of the code.
> improves VisibilityFilterTest

- server/base/src/main/java/org/apache/accumulo/server/metadata/ConditionalTabletMutatorImpl.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/split/FindSplits.java
- test/src/main/java/org/apache/accumulo/test/functional/AmpleConditionalWriterIT.java
Added a check in conditional update to see if the unsplittable column had changed. Updated the split code to use this check when setting the column.
> adds check for unsplittable column in conditional update

- core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionServicesConfig.java
- core/src/test/java/org/apache/accumulo/core/util/compaction/CompactionServicesConfigTest.java
Compaction related rate limiting properties were removed in #3874
> Removed code expecting compaction service rate limits

- server/base/src/main/java/org/apache/accumulo/server/conf/CheckCompactionConfig.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/UpgradeCoordinator.java
> Call CheckCompactionConfig during upgrade

- core/src/main/java/org/apache/accumulo/core/fate/ZooStore.java
- core/src/main/java/org/apache/accumulo/core/util/CountDownTimer.java
- core/src/test/java/org/apache/accumulo/core/util/CountDownTimerTest.java
Adds a class used to measure the amount of elapsed
time left from an initial duration.
> adds a new count down timer

- server/base/src/main/java/org/apache/accumulo/server/compaction/ProvisionalCompactionPlanner.java
- server/base/src/main/java/org/apache/accumulo/server/data/ServerColumnUpdate.java
- server/base/src/main/java/org/apache/accumulo/server/data/ServerConditionalMutation.java
- server/base/src/main/java/org/apache/accumulo/server/fs/FileManager.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeManager.java
- server/base/src/main/java/org/apache/accumulo/server/fs/VolumeUtil.java
- server/base/src/main/java/org/apache/accumulo/server/init/FileSystemInitializer.java
- server/base/src/main/java/org/apache/accumulo/server/log/SortedLogState.java
- server/base/src/main/java/org/apache/accumulo/server/manager/LiveTServerSet.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/LoggingTabletStateStore.java
- server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletServerState.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ConditionalTabletsMutatorImpl.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ScanServerRefStoreImpl.java
- server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java
- server/base/src/main/java/org/apache/accumulo/server/problems/ProblemReport.java
- server/base/src/main/java/org/apache/accumulo/server/problems/ProblemReportingIterator.java
- server/base/src/main/java/org/apache/accumulo/server/problems/ProblemReports.java
- server/base/src/main/java/org/apache/accumulo/server/security/delegation/AuthenticationTokenKeyManager.java
- server/base/src/main/java/org/apache/accumulo/server/security/delegation/ZooAuthenticationKeyDistributor.java
- server/base/src/main/java/org/apache/accumulo/server/tablets/ConditionCheckerContext.java
- server/base/src/main/java/org/apache/accumulo/server/tablets/TabletTime.java
- server/base/src/main/java/org/apache/accumulo/server/util/RandomWriter.java
- server/base/src/main/java/org/apache/accumulo/server/util/TableDiskUsage.java
- server/base/src/main/java/org/apache/accumulo/server/util/time/BaseRelativeTime.java
- server/base/src/main/java/org/apache/accumulo/server/util/time/RelativeTime.java
- server/base/src/main/java/org/apache/accumulo/server/zookeeper/DistributedWorkQueue.java
> Mark member variables as final in server-base

- server/tserver/src/main/java/org/apache/accumulo/tserver/BlockCacheMetrics.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/InMemoryMap.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/MemValue.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/NativeMap.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/PartialMutationSkippingIterator.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/RowLocks.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletMutations.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/TabletStatsKeeper.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/constraints/ConstraintChecker.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/constraints/UnsatisfiableConstraint.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/managermessage/TabletStatusMessage.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/scan/ScanTask.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/session/SummarySession.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/MinorCompactionTask.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/TabletBase.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/TabletMemory.java
> Mark member variables as final in tserver module

- server/tserver/src/main/java/org/apache/accumulo/tserver/memory/LargestFirstMemoryManager.java
Introduced a cache in #4853 but found that it was not needed because the code clears it on each pass through all of the tablets.  Had assumed it was a long lived cache.
> replace cache usage with a map

- server/base/src/main/java/org/apache/accumulo/server/util/TabletServerLocks.java
> Protect against null tserver lock var in TabletServerLocks

- core/src/main/java/org/apache/accumulo/core/conf/AccumuloConfiguration.java
- core/src/test/java/org/apache/accumulo/core/conf/AccumuloConfigurationTest.java
> caches duration computation in accumulo configuration

- core/src/main/java/org/apache/accumulo/core/client/ScannerBase.java
> Updates to ConsistencyLevel javadoc to provide more information

- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
The code that signals no balancing happened would sometimes skip balancing for user tablets and still signal no balancing happened. Modified to only signal when balancing had run on all levels.
> fixes bug with waitForBalance signaling

- core/src/main/java/org/apache/accumulo/core/client/admin/TabletInformation.java
> Clarified return value in TabletInformation.getLocation javadoc

- test/src/main/java/org/apache/accumulo/test/WaitForBalanceIT.java
WaitForBalanceIT was assuming that the tablets were not balanced after adding splits. In the last step of the split code, in DeleteOperationIds, the EventCoordinator is notified to try and get the new splits hosted as fast as possible. This seemed to have created a race condition in the test. Instead, this commit adds a new TabletServer which will cause a balancing to occur. I also modified the isBalanced method to take into account the tservers in the cluster, not just the location from the metadata.
> Added TabletServer in WaitForBalanceIT

- core/src/main/java/org/apache/accumulo/core/client/admin/InstanceOperations.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/InstanceOperationsImpl.java
- server/base/src/main/java/org/apache/accumulo/server/client/ClientServiceHandler.java
- shell/src/main/java/org/apache/accumulo/shell/commands/PingCommand.java
- shell/src/main/java/org/apache/accumulo/shell/commands/PingIterator.java
- test/src/main/java/org/apache/accumulo/test/InstanceOperationsIT.java
- test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java
> Expand types of servers that respond to ping command

- server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java
> Removed subprocess micrometer tag from CompactionCoordinator

- core/src/main/java/org/apache/accumulo/core/client/admin/ActiveCompaction.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ActiveCompactionImpl.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/InstanceOperationsImpl.java
- shell/src/main/java/org/apache/accumulo/shell/commands/ActiveCompactionHelper.java
- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_1_IT.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
> Deprecate CompactionHost for replacement in future version

- core/src/main/java/org/apache/accumulo/core/client/admin/ActiveCompaction.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/ActiveCompactionImpl.java
- shell/src/main/java/org/apache/accumulo/shell/commands/ActiveCompactionHelper.java
- test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
> Replaced CompactionHost with ServerId

- server/manager/src/test/java/org/apache/accumulo/manager/compaction/queue/CompactionJobQueuesTest.java
Fix testGetAsync() by ensuring that future6 will timeout before adding a job to the queue by waiting for the TimeoutException to happen and not arbitrarily sleeping. Before it was possible for the job to be added to the queue in rare cases before the timeout executed so future6 was receiving the job and not future7 which caused the test to fail.
This closes #5005
> Fix flaky CompactionJobQueuesTest

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/base/src/main/java/org/apache/accumulo/server/metrics/MetricsInfoImpl.java
> Optionally enable metrics for log4j2 or logback logging impls

- core/src/main/java/org/apache/accumulo/core/conf/cluster/ClusterConfigParser.java
- core/src/test/java/org/apache/accumulo/core/conf/cluster/ClusterConfigParserTest.java
> Restrict group names in cluster.yaml to valid bash var name characters

- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooCache.java
ZooCache currently has zero contention among threads for reads of cached data.  It did this w/ snapshots of data.  However it has two problems for updates. First there is global lock for writes.  Second writes are expensive because the snapshots for reads must be recomputed, which can lead to O(N^2) behavior for a large series of rapid small updates.
This change removes the global update lock and the snapshots and replaces them with a ConcurrentHashMap.  It also replaces the three maps that existed with a single ConcurrentHashMap that has a complex value that represented the data in the three maps.  This single complex values allows removal of the global lock which existed to keep the three maps in sync for a given path.  Now for any path all of its data is stored in a single value in the …
> improves zoocache performance

- core/src/main/java/org/apache/accumulo/core/metrics/MetricsDocGen.java
I accidentally created and merged this PR into main so am opening and merging the same changes into 3.1. These changes were going to be merged up into main anyway so no need to revert that commit.
> Add a table of contents to MetricsDocGen

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- test/src/main/java/org/apache/accumulo/test/CountNameNodeOpsBulkIT.java
> sets default limits on bulk imports files

- core/src/main/java/org/apache/accumulo/core/clientImpl/InstanceOperationsImpl.java
The test was failing because of a change in exceptions thrown.  Made the impl code throw the expected exception and made it fail faster.
> fixes InstanceOperationsIT

- test/src/main/java/org/apache/accumulo/test/VerifySerialRecoveryIT.java
This PR just adds improved logging and error messages. I was not able to reproduce the failure of this IT as observed in #5123 so improved logging will help figure out whats wrong with it the next time it fails.
> Improve VerifySerialRecoveryIT

- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/DistributedReadWriteLock.java
- server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java
> Better handling for ignored interrupted exceptions

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
> Removed experimental annotations from Compactor, ScanServer properties

- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
- server/compactor/src/test/java/org/apache/accumulo/compactor/CompactorTest.java
- server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java
> Validate group names passed in server arguments

- server/base/src/main/java/org/apache/accumulo/server/util/ListInstances.java
ServiceLock.getData uses either a ZooCache or ZooKeeper instance. Changed the utility to use a ZooKeeper instance.
Closes #5257
> Remove ZooCache from ListInstances command

- core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ServiceLock.java
- server/base/src/main/java/org/apache/accumulo/server/util/ZooZap.java
> Removed call to ServiceLock that checked lock data equivalence

- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
The changes in #5012 included a new addition to the server processes where they call setHostname(). In the Manager process this was done too early causing an invalid address being put into the ServiceLockData for the Manager.
> Fixed Manager hostname in ServiceLockData

- test/src/main/java/org/apache/accumulo/test/functional/MemoryFreeingIterator.java
- test/src/main/java/org/apache/accumulo/test/functional/MemoryStarvedScanIT.java
The IT was passing for a while, but then started failing consistently. Found that the MemoryFreeingIterator had an error in the way that it was being executed. Modified that and fixed a couple of other issues.
> Fixed MemoryStarvedScanIT

- core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java
When the close the accumulo client the following could happen.
1. THREAD1 sets closed atomic boolean to true in client as part of close() call
2. THREAD2 a background thread in transport pool tries to read property from client and gets exception because closed is true
3. THREAD1 shuts down the transport pool object as part of closing client
This change avoids throwing an exception in step 2 above.  This bug was causing MetaFateOpsCommandsIT to sometimes fail because it would have a random exception in the json the command was printing.
> fixes spurious race condition in client close

- core/src/main/java/org/apache/accumulo/core/cli/ConfigOpts.java
- core/src/test/java/org/apache/accumulo/core/cli/ConfigOptsTest.java
> Updates overrides option description, with example usage

- test/src/main/java/org/apache/accumulo/test/ImportExportIT.java
> Added import IT that uses same table name in a different namespace

- assemble/bin/accumulo-cluster
- server/base/src/main/java/org/apache/accumulo/server/util/ZooZap.java
> Added calls to ZooZap when shutting down groups of servers

- core/src/main/java/org/apache/accumulo/core/manager/balancer/BalanceParamsImpl.java
- core/src/main/java/org/apache/accumulo/core/spi/balancer/BalancerEnvironment.java
- core/src/main/java/org/apache/accumulo/core/spi/balancer/HostRegexTableLoadBalancer.java
- core/src/main/java/org/apache/accumulo/core/spi/balancer/TableLoadBalancer.java
- core/src/main/java/org/apache/accumulo/core/spi/balancer/TabletBalancer.java
- core/src/test/java/org/apache/accumulo/core/spi/balancer/GroupBalancerTest.java
- core/src/test/java/org/apache/accumulo/core/spi/balancer/HostRegexTableLoadBalancerReconfigurationTest.java
- core/src/test/java/org/apache/accumulo/core/spi/balancer/HostRegexTableLoadBalancerTest.java
- core/src/test/java/org/apache/accumulo/core/spi/balancer/SimpleLoadBalancerTest.java
- core/src/test/java/org/apache/accumulo/core/spi/balancer/TableLoadBalancerTest.java
- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
- test/src/main/java/org/apache/accumulo/test/BalanceIT.java
- test/src/test/java/org/apache/accumulo/test/ChaoticLoadBalancerTest.java
This PR is a subset of tested changes from #5195. 
The goal being that the string based partition balancing changes are the only changes left in #5195 once this PR is merged into 2.1.
> Fixes metadata balancing issues

- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/LoadFiles.java
- server/manager/src/test/java/org/apache/accumulo/manager/tableOps/bulkVer2/LoadFilesTest.java
When merging #5355 to main the FILES column ended up not being fetched for the tablet metadata because the Loader.pauseLimit variable had not been set. This variable was set in the call to Loader.start, which happens after the TabletsMetadata is configured
> Fixed error caused during merge of #5355 to main

- core/src/main/java/org/apache/accumulo/core/rpc/TraceProtocolFactory.java
Trace data for RPCs would include an empty string for the class name because TraceProtocolFactory created an anonymous class.  Changed to use a named class to make linking trace data to code easier.
> Fixes class name in trace data

- server/gc/src/main/java/org/apache/accumulo/gc/GCRun.java
- server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectionAlgorithm.java
- server/gc/src/test/java/org/apache/accumulo/gc/SimpleGarbageCollectorTest.java
Adds batch counter to log messages.
Adds in-progress counters to long-running methods.
> Adds batch information to GC logging

- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction_2_IT.java
> adds IT to verify external compactions can interrupt threads

- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompaction4_IT.java
readds new test from 2.1 in a different place
> adds IT to verify external compactions can interrupt threads (#5412)

- test/src/main/java/org/apache/accumulo/test/functional/AmpleConditionalWriterIT.java
The testRootTabletUpdate test was setting an operationId on the root tablet, which ends up causing the tablet to become unhosted causing the remaining tests to time out. Added code to the test to unset the operationId and set a future location for the root tablet so that it will once again be hosted.
Closes #5440
> Fixed testRootTabletUpdate test method to re-host root tablet

- assemble/bin/accumulo-service
Adds improved list output and cleanup of dead pid files.
Ported changes from #5439
> Improves accumulo-service script

- core/src/main/java/org/apache/accumulo/core/spi/balancer/HostRegexTableLoadBalancer.java
Wanted to know how much time the HostRegexTableLoadBalancer was spending on each table.  Added some trace logging to provide this information.
Tested this by running unit test for the class and inspecting the log messages.
> Adds per table trace logging to HostRegexTableLoadBalancer

- test/src/main/java/org/apache/accumulo/test/ZombieScanIT.java
Been noticing this IT timeout for a while on Jenkins on the Wait.waitFor() calls.
Increased max wait times of waiting for a condition. Some of these waits were taking 10-15 seconds locally. Possible these were taking more than the configured 30 seconds in Jenkins due to fewer resources.
Did not look into testing logic. This may very well not fix the issue, but would be simple to merge and see if it the issue is resolved.
> Potential fix for ZombieScanIT

- core/src/main/java/org/apache/accumulo/core/client/rfile/RFile.java
- core/src/main/java/org/apache/accumulo/core/iterators/IteratorEnvironment.java
- core/src/main/java/org/apache/accumulo/core/iteratorsImpl/ClientIteratorEnvironment.java
- test/src/main/java/org/apache/accumulo/test/IteratorEnvIT.java
- Improved IteratorEnvIT:
- Added means of verifying that the checks done in testEnv() actually ran
- Added testing for more usages of IteratorEnvironment, specifically all usages of the new ClientIteratorEnvironment
- Added more env tests in testEnv()
- Avoid repeated strings throughout IT
- Simplified assertions (can simply use junit assertions as assertions work outside of testing process)
- Fixed some of the bugs found with new ClientIteratorEnvironment when adding more testing
- Javadoc fixes and improvements
closes #5504
> IteratorEnvironment bug fixes and improved testing

- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
Migration cleanup was attempting to get the location from the tablet metadata without first fetching the location column.
> Fixes bug introduced in #5416

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionFinalizer.java
- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/DeadCompactionDetector.java
- server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java
Adds logging messages for additional troubleshooting of external compactions. 
Adds a new property for configuring the maxThreads of the Compaction-coordinator summaries threadpool. 
Also allows compaction-coordinator properties to be set via ZK.
> Adds logging and new property for compaction-coordinator

- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
Related to #5520 and #5604
Applies the HasMigrationFilter in more places (now applied everywhere we are getting migrations in Manager), remove the checks for a null migration (handled by the filter), ~~bug fix for one location not fetching the LOCATION column when it needs to.~~
> Migrations access related improvements

- server/base/src/main/java/org/apache/accumulo/server/manager/state/MetaDataTableScanner.java
- server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java
Adds debug info message for showing options size.
Adds debug messages for showing assignment times.
> Adds more timing logging for tablet assignment

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
also looked over all the other since 4.0.0 props for other typos. Rest are okay
this is fine to change now since this is a 4.0.0 prop
> fix minor typo with 4.0.0 prop

- core/src/main/java/org/apache/accumulo/core/client/PluginEnvironment.java
- core/src/main/java/org/apache/accumulo/core/client/admin/ActiveCompaction.java
- core/src/main/java/org/apache/accumulo/core/client/admin/InstanceOperations.java
- core/src/main/java/org/apache/accumulo/core/client/admin/compaction/CompactableFile.java
- core/src/main/java/org/apache/accumulo/core/client/admin/compaction/CompactionConfigurer.java
- core/src/main/java/org/apache/accumulo/core/client/rfile/RFile.java
- core/src/main/java/org/apache/accumulo/core/client/rfile/RFileSource.java
- core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java
- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/main/java/org/apache/accumulo/core/data/ArrayByteSequence.java
- core/src/main/java/org/apache/accumulo/core/data/Key.java
- core/src/main/java/org/apache/accumulo/core/data/KeyBuilder.java
- core/src/main/java/org/apache/accumulo/core/file/blockfile/cache/lru/LruBlockCacheManager.java
- core/src/main/java/org/apache/accumulo/core/metadata/schema/MetadataSchema.java
- core/src/main/java/org/apache/accumulo/core/security/Authorizations.java
- core/src/main/java/org/apache/accumulo/core/security/ColumnVisibility.java
- core/src/main/java/org/apache/accumulo/core/security/VisibilityParseException.java
- core/src/main/java/org/apache/accumulo/core/spi/cache/BlockCache.java
- core/src/main/java/org/apache/accumulo/core/spi/common/ServiceEnvironment.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/CompactorGroupId.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/GroupManager.java
- core/src/main/java/org/apache/accumulo/core/spi/compaction/RatioBasedCompactionPlanner.java
- core/src/main/java/org/apache/accumulo/core/spi/ondemand/OnDemandTabletUnloader.java
- server/base/src/main/java/org/apache/accumulo/server/AccumuloDataVersion.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableExport/ExportTable.java
- server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/PopulateMetadataTable.java
- test/src/main/java/org/apache/accumulo/test/ImportExportIT.java
- test/src/main/java/org/apache/accumulo/test/ZombieScanIT.java
- test/src/main/java/org/apache/accumulo/test/functional/ScannerIT.java
Cleans up references to 3.1 which are no longer applicable since 3.1 has since been dropped.
Closes #5452
> Cleans up references to 3.1

- server/manager/src/main/java/org/apache/accumulo/manager/Manager.java
Three messages are logged every 10s during the Manager shut down process while the Manager is in safe mode. This change uses the DeduplicatingLogger to suppress duplicate messages so that they are only logged once every minute.
Closes #5647
> Slow down assigned tablet logging during Manager shut down

- server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/CompactionCoordinator.java
The coordinator was making RPCs to tservers w/ no timeout set on the TCP connection. This could cause the coordinator to get stuck indefinitely on problematic tservers causing external compactions to stop.  Added a timeout to the connection.  Also modified the thread name to include the tserver when making a RPC.  Also made the coordinator more aggressive when it does see a tserver RPC error, made it clear all summary info related to that tserver instead of a subset.  This more aggresive clearing is meant to minimize threads going to a problem tserver.
> adds time outs to coordinator tserver RPCs

- test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java
testProgressViaMetrics() was looking for metrics from compactor that the tablet server could also emit when it did a minor compaction.  Sometimes the test would see these tserver metrics and it would cause the test to fail.  Modified the test to only consider compactor metrics.
> fixes flaky test in ExternalCompactionProgressIT

- test/src/main/java/org/apache/accumulo/test/fate/FatePoolsWatcherITBase.java
* removed the pattern that checked that all asserts happened. it was redundant and masked details about the actual failure
* added a timeout to the latch to avoid infinite waiting
> FatePoolsWatcherITBase - changes to improve debugging failures

- core/src/main/java/org/apache/accumulo/core/spi/compaction/RatioBasedCompactionPlanner.java
- server/base/src/main/java/org/apache/accumulo/server/util/UpgradeUtil.java
- server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java
> Added compaction service configuration validate to upgrade --start

- test/src/main/java/org/apache/accumulo/test/fate/FatePoolsWatcherITBase.java
For FatePoolsWatcherITBase made static sets immutable and logged exceptions that may be lost.
> improves FatePoolsWatcherITBase

- pom.xml
> Added "NEW" page in generated javadoc

- core/src/main/java/org/apache/accumulo/core/conf/Property.java
- core/src/test/java/org/apache/accumulo/core/conf/PropertyTest.java
Removed experimental annotations on Compactor properties and a few others.
> Removed experimental annotations on some Property values

- core/src/main/java/org/apache/accumulo/core/conf/PropertyType.java
Updates descriptions for FATE config in PropertyType. These appear on the server-properties page on the Accumulo website.
> Minor follow on to FATE config changes #5861

- pom.xml
- src/build/eclipse-codestyle.xml
* Update configuration file with new properties
> Update formatter-maven-plugin to 2.29.0

- server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java
As follow-up from #5908, remove some additional unneeded methods.
> Remove unneeded TableConfiguration methods

- test/src/main/java/org/apache/accumulo/test/VolumeChooserIT.java
> fixes verification of walog location in VolumeChooserIT

- core/src/main/java/org/apache/accumulo/core/client/MutationsRejectedException.java
- test/src/main/java/org/apache/accumulo/test/functional/ConstraintIT.java
> adds constraint class name to error message

- core/src/test/java/org/apache/accumulo/core/file/rfile/bcfile/CompressionTest.java
> Fixed compression test
